include/sway/debug.h
include/sway/server.h
sway/debug-tree.c
sway/desktop/render.c
sway/desktop/transaction.c
sway/main.c
sway/server.c

This makes all debug options stored in a single struct rather than in various places, changes/fixes the behaviour of existing options, and introduces some new options.
* Fixes damage issues with `-Drender-tree` texture (by removing scissor)
* Offsets the render tree overlay's `y` position for those who have swaybar at the top
* Replaces `-Ddamage=rerender` with `-Dnodamage`
* Replaces `-Ddamage=highlight` with `-Dhighlight-damage`
* Replaces `-Dtxn-debug` with `-Dtxn-wait`
* Introduces `-Dnoatomic`
* Removes the `create_time` and `ms_arranging` figures from transactions and the log message. Transactions are created after arranging and the create time is of no significance.
* Fixes `-Dtxn-debug` (now `-Dtxn-wait`) not working.

Standardise debug variables

---

sway/desktop/transaction.c

We were removing the saved buffer when one transaction applies, then didn't have a new buffer to save when the next transaction ran. This made the rendering code crash as it had no surface to use.
This commit makes it continue to hold the buffer if the view is destroying and has more transactions. Additionally, a check is added when saving the buffer to make sure there's no one already there.
To test, kill a view while doing an aggressive resize motion.

Fix crash when a view destroys with pending transactions

---

include/sway/tree/container.h
include/sway/tree/view.h
sway/commands/move.c
sway/desktop/transaction.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/view.c

Previously we used a reparent event to detect when a view changes parent, then sent an output enter/leave to the surfaces if needed. This worked for tiling views but not floating views, as floating views can intersect another output without changing parent.
The solution implemented for floating views also applies cleanly to tiling views, so the previous method has been completely replaced and the reparent event has been removed.
This introduces a new function `container_discover_outputs`. This function compares the container's `current` position to the outputs, sends enter and leave events as needed, and keeps track of which outputs it's intersecting in a new `container->outputs` list. If it has entered a new output with a different scale then the title and marks textures will also be …

Send enter/leave events for floating views

---

sway/tree/view.c

Fixes #2490.
To be honest I'm not sure why this fixes the issue.
I observed that I could only make the view jump if I resized it to the smallest possible size first. Then I had a suspicion that we were accidentally factoring in the title and border sizes into the view size when it uses CSD. So I changed that and it appears to have fixed the jumping issue.
I guess when we factor the title and borders in, we send a configure to the surface with a size smaller than the minimum, and it comes back with a surface at the minimum size. We interpret this as an unexpected resize, and this somehow makes it jump.

Fix jumping views

---

include/sway/tree/layout.h
sway/commands/resize.c
sway/input/seat.c
sway/tree/layout.c

No need to have two resize edge enums.

Replace enum resize_edge with wlr_edges

---

sway/ipc-json.c

This makes it much easier (possible at all?) to get ahold of the values you need to create criteria for both Wayland and X clients. Wayland clients will have a null `class`, X clients will have a null `app_id`. Tested both to make sure nothing exploded when serializing the opposite.

Add app_id and class to get_tree output

---

include/sway/output.h
include/sway/tree/container.h
include/sway/tree/root.h
include/sway/tree/view.h
include/sway/tree/workspace.h
sway/commands/move.c
sway/config/output.c
sway/desktop/output.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/seat.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/output.c
sway/tree/root.c
sway/tree/view.c
sway/tree/workspace.c

This changes the destroy functions to the following:
* `output_begin_destroy`
* `output_destroy`
* `workspace_begin_destroy`
* `workspace_destroy`
* `container_begin_destroy`
* `container_destroy`
* `view_begin_destroy`
* `view_destroy`
The terminology was `destroy` and `free`, and it has been changed to `begin_destroy` and `destroy` respectively.
When the last output is disconnected, its workspaces will now be stashed in the root. Upon connection of a new output they will be restored.
There is a new function `workspace_consider_destroy` which decides whether the given workspace should be destroyed or not (ie. empty and not visible).
Calling `container_begin_destroy` will no longer automatically reap the parents. In some places we want to reap the parents and in some we don't, so this is …

Refactor destroy functions and save workspaces when there's no outputs

---

include/sway/tree/root.h
sway/config/output.c
sway/desktop/output.c
sway/ipc-server.c
sway/tree/root.c

This list includes disabled outputs.
When `sway_container` is demoted, we'll need to store the root's children (ie. enabled outputs) in the `sway_root`. It makes sense to put these in a list called `outputs`, so I'm renaming the existing list in advance.

Rename sway_root.outputs to sway_root.all_outputs

---

sway/tree/container.c

A small fix to an annoying problem I had with the ipc, whereby when I closed a window, it would send out a focus event on the newly-focused container before sending out the close event for the old container. Unless I'm misunderstanding the problem, this should fix that.
Also removed the TODO on container_create_notify, since I think all cases have been covered.

Emit window close event earlier, before destroying

---

sway/tree/output.c

#2499 accidentally removed the check for empty workspaces when moving workspaces on output disconnect/disable. This caused empty workspaces to also be moved. This PR adds the check back in.

Destroy empty workspaces in output_evacuate

---

sway/tree/arrange.c

When moving a floating view/container to a new output using the mouse, the floating view/container would snap back to the center of the original output as soon as the center point crossed over.
This PR skips the `container_floating_move_to_center` call in `arrange_workspace` when the container is being operated on by the current seat. This makes it so the floater does not snap to the center of any workspace while being moved.

Stop floaters from snapping on move to new output

---

include/sway/tree/arrange.h
sway/commands/layout.c
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/tree/arrange.c
sway/tree/container.c
sway/tree/root.c
sway/tree/view.c
sway/tree/workspace.c

This commit changes the arrange code in a way that will support type safe arguments.
The `arrange_output` et al functions are now public, however I opted not to use them directly yet. I've kept the generic `arrange_windows` there for convenience until type safety is fully implemented. This means this patch has much less risk of breaking things as it would otherwise.
To be type safe, `arrange_children_of` cannot exist in its previous form because the thing passed to it could be either a workspace or a container. So it's now renamed to `arrange_children` and accepts a `list_t`, as well as the parent layout and parent's box.
There was some code which checked the grandparent's layout to see if it was tabbed or stacked and adjusted the Y offset of the grandchild accordingly. Accessing the …

Prepare arrange code for type safe arguments

---

sway/desktop/transaction.c

When collecting focus to save into the transaction state, the workspace needs to look in the tiling list only.
As `seat_get_focus_inactive_tiling` returns any descendant, the list also needs to be traversed back up to the direct child of the workspace.
Fixes #2532

Fix workspace tabs

---

sway/tree/container.c

It wasn't returning the surviving container.
To reproduce, open a terminal in a workspace with no siblings, run `sleep 2 && exit` then switch to another workspace during the sleep.

Fix crash when reaping a workspace

---

sway/desktop/transaction.c

Fixes this comment: https://github.com/swaywm/sway/pull/2533#issuecomment-416820583
The `C_CONTAINER` check needs to apply to `C_VIEW` as well.

Fix rendering of nested tabs

---

sway/commands/exec_always.c

The way I implemented it before was really a stop-gap measure, furthermore, there was a bug since it was comparing `argc > 0` rather than `argc > 1` so even fully-quoted commands were rejected.
Now, it allows partially-quoted commands, but does not strip quotes and split the command, only if it is fully quoted.

commands: fix exec quoting

---

sway/desktop/layer_shell.c
sway/input/seat.c

This moves the `arrange_windows` call into the `arrange_layers` function, where we know the output actually needs to be arranged.
Additionally, we shouldn't set focus to the parent of an unknown container type, because the parent may be an output and this causes a crash because outputs can't have direct focus.
Fixes #2543

Don't send never-ending transactions when a focused layer surface commits

---

sway/commands.c
sway/commands/border.c

May as well make it as easy as possible for users who are coming from i3.
This also changes the `border` command to accept a thickness when setting the border to normal. This makes it work the same way as the `default_border` command. Eg. `border normal 5`

Implement deprecated new_window and new_float commands

---

common/stringop.c
include/stringop.h
sway/commands/bind.c

If sway is reloaded using a bindsym which has multiple commands, it failed to detect the reload command, didn't create a duplicate of the binding and would crash because the reload command frees the bindings.
For example:
mode system {
bindsym r reload, mode default
}
In this example, the `binding->command` is "reload, mode default".
Fixes #2545

Fix crash on reload

---

include/sway/commands.h
include/sway/config.h
include/sway/tree/view.h
sway/commands.c
sway/commands/focus_on_window_activation.c
sway/desktop/xwayland.c
sway/meson.build
sway/tree/view.c

Depends on https://github.com/swaywm/wlroots/pull/1223
i3 docs: https://i3wm.org/docs/userguide.html#focus_on_window_activation
To test, I opened Firefox along with a terminal and ran `firefox http://github.com` from the terminal.

Implement focus_on_window_activation

---

sway/desktop/render.c

This fixes a crash I got when opening GIMP on an empty workspace, though I'm not sure why it's required.
Also, if this check is required, should it be `children->length == 0 ||` as it is here, or should it be changed to `children->length > 0 &&` (i.e. the opposite)?

Fix crash when a splash screen opens on an empty workspace

---

include/sway/tree/view.h
sway/criteria.c
sway/desktop/xwayland.c

Depends on https://github.com/swaywm/wlroots/pull/1226
This is the last of the criteria tokens.
To test, I put this in my config then launched Firefox:
for_window [window_role="browser"] title_format "%title lolz"

Implement window_role criteria token

---

swaybar/render.c

When a block is padded/offset to uphold `min_width`, the background colour is now applied to the whole block rather than just the original width before padding. This brings the behaviour in-line with i3bar.
Related issue: https://github.com/greshake/i3status-rust/issues/155

Fix swaybar block background fill logic

---

sway/config/output.c
sway/tree/output.c

Fixes #2557 
This PR:
- Calls `wlr_output_enable(wlr_output, false)` when disabling an output.
- Calls `wlr_output_enable(wlr_output, true)` when (re-)enabling an output **_if_** DPMS is not set to `DPMS_OFF`
I also refactored `apply_output_config` to:
- ~Take in a `struct sway_output` instead of `struct sway_container`~ (Taken care of by typesafety)
- Handle (re-)enabling the output instead of having it done before in `apply_output_config_to_outputs`
- ~This also required setting `sway_output->swayc` in `output_create` instead of `output_enable` to avoid an infinite loop~ (No longer needed with typesafety)
Since typesafety accidentally reverted part of #2553, I also removed the modeset from `output_create`.

Call wlr_output_enable on enable/disable if needed

---

sway/input/seat.c

We weren't calling `seat_send_focus`. I think this was previously called by `seat_set_focus_warp`.
Fixes #2534.

Restore focus correctly when closing a fullscreen view

---

sway/tree/arrange.c
sway/tree/view.c

Prior to f5b9815128b6c000bb5d47c339480fa481a5e99d, children of tabbed and stacked containers would have their container size and position set to the same as the tabbed/stacked container. Normally this would be a problem for a layout such as `T[V[view]]`, but there was some code in the
arrange functions which would check if the grandparent of the view was a tabbed or stacked container and would offset the view's Y accordingly.
Commit f5b9815128b6c000bb5d47c339480fa481a5e99d changed the box to exclude the titlebar for all tabbed/stacked children so that the grandparent check could be removed. But this meant the title was not covered in the container and wasn't damaged when the child changed its title.
This patch changes it so that a child of a tabbed/stacked container will have its box …

Adjust container box

---

include/log.h

This is a non-standard extension as well as completely useless in C.
__func__ is the standard way of doing this.

Remove __PRETTY_FUNCTION__

---

sway/desktop/render.c

Suppose the following:
* Transactions are already in progress - say transaction A.
* View A maps, which creates transaction B and appends it to the transaction queue.
* View B maps, which creates transaction C and appends it to the queue.
* View A unmaps, which creates transaction D and appends it to the queue.
* Transaction A completes, so transaction B attempts to save View A's buffer, but this doesn't exist so it saves nothing.
* Rendering code attempts to render View A, but there is no saved buffer nor live buffer that it can use.
Rather than implement an elaborate solution for a rare circumstance, I've take the safe option of just not rendering anything for that view. It means that if you reproduce the scenario above, you might get the title and borders rendered but no surface.
Fixes …

Fix crash when views rapidly map and unmap

---

sway/commands/move.c

It was incorrectly determining that the container being moved and the destination had the same parent, which resulted in tree corruption. Both parents can be `NULL` but the containers may belong to different
workspaces.
To reproduce, create layout `H[V[view] view]` in one workspace then move a view left or right from another output into that workspace.
Fixes #2581.

Fix crash when moving view across outputs

---

sway/commands/focus.c

* Fullscreen a view
* Run `focus <direction>` where there is no output in that direction
The output returned was rightfully `NULL`, which needs to be handled.
Fixes #2584.

Fix crash when focusing from fullscreen in an invalid direction

---

sway/commands/layout.c

The `argc` and `argv` used in this function are the same ones used by the layout command itself.

Fix crash when running "layout toggle"

---

sway/commands/bind.c
sway/input/keyboard.c

`seat_execute_command` needs to check the flags on `binding_copy`, as `binding` will be a dangling pointer after a reload command.
`handle_keyboard_key` needs to set the `next_repeat_binding` for non-reloads prior to executing the command in case the binding is freed by the reload command.

Fix management of bindings during reload

---

sway/desktop/render.c

When rendering, the workspace for the output needs to be retrieved from the output's `current` state. `output_get_active_workspace` returns the pending workspace, which crashes if the pending workspace is new and hasn't completed a transaction yet.
Fixes #2588.

Fix crash when switching to new workspace during transaction

---

include/sway/input/seat.h
sway/commands/floating.c
sway/commands/focus.c
sway/commands/fullscreen.c
sway/commands/move.c
sway/commands/swap.c
sway/input/cursor.c
sway/input/seat.c
sway/tree/container.c
sway/tree/output.c
sway/tree/view.c
sway/tree/workspace.c

These are the same as `seat_set_focus`, but accept a specific type rather than using nodes. Doing this adds more typesafety and lets us avoid using `&con->node` which looks a little ugly.
This fixes a crash that pretty much nobody would ever come across. If you have a bindsym for `focus` with no arguments and run it from an empty workspace, sway would crash because it assumes `container` is not `NULL` (fixed in `focus.c`).

Introduce seat_set_focus_container and seat_set_focus_workspace

---

sway/tree/container.c

To reproduce the problem this is fixing, create `H[view view view]`, fullscreen one of the views and close it. The entire workspace will be given focus rather than one of the siblings.
This happens because we emit the `destroy` event, so the seat code tries to find a new focus, but the view it finds is still believed to be hidden by the fullscreen view so it's discarded and the workspace is used instead.
This clears the workspace's fullscreen pointer prior to emitting the destroy event so that the seat code finds an appropriate new focus.

Second attempt at restoring focus when closing a fullscreen view

---

sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c

This fixes pinentry-gtk-2, but might make other views floating which would otherwise be tiled. This patch is more of a trial which could end up becoming a permanent fix.
Fixes #2181.

Float views when min == max on either dimension

---

sway/input/seat.c

The output also needs to be made dirty when focusing a new output.
Fixes #2599.

Fix workspace switching

---

sway/desktop/output.c
sway/input/cursor.c
sway/input/seat.c

* Use surface `sx` and `sy` instead of `wlr_drag_icon` fields which have been removed
* End `DOWN` mouse operation when dragging
Test plan: `weston-dnd`

Fix drag-and-drop

---

sway/commands/seat.c

Fixes crash when running `seat <seat>` without a sub-command.

 commands: prevent running empty seat command

---

sway/desktop/layer_shell.c

Sway crashed with this backtrace when I was afk.
```
0  0x0000556e7e904ec7 in handle_layer_shell_surface (listener=0x556e7e956aa8 <server+104>, data=0x556e7f316490) at ../../sway/desktop/layer_shell.c:340
#1  0x00007f7d8a0fb636 in wlr_signal_emit_safe (signal=0x556e7ed80c60, data=0x556e7f316490)
at ../../util/signal.c:29
#2  0x00007f7d8a0e4b3c in layer_surface_role_commit (wlr_surface=0x556e7f316190)
at ../../types/wlr_layer_shell.c:293
#3  0x00007f7d8a0ef4db in surface_commit_pending (surface=0x556e7f316190)
at ../../types/wlr_surface.c:398
#4  0x00007f7d8a0ef742 in surface_commit (client=0x556e7f13ca10, resource=0x556e7f1b5c10)
at ../../types/wlr_surface.c:470
#5  0x00007f7d885aa1c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#6  0x00007f7d885a9c2a in ffi_call () at …
```

handle_layer_shell_surface: Do not crash if seat doesn't have focus

---

sway/commands/focus.c
sway/tree/container.c
sway/tree/view.c
sway/tree/workspace.c

Fixes #2401 (aka #2558)
Based on feedback on #2612
Previously, when switching windows, pointer focus was not changed until the pointer was moved. This makes the pointer enter happen immediately, without the side effects of other attempted fixes.

Give windows pointer focus immediately

---

sway/tree/view.c

Tries to fix #2619
@linkmauve I failed to reproduce, but the code is wrong so I tried to fix it. Can you confirm this fix works?

Don't use handler_context in view_unmap

---

include/swaybar/status_line.h
swaybar/i3bar.c
swaybar/render.c
swaybar/status_line.c

This prevents blocks from being destroyed before their hotspots are destroyed,
in case it is used for a pending click event that fires between the bar
receiving a new status, which destroys the block, and the bar rendering the new
status, which destroys the hotspot.
This problem can be easily produced by
scrolling on a block that immediately causes a new status to be sent, with
multiple outputs.
Whether this is the best way to fix this problem I'm not sure.

i3bar: count references to blocks

---

sway/commands/move.c

The assertion can be (rightfully) triggered by creating layout `V[H[view view] view]` and moving the top right view to the right.
After removing the assertion I found the container being moved needs its size reset to prevent it from being sized wrongly after arranging.

Remove bad assertion in workspace_rejigger

---

sway/commands/output/background.c
sway/config/output.c

Fixes #654 
`wordexp` splits the file path into multiple words if there are spaces. In `master`, only the first word is used. This caused `foo bar` to be truncated to just `foo`. Additionally, the path given to `swaybg` is not escaped in anyway and `wordexp` strips any backslash escaped spaces.
This first commit of this PR joins the words from `wordexp` together and encloses the path given to `swaybg` in quotes. This works well if there are not consecutive spaces in the file path or if consecutive spaces are backslash escaped.
The second commit of this PR will detect non-escaped consecutive spaces and escape them for the user. This allows for the path to be enclosed in quotes.
With both commits, the following methods for supplying the path should be working regardless the number of …

Allow spaces in background file path

---

sway/tree/view.c

Since the container is already assigned in ~`view_create`~ ~`view_init`~ `view_map`.
Seems to work, hope I'm not missing something.

Remove redundant container creation in view initialisation

---

sway/tree/container.c

* Create layout `T[view view]`
* Move the cursor into the title bar area
* Close both views
Sway would crash because `container_at_tabbed` would attempt to divide by zero when there are no children.
The children check isn't needed for `container_at_stacked` because it doesn't divide anything by the number of children.
Fixes #2636.

Fix crash when unmapping last child of a tabbed workspace

---

sway/commands/move.c

To reproduce issue:
1. Set an empty workspace to be tabbed
1. Open two windows
1. H split one
1. Open three windows, your tree should now be:
````
Tabbed {
Window,
Tiled {
Window,
Window,
Window
}
}
````
1. Move one of the inner windows down
1. Segfault
Stack trace: 
```
Thread 1 "sway" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1fe39c0 (LWP 15042)]
0x000055555559b63f in container_split (child=0x0, layout=L_VERT)
at ../sway/tree/container.c:1168
1168		cont->width = child->width;
(gdb) bt
#0  0x000055555559b63f in container_split (child=0x0, layout=L_VERT)
at ../sway/tree/container.c:1168
#1  0x000055555558a470 in move_out_of_tabs_stacks
(container=0x555555ab80f0, current=0x555555aab710, move_dir=MOVE_DOWN, offs=1)
at ../sway/commands/move.c:294
#2 …
```

Fix crash moving out of tab container

---

common/readline.c
include/swaybar/event_loop.h
include/swaybar/status_line.h
swaybar/event_loop.c
swaybar/i3bar.c
swaybar/render.c
swaybar/status_line.c

Should fix #2177
This replaces the somewhat dodgy old implementation with something a bit more sensible, I think.
Both protocols now properly handle long and multiple statuses. The old i3bar handling also allowed dodgy JSON to be sent, as long as it starts with a valid array, which this fixes.
I've tried it with many different status commands, but I may have missed something so please test if you have anything unconventional. Might also want to test performance as well, seems fine but I haven't tested it thoroughly.
~One annoying thing is that since everything works in the one buffer, it is not trivial to print received JSON for debugging (since we cannot simply add a null-terminator). Ideas for adding it back in:~
~1. copy the string each time a valid array is encountered, then print it …

Overhaul swaybar protocol handling (+fixes)

---

sway/config/input.c

Fixes memory leaks, since they are duplicated from the command to the config, then duplicated again when merged, but only freed once.

config: free strings fields when freeing input config

---

sway/commands.c

This happens because I have [a daemon](https://github.com/emersion/kanshi) executing commands on hotplug (changing output configuration). I think there's a state in which there's no output and my daemon sends commands. Sway crashes with:
```
#0  0x000055d0dd0d7a11 in set_config_node (node=0x0) at ../sway/commands.c:218
#1  0x000055d0dd0d77aa in execute_command (_exec=0x55d0dd5b0100 "output LVDS-1 enable position 0,0 resolution 1600x900 scale 1", seat=0x55d0dd93bbf0) at ../sway/commands.c:317
#2  0x000055d0dd0e1201 in ipc_client_handle_command (client=0x55d0ddc32090) at ../sway/ipc-server.c:583
#3  0x000055d0dd0e0e53 in ipc_client_handle_readable (client_fd=54, mask=1, data=0x55d0ddc32090) at ../sway/ipc-server.c:261
#4  0x00007f0da3791702 in wl_event_loop_dispatch () at …
```

Fix segfault when executing command without focus

---

sway/commands/create_output.c

Tested:
- built sway against wlroots built with -Dx11-backend=enabled, ran WLR_BACKENDS=x11 sway, confirmed create_output still works
- built sway against wlroots built with -Dx11-backend=disabled, ran it (wayland backend), confirmed create_output still works
The error message still mentions "X11 backend" even if built without support for one, hopefully that's ok for a developer command.

Fix compilation against wlroots without X11 backend

---

swaybar/status_line.c

This prevents an signed-to-unsigned conversion error on buffer_index if
getdelim fails and returns -1, which caused swaybar to try to search the
header for the array and immediately failing

swaybar: explicitly check return value of getdelim

---

sway/tree/root.c

`root_for_each_container` and `root_find_container` were using incorrect logic to determine if a container was hidden in the scratchpad. Containers will have a `NULL` parent if they are a direct child of a workspace. Containers will have a `NULL` workspace if they are hidden in the scratchpad.
The incorrect check meant that `root_for_each_container` would run the callback on scratchpad containers twice. This meant that executing a command such as `[class="$something"] scratchpad show` would cause the command to run twice, resulting in the container being shown and hidden again which is effectively a no op.
Fixes #2655.

Fix double iteration of scratchpad containers

---

common/cairo.c
include/cairo.h
include/swaybar/bar.h
include/swaylock/swaylock.h
sway/tree/container.c
swaybar/bar.c
swaybar/render.c
swaylock/main.c
swaylock/render.c

Set cairo font options to render text and lines with subpixel hinting (if available).
I've been running sway with this patch for several months and I prefer it.

Render fonts slightly nicer 

---

common/pango.c

Call pango_cairo_context_set_font_options() before pango_cairo_update_layout() and pango_cairo_show_layout(). It looks like Pango defaults to merging the Cario font options with its own defaults, and the end result is no full hinting.
Comparison: ![comparison](https://i.imgur.com/CXNF701.png)
Master is on top and this PR is on bottom.
Notice the difference in smaller characters such as `°` and `%`. Also the top left of the `?` has a little more down curl (more accurate question mark shape). And the text is a little higher contrast.
The improvements are minor, but they're improvements.
You can see another example of pango+cairo usage in Chromium: https://chromium.googlesource.com/chromium/chromium/+/master/ui/gfx/pango_util.cc#197

Call pango_cairo_context_set_font_options().

---

include/sway/commands.h
sway/commands.c
sway/commands/bind.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/ipc-server.c
sway/main.c
sway/tree/view.c

This adds a `con` argument to `execute_command` which allows you to specify the container to execute the command on. In most cases it leaves it as `NULL` which makes it use the focused node. We only set it when executing `for_window` criteria such as when a view maps. This means we don't send unnecessary IPC focus events, and fixes a crash when the criteria command is `move scratchpad` (because we can't give focus to a hidden scratchpad container).
Each of the shell map handlers now check to see if the view has a workspace. It won't have a workspace if criteria has moved it to the scratchpad.
To test:
* `for_window [class="Firefox"] move scratchpad` and then launch Firefox
* Try other criteria commands
Fixes #2656.

Allow running commands on containers without focusing them

---

sway/input/cursor.c
sway/tree/container.c

Firstly, a change had to be made to the `container_at` functions. If you create layout `T[view H[view view]]` and hover the second tab, the `container_at` functions would return the `focus_inactive` child. They now return the split container itself. To compensate for this, `dispatch_cursor_button` has been adjusted to find the `focus_inactive` child before focusing it.
The actual implementation of wheel scrolling is pretty straightforward. This uses `handle_cursor_axis`, so I took a similar approach to `handle_cursor_button` (ie. creating a `dispatch_cursor_axis` function).
To test, create a tabbed or stacked layout, hover the title bar and scroll with the wheel.
Closes #2684.

Implement tab cycling using mouse wheel

---

sway/tree/arrange.c
sway/tree/workspace.c

If you have swaybar docked to the top, and you create a floating sticky container and switch workspaces on the same output, the sticky container would move down by the height of swaybar on each switch.
This happens because when creating the workspace we set the dimensions to the same as the output, then the subsequent arrange corrects it. During this arrange, floating containers are translated so they stay relative to the workspace. This translation needs to not occur for the initial arrange.
This patch makes workspaces have a zero width and height when first created, so we can detect whether this is the initial arrange and avoid translating the floating containers if so.

Prevent sticky containers from jumping on workspace switch

---

common/background-image.c
swaybg/main.c

Fixes #2667 
render_background_image alters the scale that cairo uses. Depending on the image mode, resolution, and image size, this may cause the surface to be rendered increasingly smaller. By calling cairo_save and
cairo_restore, any changes to the cairo settings by the function are not kept as a side effect.
The surface that swaybg uses is also now cleared before rendering a frame. This is needed to avoid artifacts  with certain combinations of image modes, resolutions, and image sizes. This was also part of the increasingly smaller background visual since it made it so it was not obvious the region being rendered to was smaller and caused an increasing number of smaller images to be appear for each hotplug.

swaybg: fix increasingly smaller bg on hotplug

---

include/sway/config.h
sway/commands.c
sway/commands/input.c
sway/commands/input/accel_profile.c
sway/commands/input/click_method.c
sway/commands/input/drag_lock.c
sway/commands/input/dwt.c
sway/commands/input/events.c
sway/commands/input/left_handed.c
sway/commands/input/map_from_region.c
sway/commands/input/map_to_output.c
sway/commands/input/middle_emulation.c
sway/commands/input/natural_scroll.c
sway/commands/input/pointer_accel.c
sway/commands/input/repeat_delay.c
sway/commands/input/repeat_rate.c
sway/commands/input/scroll_button.c
sway/commands/input/scroll_method.c
sway/commands/input/tap.c
sway/commands/input/tap_button_map.c
sway/commands/input/xkb_capslock.c
sway/commands/input/xkb_layout.c
sway/commands/input/xkb_model.c
sway/commands/input/xkb_numlock.c
sway/commands/input/xkb_options.c
sway/commands/input/xkb_rules.c
sway/commands/input/xkb_variant.c
sway/config/input.c
sway/input/input-manager.c

Closes #2662 
Implements support for`input *`. The code is structured similar to the way `output *` is currently implemented.
This required restructuring the input subcommand handlers. Instead of creating a new input config and applying it in each subcommand, the one created by the main input command is used and the input config is stored/merged and applied after returning from the subcommand.

Implement support for input wildcard

---

sway/tree/container.c

If the output being disconnected contains views, and the views are being relocated to another output of a different size, a transaction must occur to reconfigure them. This means by the time `container_discover_outputs` is called, the output is already disabled and `wlr_output` is `NULL`.
I considered making it check `output->wlr_output`, but `output->enabled` should work just as well and is more descriptive.
Untested on DRM. Someone please test this on DRM before merging.
Fixes #2705.

Fix crash when disconnecting output

---

sway/input/cursor.c

Trying to move the About window in Android Studio causes a crash without this check.

Add a missing null check for moving tiling containers

---

sway/tree/container.c

When a view unmaps, we start a transaction to destroy the container, then when the transaction completes we destroy the container and unset the view's container pointer. But if the view has remapped in the meantime, the view's container pointer will be pointing to a different container which should not be cleared.
This adds a check to make sure the view is still pointing to the container being destroyed before clearing the pointer. The freeing of the title format is also removed as it is already freed when the view destroys in `view_destroy`.
Fixes #2710.

Fix race condition crash when view unmaps + maps quickly

---

meson.build
sway/ipc-server.c

This PR will add the `_C11_SOURCE` feature macro to meson.build on FreeBSD, thus narrows down the default namespace set (POSIX 2008 + XSI extensions, C11 + EXT1 extensions, BSD specific stuff) to only the C11 standard. This fixes #2616, and also prevents any future name clashes with FreeBSD-specific symbols.
This change would require to either define `__BSD_VISIBLE` or undefine `_C11_SOURCE` on sway/ipc-server.c because of the non-standatd `SOCK_NONBLOCK` and `SOCK_CLOEXEC` flags. I have replaced the usage of these flags with two `fcntl` calls instead, which makes the file POSIX 2001 compliant.

Use _C11_SOURCE feature test macro on FreeBSD (fixes #2616)

---

sway/input/input-manager.c

This allows, for example, setting left handed mode for tablets.

input: enable configuring tablets with libinput

---

sway/tree/view.c

`view_is_visible` would return false, which meant the view wouldn't receive a frame done event. `view_is_visible` needs to make an exception for floating containers.
This also moves the `workspace_is_visible` check to an earlier location for performance reasons.
Fixes #2659.

Fix floating views in tabbed/stacked workspaces not getting frame events

---

include/swaylock/swaylock.h
meson.build
swaylock/main.c
swaylock/meson.build
swaylock/pam.c
swaylock/password.c
swaylock/shadow.c

This involves setuid'ing swaylock, which then forks and drops perms on
the parent process. The child process remains root and listens on a pipe
for requests to validate passwords against /etc/shadow.

Add support for building swaylock without PAM

---

include/sway/config.h
include/sway/tree/workspace.h
sway/commands/workspace.c
sway/config.c
sway/tree/workspace.c

When we eventually implement `workspace <ws> gaps inner|outer <px>`, we'll need to store the gaps settings for workspaces before they're created. Rather than create a `workspace_gaps` struct, the approach I'm taking is to rename `workspace_outputs` to `workspace_configs` and then add gaps settings to that.
I've added a lookup function `workspace_find_config`. Note that we have a similar thing for outputs (`output_config` struct and `output_find_config`).
Lastly, when freeing config it would create a memory leak by freeing the list items but not the workspace or output names inside them. This has been rectified using a `free_workspace_config` function.

Rename workspace_outputs to workspace_configs and fix memory leak

---

sway/sway-bar.5.scd
sway/sway-input.5.scd
sway/sway.5.scd

Apparently, I forgot to update the man pages for a couple of my PRs. This PR updates the man pages to
- Move `set` to the section of commands that can be in the config file or at runtime
- Mention `$$` in the `set` command description
- Add a section on generic command blocks
- Alter commands and descriptions for previous block only commands (`bar`, `input`, `mode`, `seat`) to make it so it does not say that blocks are required

Update man pages - dynamic vars and generic blocks

---

sway/input/cursor.c
sway/input/seat.c

Fixes https://github.com/swaywm/sway/issues/1568
The implementation works, idk if it's any good though. Also haven't dealt with tablet pads because I don't have one.
Possible FR: some sort of seat sub-command `show_cursor yes|no|auto`

Only show cursor if pointer configured

---

sway/tree/root.c

When the last output is disconnected, `output_disable` is called like usual and evacuates the output to the `root->saved_workspaces` list. It then calls `root_for_each_container` to remove (untrack) the output from each container's outputs list. However, `root_for_each_container` did not iterate the saved workspaces, so when the output gets freed the containers would have a dangling pointer in their outputs list. Upon reconnect, `container_discover_outputs` would attempt to use the dangling pointer, causing a crash.
This makes `root_for_each_container` check the saved workspaces list, which fixes the problem. It also adds it to `root_find_container` for good measure.

Fix hotplugging down to zero outputs

---

include/sway/commands.h
include/sway/config.h
sway/commands/input.c
sway/commands/input/drag.c
sway/config/input.c
sway/input/input-manager.c
sway/meson.build
sway/sway-input.5.scd

Add functionality to disable tap-and-drag to sway-input with `drag disable`.

Add tap and drag to sway-input

---

sway/tree/container.c
sway/tree/output.c

When evacuating an output, sticky containers need to be moved to a different output. Currently, they are not moved since `workspace_is_empty` returns `true` when there are only sticky containers.
This PR adds an additional check after the `workspace_is_empty` call that checks whether there are `floating` containers. If there are, they must all be sticky. The sticky containers get moved to another output and the workspace gets destroyed as normal.

Move sticky containers in output_evacuate

---

include/sway/config.h
include/sway/tree/container.h
include/sway/tree/workspace.h
sway/commands/gaps.c
sway/commands/layout.c
sway/commands/workspace.c
sway/sway.5.scd
sway/tree/container.c
sway/tree/workspace.c

This changes our gaps implementation to behave like i3-gaps.
Our previous implementation allowed you to set gaps on a per container basis. This is no longer possible as it isn't supported by i3-gaps and doesn't seem to have a practical use case. The `gaps_outer` and `gaps_inner` properties on containers are now removed as they just read the `gaps_inner` from the workspace.
`gaps inner|outer <px>` no longer changes the gaps for all workspaces. It only sets defaults for new workspaces.
`gaps inner|outer current|workspace|all set|plus|minus <px>` is now runtime only, and the workspace option is now removed. `current` now sets gaps for the current workspace as opposed to the current container.
`workspace <ws> gaps inner|outer <px>` is now implemented. This sets defaults for a workspace.
This …

Make gaps implementation consistent with i3-gaps

---

meson.build
meson_options.txt
sway/main.c
sway/meson.build
swaybar/meson.build
swaybg/meson.build
swayidle/meson.build
swaylock/meson.build
swaymsg/meson.build
swaynag/meson.build

It's better to use DT_RPATH dynamic section of the elf binary to store
the paths of libraries to load instead of overwriting LD_LIBRARY_PATH
for the whole environment, causing surprises. This solution is much more
transparent and perfectly suitable for running contained installations
of wayland/wlroots/sway.
The code unsetting the LD_LIBRARY_PATH/LD_PRELOAD was also deleted as
it's a placebo security at best - we should trust the execution path
that leads us to running sway, and it's way too late to care about those
variables since we already started executing our compositor, thus we
would be compromised anyway.

Add support for installing binaries with DT_RPATH

---

sway/criteria.c

This makes the criteria parser recognize the "floating" token. From there on the criteria seems to be handled as expected.

Parse floating criteria

---

sway/commands.c

Leave quotes intact for `cmd_exec`, `cmd_exec_always`, `cmd_bindcode`, `cmd_bindsym`, and `cmd_set`.
`cmd_exec` and `cmd_exec_always` should not have any quotes stripped from them and should be passed to `exexcl` as is.
`cmd_bindcode` and `cmd_bindsym` will have their bound command processed by `execute_command`, which will strip quotes for everything except `cmd_exec`.
Fixes #2736
Fixes #2738

Do not strip quotes for exec or bind commands

---

include/sway/tree/view.h
sway/input/seat.c
sway/tree/container.c
sway/tree/view.c
sway/tree/workspace.c

Fixes #2653 
This PR should make it so `smart_gaps` works identical to how it does in `i3-gaps`.
Since `i3-gaps` does not allow for floating containers (only floating views), there is no behaviour to replicate. Currently, each floating container gets treated as a separate group and will apply gaps accordingly.

Fix smart gaps

---

include/sway/commands.h
include/sway/config.h
sway/commands.c
sway/commands/hide_edge_borders.c
sway/commands/smart_borders.c
sway/config.c
sway/meson.build
sway/sway.5.scd
sway/tree/view.c

Fixes `hide_edge_borders smart` when gaps are in use.
Implements `hide_edge_borders smart_no_gaps` and `smart_borders on|no_gaps|off`.
Since `smart_borders on` is equivalent to `hide_edge_borders smart` and `smart_borders no_gaps` is equivalent to `hide_edge_borders smart_no_gaps`, I opted to just save the last value set for `hide_edge_borders` and restore that on `smart_borders off`. This simplifies the conditions for setting the border.

Handle gap borders

---

include/sway/server.h
include/sway/tree/container.h
include/sway/tree/view.h
include/sway/xdg_decoration.h
sway/commands/border.c
sway/decoration.c
sway/desktop/render.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/ipc-json.c
sway/meson.build
sway/server.c
sway/tree/container.c
sway/tree/view.c
sway/xdg_decoration.c

This replaces `view.using_csd` with a new border mode: `B_CSD`. This also removes `sway_xdg_shell{_v6}_view.deco_mode` and `view->has_client_side_decorations` as we can now get these from the border.
You can use `border toggle` to cycle through the modes including CSD, or use `border csd` to set it directly. The client must support the xdg-decoration protocol, and the only client I know of that does is the example in wlroots.
If the client switches from SSD to CSD without us expecting it (via the server-decoration protocol), we stash the previous border type into `view.saved_border` so we can restore it if the client returns to SSD. I haven't found a way to test this though.
Closes #2429.

Add CSD to border modes

---

sway/input/cursor.c

* Click and hold a scrollbar
* Drag the cursor onto another surface
* While still holding the original button, press and release another cursor button
* Things get weird
There's two ways to fix this. Either cancel the seat operation and do the other click, or continue the seat operation and ignore the other click. I opted for the latter (ignoring the click) because it's easier to implement, and I suspect a second click during a seat operation is probably unintentional anyway.
Fixes #2756

Ignore unrelated cursor buttons while doing seat operations

---

sway/desktop/layer_shell.c
sway/input/seat.c

* Have multiple outputs
* Launch swaylock
* Unplug an output (possibly has to be the last "connected" one)
* The swaylock surface on the remaining output would not respond to key events
This was happening because when the output destroys, focus was not given to the other swaylock surface.
This patch makes focus be transferred to another layer surface owned by the same Wayland client, but only if input was inhibited by the surface being destroyed, and only if it's in the overlay layer. I figure it's best to be overly specific and relax the requirements later if needed.
This patch removes a check in `seat_set_focus_surface` which was preventing focus from being passed from a layer surface to any other surface. I don't know of a use case for this check, but it's possible that this change …

Give focus to another swaylock surface when output is disconnected

---

sway/input/seat.c

`container_flatten` removes the container from the tree (via `container_replace`) before destroying it. When destroying, the recent changes to `handle_seat_node_destroy` incorrectly assumes that the container has a parent.
This adds a check for destroying a container which is no longer in the tree. If this is the case, focus does not need to be changed.
To test, create layout `H[view T[view]]`, focus the tabbed view and run `move left`.
Fixes #2765

Fix crash when flattening container after moving

---

include/swaylock/swaylock.h
swaylock/main.c
swaylock/seat.c

* Lock the screen with swaylock
* Do something that triggers the seat to update its capabilities (unplug/replug the keyboard, switch TTYs, sleep/suspend...)
* Keys you then type into swaylock would be handled multiple times
This stores the keyboard and pointer in the swaylock state so they can be released when new capabilities are given.
I had to bump the seat version up to 3 because `wl_pointer_remove` isn't supported on anything earlier.

swaylock: Support keyboard and pointer disconnects and reconnects

---

sway/input/seat.c
sway/tree/workspace.c

* Create a view on workspace 1
* Switch to workspace 2 (on the same output) and create a floating sticky view
* Use criteria to focus the view on workspace 1
In master, the sticky container remains on workspace 2 and is not rendered. In this PR it is relocated to workspace 1. This is because the code that moves the sticky containers was in `workspace_switch` which is not called when using the above method. This patch relocates the sticky-moving code into `seat_set_focus_warp`.
A side effect of this patch is that if you have a sticky container focused and then switch workspaces, the sticky container will no longer be focused. It would previously retain focus. I think unfocusing is desirable though, as the user's intention is to focus whatever's on the workspace.
In `seat_set_focus_warp`, …

Move sticky containers when switching workspace via criteria

---

sway/ipc-json.c

Only just noticed this detail in i3:
> type (string)
>    Type of this container. Can be one of "root", "output", "con", "floating_con", "workspace" or "dockarea".

ipc: set "type" of floating containers to "floating_con"

---

swaybar/bar.c

To reproduce, suspend multiple times your computer and try using your mouse wheel on swaybar to switch between workspaces. It switches multiple times.
Fixes #2741

swaybar: fix binding to wl_pointer multiple times

---

swaynag/swaynag.c

When destroying swaynag from within wl_display_dispatch (e.g. destroy output), we cannot disconnect the display as that will free the queue's event_list.
Free it after running the loop instead.
Fixes this use-after-free:
```
==7312==ERROR: AddressSanitizer: heap-use-after-free on address 0x612000000110 at pc 0x000000412a9f bp 0x7ffd4e811760 sp 0x7ffd4e811750
READ of size 8 at 0x612000000110 thread T0
#0 0x412a9e in wl_list_empty ../common/list.c:206
#1 0x7f5b58f0d42f in dispatch_queue src/wayland-client.c:1572
#2 0x7f5b58f0d42f in wl_display_dispatch_queue_pending src/wayland-client.c:1815
#3 0x40f465 in swaynag_run ../swaynag/swaynag.c:390
#4 0x407576 in main ../swaynag/main.c:123
#5 0x7f5b58bb9412 in __libc_start_main ../csu/libc-start.c:308
#6 0x404a3d in _start …
```

swaynag: fix use-after-free in wl_display_dispatch

---

include/sway/config.h
sway/commands/bind.c
sway/commands/reload.c
sway/commands/seat/attach.c
sway/commands/seat/fallback.c
sway/config.c
sway/input/keyboard.c

This patch makes it so when you run `reload`, the actual reloading is deferred to the next time the event loop becomes idle. This avoids several use-after-frees and removes the workarounds we have to avoid them.
When you run `reload`, we validate the config before creating the idle event. This is so the reload command will still return an error if there are validation errors. To allow this, `load_main_config` has been adjusted so it doesn't apply the config if `validating` is true rather than applying it unconditionally.
This also fixes a memory leak in the reload command where if the config failed to load, the `bar_ids` list would not be freed.
To test:
* Change config and reload, verify new config applied
* Hold the binding for reload
* Introduce a validation error and reload your …

Reload config using idle event

---

config.in
sway/commands/bar.c
sway/commands/bar/status_command.c
sway/config/bar.c
sway/ipc-json.c
sway/sway-bar.5.scd
swaybar/bar.c

Sway sets a default `status_command` which runs `date` every second. This patch removes this behaviour so the user can have a `NULL` status bar if desired.
I had to swap swaybar's `event_loop_poll` and `wl_display_flush` so that it would map the initial surface.

swaybar: allow null status_command

---

sway/commands/opacity.c

Fixes https://github.com/swaywm/sway/issues/2792
Issuing an opacity command when there is no current container (for example issuing via `exec swaymsg "opacity 0.75"` from the config file) causes sway to crash. Now there is a NULL check which stops this from happening.

Check if there is a current container before setting its opacity

---

include/sway/tree/view.h
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/tree/view.c

The previous behaviour was to damage the entire view, which would recurse into each popup. This patch makes it damage only the popup's surface, and respect the surface damage given by the client.
This adds listeners to the popup's map and unmap events rather than doing the damage in the create and destroy functions. To get the popup's position relative to the view, a new `child_impl` function `get_root_coords` has been introduced, which traverses up the parents.
Fixes #2601

Only damage popups when popups have damage

---

include/sway/commands.h
sway/commands/resize.c

Returning a boolean from `container_resize_tiled` and `resize_tiled` doesn't work in all cases. This patch changes it back to void and does a before/after check to see if the container was resized.
See https://github.com/swaywm/sway/pull/2729#issuecomment-428155420

resize: Determine if anything changed using before/after check

---

sway/tree/view.c

In view_autoconfigure the height of the view is adjusted if the parent
container has a tabbed/stacked layout. Previously this height change
would also be applied to floating views, although it is not needed for
them.
To reproduce the problem:
1.  Open a floating window with a Sway titlebar (SSD).
2.  Change the workspace layout from split to tabbed/stacked.
3. In case of a tabbed workspace layout the height of the floating window
is reduced by the height of the titlebar.
4. In case of a stacked workspace layout the height of the floating window
is reduced by  (height of titlebar) * (number of floating windows on this
workspace). If there are more than one floating windows on the same
workspace, there is a visible gap between the titlebar and the content of
the floating window.

Fix undesirable height change of floating views

---

swaybar/main.c
swaymsg/main.c

When running `swaymsg -v`, the version returned is actually the version of swaymsg itself, yet the message displayed was `sway version <version>`. This can create confusion if users update sway and swaymsg but don't restart sway, then use swaymsg to check the version.
This patch changes the wording to be `swaymsg version <version>` instead, and likewise for swaybar.
To get the version of a running sway instance, users should run `swaymsg -t get_version`.

Fix program name in version strings

---

sway/input/cursor.c
sway/input/seat.c
sway/tree/container.c

* Set focus to a floating container when clicking its title bar.
* Raise floating when user clicks title bar or decorations (in the `seat_begin` functions).
* In `container_at`, it only returned a floating container if the user had clicked the surface. This makes it use `floating_container_at` instead.
I have tested using `focus_follows_mouse` and `raise_floating` and it seems to work correctly.
Fixes #2801.

Fix floating click events

---

include/sway/config.h
sway/commands/mouse_warping.c
sway/config.c
sway/input/seat.c
sway/sway.5.scd

This option always moves the cursor into the middle of the container if the warp
variable is true in seat_set_focus_warp.
Fixes #2577

Add mouse_warping container

---

include/sway/config.h
include/swaybar/config.h
include/swaybar/ipc.h
sway/commands/bar/bindsym.c
sway/config/bar.c
sway/ipc-json.c
sway/sway-bar.5.scd
swaybar/bar.c
swaybar/config.c
swaybar/ipc.c

Implements `bar [<bar-id>] bindsym [--release] button<n> <command>`.
Tests:
- `bar bindsym button1 nop` should prevent switching to a workspace when left clicking on the workspace buttons
-  The following should prevent switching the workspace when scrolling up and down on the workspace buttons
```
bar bindsym button4 nop
bar bindsym button5 nop
```
- `bar bindsym --release button1 layout  toggle all` should
- _(If on a workspace button)_, switch to the workspace clicked (or the auto_back_and_forth workspace) and change it's layout (this tests makes sure it doesn't override the pressed behaviour)
- _(If not on a workspace button)_, change the layout of the current workspace
Fixes #1521

Implement bar bindsym

---

sway/desktop/output.c
sway/desktop/render.c

The basic idea here is to apply rounding after scaling. It's not as simple as this, though, and I've detailed it in the comments for a function.
In order to fix some pixel leaks in the title bar, I found it easier to change how we place rectangles to fill the area. Instead of placing two rectangles across the full width above and below the title and having shorter rectangles in the inner area, it's now pieced together in vertical chunks. This method involves drawing two less rectangles per container.
I've done some pretty thorough testing, including:
* Testing with scale 1, scale 2, scale 1.4
* Testing with semi-transparent containers to make sure we're not rendering over the same pixels twice
* Testing with output positions that are not 0,0
* Testing with containers in different parts of …

Fix pixel leaks when using fractional scaling

---

include/sway/config.h
sway/commands/gaps.c
sway/commands/workspace.c
sway/config.c
sway/sway.5.scd
sway/tree/workspace.c

Fixes [Issue: Fix or remove edge_gaps](https://github.com/swaywm/sway/issues/2727) by removing them and allowing negative values for `gaps outer` just the way i3 does it.
While this change allows negative values for the outer gaps to essentially negate `gaps inner` it does not allow to set it lower than the negated `gaps inner` value to prevent windows from ending up outside the container.
This pull request may result in issues with the -1 token value in `workspace_config` struct, if you see this going wrong please give me some pointers on how to go about fixing and testing that.

Fix edge gaps

---

swaylock/password.c

Just a typo that breaks buffer clearing
(I think it could be safely replaced with a memset since there is no succeeding memory freeing)

Fix clear_password_buffer

---

include/sway/config.h
sway/commands/bar.c
sway/commands/bar/id.c
sway/commands/bar/status_command.c
sway/config/bar.c

Overview of changes:
- Made it so `mode` and `hidden_state` are valid both in the config and during runtime.
- Made it so `id` and `swaybar_command` are  only valid in the config.
- Moves the config-only subcommand handling to below bar selection/creation.
- Only allows creation of custom id bars during runtime (default id bars in config only)
For a follow-up PR:
Once #2751 is merged, send the IPC `barconfig_update` event for the subcommands in `cmd_bar_handlers` and handle it in swaybar

Fix bar subcommand handler structs and selection

---

include/ipc.h
include/sway/config.h
include/sway/ipc-server.h
include/swaybar/bar.h
include/swaybar/config.h
include/swaybar/i3bar.h
include/swaybar/ipc.h
include/swaybar/status_line.h
sway/commands/bar/hidden_state.c
sway/commands/bar/mode.c
sway/config/bar.c
sway/input/keyboard.c
sway/ipc-server.c
sway/sway-bar.5.scd
sway/sway.5.scd
swaybar/bar.c
swaybar/config.c
swaybar/ipc.c
swaybar/main.c
swaybar/render.c
swaybar/status_line.c

TODO:
~Priority low on this one, it's mostly there but I don't think I will be working that much on it for now.~

Bar mode/hidden_state events

---

sway/commands/swap.c

When swapping containers that are in the root of the workspace, `parent` will be `NULL`.
To test:
* Create two workspaces with a terminal on each
* Mark one of them
* On the unmarked terminal, run `swaymsg swap container with mark foo`

Fix crash in swap command

---

swaybar/bar.c
swaybg/main.c
swayidle/main.c
swaylock/main.c
swaynag/swaynag.c

The previous behaviour was to show an error and then crash. The new behaviour is to show a more helpful error then exit.

Sway clients: Exit gracefully when compositor is unavailable

---

swaylock/main.c

The referenced constants were not defined so it always printed "version unknown".
Also it would exit with code 1. It now exits with code 0.

Fix swaylock version string

---

common/loop.c

I was getting build errors on my system/toolchain due to an implicit declaration for `clock_gettime` and `CLOCK_MONOTONIC`.
Googling indicated that defining `_POSIX_C_SOURCE` should resolve it. I've used the same value that are used in other source files in the sway source.
This seems to resolve the problem.

common/loop.c: add _POSIX_C_SOURCE for clock_gettime and CLOCK_MONOTONIC

---

include/sway/input/seat.h
sway/commands/move.c
sway/commands/swap.c
sway/input/cursor.c
sway/input/seat.c
sway/tree/container.c

This introduces `seat_set_raw_focus`: a function that manipulates the focus stack without doing any other behaviour whatsoever. There are a few places where this is useful, such as where we set `focus_inactive` followed by another call to set the real focus again. With this change, the `notify` argument to `seat_set_focus_warp` is also removed as these cases now use the raw function instead.
A bonus of this is we are no longer emitting `window::focus` IPC events when setting `focus_inactive`, nor are we sending focus/unfocus events to the surface.
This also fixes the following:
* When running `move workspace to output <name>` and moving the last workspace from the source output, the `workspace::focus` IPC event is no longer emitted for the newly created workspace.
* When splitting the …

Introduce seat_set_raw_focus and remove notify argument from seat_set_focus_warp

---

sway/commands/workspace.c

Fix crash when using workspace back_and_forth with no previous

---

meson.build

SYSCONFDIR should always point to `/etc` since `/usr/etc` is not FHS compliant.
From [FHS-2.3](http://www.pathname.com/fhs/pub/fhs-2.3.html):
> Note that /usr/etc is still not allowed: programs in /usr should place configuration files in /etc.
This is the default in meson since version 0.44: [Release Notes](http://mesonbuild.com/Release-notes-for-0-44-0.html#prefixdependent-defaults-for-sysconfdir-localstatedir-and-sharedstatedir)
Since meson installs the config file in `/etc/sway/config` in any case (even with `config.set('sysconfdir', join_paths(prefix, sysconfdir))` in `meson.build` with `prefix="/usr"`), setting the project argument `SYSCONFDIR=/usr/etc` makes sway unable to find the global configuration file (it crashes with error "Unable to find a config file!"). This PR fixes the …

Make SYSCONFDIR FHS compliant when "prefix" is set

---

common/pango.c

This PR fixes #2842. I think this should work since `vsnprintf` truncates the `va_list` to the size specified in the second parameter. I'm probably wrong on this, so please let me know. Thanks.

swaynag: Truncate message to 2048 chars.

---

common/pango.c

Compiling current master:
```
In function ‘strcpy’,
inlined from ‘get_text_size’ at ../sway-9999/common/pango.c:95:3:
/usr/include/bits/string_fortified.h:90:10: error: ‘__builtin___memcpy_chk’ writing 18 bytes into a region of size 8 overflows the destination [-Werror=stringop-overflow=]
return __builtin___strcpy_chk (__dest, __src, __bos (__dest));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strcpy’,
inlined from ‘pango_printf’ at ../sway-9999/common/pango.c:115:3:
/usr/include/bits/string_fortified.h:90:10: error: ‘__builtin___memcpy_chk’ writing 18 bytes into a region of size 8 overflows the destination [-Werror=stringop-overflow=]
return __builtin___strcpy_chk (__dest, __src, __bos (__dest));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
``` …

Fix overflow in strcpy

---

include/sway/input/cursor.h
include/sway/tree/view.h
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/seat.c
sway/tree/view.c

For the drm backend the pointer would warp to 0,0 on window if `mouse_warping container` was set.
Check that the pointer does not warp to 0,0 and move the arrange functions into `view_map`.
This is actually a decrease in code size, if somebody has a fancier idea than passing `fullscreen` and `decoration` as arguments, I'm all for it. The cursor now correctly warps to the middle of the newly created window.
Edit: codestyle has not been fixed thoroughly, will do that when I can remove the [WIP] comment.

Fix mouse warping container

---

sway/commands/border.c
sway/commands/mark.c
sway/commands/title_format.c
sway/commands/unmark.c

This fixes crashes when running the `border`, `mark`, `unmark` and `title_format` commands on an empty workspace.

Fix crashes when running certain commands on an empty workspace

---

sway/commands/move.c

* Make a workspace which only contains floating views
* Switch to another workspace and create a tiled view
* Move the tiled view to the workspace with `move container to workspace N`
The container would be added as a sibling to the floating view, which makes the container floating while having the geometry of a tiled container.
This changes it so it only looks for tiled containers in the workspace with a fallback to the workspace itself.
Probably fixes #2857 but my symptoms are different to the ones reported in that issue. @c-edw Can you please test if this fixes your issue?

Fix moving tiled containers to workspaces which only have floating views

---

sway/server.c

These can be used by toolkits (currently Qt, libxcursor, glfw) to
choose a default cursor theme and size.
This backports this rootston commit:
https://github.com/swaywm/wlroots/pull/1294/commits/3a181ab430997aaf03a75cbe3b79b0fc56ec96c3

Export XCURSOR_SIZE and XCURSOR_THEME

---

include/sway/input/seat.h
sway/commands/focus.c
sway/commands/swap.c
sway/input/cursor.c
sway/input/seat.c

Because cursor warping was the default behaviour in `seat_set_focus`, there may be cases where we may have been warping the cursor unintentionally. This patch removes cursor warping from `seat_set_focus` and only does it in the `focus` command. This is managed by a static function in `focus.c`.
To know whether to warp or not, we need to know which node had focus previously. To keep track of this easily, `seat->prev_focus` has been introduced and is set to the previous in `seat_set_focus`.

Remove cursor warping from seat_set_focus

---

include/sway/input/seat.h
sway/commands/focus.c
sway/commands/workspace.c
sway/input/seat.c

Fixes a regression introduced in 24a90e5d86441fc345356eb3767e5a6880dcedbd.
`consider_warp_to_focus` has been renamed to `seat_consider_warp_to_focus`, moved to `seat.c` and made public. It is now called when switching workspaces via `workspace <ws>`.

Consider cursor warp when switching workspaces

---

include/sway/config.h
include/sway/input/cursor.h
include/sway/input/input-manager.h
sway/commands/bind.c
sway/commands/seat/cursor.c
sway/input/cursor.c
sway/input/input-manager.c
sway/input/keyboard.c
sway/sway.5.scd

Closes #2378 
Closes #2141 
Implements the syntax `bind{sym,code} --input-device=<identifier> <...>` for both keyboard and mouse bindings.
Since I don't have multiple physical keyboards, I found this easiest to test by launching sway on DRM, on the Wayland backend, and on the X11 backend.
My test config:
```
set $mod Mod4
set $keyboard <keyboard-id>
set $wl_keyboard 0:0:wayland
set $mouse <mouse-id>
set $wl_mouse 0:0:wayland
bindsym $mod+x exec urxvt -e python
bindsym --input-device=$keyboard $mod+x exec urxvt -e bash
bindsym --input-device=$wl_keyboard $mod+x exec urxvt -e zsh
bindsym --whole-window button3 floating toggle
bindsym --input-device=$mouse --whole-window button3 fullscreen toggle
bindsym --input-device=$wl_mouse --whole-window button3 border toggle
```
For the config above: …

cmd_bind{sym,code}: Implement per-device bindings

---

include/sway/input/seat.h
sway/input/seat.c

Turns out we don't need to store the previous focus, and it should be based on which output the cursor was in.
Fixes #2881

Fix logic used for mouse_warping output

---

swaylock/main.c

Fixes #2867.
I have added a new variant of the `background_mode` enum called `BACKGROUND_MODE_UNSET`. This is probably not the best solution.

Prevent overriding background mode after it's been set.

---

sway/input/seat.c

If the container being dragged has a parent that needs to be reaped, it must be reaped after we've reinserted the dragging container into the tree. During reaping, `handle_seat_node_destroy` tries to refocus the dragging container which isn't possible while it's detached.
Fixes #2846.

Fix crash when ending tiling drag

---

include/sway/input/cursor.h
sway/commands/border.c
sway/commands/focus.c
sway/commands/seat/cursor.c
sway/input/cursor.c
sway/input/seat.c
sway/tree/view.c
sway/tree/workspace.c

This function "rebases" the cursor on top of whatever is underneath it, without triggering any focus changes.
Fixes #2815

Introduce cursor_rebase

---

sway/commands/bar/position.c
swaybar/config.c

The positions "left" and "right" are not allowed by the man page, remove them
from the allowed positions. Also print an error to stderr if we default to the
bottom position.
Fixes #2878

swaybar: disallow left and right position and print error on default

---

sway/tree/output.c
sway/tree/workspace.c

When a view unmaps, we call `workspace_consider_destroy`. This function assumed the workspace would always have an output, but this is not the case when hotplugged down to zero. The function now handles this and allows itself to be destroyed when there is no output.
This means that `workspace_begin_destroy` must remove the workspace from the `root->saved_workspaces` list to avoid an eventual dangling pointer, so it does that now.
Lastly, when an output is plugged in again and it has to create a new initial workspace for it, we must emit the `workspace::init` IPC event otherwise swaybar shows no workspaces at all. I guess when you start sway, swaybar is started after the workspace has been created which is why this hasn't been needed earlier.
To test:
* Run sway in a nested session.
* Open …

Fix crash when view unmaps while no outputs connected

---

include/sway/input/input-manager.h
include/sway/input/seat.h
sway/commands.c
sway/commands/border.c
sway/commands/input.c
sway/commands/move.c
sway/commands/scratchpad.c
sway/commands/swap.c
sway/config.c
sway/criteria.c
sway/debug-tree.c
sway/desktop/layer_shell.c
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/transaction.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/input-manager.c
sway/input/keyboard.c
sway/input/seat.c
sway/ipc-json.c
sway/ipc-server.c
sway/server.c
sway/tree/container.c
sway/tree/output.c
sway/tree/root.c
sway/tree/view.c
sway/tree/workspace.c

The input manager is a singleton object. Passing the `sway_input_manager` argument to each of its functions is unnecessary, while removing the argument makes it obvious to the caller that it's a singleton. This patch removes the argument and makes the input manager use `server.input` instead.
On a similar note:
* `sway_input_manager.server` is removed in favour of using the `server` global.
* `seat.input` is removed because it can get it from `server.input`.
Due to a circular dependency, creating seat0 is now done directly in `server_init` rather than in `input_manager_create`. This is because creating seats must be done after `server.input` is set.
Lastly, it now stores the default seat name using a constant and removes a second reference to seat0 (in `input_manager_get_default_seat`).

Minor refactor of input manager

---

sway/input/input-manager.c

Function input_manager_get_default_seat should always return a seat.
Fixes #2891.

Fix crash when defaut seat is not created

---

swaybar/bar.c

This allows the bar to render over fullscreen views.
Fixes #2832.

Put swaybar in overlay layer when using mode hide

---

sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c

The `wlr_xdg_popup_get_toplevel_coords` function has the following quirks:
* It does not do anything with the coordinates of the passed popup. Instead, we are required to add them ourselves, which we do by passing them to the function as the surface local values.
* It adds the geometry (shadows etc) of the toplevel itself, so the coordinates are surface local rather than content local. For this reason, we have to negate the toplevel's geometry (`child->view->geometry`).
* I may be wrong, but the popup positions appear to be stored in surface local coordinates rather than content local coordinates. The geometry (shadows etc) of the popup itself must be negated (`surface->geometry`).
Fixes #2893.

Fix popup damage issues when toplevel and/or popup uses geometry

---

include/sway/input/seat.h
include/sway/tree/workspace.h
sway/commands/move.c
sway/commands/swap.c
sway/commands/workspace.c
sway/input/seat.c
sway/tree/view.c
sway/tree/workspace.c

* When using multiple seats, each seat has its own `prev_workspace_name` for the purpose of `workspace back_and_forth`.
* Removes `prev_workspace_name` global variable.
* Removes unused `next_name_map` function in `tree/workspace.c`.
* Fixes memory leak in `seat_destroy` (`seat` was not freed).
Tested using `workspace back_and_forth`, `move container to workspace back_and_forth`, and `reload`.

Make workspace back_and_forth seat-specific

---

sway/commands/reload.c

Fixes #2905 
When the config gets reloaded, the font height and baseline get reset to 0. If the config does not have a font command in it, the variables will remain at 0 causing a transparent area where the title would be rendered.
This makes it so the font height and baseline are recalculated. Additionally, since the font height and baseline may have changed due to the reload, the title and marks textures are rebuilt.

cmd_reload: recalc font sizing + rebuild textures

---

sway/commands/move.c

Setting normal focus to the fullscreen view causes the old workspace to start destroying. We then set focus to the old workspace which is no longer attached in the tree.
As we are only setting `focus_inactive` on the fullscreen container, the fix uses `seat_set_raw_focus` to avoid all the additional behaviour that comes with it such as destroying the old workspace.
Fixes #2915.

Fix crash when moving a container to a fullscreen workspace

---

include/sway/tree/view.h
sway/tree/view.c

QT unmaps the view before destroying the popup. We destroyed the popup in response to the view unmapping, but then we'd attempt to destroy it a second time which caused a crash.
The patch removes the listener.
I tested it with GTK as well, and can confirm the popup is still being destroyed.
Fixes #2908.

Fix crash when quitting a QT app on the wayland backend using menu

---

sway/desktop/xwayland.c

Requires https://github.com/swaywm/wlroots/pull/1327 to actually fix the floating logic, but won't break anything if this is merged first.
See i3's implementation here: https://github.com/i3/i3/blob/a319860cd10cda17e176218e6dc34145fbb3bd94/src/manage.c#L444-L445
To test:
* Run `emacs`, press Alt + x and type `server-start`, then open a terminal and run `emacsclient -nc`. This window should be tiled.
* Run `echo getpin | pinenetry-gtk-2`. This window should be floating.
Fixes #2844.

Fix xwayland wants_floating logic

---

sway/commands/resize.c
sway/tree/container.c

Firstly, the container was wrongly identifying as a tiling container because it had no workspace.
Secondly, when calculating the maximum possible size we can't use the workspace if it's not there, so we'll allow unlimited size in this case.
We should probably use the `config->floating_maximum_{width,height}`, but I feel the resize constraints needs to be refactored anyway and I just want to fix the crash for now.
Fixes #2928.

Fix crash when resizing container hidden in the scratchpad

---

sway/sway.5.scd

I noticed some missing references to sway-output(5) in the sway(5) man page while looking for the documentation of the _output_ command.
Somewhat a follow-up of #2831
I tried to keep it consistent with the documentation of _input_ and how sway-input(5) is handled.
- Update the incorrect reference to _output_ in the _swaybg_command_ description.
- Add a reference to sway-output(5) in See Also
- Add an _output_ command description referring to sway-output(5)

Add references to sway-output(5) in sway(5)

---

sway/commands/swaynag_command.c

The custom `swaynag_command` was being stored as `config->swaybg_command` instead of `config->swaynag_command`.

cmd_swaynag_command: fix typo in variable

---

sway/input/cursor.c
sway/input/seat.c

The cursor's image would be removed or set when the seat's capabilities were updated, but there was nothing to prevent the image from being set at other times.
To test:
* Have `seat seat1 attach "1:1:AT_Translated_Set_2_keyboard"` in your config.
* Launch sway on DRM.
* The cursor's position will be in the top left of an output. Move it away and note there is only one cursor at the moment.
* Launch a view on that output then close the view.
* A second cursor would appear in the top left in response to the view unmapping.
Fixes #2921.

Fix dormant cursor when using multiple seats

---

include/sway/tree/view.h
sway/desktop/xwayland.c
sway/ipc-json.c
sway/tree/view.c

window_properties is documented to contain a subset of the X11 properties
of a window (its title, class, instance, role, and transient ID). This
commit adds the missing json object from the get_tree output for
xwayland windows only.
This is a follow-up of #2911.
Signed-off-by: Franklin "Snaipe" Mathieu <me@snai.pe>

xwayland: populate window_properties in json for views

---

sway/commands/focus.c

Prior to this patch, creating a tabbed container with two views, switching tab and then scrolling without motion would cause the scroll events to be sent to the old focus. To fix this, rebasing the cursor is needed after changing focus.
Fixes #2945.

Rebase the cursor after focusing in a direction

---

include/sway/desktop/transaction.h
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c

I originally put the rebase at the end of view_map, but at this point the view is still at its native size and will ignore the motion event if it falls outside of its native size. The only way to do this properly is to rebase the cursor later - either after sending the configure, after the view commits with the new size, or after applying the transaction. I chose to do it after applying the transaction for simplicity.
I then attempted to just call `cursor_rebase` after applying every transaction, but this causes crashes when exiting sway (and possibly other places) because `cursor_rebase` assumes the tree is in a valid state.
So my chosen solution introduces `transaction_commit_dirty_with_callback` which allows `handle_map` to register a callback which will run when the transaction is …

Rebase the cursor after mapping a view

---

sway/tree/root.c

This fixes a regression introduced by 662466e8db773926bf61b21280194a3540ae26ec (#2929). When adding a container to the scratchpad, setting `container->scratchpad = true` before `container_set_floating` made `container_set_floating` believe that the container was already floating. This fixes it by setting the property afterwards instead.
Test by focusing a tiling view then running `move scratchpad` followed by `scratchpad show`.
Also tested with the config that the original issue was fixing:
for_window [class="Firefox"] floating enable
for_window [class="Firefox"] move scratchpad
for_window [class="Firefox"] resize set 1000 1000

Fix containers not being resized when entering scratchpad

---

include/sway/desktop/transaction.h
sway/commands/border.c
sway/commands/focus.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/seat.c
sway/tree/view.c
sway/tree/workspace.c

This approaches cursor rebasing from a different angle. Rather than littering the codebase with `cursor_rebase` calls and using transaction callbacks, this just runs `cursor_rebase` after applying every transaction - but only if there's outputs connected, because otherwise it causes a crash during shutdown.
There is one known case where we still need to call `cursor_rebase` directly, and that's when running `seat seat0 cursor move ...`. This command doesn't set anything as dirty so no transaction occurs.

Rebase the cursor after applying transactions

---

sway/commands/floating.c
sway/commands/focus.c
sway/commands/fullscreen.c
sway/commands/gaps.c
sway/commands/kill.c
sway/commands/layout.c
sway/commands/move.c
sway/commands/rename.c
sway/commands/resize.c
sway/commands/scratchpad.c
sway/commands/split.c
sway/commands/swap.c
sway/commands/workspace.c

Fixes #2972.
I probably haven't found them all, but these are the ones that are likely to be bound to shortcuts and which will cause crashes.

Deny several commands when there's no outputs connected

---

swaybar/input.c
swaybar/ipc.c
swaybar/render.c

1. wrap_scroll has been fixed
2. release bindings are checked when returning early

swaybar: fix scrolling behaviour

---

sway/sway.5.scd

The two lines were collapsed in the generated man page

protect newline

---

sway/ipc-server.c

As discussed in #2967.
The error paths in the handling of the SUBSCRIBE message used `wlr_log_errno()`, which appends the textual representation of `errno`.
In the first case, after failing to parse the message with Json-C, "Failed to read request" is printed.
This is misleading, since it was read correctly, it just wasn't valid JSON. Also, Json-C doesn't set `errno`, so either we use `wlr_log()` or also switch on `json_tokener_get_error()` and build a more detailed error message. The latter is not worth the boilerplate IMO.
Secondly, if an unsupported event name is encountered, the message was "Failed to parse request". I changed this to "Unsupported event type in subscribe request". I changed to `wlr_log()` as above.

sway-ipc: don't log errno if unneeded and add more descriptive errors

---

sway/tree/container.c

When a floating container is tiled (e.g.: 'floating toggle' or
'floating disable'), it should be placed after/below the inactive
focused container from the tiling layout.
Fixes #2866

Fix re-tiling for floating containers

---

sway/input/seat.c

The code being changed is responsible for updating the focus stack when a container is destroyed in a different part of the tree to where the real focus is. It's attempting to set focus_inactive to a sibling (or
parent if no siblings) of the container that is being destroyed, then put our real focus back on the end of the focus stack.
The problem occurs when the container being destroyed is in a different workspace. For example:
* Have a focused view on workspace 1
* Have workspace 2 not visible with a single view that is unmapping
* The first call to `seat_set_raw_focus` sets focus to workspace 2 because it's the parent
* Prior to this patch, the second call to `seat_set_raw_focus` would set focus to the view on workspace 1
* Later, when using `output_get_active_workspace`, this function …

Fix focus after a non-visible workspace's last container is destroyed

---

sway/desktop/render.c
sway/tree/view.c

In i3, when a child of a tabbed or stacked container has no siblings, its border settings are respected.
This patch achieves the same effect by rendering a lone tabbed/stacked child as if it's a linear container. This makes the border settings be respected.
Over in `view_autoconfigure`, we compensate for this by only adjusting `y_offset` if there's multiple children.
When the lone child is itself a split container, I'm taking a guess that rendering the tab title (containing the tree representation) is the ideal thing to do here.
Tested with `hide_edge_borders smart`, `hide_edge_borders none`, and with the lone child being a split container.
Fixes #2912.

Respect border settings when rendering lone tabbed/stacked child

---

sway/tree/view.c

I don't know if it's the project settings or the way the meson infra works in `nixpkgs`, but my package is broken without this change. (my toolchain is treating warnings as errors.) Plus, I figure this can only help.
Thanks.
cc: @RyanDwyer the change came from (https://github.com/colemickens/sway/commit/65328ef60c9468ae44b4b1d6316d604c47293ec3#diff-819010104a02bd78a3801147b06a4d57)

tree/view.c: fix uninitialized variables warning

---

sway/input/input-manager.c

input_manager_set_focus is used to set the focus after mapping the view in
view_map. This needs to consider to warp the cursor as well, since for
WARP_CONTAINER, the cursor should warp to the newly created view.
OT:
The only place where `input_manager_set_focus` is used is inside the `view_map`function. We could remove the function and open code it into `view_map`.

input-manager: consider cursor warping on input_manager_set_focus

---

sway/tree/output.c

The previous pull request #2993 tried to fix this by moving the function which
used the layers after the initilization.
Since this initialization is done unconditionally only depending on the struct
definition, move the layer initialization to the beginning of the function.
Fixes #2992

output: initialize layers before usage in apply_config

---

swayidle/main.c
swayidle/swayidle.1.scd

This allows to e.g. turn off screens when starting `swaylock`.
Also fixes a few things:
* Removes generic idle callback infrastructure
* Only connect to systemd system bus once if needed
* Allow zero timeouts to mean no timeout in swayidle CLI
* Fixes event loop
* Use `wl_event_loop_add_signal` instead of `signal`
Depends on https://github.com/swaywm/wlroots/pull/1337
Fixes #2914

swayidle: enter idle state on SIGUSR1

---

common/util.c
include/sway/output.h
include/sway/tree/container.h
include/util.h
sway/commands/focus.c
sway/commands/move.c
sway/tree/output.c

There's no point having both `movement_direction` and `wlr_direction`. This replaces the former with the latter.
As `movement_direction` also contained `MOVE_PARENT` and `MOVE_CHILD` items, these are now checked specifically in the focus command and handled in separate functions, just like the other focus variants.
This is progress towards #3030.

Remove enum movement_direction

---

common/util.c
include/util.h
sway/commands/focus.c
sway/commands/move.c

Also moves the `opposite_direction` function into `util.c` as it's used in two places now.
Fixes #3030.

Wrap to fartherest output when running focus output

---

include/sway/tree/container.h
include/sway/tree/view.h
sway/commands/border.c
sway/desktop/transaction.c
sway/input/cursor.c
sway/tree/container.c
sway/tree/view.c

This will be needed to implement layout saving and restoring, as we need to be able to configure borders on a placeholder container which has no view.

Move view border properties to container struct

---

include/sway/tree/container.h
include/sway/tree/view.h
sway/commands/client.c
sway/commands/mark.c
sway/commands/move.c
sway/commands/reload.c
sway/commands/show_marks.c
sway/commands/swap.c
sway/commands/unmark.c
sway/criteria.c
sway/desktop/output.c
sway/desktop/render.c
sway/ipc-json.c
sway/ipc-server.c
sway/tree/container.c
sway/tree/view.c

Like border properties, this will be needed to implement layout saving and restoring.

Move view marks properties to container struct

---

sway/ipc-json.c
swaymsg/main.c

Fixes #3051.
Fixed output example:
```
Output eDP-1 'Sharp Corporation 0x148B 0x00000000'
Current mode: 3840x2160 @ 59.997002 Hz
Position: 3440,0
Scale factor: 2x
Transform: normal
Workspace: 1
Available modes:
3840x2160 @ 47.997002 Hz
3840x2160 @ 59.997002 Hz
```

Correct "Current mode" in `swaymsg -t get_outputs` for scaled outputs

---

include/sway/input/keyboard.h
sway/input/keyboard.c

This makes bindings more snappy when the user is typing faster than
his keycaps are releasing.
Signed-off-by: Franklin "Snaipe" Mathieu <me@snai.pe>

binding: match single-key bindings if no multi-key binding matched

---

sway/ipc-json.c
swaymsg/main.c

In responding to feedback during #3052, I accidentally removed the `refresh` field from each `mode` entry. This corrects that mistake. Sorry for the churn.
cc: @emersion

ipc: move refresh to current_mode

---

completions/fish/swaymsg.fish
sway/input/seat.c
sway/sway.5.scd
swaymsg/swaymsg.1.scd

This contains three unrelated things:
* Documentation for `swaymsg -t get_seats` (as well as implementation in fish completions)
* Fix in sway.5 manpage (fixes spacing after the Table)
* Deletion of a not needed code fragment in seat.c

Improve documentation and remove dead code

---

sway/commands/gaps.c
sway/sway.5.scd

This patch addresses two issues:
1. The command `gaps inner|outer all|current set|plus|minus <amount>` is not valid in the configuration file, hence list it accordingly in the manpage.
2.  Always raise an error if the mentioned gaps command is found in the config file. Previously there was only an error reported on startup but not on config reload.
By working on this patch I realized that the gaps command is an exception to the other commands: All commands are classified in config file only commands, runtime only commands or commands which are valid in both cases. But the gaps command doesn't conform to this classification and actually consists  of two commands:
- `gaps inner|outer all|current set|plus|minus <amount>` (runtime only)
- `gaps inner|outer <amount>` (runtime and config) …

Improvements to the runtime only part of the gaps command

---

swayidle/main.c

SIGUSR1 is supposed to trigger swayidle; however, in my experience this never happens.
I suspect there might be some kind of a race condition between setting a 0-timeout timer and the actual signal handling, so here's a PR that kind of papers over the problem by making the timeout 50ms instead. This makes it work for me consistently
Feel free to reject this PR if this workaround is not acceptable, but I'm not sure how to actually fix the timer logic so that 0-timeout timers work.

Work around swayidle never triggering on SIGUSR1

---

sway/commands/focus.c

Fixes #3064 
It appears that the focus code that handles `focus_wrapping yes` was removed during the conversion to type safety. This re-implements the focus code for when `focus_wrapping` is set to `yes` (default). Neither the `no` or `force` options appear to be effected and should be working.

Fix focus_wrapping yes

---

sway/commands/exec_always.c
sway/config.c

While at it, fix the reload message.

Fix the double execution of exec_always commands on config reloads

---

sway/commands/output/transform.c
sway/sway-output.5.scd

This commit enhances the output transform
command with options for a relative transform,
i.e. the provided transform will be applied as
an offset to the current transform. Append
`clockwise` to rotate clockwise from the current
rotation, or `anticlockwise` to rotate in the
opposite direction.
For example, if the output LVDS-1 is rotated 90 degrees
clockwise, the command `output LVDS-1 transform 90 clockwise`
will rotate the display to 180 degrees. All transform
options are supported, including flipped transforms.

Add relative output transform

---

include/sway/config.h
sway/commands/focus_follows_mouse.c
sway/config.c
sway/input/cursor.c

I suggested a feature in #3025 where the focus will always follow the mouse. This can be used by specifying `focus_follows_mouse always` in the config file.

Add focus_follows_mouse always.

---

include/sway/tree/container.h
sway/tree/container.c
sway/tree/view.c

Removes duplicate inner gaps between two containers. See https://github.com/swaywm/sway/issues/307#issuecomment-165437419.
Instead of dividing the gaps by two between two containers as suggested, I decided to do the following:
1) Inner gaps are always added to the right and bottom sides
2) Inner gaps are only added to the top side when the container's y location matches the workspace's y location without inner gaps applied
3) Inner gaps are only added to the left side when the container's x location matches the workspace's x location without inner gaps applied
I think this solution is better since the inner gaps are guaranteed to be integer values instead of having to deal with half pixel values when dividing an odd inner gap by two.

gaps: remove duplicate inner gaps

---

include/sway/config.h
include/sway/tree/workspace.h
sway/commands/gaps.c
sway/commands/workspace.c
sway/config.c
sway/sway.5.scd
sway/tree/view.c
sway/tree/workspace.c

Closes #3059 
This introduces the following command extensions from `i3-gaps`:
* `gaps horizontal|vertical|top|right|bottom|left <amount>`
* `gaps horizontal|vertical|top|right|bottom|left all|current set|plus|minus <amount>`
* `workspace <ws> gaps horizontal|vertical|top|right|bottom|left <amount>`
`inner` and `outer` are also still available as options for all three of the above commands. `outer` now acts as a shorthand to set/alter all sides.
Additionally, this fixes two bugs with the prevention of invalid gap configurations for workspace configs:
1. If outer gaps were not set and inner gaps were, the outer gaps would be snapped to the negation of the inner gaps due to `INT_MIN` being less than the negation. This took precedence over the default outer gaps.
2. Similarly, if inner gaps …

Implement per side and per direction outer gaps

---

sway/commands/swap.c

The `struct sway_container *other` variable in swap.c was potentially used uninitialized, depending on an "if" statement.

Fix building with clang

---

sway/commands/resize.c
sway/sway.5.scd

Related to #3082
i3 documentation: https://i3wm.org/docs/userguide.html#resizingconfig
This implements the following syntaxes from `i3 4.16`:
* `resize set [width] <width> [px|ppt]`
* `resize set height <height> [px|ppt]`
* `resize set [width] <width> [px|ppt] [height] <height> [px|ppt]`
Additionally, a bug was fixed that caused setting the height of a tiled container to change the width instead due to a typo.

resize set: implement width and height keywords

---

sway/sway.5.scd

In PR #3081, I forgot to update the documentation for the `focus_follows_mouse` option. Sorry about that.

Update documentation for focus_follows_mouse.

---

include/sway/config.h
sway/commands/workspace.c
sway/sway.5.scd
sway/tree/output.c
sway/tree/workspace.c

Related to #3082 
i3 documentation: https://i3wm.org/docs/userguide.html#workspace_screen
`workspace <workspace> output <outputs>`
`i3 4.16` allows users to list multiple outputs for a workspace and the first available will be used.
Additionally when the workspace is created, the outputs get added to the output priority list in the order specified. This ensures that if a higher output gets connected, the workspace will move to the higher output. This works the same way as if the user had a workspace on an output, disconnected the output, and then later reconnected the output.

Allow multiple outputs for workspace output

---

sway/commands/ws_auto_back_and_forth.c

In the conversion to `parse_boolean` for `cmd_ws_auto_back_and_forth` (#3098), the `!` was never removed (was previously using `strcasecmp`) causing the setting to be the opposite of what it should be.

cmd_ws_auto_back_and_forth: fix negation

---

sway/commands/swap.c

```
Error: test_id defined but not used. [-Werror=unused-function].
```
Also fixes a `size_t` cast to `void *`.
https://github.com/swaywm/sway/issues/3123#issuecomment-438763220

Fix unused function in swap command

---

sway/config.c

`config->current_mode` is a pointer into the `config->modes` list, and each mode has already been freed earlier in the function.
Same with bars.
Fixes #3129.

Fix double free of mode

---

sway/commands/resize.c

I'm not sure I understand why the PPT/PX codepaths are different and thus why these would be uninitialized. Hopefully zero is a sane default.
This fixes a build error and my packaging treats it as an error. Thanks.

commands/resize: fix grow vars uninitialized

---

include/sway/tree/container.h
include/sway/tree/view.h
sway/commands/border.c
sway/commands/resize.c
sway/desktop/desktop.c
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/ipc-json.c
sway/tree/container.c
sway/tree/view.c

This renames/moves the following properties:
* `sway_view.{x,y,width,height}` -> `sway_container.content_{x,y,width,height}`
* This is required to support placeholder containers as they don't have a view.
* `sway_container_state.view_{x,y,width,height}` -> `sway_container_state.content_{x,y,width,height}`
* To remain consistent with the above.
* `sway_container_state.con_{x,y,width,height}` -> `sway_container_state.{x,y,width,height}`
* The `con` prefix was there to give it contrast from the view properties, and is no longer useful.
The function `container_set_geometry_from_floating_view` has also been renamed to `container_set_geometry_from_content`.

Move view {x,y,width,height} into container struct

---

common/util.c
include/sway/commands.h
include/sway/config.h
include/util.h
sway/commands/input.c
sway/commands/input/pointer_accel.c
sway/commands/input/scroll_factor.c
sway/config/input.c
sway/input/cursor.c
sway/meson.build
sway/sway-input.5.scd

This commit adds a `scroll_factor` input command whose value is used as a multiplier for axis event deltas received from a device. Put simply, this means that scrolling speed can now be adjusted, a configuration feature that libinput itself lacks. At least on my laptop's touchpad, such a change is sorely needed.
For example, adding `scroll_factor 0.5` under a device's `input` section will make scrolling half as fast.
Fixes #3004.

Add scroll factor input command.

---

config.in

I think there's a typo in config.in and this commit fixes it.
From experimantation I think that the example timeouts given in config.in don't add to another (like currently described in the comment block) but are timeouts on its own.
This typo is misleading and can be dangerous, e.g. I set the second (DPMS) timeout to a lower value than the first one (I thought from the comments they add to each other) and then typed my password into an open shell (I thought the screen locked).
Please tell me if the commit message is too short - but actually it's just a typo I think.
Although I DID NOT CONFIRM in the source code that it's actually two independent timeouts (I don't know where that is.) Please, someone else should do this.

fix typo in config.in

---

meson.build

```SYSCONFDIR``` was set to the wrong path if ```prefix``` is not ```'/usr'``` and
```sysconfdir``` is an absolute path. Use ```join_paths()``` to fix it.
Also remove the special case for ```prefix``` ```'/usr'```. In that case Meson
already sets ```sysconfdir``` to the absolute path ```'/etc'```, so just using
```join_paths()``` will return the correct value.
join_paths('/usr/local', 'etc') => '/usr/local/etc'
join_paths('/usr/local', '/etc') => '/etc'
join_paths('/usr', '/etc') => '/etc'
This should allow building and installing to '/usr/local' while storing configuration data like pam settings in ```/etc```. (#3096)

Meson: Fix SYSCONFDIR definition

---

include/sway/commands.h
include/sway/config.h
include/sway/tree/container.h
sway/commands.c
sway/commands/titlebar_border_thickness.c
sway/commands/titlebar_padding.c
sway/config.c
sway/desktop/render.c
sway/meson.build
sway/sway.5.scd
sway/tree/container.c

As talked in issue #3134 titlebar border size and padding are currently hardcoded
This patch proposes two new commands, which permits to adjust the width of titlebars
- titlebar_border_thickness \<n\>
- titlebar_padding \<h\> [v]
Example use with swaymsg to just get a 1 px border and minimal space above and below text : 
$ swaymsg titlebar_border_thickness 1
$ swaymsg titlebar_padding 5 1

Adding commands for configuring titlebar borders and padding

---

sway/commands/resize.c

The behavior of `resize set <width> <height>` for floating containers has changed recently. According to the documentation, floating containers should be resized in px if the units are omitted, but now ppt are used for both tiled and floating containers.

resize set: fix units for floating containers

---

swayidle/main.c

The wl_event_source_fd_update docs say:
> File descriptors are usually writable to begin with, so they do not need to
> be polled for writable until a write actually fails. When a write fails,
> the event mask can be changed to poll for readable and writable, delivering
> a dispatch callback when it is possible to write more. Once all data has
> been written, the mask can be changed to poll only for readable to avoid
> busy-looping on dispatch.
So we should only poll for WL_EVENT_WRITABLE if a write fails. I'm not yet sure
how to do this properly and Weston doesn't do it, so in the meantime I'll just
fix the busy loop. I'll ask them too.
Fixes https://github.com/swaywm/sway/issues/3190

swayidle: fix busy loop on writable FD

---

sway/ipc-json.c
sway/tree/root.c

This matches i3's behavior:
- triggers window::move events when containers are moved to scratchpad or when scratchpad is shown
- adds all hidden scratchpad containers to get_tree reply 
Fixes #3159

Fix missing IPC scratchpad replies/move events

---

sway/commands.c

Fixes #3146
Like with cmd_bindsym and cmd_bindcode, the quotes should not be stripped for cmd_mode. cmd_mode performs its own stripping for the mode name and the only valid subcommands are cmd_bindsym and cmd_bindcode.

Do not strip quotes for cmd_mode

---

include/swaynag/swaynag.h
swaynag/config.c
swaynag/swaynag.1.scd
swaynag/swaynag.c

Related to #3082 
In `i3 4.16`, `i3-nagbar` introduces the flags `-B/--button-no-terminal` to run the action directly instead of inside a terminal. This implements the flags for swaynag for compatibility.
Since swaynag does not use an equivalent to `i3-sensible-terminal`, the flags `-b/--button` only uses a terminal when the environment variable `TERMINAL` is set, otherwise it acts the same as these new flags.

Implement swaynag -B/--button-no-terminal

---

include/sway/tree/view.h
sway/tree/view.c

Damage subsurfaces when they are destroyed. Since subsurfaces don't have an
unmap event we need to do that on destroy.
We also don't want to keep a sway_view_child when the wlr_subsurface has been
destroyed.
Fixes https://github.com/swaywm/sway/issues/3197

Handle destroyed subsurfaces

---

include/sway/config.h
sway/commands/bind.c
sway/commands/output/background.c
sway/config.c

Closes #3138
Adds the function `config_add_swaynag_warning(char *fmt, ...)` so that handlers can add warnings to the swaynag config log in a uniform way. The formatting is identical to errors and include the line number, line, and config path.
This also alters the background file access warning to use the function and introduces a warning for duplicate bindings.

Introduce a way to show config warnings in swaynag

---

sway/commands/move.c

moving a container to a non-empty workspace will find a container to move
to in the destination workspace and call container_move_to_container,
which must not just skip floating containers

move to workspace: fix moving floating container to non-empty workspace

---

include/sway/commands.h
include/sway/config.h
include/swaybar/config.h
sway/commands/bar.c
sway/commands/bar/gaps.c
sway/ipc-json.c
sway/meson.build
sway/sway-bar.5.scd
swaybar/config.c
swaybar/ipc.c
swaybar/render.c

Closes #2904
Adds the bar subcommand `gaps <amount>|<horizontal> <vertical>|<top> <right> <bottom> <left>` to set gaps for swaybar. Due to restrictions on margins for a layer_surface, only the sides that are anchored to an edge of the screen can have gaps. Since there is support for per-side outer gaps for workspaces, those should be able to be used instead for the last side.

Implement bar gaps

---

sway/ipc-server.c
swaymsg/main.c
swaymsg/swaymsg.1.scd

Related to #3082
In `i3 4.16`, `i3-msg` can be used with the message type `subscribe` and has the ability to monitor for responses until killed. This adds support for both to swaymsg.
If the JSON array of event types is malformed or contains an invalid event, sway will send a response with `success` set to `false`. If swaymsg sees this, it will not display the failure and exit.
If the `subscribe` event is successful, swaymsg will wait for the first response and display that instead of the success message. If `-m/--monitor` is given, swaymsg will continue monitor for responses until killed or a malformed response is received.
For the `subscribe` event, the responses will always be printed as JSON. If `-r/--raw` is given, the JSON will not be pretty printed, which may be preferred when …

Implement support for swaymsg -t SUBSCRIBE [-m]

---

sway/tree/root.c

Fixes #3203 
When adding a container to the scratchpad, it was possible for focus to be removed from the seat. This occurred when a single child was moved from it's parent to the scratchpad due to the focus_inactive for the parent being NULL. If the focus_inactive for the parent is NULL, the focus_inactive for the workspace should be focused.

Fix scratchpad segfault - NULL focused workspace

---

sway/desktop/render.c

Fixes #3215 
This fixes the rendering of the titlebar when there is no title or marks.

Fix titlebar when no title or marks

---

sway/ipc-server.c

Pull request https://github.com/swaywm/sway/pull/3206 seems to have broken the expected json success return values so that existing ipc tooling won't work (eg. it turned an object into an object wrapped in an array).

Fix json object ipc success return

---

swaymsg/main.c

Related to #3218
Allows swaymsg to parse the success attribute of a single object response. This is needed for the subscribe event.

swaymsg: parse success of single object

---

swaylock/main.c

To use POLL_IN, signal.h must be included and _XOPEN_SOURCE [must be defined](https://git.musl-libc.org/cgit/musl/tree/include/signal.h#n223).

swaylock: fix build with musl libc

---

sway/commands/fullscreen.c
sway/sway.5.scd

The first commit fixes a problem that I have when using the following keybinding on an empty workspace
`bindsym Mod4+v fullscreen disable,exec termite -e pulsemixer`.
With this binding I want to open an application but in case that another view is currently in fullscreen mode, it should leave fullscreen mode first. This does not work on an empty Workspace, because `fullscreen disable` returns with error status `CMD_INVALID` and then the following exec command will not be executed (cf. https://github.com/swaywm/sway/blob/master/sway/commands.c#L307).
In i3 this binding works on empty workspaces.
The second commit documents the optional arguments of the fullscreen command, which can be found in i3's documentation too.

Fix fullscreen command and improve documentation

---

meson.build

It is redefined in swayidle/meson.build

meson.build: remove obsolete definition of swayidle_deps

---

sway/commands/bind.c
sway/sway.5.scd

Recently, bindsym/bindcode was changed to give a warning when you rebind a keystroke.  This patch allows the user to suppress that warning with the --no-warn flag.

Add option to bindsym/bindcode to suppress warning on override

---

sway/commands/focus.c

Fixes #3235 
If a scratchpad container is hidden, it is still focusable using criteria and should be shown. This fixes a segfault when attempting to rebase the cursor since previously the scratchpad container would not be on any output.

cmd_focus: show scratchpad if hidden

---

sway/config.c

Before, it was only set if it was not set, but it should also be done
when empty.
Source: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

config: set $XDG_CONFIG_HOME if empty

---

sway/commands.c

Test plan:
1.  Open two terminals side by side:
```
+-------+-------+
|   A   |   B   |
+-------+-------+
```
2. In terminal B type `swaymsg focus left, fullscreen`
3. Terminal A is in fullscreen mode.
Before this patch terminal B was made fullscreen.

Fix command list execution

---

sway/commands/split.c

Fixes #3259 
Matches i3 behavior

cmd_split: flatten when possible

---

common/list.c

This is the industry standard since it allows insertion to be amortized
O(1) time.

list: double list capacity when resizing instead of incrementing

---

sway/desktop/output.c

Fixes #2948
When a new output is detected and it is disabled by the output config, call `wlr_output_enable(output->wlr_output, false)` to DPMS off the output.

Call wlr_output_enable for disabled new outputs

---

sway/input/seat.c

Fixes #3281
Changing the focus stack when destroying a container's node on a
non-visible workspace (on an non-focused output) incorrectly causes
the non-visible workspace to become visible. If the workspace is empty,
it will not be destroyed since it is now visible. Additionally since
there was no workspace::focus event, swaybar still shows the previous
workspace as focus-inactive. It also makes no sense to change visible
workspaces due to a container on a non-visible workspace being
destroyed.
Since the focus will either be set when switching to the non-visible
workspace or the workspace will be destroyed due to being empty, there
is no need to change the focus stack when destroying a container on a
non-visible workspace.

Keep focus when destroying containers on non-vis ws

---

sway/tree/view.c

This patch moves view_execute_criteria(view) at the end of the function.
Previously, if a view requested to be started in fullscreen, this was
done after execution of criteria and hence it was impossible to disable
fullscreen via criteria.
Fixes #3285 
I don't use telegram but I was able to reproduce the problem in #3285 with mpv by adding
```
for_window [app_id="^mpv$"] fullscreen disable
```
to my config and starting mpv with `mpv --fullscreen <file>`. Before this patch mpv remained in fullscreen.

Fix criteria execution in view_map

---

include/sway/config.h
sway/config.c
sway/config/output.c

Fixes #3277 
Fixes #3261
Default output configs were generated on reload to reset an output to its default settings. The idea was that anything that was removed from the config or changed at runtime and not in the config should be reset on reload. Originally, they were created using the output name. Recently, they were changed to use the output identifier. It turns out that there are issues of shadowing with that solution as well. This should fix those issues.
Instead of generating the default output configs on reload and storing them in the output config list to merge on top of, they are now only generated when retrieving the output config for an output during a reload. This means that the default output configs are never stored anywhere and just used as a base to merge unaltered user …

Rework default output configs

---

sway/input/seat.c

Fixes #2625 
#3281 should still be fixed and have no regression
My previous attempt (#3288) was not quite right. Changing the focus stack on a non-visible workspace should only be blocked if the focus would be set to the workspace itself.

Fix focusing on non-visible workspace

---

swaynag/swaynag.c

When the cursor surface gets updated, it should be damaged.
This also bumps up `wl_compositor` to version 4 to be able to use `wl_surface_damage_buffer`.

swaynag: damage the cursor surface on update

---

sway/input/cursor.c

Fixes #3182
Enables titling views to be dragged by the titlebar. This is in addition to using the modifier and dragging them from anywhere on the container surface. Floating views already allow this behavior.

Allow tiling views to be dragged by the titlebar

---

swaynag/swaynag.c

Fixes #3300 
If there are no arguments or invalid arguments given, swaynag will free
`swaynag.details.button_details` under the `cleanup` label in main. It
then called `swaynag_destroy`, which would attempt to free it again.
Since `swaynag.details.button_details` is either freed on line 106 of
main (when there is no detailed message) or added to `swaynag.buttons`
on line 103 of main, there is no reason to manually free it in
`swaynag_destroy`.
Although I cannot reproduce a double free on my system, for some reason,
it should have actually resulted in a double free in all code paths.

swaynag: remove double free of details button

---

sway/commands/split.c

Fixes #3304
Fixes a crash when running `split` commands with the workspace focused.

cmd_split: add null checks in do_split

---

sway/input/cursor.c

Before attempting to drag a tiling container by its titlebar, focus it. This fixes clicking on titlebars to focus a container.

Focus node before tiling drag if on titlebar

---

include/sway/output.h
sway/commands/focus.c
sway/commands/move.c
sway/commands/output/transform.c
sway/desktop/output.c
sway/input/seat.c
sway/tree/view.c
sway/tree/workspace.c

Supersedes #3314
This combines `output_by_name` and `output_by_identifier` into a single
function called `output_by_name_or_id`. This allows for output
identifiers to be used in all commands, simplifies the logic of the
callers, and is more efficient since worst case is a single pass through
the output list.

Combine output_by_name and output_by_identifier

---

sway/desktop/output.c
sway/desktop/render.c
sway/tree/container.c

Fixes #3322 
The fix pushed to master missed wlr_box_intersection. This just fixes those calls so sway renders properly again

Fix wlr_box_intersection args for wlroots 1441

---

swaylock/password.c

There are a few key combos that do something in the standard `login` program that don't work with swaylock (sabotaging my muscle memory :wink:). Namely, Ctrl-C restarts login (i.e. clears the password buffer) and Ctrl-D (effectively EOF) submits it.
See the commit messages for more detail.

swaylock: Add some key bindings to emulate login(1)

---

include/sway/commands.h
include/sway/config.h
include/sway/input/cursor.h
sway/commands.c
sway/commands/hide_cursor.c
sway/config.c
sway/input/cursor.c
sway/meson.build
sway/sway.5.scd

Supersedes #1979 
Related to #1894
Allows the cursor to be hidden after a specified timeout in milliseconds. Unlike #1979, `handle_activity` will only set the cursor image when it was previously hidden. This version will also iterate over the seats and update the timeouts for the associated cursors when the timeout is changed.

Implement hide_cursor <timeout> command

---

sway/tree/root.c

To reproduce:
* Launch two terminals in a workspace
* `focus parent` to select both terminals
* `move scratchpad`
* `scratchpad show` to show the terminals
* `scratchpad show` to hide the terminals
* `scratchpad show` - crash
When hiding the terminals, it should be moving focus to whatever is in the workspace, but this wasn't happening because the focus check didn't consider split containers. So the terminals were hidden in the scratchpad while still having focus. This confused the next invocation of `scratchpad show`, causing it to attempt to hide them instead of show them, and the hide-related code caused a crash when it tried to arrange the workspace which was `NULL`.
This patch corrects the focus check.

Fix crash when scratchpad contains split containers

---

sway/input/cursor.c

This fixes a bug in `dispatch_cursor_button` where if there was an
operation occurring, the button would not be removed from the state on
release. This resulted in the button appearing to be permanently pressed
and caused mouse bindings to not match correctly.
This was probably part of the problem for https://github.com/swaywm/sway/issues/2576

Remove button from state on release during op

---

include/ipc.h
sway/ipc-server.c

Related to #3082 
**UPDATE**: It has been decided that sway will not support the i3 sync protocol. This just returns `{'success': false}` when receiving and `IPC_SYNC` request.
<strike>
**PREFACE**
I am not too familiar with x11 terminology so sorry if there are any
incorrectly used terms.
**SUMMARY**
Implements the i3 sync protocol introduced in i3 4.16. This includes two
parts: I3_SYNC and IPC_SYNC.
The protocol ensures that all pending operations for a window have
completed. It was designed for i3 tests, but can be used by other
applications. However since this uses x11 events, it will only be
available in sway for xwayland applications.
**DETAILS**
To request a sync with i3, the client window will send a client message
with the type of the atom by the name of `I3_SYNC`. The client …

Implement i3 sync protocol

---

include/sway/config.h
sway/commands.c
sway/commands/seat.c
sway/commands/seat/attach.c
sway/commands/seat/fallback.c
sway/config/seat.c
sway/input/input-manager.c

This makes seat configs work like output and input configs do. This also
adds support for wildcard seat configs. A seat config is still created
in the main seat command handler, but instead of creating a new one in
the subcommands and destroying the main seat command's instance, the
seat subcommands modify the main one. The seat config is then stored,
where it is merged appropriately. The seat config returned from
`store_seat_config` is then applied. When attempting to apply a wildcard
seat config, a seat specific config is queried for and if found, that is
used. Otherwise, the wildcard config is applied directly.
Additionally, instead of adding input devices to the default seat
directly when there is no seat configs, a seat config for the default
seat is created with only fallback set to …

Revamp seat configs

---

include/sway/input/input-manager.h
sway/config.c
sway/input/input-manager.c

Fixes #3347 
This fixes an issue where on reload, all input devices that were added
via an implicit fallback to the default seat would be removed from the
default seat and applications would crash due to the seat having no
capabilities.
On reload, there is a query for a seat config with the fallback setting
set (it can either be true or false). If no such seat config exists, the
default seat is created (if needed) and has the implicit fallback true
applied to its seat config. This is the same procedure that occurs when
a new input is detected.

Verify seat fallback settings on reload

---

swaybar/status_line.c

status->text should not be freed here. There are two scenarios:
* status->text has been set to an error by status_error. In this case
the value shouldn't be freed because it's always a reference to a
constant.
* status->text has been set to status->buffer because the bar is in
text protocol mode. In this case it's a double free because the
buffer is already freed after.

swaybar: fix double free

---

sway/input/input-manager.c

#3348 did not completely fix the issue of input devices being
removed from the implicit fallback on reload. This should handle
the remaining case(s).
The implicit fallback seat config needs to be applied (if created).
Otherwise, the input devices will still be removed from the implicit
default seat on reload when there is any seat config.

Apply implicit fallback seat config

---

sway/desktop/render.c

See issue #3359 for reproduction details. When a fullscreen view is
unmapped and there's a preceding transaction waiting, there may be
neither a saved buffer or a surface to render. This change matches
the equivalent code in render_view.

Fix fullscreen view rendering crash

---

include/sway/commands.h
include/sway/config.h
include/sway/input/seat.h
sway/commands.c
sway/commands/tiling_drag_threshold.c
sway/config.c
sway/input/cursor.c
sway/input/seat.c
sway/meson.build
sway/sway.5.scd

This is designed to replicate https://github.com/i3/i3/pull/3559 for sway. I was going to wait for that PR to be reviewed and merged, but decided to just do it now. Unlike that PR, this one allows the user to configure the threshold to their liking.
Implements `tiling_drag_threshold <threshold>` to prevent accidental
dragging of tiling containers. If a container (and all of its
descendants) are unfocused and the tile bar is pressed, a threshold
will be used before actually starting the drag. Once the threshold has
been exceeded, the cursor will change to the grab icon and the operation
will switch from `OP_MOVE_TILING_THRESHOLD` to `OP_MOVE_TILING`.

Implement tiling_drag_threshold

---

swaylock/password.c
swaylock/seat.c

Partially fixes #2788. This change makes it so the lock screen is redrawn whenever the caps lock modifier state changes, rather on relying on the keypress event. This didn't work because caps lock is disabled when the key is released, not pressed, so the caps lock indicator does not go away until the next keypress event.
This doesn't fully implement the suggestions in #2788, but is a more basic fix that just makes it so the caps lock indicator is always accurate. I'd be happy to have a go implementng them if anyone's interested, although it doesn't personally seem to me that they'd be that useful.

swaylock: Fix caps lock not updating immediately

---

sway/desktop/transaction.c

Found while packaging on FreeBSD e.g.,
- [12.0 armv7](https://ptpb.pw/a104)
- [12.0 i386](https://ptpb.pw/bxyk)

Unbreak build on 32bit platforms

---

include/sway/input/cursor.h
sway/input/cursor.c
sway/input/seat.c
sway/tree/view.c

After @RedSoxFan implemented hide_cursor command, I noticed that the cursor was not shown between window switches, if container warping is enabled. This PR adds this feature, however I am not sure whether this should be configurable and that the code handles all cases correctly.
Please provide feedback if and how this should be configurable (IMO this only makes sense if container warping is enabled) and review the code, thanks!

Unhide mouse after container warp to focus

---

sway/commands/seat/cursor.c

~**DO NOT MERGE UNTIL AFTER #3334**~
Instead of simulating events on the current seat, this makes it so
seat_cmd_cursor respects the seat name provided by
`seat <name> cursor <args>`. It also adds support for simulating
events on all seats when the wildcard is given.
This also defers the command when reading the config, which allows the
user to set the initial position of the cursor when the command is
included in the config file.

seat_cmd_cursor: work on seat name provided

---

sway/commands/swap.c

Use the handler context seat instead of the default seat in cmd_swap

cmd_swap: use handler context seat

---

sway/commands/bind.c

I think this fixes at least part of #2918. I'm not sure if it completely fixes it
`seat_execute_command` was incorrectly setting
`config->handler_context.seat` before calling `execute_command`. Since
`execute_command` was being called with a `NULL` seat argument,
`execute_command` was setting `config->handler_context.seat` to the
default seat. This resulted in all bindings being executed on the
default seat and causing undesired behavior for devices on other seats.

cmd_bind: pass the seat to execute_command

---

sway/commands/seat.c
sway/config.c

Wait until all seat configs have been read before applying them on
reload. This prevents unnecessary attachment/detachment of input
devices and therefore creation/destruction of seat devices as
individual lines are read.

reload: apply seat cfgs after reading entire cfg

---

sway/commands/bind.c
sway/commands/seat/cursor.c
sway/config.c
sway/input/cursor.c
sway/input/seat.c
sway/ipc-server.c
swaybar/input.c

Same as swaywm/wlroots#1454. libevdev already depends on `<linux/input.h>` from `evdev-proto` package on both FreeBSD and DragonFly.

Simplify FreeBSD build

---

sway/input/cursor.c
sway/tree/output.c

Fixes #3065 
This fixes two causes of segfaulting when an output is destroyed.
The first occurred when an output was never enabled. The issue was that
the destroy signal was never initialized so when it was emitted, sway
segfaulted. This was fixed by moving the initialization into
`output_create` since all outputs, regardless of whether they have ever
been enabled, will be destroyed at some point.
The second occurred when the cursor was on an output that was being
destroyed. The sway output would have already been removed, but if there
are other outputs, a cursor rebase would still occur. Since the
wlr_output still existed and the sway output was destroyed, the cursor
could be over nothing, resulting in a segfault when trying to get the
sway output, which was destroyed.

Fix segfaults on output destruction

---

include/sway/config.h
include/sway/input/cursor.h
sway/commands/bind.c
sway/input/cursor.c
sway/ipc-server.c
sway/sway.5.scd

This is the first of five follow-up PRs to #3313. This extracts the parsing of
mouse buttons into helpers and then uses them for `bindcode` and `bindsym`.
The next four PRs are for `input scroll_button`, `seat cursor`, `bar bindsym`,
and `bar tray_bindsym`.
The following helper functions have been added to aid with parsing mouse
buttons from a string:
1. `get_mouse_bindsym`: attempts to parse the string as an x11 button
(button[1-9]) or as an event name (ex BTN_LEFT or BTN_SIDE)
2. `get_mouse_bindcode`: attempts to parse the string as an event code
and validates that the event code is a button (starts with `BTN_`).
3. `get_mouse_button`: this is a conveniency function for callers that
do not care whether a bindsym or bindcode are used and attempts to parse
the string as a bindsym and then …

Improve mouse button parsing: helpers and bind{code/sym}

---

include/swaylock/swaylock.h
swaylock/main.c
swaylock/render.c
swaylock/swaylock.1.scd

This implements customization for the indicator as proposed in #2788 with comments from #3367 in mind.
The default behaviour does not change exept for the caps lock text color.
@RedSoxFan Could you review this? Thank you :)

swaylock: Add caps lock state to indicator

---

include/swaybar/bar.h
swaybar/bar.c
swaybar/tray/tray.c

Closes #3414
This allows `bar output` and `bar tray_output` to specify an output
identifier. Output names should still work as well.
This parses the output identifier from the xdg_output description,
which wlroots currently sets to `make model serial (name)`. Since this
could change in the future, all identifier comparisons are guarded by
NULL-checks in case the description cannot be parsed to an identifier.

swaybar: allow identifiers for output and tray

---

include/sway/commands.h
include/sway/config.h
include/swaybar/config.h
sway/commands/bar.c
sway/commands/bar/status_edge_padding.c
sway/commands/bar/status_padding.c
sway/config/bar.c
sway/ipc-json.c
sway/meson.build
sway/sway-bar.5.scd
swaybar/config.c
swaybar/ipc.c
swaybar/render.c

Closes #3329 
Related to #3394
Adds the bar subcommand `status_padding <padding>` which allows setting
the padding used for swaybar. If `status_padding` is set to `0`, blocks
will be able to take up the full height of the bar.
Adds the bar subcommand `status_edge_padding <padding>` to set the
padding used when the status line is on the right edge of the bar.

swaybar: adjustable status padding

---

sway/commands/input/events.c
sway/ipc-json.c
sway/sway-input.5.scd
swaymsg/main.c

Closes #2157 
Implements toggling input events during runtime. This will not attempt
to toggle to a mode that is not supported by the device. When toggling
the wildcard input, the device specific input configs are altered. Each
device will cycle one supported mode.
This also adds `libinput_send_events` to the IPC output for `get_inputs`
to allow for custom scripting of mode changes/toggling.

input events: toggle and ipc get_inputs

---

sway/config/bar.c
sway/sway-bar.5.scd
swaybar/render.c

Fixes #3012 
If there is a bar height given, use that as the absolute height rather than as a minimum height. This matches i3-gaps behavior.
Easy test:
1. Use the following minimal config:
```
set $mod Mod4
set $term termite
bindsym $mod+Return exec $$term
bindsym $mod+Shift+e exit
bar bar-0 position top
bar bar-0 height 0
bar bar-0 status_command while date +'%Y-%m-%d %l:%M:%S %p'; do sleep 1; done
bar bar-1 position bottom
bar bar-1 height 25
bar bar-1 status_command while date +'%Y-%m-%d %l:%M:%S %p'; do sleep 1; done
```
2. Execute the command `swaymsg workspace 𒁏` (Unicode character: 0x1204F)
3. Observe `bar-0` (top) increases in height while `bar-1` (bottom) stays the same height

swaybar: obey height if given

---

include/sway/input/input-manager.h
include/sway/input/seat.h
sway/config.c
sway/input/input-manager.c
sway/input/seat.c

This resets all input options to their defaults on reload. This also
fixes some debug log typos in `input_manager_libinput_config_pointer`.
_Note: Without #3386 and/or #3387, reloading may crash due to the
destruction of the keyboard. This can be prevented by adding
`seat seat0 fallback true` to the top of your config while testing this or by
rebasing on top of one or both of the PRs._

reload: reset input configs

---

include/sway/input/cursor.h
include/sway/input/seat.h
include/sway/output.h
include/sway/tree/container.h
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/seat.c
sway/input/seatop_down.c
sway/input/seatop_move_floating.c
sway/input/seatop_move_tiling.c
sway/input/seatop_resize_floating.c
sway/input/seatop_resize_tiling.c
sway/meson.build
sway/tree/container.c

This splits each seat operation (drag/move tiling/floating etc) into a separate file and introduces a `struct sway_seatop_impl` to abstract the operation. This removes a heap of code from cursor.c and seat.c, and removes a bunch of multi-purpose properties from the seat struct.
The `move_tiling_threshold` operation has been merged into `move_tiling`.
The main logic for each operation is untouched aside from variable renames.
The following previously-static functions have been made public:
* `node_at_coords`
* `container_raise_floating`
* `render_rect`
* `premultiply_alpha`
* `scale_box`
Everything seems to work correctly, but I've only tested it hastily. Please test thoroughly.

Refactor seat operations to use an interface

---

sway/commands/input/scroll_button.c
sway/input/cursor.c
sway/sway-input.5.scd

~**DO NOT MERGE UNTIL AFTER #3341**~
This is the second in a series of follow-up PRs for #3313.
This modifies `input_cmd_scroll_button` to utilize the mouse button
helper `get_mouse_button` when parsing the button. x11 axis buttons are
not supported with this command and `CMD_INVALID` will be returned, but
all other x11 buttons, button event names, and button event codes should
be working
This also fixes a typo in `get_mouse_button` that prevented the call to
`get_mouse_bindcode` from being executed.

Improve mouse button parsing: input scroll_button

---

include/sway/input/cursor.h
sway/commands/seat/cursor.c
sway/input/cursor.c
sway/sway-input.5.scd
sway/sway.5.scd

~**DO NOT MERGE UNTIL AFTER #3341**~
This is the third in a series of follow-up PRs for #3313.
This modifies `seat_cmd_cursor` to utilize `get_mouse_button` when
parsing mouse buttons for the `press` and `release` operations. All x11
buttons, button event names, and button event codes are supported.
For x11 axis buttons, `dispatch_cursor_axis` is used instead of
`dispatch_cursor_button`. However the `press`/`release` state is ignored
and the either axis event is processed. This also removes support for
`left` and `right` in favor of `BTN_LEFT` and `BTN_RIGHT`.
Note: #3342 has a fix for a typo in `get_mouse_button` that prevents the call to
`get_mouse_bindcode` so in order to test bindcodes, rebasing against that PR
is currently necessary

Improve mouse button parsing: seat cursor buttons

---

include/sway/commands.h
include/sway/config.h
include/sway/server.h
sway/commands.c
sway/commands/xwayland.c
sway/config.c
sway/main.c
sway/meson.build
sway/server.c
sway/sway.5.scd

This allows xwayland to be disabled at runtime.
Xwayland needs to be started in `server_start`, after the config has been read.
Closes https://github.com/swaywm/sway/issues/2965

Add xwayland command

---

swaynag/config.c

Set config path to fallback instead of setting $XDG_CONFIG_HOME

swaynag: handle empty $XDG_CONFIG_HOME better

---

sway/commands/resize.c

This patch removes the `resize_axis` enum in favour of `wlr_edges`. As `wlr_edges` has no `horizontal` or `vertical` value, it denotes these by bitwise `or`ing the left/right and up/down values. Two constants are defined to make it easier to refer to these.
This will allow the tiling resize seatop to utilise the functions in this file. `resize_axis` was local to the resize command and couldn't be exposed in function arguments.
This is progress towards #3253.
The function `container_resize_tiled` used to convert from a `wlr_edges` to a `resize_axis`, and now just passes the values through. This function is public and will be cleaned up as part of #3253.

Replace resize_axis with wlr_edges

---

CONTRIBUTING.md

Follow-up to https://github.com/swaywm/sway/pull/3403#issuecomment-453995544
Adds a note about assuming a tab width equal to 4 spaces when
determining the line length to CONTRIBUTING.md

CONTRIBUTING.md: mention tab width for line length

---

include/sway/input/keyboard.h
sway/input/keyboard.c
sway/input/seat.c

Fixes #3420
When resetting the keyboard during reload, disarm the key repeat on all
keyboards since the bindings (and possibly keyboard) will be freed before
the key repeat can go off.

Disarm key repeat on reload

---

include/sway/commands.h
sway/commands/resize.c
sway/input/seatop_resize_tiling.c

For example, create layout `V[view view view]` and resize the leftmost view using mod+rightclick. Previously, the edge between view 2 and 3 would be adjusted as well. Now this edge will remain constant, which matches the behaviour of i3.
To do this operation correctly, the resize tiling seatop now keeps track of two containers, as the container that resizes horizontally will be a different container to the one which resizes vertically (one will be an ancestor). The tiling resize seatop now figures out these containers during the start of the operation and keeps references to them in the event. A new function `container_find_resize_parent` has been introduced to do this. This function is also used by the resize command.
During cursor motion, the seatop logic is similar to before, but now …

Resize only current and immediate siblings rather than all siblings

---

sway/commands/floating.c
sway/commands/move.c
sway/commands/resize.c
sway/commands/split.c
sway/commands/sticky.c
sway/tree/root.c

Fixes #3236
This fixes the handling of hidden scratchpad containers for some
commands. For the most part, this just prevents running the commands on
hidden scratchpad containers, but there are some commands that have some
special handling for them.

Handle hidden scratchpad containers in commands

---

sway/tree/view.c

Fixes #3263 
Fixes #3286 
Fixes #3406
In `view_child_damage`, do not damage the surface if it has been
unmapped or if the container is NULL.

Do not damage view child when container is NULL

---

sway/main.c

Related to #3433 
In `sway_terminate`, `ipc_event_shutdown` was being sent regardless
which mode sway was running in. When running as an ipc client,
`sway_terminate` should just exit

Do not send ipc_event_shutdown from ipc client

---

sway/input/seatop_down.c

Fixes #3436 
In `seatop_begin_down`, raise the floating container. This appears to
have been dropped in the transition to seatops (https://github.com/swaywm/sway/pull/3402/files#diff-57d5973ad58d843753d353531e8cb85eL1039)

seatop_begin_down: raise floating

---

sway/commands/resize.c

Fixes https://github.com/swaywm/sway/pull/3430#discussion_r248157954
Allow resizing a hidden scratchpad container by px. Resizing a hidden
scratchpad container by ppt is still not allowed since there is no
workspace

cmd_resize: allow resizing hidden scratchpad by px

---

sway/desktop/layer_shell.c

Fixes #3433 
Related to #2337
If there are no outputs, do not SIGABRT when a layer surface is created,
just close the layer surface.

layer_shell: do not SIGABRT sway on zero outputs

---

include/sway/output.h
sway/desktop/output.c
sway/tree/output.c

Simplify the code by registering signals when outputs are created and removing
signals when they are destroyed.

output: remove output_add_listeners

---

swaybar/tray/icon.c

Memory leaks were found with AddressSanitizer. Two were simple unfreed allocations; the other was a call to `opendir` without a corresponding call to `closedir`.

Fix memory leaks in swaybar tray initialization

---

common/ipc-client.c

When environment variables I3SOCK and SWAYSOCK are cleared, the fallback to calling  `sway --get-socketpath` handled errors for [getline](https://linux.die.net/man/3/getline) incorrectly, relying on the fact that newly allocated memory is almost always zeroed out. (Also, the trailing newline was not removed.)

Fix backup methods in get_socketpath for IPC client

---

sway/desktop/output.c

If output->configured is true, then the output has been modeset correctly and
we don't need to try again. If output->enabled is true, then we are in the
process of configuring the output and we shouldn't do anything.
With https://github.com/swaywm/wlroots/pull/1479, this PR makes it so various sequences of hotplugging and/or enabling/disabling outputs work properly. For instance, this is now possible on a laptop only supporting two outputs:
* Start with the internal screen connected and nothing else
* Plug in the laptop on a dock with two external outputs connected, one of them turns on, the other doesn't (limit reached, no more CRTC)
* Disable the internal screen, the other external output turns one (CRTC moved from internal screen to the external one)
* Enable the internal screen again, …

Fix re-enabling outputs gaining a CRTC

---

.gitignore
common/pango.c

Almost forgot about this. See [here](https://github.com/swaywm/sway/pull/3438/files/338a8c051df8290eb7863ba0c566139747b7b224#r248228815) (annoyingly this doesn't link directly to the comment. It's in one of the resolved conversations...).

Allocate minimum size necessary in pango text functions.

---

sway/input/input-manager.c

This add errors from calls to `libinput_device_config_*_set` to the
debug log. This may be useful when looking at issues related to input
devices and config settings not working.

Log libinput_config_status errors

---

client/meson.build
common/meson.build
common/util.c
include/cairo.h
include/sway/input/keyboard.h
include/sway/output.h
include/util.h
sway/commands/bar/modifier.c
sway/commands/bind.c
sway/commands/floating_modifier.c
sway/config/bar.c
sway/input/keyboard.c
sway/ipc-server.c
sway/tree/output.c
sway/tree/root.c
swaybar/meson.build
swaybg/meson.build
swaymsg/meson.build
swaynag/meson.build

This PR:
* Moves functions in `common/util.c` that are specific to the main sway executable to the best corresponding places in the `sway/` subdirectory that I could find.
* Fixes an edge case bug in `numlen`, removing the use of `log10` from libm
* Removes wlroots (and sometimes libm) dependencies from subfolders `common/`, `client/`,  `swaybar/`, `swaybg/`, `swaymsg/`, and `swaynag/`.
Closes #3476.

Remove wlroots dependency for sway(bar|bg|msg|nag)

---

swaynag/render.c

I noticed this a long time ago but only just got round to fixing it. 
Before:
After:
(screenshots taken with slurp + grim... god I love Wayland)

swaynag: Small graphical fix, add offset of +1 to X/Y.

---

sway/input/seat.c

Fixes #3458 
This sets the initial focus for all seats other than the first seat,
which gets it focus on launch. The ensures that all seats have
something focused.

seat_create: set initial focus for added seats

---

include/sway/server.h
include/sway/tree/root.h
sway/commands/output.c
sway/commands/output/enable.c
sway/config/output.c
sway/desktop/output.c
sway/ipc-server.c
sway/server.c
sway/tree/output.c
sway/tree/root.c
sway/tree/view.c
sway/tree/workspace.c

Instead of having `NULL` `workspace->output` pointers, use a <s>headless</s> noop output. This should be safer.
I've tested this with the wayland backend by closing the output window and then using swaymsg to connect to the socket and run the `create_output` command. Upon creation, I had some issues with the alignment of the first output's contents within the output window, but I'm not sure this is related to my change.
I have not tested on DRM yet.
The output is returned in the IPC `get_outputs` list, so perhaps we should hide it. Also, we never enable the output (we never have to), so perhaps we should add a check to make sure it can't be enabled using config or IPC.

Use noop output when there's no outputs connected

---

common/util.c
include/util.h
sway/commands/bar.c
swaybar/ipc.c

Its uses have been replaced by snprintf, which is more in line with its usage.
Also cleaned headers.

util.c: remove numlen function

---

sway/commands/move.c
sway/commands/scratchpad.c
sway/tree/root.c

Fixes #3461
This removes the call to `root_scratchpad_show` from
`root_scratchpad_remove_container` and places it in the
`cmd_move_container`. This also moved the IPC `window::move` event to
`cmd_scratchpad`.

root_scratchpad_remove_container: do not show 

---

sway/commands/floating.c
sway/commands/sticky.c
sway/tree/container.c

1. Allow tiled containers to be stickied
This also stops stickied containers from losing its sticky status when
it is tiled, allowing it to be immediately stickied when floated again.*
2. Allow setting floating on scratchpad containers
* There's a quirk in i3 that if the container is not on the active workspace when floated (and is sticky), it is not moved to the current workspace, but sticks when switching to that workspace. This matches that behaviour, though I'm not sure if it is a bug.
I've tested it a bit, but not sure if I've missed some edge case.
Looking into it more, it seems like there are a number of commands that, if run on hidden scratchpad containers, result in failure on sway but success on i3 (though I haven't tested which ones), so if compatibility is the goal then …

i3 command behaviour compatibility fixes

---

client/pool-buffer.c
sway/commands/focus.c
sway/commands/resize.c
sway/desktop/layer_shell.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/tree/root.c
sway/tree/view.c
swaybar/tray/item.c
swaynag/render.c

`ninja scan-build` was used to invoke the [clang static analyzer](https://clang-analyzer.llvm.org/). 
In addition to removing unused code, two minor problems are fixed:
* `resize set` and `resize adjust` did not yield an error when given too many arguments. Now
bindsym Ctrl+Return resize set width 400 px height 400 px
still works, but the following fails:
bindsym Ctrl+Return resize set width 400 px height 400 px oops
* `orientation` was incorrectly overridden to be 'U' for scroll events in the swaybar tray `handle_click` function.

Fix dead stores found by scan-build

---

swaybar/ipc.c

Escape quotes and backslashes, allowing switching to workspace names
like "1" (including quotes) and \

swaybar: fix workspace command

---

swaybar/ipc.c

Fixes https://github.com/swaywm/sway/commit/d8f3e6e19a12514ed6f8c8f470b89fde0f39dc59#commitcomment-32026156
This fixes a typo on the malloc line in ipc_send_workspace_command. The
plus one to the size for the null-terminator was outside of the malloc
call, which was causing the incorrect pointer to be freed later in the
function.

swaybar: fix command malloc in workspace command

---

swaybar/tray/item.c

Apparently, IconThemePath needs to be reread on NewIcon signal.
This fixes tray icon updates in electron apps with libappindicator-gtk3.

Fix tray icon updates

---

swaynag/config.c

Build problem was introduced in commit d7ff7765. Here, unistd.h was removed from utils.h, but 
swaynag/config.c needs to include it. 
Sway master was failing to build on Fedora 29 without this fix:
```
Found ninja-1.8.2 at /usr/bin/ninja
[211/220] Compiling C object 'swaynag/183c222@@swaynag@exe/config.c.o'.
FAILED: swaynag/183c222@@swaynag@exe/config.c.o 
ccache cc -Iswaynag/183c222@@swaynag@exe -Iswaynag -I../swaynag -Iinclude -I../include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g …
```

Fix build failure in config.c

---

include/sway/tree/container.h
include/sway/tree/root.h
sway/commands/focus.c
sway/commands/fullscreen.c
sway/commands/move.c
sway/commands/split.c
sway/commands/swap.c
sway/commands/workspace.c
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/seat.c
sway/ipc-json.c
sway/sway.5.scd
sway/tree/arrange.c
sway/tree/container.c
sway/tree/root.c
sway/tree/view.c

The fullscreen container is stored in the root struct.
I'm not sure how it's supposed it behave in regards to using `fullscreen disable` or `fullscreen toggle` (without global) while the container is fullscreen global. Or whether a container can be both workspace-fullscreen and global-fullscreen at the same time.
I've added checks in the `focus` and `workspace` commands to prevent moving focus off the fullscreen global container. Not sure if similar checks are needed elsewhere or whether they should go in `seat_set_focus` instead.
Please test thoroughly.
Closes #3255.

Implement fullscreen global

---

README.md

scdoc is outdated on Fedora 29 (it was ~1.3.0 or something like that) and probably is on many other distros, so I wasn't able to generate manpages until I built the latest version.

Add note about required scdoc version to README.

---

include/sway/tree/container.h
sway/commands/focus.c
sway/commands/move.c
sway/commands/resize.c
sway/commands/split.c
sway/commands/sticky.c
sway/desktop/output.c
sway/desktop/render.c
sway/ipc-json.c
sway/tree/container.c
sway/tree/root.c
sway/tree/view.c

Just a convenience function that improves readability of the code.
Other things worth noting:
* `container_get_siblings` and `container_sibling_index` no longer use the `const` keyword.
* `container_handle_fullscreen_reparent` is only ever called after attaching the container to a workspace, so its `con->workspace` check has been changed to an assertion.

Introduce container_is_scratchpad_hidden

---

sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/tree/container.c

After some debugging I found the reason for the crash in #3311. The problem was
that I ended up with a toplevel child whos parent had unmapped.  So the child's
`xdg_surface->toplevel->parent` pointed to an `xdg_surface` with its role set
to `WLR_XDG_SURFACE_ROLE_NONE` and its `xdg_surface->toplevel` pointer freed.
The function `surface_is_popup` didn't check this case, which led to a segfault
when setting `xdg_surface = xdg_surface->toplevel->parent;`.  I searched for
similar occurrences and found one in the function `is_transient_for`, where I
also added a check (I was able to reproduce a segfault there too).
Despite that this patch fixes my crash, I know too little about how xdg shell
works, to be confident that this is the right fix. I don't know if it is normal
that a child points to …

Check xdg_surface's role before using its toplevel

---

sway/main.c

SWAY_CURSOR_* are not used anymore. LD_PRELOAD_PATH doesn't exist and has been
replaced with LD_PRELOAD.

Cleanup log_env

---

sway/tree/container.c

The assertion could trigger when called from `workspace_wrap_children`.
Fixes #3527.

Remove bad assertion in container_handle_fullscreen_reparent

---

sway/sway-output.5.scd

Add a sentence to sway-output.5.scd to highlight that the cursor can
only be moved between immediately adjacent outputs.
References issue #3529
Signed-off-by: Peter Grayson <pete@jpgrayson.net>

Document cursor moving between adjacent outputs

---

include/sway/config.h
sway/config.c
sway/main.c

Related https://www.reddit.com/r/swaywm/comments/akqofn/sway_wont_start_at_all_on_intel_graphics/
This cleans up the log when sway fails to read a config file. The
following changes have been made:
- A missing error message has been added to the log when the config file
is a directory instead of a regular file
- In main, `goto` statements have been added after the `sway_terminate`
calls instead of wrapping every block in `if (!terminate_request)`
- Unnecessary NULL-checks around calls to free in `main` have been
removed
- Deferred command execution has been extracted to a separate function
and the `Running deferred commands` log message will not be shown when
there are no deferred commands.

Cleanup config reading failure error logs

---

sway/commands/scratchpad.c

sway version 1.0-beta.2-274-g5f45a4bb (Jan 27 2019, branch 'master')
example:
1) mark window en scratchpad
2) show it
3) change workspace
Need send swaymsg "[con_mark="mark"] scratchpad show  twice for show it.
short explain. 
set $criteria swayTerm
for_window [app_id="(?i)$criteria"] floating enable, resize set 800px 400px, move position 1110px 10px, move to scratchpad, scratchpad show, mark $criteria
bindsym Menu exec (pgrep -a $term| grep $criteria) && \
(swaymsg "[con_mark=$criteria ] scratchpad show"  || \
swaymsg "[tiling con_mark=$criteria] move container to workspace current, move to scratchpad, scratchpad show, resize set 800px 400px, move position 1110px 10px") || \
exec $term --name $criteria
Need press Menu key twice if show in another workspace. ($term is termite)

criteria & scratchpad verify if show in another workspace

---

include/sway/commands.h
include/sway/config.h
include/sway/input/cursor.h
include/sway/input/seat.h
include/sway/server.h
protocols/meson.build
sway/commands.c
sway/commands/pointer_constraint.c
sway/config/seat.c
sway/input/cursor.c
sway/input/seat.c
sway/input/seatop_down.c
sway/meson.build
sway/server.c
sway/sway.5.scd

It's fully functional and has been tested with the example wlroots clients, although there is one thing I'd like to fix, which I'd like input from you on how to fix it:
In `sway/input/cursor.c` I duplicate some code from wlroots, because the code from wlroots isn't always run before this function runs, since the focus will be moved to the new surface before all surface commit listeners have been executed. If you remove the duplicated code, pointer constraints will still work fine, but the cursor won't always be able to warp into the region, which can be quite annoying for the user.
The duplicated code (`sway/input/cursor.c:1433`):
```c
// FIXME: Big hack, stolen from wlr_pointer_constraints_v1.c:121.
// This is necessary because the focus may be set before the surface
// has finished …
```

Implement pointer-constraints-unstable-v1 and relative-pointer-unstable-v1

---

sway/sway.5.scd

Updates sway.5 to include information on the usage of the `--whole-window` option in the context of the `bindsym` command, which modifies mouse bindings to allow them to operate over the whole window instead of just the titlebar. Also includes the disclaimer about mouse bindings only working over the title bar.
Also fixes the escaping of the `BTN_LEFT` and `BTN_RIGHT` key mention.

Add details on `--whole-window` for bindsym

---

swaybar/tray/icon.c

Fixing typo error while matching "Inherits" parameter of theme configuration file.

Fix #3445: swaybar tray inherited themes not processed

---

sway/commands/seat.c
sway/sway-input.5.scd

This allows for `-` (hyphen) to be used as an alias for the current seat
while sway is running. This alias was chosen since it is unlikely to
interfere with any desirable seat identifier

cmd_seat: allow - to be used as alias for current

---

sway/config.c
sway/input/cursor.c

This fixes a couple of issues that led to the below traceback:
- `destroy_removed_seats` should not attempt to operate on the wildcard seat config if one is present
- `sway_cursor_constrain` should fall back to the wildcard seat config when checking if constraints are disabled
- It should also bail if no config could be found at all
To reproduce this crash in master, issue something like `swaymsg seat * hide_cursor 0` (to cause the wildcard config to be present) and then reload the config.
```
(gdb) bt full
#0  0x000055c371d839e6 in sway_cursor_constrain (cursor=0x55c372d01890, constraint=0x0)
at ../sway/sway/input/cursor.c:1462
config = 0x0
#1  0x000055c371d7a76d in seat_send_focus (node=0x55c372c79160, seat=0x55c372d86680)
at ../sway/sway/input/seat.c:112
keyboard = 0x0
constraint = 0x0 …
```

Fix wildcard seat constrain crashes during reconfig

---

include/sway/input/input-manager.h
sway/commands/seat/cursor.c
sway/config.c
sway/input/input-manager.c

If a seat does not exist in seat_cmd_cursor, do not create it. A seat
without any attachments is useless since it will have no capabilities.
This changes `input_manager_get_seat` to have an additional argument
that dictates whether or not to create the seat if it does not exist.

seat_cmd_cursor: do not create non-existing seat

---

sway/input/cursor.c

Fixes #3552. I'm pretty sure that passing through the potential NULL here is the right thing to do, since seat_set_focus handles it, but if not I can add a check for that.

Focus workspace inactive node with focus_follows_mouse

---

sway/config.c

Fixes #3565 
This fixes the failure condition for the wordexp call in
load_include_configs. The only success value is zero. Since the error
codes are positive, having the check be less than zero was causing
segfaults on failure when accessing the words.

load_include_configs: fix wordexp fail condition

---

swaynag/config.c

Fixes #3571 
Now that swaynag uses getline (instead of the old readline), the
trailing newline characters have to be removed when reading the config

swaynag: remove trailing newlines in config

---

sway/commands.c

This removes quote stripping for `exec_always` in `execute_command`.
Since `exec_always` commands will be deferred in the config and
processed by `execute_command`, the quotes need to be left intact
like they are for `exec`.

execute_command: dont strip quotes for exec_always

---

sway/commands.c

Let's not use `!strcmp(…)` anymore.
Fixes https://github.com/swaywm/sway/issues/3575

Fix quote stripping

---

meson.build
meson_options.txt

Let's set the version in the meson file instead of declaring it outside.
In case git is installed we use the git hash as version. Instead it
isn't (like on a clean build system), let's use the version defined in
the project.

Set version in project file

---

sway/ipc-server.c

Related to #3566 
This splits commands given in IPC_COMMAND on newline to match i3's behavior.

IPC_COMMAND: split on newline

---

sway/commands/workspace.c

Fixes #3577 
This fixes a double free in cmd_workspace_gaps when the amount given is
invalid. The end pointer from strtol is part of the argument and should
not be freed. Freeing the end pointer could result in a double free or
bad free depending on whether or not the end pointer was at the start of
the argument

cmd_workspace_gaps: fix double free on bad amount

---

sway/main.c

I may be missing something, but I can't see why we would initialize the server and IPC when we only want to validate the config file. It was causing a memory leak (not that it matters since Sway exits almost immediately) due to the server not being destroyed.
This change has the caveat that various debug information in wlroots code won't appear.
I also think that verbose logging when validating a config file is unnecessary, but I won't submit that change unless others agree.

If validating the config, do it as early as possible.

---

common/stringop.c
sway/commands/output/background.c

Fixes #3580 
If output_cmd_background is given a valid mode as the first argument,
then there is no file given and an error should be returned.
join_args should not be called with an argc of zero since it sets the
last character to the null terminator. With an argc of zero, the length
is zero causing a heap buffer overflow when setting the byte before the
start of argv to '\0'. This probably will not ever generate a segfault,
but may cause data corruption to whatever is directly before it in
memory. To make other such cases easier to detect, this also adds a
sway_assert in join_args when argc is zero. 
_If desired, I can split the second part into a separate commit or PR_.

output_cmd_background: fix no file + valid mode

---

sway/desktop/xdg_shell.c

wlr_xdg_popup_destroy will destroy popups, so we need to walk the tree
carefully. It's enough to just destroy all direct children, since destroying
the parent will also destroy all children.

Fix close_popups for xdg-shell

---

sway/config.c

Fixes #3589 
Since `load_include_config` compares against the realpath of a config
file when checking if a config has already been added, the main config's
realpath has to be added to the config_chain.

load_main_config: add realpath to config_chain

---

sway/ipc-server.c

`subscribed_events` is a bit mask, with each *set* bit representing an
event the client has subscribed to.
This fixes #3560

ipc_has_event_listeners: fix inverted check of subscribed_events

---

sway/config.c

Fixes #3590.
This makes two assumptions:
- A wildcard path pointing to an empty directory or non-existent directory is OK
- An error should be thrown if the included path does not exist and it is not a wildcard path

Return false if config could not be loaded.

---

sway/main.c

When both options and positional arguments are given, sway would print
the error `Don't use options with the IPC client`. Over the past
several months, it seems like a large number users are including this error
message in issues instead of a debug log due to not understanding that
the error message means there is an issue with their command.
This makes the error message more verbose and will hopefully make it so
more users understand that the message is not a bug in sway, but with
the command used.

Clarify error for options and positional args

---

sway/config.c

Fixes #3605 
Since `load_include_config` compares against the realpath of a config
file when checking if a config has already been added, the main config's
realpath has to be added to the config_chain.
However, includes from the main config should be processed relative to
the path given to allow for symbolic links. This stores the realpath in
`config->config_chain`, but uses the given path for all other
operations.

load_main_config: use given path, store realpath

---

sway/input/seat.c

Fixes #3512 
Since a tablet tool provides the WL_SEAT_CAPABILITY_POINTER capability,
sway will attempt to use the xcursor manager to set a cursor image. If
the tablet tool was the first (and possibly only) device to provide the
capability for the seat, the xcursor manager was not being configured
before attempting to set a cursor image. This was due to
`seat_configure_xcursor` only being called in `seat_configure_pointer`.
Since the xcursor manager was NULL in this case, it would cause a
segfault when attempting to set a cursor image. This adds a call to
`seat_configure_xcursor` in `seat_configure_tablet_tool` to ensure that
the seat has a xcursor manager.
@YaLTeR, can you please test this and confirm that it fixes your issue? I think
this should fix it, but I do not have a tablet tool to …

seat_configure_tablet_tool: configure xcursor

---

sway/commands/bar/modifier.c
sway/input/keyboard.c

Fixes #3601 
sway-bar(5) documents `modifier none`, which comes from i3. This
implements the functionality for `modifier none` since it was not
previously implemented. The bar modifier toggles visibility of the bar
when the bar mode is set to hide. When the bar modifier is set to
`none`, the ability to toggle visibility of the bar will be disabled.

bar_cmd_modifier: add support for none

---

sway/tree/container.c

Fixes #3618
It is possible to make the title bars have a zero pixel height while
stacked, by using a blank font and no padding. This causes a division by
zero when attempting to calculate the child index in
container_at_stacked, which then results in a segfault when attempting
to access the child at that bad index (INT_MIN). This just skips the
check to see if the cursor is over a title bar of a child of a stacked
container when the title bar height is zero since there will be no title
bars.

container_at_stacked: skip titles when zero pixels

---

sway/commands/bar/mode.c

If the bar was set to "invisible" and subsequently "toggle" was send twice, the
new mode was never set and the bar->mode was double freed.
Fix this by not requiring the bar->mode to be "hide" and instead show it
unconditionally, because it was either hidden or invisible.
Fixes #3637

fix double free for mode toggle if bar was invisible

---

sway/input/keyboard.c

Fixes #3640 
If `repeat_rate` or `repeat_delay` is set without the other being set,
the default was being used for both. This changes the logic to respect
the value given and use the default for the other when only one is set.

input/keyboard: respect solo repeat_{rate,delay}

---

sway/tree/view.c

Fixes #3599 
If the view has any pointer constraints, ensure they are removed
before the view is unmapped and the surface is no longer tied to the
view.

view: remove pointer constraints on unmap

---

sway/ipc-json.c
swaymsg/main.c

Fixes #3639 
If the active xkb_layout does not have a name, use `NULL` instead of
`json_object_new_string(NULL)`. This also makes it so swaymsg will pretty
print this as `(unnamed)`.

ipc: handle unnamed xkb_active_layout_name

---

sway/commands/seat.c
sway/config.c
sway/config/bar.c

This fixes a few misc memory leaks reported by asan:
- Items of `config->config_chain` are now freed instead of just the list
itself
- `bar->swaybar_command` is now freed
- The result returned by a seat subcommand is now returned instead of
leaked

fix misc memory leaks

---

sway/main.c

Fixes #3187 
This aborts sway and displays an error message about XDG_RUNTIME_DIR
not being set without initializing the wl_display or logging any other
information.

Abort early when XDG_RUNTIME_DIR is not set

---

sway/tree/workspace.c

Fixes #3616 
When a layer surface is focused, `seat_get_focused_workspace` will be
NULL. This changes `workspace_get_initial_output` to use output of the
focus inactive. If the focus inactive is also NULL, then either the
first output or the noop output will be used as fallbacks.

workspace_get_initial_output: handle focused layer

---

include/sway/input/cursor.h
sway/desktop/layer_shell.c
sway/desktop/transaction.c
sway/input/cursor.c

Also removes an extraneous arrange_outputs call, it's already called if
necessary in arrange_layers.
Updates https://github.com/swaywm/sway/issues/3080

Rebase cursor when a layer surface maps

---

sway/tree/view.c

Fixes #3671 
It is possible for `wlr_surface_is_subsurface` to return true, but
`wlr_surface_from_wlr_surface` to be NULL. This adds a NULL check to the
value returned by `wlr_surface_from_wlr_surface` and breaks out of the
while loop in `subsurface_get_root_coords`.

subsurface_get_root_coords: break on NULL

---

sway/input/seatop_move_tiling.c

When moving a descendant of a tabbed or stacked container, it is possible
for the target node to be the node being moved. This causes a segfault in
`handle_finish` since the node will be detached and then attempted to be
attached to it own parent, which is NULL due to the detach. In this
case, the target node should not be set to the node being moved, but the
parent of the node. This also allows for a descendant of a tabbed or
stacked container to be dragged out of the tabs/stacks and to be a
sibling of the tabbbed/stacked container, which was not previously
possible.
Create `T[viewa V[viewb]]` with only one output and focus viewb. Attempt to
drag it to the left or right side of the monitor. On the current master, this will
segfault. With this PR, it should create `H[T[viewa] viewb]`.

seatop_move_tiling: use tab/stack parent not self

---

sway/input/seat.c
sway/tree/workspace.c

Fixes #3615 
This allows the focused inactive tree node and visible workspaces to be
changed while a surface layer has focus. The layer temporarily loses
focus, the tree focus changes, and the layer gets refocused.

seat: allow tree focus changes while layer focused

---

sway/input/seatop_move_tiling.c

In seatop_move_tiling, it is possible to cause a stack overflow by
dragging a container into one of its descendants. This disables the
ability to move into a descendant.

seatop_move_tiling: do not move to descendant

---

sway/config/output.c

Fixes #3688 
On the DRM backend, if an output is dpms'd off and a different output is
hotplugged, the CRTC for the output is reclaimed. When modesetting an
output without a CRTC, a CRTC will not be given to an output that is not
desired to be enabled. This splits setting the dpms state in
apply_output_config. If the output should be dpms on, the it is enabled
before attempting to modeset. Otherwise, it is dpms'd off after setting
everything else.

apply_output_config: dpms on before modeset

---

sway/input/cursor.c

This fixes issues of clients at the edge of the screen, like swaybar, ignoring buttons.
Fixes https://github.com/swaywm/sway/issues/3594

Check layout before getting pointer surface coords

---

include/sway/config.h
sway/config.c
sway/config/output.c

Fixes #3685 with swaywm/wlroots#1545 -- which was
reverted in swaywm/wlroots#1550 due to #3685
On master, all output configs are applied on reload. This may cause an
output to have its config applied up to three times, instead of just
once. The three cases are: output name, output identifier, and wildcard.
Not only is this inefficient, but it can cause swaybg to be spawned and
immediately killed.
However, swaybg requires two roundtrips of wl_display (to obtain needed
globals) before it enters its normal event loop. Modesetting will
roundtrip the wl_display. Without modesetting, waitpid for killing
swaybg could block infinitely due to swaybg being blocked by
wl_display_roundtrip.
This only configured an output once. It either uses the wildcard config
or creates an empty wildcard config and …

Fix reload freeze when not modsetting current mode

---

sway/sway-input.5.scd

See https://github.com/swaywm/sway/issues/3703#issuecomment-464391058
This documents the wildcard character for both inputs and seats. There
is also a tip added on trying the wildcard to verify a setting if the
identifier does not appear to be working.

sway-input.5: document wildcard and id troubleshooting

---

include/sway/output.h
sway/config/output.c
sway/desktop/output.c
sway/tree/output.c

This is much more reliable. This also fixes race conditions when killing swaybg
while it's doing a wl_display_roundtrip.

Disconnect swaybg instead of killing it

---

sway/tree/workspace.c

This changes `workspace_next_name` to use the next available number as
the workspace name instead of the number of outputs. This fixes the case
where a number that is already in use could be returned. The workspace
numbers in use have no relation to the number of outputs so it makes
more sense to use the lowest available number

workspace_next_name: fallback to next available number

---

sway/commands/bind.c
sway/sway.5.scd

This matches i3's behavior of executing mouse bindings in regards to the
container under the cursor instead of what is focused.
[i3 User Guide 4.4](https://i3wm.org/docs/userguide.html#mousebindings): A mouse binding makes i3 execute a command upon pressing a specific mouse button **in the scope of the clicked container**

Use container under cursor for mouse bindings

---

sway/commands/seat/cursor.c

This just fixes a typo in the expected syntax for seat_cmd_cursor

seat_cmd_cursor: fix typo in expected syntax

---

sway/ipc-json.c

This greatly simplifies the `jq` query for https://github.com/emersion/slurp/pull/28.

Feature: Add 'visible' key to view json response

---

sway/tree/output.c

This calls `workspace_consider_destroy` on the workspace that was
visible on an output that a workspace was just evacuated to. This
prevents having hidden empty workspaces.

output_evacuate: call workspace_consider_destroy

---

sway/desktop/output.c

Fixes #3658 
Fixes #3654 
Fixes #3043 
If an output's node was dirty and the transaction was committed before a
workspace was moved to or created for the output, the instruction would
have a bad value for `state->active_workspace` due to a missing
length check in `output_get_active_workspace`. If there was no focus on
the output, the first workspace was being returned. If the workspace
list was currently empty, the value was either garbage, or in the case of
an output being disabled and re-enabled, a workspace that may have been
previously freed. This just adds the length check to avoid returning out
of bounds value.

output_get_active_workspace: check workspaces length

---

sway/commands/focus.c
sway/commands/move.c
sway/commands/sticky.c
sway/commands/swap.c
sway/commands/titlebar_border_thickness.c
sway/desktop/output.c
sway/input/cursor.c
sway/ipc-json.c
sway/tree/container.c
sway/tree/output.c

Follow-up for #3743 
This modifies the places where output_get_active_workspace is called to
handle a NULL result. Some places already handled it and did not need a
change, some just have guard off code blocks, others return errors, and
some have sway_asserts since the case should never happen. A lot of this
is probably just safety precautions since they probably will never be
called when `output_get_active_workspace` is not fully configured with a
workspace.

Handle NULL from output_get_active_workspace

---

sway/commands/move.c

Commit d3d7956576341bbbfb60d045175b0e8a44752e0b removed this NULL check, which
leads to the following backtrace:
```
#0  0x0000557bd201df46 in node_is_view (node=0x0) at ../sway/sway/tree/node.c:41
#1  0x0000557bd1ff5d4e in seat_get_focus_inactive (seat=0x557bd3fc7580, node=0x0) at ../sway/sway/input/seat.c:968
current = 0x557bd2033485
#2  0x0000557bd2009f24 in cmd_move_container (argc=3, argv=0x557bd46b19c0) at ../sway/sway/commands/move.c:557
new_output_last_focus = 0x0
error = 0x0
node = 0x557bd469f360
workspace = 0x557bd4572ee0
container = 0x557bd469f360
no_auto_back_and_forth = false
seat = 0x557bd3fc7580
old_parent = 0x0
old_ws = 0x557bd4572ee0
old_output = 0x557bd411f740
destination = 0x557bd46a0cc0
new_output = 0x557bd411f740
new_output_last_ws = 0x0
focus = 0x557bd469f360 …
```

commands/move: reintroduce wrongly removed NULL check

---

sway/commands/move.c

Fixes #3748
This makes it so running `move [to] scratchpad` on a container already
in the scratchpad does not return an error. To match i3's behavior, a
visible scratchpad container will be hidden and a hidden scratchpad
container will be treated as a noop.

move scratchpad: hide visible scratchpad container

---

sway/input/cursor.c
sway/sway.5.scd

Fixes #3750 
To match i3's behavior, this allows mouse bindings to be triggered over
a workspace when `--whole-window` is given.

input/cursor: allow whole-window bindings on ws

---

sway/desktop/xdg_shell.c
sway/xdg_decoration.c

Fixes heap-use-after-free:
```
==32046==ERROR: AddressSanitizer: heap-use-after-free on address 0x615000064d20 at pc 0x55571ce4d303 bp 0x7fff545c64c0 sp 0x7fff545c64b0
WRITE of size 8 at 0x615000064d20 thread T0
#0 0x55571ce4d302 in xdg_decoration_handle_destroy ../sway/xdg_decoration.c:13
#1 0x7f64009d6f36 in wlr_signal_emit_safe ../util/signal.c:29
#2 0x7f64009d3c46 in toplevel_decoration_handle_resource_destroy ../types/wlr_xdg_decoration_v1.c:65
#3 0x7f6400a19f8d  (/usr/lib/x86_64-linux-gnu/libwayland-server.so.0+0x7f8d)
#4 0x7f6400a19fed in wl_resource_destroy (/usr/lib/x86_64-linux-gnu/libwayland-server.so.0+0x7fed)
#5 0x7f64009d3d1f in toplevel_decoration_handle_surface_destroy ../types/wlr_xdg_decoration_v1.c:82
#6 0x7f64009d6f36 in wlr_signal_emit_safe ../util/signal.c:29
#7 …
```

view: set xdg_decoration->view to NULL, check decoration destroy

---

sway/desktop/layer_shell.c

Fixes #3686 
If the noop output is focused (all other outputs disabled/disconnected),
do not auto assign a layer surface to it. The noop output is not enabled
and does not have the `output->layers` list initialized. It also does
not make sense to map the layer surfaces to something that is not
visible.
Easy way to reproduce:  `swaymsg output \* disable; swaynag -m test`

handle_layer_shell_surface: do not use noop output

---

sway/input/seat.c

Fixes #3754
If an unmanaged or layer surface is focused when an output gets
disabled and an empty workspace on the output was focused by the seat,
the seat needs to refocus it's focus inactive to update the value of
`seat->workspace`.

handle_seat_node_destroy: update seat->workspace

---

include/swaybar/bar.h
include/swaybar/input.h
swaybar/input.c

- Activate hotspots on tap
- Cycle workspaces on swipe
Future patches:
- Make padding (constants in `render.c`) configurable so my fat fingers have bigger targets
- Incorporate with #3697 to create new workspaces on swipe(?)
Fixes https://github.com/swaywm/sway/issues/2377

Initial pass on touch support for swaybar

---

sway/ipc-json.c

i3 requires all outputs to have certain fields, including 'primary', 'current_workspace', and 'rect' which were missing on disabled outputs.
https://i3wm.org/docs/ipc.html#_outputs_reply
Fixes a bug I was having with [i3ipc-rs](https://github.com/tmerr/i3ipc-rs) where my program would crash when calling get_outputs() because the fields were missing.

ipc: add missing fields to disabled outputs

---

sway/tree/container.c

container_floating_move_to_center and container_fullscreen_disable were
calling recursively when the container spawned as a fullscreen floating
container (via for_window). Such a window now doesn't crash sway anymore
but is still configured with a wrong, zero size, making it not directly
usable.
I didn't see this patch break anything that wasn't already broken.

Fix crash exiting fullscreened floating container

---

include/sway/config.h
sway/commands/include.c
sway/config.c

Related #3595, #3619.
I made `load_include_configs` void and added a comment that emphasises we don't care if config files fail to load (unless something abnormal occurs).
Also re-reverts improved error handling that fixes a case where the working directory would not be restored.

Add comment about load_include_configs.

---

include/sway/config.h
sway/commands/hide_edge_borders.c
sway/config.c
sway/desktop/render.c
sway/sway.5.scd
sway/tree/view.c

Behaves same as _both_ in i3wm with regards to tabbed/stacked containers. If
there is only one tabbed/stacked container child, title bar is hidden.
Related issues and merge requests: #3031, #3002, #2912, #2987.
Fixes #3663

introduce hide_edge_borders lone_tab

---

include/swaybar/bar.h
sway/commands/bar/mode.c
sway/sway-bar.5.scd
swaybar/bar.c

Fixes #1620. Overlay mode puts swaybar above normal windows (in the overlay layer) and ignores input events. In my case I'm using it to always have the time in the corner of the screen. It probably works best with a theme/color scheme like mine, where the swaybar background color is transparent.

Add swaybar overlay mode

---

sway/sway.5.scd

The wording for smart_borders was opposite the actual behavior.

fix smart_borders description in manual

---

sway/commands.c

Fixes #3775 
Related to #3209 
`cmd_mode` performs its own quote stripping for the mode string to
avoid double stripping quotes for `cmd_bindcode` and `cmd_bindsym` in
`config_command` and `execute_command`. Stripping quotes in
`execute_command` for `cmd_mode` will also result in double stripping,
which will cause issues for any mode string with spaces, such as pango
markup.

execute_command: do not strip qoutes for cmd_mode

---

meson.build

Makes it more obvious that building sway with an old copy of wlroots won't work.

Set minimum wlroots version

---

README.es.md
README.md
README.pl.md
meson.build
sway/sway-ipc.7.scd
sway/sway.1.scd
sway/sway.5.scd
swaymsg/swaymsg.1.scd

**~~This is still a WIP~~ and will ideally be completed before 1.0 is
released since it would be nice to have for release**
Closes #707 
This add `sway-ipc.7.scd` that documents the IPC protocol
Note: This increases the minimum scdoc version from 1.8.1 to 1.9.0 to
allow for table cells to be continued on the following line

Add sway-ipc.7.scd to document IPC protocol

---

sway/sway-ipc.7.scd

Closes #3785 
According to the i3 ipc documentation, `window_rect` excludes the window
decorations from the calculation. This just clarifies that in
`sway-ipc.7.scd`

sway-ipc.7: clarify window_rect omits decorations

---

swaybar/tray/item.c

by converting from network byte order to host byte order
Fixes https://github.com/swaywm/sway/issues/3635

tray: fix pixmap colors

---

include/sway/input/seat.h
sway/input/cursor.c
sway/input/seat.c
sway/input/seatop_down.c
sway/input/seatop_move_floating.c
sway/input/seatop_move_tiling.c
sway/input/seatop_resize_floating.c
sway/input/seatop_resize_tiling.c

All seat operations except "down" eat the button pressed event and don't send
it to clients. Thus, when ending such seat operations we shouldn't send the
button released event.
This commit moves the logic used to send pressed/released into the "down"
operation.
Related to https://github.com/swaywm/wlroots/pull/1586

seat: don't send button release when not pressed

---

.builds/alpine.yml
.builds/archlinux.yml
.builds/freebsd.yml

Follow-up issue: revert this patch when scdoc-1.9.2 is released and included in all the platforms we support.

ci: use scdoc-git because 1.9.1 is broken

---

sway/main.c

This change removes 3~ lines of code that didn't need to be restated. Doesn't modify functionality, except for reordering the checks in the nested if statement to mirror its parent aesthetically.

Minor fix of code duplication.

---

include/sway/tree/container.h
sway/commands/resize.c
sway/input/seatop_resize_floating.c
sway/sway.5.scd
sway/tree/container.c

Fixes #3718 
Fixes #3593 
This changes the way zero (which is the default) is interpreted for both
the width and height of `floating_maximum_size`. It now refers to the
width and height of the entire output layout, which matches i3's
behavior.
This also removes duplicated code to calculate the floating constraints
in three files. Before this, `container_init_floating` used two-thirds
of the workspace width/height as the max and the entire workspace
width/height was used everywhere else. Now, all callers use a single
function `floating_calculate_constraints`.

floating_maximum_size: change default behavior

---

sway/desktop/render.c

Fixes #3808 
If a floater is fullscreen either on a workspace or globally, it
should not be rendered on any output is is not fullscreened on. When
rendering it on an output it should not be rendered on, there will be
an extraneous border along the adjacent side of the output. This adds
a check in render_floating to skip all fullscreened floaters

render_floating: skip fullscreen floaters

---

sway/input/cursor.c
sway/input/seatop_down.c

If two cursor buttons are pressed at the same time, the client will now be notified of the second button press.
The main reason for not sending the concurrent presses was due to an early return in `dispatch_cursor_button` if a seatop is in progress. This patch makes it call `seat_pointer_notify_button` prior to returning. But it also has to make sure there's not a mismatch in events such as a release without a press.
Prior to this patch, the `down` seatop would send press and release events in its begin and finish functions. No other seatops did this. A press event would be sent prior to starting tiling drag, but never an associated release.
After this patch, no seatops send their own press or release events. We send them prior to calling the seatop begin functions, then the first part of …

Allow concurrent clicks

---

README.es.md
README.md
README.pl.md
meson.build

Since scdoc 1.9.1 is bugged, this updates the meson version check to
\>= 1.9.2 and drops the version requirement from the README. This should
make it more obvious to users who have 1.9.1 that they need to update
scdoc to be able to compile man pages and hopefully cut down on the
duplicate issues

meson: update scdoc requirement to >= 1.9.2

---

sway/ipc-json.c
sway/sway-ipc.7.scd

Related to #3821 
This fixes the `deco_rect` and `rect` properties in the IPC responses
to match i3's behavior.
`deco_rect` should be relative to the parent node, not the current
node. This also takes tabbed and stacked decorations into account and
will calculate `deco_rect` for all containers since tabbed and stacked
child containers will have decorations.
`rect` should exclude the window decorations.

ipc: change {,deco_}rect to match i3

---

sway/ipc-json.c

Related to #3821 
This now takes all titlebars for stacked children into account for the
ipc property `rect`

ipc: fix rect for stacked children

---

sway/ipc-json.c

Related to #3821 
This fixes the deco_rect reported by the ipc for fullscreen containers
to be all zeroes. Children of the fullscreen container should still
have their decorations reported correctly

ipc: fix fullscreen deco_rect

---

sway/ipc-json.c
sway/sway-ipc.7.scd
swaymsg/main.c

Closes #3745 
This adds the device configurations to the ipc response for libinput
devices. Only supported configuration options for the device will be
added. This also moves `libinput_send_events` inside a new `libinput`
object that contains the rest of the configuration options. sway-ipc(7)
has been updated to reflect the changes and document the new additions.

ipc: describe libinput device configuration

---

completions/bash/swaymsg
completions/fish/swaymsg.fish
completions/zsh/_swaymsg
swaymsg/main.c
swaymsg/swaymsg.1.scd

This new option forces pretty (non-raw/non-JSON) output. By default, when
not using a tty, swaymsg outputs using the "raw" format. This makes it
impossible to, for example, pipe the pretty output to a pager such as
`less` since piping does not use a tty.
The new -p/--pretty option gives the user explicit control over the output
format while retaining the default tty-dependent behavior.
Signed-off-by: Peter Grayson <pete@jpgrayson.net>

Add -p/--pretty option to swaymsg

---

completions/bash/swaymsg
completions/fish/swaymsg.fish
completions/zsh/_swaymsg

The `-m/--monitor` option was missing from the bash and fish completions.
The `subscribe` IPC message type was missing from the bash, fish, and zsh
completions.
Signed-off-by: Peter Grayson <pete@jpgrayson.net>

Add missing swaymsg completions

---

sway/criteria.c
sway/input/seat.c

In sway/criteria.c - value was the offender. Moved the logging call up to where value is not guaranteed to e NULL.
In sway/input/seat.c - until cursor_theme is configurable, it shouldn't be passed to sway_assert. It's already marked with a TODO, so I'm sure the logging can be changed back later.
Full disclosure: I have not (yet) tested these changes.

fix "directive argument is null" errors

---

sway/desktop/output.c

Closes #1883
Related #3822 
This removes `output_damage_view` since it is unnecessary. The logic
has been moved into its only caller `output_damage_from_view`. When
damaging the whole view, `output_damage_whole_container` should be used
instead

damage: remove output_damage_view

---

sway/tree/arrange.c

Fixes #3845 
Related to #3333
This changes `apply_tabbed_layout` and `apply_stacked_layout` to use
`int` instead of `size_t`. This is necessary for tabbed and stacked
containers to be positioned correctly when the y-location is negative.
The reasoning for this is signed plus unsigned is always an unsigned
value. This was causing the y-location of the container to be
positioned near `INT_MIN` due to an unsigned integer underflow
_`ssize_t` will also work, but I feel like `int` is better since `ssize_t`
makes it seem like the titlebar height can be negative_

arrange: use int not size_t for title offsets

---

sway/commands/workspace.c
sway/input/seat.c

This changes `seat_get_focused_workspace` to use `seat_get_focus_inactive` instead of `seat_get_focus`. This may break things, but I can't think of a situation in which it would.
We still need to check whether `seat_get_focused_workspace` is NULL.
Follow-up issue: check all other `seat_get_focused_workspace` calls.
Test plan: run `sleep 5; swaymsg workspace prev_on_output`, then run `slurp` in another terminal
Fixes https://github.com/swaywm/sway/issues/3795

Fix crash in cmd_workspace when layer surface has focus

---

meson.build

Also make sure to specify `native: true` to use the host binaries in case of a cross-build.

meson: use pkg-config var for scdoc path

---

sway/tree/container.c

Fixes #3850 
If a container gets mapped as fullscreen and set to floating by
criteria, the size and location are never set for the floating
container. This adds a check in container_fullscreen_disable for a
width or height of 0 and calls container_init_floating
_Note that the content may be smaller than the container due to the
natural size being larger than the maximum floating size and the
client giving a smaller surface of the same aspect ratio. I think
this is related to #2176 (or at least the discussion in the issue)_

fullscreen: init floating on disable without size

---

sway/main.c

Fixes #1594
Only the main nvidia module needs to be blocked. Others such as
nvidiafb are benign and do not need to be blocked

detect_proprietary: use strncmp

---

include/sway/tree/view.h
sway/tree/view.c

I think this should fix #3835, but I'm not sure it is the best solution
or how to get firefox to do self-updates to test it.
Since not all child views's have an unmap event, it is possible for it
to still be mapped (default state) in the destruction handler. When
the destruction handler is called, the corresponding view may have
already been freed and the memory location reallocated. This adds a
listener for the view unmapping and removes the mapped status. This
ensures that the child view is damaged due to destruction while the
view still exists and not after.

sway_view_child: add listener for view unmap

---

common/stringop.c
include/stringop.h
swaybar/tray/icon.c

I've removed a lot of old and unused functions.
I want to refactor some of the other functions. In particular `unescape_string`, and maybe move it to `sway/commands.c` since it is the only place it is used, but I'm not sure about its specification to be confident in rewriting it correctly.

Cleanup stringop.c (partly)

---

swaybar/tray/icon.c

`len` will underflow but will overflow right after, so it's not as bad as it
may appear. Still better not to under/overflow at all.
Fixes https://github.com/swaywm/sway/issues/3862

Fix size_t temporary underflow in log_loaded_themes

---

include/sway/output.h
sway/config/output.c
sway/desktop/desktop.c
sway/desktop/output.c
sway/desktop/render.c
sway/input/seatop_move_tiling.c
sway/tree/arrange.c
sway/tree/output.c

This is an update for https://github.com/swaywm/wlroots/pull/1611. It doesn't depend on it though, and can be merged before.
Also fixes sway_output->{lx,ly,width,height} not being updated. Also fixes
output_get_in_direction adding buffer coords to layout coords.

Stop using wlr_output->{lx,ly}

---

swaynag/config.c

When swaynag is run with the `-l/--detailed-message option`, a crash may
occur if the detailed message read from stdin is large enough. E.g.:
swaynag -m hello -l < ~/.config/sway/config
The root cause is that the `read_from_stdin()` function under-allocates
memory for the destination buffer which causes that buffer to be overflowed
when copying line data to it with `snprintf()`.
The repair is to allocate one more byte for the terminating null byte.
N.B. although `getline()` returns the number of bytes read excluding a
terminating null byte, the line buffer is terminated with a null byte. Thus
we have a guarantee that the line buffer will be null terminated (which is
important when copying with `snprintf()`).

Repair swaynag crash reading message from stdin

---

config.in

Without this change you can't execute apps with command line arguments (e.g. firefox -P profile) because -P will be parsed as argument for "swaymsg exec".

config.in: allow launch apps with args via dmenu

---

sway/commands/focus.c
sway/commands/scratchpad.c
sway/commands/workspace.c
sway/desktop/layer_shell.c
sway/tree/root.c
sway/tree/workspace.c

Closes #3853 
This modifiers the callers of seat_get_focused_workspace to handle
getting NULL as the return value, if they did not already.

Handle seat_get_focused_workspace returning NULL

---

include/sway/criteria.h
sway/criteria.c

Fixes #3877 
This changes the workspace criteria to support regex instead of basic
strings. This matches i3's behavior.

criteria: change workspace to support regex

---

sway/desktop/xwayland.c

Fixes https://github.com/swaywm/sway/pull/3854#issuecomment-471356043
This makes it so the container gets resized by a configure request for
xwayland floating views. The minimum and maximum sizes are also
respected. Previously, the configure request was resizing the surface
to the size requested, but never changing the container size. This
caused the surface to be rendered outside of the container or to be
smaller than the container. The former is never ideal and the latter
makes no sense for floating views since the container itself can just
be shrunk.
Test:
- Add `for_window [class="mpv"] floating enable` to your config
- Run`mpv /path/to/image-smaller-than-output --no-config --gpu-context=x11 --fs=yes --image-display-duration=inf --force-window=immeadiate`
- Fullscreen disable
- …

xwayland: handle floating configure request size

---

swaybar/tray/icon.c

If the icon index.theme contained a key-value pair without a preceding
group header, entry_handler() would be called with a zero pointer and
lead to a segfault.
Set the error flag and break on such malformed files.

swaybar: fix loading of malformed icon theme

---

sway/input/seat.c
sway/tree/workspace.c

Fixes #3888
This moves setting `seat->prev_workspace_name` from `workspace_switch`
to `set_workspace`. `workspace_switch` is only called when using a
`workspace` command to change the workspace so any workspace change
based on criteria was not altering `seat->prev_workspace_name`. By
moving it to `set_workspace`, which is called by `seat_set_focus`, it
will change any time focus changes to a node on a different workspace

Set prev_workspace_name based off of focus

---

sway/commands/output/background.c

This validates the color and fallback color in `output_cmd_background`
to ensure that only colors of the form `#RRGGBB` are accepted.

output_cmd_background: validate colors

---

sway/commands.c

E.g. `for_window [class="mpv"] move container to output "Dell Inc. ..."`
does not work because the executed move command only uses `Dell` as
output name.

Fix quoting of commands passed to for_window

---

swaymsg/main.c

When in subscribe mode **and** piping to a process, the notifications are only arriving when the stdout buffer is full.
An easy way to reproduce that is `swaymsg -m -t subscribe '["window"]' | cat`.
Flushing stdout after printing a message fixes that.

Flush stdout in swaymsg when in subscribe mode

---

include/sway/config.h
include/sway/output.h
sway/config/output.c
sway/desktop/output.c
sway/tree/output.c

This removes `output_find_config`, which would take the first matching
output config it found. This is fine if only a name output config,
identifier output config, or even just wildcard exist, but if there is
a name output config and identifier output config, they are not merged.
Instead, this introduces find_output_config, which is just a wrapper
for `get_output_config`. This ensures that both the name and identifier
output configs are respected.
This fixes the following case:
- For simplicity in this example, remove all output configs from config
- Run `swaymsg output <name> bg #ff0000 solid_color`
- Run `swaymsg output <identifier> scale 2`
- (Note the bg will be removed here. That will be fixed by #3905)
- Disconnect and reconnect output
Without this, the output will have the …

Fix output config retrieval for new outputs

---

sway/config/output.c

Fixes #3891 
This revamps the way that output configs are handled when referencing
an output by both identifier and name. If an output is always referred
to by name or by identifier, this should have no noticeable change. As
soon as there is a name output config and an identifier output config
that matches an output, an output config is generated that is named
`<identifier> on <name>` that is generated with the identifier output
config merged on top of the name output config and stored. When a
change to either is stored, the delta is merged on top of that
"id on name" output config, as well. If the "id on name" output config
exists, it has the highest precedence and will be used when applying
a config to the output.
This fixes the following case:
- `swaymsg output <name> bg …

config/output: revamp identifier/name layering

---

include/sway/input/cursor.h
include/sway/input/seat.h
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/seat.c
sway/input/seatop_default.c
sway/input/seatop_down.c
sway/input/seatop_move_floating.c
sway/input/seatop_move_tiling.c
sway/input/seatop_resize_floating.c
sway/input/seatop_resize_tiling.c
sway/meson.build

This introduces a `default` seat operation which is used when no mouse buttons are being held. This means there is now always a seat operation in progress. It allows us to separate `default` code from the standard cursor management code.
Note that as of creation, this PR has two commits. The first is small and replaces the seatop `allows_events` boolean with a `button` callback. The second commit is somewhat significant. The rest of this description relates to the second commit.
The `sway_seatop_impl` struct has gained callbacks `axis`, `rebase` and `end`, and lost callbacks `finish` and `abort`. `axis` and `rebase` are only used by the default seatop. `end` is called when a seatop is being replaced by another one and allows the seatop to free any resources, though no seatop currently …

Introduce default seatop

---

sway/config/output.c

Fixes #3919 
In #3916, I overlooked that `get_output_config` does not handle
wildcards unless the config is reloading, which is a remnant of older
iterations of the output config handling that went unnoticed due to
`output_find_config` handling it. With the current version of the
output config handling, having `get_output_config` handle wildcard
configs is actually preferable. This fixes having only a wildcard
output config in the config file or when connecting/enabling a new
output with only a wildcard config existing.

config/output: handle wildcard in get_output_config

---

sway/input/seatop_default.c

Firstly, this fixes a recent regression where having `focus_follows_mouse yes` and hovering an inactive tab caused it to gain focus. The code was missing a `view_is_visible` check.
The code is handling the logic for both `focus_follows_mouse yes` and `focus_follows_mouse always`, where the latter will apply when nudging the mouse after a workspace switch. However, the `view_is_visible` check didn't apply when using `focus_follows_mouse always`, so hovering a tab
with that configuration would cause is to focus. This was a bug. When adding the `view_is_visible` check, it now applies to both `yes` and `always`.
Note that the comment about the split container was wrong. At this point the hovered node cannot be a split container because it passed the `node_is_view` check. The comment has been …

Clean up focus follows mouse logic

---

include/sway/commands.h
include/sway/config.h
include/sway/input/seat.h
include/sway/input/switch.h
sway/commands.c
sway/commands/bind.c
sway/commands/mode.c
sway/config.c
sway/input/input-manager.c
sway/input/seat.c
sway/input/switch.c
sway/ipc-json.c
sway/meson.build
sway/sway.5.scd

~I'm planning to expose this config by adding the `bindswitch` command as follows:~
On second thoughts it might be better to use the existing `bindsym` architecture and match `evdev` switch names, 
eg `bindsym tablet:lid:on exec "Lid opened"`
vs
```
bindswitch lid:on exec echo "Lid opened"
bindswitch lid:off exec echo "Lid closed"
bindswitch lid:toggle exec echo "Lid moved"
bindswitch tablet:on exec echo "Entered tablet mode"
bindswitch tablet:off exec echo "Entered laptop mode"
bindswitch tablet:toggle exec echo "Toggled tablet mode"
bindswitch ThinkPad Extra Buttons:on exec echo "Matched name on"
bindswitch ThinkPad Extra Buttons:on exec echo "Matched name off"
```
As we did for rootston, commands can match on either the switch type (`lid` for `LIBINPUT_SWITCH_LID`, `tablet` for …

Switch events

---

sway/commands/mode.c
sway/sway.5.scd

Related https://github.com/swaywm/sway/issues/2336#issuecomment-474661290
This allows set to be used in mode blocks

cmd_mode: allow cmd_set to be a subcommand

---

include/sway/criteria.h
sway/criteria.c

Fixes #3953 
This fixes the behavior of `__focused__` when there is no focused view
to match i3's behavior of successfully matching no views instead of
returning an error of a missing value. It also applies the same logic
when a token is not applicable (or unset) for a view such as `app_id`
for a focused xwayland view or `class` for a focused xdg-shell view.
This adds an `autofail` boolean to `struct criteria`. If it is set to
`true`, then `criteria_matches_view` will immediately bail out as a
no match. If `autofail` is set, the criteria will also not be
considered empty by `criteria_is_empty`.
To set this new `autofail` property, `get_focused_prop` will now take
in a boolean pointer of the same name. If `__focused__` is supported
for the token and there is no focused view or the focused …

criteria: fix __focused__ when no focus or unset

---

sway/tree/container.c
sway/tree/output.c

Fixes #3954
Since the NOOP output has no size, the minimum floating size is greater
than the workspace size for the NOOP output. In this case, the floater
gets centered in the output instead of the workspace. However, the
NOOP output is not part of the output layout and thus has a NULL box.
Attempting to access the properties of this box was causing a segfault.
This fixes the issue by just setting the floater's box to all zeroes
when mapping on the NOOP output. When the workspace gets moved from the
NOOP output to a new output, any floater whose width or height is zero
or has an x or y location outside of the output, gets passed to
`container_init_floating` again. This will then set the appropriate
size and centering. For any floater that has a valid size and location,
they are preserved.

fix opening a floating view on the NOOP output

---

include/sway/tree/root.h
sway/commands/rename.c
sway/tree/root.c

This change adds support for renaming workspace (without changing
workspace number) when `exec` command is being processed. If focused
workspace is renamed  after receiving `exec` command but before
the application is launched, sway will assign the application to
a workspace basing on matching number.
The change can be verified by running following command:
swaymsg exec <application>; swaymsg rename workspace number 1 to '1: new'
Fixes: #3952

Allow for workspace renaming during exec handling

---

common/util.c
include/sway/commands.h
include/sway/config.h
include/sway/output.h
include/util.h
sway/commands/output.c
sway/commands/output/subpixel.c
sway/config/output.c
sway/ipc-server.c
sway/meson.build
sway/sway-ipc.7.scd
sway/sway-output.5.scd
sway/tree/output.c
swaymsg/main.c

Many laptop screens report unknown subpixel order. Allow users to manually set subpixel hinting to work around this.
Addresses https://github.com/swaywm/sway/issues/3163
~~TODO: update docs.~~

Add support for manually setting subpixel hinting on outputs.

---

sway/commands.c

From what i understand, 
do_var_replacement never adds escape characters.
if the variable's value contains an escaped characther, it should stay escaped after the replacement.
Thus, unescapping the string after calling do_var_replacement is unescessary and strips the escape characters before calling the exec_always.c
And exec_always.c removes the quotes because they are not escaped anymore

Fix #3924 ( Stripping of escaped quotes in exec )

---

include/sway/commands.h
include/sway/desktop/idle_inhibit_v1.h
sway/commands.c
sway/commands/inhibit_idle.c
sway/desktop/idle_inhibit_v1.c
sway/desktop/transaction.c
sway/meson.build
sway/sway.5.scd

Closes #3070
This implements the following command to set/unset a user idle
inhibitor for a view:
`inhibit_idle focus|fullscreen|open|none|visible`
It can be used to set/unset a user idle inhibitor for a view.
The modes are as follows:
- focus: inhibited when the view is focused by any seat
- fullscreen: inhibited when the view is fullscreen (or a descendant of
a fullscreen container) and is visible on any output
- open: inhibited until the view is closed or the inhibitor is unset or
changed
- none: unsets any user set idle inhibitors for the view
- visible: inhibited when the view is visible on any output
This should have no effect on idle inhibitors set by the applications
themselves and those should still work as intended.
Since this operates on the view in the handler context, it is …

Implement inhibit_idle command

---

sway/commands/bind.c

Spotted just thanks to the same-message-different-sink that follows.

Fix order mismatch in interpolated string arguments

---

sway/input/seatop_move_tiling.c

* Create layout `S[V[view view] view]`
* Drag bottom view to the top
* Sway would crash when the cursor hovers the `V[view view]` title while dragging
Also fixes a typo in a comment.
Fixes #3985.

Fix null pointer crash when doing tiling drag

---

swaybar/tray/icon.c

Fix a crash in swaybar when an icon dir is not readable

---

include/sway/tree/container.h
sway/desktop/xwayland.c
sway/tree/container.c
sway/tree/output.c
sway/tree/root.c

Fixes https://github.com/swaywm/sway/issues/3972#issue-425142958
This fixes a crash in `container_init_floating` when a xwayland view
sends a configure request while in the scratchpad.
`container_init_floating` gets called so the configured minimum and
maximum sizes gets respected when resizing to the requested size. Since
the workspace was NULL, it would SIGSEGV when attempting to get the
workspace's output for the output box retrieval.
This extracts the resizing portion of `container_init_floating` into a
separate function. If the container is in the scratchpad, it will just
be resized and skip the centering
Additionally, `container_init_floating` has been renamed to
`container_floating_resize_and_center` to more accurately describe what
it does.

Fix xwayland configure request scratchpad crash

---

include/sway/tree/container.h
sway/tree/container.c
sway/tree/root.c

Fixes #3991 
Fixes #3935 
This fixes the sizing of floating non-view containers. On master, the
floater will get set to the maximum width and height, which by default
is the entire output layout. When setting a non-view container to
floating, this will set a sane default size of 50% of the workspace
width and 75% of the workspace height, or whatever the closest is that
the minimum and maximum floating width/height values allow for. On all
future calls to `floating_natural_resize`, the width and height will be
kept unless they need to be changed to respect the min/max floating
width/height values.
This also matches i3's behavior of setting scratchpad containers to 50% of
the workspace's width and 75% of the workspace's height, bound by the
minimum and maximum floating width/height.

Fix sizing of floaters + scratchpad

---

README.md

Sorry for the broken link added to `README.md`, now it is fixed.

fix broken link to README.zh-CN.md

---

sway/tree/root.c

Fixes #4008 
This fixes a crash in `root_scratchpad_hide` when a layer surface is
focused. Since `seat_get_focus` is NULL when a layer surface is
focused, the call to `node_has_ancestor` was causing a SIGSEGV since it
was attempting to access the parent of NULL. This changes the call to
`seat_get_focus_inactive`, which will return a node even when a layer
surface is focused and is also guaranteed to have something in the
focus stack if a scratchpad container is being hidden (otherwise there
would not be any containers yet).

root_scratchpad_hide: fix crash when layer focused

---

sway/desktop/idle_inhibit_v1.c

Fixes #4004
This fixes a crash for application set idle inhibitors when their
associated view is being destroyed. There is a call to
`view_is_visible` to determine is the view is visible and it assumes
that the view has an container, but it is possible for the container
to already have been destroyed at this point. There is a NULL check for
the view in `check_active` and this re-adds the NULL check for the
container that I accidentally dropped when refactoring during the
inhibit_idle command PR (#3962)

idle_inhibit: fix crash during view destruction

---

include/sway/config.h
include/sway/output.h
sway/commands/output.c
sway/config.c
sway/config/output.c
sway/desktop/output.c
sway/tree/output.c
swaybg/main.c

Closes #2051 
Fixes #3892
This makes it so there will only be one swaybg instance running
instead of one per output. swaybg's cli has been changed to a xrandr
like interface, where you select an output and then change properties
for that output and then select another output and repeat. This also
makes it so swaybg is only killed and respawned when a background
changes or when reloading.

swaybg: one instance for all outputs

---

sway/config/output.c

Same as https://github.com/swaywm/wlroots/pull/1650. See error logs: [armv7](https://github.com/swaywm/sway/files/3055931/sway-1.0.r1.221.log), [i386](https://github.com/swaywm/sway/files/3055930/sway-1.0.r1.221.log).

Unbreak -Werror on 32-bit platforms

---

include/sway/tree/view.h
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/tree/view.c

Fixes #1813 
Requires swaywm/wlroots#1638
This honors the fullscreen output request for
`xdg_toplevel_set_fullscreen` and `zxdg_toplevel_v6_set_fullscreen`.
If the request was sent before mapping, the fullscreen output request
will be retrieved from the client_pending state for the toplevel. The
output will be passed to `view_map` and if there is a workspace on the
output, the view will be placed on that workspace.
If the request comes in after being mapped, the view will be moved to
the workspace on the output (if there is one) before becoming
fullscreen.

Honor output for xdg_toplevel_set_fullscreen

---

sway/commands/focus.c

Closes #4031 
Floaters are currently raised for `focus <direction>`. This extends the
same functionality to `<criteria> focus`.

cmd_focus: raise floating for `<criteria> focus`

---

sway/sway-input.5.scd

Since xkeyboard-config(7) is mentioned in the man page, add a reference
to the "see also" section.

sway-input.5: add xkeyboard-config(7) to "see also"

---

sway/tree/root.c

Only sets an initial size if the container does *not* have a view. This
allows initial sizing geometry to be respected.
This is a follow up to https://github.com/swaywm/sway/pull/3992, wherein I believe the original intent was to only set a default size for containers without a view:
> When setting a non-view container to
floating, this will set a sane default size of 50% of the workspace
width and 75% of the workspace height, or whatever the closest is that
the minimum and maximum floating width/height values allow for.

Fix scratchpad logic for floating windows 

---

sway/commands/move.c
sway/input/seat.c

I recommend viewing this with whitespace ignored. I simply wrapped some branches in `if`s where the subject could be null. I ran into all of these while doing some testing.

Fix potential null accesses

---

include/sway/input/seat.h
sway/commands/floating.c
sway/commands/focus.c
sway/commands/fullscreen.c
sway/commands/layout.c
sway/commands/move.c
sway/commands/split.c
sway/desktop/output.c
sway/desktop/render.c
sway/input/seat.c
sway/tree/container.c
sway/tree/node.c
sway/tree/root.c
sway/tree/view.c

Fixes https://github.com/swaywm/sway/issues/3972#issuecomment-476576069
When setting fullscreen on a hidden scratchpad container, there was a
check to see if there was an existing fullscreen container on the
workspace so it could be fullscreen disabled first. Since the workspace
is NULL, it would cause a SIGSEGV. This adds a NULL check to avoid the
crash.
This also changes the behavior of how fullscreen is handled when adding
a container to the scratchpad or changing visibility of a scratchpad
container to match i3's. The behavior is as follows:
- When adding a container to the scratchpad or hiding a container back
into the scratchpad, there is an implicit fullscreen disable
- When setting fullscreen on a container that is hidden in the
scratchpad, it will be fullscreen when shown (and …

Fix scratchpad fullscreen behavior and crash

---

swaynag/swaynag.c

Currently on master, swaynag will retrieve a pointer instance whenever
the capabilities change and WL_SEAT_CAPBILITY_POINTER is set. The
pointer instances were never being destroyed so swaynag received events
multiple times due to having several instances of the pointer.
This fixes it so if there is already a pointer instance, swaynag does
not attempt to retrieve another. Additionally, if the pointer
capability is removed, the pointer instance is destroyed.

swaynag: fix pointer management

---

common/util.c
include/sway/swaynag.h
include/util.h
sway/config.c
sway/config/output.c
sway/main.c
sway/swaynag.c
swaynag/swaynag.c

**Until #4051 is merged, I would recommend rebasing this on top of it for testing. Otherwise, pressing the "Reload sway" button may result in sway reloading multiple times causing a noticeable delay/unresponsive period. Reloading via a binding or command line is not affected by the multiple reloads issue**
Fixes #4047 
This spawns swaynag as a wayland client similar to how swaybar and
swaybg are already done

Spawn swaynag as a wayland client

---

include/sway/config.h
include/sway/input/input-manager.h
sway/config.c
sway/config/input.c
sway/input/input-manager.c
sway/ipc-json.c
sway/sway-input.5.scd
swaymsg/main.c

This PR implements #3784.
The "touchpad-iness" of a pointer is determined through `libinput_device_config_tap_get_finger_count`, which is referenced from [clutter](https://gitlab.gnome.org/GNOME/mutter/blob/master/clutter/clutter/evdev/clutter-input-device-evdev.c#L1459). In the future, this may be updated to a more concrete method of determining whether an input device is a touchpad.
`swaymsg` is updated to reflect this change, outputting `Type: Touchpad` or `Type: Mouse` rather than only `Type: Pointer`. In addition, `sway` now logs the matching of a type wildcard.
The behaviour is as follows:
- If a device is added and has a configuration, it is applied on top of it's type config.
- If a device is added, does not have a configuration, and it has a matching type config, the device will …

Add support for configurations per input device type

---

sway/tree/view.c

With the command `hide_edge_borders` it is possible to hide window borders adjacent to the screen edges and this was also applied to floating windows. This patch changes this behavior to match i3's (see https://github.com/i3/i3/blob/56bbc528d7de68100298c6ba85a6488778f3a64e/src/con.c#L1645).
The old behavior led to the following problem: If a floating window's border (adjacent to the screen edge)  was hidden by `hide_edge_borders`, the border stayed hidden when the window was moved away from the screen edge. To reproduce:
1. Open a floating terminal (with a size smaller than the screen).
2. In this terminal execute `swaymsg border normal 2, hide_edge_borders both, move window to workspace 1, workspace 1, move absolute position 0 0, workspace 1, move position center`
3. The terminal is …

Don't apply hide_edge_borders to floating windows 

---

sway/ipc-server.c

If a client is subscribed and sends a subsequent ipc command which
causes event updates, then those event updates override the
`client->current_command` and send the incorrect type for the payload
associated with the command.
Example:
SUBSCRIBE {window}
RUN_COMMAND focus -> PAYLOAD_TYPE is 0x80000002 for window events
Therefore, we decouple the `client->current_command` by passing it as an
argument to the ipc_send_reply function, avoiding a data race. The same
is done for the `client->payload_length` as a precautionary measure for
the same reason.
Closes #4053

Fix the payload type returned by IPC

---

common/ipc-client.c
include/ipc-client.h
swaymsg/main.c

*Disclaimer: I'm not really sure of the value of this, but it's not that large*
Closes #4046 
This adds a 3 second timeout to the initial reply in swaymsg. This
prevents swaymsg from hanging when `swaymsg -t get_{inputs,seats}` is
used in i3. The timeout is removed when waiting for a subscribed event
or monitoring for subscribed events.
This also adds type checks to commands where i3 does not reply with all
of the properties that sway does (such as `modes` in `get_outputs`).
This is mostly just a behavioral adjustment since swaymsg should run on
i3. When running under i3, some command reply's (such as the one for
`get_outputs) may have more useful information in the raw json than the
pretty printed version.

swaymsg: add timeout and type checks

---

include/sway/commands.h
sway/commands.c
sway/commands/bar.c
sway/commands/bar/bind.c
sway/commands/bind.c
sway/sway-bar.5.scd
sway/sway.5.scd

This PR implements the feature request #3971 that will allow a user to revoke key, mouse, or switch bindings both for sway and swaybar.
Status:
Closes #3971

Add feature to revoke bindings

---

sway/commands/hide_edge_borders.c

Disable the i3-compatible behavior if the option '--i3' is not given.
Previously it was only possible to disable it by changing the config
file. Now it also works via swaymsg.

hide_edge_borders.c: add missing case for --i3

---

sway/commands/move.c
sway/sway.5.scd

Related https://github.com/swaywm/sway/issues/3793#issuecomment-484433598
This modifies cmd_move to allow for the [syntax options allowed by i3](https://github.com/i3/i3/blob/a574346964ce17d35df2ef9072ba16e26209ac84/parser-specs/commands.spec#L316-L324).
The following syntaxes are supported:
- `move left|right|up|down [<amount> [px]]`
- `move [--no-auto-back-and-forth] [window|container] [to] workspace
<name>|next|prev|next_on_output|prev_on_output|current|number <num>`
- `move [window|container] [to] output <name/id>|left|right|up|down`
- `move [window|container] [to] mark <mark>`
- `move workspace to [output] <name/id>|left|right|up|down`
- `move [window|container] [to] [absolute] position <x> [px] <y> [px]`
- `move [window|container] [to] [absolute] position center`
- `move …

cmd_move: allow for all i3 syntax options

---

sway/input/keyboard.c

Fixes #4066 
This fixes the criteria for emitting a `bar_state_update` event to
notify swaybar (and any other bars utilizing the event) on whether the
bar is visible by modifier. It is not enough to only emit the event
when both the bar mode and bar hidden state are `hide` since it is
possible to release the modifier while hidden state is `show` and then
change hidden state to `hide` without pressing the modifier. This also
emits the event whenever visible by modifier is set and should no
longer be regardless of the mode and state to ensure that it gets
properly cleared. If visible by modifier is not set and the bar is not
in `hide`/`hide`, then no events will be sent and visible by modifier
will not be set

ipc: fix criteria for emitting bar_state_update

---

include/swaynag/types.h
swaynag/config.c
swaynag/main.c
swaynag/types.c

Fixes #4070 
This revamps the type configs for swaynag. All sizing attributes for
swaynag are now `ssize_t` instead of `uint32_t` to allow for a default
value of `-1`, which allows for `0` to be a valid value. Additionally,
the initialization of the type configs has been changed from a simple
calloc to use a new function `swaynag_type_new`. `swaynag_type_new`
calloc's the memory, checks for an allocation failure, sets the name,
and all sizes to -1. The layering order has also been changed to
default, general config, type config, and as highest priority command
line arguments. Finally, `swaynag_type_merge` has been modified to
handle the layering and sizing changes.

swaynag: revamp type configs

---

swaybar/tray/icon.c

The read_theme_file function used to return an invalid icon_struct in
some cases, for example when an empty index.theme file was read.
This makes sure the struct we're returning is always valid as per the
Icon Theme specification.
Signed-off-by: Maxime “pep” Buquet <pep@bouah.net>

Validate icon_struct in read_theme_file

---

include/swaybar/bar.h
swaybar/bar.c
swaybar/ipc.c

Closes #3036
This allows swaybar to become visible when the mode changes (to any
mode other than the default). swaybar will be hidden again when the
modifier is pressed and released or when switching back to the default
mode.
This also applies the same logic to visible by urgency to hide swaybar
when the modifier is pressed and released.
These changes are to match i3's behavior.

swaybar: hide mode visibility improvements

---

sway/tree/container.c
sway/tree/workspace.c

Fixes #4038 
When moving a container to become a direct child of the workspace and
the workspace's layout is tabbed or stacked, wrap it in a container
with the same layout. This allows for the following:
- Run `layout tabbed|stacked` on an empty workspace (or use
`workspace_layout tabbed|stacked` in the config)
- Open some views
- Move one of the views in any direction
- Open another view
- The new container should also be `tabbed`/`stacked`

cmd_move: respect workspace layout when inserting

---

meson.build

The release notes say "The recommended wlroots release for use with sway 1.0 is wlroots 0.5." so that should probably adjusted

Set the correct version for wlroots dependency

---

.builds/alpine.yml
.builds/archlinux.yml

If unspecified, feature options are set to "auto", which means enabled only if
the required dependencies are found. In CI we don't want to miss compilation
errors because a dependency hasn't been found and code isn't built.
Leave FreeBSD out for now because it uses a subproject (haven't found a way to
make auto_features=enabled only apply to the toplevel project).

ci: enable all features

---

include/sway/config.h
sway/commands/bind.c
sway/commands/input.c
sway/config.c
sway/config/input.c
sway/input/keyboard.c
sway/sway.5.scd

Fixes #2999.
The idea is to have an instance of default xkb_keymap and try to resolve bindsyms into bindcodes while binding.
If the conversion is successful, we just treat the binding as a bindcode. If the conversion has failed, we do not change the binding, so it will be processed as a normal bindsym.
In my configuration, all of the 80 bindsyms have been converted into bindcodes. I have tested the following and it worked in any keyboard layout:
* Default bindings
* Bindings with function keys
* Uppercase keysyms
* Special ones like XF86AudioRaiseVolume, XF86AudioMute, XF86MonBrightnessUp
I also checked a keysym with no simple keycode translation (the question mark, keysym `question`) and it worked as a keysym binding, however this kind of bindings still depends on the current keyboard …

Implement layout-independent keysym bindings

---

sway/main.c

The header file `stdio.h` was included twice in `main.c`.

Remove extra inclusion of stdio.h

---

sway/input/seatop_default.c
sway/input/seatop_move_floating.c
sway/input/seatop_move_tiling.c
sway/input/seatop_resize_floating.c
sway/input/seatop_resize_tiling.c

This fixes a minor annoyance when moving or resizing using the floating_modifier.  Currently, after finishing moving or resizing a window, the cursor is reset to "left_ptr", not the image requested by the client.  This PR saves said image and restores it correctly.

Correctly reset the cursor image after a seatop

---

sway/commands/move.c
sway/sway.5.scd

Related to https://github.com/swaywm/sway/issues/4108#issuecomment-488104938
This adds support for the following commands for i3 compatibility:
- `move [window|container] [to] output current`
- `move workspace to [output] current`
- `move workspace [to] output current`
The above commands are only useful when used with criteria.

cmd_move: add support for output current

---

sway/sway.5.scd

_Due to common confusion with mostly the workspace gaps configuration,
but also workspace outputs configuration:_
This clarifies that `workspace <name> output <outputs...>` and
`workspace <name> gaps ...` do not operate on existing workspaces.
Additionally, alternate commands/solutions that operate on existing
workspaces are listed.

sway.5.scd: clarify workspace config commands

---

sway/xdg_decoration.c

In case a set_mode/unset_mode request is sent before the first commit, we need
to handle the value and send our preference accordingly.
This fixes xdg-decoration support for Qt apps.

Fix xdg-decoration unconfigured if set before first commit

---

sway/config.c
sway/config/output.c

Supersedes/Closes #4122  _(thanks @Hummer12007 for the initial PR)_
When reloading, this destroys the old config's swaybg client before
spawning the new config's swaybg. This fixes a race condition where the
old config's swaybg client's destroy was being called after the new
config's swaybg client was being spawned. This was causing the
reference to the new swaybg client to be removed and never destroyed.
This also modifies handle_swaybg_client_destroy to grab the config
reference using wl_container_of on the listener since the swaybg client
may be the old config swaybg client and should be used instead of the
global config instance

Destroy swaybg client on reload

---

sway/config/output.c

Fixed #4131 
This fixes a typo in `merge_id_on_name` for output configs that
resulted in incorrect id-on-name output configs being generated.
Instead of using the output that matched the name or identifier, the
first output in the list was being used instead. This could cause
merging across unrelated output configs and preventing output configs
from being applied correctly

config/output: fix typo in merge_id_on_name

---

include/sway/commands.h
include/sway/output.h
sway/commands/output.c
sway/commands/output/toggle.c
sway/desktop/output.c
sway/meson.build
sway/sway-output.5.scd

Closes #4136 
Per discussion in #4136. Does handle disconnected output but does not handle wildcard.

Implement output toggle

---

include/sway/input/keyboard.h
sway/input/keyboard.c

Partial fix for #4148. The user facing error portion is still a WIP
This attempts to use the default keymap when the one defined in the
input config fails to compile. The goal is to make it so the keyboard
is always in a usable state, even if it is not the user's requested
settings as usability is more important.
This also removes the calls to `getenv` for the `XKB_DEFAULT_*` family
of environment variables. The reasoning is libxkbcommon will fallback
to using those (and then the system defaults) when any of the rule
names are `NULL` or an empty string anyway so there is no need for
sway to duplicate the efforts.

input/keyboard: attempt default keymap on failure

---

sway/commands/bar.c
sway/commands/bar/bind.c
sway/commands/bar/binding_mode_indicator.c
sway/commands/bar/font.c
sway/commands/bar/gaps.c
sway/commands/bar/icon_theme.c
sway/commands/bar/modifier.c
sway/commands/bar/output.c
sway/commands/bar/pango_markup.c
sway/commands/bar/position.c
sway/commands/bar/separator_symbol.c
sway/commands/bar/status_command.c
sway/commands/bar/strip_workspace_name.c
sway/commands/bar/strip_workspace_numbers.c
sway/commands/bar/swaybar_command.c
sway/commands/bar/tray_bind.c
sway/commands/bar/tray_output.c
sway/commands/bar/tray_padding.c
sway/commands/bar/workspace_buttons.c
sway/commands/bar/wrap_scroll.c

Prior to this patch, if I ran something like this, sway would crash:
swaymsg bar height 50
or
swaymsg bar not-a-bar-id color bg #ff0000
This was in contrast to other bar subcommands, like status_command, which would exit with a "No bar defined message".
The difference between the subcommands that crashed and the ones that exited was that some subcommands had a check to see if a bar was specified, while others just assumed that it had been and carried on until they segfaulted.
Because this check was identical in every subcommand it was present in, and I couldn't think of a case where it would be valid to run a bar subcommand without specifying which bar to apply it to, I moved this check from individual subcommands into the bar command, which is already responsible for actually setting the …

bar: fix segfault with missing or invalid bar id

---

sway/commands/bar.c

Running a command like this produced a confusing error message:
$ swaymsg bar bar-0 colors background #ff0000
Error: Unknown/invalid command 'bar-0'
This patch makes the error message use argv[1] instead of argv[0] (from config_subcommand's implementation), so it actually uses the name of the command, rather than the id of the bar.

commands/bar: improve error for invalid subcommand

---

sway/commands/bar.c

This fixes a regression that I missed when reviewing #4160 
For compatibility with i3, `bar mode` and `bar hidden_state` do not
require bar-ids (in the normal location) at runtime since they follow
the alternative syntax: `bar mode|hidden_state <option> [<bar-id>]`
This removes the incorrect error that the bar-id is missing for those
two bar subcommands

commands/bar: fix mode and hidden_state at runtime

---

sway/input/switch.c

This just changes the indentation of `sway/input/switch.c` to use
tabs instead of spaces since I messed up and missed it when approving
the PR that added the file.

input/switch: fix indentation of file

---

common/ipc-client.c

Supersedes/Closes #4092 
See #4092 for compilation logs showing the issue
This just removes the ipc recv timeout log statement in
`ipc_recv_set_timeout`. The `tv_sec` field of `struct timeval` has
varying types and/or sizes depending on the platform and architecture.
On some of these, the current format string will cause compilation
errors. Additionally, the log statement is not extremely useful and the
function is currently only used by swaymsg, which has a hardcoded log
level that will prevent it from even being shown, so there is no point
in even keeping it.

common/ipc-client: remove ipc recv timeout log

---

sway/ipc-json.c
sway/sway-ipc.7.scd

This is useful for scripting dpms switching.

Provide current DPMS state in GET_OUTPUTS

---

sway/commands/bind.c
sway/input/keyboard.c
sway/input/switch.c
sway/sway.5.scd

_Preface: I noticed while working on this that I missed that
`sway/input/switch.c` is space indented when I approved the PR that
added it. I'll submit a follow-up PR to correct the indentation of the
file (submitted as #4188)_
Closes #4183 
This changes the behavior of bindings to make the `BINDING_LOCKED` flag
conflicting, which will allow for both unlocked and locked bindings.
If there are two matching bindings and one has `--locked` and the other
does not, the one with `--locked` will be preferred when locked and
the one without will be preferred when unlocked.
If there are two matching bindings and one has both a matching
`--input-device=<input>` and `--locked` and the other has neither, the
former will be preferred for both unlocked and locked.
This also refactors …

bindings: allow unlocked and locked bindings

---

meson.build
sway/sway-bar.5.scd
swaybar/swaybar-protocol.7.scd

Closes #4135 
This adds swaybar-protocol.7.scd documenting the swaybar status line
protocol including some differences from the i3bar counterpart.

Add swaybar protocol documentation

---

include/sway/tree/view.h
sway/tree/view.c

Subsurfaces need access to the parent get_root_coords impl for positioning in
popups. To do this, we store a reference to the parent view_child where
applicable.
Fixes #4191.

Use parent get_root_coords in subsurfaces

---

sway/desktop/output.c

handle_destroy would mark the output es being destroyed and commit the
transaction. Committing the transaction results in the output being
freed, the output manager can not retrieve the server reference
afterwards, resulting in the following use-after-free:
```
==22746==ERROR: AddressSanitizer: heap-use-after-free on address 0x614000017088 at pc 0x560c1ac17136 bp 0x7ffeab146f20 sp 0x7ffeab146f10
READ of size 8 at 0x614000017088 thread T0
#0 0x560c1ac17135 in handle_destroy ../sway/desktop/output.c:566
#1 0x7f38af69330e in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
#2 0x7f38af5d3dfc in drm_connector_cleanup ../subprojects/wlroots/backend/drm/drm.c:1448
#3 0x7f38af5d2058 in scan_drm_connectors ../subprojects/wlroots/backend/drm/drm.c:1240
#4 0x7f38af5c6a59 in …
```

desktop: output: fix use-after-free in destroy

---

sway/commands/hide_edge_borders.c

This adds the missing argument count check after the --i3 flag
processing in cmd_hide_edge_borders. Without the check,
`hide_edge_borders --i3` would result in a SIGSEGV instead of a syntax
error. There are some minor adjustments to make it so nothing gets
altered if this check fails

cmd_hide_edge_borders: add missing arg count check

---

include/sway/commands.h
include/sway/config.h
sway/commands/seat.c
sway/commands/seat/xcursor_theme.c
sway/config/seat.c
sway/input/seat.c
sway/meson.build
sway/server.c
sway/sway-input.5.scd

This adds configuration commands that configures the XCursor theme and
size. Configuration is done through a new seat command (the size is optional and defaults to 24):
```
seat * xcursor_theme Adwaita [48]
```
The configured theme name and size is used as the default pointer
theme (set in `input/seat.c`), and exported through the `XCURSOR_THEME` and `XCURSOR_SIZE`
environment variables, and used as the default XWayland xcursor theme.
Marked as WIP since it's missing, at the very least, documentation updates. I would like to get some feedback first though, before I get to that.
The biggest changes (in addition to the new feature in itself) are:
* `XCURSOR_THEME` and `XCURSOR_SIZE` are now exported by the default seat, every time its xcursor configuration is changed. Thus all applications …

Implement XCursor theme configuration

---

sway/commands.c
sway/sway.5.scd

This matches i3's behavior of only retaining criteria across comma
separated commands. When separating commands with a semicolon, the
criteria is reset and allows for new criteria to be set, if desired.
Excerpt from [i3 user guide](https://i3wm.org/docs/userguide.html#command_criteria):
> When using multiple commands, separate them by using a , (a comma) instead of a semicolon. Criteria apply only until the next semicolon, so if you use a semicolon to separate commands, only the first one will be executed for the matched window(s).

criteria: reset on semicolon separation

---

swaybar/input.c
swaynag/swaynag.c

If the `XCURSOR_THEME` and/or `XCURSOR_SIZE` environment variables are
set, use the theme and size they define.
If they're not set, use the same defaults as before (system default
theme, size=24).
Note: this builds upon https://github.com/swaywm/sway/pull/4202, and was suggested here: https://github.com/swaywm/sway/pull/4202#issuecomment-497972719

swaybar/nag: use xcursor theme defined by XCURSOR_THEME/SIZE

---

swaymsg/main.c

Very minor edit.
On another note, I saw the TODO but couldn't figure a proper location for the constants in `common/`.

Add the missing constant for the switch input type

---

sway/input/seat.c

Commit 190546fd315a24c04006fb1b177069933f4350da failed to consider the
edge case where xwayland is disabled via the sway config. This leads to
a SEGFAULT when setting the xwayland cursor since the xwayland server is
not running.

Fix "xwayland false"

---

sway/input/cursor.c

Fix a small bug where the cursor becomes hidden after receiving a touch event until the surface is unfocused or sway receives a `set_cursor` event.

Unhide cursor on cursor activity after touch

---

include/sway/config.h
include/sway/input/keyboard.h
sway/commands/input.c
sway/commands/input/events.c
sway/config/input.c
sway/input/keyboard.c

Closes #4148 (this is the error part; see #4153 for something usable)
**Just the first commit**: basic invalid keymap prevention
Before the delta input config is stored, this attempts to compile a
keymap with it. If the keymap fails to compile, then the first line of
the xkbcommon log entry will be included with a `CMD_FAILURE`, the
entire xkbcommon log entry will be included in the sway error log, and
the delta will not be stored.
This will only handle basic issues such as a layouts not existing. This
will NOT catch more complex issues such as when a variant does
exist, but not for the given layout (ex: `azerty` is a valid variant,
but the `us` layout does not have a `azerty` variant).
**Both commits combined**: full invalid keymap protection
This allows for an optional validation stage …

Perform keymap validation

---

common/stringop.c
include/stringop.h
sway/commands.c
sway/tree/workspace.c

This fixes faulty command parsing introduced by
f0f5de9a9e87ca1f0d74e7cbf82ffceba51ffbe6. When that commit allowed
criteria reset on ';' delimeters in commands lists, it failed to account
for its inner ','-parsing loop eating threw the entire rest of the
string.
This refactors argsep to use a list of multiple separators, and
(optionally) return the separator that it matched against in this
iteration via a pointer. This allows it to hint at the command parser
which separator was used at the end of the last command, allowing it to
trigger a potential secondary read of the criteria.
Fixes #4239

Fix segfaults caused by faulty command parsing

---

include/sway/config.h
include/sway/input/seat.h
sway/commands/bind.c
sway/config.c
sway/input/seat.c
sway/main.c

Fixes #4224 
This adds the logic to defer binding execution while sway is still
initializing. Without this, the binding command would be executed, but
the command handler would return CMD_DEFER, which was being treated as
a failure to run. To avoid partial executions, this will defer all
bindings while config->active is false.

bindings: defer while initializing

---

sway/sway.5.scd

The missing underscore after "toggle" causes the underline to continue
for a whole sentence.

Add missing underscore in bindswitch documentation

---

include/sway/tree/root.h
sway/commands/move.c
sway/tree/container.c
sway/tree/root.c

Currently container_replace removes the container from the scratchpad
and re-adds it afterwards. For the split commands this results in the
container being send to the scratchpad, which results in a NULL segfault
if the same container should be shown.
Pass an optional workspace to root_scratchpad_add_container, if the
workspace is passed the window will continue to show on the workspace.
If NULL is passed it is sent to the scratchpad.
This was an issue if no other window except the scratchpad container was
on the workspace.
Fixes #4240

Fix sway crashes for scratchpad layouts

---

sway/commands/xwayland.c
sway/config.c

Fixes #4265 
Since xwayland can only be enabled/disabled at launch, the xwayland
status should be retained on reload. Having `xwayland enabled|disabled`
in the config, should not cause `config->xwayland` to be invalid on
reload. This also returns `CMD_FAILURE` with a message that xwayland
can only be enabled/disabled on launch when trying to set the invalid
status on reload. This allows swaynag to notify the user that the
change will not take effect until sway is restarted.

config/xwayland: retain xwayland status on reload

---

include/sway/commands.h
sway/commands.c

Without this change, the handlers listed in the config_handlers or
command_handlers arrays (depending on reading or active) in commands.c
would be valid subcommands. To make matters worse, they would also take
precedence over the defined subcommand handlers.
This corrects find_handler to only work on the handler array given
instead of implicitly trying others.

config: fix find_handler logic

---

sway/commands/seat.c

Fixes #4233 
This separates the logic for seat subcommand handlers that only perform
actions on the seat and handlers that alter the seat config. The former
group can immediately free the seat config after running the command as
it is only used by the subcommand to find the name of the seat to
operate on. The latter group alters the seat config so it will need to
go through the storage and application stage (assuming success).
_I chose the above solution rather than the proposed flag since this
constrains all of the logic to the seat command handler. Additionally,
a flag is useless for the remainder of the life of the seat config_

cmd_seat: split action and config handlers

---

sway/desktop/output.c

Using the content coordinates can go wrong if the surface inside the content is actually smaller than the content space.
You can see the effect if you run [havoc](https://github.com/ii8/havoc) and enter text on the very bottom line; if the content width/height is not an exact multiple of the cell width/height then the text will be cut off.
Somebody more familiar with the sway codebase can hopefully confirm that using pending coordinates instead of current ones has no bad side-effects.

use surface coordinates for damaging buffers

---

sway/tree/workspace.c

Fixes #4278 
The function used for comparing two output names in the workspace
output priority lists was inverted. This was causing priority to not be
stored correctly resulting in workspaces not always being restored or
moved to the desired outputs

ws-output-priority: fix logic issue in find_output

---

protocols/meson.build

Closes  #4209. This change replaces the meson `generator` used to generate protocol source files and headers with a set of `custom_target`s. Each distinct file is now generated only once.
I've also added a fix for the dependency for `lib_server_protos`, which should depend on `wayland_server` instead of `wayland_client`; this doesn't change the dependency list for the `sway` binary, because `libwlroots.so` links both client and server libraries.

Generate wayland protocol header/data code with custom_target

---

sway/tree/container.c
sway/tree/view.c

Currently, `border` is set to `B_CSD` after setting coordinates, messing up the `content_*` fields.

tree: set correct border value before creating floater

---

swaybar/swaybar-protocol.7.scd

This corrects the description of border_{top,bottom,left,right} in the
block properties table in swaybar-protocol.7. The values should be an
integer denoting the width/height rather than a boolean denoting
whether to show them.
_swaybar's implementation is correct. I just got mixed up when writing
the documentation_

swaybar-protocol.7: fix block border descriptions

---

include/sway/commands.h
include/sway/config.h
sway/commands/input.c
sway/commands/input/calibration_matrix.c
sway/config/input.c
sway/input/input-manager.c
sway/ipc-json.c
sway/meson.build
sway/sway-input.5.scd
sway/sway-ipc.7.scd

Can be used to change the orientation of a touchscreen.
Example usage with swaymsg:
swaymsg input type:touch calibration_matrix '"1 0 0 0 1 0"'
swaymsg input type:touch calibration_matrix '"0 -1 1 1 0 0"'
swaymsg input type:touch calibration_matrix '"-1 0 1 0 -1 1"'
swaymsg input type:touch calibration_matrix '"0 1 0 -1 0 1"'
Documentation:
https://wayland.freedesktop.org/libinput/doc/latest/absolute-axes.html#calibration-of-absolute-devices
I have never really written any C, so please don't hesitate to tell me if I did anything horrible C-wise.
Personally I'm unsure about a few things:
1) The struct I chose to represent the calibration matrix in `config.h`. I also tried using:
- A plain `float matrix[6]`, but there was no good way to represent the non-configured state.
- A `float …

Add calibration_matrix config option

---

include/sway/tree/container.h
sway/commands/swap.c
sway/input/seatop_move_tiling.c

I've always had the idea that the highlighted middle area would swap the current container, so I've implemented a quick solution for this.
This will also make it so that all 5 highlightable areas have unique actions. Previously, I've run into cases where the middle area would just perform the same action as one of the others.
I'm guessing we could add a config option for this if anyone feels strongly about using the middle area for swapping.
Now, I've added some code to see if the action should trigger a swap action and then just copied the swap function from `sway/commands/swap.c`. I don't know how the right way to solve this would be. Should we move in the swap function from `swap.c` into a central place or make the swap function a public function?
This is my first patch to sway, so I'm …

Make mouse drag in tiled mode swap containers if no edge is selected

---

include/sway/config.h
include/sway/input/switch.h
sway/commands/bind.c
sway/config.c
sway/input/switch.c
sway/sway.5.scd

Closes #4305
This adds a --reload flag to cmd_bindswitch that allows for the binding
to be executed on reload. One possible use case for this is to  allow
users to disable outputs when the lid closes and enable them when the
lid opens without having to open and re-close the lid after a reload.

cmd_bindswitch: add option to execute on reload

---

sway/input/input-manager.c

This adds checks to the `input_manager_libinput_reset_*` functions to
only attempt resetting supported options on reload. This should have no
functional difference to the user, but will remove several
`Failed to apply libinput config: Unsupported configuration option`
lines from the log that can be noisy and potential red herrings.

input/libinput: only reset supported options

---

sway/config/output.c

Fixes #4198
In `apply_output_config`, this sets `output->{width,height}` using the
values in the output box. Previously, they were being set using
`wlr_output_transformed_resolution`, which takes the width and height
from the wlr_output and just checks whether they should be swapped
based on the transform. This did not take into account the output's
scale. `wlr_output_effective_resolution` could be used instead, which
handles both transform and scale. However, the values in the output box
have already been processed by `wlr_output_effective_resolution` so they
can just be used directly

config/output: correctly set width/height in apply

---

sway/commands/layout.c

Fixes #4316 
Previously, `layout toggle` and `layout toggle split` would set L_VERT
when layout was L_HORIZ, otherwise it would set L_HORIZ. This meant
that when the layout was L_TABBED or L_STACKED, it would always be
L_HORIZ. This extends #4315 (which corrects the handling when multiple
layouts are given) to try prev_split_layout,
config->default_orientation, and then falling back to L_VERT when the
output is taller than wide and L_HORIZ when wider than tall.

cmd_split: fix toggle split for non-split layouts

---

include/sway/tree/container.h
sway/commands/move.c
sway/commands/resize.c
sway/commands/swap.c
sway/input/seatop_move_tiling.c
sway/tree/arrange.c
sway/tree/container.c

This is an alternative to #4283 that's implemented using width/height fractions of the parent container. It seems to make the code cleaner, although it also required changing the resize command to match. As far as I can tell everything works fine.
Fixes #3547
Fixes #4297

Fix layout when fullscreen

---

common/log.c
include/log.h
meson.build

Closes #3680. This uses `-fmacro-prefix-path` to make `__FILE__` strings independent of the filesystem location of the build directory. If the option is not available, it falls back to the second method described in https://github.com/swaywm/sway/issues/3680#issuecomment-463804964 .
The method used to identify the relative path prefix is ugly but straightforward. I am not aware of any simple ways to determine string lengths with Meson itself.
I've tested this change with gcc 9.1.0 (which supports `-fmacro-prefix-path`) and clang 8.0.0 (which does not yet support it, their patch depends on others which are not yet merged).

Use -fmacro-prefix-map to strip build path, when available

---

include/sway/tree/container.h
include/sway/tree/node.h
sway/commands/move.c
sway/commands/resize.c
sway/tree/arrange.c
sway/tree/container.c
sway/tree/view.c
sway/tree/workspace.c

Rework the gaps code to fix a series of bugs. The general approach is:
1. In tiled containers apply only gaps between containers directly in the layout code. This ensures proper sizing of containers. Fixes #4296 and #4294
2. For the gaps around the outside of workspaces (both outer and inner), calculate them together and apply them in the workspace code. At the end make sure they are positive and leave enough usable space in the container. Fixes #4304 and #4308
Depends on the layout PR (#4293) as it currently builds on top of it in the parts it touches the same code. But it doesn't depend on it functionally, so it can be reworked to apply to master.

Rework the gaps code to make it simpler and correct

---

sway/commands/fullscreen.c

This ensures that a child of a fullscreen container cannot be fullscreened.
Fixes #4332.

Make fullscreen check for fullscreen parents

---

include/sway/output.h
include/sway/server.h
sway/desktop/output.c
sway/server.c

The output manager config was not properly updated if the position
of the output got changed.

Update output manager on layout change

---

include/sway/commands.h
include/sway/config.h
sway/commands/input.c
sway/commands/input/xkb_file.c
sway/commands/input/xkb_layout.c
sway/commands/input/xkb_model.c
sway/commands/input/xkb_numlock.c
sway/commands/input/xkb_options.c
sway/commands/input/xkb_rules.c
sway/commands/input/xkb_variant.c
sway/config/input.c
sway/input/keyboard.c
sway/meson.build
sway/sway-input.5.scd

Adds a new commend "xkb_file", which constructs the internal
xkb_keymap from a xkb file rather than an RMLVO configuration.
This allows greater flexibility when specifying xkb configurations.
An xkb file can be dumped with the xkbcomp program.

Implement input_cmd_xkb_file (#3999)

---

sway/commands/output.c
sway/sway-output.5.scd

Closes #4345 
Similar to seat command, this provides an alias for the current output.
Instead of the output name or identifier, `-` can be used to operate on
the focused output by name and `--` can be used to operate on the
focused output by its identifier. This will prevent operating on the
no-op output when using either alias.

cmd_output: support current output alias

---

sway/commands/input/xkb_switch_layout.c

This just adds input type config support to input_cmd_xkb_switch_layout
so that `input type:keyboard xkb_switch_layout <idx>` will work

input_cmd_xkb_switch_layout: support input types

---

sway/tree/arrange.c

Fixes #4369 
When arranging the workspace, `prev_x` and `prev_y` should be ignoring the
current gaps otherwise the workspace `diff_x` and `diff_y` location deltas
will be off. When the deltas are off, each arrangement of the workspace
would incorrectly move floaters an extra `-workspace->current_gaps.left`
along the x-axis and an extra `-workspace->current_gaps.top` along the
y-axis.

arrange: remove gaps for workspace location deltas

---

include/sway/output.h
include/sway/server.h
include/sway/tree/view.h
meson.build
sway/desktop/layer_shell.c
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/ipc-server.c
sway/server.c
sway/tree/container.c
sway/tree/view.c

The documentation for wayland-server.h says:
> Use of this header file is discouraged. Prefer including
> wayland-server-core.h instead, which does not include the server protocol
> header and as such only defines the library PI, excluding the deprecated API
> below.
Replacing wayland-server.h with wayland-server-core.h allows us to drop the
WL_HIDE_DEPRECATED declaration.
This commit si similar to wlroots' ca45f4490ccc ("Remove all wayland-server.h
includes").

Remove all wayland-server.h includes

---

sway/commands/resize.c

Sibling amounts for resizing were being calculated after the original fraction had been altered. This led to broken resize amounts.
Fixes #4386

Fix resize sibling amount calculations

---

sway/input/libinput.c

Fixes #4387 
This fixes a typo in set_middle_emulation where it would set left
handed instead of middle emulation. _Apparently, I didn't do a 
good enough job double checking my refactor in #4342. Just
looked it over again and this looks like the only issue..._

input/libinput: fix typo in set_middle_emulation

---

sway/input/libinput.c

This just fixes the check in set_send_events for whether the mode has
changed. LIBINPUT_CONFIG_SEND_EVENTS_ENABLED is 0 so the bitmask check
cannot be fixed, but Sway doesn't allow multiple modes to be set anyway
(not really sure why you would need to) so a basic equality check works

libinput: fix set_send_events

---

sway/input/keyboard.c

~**This is built on #4342 so that'll have to be merged first.**~ #4342 has been merged
In sway_keyboard_config, do not change the keymap when the new keymap
is unchanged, unless this is during a config reload. The reasoning for
this is to prevent the effective layout from being reset to index 0 for
input config changes unrelated to the keymap.
For example,
```sh
swaymsg "input type:keyboard xkb_layout 'us,us'"
swaymsg "input type:keyboard xkb_variant ',dvorak'"
swaymsg "input type:keyboard xkb_options caps:toggle"
swaymsg "input type:keyboard repeat_delay 1000"
```

 input/keyboard: don't reset layout for same keymap 

---

include/sway/config.h
sway/commands/bind.c
sway/input/keyboard.c
sway/sway.5.scd

~**This is built on #4342 so that'll have to be merged first.**~ #4342 has been merged
Closes #3662 
This adds support for specifying a binding for a specific group. Any
binding without a group listed will be available in all groups. The
priority for matching bindings is as follows: input device, group, and
locked state.
For full compatibility with i3, this also adds Mode_switch as an alias
for Group2. Since i3 only supports this for backwards compatibility
with older versions of i3, it is implemented here, but not documented.

bindsym/code: add group support

---

sway/config/output.c

See https://github.com/swaywm/wlroots/pull/1762

Add support for wlr_output's atomic API

---

sway/input/libinput.c

This just fixes some typos in the reset functions that were using
the get calls instead of get_default

input/libinput: typo fixes (get -> get_default)

---

sway/commands/opacity.c
sway/sway.5.scd

This enhances the opacity command to support relative assignment as well
as the currently implemented absolute assignment. The syntax is inspired
by the syntax used in pactl and looks like this in a sway config:
// relative change (new feature)
bindsym button4 opacity +.1
bindsym button5 opacity -.1
// absolute change (already implemented)
bindsym button4 opacity 1
bindsym button5 opacity .3

cmd_opacity: add relative opacity changes

---

sway/commands/swap.c

For feature parity with i3 4.17, this just adds floating container
support to the swap command
https://github.com/i3/i3/blob/next/RELEASE-NOTES-4.17

cmd_swap: add floating support

---

sway/input/cursor.c

Closes #4420
This just adds a small quality of life improvement to the cursor hiding
functionality. The cursor will no longer be hidden unless all buttons
are released.

input/cursor: do not hide when buttons are pressed

---

swaymsg/main.c
swaymsg/swaymsg.1.scd

This mirrors a change in i3 4.17 that returns 2 for errors from sway,
including invalid command, command failed, and invalid subscription
requests
https://github.com/i3/i3/blob/next/RELEASE-NOTES-4.17
https://github.com/i3/i3/pull/3614

swaymsg: return 2 for sway errors

---

sway/commands/mode.c

This mirrors a change in i3 4.17 that makes binding modes case
sensitive
https://github.com/i3/i3/blob/next/RELEASE-NOTES-4.17

cmd_mode: make modes case sensitive

---

sway/config/output.c

Fixes #4410
When applying an output config, an output may transform or be altered
in some way that effects the cursor. In order for the cursor images to
be updated properly, all cursors need to be rebased after applying
output configs.

config/output: rebase cursors after config applied

---

sway/sway.5.scd

Closes #4411
This clarifies the syntax to use for the font command to enable pango
markup support.

sway.5: explain how to enable pango markup in font

---

sway/config/output.c

This reverts commit 6e0565e9de4247bbf0ca662565c58e0a54258d6e.
This is required for the revert on swaywm/wlroots#1781

Revert "Add support for wlr_output's atomic API"

---

sway/desktop/layer_shell.c

This can happen with surfaces that set negative margins.

layer_shell: Guard against negative exclusive zone

---

sway/input/seat.c

Fixes #4444 
In handle_seat_node_destroy, it was possible to focus the node attached
to the seat node that is being destroyed when an empty workspace was
being destroyed in a multiple seat environment. This resulted in
infinite recursion when attempting to destroy the workspace. This just
moves the seat node destruction higher so it cannot be the focus
inactive for the seat. This is the same ordering that is applied to
destruction of seat nodes for containers
--
On a related note, since seats have their own focus, should the workspace
not actually be destroyed until all seats have switched focus away (even if
the workspace is hidden) instead of forcing all seats to vacate the empty
workspace?

handle_seat_node_destroy: do not focus own node

---

sway/tree/workspace.c

Follow-Up for #4446 
Since each seat has its own focus, do not destroy a workspace until it
is no longer focused by any seat. This prevents seats from being forced
to evacuate the workspace just because another seat switched focus away
from it

workspace: do not destroy if any seat is focusing

---

swaymsg/swaymsg.1.scd

Closes #4443
This adds a tip to the command section about using two hyphens before a
command to signal that no swaymsg options will follow to allow for sway
commands with leading hyphens.

swaymsg.1: add tip about two hyphens for commands

---

sway/tree/container.c

Fixes #4422
This copies the width and height fractions from the container to the
container replacing it. Without setting these values, the container
is treated as a new container and throws off the existing sizing. Since
one container is replacing the other, it makes sense for the sizing to
remain the same.

container_replace: copy {width,height}_fraction

---

sway/tree/workspace.c

Fixes #4423
In workspace_split, the middle container that wraps the workspace's
children should be focused for any seat that is focusing the workspace

workspace_split: focus middle if workspace focused

---

include/sway/layers.h
sway/desktop/layer_shell.c
sway/desktop/output.c
sway/input/cursor.c

Supports nested popups as well.

layer-shell: add support for popups

---

sway/sway-bar.5.scd
sway/sway.5.scd

Closes #4457 
This just specifies that both cmd_font and bar_cmd_font should be
specified using the pango font description and adds a link to the pango
documentation regarding the font description

sway{,-bar}.5: add link to pango font description

---

sway/desktop/output.c

`pixman_region32_contains_rectangle()` returns `pixman_region_intersection_t` not a `bool`.
We need to check whether the intersection is `PIXMAN_REGION_IN`, otherwise we can have `PIXMAN_REGION_PART` if for example the layer surface is smaller than the output.

properly check pixman_region32_contains_rectangle return

---

include/sway/input/keyboard.h
sway/input/keyboard.c
sway/input/seat.c

Fixes #3063
Fixes #3196
This keeps track of whether surfaces received a key press event and
will only send a key release event if the pressed event was sent. This
also requires changing the keycodes that are sent via wl_keyboard_enter
to only include those that were previously sent. This makes it so
surfaces do not receive key release events for keys that they never
received a key press for and makes it so switching focus doesn't leak
keycodes that were consumed by bindings.

input/keyboard: send released only if pressed sent

---

include/sway/config.h
sway/commands/xwayland.c
sway/config.c
sway/server.c
sway/sway.5.scd

Closes #4359
This just adds a force option to cmd_xwayland that allows for xwayland
to be immediately launched instead of lazily launched. This is useful
for slower machines so it can be part of the startup time instead of
when the user is actively trying to use it

cmd_xwayland: add force for immediate launch

---

sway/commands/move.c
sway/tree/container.c

i3 allows this and it seemed easy to support here as well.

Allow moving a container hidden in scratchpad

---

sway/sway.5.scd

It looks like floating_scroll was still in the sway(5) man page as a
remnant of the 0.x era. This just removes it from the man page since it
is no longer a valid command. Mouse bindings with Button4-7 can be used
instead

sway.5: remove mention of floating_scroll

---

sway/commands/move.c

**Behavior matches i3 PR: https://github.com/i3/i3/pull/3776**
Fixes #4473 
When moving to a scratchpad hidden container (using
`move [window|container] [to] mark <mark>`), this moves the container to
the scratchpad (equivalent to `move [window|container] [to] scratchpad`).
Previously, this would crash since the destination did not have a
workspace.

cmd_move: fix move to scratchpad hidden container

---

sway/sway.5.scd

Use explicit linebreaks to make scdoc use a separate line for each entry
listed

Fix formatting for title_format in man 5 sway

---

sway/desktop/layer_shell.c

This should fix issue #4407 and definitely fixes #4461

A layer-shell will only be focused if it is non-null

---

sway/commands/mode.c

In cmd_mode, the mode is currently being reset to the default mode after
a mode subcommand handler is executed. This stores and restores the mode
instead

cmd_mode: don't reset to default after subcommand

---

sway/input/seat.c

Load xcursor theme on configuring pointer or tablet tool only if
there was no pointer cap before.
With #4521 , this also avoid resetting cursor to left_ptr if new
device is added but there was pointer cap already.

seat: avoid unneeded reloading xcursor theme

---

sway/input/seat.c

This make seat_update_capabilities set cursor image only if
there was no pointer cap before update. This avoid resetting
cursor to left_ptr if an input device is removed.

seat: set cursor image only if no pointer cap previously

---

sway/desktop/layer_shell.c

The current seat may have changed between the last focus change and
this unmap, so we need to scan through all seats to find our layer.

Ensure that seat->focused_layer is cleared on unmap

---

sway/desktop/layer_shell.c
sway/input/seat.c

Focused layers are not cleared when destroyed, they are cleared on unmap.
Giving focus to an unmapped layer surface is (1) incorrect and (2) triggers a
use-after-free.
Closes: https://github.com/swaywm/sway/issues/4517
Closes: https://github.com/swaywm/sway/issues/4502

layer-shell: don't give focus to unmapped layer surfaces

---

sway/sway-ipc.7.scd

`man sway-ipc` incorrectly showed a `bar_status_update` event, when the event is `bar_state_update`.

Fix bar_state_update docs

---

swaybar/tray/item.c

I felt it inappropriate to mutate the `sni->tray->basedirs` list, though I'm sure this isn't the right way of going about this, but I'm new to the code base and my C is a little rusty.
This (or some variation of this) results in the proper icon being displayed in the tray for Quassel, I've not tested against anything else.

Fully search icon_theme_path if icon isn't found in expected paths

---

sway/input/seatop_default.c

Fixes #4529
This matches i3's behavior of only focusing a container when pressed.
This allows for `bindsym button1 nop`, `bindsym BTN_LEFT nop`, or
`bindcode 272 nop` to be used to disable focusing when clicking on the
title (or with additional flags to `bind{code,sym}` other portions of
the container).
Without this additional condition, the user would need both
`bindsym button1 nop` and `bindsym --release button1 nop` to override
both the pressed and released behavior.

seatop_default: only focus container on press

---

include/swaybar/bar.h
include/swaybar/config.h
sway/commands/bar.c
sway/commands/bar/hidden_state.c
sway/commands/bar/mode.c
sway/commands/bar/output.c
sway/commands/bar/status_command.c
sway/commands/bar/tray_output.c
sway/config/bar.c
sway/sway-bar.5.scd
sway/sway.5.scd
swaybar/bar.c
swaybar/config.c
swaybar/ipc.c
swaybar/status_line.c

Supersedes/Closes #4159
Supersedes/Closes #4500
Closes #4533 
This adds complete support for the barconfig_update ipc event. This also
changes the bar command and subcommand handlers to correctly emit the
event. This makes it so all bar subcommands other than id and
swaybar_command are dynamically changeable at runtime. sway-bar.5 has
been updated accordingly
_Note: Although this does provide a solution for #4500/#4533, it does not handle
the generic case of the status command process not being terminated when
swaybar segfaults or aborts. I'm not sure what the best solution for that would be_

swaybar: complete barconfig_update event handling

---

sway/sway-input.5.scd

While I'm at it could I ask a question?
I have a device that provides absolute events (a wacom tablet), how can I make it relative?

Fix typo (an -> and)

---

sway/sway.5.scd

Related to #4542 
This just clarifies that a mark can only be set for a single window
since they are used as unique identifiers

sway.5: clarify that a marks are unqiue

---

sway/sway-output.5.scd

__foo__ is verbatim in scdoc, but we want the variable foo in italic,
i.e. _foo_.

sway-output.5: fix variable name

---

sway/desktop/render.c

Fixes #4451, requires https://github.com/swaywm/wlroots/pull/1798.
There's one issue: it looks like the very first drawn frame frequently gets a discarded presentation feedback. I can't quite figure out why. Is there any other path where a surface can get rendered? I tried adding a similar call to `render_saved_view` but that didn't help.
Update: might actually not be an issue, but just how new tiled views are handled and how the timings align.
Update 2: I recorded the screen with my phone and it seems that the discarded/presented notifications correspond exactly to frames shown on screen, so yeah, looks like no issue with this PR.
Update 3: Actually, sometimes it does seem to deliver discarded events to presented frames, most notably when resizing a floating window with mouse fast …

render: set surface as sampled for presentation

---

swaybar/render.c

Other components like workspace button, status line (error or plain
text) already render text at integer coords. This make status block
also render text at integer coords.

swaybar: make status block text render in the same way as others

---

sway/main.c

Otehrwise it's pretty easy to misremember a flag and think damage=rerender is
enabled when it's not.

Error out on unknown debug flag

---

sway/tree/view.c

This is my attempt at fixing #4578 . This is my first time working on sway, so sorry if there is a glaring issue with the patch.
My understanding is this: some criteria like 'tiling' and 'floating' predicates need a container to determine if they match. When container is null it causes a segfault. All I've done is move container_create earlier in view_map so that it precedes select_workspace and all the criteria can check matches without error.
This avoids the segfault for me, and it doesn't seem that view is modified in the intermediate code, so I don't think there will be unintended side-effects.

Create container before selecting workspace

---

meson.build

wlroots versions are incompatible with each other. Often our users struggle
with figuring out that their wlroots version is too old after a new release.
Use a more strict version check to prevent building sway with incompatible
wlroots versions.

build: update wlroots version, be more strict

---

include/sway/input/cursor.h
include/sway/input/seat.h
include/sway/input/tablet.h
include/sway/server.h
protocols/meson.build
sway/input/cursor.c
sway/input/seat.c
sway/input/tablet.c
sway/meson.build
sway/server.c

This implements the wlr tablet v2 protocol, including fallback events for surfaces that do not support it. This is mostly based on the code in Rootston, but differs enough thanks to Sway's input system being reasonably different from Rootston's.
Most things seem to work correctly at this point. I do not own a tablet with certain features (like tilt, or a ring) so I can not test all functionality.
Applications tested:
Fixes #2288.

Full drawing tablet support.

---

sway/desktop/output.c
sway/desktop/render.c

Sometimes when using direct scan-out, some flickering between the
fullscreen app and the regular desktop could be seen.
This happened because we called wlr_output_attach_render and then
wlr_output_attach_buffer for direct scan-out. wlr_output_attach_render
makes the OpenGL context current but also attaches the OpenGL buffer to
the primary plane apparently (all of this happens inside
eglMakeCurrent).
This patch moves the scan-out logic outside of output_render, before
wlr_output_attach_render. This lines it up with rootston's
implementation. This also makes more sense since no rendering is
involved when using direct scan-out.
Sorry about that, I should've tested this with more clients. The new
code has been tested with mpv and a GLFW demo.

Fix direct scan-out flickering

---

sway/desktop/layer_shell.c

Popups are positioned relative to local surface coordinates of the parent surface. There's no need to consider values set with `xdg_surface.set_window_geometry` for parent surfaces.
This fixes damaging issues in mate-panel.

layer-shell: Fix damage tracking of nested popups

---

sway/sway-output.5.scd

Some examples use comma to separate x and y for setting the output
position which is wrong.
Let's change it to spaces, as correctly demonstrated in the
`output <name> position|pos <X> <Y>` section.

Fix syntax in examples in sway-output(5)

---

meson.build

Fixes an invalid option warning from Meson.

build: remove rootston from wlroots subproject

---

sway/sway.5.scd

Just like the title / commit messages say. Both of the changes follow the style used in other descriptions.

sway(5): Add a missing verb, highlight a valid value in the description of tiling_drag

---

sway/sway.5.scd

According to the source files, workspace_layout is a configuration only
command, move it to the correct section within the man page.
Fixes #4607

sway(5): move workspace_layout to config only

---

meson.build

Don't use the latest tag, always use the project version for the version
string. Because of version branches, getting the version from Git can be
unreliable.
Closes: https://github.com/swaywm/sway/issues/4631

build: always use the project version

---

sway/desktop/xwayland.c

Fixes #4647
When changing a surface from managed to unmanaged in handle_map(), the
call to handle_destroy(.., view) causes the sway_xwayland_view pointed
to by the untyped wlr_xwayland_surface.data field to become invalid
garbage, yet the untyped wlr_xwayland_surface.data continues to point
at it.  In particular: view_get_*(view_from_wlr_surface(..)), even
with appropriate NULL checking, will crash sway when this codepath is
exercised (reliable test case: drop-down menus in Google Earth).

xwayland.c handle_map(): NULL out xsurface->data() to prevent crashing.

---

sway/config/output.c
sway/desktop/output.c

When applying config, value mode->refresh is mHz; convert it to Hz before
assigning it to the temporary output config. oc->refresh_rate will
be converted back to mHz in set_mode function.
Fix debug log printing GHz instead of Hz.
Based on #4577, fixes https://github.com/emersion/kanshi/issues/51 .

Fix refresh rate scale of output

---

include/swaybar/tray/item.h
swaybar/tray/item.c
swaybar/tray/tray.c

In case a tray icon cannot be found or does not have a desirable size, swaybar retries the search again and again, which increases load on disk and CPU.
This commit solves it by storing `target_size` for each icon, so that swaybar does not search for an icon of some size if it already tried to.
Fixes #3789.

swaybar: do not retry search for tray icons

---

swaybar/tray/item.c

swaybar: fix typo in the loop over pixmaps

---

sway/input/seatop_default.c

Fixes regression introduced in 2c1a11016ccb7646a74de51eff003c18e5aa7902
Fixes #4659
cc @versusvoid

Fix tiled containers resize with mouse

---

include/sway/output.h
sway/config/output.c
sway/desktop/output.c
sway/tree/output.c

See individual commit messages.
Closes: https://github.com/swaywm/wlroots/issues/1867

Fix output manager segfault

---

sway/commands/focus.c
sway/sway.5.scd

Support `focus prev|next [sibling]` from i3 -- steps 2+3 for #4638 .
PTAL. If the behavior does not match i3, let me know.

Support focus next|prev [sibling] i3 commands

---

include/sway/criteria.h
sway/criteria.c

This is another fix for #4586 which replaces #4587.
This time, I have modified criteria to make a literal comparison rather than a regex comparison when the attribute value is `__focused__`. The behavior should now better match [i3's logic](https://github.com/i3/i3/blob/7db0d179a3aa659f1dc109012d253403094c72a2/src/match.c) .
previously, the criteria->autofail field was used to disqualify criteria that had a `__focused__` attribute value, but had no focused container at the time of parsing. Criteria now compare against the focused container at match time, like i3 does, so the field is no longer necessary, but criteria should have the same matching behavior as before.
con_id never made a regex comparison in the first place, so I kept the logic the same. When there is no focused container, …

criteria: make literal comparison for __focused__ values

---

include/sway/layers.h
sway/desktop/layer_shell.c

Closes: https://github.com/swaywm/sway/issues/4644
References: https://github.com/emersion/rootston/commit/1982106c9b0fbd48ee9fe20e013524125f6ca3cf

Handle layer changes for layer shell surfaces

---

sway/config.c

Currently commented lines ending in the backslash character will be
concatenated with the following line.
```
exec swaynag -m 'will not run'
```
This change modifies `getline_with_cont` to stop reading when the
initial character is a '#'.
Closes #4585

Skip line continuation when it is a comment

---

sway/commands.c
sway/commands/focus.c
sway/config.c
sway/config/bar.c
sway/input/seat.c
sway/main.c

Some memory leaks in more or less pathological code paths, some simplifications and defensive null checks.
Most of these were found by running clang-tidy/analyzer.

Various small fixes

---

client/pool-buffer.c
common/util.c
include/util.h
sway/config/bar.c
sway/config/output.c
sway/swaynag.c

set_cloexec is defined by both sway and wlroots (and who-knows-else),
so rename the sway one for supporting static linkage. We also remove
the duplicate version of this in client/.
Fixes: https://github.com/swaywm/sway/issues/4677

Rename symbol set_cloexec to sway_set_cloexec, remove duplicates.

---

sway/commands/focus.c

Closes #4689 
It appears i3 just does nothing in this case, so we should too.

focus: do nothing on focus prev|next for workspaces

---

include/sway/config.h
sway/commands/output/mode.c
sway/config/output.c
sway/sway-output.5.scd

This forces to set the mode as a custom mode.
Closes: https://github.com/swaywm/sway/issues/3791 (with https://github.com/swaywm/wlroots/pull/1881)

Add --custom to `output mode` command

---

sway/config/output.c

best is NULL prior to being assigned to a mode.
Closes: https://github.com/swaywm/sway/issues/4705

Fix segfault in set_mode

---

sway/config/output.c

Instead of relying on the order of modes, use wlr_output_preferred_mode
to get the preferred mode.

Use wlr_output_preferred_mode instead of the last mode

---

sway/input/seatop_default.c

- Move unmanged xwayland block down where it belongs
- Only apply to override_redirect windows
- Move focus and return into wants_focus bit so we don't exit early for xwayland views that don't want focus, in case more blocks get added below.
Fixes #4707

seatop_default: handle focus for unmanaged xwayland windows last

---

sway/desktop/xwayland.c

Previously, Xwayland windows did not have size_constraints implemented,
resulting in the window being resizable. This implements the constraints
through the X11 size hints supplied by the window itself.
Should fix the Xwayland part of #4710

xwayland: get_constraints using size hints

---

contrib/grimshot

The previous behavior was incorrect because `if` was checking the return
status of the `[` command which was never going to be an error. `[`
seems to only return an error if no args are provided. This was
basically a useless use of `[` anyway since it was just meant as a
straight interpretation of command exit, something that `if` can do
itself.
Compare:
```sh
[ ]; echo ?=$?
[ /bin/false ]; echo ?=$?
if [ /bin/false ]; then echo this is the unintended bug; fi
if /bin/false; then echo this will not be printed; fi
```

grimshot: fix branching on command exit status

---

meson.build

-Wmissing-braces makes it annoying to zero-initialize structs with = {0}
when the first field is a struct. See for instance [1].
[1]: https://builds.sr.ht/~sircmpwn/job/110425

Add -Wno-missing-braces

---

include/sway/commands.h
include/sway/config.h
include/sway/output.h
include/sway/server.h
include/sway/surface.h
include/sway/tree/view.h
sway/commands.c
sway/commands/max_render_time.c
sway/commands/output.c
sway/commands/output/max_render_time.c
sway/config/output.c
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/surface.c
sway/ipc-json.c
sway/meson.build
sway/server.c
sway/sway-output.5.scd
sway/sway.5.scd
sway/tree/output.c
swaymsg/main.c

Requires https://github.com/swaywm/wlroots/pull/1832.
This PR establishes the necessary infrastructure to delay output renders and frame callbacks to reduce the visual latency between a surface committing new contents and the contents being shown on-screen. Additionally, it adds configurable **constant** delays to individual output renders, and to individual view frame callbacks. The way the code is structured makes it possible to subsequently add some kind of an _adaptive_ mode which figures out the delays automatically for lowest possible latency with minimal dropped frames.
For more details on how this works see [how it's done in Weston](https://www.collabora.com/about-us/blog/2015/02/12/weston-repaint-scheduling/): this PR does pretty much the exact same thing, except it also adds …

Repaint scheduling

---

sway/input/keyboard.c

Fixes https://github.com/swaywm/sway/issues/4637#issuecomment-542271957
This fixes an inverted fclose return value check and simplifies the
error handling and logging for xkb_file in sway_keyboard_compile_keymap

input/keyboard: cleanup xkb_file error handing

---

common/stringop.c
include/stringop.h
sway/commands/input/xkb_file.c
sway/commands/output/background.c

Closes https://github.com/swaywm/sway/issues/4637#issuecomment-542679437
This allows for shell path expansion for input_cmd_xkb_file. The logic
has been extracted from output_cmd_background

input_cmd_xkb_file: allow shell path expansion

---

include/sway/commands.h
include/sway/config.h
include/sway/input/keyboard.h
include/sway/input/seat.h
sway/commands/seat.c
sway/commands/seat/keyboard_grouping.c
sway/config/seat.c
sway/input/input-manager.c
sway/input/keyboard.c
sway/input/seat.c
sway/meson.build
sway/sway-input.5.scd

**Depends on wlroots PR swaywm/wlroots#1771**
Related swaywm/wlroots#1217
Related #2897
Closes #3847
A wlr_keyboard_group allows for multiple keyboard devices to be
combined into one logical keyboard. This is useful for keyboards that
are split into multiple input devices despite appearing as one physical
keyboard in the user's mind.
This adds support for wlr_keyboard_groups to sway. There are two
keyboard groupings currently supported, which can be set on a per-seat
basis. The first keyboard grouping is none, which disables all grouping
and provides no functional change. The second is keymap, which groups
the keyboard devices in the seat by their keymap. With this grouping,
the effective layout and repeat info is also synced across keyboard
devices in the seat. Device specific bindings …

Add support for wlr_keyboard_group

---

sway/desktop/output.c
sway/desktop/render.c

See https://github.com/swaywm/wlroots/pull/1919
This has the advantage to (1) reduce boilerplate and (2) make us
correctly handle wlr_output_event_present.commit_seq.

Use new presentation-time API

---

sway/input/seat.c

When being created, non first seats would get through the list of devices
without the list being first initialised -> segfault.
Issue introduced with ab0248a54564b2f644b6fb367f9eb44fe0bf5f3c
Fixes #4750: Crash when reloading Sway with multiple seats configured

input: seat: Fix seat device list not initialised before use

---

sway/input/keyboard.c

Fixes #4752
In sway_keyboard_destroy, only remove the keyboard from a keyboard
group, if it is part of a keyboard group. If the keyboard is not part of
a keyboard group, then there is nothing to remove it from

input/keyboard: check keyboard group before remove

---

sway/commands/input.c
sway/config.c
sway/input/input-manager.c

Fixes #4744 
For the validation pass of reloading, there is no need to touch swaybg,
swaynag, inputs, outputs, or seats. This drastically improves the speed
of a reload by skipping over the expensive I/O configuration and
handling of wayland clients. As long as the syntax is valid, the
CMD_FAILURE's can be relayed during the actual reload.

config: improvements to the reload validation

---

sway/input/keyboard.c

Fixes #4758 
If a sway keyboard is being destroyed, then the keyboard is being
removed from a seat. If the associated wlr_keyboard is the currently
set keyboard for the wlr_seat, then we need to reset the wlr_seat's
keyboard to NULL so it doesn't reference an invalid device for the seat.
The next configured keyboard from the seat or the next keyboard from
that seat that has an event will then become the seat keyboard.
Similarly, this needs to be done for a wlr_keyboard_group's keyboard
when the wlr_keyboard_group is being destroyed.

input/keyboard: reset seat keyboard on destroy

---

sway/sway-ipc.7.scd

While implementing rust bindings for the sway-ipc I noticed this small bug in the sway-ipc docs.
Hope this will prevent future confusion if someone wants to implement other bindings.

Rename field 'node' to 'nodes' from the 'GET_TREE' reply in the sway-ipc docs

---

sway/desktop/output.c

max_render_time can be set on output, view, or both. However, if only
applied to the output, send_frame_done_iterator would erroneously send
frame_done immediately, ignoring the output max_render_time. As
damage_handle_frame processed max_render_time correctly, idle frames
would be blocked in anticipation of the delay that was meant to happen.
Without the delay, frame events would be dispatched during the idle
frame block, and some clients would never receive the frame done events
they had requested, at least not until something else actively drove
another render.
Respecting both view and output max_render_time in
send_frame_done_iterator ensures that the frame events are always
correctly delayed.
Fixes #4756

output: Ensure that frame_done is delayed on max_render_time

---

include/sway/output.h
sway/desktop/output.c

The previous fix (#4766) was discovered to just treat a symptom rather than the cause, and did not account for proper use of per-view max_render_time.
This PR restores the original behavior of view max_render_time, and instead ensures that surface commits always result in a frame being scheduled, even if it occurred during our frame schedule block.

output: Really fix max render time

---

sway/sway-ipc.7.scd

While implementing rust bindings for the sway-ipc I noticed this small bug in the sway-ipc docs.
Hope this will prevent future confusion if someone wants to implement other bindings.

fix bar_state_update/input event in sway-ipc docs

---

sway/sway-ipc.7.scd

Reverts swaywm/sway#4775
As @RedSoxFan pointed out I forgot the hex conversion. My fault, sorry!

Revert "fix bar_state_update/input event in sway-ipc docs"

---

sway/config.c

Fixes #4780 
When making the reload validation improvements (#4757), I forgot that
input type configs are stored in a separate list. This makes it so input
type configs are correctly applied on reload.

config: apply input type configs on reload

---

contrib/autoname-workspaces.py
contrib/inactive-windows-transparency.py

I changed `inactive-windows-transparency.py` so that the transparency gets removed when the script is terminated and added a command line option to set the transparency value.
`autoname-workspaces.py` is a script that adds icons to the workspace name for each open application.

Improve and add contrib scipts

---

include/sway/input/cursor.h
sway/input/cursor.c

Fixes #4724.
This change can be tested quite easily if you use a backend which supports gestures (i.e. libinput). Open evince and your favourite pdf and you shall now see that pinch-to-zoom works properly. Prior to this, pinch-to-zoom would not do anything since the pinch and swipe events generated by the libinput backend are not handled anywhere (i.e. passed to the active client).
I'm not too sure how this will affect #1904 but I think there shouldn't be a huge change, as this change is solely passing pointer gestures to clients, rather than detecting a configurable gesture and executing a sway routine.

Pass gesture events to clients

---

sway/input/cursor.c

Part of #4794. Forgot to remove gesture listeners when the
cursor is destroyed.

input/cursor: remove gesture listeners in destroy

---

sway/desktop/layer_shell.c

Fixes #4599 
If a layer is focused by any seat, it needs to be unfocused on unmap. If
the unmap was due to an output being disabled, there would not be a
sway_output and unmap would do an early return. This results in a
use-after-free if the layer was focused by any seat prior to being
unmapped. This change just moves the refocusing code above the early
returns.

layer-shell: unfocus output-less layer on unmap

---

sway/tree/root.c

Showing a window in the scratchpad can move a visible scratchpad window
from another workspace to the current one. If the scratchpad window was
the last visible container in that workspace, the old workspace should
be destroyed.
Fixes #4806

Fix lingering workspace with scratchpad show

---

include/sway/commands.h
include/sway/config.h
include/sway/input/seat.h
sway/commands/seat.c
sway/commands/seat/idle.c
sway/config/seat.c
sway/input/cursor.c
sway/input/keyboard.c
sway/input/seat.c
sway/input/switch.c
sway/meson.build
sway/sway-input.5.scd

This adds seat configuration options which can be used to configure what
events affect the idle behavior of sway.
An example use-case is mobile devices: you would remove touch from the
list of idle_wake events. This allows the phone to stay on while you're
actively using it, but doesn't wake from idle on touch events while it's
sleeping in your pocket.

Add seat <seat> idle_{inhibit,wake} <sources...>

---

sway/input/keyboard.c

Fixes #4799 
This includes two fixes related to changing the keymap of the last keyboard in a keyboard group with a keyboard binding. The first commit removes the listeners for the keyboard group's keyboard when destroying the keyboard group. The second commit defers the destruction of the wlr_keyboard_group until idle so that the keyboard group's keyboard is not destroyed in the middle of handling the key event for the binding.

input/keyboard: keyboard group destruction via keybind fixes

---

sway/tree/root.c

I think this fixes @edrex's [crash](https://github.com/swaywm/sway/issues/4065#issuecomment-532890928) in #4065. Either way, this does fix a crash when hiding a scratchpad container when any of it's descendants are fullscreen
Any descendant of a scratchpad container may be fullscreen so checking
to see if the top-level scratchpad container is fullscreen in
root_scratchpad_hide is not sufficient. This iterates through all
descendants of the scratchpad container

root_scratchpad_hide: disable fullscreen descendants

---

sway/input/seatop_default.c

Fixes #4728 
When clicking on the titlebar of a floating container (or descendant of
a floating container), the top-level floating container was being
focused and then allowing you to move the top-level floating container.
This made it so you couldn't switch to a different tab/stack within the
floating container. With this patch, the focus inactive view for the
container that the titlebar is associated with is focused, then the
traversal to the top-level floating container is performed to use with
the move floating operation.

input/seatop_default: fix focusing floating titles

---

include/sway/config.h
include/sway/input/keyboard.h
sway/commands/seat/keyboard_grouping.c
sway/input/keyboard.c
sway/sway-input.5.scd

Closes #4811 (this indirectly fixes the second bullet)
This removes `seat <seat> keyboard_grouping keymap` and replaces it with
`seat <seat> keyboard_grouping smart`. The smart keyboard grouping will
group based on both the keymap and repeat info. The reasoning for this
is that deciding what the repeat info should be for a group is either
arbitrary or non-deterministic when multiple keyboards in the group have
repeat info configured (unless somehow exposed to the user in a
reproducible uniquely identifiable fashion).

seat_cmd_keyboard_grouping: change keymap to smart

---

sway/desktop/surface.c

This change fixes the specific segfault mentioned in #4796.

desktop/surface: Fix crash when timer is NULL

---

sway/config/output.c

An accidental regression from 2f84d6e. scale_filter may change via the ipc even if scale has not changed.
This code previously lived in the `if (oc && oc->scale)` block, but previously an unset scale always meant an output scale of 1, so there was no issue when scale_filter wasn't applied. The more correct place to apply scale_filter seems to be in it's own block.

config/output: apply scale_filter even when scale has not changed

---

sway/desktop/layer_shell.c

Fixes #4840 
When arranging layer-shell layers, verify that the currently focused
layer, if any, for each seat is still keyboard interactive. If the layer
is no longer keyboard interactive and there is not a keyboard
interactive overlay or top layer to change the focus to, refocus the
focus inactive node for the seat.

layer-shell: refocus if keyboard interactive lost

---

common/util.c
include/sway/commands.h
include/swaybar/i3bar.h
include/util.h
sway/commands.c
sway/commands/bar/colors.c
sway/commands/client.c
sway/config.c
swaybar/i3bar.c
swaybar/ipc.c
swaybar/render.c
swaynag/config.c

There are currently multiple color parsing functions in use by sway. This purpose of this PR is to remove some duplicated code and refactor some of the calling code along the way. This PR also ensures that although the colors may be stored in different formats (uint32_t, float[4], const char *), they are all parsed in the same way.
See the individual commits for the full commit messages, but here's a summary:
- First commit: adds color validation to parse_color and refactors swaybar's ipc_parse_colors
- Second commit: remove duplicated float array color code in cmd_client_* and config
- Third commit: remove add_color and refactor bar_cmd_colors color parsing
_Note: I am aware that this PR does not touch the color validation for colors in `output_cmd_background`. For that command, the …

Refactor color parsing related code

---

sway/commands/client.c
sway/sway.5.scd

Closes #4822 
For i3 compatibility, allow the indicator and child_border colors values
to be optional. The indicator will fallback to sane defaults and
child_border will fallback to the background color for the class.

cmd_client_*: support optional args for i3 compat

---

sway/config/output.c
sway/desktop/output.c

This reverts commit 724926ea6ae119956dc7b1e39c2e30c1e3657676 and
re-applies commit 6e0565e9de4247bbf0ca662565c58e0a54258d6e.
See also: https://github.com/swaywm/wlroots/pull/1797 (wlroots PR)
See also: https://github.com/swaywm/sway/pull/4355 (Original sway PR)
See also: https://github.com/swaywm/sway/pull/4434 (Revert sway PR)

Re-add support for wlr_output's atomic API

---

sway/config/output.c

This fixes a crash where the `oc->name` would be accessed by sway_log()
even when `oc` was NULL.

Fix sway_log using non initialised output_config pointer

---

include/sway/tree/container.h
sway/commands/resize.c
sway/tree/arrange.c

Because the layout code rounds down the dimensions of the windows resizing would often be off by one pixel. The width/height fraction would not exactly reflect the final computed width and so the resize code would end up calculating things wrong.
To fix this recompute the width/height fractions after rounding down and adjust the resize amount by 0.1 pixels to always survive the rounding down correctly when we end up on the fence.
Also adjust the gaps calculation to not end up with fractions of a pixel in the case where the gaps were sized down for lack of space.
Fixes #4391

Fix numerical issues in resize

---

include/sway/tree/container.h

Containers are always fixed to the pixel grid so position and size them with integers instead of doubles.
Functionally this should be no different since rounding down is already being done on things like layout. But it makes it clear what the intention is and avoids bugs where fractional pixels are used. The translating and moving code is still using doubles because the cursors can have fractional pixels and thus the code is plumbed that way. But that could also probably be changed easily by doing the integer
conversions earlier and plumbing with int.

Make all the container dimensions integers

---

sway/desktop/xwayland.c

In case xcb-iccm is not installed on the system, size_hints will be
null. Handle this as if the get_constraints functions was not
implemented and return the defaults.
Fixes #4870

xwayland: handle size_hints == NULL

---

sway/sway-ipc.7.scd

A few items in the response for the get_tree ipc call were missing from
the documentation. This adds some documentation for them.

Add missing items to documentation for GET_TREE response in ipc.

---

sway/desktop/render.c

Fixes #4860 
This adds a check to make it so the indicator is only rendered on views
with a parent, which floating views do not. Since floating views do not
have a parent, the workspace layout was being incorrectly used to
determine whether to show the split indicator previously. This has no
impact on floating containers and a view within a floating container
will still have indicators rendered appropriately.

render: do not render indicator on floating views

---

include/sway/input/cursor.h
sway/input/cursor.c

Fixes #4880
This adds a listener for the destroy event of the cursor image surface.
This prevents a use-after-free when the last visible image surface is
freed, there has not been a new cursor set, and the cursor is reshown.

input/cursor: handle image surface destroy

---

include/sway/tree/root.h
sway/tree/root.c
sway/tree/view.c

Related #4892 (fixes first bullet)
If a view is mapped to a workspace using an assign, the pid should still
be removed from the pid mapping list. This prevents child processes from
matching against it and mapping a view to a likely undesired workspace.

view: remove workspace pid mapping for assigns

---

contrib/inactive-windows-transparency.py

Currently the transparency passed in on the command line is not being used in the `on_window_focus` event. This is unexpected since upon start-up, all the windows will be set to the correct transparency, but then switching between windows will set it to the default of 0.8.
It can be tested by running the script with `-o 0.1` to view the incorrect behavior, apply the patch, and then run the same test again to see the now correct behavior.

(contrib/inactive-windows-transparency.py): Use transparency arg in the window focus event

---

sway/sway-output.5.scd

Integral scaling doesn't make any sense. If this is actually how the downscaling works, ignore, but I have a feeling it is simply integer scaling.

integer scaling, not integral
