swaywm/sway

sway/commands.c
sway/movement.c
sway/movement.h

fixed changing focus to parent by moving it into move_focus().
anyway, i need experience in working on actual projects so ill try to do more if i can.

fixed focus_parent, moved into move_focus() function

---

sway/commands.c

corrected return value for commands.

return 0 on success.

---

sway/commands.c
sway/commands.h
sway/config.c
sway/layout.c
sway/layout.h
sway/list.c
sway/list.h
sway/workspace.c
sway/workspace.h

destroys empty workspaces. 
`() -> (void)`, as () takes any number of arguments when it should take none.
`int -> bool` for `handle_command` return type.
put `free_swayc()` into header for `destroy_workspace` to use
temporary fix to `workspace_next_name()` as it returned an unfreeable name.
https://github.com/SirCmpwn/sway/issues/11

destroys empty workspace + minor fixes

---

sway/handlers.c

this could probably be a lot better, but for now allows for multikey bindings. 
something like `mod+q+a` and `mod+q` still cant coexist.
commands are now resent when keys are held down, both single and multikeys.
a possible suggestion. have the `cmd_*()` return a bitflag instead of a simple bool.
with one bit being whether to resend command while key is held down.
with a  bit of button mashing, i can get it to skip some KEY_RELEASE events, so they dont get removed, until they get pressed again.
shouldnt be much of a problem, it only happens when you release 8~ keys at the same time.

Multikey handling

---

sway/list.c

also put list resizing into a static function.

list_insert now works as it should

---

sway/commands.c
sway/handlers.c
sway/handlers.h
sway/log.c
sway/main.c
sway/movement.c
sway/movement.h

moved `struct wlc_interface` into `handler.c` accessable via `extern` in `handler.h`
basic forking safety checks, and reduce code duplication.
added signal handler to cleanup dead processes.
added error handling function for checking argument count.
fixed `cmd_focus` movement function return values.
added `FD_CLOEXEC` flag to stdout|in|err so programs called with exec dont write stuff to logs
also sorry for the mess of adding a bunch of different stuff.

moving things around + statics + forking + exec cleanup + fixed cmd_focus return + keep exec programs out of logs

---

sway/commands.c

splitting a empty workspace would put it in a container which we dont want,
now changes layout of workspace.
splitting would do this `(Root (Output (container (... (workspace (...)))))`
hope this merges with the other pr, if it doesnt ill just wait and re add it.

split workspace bug

---

sway/commands.c
sway/config.c
sway/config.h
sway/handlers.c
sway/main.c
sway/workspace.c

Workspace names are now generated by scanning for bindsyms which execute "workspace [workspace name]", with a fallback option to use the number of currently active workspaces + 1.
In addition, a command queue has been implemented to allow for the configuration file to be loaded prior to initializing wlc. Upon initialization, all queued commands will be executed.
Additionally, exec and exec_always have been been modified to execute even if the sway config fails to properly load.

 Added in proper workspace name generation and command queue

---

sway/commands.c
sway/container.c
sway/container.h
sway/handlers.c
sway/handlers.h
sway/layout.c
sway/layout.h
sway/movement.c
sway/workspace.c
sway/workspace.h

rewrote and moved a bunch of functions into `container.[ch]`
`new_output` `new_workspace` `new_container` `new_view`
`destroy_output` ....
layouts.
the focus/arrange functions are removed from the old versions of these, 
and are now handled by the wlc handler functions.
the `_do_split` command was nicely cleaned up as a result of changing `new_container`.
creating new views was fixed up, its added as the sibling of current focus, or child of workspace.
removed debug

rewrote and grouped swayc related functions together.

---

sway/layout.c

Some lines which were based on absolute monitor positions(which wlc does not do right now) were commented out, and should be reviewed if wlc changes how it does positioning.

Fixed reloading and arrange_windows

---

sway/handlers.c

very small update.
as i used weston-terminal to test, the gaps were bothering me, and i thought of this.
when implementing floating windows later this should be unset for them.

set maximize flag for handled views

---

sway/container.c
sway/handlers.c
sway/layout.c
sway/log.h
sway/stringop.c
sway/workspace.c

using `get/set_userdata` to store swayc_t * container for handle.
fixed leaking container names.
`get_focused` is now iterative insteda of recursive
added format attributes to logs, 
reduced code duplication in `unescape_strings` and can more easily add fancy escape codes.
in `split_string` strlen is now only called once instead of all over the place.

get/set_userdata stores swayc_t *, fixed memory leak, minor changes.

---

sway/commands.c

On exit, all views are now closed by wlc.

Added in kill command and better exit handling.

---

sway/commands.c
sway/container.c
sway/stringop.c

split vh was passing unaltered arugments into _do_split which wanted no arguments.
frees container names now.
unescape handles a few more things `\'` `\"` `\xnn` `\\`

fixed split [vh], small memory leak, unescape_strings handle \xnn

---

sway/container.c
sway/handlers.c

unmanaged views handled better depending on type.
`OVERRIDE_REDIRECT` takes focus (for example dmenu) but only if `UNMANAGED` bit is unset (firefox typing popup is both)
might need to look more into the other combinations and how to deal with them.

unmanaged views handled better

---

sway/container.c
sway/handlers.c

would try to duplicate windows with no name, and crash it. (context menus and whatnot)
theres probably a lot more to fix and change, ill look through it some more later.
but for now, a quick fix.

fixed when views dont have names.

---

sway/handlers.c

keyboard input not accepted when view with override_redirect is created,
when destroyed keyboard input is again accepted.
also `focus_view(focus_pointer());` is pointless as `focus_pointer` already sets the focus,
and returns what the focus has been set too.

fixed handling of views with override_redirect (dmenu)

---

sway.1.txt

Asciidoc uses tildes to subscript and carets to superscript text.
The first tilde can be escaped to fix this, but looks weird because
the second tilde may not be escaped.
It doesn't seem like subscripting will be used in the man page so it
makes sense to disable it altogether.

disable tilde subscripting to fix manpage

---

sway/commands.c
sway/container.c
sway/focus.c
sway/handlers.c
sway/layout.c
sway/workspace.c

fullscreen behaviour is restored.
wont change focus randomly, keeps view set to fullscreen when switching workspaces and back.
floating windows behave properly with fullscreen now.
also changed layout_log, its neater now.

restored fullscreen/focus behavior

---

sway/handlers.c

The change to `container_under_pointer` reverses the order in which the floating list is traversed so that focus order is preserved. The change to `handle_pointer_button` makes it so that if a user clicks on a floating window, it's brought above all other floating windows.

Added in proper focus handling for floating containers.

---

CMakeLists.txt
include/log.h
sway/log.c

sway_assert returns false on a failed assertion in release mode and raises SIGABRT in debug mode
printing a backtrace in debug mode is unnecessary, expecting it to run in a debugger anyway.
also removed the static build type config from CMakeLists.txt because it prevents building in release mode.

added sway_assert function

---

sway/handlers.c
sway/layout.c

Resizing now works properly. The only remaining(serious) thing to fix with floating windows is that mod key detection isn't actually being done, and is always considered to be on.

Added in proper floating window resizing

---

sway/config.c

No more segfaults if either $XDG_CONFIG_DIR or $HOME aren't set.

Fixed config loading

---

sway/commands.c
sway/handlers.c

This adds in resize locks so that resizing functions more similarly to i3. Currently, if you shrink a window and move past the midway point, the window will begin to grow in the opposite direction. This is not how i3 works, so I've added in locks which prevent windows from having their opposite edge from being resized once one of the edges is changed. I've also established minimum sane height/width so to make sure that windows don't get too small when being resized.

Added in resize locking

---

sway/config.c

This extra period stopped sway from loading the user config file at ~/.config/sway/config. Instead the default file at /etc/sway/config was being loaded.

Fixed config path

---

sway.5.txt
sway/commands.c
sway/handlers.c

added floating mode_toggle. #85
also added debugging for key_press due to the wlc bug of flipping modifiers around.

floating mode_toggle

---

sway/handlers.c
sway/log.c
sway/readline.c

Most of the issues in #58 seem to not be present anymore; at least my version of cppcheck (1.69) doesn't find any more (with `--enable=all --inconclusive`), except an issue with the format specifier for wlc_handle being for signed numbers and some unused functions.
For the former I've opened a ticket for wlc, Cloudef/wlc#53, and the latter is not a concern I think.
The memory leak commit is an interesting one though; read_line.c seems to be the only fire where `malloc` and `realloc` is checked for failure. Maybe the checks should be removed and these functions are expected to never fail, or checks should be inserted everywhere else.

A couple of cppcheck issues

---

sway/container.c
sway/layout.c

Previously, when only using inner gaps, the gap between a window at the
edge of the output was only half the size of the gaps between views.
Additionally, the gaps between the actual windows was twice as wide as
it was on i3-gaps.

Change gap behaviour to more closely match i3-gaps

---

include/container.h
sway/commands.c
sway/container.c
sway/layout.c
sway/log.c

as it says, it drops the weight method for calculating size,
and instead uses previous width/height.

setup for resizable windows, drop weight

---

include/container.h
sway/commands.c
sway/container.c
sway/handlers.c
sway/layout.c
sway/workspace.c

replaced all instance of
```
while (container->type != C_WORKSPACE) {
container = container->parent;
}
```
with
`container = swayc_parent_by_type(container, C_WORKSPACE);`
theres also a `swayc_parent_by_layout` too.
also added sway_asserts to destroy/create functions.
ill try to find more things to clean up

find_parent_by_type

---

include/stringop.h
sway/ipc.c
sway/stringop.c

No escaping on container names is done yet, as well as some values are
hardcoded because they don't exist yet.
Test with:
`i3-msg -t get_outputs`
`i3-msg -t get_workspaces`
From outside sway first `export I3SOCK=/tmp/sway-ipc.sock`

added IPC messages get_workspaces and get_outputs

---

include/input_state.h
sway/handlers.c
sway/input_state.c

Resize now locks properly if you over-resize a container and make it smaller than the mininimum width/height. Some unnecessary debugging was also removed.

Added in proper resize locking

---

include/container.h
include/layout.h
include/workspace.h
sway/commands.c
sway/container.c
sway/focus.c
sway/handlers.c
sway/layout.c
sway/log.c
sway/workspace.c

first the few bugfixes, the same ones i fixed in my view_ordering pr.
splithv on floating windows, set_focused behavior for fullscreen windows.
next change is `active_workspace` -> `swayc_active_workspace()` function and other related functions such as `swayc_active_workspace_for(view)` `swayc_active_output()`
since active workspace should always be `root->focused->focused` its better to use that instead of updating active_workspace all the time.
also some name changes. `swayc_by_test()` replaces `find_container`, `sway_by_handle()` replaces `get_swayc_for_handle`
replaced the fullscreen checking with `swayc_is_fullscreen(view)` 
as for the window resizing with rightclick, i made it check for floating_modifier, and behave the same for resizing floating windows (no rightclick when …

bugfixes, renames, and other things.

---

include/log.h
sway/log.c

I've added in backtrace printing as referenced in #66. SIGABRT is handled in addition to SIGEGV because that can also be called when sway_assert fails.

Added in backtrace printing

---

include/container.h
include/layout.h
include/util.h
include/workspace.h
sway.5.txt
sway/commands.c
sway/container.c
sway/focus.c
sway/handlers.c
sway/layout.c
sway/util.c
sway/workspace.c

- Fixes to the visibility of views
- `move container to workspace <name>`
- rewrote `workspace{,_output}_{prev,next}` and patched that into `workspace_by_name` so it works with the move command

Implemented "move container to workspace"

---

sway/handlers.c

Addresses issue #126:
The fix doesn't exactly replicate I3wm's behavior, mostly because I3wm's behavior is counter intuitive.

Focus floating window, if any, when the last tiling window has been closed

---

include/focus.h
sway/container.c
sway/focus.c
sway/handlers.c
sway/layout.c

put the floating focus thing in `remove_child`.
also fixed a segfault caused by destroying views when no outputs exist.

fixed segfault on exit + a little fixup of that floatfocus pr

---

include/container.h
include/log.h
sway/commands.c
sway/container.c
sway/layout.c
sway/log.c
sway/main.c

`move container to workspace %s` has more proper behavior.
changed `sway_assert` to a macro that calls `_sway_assert` with `__PRETTY_FUNCTION__:` prepended.

move_container_to fixup

---

include/container.h
sway/container.c
sway/focus.c
sway/layout.c

after testing out tty switching, i noticed that it creates duplicate outputs.
also unlike the log in #141 it doesnt destroy outputs when switching, i dont know why though.
though it does attempt to recreate them when switching back.
welp, went and redid the `update_visibility`,
also added some helper functions and cleaned up `update_focus`

use previous output containers

---

include/layout.h
sway/commands.c
sway/layout.c

The basic scratchpad has been implemented. Special types of `scratchpad show` commands using syntax like `[title="^Sup ::"] scratchpad show` aren't implemented yet.

Added in Scratchpad

---

sway/commands.c
sway/workspace.c

cleaned up leaky prev_workspace_name

---

.ci/build.sh
.travis.yml

As discussed in #20 this adds support for travis-ci builds based on [arch-travis](https://github.com/mikkeloscar/arch-travis).
I have added `make install` for wlc as suggested by @Luminarys

Add CI support

---

include/container.h
sway/commands.c
sway/container.c
sway/layout.c

if in the future, we add a command for setting gaps of a window individually, this will help.
default value of `swayc_t.gap` is -1, in this case it gets the value to use from the `config->gaps_xxx`.
when `swayc_t.gap` is nonnegative it will use that instead.
also some minor changes.

default gap value.

---

README.md

Make the travis badge a link for easy access to the travis build page.

Add link to travis-ci badge

---

include/container.h
sway.5.txt
sway/commands.c
sway/config.c
sway/container.c
sway/log.c

resize gaps for workspace, views via the following commands.
`gaps inner|outer all|current|workspace set|plus|minus nnn`
one difference in the `inner current|workspace`
airbladers `inner current` changes all view gaps for a workspace, while this sets it for the focused view.
and newly added `inner workspace` changes all view gaps for a workspace.
i could change `inner workspace` to `inner view` so the `inner current` is the same as airbladers, but it was a bit neater this way.

resize gap

---

include/commands.h
include/config.h
include/stringop.h
sway/commands.c
sway/config.c
sway/handlers.c
sway/ipc.c
sway/stringop.c

config modes are done.
```
mode "mode_name" {
whatever bindings you want go here
bindsym mode default # default is the default mode name
}
```
lots of changes here and there.
commands no longer have `config` as an argument, no more temp_config stuff so its not needed.
cleanedup the `split_directive`, renamed to `split_args`, along with a `free_args`
and a few other functions here and there cleanedup.

config modes

---

include/commands.h
include/config.h
sway/commands.c
sway/config.c
sway/handlers.c
sway/stringop.c
sway/workspace.c

commands now return a status instead of boolean.
it now returns if it should defer the command, which only happens when !config->active
it now checks if its calling the command from a config or keybind and returns failure/success accordingly
ans workspace output behavior is fixed.
it wont move any already created workspaces but it will search for the output to use when creating workspace.

cmd status + workspace ws output op

---

include/commands.h
include/config.h
include/container.h
include/stringop.h
include/workspace.h
sway/commands.c
sway/config.c
sway/container.c
sway/handlers.c
sway/ipc.c
sway/stringop.c
sway/workspace.c

new_workspace now takes NULL pointers, which tells it to figure out the name/output to use itself.
this cleaned up a bit of code here and there.
tests and mapping functions are redone a bit,
there are regex tests too which can be used.
added `char *criteria` too all commands, though i havent done anything with it yet.
a dummy version of for_window takes a regex argument and prints all views with the matching title.
anyway lots of changes here and there. hope i didnt break much,

new_workspace null behavior + testmap functions + regex

---

.travis.yml

wlc now depends on `xcb-util-image` Cloudef@eecbeccf96dfea1f05c1ad89bb08f6cfd68be73d.

Add missing wlc dependency

---

sway/main.c

this seems to work.
it seemed the sigchld handler was only called once for the first child process that it closed.

#187 cleanup zombies properly

---

README.md

It seems to be good idea to add location for openSUSE packages as well.

tell where openSUSE packages lives as well

---

sway/ipc.c

If multiple users try to use sway at the same time the identically named ipc socket will prevent anyone other than the first user to actually run sway.
This patch fixes that by adding the user id to the socket path.
Note: I have no idea what I'm actually doing, please review carefully before pulling and please excuse any obvious errors I might have made ...
(Also, when using logind the path should actually be something like `/var/run/user/<id>/sway-ipc.socket`, but this patch is anyway an improvement.)

Multi user

---

sway/commands.c

When using an i3 config verbatim in sway this switch to exec or
exec_always might appear.
Before this patch the switch would be passed to /bin/sh, causing
an error, and the command would not be run.

Ignore exec switch "--no-startup-id".

---

sway/commands.c

Before this patch sway would proceed into find_handler which would cause
a crash trying to parse a NULL string.
This could be triggered via e.g. `i3-msg -s $(sway --get-socketpath)`.

commands: Gracefully handle empty commands.

---

include/config.h
sway/commands.c
sway/config.c
sway/container.c

config: Apply output config also during config reload.
My biggest patch so far, this code allows sway to apply changes in outputs config after config reload.
The position data isn't used (so far), but the resolution of the different outputs can now be changed on the fly by simply reloading the config. Everything seems to be working nicely. Please review.

Configure outputs during reload 

---

include/commands.h
sway/commands.c
sway/config.c
sway/handlers.c
sway/ipc.c

(First off, this got bigger than I anticipated, sorry about that, but I am pretty happy with the end results.)
In i3 the ipc reply will contain a human readable error message, and
this patch replicates that behaviour.
However, that error message is also useful for logging, which this
patch takes advantage of.
E.g. instead of logging errors directly in commands.c/checkargs, it is
fed back to the caller which eventually ends up logging everything with
maximum context available (config.c/read_config).
So instead of logging e.g. "Error on line 'exit'" it will now log:
"Error on line 'exit': Can't execute from config."
PS: I've tested it and it works pretty nicely, both via i3-msg and in the logs. Please review, comments are welcomed.
PPS: There's something about string literals I'm uncertain …

Replace cmd_status with cmd_results struct

---

include/focus.h
include/workspace.h
sway/focus.c
sway/handlers.c
sway/workspace.c

1) If you're using a scrollbar at the edge of the screen you don't want to accidentally switch workspace (as that cancels the scrolling).
2) When using e.g. firefox, if you right click to open a menu and then move the cursor off the screen it will jump to the other edge of the screen because the menu actually blocked the switch from happening, so don't move the mouse pointer in those cases.

Seamless mouse adjustments

---

include/log.h
sway.5.txt
sway/commands.c
sway/log.c

Replicates i3 option. Verbosity level given as command line argument
becomes default log level, and using 'debuglog toggle' switches back and
forth between default and debug (or L_ERROR and debug if default is also
L_DEBUG).

commands: Learn 'debuglog'.

---

sway/handlers.c

The old `workspace_switch` accepted that this was incorrect, but the latest pull exposed it as the bug that it is (making sway crash).

seamless_mouse: Pass workspace to workspace_switch, not output.

---

sway.5.txt
sway/commands.c
sway/layout.c

Replicates i3 functionality. This is the first part of pull request #205 , and it works properly.
(+ The fix for moving floating windows to other workspaces.)

commands: Learn 'focus output <direction|name>'

---

include/commands.h
include/container.h
include/handlers.h
include/input_state.h
sway.5.txt
sway/commands.c
sway/container.c
sway/focus.c
sway/handlers.c
sway/input_state.c

This patch series contains two patches with refactoring and a third with a new `mouse_warping` command (same as in i3). The refactoring is done in order to reuse code in the last patch.
`mouse_warping` can be triggered in multiple ways:
A) via `workspace <name>` which changes output
B) via `focus <direction>` which changes output
C) via `focus output <name>` which (obviously) changes output

Learn mouse_warping

---

sway/focus.c
sway/workspace.c

from the comment here 6cd106d23c73c1f5c5f87d4c024400cfd5edc93f
>This part is problematic, as active_ws is not allocated:
>
>==23819==    at 0x4C2A7FB: free (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
>==23819==    by 0x412912: free_swayc (container.c:53)
>==23819==    by 0x413645: destroy_workspace (container.c:319)
>==23819==    by 0x409DE1: update_focus (focus.c:37)
>==23819==    by 0x40A001: set_focused_container (focus.c:108)
>
>it depends only on timing if the data will be there or not.
this should fix it.
`ipc_event_workspace` should get called before destroying empty workspaces and will also be called in every situation where workspace switches.
duno if that last part is desirable or not though, but if not then just move `ipc_event_workspace` before …

put ipc_event_workspace in update_focus

---

include/layout.h
sway.5.txt
sway/commands.c
sway/layout.c

Three new functionalities related to outputs (I have a quad monitor setup so that stuff is of interest to me). All three are replicas of i3 functionality. 
Known issues:
1) Sometimes when moving a workspace, the windows on that workspace go black until one of those windows receive focus again. I haven't looked properly into why that is yet.
2) If you switch focus with a normal `focus <direction>` command, you might switch output also. However, that code doesn't take output positions into account, so it ends up switching to an "arbitrary" output. That's confusing and should be fixed.

Learn focus / move container to adjacent output

---

sway.5.txt
sway/commands.c

Multiple fixes:
1) Accept zero value (fixes #207).
2) Always set default gaps config when command is given (not just once like before).
3) Re-arrange windows after setting new gaps value (so that effect is immediate).

Clean up gaps command

---

include/config.h
sway.5.txt
sway/commands.c
sway/config.c
sway/layout.c

When yes, the old behaviour of adding half the inner gap around each
view is used.
When no, don't add any gap when an edge of the view aligns with the
workspace. The result is inner gap only between views, not against the
workspace edge.
The algorithm is not perfect because it means the extra space is
distributed amongst edge-aligned views only, but it's simple, looks good
and it works.
(The name was kind of hard to make up, "gaps edge_gaps on" looks kind of clumsy, but it's descriptive at least...)

Learn "gaps edge_gaps <on|off|toggle>".

---

sway/focus.c

Build is throwing a warning because the header file is missing. So let it be included :)

Include header declaring ipc_event_workpace(2)

---

.travis.yml

Add missing `pango` and `cario` packages to travis build.

Add new swaybg dependencies

---

sway/ipc.c
sway/main.c

After adding pid to the socket path the `--get-socketpath` command broke
because it doesn't know the pid of the running instance. Fix this by
setting and querying `SWAYSOCK`.
Also ignore `SWAYSOCK` upon normal startup if a socket exists at that
location (ie. from another sway instance), and don't overwrite `I3SOCK`
if it exists either.

ipc: Store socketname in SWAYSOCK. Fixes `--get-socketpath`.

---

swaybg/main.c

In case that there's no Wayland compositor running, swaybg will crash because client_setup() will return NULL.

Check the client_setup() return value

---

include/config.h
sway/commands.c
sway/config.c

When issuing multiple output commands, always replace existing output config.

cmd_output: Replace existing config if called multiple times.

---

common/list.c
include/config.h
include/list.h
include/stringop.h
sway/commands.c
sway/config.c
sway/stringop.c

When issuing multiple `workspace name output somewhere` commands with the same workspace name (e.g. via ipc or config reload) the old config remains stored, leading to it being used instead of the new config. The third patch fixes that.
In order to implement this I've added two helper functions: `lenient_strcmp` which takes `NULL` pointers into account when comparing, and `list_seq_find` which allows one to use a compare function to sequentially search for and return the index of an item.

Fix `workspace_output` duplicates

---

include/config.h
sway/commands.c
sway/config.c

First patch: Unrelated comment piggybacking the pull request.
Second patch: Detect/handle duplicates in `cmd_bindsym`. Duplicates are found and freed.
Also replace `bindsym_sort` with function `sway_binding_cmp` that takes
all data into account when comparing (although having the list sorted is never actually taken advantage of as far as I can tell...)

Handle bindsym duplicates

---

common/list.c
sway/commands.c
sway/config.c

list_sort has changed so that comparison functions passed to it receive the pointer to the object it cares about, instead of a pointer to that pointer.
the comparison function in #247 `list_sort(mode->bindings, sway_binding_cmp);` would use the wrong pointer, and could cause all sorts of fun.

fix list sorting

---

include/container.h
sway/container.c

Store `class` and `app_id` attributes in view containers (fetched from wlc).
(Not used at the moment, but are needed when using criteria strings to filter which views to execute commands on.)

Extra view metadata

---

sway/commands.c
sway/stringop.c

Patch 1: Treat criteria strings as a single argument.
Patch 2: Don't execute commands with a prefixed criteria string (notify the user). (Before this the command would just fail to parse.)

Initial support for criteria strings

---

sway/config.c

Compare modifiers as well as keys when number of modifiers+keys are the
same (so that e.g. mod1+x != mod4+x).
(This happens after comparing length, so shouldn't mess anything up...)

sway_binding_cmp_keys: Differentiate between modifier keys.

---

sway/layout.c

4 patches that takes floating into account when using `index_child` in layout code.
First patch should fix #241 .
I haven't thoroughly tested this, but it's pretty straight forward code (famous last words?).

Handle floating views in layout code

---

sway/extensions.c

This fixes a compiler warning:
../sway/extensions.c: In function ‘set_background’:
../sway/extensions.c:16:37: warning: implicit declaration of function ‘malloc’ [-Wimplicit-function-declaration]
struct background_config *config = malloc(sizeof(struct background_config));
^
../sway/extensions.c:16:37: warning: incompatible implicit declaration of built-in function ‘malloc’
../sway/extensions.c:16:37: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’

extensions: add missing include

---

CMake/Wayland.cmake

When using the ninja generator:
$ cmake -G Ninja <dir>
$ ninja -C <dir>
This commit fixes the warning:
ninja: warning: multiple rules generate bin/wayland-desktop-shell-protocol.c.  builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]

cmake: fix ninja build

---

include/config.h
include/criteria.h
sway.5.txt
sway/commands.c
sway/config.c
sway/criteria.c
sway/handlers.c

A criteria is a string in the form of `[class="regex.*" title="str"]`.
It is stored in a struct with a list of *tokens* which is a
attribute/value pair (stored as a `crit_token` struct). Most tokens will
also have a precompiled regex stored that will be used during criteria
matching.
for_window command: When a new view is created its metadata is tested
against all stored criteria, and if a match is found the associated
command list is executed.
Unfortunately some metadata is not available in sway at the moment
(specifically `instance`, `window_role` and `urgent`). Any criteria
string that tries to match an unsupported attribute will fail.
(Note that while the criteria code can be used to parse any criteria
string it is currently only used by the `for_window` command.)
So this patch became …

criteria: Add. Learn for_window command.

---

sway/config.c

This makes escaping the arguments obsolete.
Also avoid dynamic memory allocation for the output id. It only supported ids up
to 99. Now we support up to 999, and take 4 bytes off the stack instead.

Call swaybg without invoking a shell

---

sway.5.txt
sway/commands.c

This is especially relevant in combination with `for_window`, e.g.:
`for_window [title="Terminal"] floating enable`.

cmd_floating: Support `enable` and `disable` commands too.

---

include/container.h
sway.5.txt
sway/commands.c
sway/container.c
sway/workspace.c

A floating window that's sticky will move to the new active workspace
whenever the workspace on the same output changes.
(Another one bites the dust: #2 ) Please review, comments are welcomed.

workspace: Learn sticky.

---

sway/main.c

First of all because it's not needed that early, and second of all
because there's a bug where calling `sway --get-socketpath` via `popen`
causes the child sway process to spin/hang instead of returning EOF.
(Specifically `(unset SWAYSOCK; swaymsg)` hangs.) This patch fixes that.
(Also note that this patch moves the "detailed review" comment, so I
guess this patch requires extra detailed review?)

sway/main: Move wlc init to after args are handled.

---

sway/commands.c

This handles some cases where sway will crash if an output command is
invalid/missing an argument.

Add warnings about invalid output commands

---

sway/main.c

If `wlc_init` fails the error message will never be logged or printed
anywhere.
(Even more code running as root ;-)

main: Setup logging before wlc_init.

---

sway/commands.c

When turning a float to a non-float, `get_focused_container` might
return another floating view, causing the active view to be inserted
into the floating list on its workspace instead of the normal child list
which it should. (Since it has `is_floating` as false the resulting
discrepency triggered other bad behaviour eventually leading sway to
crash.)
This patch fixes that by simply checking floating status before making
it a sibling.
This should fix the extra issue reported at #241 .

cmd_floating: Don't add non-float as sibling to float.

---

CMakeLists.txt
README.md
sway.1.txt
sway/config.c

CMake takes a `DDUMP_CONFIG_DIR` flag which is the directory where the
standard configuration file `config` is copied at installation.

Can customize fallback config directory

---

CMakeLists.txt
sway/config.c

- Flag was ignored. Now it's taken into account.
- Missing trailing slashes in path now behaves properly.
Sorry for the last PR. This one has been tested properly. It should build nicely.
Plus, the type "PATH" in CMake automatically removes trailing slashes.

FALLBACK_CONFIG_DIR did not work. Fixed.

---

sway/handlers.c

Struct was renamed in wlc [1], this just uses the new name.
[1] https://github.com/Cloudef/wlc/blob/10642a98371fc8043a6d260ef08336e22002241f/include/wlc/geometry.h#L24

Use wlc_point instead of deprecated wlc_origin

---

config
include/config.h
sway/commands.c
sway/config.c
sway/input_state.c
sway/sway.5.txt

This makes it possible to define what mouse button key (left|right) to use for dragging/resizing.
Right now you define the following commands in the config or leave them out if you just want the default behavior.
```
dragging_key right
resizing_key left
```
default is the reverse of the above.
Do you like this version or should I call the config commands something different?
As an alternative you could have a single command like this, where you just define if it should be:
**normal** (left = dragging, right = resizing) or **inverse** (left = resizing, right = dragging).
```
dragging_resizing_mode inverse
```
or it could be an extension to `floating_modifier`
```
floating_modifier $mod inverse
```
What do you think?
(I will update manpage and the default config when a command definition …

[RFC] Make mouse key used for drag/resize configurable

---

sway/layout.c

The x and y position is calculated based on the position of the bar, we
don't want to reset these values when we need them.

Don't reset x,y position before use.

---

sway/focus.c
sway/ipc-server.c

Empty workspaces are deleted on focus-swap, made set_focused_container aware of that.

Fix dangling pointer on focus swap/describe WS

---

include/config.h
sway/commands.c
sway/config.c

This implements parsing of `bar { }` blocks in the config file. I have also implemented parsing of `workspace_buttons <yes|no>` and `tray_padding <px> [px]` as an example for implementing the other sub-commands.
I have just assumed that the `bar-id` can be the index of the bar in `config->bars->items`. Is this alright, or should we generate a custom id, like in i3 [1]?
This will affect the implementation of #309. @gpyh can you please check this out, so we are sure that we are on the same page? Hopefully I haven't created too much new work for you :)
[1] http://i3wm.org/docs/ipc.html#_bar_config_reply (Example of configured bars:)

Implement bar { } config parsing

---

sway/commands.c

Some more bar config options implemented.
* `positon <top|bottom|left|right>`
* `strip_workspace_numbers <yes|no>`
* `tray_output` (message about it not being supported)

Bar confing subcommands

---

sway/main.c

Untested on an actual catalyst install but this is the right kernel module to detect.

Detect proprietary AMD drivers too

---

include/config.h
sway/commands.c
sway/config.c

Get rid of `config->bar` and define the default bar config options when
a bar is initialized.

Move default bar config to bar creation.

---

sway/commands.c

That's mostly taken from `cmd_bindsym`.
I understand the code but you might wanna double check this.

Added bar_cmd_modifier

---

include/config.h
sway/commands.c
sway/config.c

Note the list of outputs will be empty if no output commands are defined in the bar config. Thus empty list should be treated the same as `["*"]`.

Implement bar option: output <output>

---

include/config.h
sway/commands.c
sway/config.c
sway/ipc-server.c

I think this concludes the implementation of the bar config parser.

Implement bar option: separator_symbol

---

swaybar/main.c

This is really nitpicking, hope you don't mind.

Correct typo seperator -> separator

---

swaybar/main.c

This fixes a segfault which would occur if you try to run swaybar without any arguments.

swaybar: Check that registry is set before teardown

---

swaygrab/CMakeLists.txt
swaygrab/main.c

This makes `swaygrab` use the currently focused output as source if no
other output is defined with the `-o, --output <output>` option.
Note this changes the way swaygrab is called:
```
Usage: swaygrab [options] [file]
-h, --help             Show help message and quit.
-c, --capture          Capture video.
-o, --output <output>  Output source.
-v, --version          Show the version number and quit.
-s, --socket <socket>  Use the specified socket.
-R, --rate <rate>      Specify framerate (default: 30)
-r, --raw              Write raw rgba data to stdout.
```
If you don't like this change, please let me know.
I will update the man page when/if this is accepted.

swaygrab: make focused output default

---

include/layout.h
include/workspace.h
sway/commands.c
sway/container.c
sway/workspace.c

These two commits improve handling of numbered workspaces.
The first commit allows the selection of a workspace by its number if it has a number and a name.
The second commit sorts numbered workspaces in ascending order at the beginning of the workspace list.

Workspace numbers

---

swaybar/main.c

Turns out that fedora killed off stropts.h some time ago [1] and
removing it seems to work just fine. (Tested on Fedora 23)
[1] https://bugzilla.redhat.com/show_bug.cgi?id=439403
Same as issue #162 .

swaybar: Remove stropts.h, fixes build for fedora.

---

sway/focus.c

If there's only one workspace on an output and it's moved to a different
output then active workspace will be NULL.

focus: Fix moving last workspace.

---

swaybar/main.c

`json_object_object_get_ex` does not require `json_object_put` according to
docs, this should fix the random crashes.
Ref: https://json-c.github.io/json-c/json-c-0.10/doc/html/json__object_8h.html#accc34b38e15e46357d64a0beed3d0150

swaybar: ipc_update_ws: Fix memory corruption.

---

include/config.h
include/container.h
sway/commands.c
sway/config.c
sway/container.c

This works by tracking the pids of the child processes in the related
output container and terminating the processes and spawning new ones on
a config reload.
Should solve: #347

Reload swaybar/swaybg on config reload.

---

include/config.h
sway/commands.c
sway/config.c

This adds config support for a custom `swaybar_command` in a `bar { }` block as mentioned here: https://github.com/SirCmpwn/sway/issues/343#issuecomment-165625365.
I will add the rest when #358 is merged as it builds on top of that.

Add bar option: swaybar_command <command>

---

sway/layout.c

First patch fixes some of the debugging output and adds some debug output line for panels.
Second patch makes sure width and height are properly set which is actually used later on (after the switch statement). (And also fixes x/y for workspace for left/right panels.)
This should properly restore the behaviour of `arrange_windows` to what it used to be.
Ref #358 , @mikkeloscar please test/confirm...

Fix arrange windows

---

sway/config.c

The missing part that makes you run a custom `swaybar`.
This is very useful if you are trying to fix a bug in swaybar only to find out that you keep running the version installed globally which is an old version. (I may or may not have done this last night)..

Add support for running swaybar_command

---

README.md

Hi!
It seems pam dependency is missing from the readme file.
Also "cd .." is missing in "run these commands" section.

Update readme dependency list and build instructions

---

sway/config.c

bar_config.outputs is NULL if no output is explicitly defined in config
(ie. use for all outputs).
Should fix #363 .

config: free_bar: Check if outputs is NULL.

---

include/extensions.h
sway/extensions.c
sway/handlers.c
sway/layout.c

Panel position was a single property that applied to all swaybars. With this patch it is placed in `panel_config` instead so that each panel can have its own position.
In order to make this work the `wl_resource` used in the requests from the client needs to be stored and matched to the correct panel config.
Also, `set_panel_position` might be called before `set_panel` (for unknown reasons), so existing `panel_config` is used in `set_panel` if found.

Per panel config

---

swaybar/main.c

I added the font parsing (removing the `pango:` prefix) to swaybar, but it may make more sense to just strip `pango:` when the font is parsed in sway.

swaybar: Add font support

---

include/ipc-server.h
sway/commands.c
sway/ipc-server.c

This implements the `barconfig_update` event (missing part in #388).
Eventually we should also trigger a `barconfig_update` when reloading the config file, but I don't think it makes sense to implement this before `swaybar` has been refactored and supports the event.

Implement ipc_event_barconfig_update

---

sway/ipc-server.c

Only clients not subcriped to the workspace event should be skipped.

Don't skip all clients on ipc_workspace_event.

---

include/ipc-server.h
sway/focus.c
sway/ipc-server.c
sway/layout.c

This makes sure that the workspace IPC event is triggered when needed.
Fixes #382 while making sure that the IPC event is only triggered once.

Trigger ipc_event_workspace in all cases

---

common/list.c
include/list.h
swaybar/main.c

This commit series implements three things:
* Allow swaybar to understand the i3bar json protocol.
* Format output with specified colors and separators.
* Fall back to legacy single line text if the status_command doesn't ask for the json protocol.

swaybar: I3bar json protocol

---

swaybar/main.c

I am not sure if this is a correct issue/fix but on my system at least
after an i3bar protocol is detected this while loop never goes back
around meaning it doesnt process the status line anymore.

Stop swaybar from not rendering after the first go around

---

swaygrab/main.c

I think it's a good idea to do a `free()` in that loop otherwise my 4GB RAM fills up in like 20 seconds it's crazy.

swaygrab: Fix memory leak when recording videos

---

CMakeLists.txt

Silent bug introduced by f02cf75.
I forgot to commit this change so variables were not initialized. This did not raise any warning because CMake doesn't care.
It may have polluted the root directory. Check for /sway and /pam.d folders and delete them.

Bugfix: Added include(GNUInstallDirs)

---

.travis.yml

I have added clang support to [arch-travis](https://github.com/mikkeloscar/arch-travis), and this enables it for sway travis builds.
Note that building wlc with clang throws a lot of warnings, if this is a problem then we can either use `gcc` for `wlc` or silence the warnings (or fix them upstream).

Add clang build to travis

---

README.md

The package didn't make it in the official repositories yet (that will happen, when there's a release version). But I've implemented some kind of overlay (AUR) for Void Linux, so we can have it there, too :+1: 
https://wiki.voidlinux.eu/sway

Readme: add link to sway article in Void Linux wiki

---

swaybar/main.c

This should fix the random json related crashes in swaybar.
The crashes occured because the same socket was used for listening on
workspace events and requesting workspace info, resulting in a
unreliable message queue on the socket.
The solution is to use one socket for the events and one socket for
reliably requesting workspace/output info.
(Note: I also sneaked in a commit fixing random whitespaces in `swaybar/main.c`)

swaybar: Fix json related crash.

---

sway/layout.c

Triggers workspace init event when moving a floating window to a new
workspace.
This is a follow up on #391 which didn't handle floating windows.

Trigger workspace init event (floating)

---

sway/layout.c

This makes sure that the window being added to a container gets focus. For instance if you move a window from one workspace to another you want to keep focus on the window that is moved.

Focus new sibling added to container

---

swaybar/main.c

This extends the i3bar protocol implementation with the following
features from @Airblade/i3:
* background
* border
* border_top, border_bottom, border_left, border_right
A block will now be rendered like this:
```
(border_left + margin) + width + (margin + border_right) + sep
```
Where `border_left/border_right` and their related margin is only drawn
if the `border` is specified and the border has a width > 0 (default is
1).
`border_top` and `border_bottom` does not affect the height of the bar
(no margin is added), thus it will be drawn behind the text if it is too
big. The user should specify a bar height if more space between
top/bottom borders are required.
I'm sorry that the commit is so big, but I had to refactor some of the render code in order to make sense of it all. If you …

swaybar: Add support for Airblade i3bar extensions

---

sway/CMakeLists.txt
sway/handlers.c
sway/layout.c

If the width or height of a container can't be evenly distributed to its
children, then the layout algorithm still thought it got it right (due
to using decimals) which caused a gap of one or more pixels for some
window arrangements.
This is fixed (by the second patch) by first rounding off the width and height
(so that decimals are never introduced) and then adjusting the last
view in a container to fill the remaining pixels (which now is counted
correctly due to the decimals being removed).
Also, due to the way gaps are implemented, an odd sized gap can never be
aligned properly, so just adjust to closest even number.
Fixes #392 .
First patch is a "minor refactoring" of the layout algorithm. Third patch adjusts some debug output that was annoying me.

Fix layout calculations

---

include/container.h
sway/commands.c
sway/container.c
sway/main.c

This makes sway handle and gracefully shut down everything when
receiving a SIGTERM.
Fix #416

Handle SIGTERM sent to sway

---

swaybar/main.c

I accidentally left a random debug log in d72be6c0d59b02e21c056e7b41be784eceaa540a.

saybar: remove stray logline

---

swaybar/main.c

This makes sure the `:` isn't striped if you have a workspace named:
`:something`.

Only strip when starting with a num

---

common/ipc-client.c
include/ipc-client.h
include/ipc.h
sway/ipc-server.c
swaybar/main.c

This includes some changes/additions to the IPC server/client which makes it use custom IPC_EVENT_* types for events as required by the i3 IPC spec, and also includes the type in the response from `ipc_recv_response` such that the type can be checked at the client side.
(This is needed before I can implement the binding mode indicator)

Refactor IPC server/client

---

swaybar/main.c

Optionally turn on debugging in swaybar. I acidentally introduced
persistent logging in a previous commit

swaybar: fix logging

---

sway/input_state.c

This fixes a bug where the key at index 0 in the `key_state_array` would
be overwritten by the next pressed key. This broke any bindings
consisting of multiple non-mod keys like: `$mod+a+b`.

Fix overwriting current pressed keys.

---

sway/commands.c
sway/handlers.c

This fixes https://github.com/SirCmpwn/sway/issues/431 by returning
focus to the fullscreen view. Also it fixes the issue with the
fullscreen view pointer not being set which did my head in

Return focus to fullscreen view

---

sway/sway.1.txt

The i3wm config locations are visited _before_ using the fallback
configs. The man page was confusing - it talked about the fallback
configs first, but also said they are looked at "at last". By changing
the order of the sentences, this should be clearer.

Clearer order of locations searched for config file.

---

common/util.c
include/config.h
include/input_state.h
include/ipc-server.h
include/ipc.h
include/util.h
sway/commands.c
sway/config.c
sway/handlers.c
sway/input_state.c
sway/ipc-server.c

Detects when a bar modifier key is pressed/released and sends a modifier IPC event to any listeners (usually swaybars).
This way a swaybar can listen on the modifier event and hide/show the bar accordingly (not implemented yet).
The modifier event looks like this:
{
"change": "pressed", // or released
"modifier": "Mod4"
}

Send IPC modifier event on bar_modifier up/down

---

include/config.h
include/input_state.h
sway/commands.c
sway/handlers.c
sway/input_state.c

This is a "simple" version of --release (same as i3) that only supports
a binding that contain one normal key. e.g.:
bindsym --release $mod+x exec somthing-fun
I didn't bother implementing it for a combination like `$mod+x+z` since
it is a bit tricky to get right and also a bit weird to actually do on a
keyboard.

Implement bindsym --release

---

CMakeLists.txt
common/util.c
include/config.h
include/ipc-server.h
include/util.h
sway/config.c
sway/handlers.c
sway/ipc-server.c

This implements the IPC binding event for keyboard bindings.  It is
slightly different from the i3 implementation [1] since sway supports
more than one non-modifier key in a binding. Thus the json interface has
been changed from:
{
...
"symbol": "t",
...
}
to:
{
...
"symbols": [ "t" ],
...
}
(Also note that `input_code` is not implemented because it depends on `bindcode`)
[1] http://i3wm.org/docs/ipc.html#_binding_event

Implement IPC binding event (keyboard)

---

include/config.h
sway/commands.c
sway/config.c
sway/handlers.c
sway/input_state.c

If a bindsym and bincode maps to the same combination, the last one will
overwrite any previous mappings.

Add support for bincode command

---

sway/ipc-server.c

This adds the field `input_codes` to binding events.
Again, unlike i3, sway can handle multiple non-modifier keys, so `input_codes` is an array compared to the i3 version where it's a single value field, `input_code`.

Add bindcode to binding events.

---

sway/CMakeLists.txt
sway/config.c

CMAKE_INSTALL_FULL_SYSCONFIG is not actually passed to
the C preprocessor. I remember it working, so I must have
messed up somewhere last time I touched this.
This is fixed by manually passing its value to the C preprocessor
through the SYSCONFDIR definition

Fix issue #455

---

sway/container.c

This is a possible fix for #384.
To be honest I don't fully understand why this bug is happening, but I
have narrowed it down to the view stack in wlc and how sway orders views
in very specific situations (those described in #384).
Anyway this should fix the problem by eliminating the call to
`wlc_view_bring_to_front` which isn't really needed anyway since sending
all invisible views to the back is the same as bringing all visible
views to the front (rotating the view stack).
It would be nice if someone could test this patch for a bit and report back if any issues are found. Basically, if a view doesn't show up when it should, or does when it shouldn't then it's a bug caused by this.

Fix rendering of view when moving to new workspace

---

common/stringop.c
include/stringop.h
sway/commands.c

This adds quotes around multiword arguments before they are passed to
`/bin/sh -c` in an exec command.
Example:
I connect to irc like this:
exec termite -e "mosh server tmux a"
Without this patch the arguments are passed to sh as:
termite -e mosh server tmux a
When it should be:
termite -e "mosh server tmux a"
For the command to work.

Add quotes to multiword arguments.

---

swaylock/main.c

There is only a slight issue. When using a transparent color the views
are arranged to make room for swaylock which we can now see. I tried removing
the arrange call but that just made it worse by putting in an opaque view on the
workspace and not making the lockoverlay color. Ill raise an issue if
this is not easily solved

swaylock: Allow for transparent color values

---

sway/commands.c

Bounds checking works ok except it overlaps the bar. Just like with
normal floating. Should be fixed once swaybar is fixed.

commands: move position mouse

---

include/ipc-server.h
sway/handlers.c
sway/ipc-server.c

This makes IPC GET_PIXELS use the new `wlc_pixels_read` call instead of the deprecated `wlc_output_get_pixels`.
The old version worked by passing a callback function to wlc which would grab the pixels and send them to the IPC client.
The new version works by maintaining a list of clients who have requested the pixels of some output and then grap and send the pixels in the output_post_render hook of the `wlc_interface`.

Replace deprecated function wlc_output_get_pixels.

---

sway/extensions.c

This fixes #481 by making the swaylock views floating so they don't affect the arranging of other tiled views on the same workspace.

Don't rearrange views behind swaylock.

---

sway/main.c
sway/sway.5.txt

Ultimately, this is caused by the `sway_abort` that does not exit in this case.
It calls `wlc_terminate`, which itself does not exit if there is not current display.
Added some very minor fix here and there while browsing through the code ; they each have their separate commit.

Fix segfault when trying to use sway as IPC without a sway instance

---

include/bar/bar.h
include/bar/config.h
include/bar/ipc.h
include/config.h
include/container.h
sway/commands.c
sway/config.c
sway/container.c
sway/ipc-server.c
sway/main.c
swaybar/bar.c
swaybar/config.c
swaybar/ipc.c
swaybar/main.c

Right now, sway spawns at least one swaybar for every output, and an equal number of `status_command`'s.
This patch changes that behavior so sway only spawns one swaybar for every bar section in the config. And in turn swaybar is now responsible for drawing a bar on all the relevant outputs.
The main benefit is that the number of running swaybars are reduced, and more importantly, the number of `status_command` processes are reduced, reducing CPU usage.
This is also how i3 does it.
This is ready for review, but I need to fix one issue before it is merged.
The issue is when running the same bar on multiple outputs, then all the bars will pause rendering if a view is in fullscreen on one of the outputs.

Display single swaybar on multiple outputs

---

sway/extensions.c

Force sway to rearrange windows after the lock-view has been set as a floating window to finally fix #481.

swaylock: call arrange_windows for floating change

---

sway/sway.5.txt

In anticipation for #375, reorganized and augmented slightly sway(5)
so it makes a difference between commands intended for configuration,
commands intended for control, and those that can serve as both.

Segregate between config and runtime cmds in doc

---

include/workspace.h
sway/container.c
sway/layout.c
sway/workspace.c

It's possible to assign workspaces to certain outputs using the command:
workspace <name> output <output>
However, this did not work in some cases where the workspace was
assigned before the given output was made available to sway.
This patch fixes those cases.

Fix assigning workspaces to outputs

---

sway/extensions.c

This should fix #498 by resetting the input state when locking sway, such that the state is clear after unlocking swaylock.

Reset input state when locking compositor

---

sway/handlers.c

This makes sure that the outputs are rendered when sway is launched, so
the user doesn't have to move the cursor before the background and bar
gets rendered on screen.
Fixes #509

Render outputs as soon as wlc is ready

---

sway/extensions.c
sway/handlers.c

This should be a real fix for #509
This schedules a render when a background or panel is added to sway
through the desktop shell interface, that makes sure the render isn't
scheduled before the bg or panel is ready and you don't end up with a
black screen until the cursor is moved.

Schedule render when adding bg and panel

---

sway/CMakeLists.txt
sway/sway-bar.5.txt
sway/sway-input.5.txt
sway/sway.5.txt

Documents most of the bar commands in sway-bar(5) manpage.
The following command has not been document because they haven't been
fully implemented yet:
* mode
* hidden_state
* modifier
* tray_output
* tray_padding

Document swaybar commands

---

sway/extensions.c

Swaylock spawns and focuses a view for each output in sway. This can
sometimes move the focus to a new output after locking and unlocking the
screens.
This patch makes sure that the output which had focus when swaylock
was invoked, will regain focus once swaylock is closed/unlocked.
Fix #499

Focus correct swaylock view in multimonitor setup

---

include/extensions.h
sway/extensions.c
sway/handlers.c

desktop_shell.panel_size was only used to determine if sway should
rearrange the output when rendering the panel in the output_pre_render
hook.
This is not needed since the output will have been arranged at
that point.
It also caused sway to rearrange all the time when running with two
or more different monitors/resolutions because panel_size kept changing
with every output_pre_render callback.
Should fix #514 (unless there are more cases where this happen, but I don't think so)

Remove unused panel_size (and fix rearrange)

---

sway/commands.c

Before passing a command to a command handler the quotes are stripped
from each argument in the command. This is usually the wanted behavior
but causes a problem in the case of `exec` where quoted arguments can be
required when passing the exec command to `/bin/sh -c`.
This patch makes `exec` a special case and doesn't strip quotes from the
arguments. It will just pass the exec command verbatim to the exec
command handler.
Fix #518

Don't strip quotes from exec args

---

sway/commands.c
sway/sway.5.txt

So I was looking through #2 and found this :)
This just adds the config parsing of `workspace_layout <default|stacking|tabbed>` we obviously need borders for the actual implementation.

Add config option workspace_layout

---

sway/commands.c
sway/handlers.c

Sway has been very strict when it comes to key handling. Only on an
exact match would a bindsym be triggered.
This patch makes it less strict by for instance allowing the key combo
`$mod+1+2` to act as `$mod+2` if 2 was the last pressed key and `$mod+1`
if 1 was the last pressed key.
The new key handling uses the following algorithm:
1. List of bindings sorted by number of keys in binding (already the
default)
2. Find all bindings covered by the current keyboard state and list them
by same order as in 1.
3. Select the first binding from the list where the last pressed key is
part of the binding.
Addresses #452
@SirCmpwn we discussed the situation of `$mod+Shift+s` acting as `$mod+s`, but this will actually not happen because modifiers are checked [separately from other …

Make key handling less strict

---

sway/commands.c

Use of wrong type results in warning from clang. This fixes that.

Use correct type for keycode

---

common/ipc-client.c

When sway crashes a swaybar process is sometimes left behind running at
100% CPU. This was caused by the swaybar trying to retrieve an IPC
response from the closed sway socket.
This patch fixes the problem by aborting when the socket has been closed
(recv return 0).
Fix #528

swaybar: Abort when receiving 0 bytes in IPC call

---

swaylock/main.c

Prevent swaylock from crashing when it can't connect to sway for
whatever reason. i.e. XDG_RUNTIME_DIR not set.
Fix #534

swaylock: Fix crash when unable to connect to sway

---

sway/config.c
sway/main.c

This makes sure that sway will gracefully exit if the config is not
found or sway is unable to read it.

Gracefully exit when config is not found

---

_layouts/master.html
css/master.scss

The video was overlapping the logo when the browser window wasn't wide enough. :)

Prevent video from overlapping logo

---

include/lock/lock.h
swaylock/main.c

This should implement a similar input feedback as i3lock provides.
However I couldn't find out how to effectively flush the wayland pipeline, so that the rendered surface is actually viewed on the screens (See around L115)

Add graphical feedback to swaylock (#526)

---

include/config.h
sway/commands.c
sway/config.c
sway/main.c
sway/sway.5.txt

The include command (`include <path>`) makes it possible to include sub config files from
the main config file (or from within other sub config files).
The include command uses the following rules for including config files:
* the `path` can be either a full path or a path that is relative to the
parent config. Relative paths can be specified as `./relative/path` or
just `relative/path`.
* The same config file can only be included once (to prevent include
cycles). If a config is included multiple times it will just be
ignored after it has been included once.
* Including a sub config file is the same as inserting the content of
that file into the parent config, thus rules about overwriting
bindsyms etc. works the same as for a single config.
Implement #542

Add include command

---

sway/config.c

This makes sure sway doesn't hang if you try to pass a directory as config file.

Don't try to read config if not a file.

---

swaygrab/main.c

This pr fixes opt_string in swaybar, so that -R will be accepted in short form.

Add -R option to getopt opt_string

---

sway/commands.c

This makes it possible to define a mode name with surrounding spaces if
so desired. e.g.:
mode "   hello   " {  }

Allow surrounding spaces in mode name

---

sway/commands.c

We made the `pango:` prefix optional for the sway font, this makes it optional for the bar font config as well.

Make pango: optional for bar font

---

include/config.h
sway/commands.c
sway/config.c
sway/container.c
sway/sway.5.txt

Makes it possible to set default layout style for new windows and new
floating windows.
Close #556 
Note #559 also implements `new_window` and I don't mind rebasing on top of that if it's merged first.

Add cmds new_window and new_float

---

sway/layout.c

Was doing the wrong thing, causing warnings with clang. This is the way to reset the geometry.

Correctly reset border geometry

---

sway/container.c

Fix #564
I bet @DaanDeMeyer has tabbed/stacked layout by default.

Fix pointer related crash when stacked/tabbed

---

sway/container.c
sway/handlers.c

When creating a new view, wlc usually returns an initial visible geometry with
size 1x1. Setting those values as desired width/height causes a problem
for some windows (QT5) because they don't request a new geometry for
instance when made floating, so the floating window becomes 1x1.
To fix this problem we can just omit setting the desired width/height on
new_view and instead let the clients request a certain size if they feel
like it. e.i. gnome-calculator.
Fix #578
I have also included a related patch that just updates the geometry of a single floating window instead of the entire workspace on `view_geometry_request`, eliminating redundant updates in the layout.

Don't init desired width/height on new_view

---

swaylock/main.c

This was briefly discussed in #527 and I had this in my stash so I might as well push it.
It makes things a bit safer regarding the password buffer in swaylock, so you can't crash swaylock by filling up the memory with a really long password.

swaylock: Handle possible fail on password realloc

---

sway/border.c
sway/container.c

I have been observing increased memory usage with the latest git version of sway.
The best way to reproduce this is to open, say 200 terminal windows and close them, and observe that sway has shown drastically increased memory usage. This would suggest that sway has leaked memory somewhere.
I did a git bisect and found the first bad commit to be a8e084433d, which introduced window borders.
This pull request fixes two of the memory leaks I have found. However there still seem to be more memory leaks lurking somewhere as even after applying this I am still seeing increased memory usage even after all windows are closed. It may be worthwhile to do a stress test of both stability and memory usage. <del>This was due to a mistake in the previous attempt to fix this.</del> It wasn't. It's still …

Plug two memory leaks

---

sway/layout.c

Remove clang warnings (and some stray white spaces in the same part of the code).

Remove clang warnings (-Wsign-compare)

---

swaylock/pam/swaylock

Change swaylock.pam to make it work on Debian-based systems also.
Reference: https://github.com/i3/i3lock/blob/master/i3lock.pam

swaylock: Fix swaylock.pam

---

swaybar/status_line.c

In the i3bar protocol the value of the markup field is a string: "pango"
or "none" rather than a bool. This patch makes swaybar compatible with that.
http://i3wm.org/docs/i3bar-protocol.html

Use i3bar format for markup field.

---

sway/border.c
swaybar/render.c

This commit adds passing the markup argument to the get_text_size function, where omitted earlier.

Passing missing argument to get_text_size

---

include/bar/config.h
include/config.h
sway/commands.c
sway/config.c
sway/ipc-server.c
sway/sway-bar.5.txt
swaybar/config.c
swaybar/ipc.c
swaybar/render.c

This PR adds the ability to toggle parsing pango markup for plaintext statuslines.

Pango markup config

---

include/border.h
include/container.h
include/layout.h
sway/border.c
sway/commands.c
sway/config.c
sway/container.c
sway/debug_log.c
sway/focus.c
sway/layout.c

This is now ready for review/merge.
There's one known bug in wlc, that causes views to become invisible when moved away from a tabbed/stacked layout in some cases. (Will be fixed separately, obviously).
---------------------------------------
This is just to let other people follow the progress and for me to have some sort of checklist for bugs I find.
Will update when ready for review.

Tabbed and stacked layout

---

swaylock/main.c

PAM will free() the password buffer during the authentication process so swaylock is causing a double-free when the entered password is invalid.

swaylock: fix double free

---

include/border.h
sway/border.c
sway/layout.c

This patch makes sure to clear the border buffer of fullscreen view so
the border doesn't get drawn behind a fullscreen view, which would be
visible if the view was transparent.
(I also sneaked in a commit addressing this [comment](https://github.com/SirCmpwn/sway/pull/566#discussion_r60936168)).

border: clear buffer on fullscreen views

---

sway/commands.c

The bindcode has to be offset by 8 to match the keycode we get from wlc.
https://github.com/xkbcommon/libxkbcommon/blob/master/xkbcommon/xkbcommon.h#L160

Fix bindcode by offsetting xkb keycode by 8

---

sway/commands.c

sway/commands.c: add some free calls to release allocated memory

---

sway/workspace.c

With this patch, memory that was allocated and would not have been free'd before continue'ing is cleaned up.
@SirCmpwn: Is the logic of this method still okay, particularly with the new `break;`? I'm not comfortable with the source code yet but I hope my changes still achieve the same thing.

sway/workspace.c: Cleanup some un-free'd memory

---

sway/config.c

`bar->verbose` never gets initialised which causes Valgrind to complain with the following message:
```
Conditional jump or move depends on uninitialised value(s)
==13873==    at 0x5531358: ??? (in /usr/lib/libjson-c.so.2.0.1)
==13873==    by 0x55318C4: ??? (in /usr/lib/libjson-c.so.2.0.1)
==13873==    by 0x553172B: json_object_to_json_string_ext (in /usr/lib/libjson-c.so.2.0.1)
==13873==    by 0x41F3E9: ipc_client_handle_command (ipc-server.c:472)
==13873==    by 0x41E538: ipc_client_handle_readable (ipc-server.c:209)
==13873==    by 0x5742831: wl_event_loop_dispatch (in /usr/lib/libwayland-server.so.0.1.0)
==13873==    by 0x5740EE4: wl_display_run (in /usr/lib/libwayland-server.so.0.1.0)
==13873==    by 0x4E6085B: wlc_run (in /usr/lib/libwlc.so.0.0.2)
==13873==    by 0x424C56: main …
```

sway/config.c: Initialise struct value

---

wayland/registry.c

registry wasn't freed anywhere, and thus memleaked.

wayland/registry.c: free() registry at registry_teardown

---

sway/workspace.c

I was a bit too quick to merge #616 which introduced a bug.
This should fix that.

Remove premature break in workspace_next_name

---

include/config.h
sway/commands.c
sway/config.c
sway/input.c
sway/sway-input.5.txt

Implement a new sway input command for setting the libinput pointer acceleration profile.
Closes #576 .

Add input cmd for setting pointer accel profile.

---

sway/border.c
sway/handlers.c

Requires Cloudef/wlc@80bf003
Fix #623 
This uses the newly added `wlc_view_properties_updated` callback to know when a title must be updated, rather than doing it every time a view is rendered.

Update view title of tabbed/stacked windows

---

sway/ipc-server.c

`strncpy()` makes sure to not overflow the buffer, but doesn't terminate it if the max size was reached.

Always terminate ipc path

---

common/log.c

That `fclose()` was followed by a second one 2 instructions later.
I also moved the scope of `maps` to reflect its actual usage.

Fix double-close in error_handler()

---

common/log.c
include/log.h

This removes most preprocessor logic, leaving it only it the header, which I find cleaner.
I won't be offended if you prefer the old code and don't want my patch, so feel free to just tell me so :stuck_out_tongue_winking_eye:

Refactor preprocessor logic out of _sway_log()

---

include/config.h
sway/commands.c
sway/config.c
sway/handlers.c
sway/sway.5.txt

This PR implements configurable floating scroll behavior (it adds a command to set it, and additionally it adds another possible behavior to existant ones: run a user-defined sway command).
I'm having trouble documenting it according to the conventions though: I have know idea how shall the specification look like.
The command is 'floating_scroll', and it accepts three possible parameters: behavior, to set behavior, up and down, to set a command to run.

Implement configurable floating scroll behavior

---

sway/commands.c

The layout command should only work with titled windows, thus it should
have no effect when a floating window has focus.
Should fix #643

Prevent changing layout when focusing float window

---

sway/container.c

When trying to split with an empty workspace, it segfaults on `view->layout` because `view->parent` becomes null.
This should fix #640, thanks to @jpml-

sway/container.c: fix segfault where view is assigned prematurely

---

sway/border.c
sway/layout.c

Borders are now drawn correctly (same behavior as i3) for tabbed and
stacked containers, when the children have 'border none' set.
Closes #661

Fix borders for tabbed and stacked containers when children have 'border none' set.

---

sway/extensions.c

When setting the background we need to rearrange the output otherwise the swaybar won't be arranged as it should.
Fix #659

Rearrange output when setting background

---

README.md
include/commands.h

1. add openSUSE into README.md
2. header contained `remove_view_from_scratchpad()` with wrong prototype

2 minor things

---

sway/focus.c

Please note this will require careful review; I'm just learning C and also I'm pretty sure the way I did this is really dumb. I'm not familiar enough with the codebase to know if it will break other things.
Assume the following view/monitor setup:
monitor 1       monitor 2
+-----------+   +-----------+
|A          |   |D          |
|           |   |           |
+-----+-----+   |           |
|B    |C    |   |           |
|     |     |   |           |
+-----+-----+   +-----------+
If view A is set to full screen, and focus is on view D, `focus left` will not change focus to A - instead Sway will attempt to focus on C, find that A is full screen, and return without changing focus.
This patch changes the behavior of `set_focused_container()` so that when focus is shifted to a workspace with a …

set focus on fullscreen view when changing focus

---

sway/commands.c
sway/container.c
sway/focus.c

This solves a pain point I have. I assign workspaces 1-6 to my left monitor, 7-12 to my right. When I turn my monitors back on after being off, all workspaces end up on my left monitor, even 7-12. This commit changes the `new_output()` function so that when an output is being created, if there are workspaces that are assigned to that output on some other output, they are moved to the new (assigned) output.
(also included is a minor formatting fix and removal of a comment that is no longer applicable - neither is related to the aforementioned functionality)

enforce workspace output assignents

---

sway/ipc-server.c

First one is a simple missing `close()` before a `return` in `ipc_handle_connection()`.
The second one is a bit more complicated:
A couple `break` were not going all the way out of the `switch`, so I replaced all these implicit `goto` (ie. `break`) with explicit ones to always exit the switch. A `break` was also missing, resulting in a false-positive error msg in `IPC_GET_BAR_CONFIG`.
This also fixes the `buf` mem leak, which wasn't freed when hitting the `default` branch.
I also added a `return` when `buf` fails to `malloc`, to avoid a null-dereference in `recv()`.
I also made `ipc_send_reply()` consistent by never closing the connection, and having the caller explicitly do it when appropriate. I wasn't sure if `ipc_send_event()` should always close it, so I kept the old behaviour of …

Fix a few mem leaks in ipc-server

---

include/config.h
include/container.h
sway/config.c
sway/container.c
sway/handlers.c

This patch includes a initial work for these options:
floating_maximum_width
floating_maximum_height
floating_minimum_width
floating_minimum_height
It also sets sane values for the floating windows, avoiding 1x1 windows caused by wlc.

Initial work for floating view with sane values

---

common/list.c
include/list.h
include/output.h
sway/output.c

Summary: implement a `list_stable_sort()` function, make `sort_workspaces()` use it instead of `list_qsort()`. For more backstory, see https://github.com/SirCmpwn/sway/pull/675.

implement stable sort for lists

---

common/readline.c
sway/config.c
sway/sway.5.txt

Escape line return in configuration file with the '\' character. Similar
to shell scripts.
Signed-off-by: Roosembert Palacios <roosembert.palacios@epfl.ch>

Sway: Configuration: Support for escaping line breaks.

---

sway/commands.c

This includes the check of the $ for the variable assigned.
So set something /home generates an error, since the correct syntax must be set $something /home.
This also should fix partially the issue #681 since now it handles the undefined behavior of p.we_wordv.

Variables related fixes

---

common/util.c
include/config.h
include/util.h
include/workspace.h
sway/commands.c
sway/config.c
sway/handlers.c
sway/workspace.c

This PR is mostly for discussion - it still needs work even if you want to merge it. This is a (very messy) start on a potential fix for #462, however the problem is it's not that useful for two reasons:
1. If the app is a client-server-style app, like gnome-terminal for example, the pid we get from the view is probably the pid of the client, but the pid we're looking for is that of the original process, which could be the server.
2. This only works on Wayland apps. [`wl_client_get_credentials()`](https://people.freedesktop.org/~whot/wayland-doxygen/wayland/Server/structwl__client.html#a82a97cb3a66c1c56826a09a7b42453d9) returns the pid of the compositor if the forked process is connected through `socketpair()`, which is how WLC handles xwayland processes. Obviously the compositor's pid is …

messy start of a fix for #462

---

common/util.c
sway/config.c

Sorry for the post-merge update but I found a couple small things that needed to be fixed. In util.c, if `fopen()` worked but `read_line()` failed, the file wouldn't get closed. And in the `config->pid_workspaces` cleanup, I forgot to free the items before deleting them from the list.

couple small fixes

---

sway/container.c

This fixes a segfault, when trying to get parent of the workspace/root container/(?), as it is not assuered that the view's parent node is not null in the loop.
For example, when performing `split` on a workspace.

Added a null check in tabbed_stacked_parent

---

sway/handlers.c

Fixes #714, by preventing change of focus from a window to the whole ws

Check if found ws is focused in new view handler

---

swaylock/main.c

Without unistd.h the following functions getuid, alarm and
close are implicitly declared causing compilation to fail due to
-Werror=implicit-function-declaration

Bug fix: Add missing header file, unistd.h

---

common/log.c
include/log.h
sway/debug_log.c

This patch also makes all global variable in log.c static.

Add get_log_level() to encapsulate v (current log level)

---

include/ipc-json.h
sway/CMakeLists.txt
sway/container.c
sway/ipc-json.c
sway/ipc-server.c
sway/layout.c

This PR will:
- implement `get_tree` swaymsg command
- factor most JSON object construction out of `ipc-server.c` into a separate `ipc-json.c`
- add root container geometry (updated when outputs are created/destroyed)
The output from `get_tree` doesn't have everything i3's output does yet, but this at least gets most of it. I added some non-i3 stuff in there too, like the scratchpad contents. Definitely open to changes/fixes/etc on this!

implement `get_tree` command

---

sway/handlers.c

This adds an `arrange_windows()` call in `handle_output_post_render()` which seems to have fixed #678 for me.

I think this fixes #678

---

include/client/window.h
wayland/registry.c
wayland/window.c

Tested the keyboard related changes by running swaylock and making sure I could unlock the screen. (As far as I can tell, swaylock seems to be the only client that handles keyboard events.)

Enable windows to register to get notified of pointer button events

---

include/container.h
sway/commands.c
sway/container.c
sway/handlers.c

Tabbed/stacked containers are now created only if a view is present on
the workspace. If a view is created on previously empty tabbed/stacked
workspace, it gets wrapped in a container.
I might have broken something with the change in container.c/swayc_tabbed_stacked_parent, as it's used in some other places, though it seems to work.

Fix tabbed/stacked corner case #742

---

sway/ipc-json.c

Use C99 `intptr_t` instead of `int64_t` when passing pointers.

Fix build on x86

---

include/container.h
sway/border.c
sway/commands.c
sway/container.c
sway/focus.c
sway/handlers.c
sway/layout.c

Refactored swayc_tabbed_stacked_parent into 2 functions - one returns the root tabbed/stacked ancestor (which was how the original function worked), the other return just the immediate tabbed/stacked parent.

Clarify which tabbed/stacked container we want (fixes #751)

---

README.md

I wanted to make sure that NixOS users get the warning without polluting the README.
Turns out the "Install other distros" had plenty to say about supported packages, so I slightly restructured the page.
Now the README links to the wiki page.

Packages link to the wiki page with instructions

---

completions/zsh/_swaylock

added new option of daemonize (-f --daemonize) that was added to swaylock in https://github.com/SirCmpwn/sway/pull/750 and added socket completion upon reading more into swaylock/main.c  (it also is in the usage help but never had it in completion)

Update swaylock zsh completion

---

include/ipc.h

For reference, https://i3wm.org/docs/ipc.html#_events

Properly construct event bitmasks

---

include/layout.h
sway/focus.c
sway/layout.c
sway/workspace.c

More invocations of `arrange_backgrounds()` to be inserted, if/when the need arises.

Arrange backgrounds only when required

---

sway/layout.c

With hide_edge_borders option on, borders were hidden even where they shouldn't been.
Since containers can only be inside workspaces, workspace geometry is used for determining edge borders (instead of output, which might also contain swaybar).

Hide edge borders fix

---

sway/layout.c

origin x & y are not needed because this is the only child in the workspace. if swaybar location is top, view's y is not zero, so y + view's height > workspace height.

fix regression in hide_edge_borders

---

sway/layout.c

Prior to this commit, only windows that are as high or as wide as the workspace had hidden bottom or right borders. I hope we'll get it right this time :D

properly hide bottom and right borders

---

sway/handlers.c

don't passthrough a floating_scroll event to focused window

---

sway/commands.c

For compatibility with i3, put the command result into an array.
Returning multiple command results is still unsupported.

Put ipc command result json in an array

---

sway/focus.c

In the `focus parent` command, do not set focus above the workspace level.
These containers are not meant to be focused.
This prevents a crash on repeated `focus parent` commands.

bugfix: cmd focus parent don't set focus above ws

---

sway/focus.c

In `move_focus()`, when given an output, set the focus to the workspace of that
output instead of the output itself.
This fixes a bug that did not allow users to switch between outputs introduced
in afc6ad6.
It also fixes other issues before that commit when a workspace with children
was selected and the user tried to switch focus in the direction of another
output.

bugfix: set focus to workspace of an output

---

sway/commands.c

Previously, cmd_kill only closed a focused view, while containers were
not affected. Now it closes all views that are children of the focused
container.

Close all focused container's child views on cmd_kill

---

sway/border.c

Whenever a stacked or tabbed container has focused, paint the titlebars of all
its child windows to be focused as well to indicate the parent stack/tab
container has the focus.

Render focused stack/tab children focused

---

include/focus.h
sway/commands.c
sway/focus.c
sway/layout.c
sway/sway.5.txt

The `focus child` command focuses the child container within the selected
container.

Implement `focus child` command

---

sway/layout.c

This commit just fixes the bug that sometimes made initial workspace_layout unusable.
Sway is actually quite different in how workspace_layout functions, compared to i3. The i3 behavior isn't exactly logical, so I raised an issue in https://github.com/i3/i3/issues/2402.  When I get some response over in the i3 repo, I'll try to match its correct functionality.

bugfix: invisible windows on empty workspace with tabbed/stacked layout

---

include/border.h
sway/border.c
sway/layout.c

- properly hide top border inside tabbed/stacked
When titlebar is hidden, top border of the topmost view inside
tabbed/stacked container will not be drawn. This is changed in layout.c
On the other hand, top border should be drawn sometimes, for example
when titlebar is hidden on a view that is not the topmost inside
tabbed/stacked container. This is changed in border.c
- second commit is just a revert of some changes in 6ea02f30, which didn't incorporate some more recent fixes

Misc border fix

---

sway/commands.c

Deeply nested containers which had their layouts changed didn't update
their actual_geometry, this messed up their child containers. Those got
width and height of 0, which was then decreased for stacked/tabbed
containers by title height. Underflow ensued, these containers suddenly
had height 4294967273. In short, not updating actual_geometry didn't
play nicely with nested containers.

Update container geometry on layout switch

---

include/border.h
sway/border.c
sway/commands.c
sway/focus.c
sway/handlers.c
sway/layout.c

The previous implementation of focus handling assumed that only views can be
focused. Containers can also be focused with a command like `focus parent` or
`focus child`.
Change `set_focused_container()` to handle the case of the given container
being a container with children and update borders accordingly.

Implement focus handling for containers

---

include/focus.h
sway/focus.c
sway/handlers.c

The value of `locked_view_focus` is always false. Remove dead code associated
with this variable to simplify things.

Remove dead global locked_view_focus

---

sway/handlers.c

Focus the container on the output (not the output itself) when an output is
focused.
This is intended to fix a bug where borders are not updated correctly when
switching the vt away/back to sway.

bugfix: focus container on output when focused

---

sway/ipc-json.c

When I wrote `get_tree` I didn't realize an unmanaged node is just a `wlc_handle`. It makes no sense to include these in the json response. Currently this causes a segfault if any unmanaged nodes exist when `get_tree` is called.

remove unmanaged nodes from get_tree

---

include/border.h
sway/border.c
sway/focus.c

Merge the main rendering paths of all containers to make focus setting a bit
simpler and easier to follow.

Simplify focus setting

---

common/util.c

Some implementations of strtol may clamp the values to LONG_MAX instead of
wrapping around to negative values, so use strtoul instead to parse colors.
(Mentioned in #343)

common: use strtoul in parse_color to avoid clamp

---

sway/commands.c

When workspace_auto_back_and_forth is enabled, workspaces get switched
twice with previously mentioned command, which is not the expected
behavior.
Removes one redundant creation of previous workspace.

Fix 'workspace back_and_forth' and workspace_auto_back_and_forth clash

---

sway/ipc-json.c

This is for i3 (and i3ipc library) compatability.

ipc: always include nodes in views

---

sway/ipc-server.c

Recursively describe workspace containers in the workspace event. This is for
compatability with i3 and i3ipc libraries.

ipc: recursive workspace containers in event

---

sway/ipc-server.c

Log the sending of the events in the debug log. This makes ipc server events
easier to verify.

ipc: log sending of events

---

sway/handlers.c

Switching back to original workspace should be done only if workspace
was switched while appending new view.

Fix switch to prev ws on handle_view_created

---

sway/sway-input.5.txt

Making it more obvious where to get the proper input device names.

added get_inputs hint to man 5 sway-input

---

sway/border.c

This is a feature that can't work the same as i3, because there is no
real window classes in wayland. This way, we avoid null titles as much
as possible.

Display class in container title if app_id is null

---

sway/config.c

Output now gets disabled if disable command is invoked via bindsym or
IPC.

Handle output disabling during runtime

---

common/ipc-client.c

Calculating size of struct using "sizeof(addr.sun_family) + strlen(addr.sun_path)" is not valid on FreeBSD.

Fix to make ipc client code FreeBSD compatible.

---

sway/layout.c

`vertical` and `horizontal` should be swapped.
If border_left and border_right were set to 0, the vertical borders
instead of the horizontal borders would be hidden.
i3 handles this command equally.

Correct `hide_edge_borders` command

---

sway/border.c

Indicator border color is now used only when a container is the only
child. Reason for the change? i3 does it this way. Sway container
borders are now a bit more similar to i3 ones.

Use indicator border color only when needed.

---

sway/config.c
sway/container.c
swaybar/ipc.c

When using a bar on a named output, load_swaybars() requires the
output to be active (ie. in the root container), but this is not the case if
the bar is added to the last output. To fix this, load_swaybars() is now
called after the output has been added to the root container.
After fixing that, swaybar would segfault due to using the wrong index
variable when loading outputs and config.

Fix swaybar when running on named outputs.

---

include/sway/container.h
sway/focus.c
sway/layout.c

Based on some test logging I think setting this pointer in `set_focused_container()` should be sufficient. I also set it to the root container in `init_layout()`; I do not know if that is a useful thing to do.

add global `current_focus` pointer

---

sway/ipc-json.c

This changes how the `focused` property is set on views in the `get_tree` JSON response. Previously, all views in a focused parent container were marked as focused; now only the focused view is.

fix view focus property in get_tree json

---

sway/ipc-server.c

Further reading of the i3 docs indicate the `get_workspaces` reply doesn't follow the `get_tree` reply's rules regarding the `focused` attribute. This also fixes a Swaygrab bug introduced with #904 (Swaygrab currently depends on the `get_workspaces` reply).

fix get_workspaces json reply

---

include/swaygrab/json.h
sway/ipc-json.c
sway/ipc-server.c
swaygrab/CMakeLists.txt
swaygrab/json.c
swaygrab/main.c

`swaygrab -f` will grab only the focused container instead of the whole output. Tested with both the image and video options. Requires [this WLC commit](https://github.com/Cloudef/wlc/commit/5c4528bd3ff7e4bdcd7356b5f902b10d5be9a27f), otherwise the geometry gets wonky.

implement "focused container" option for swaygrab

---

sway/commands/workspace.c

This implements commands such as:
workspace number 9: test
If a workspace with the given number exists then it will be focused,
otherwise a new workspace with the given name will be created.
This functionality is as per i3's.
I'm not an expert at C, so if there's an easier way to get argv[1] onwards as a string then let me know and I'll amend.

Implement default name for workspace command

---

sway/main.c

This commit deals with issue #884. I consulted the following sources:
https://www.securecoding.cert.org/confluence/display/c/POS36-C.+Observe+correct+revocation+order+while+relinquishing+privileges
and
https://www.securecoding.cert.org/confluence/display/c/POS37-C.+Ensure+that+privilege+relinquishment+is+successful

Split setgid and setuid, add privilege check [RFC]

---

swaybar/render.c

Fixes #910. There were some missing multiplications with window->scale.

Correctly scale swaybar

---

sway/main.c

This is necessary because commands in the config file (mode for
instance) emit ipc events, and if ipc_init has not been called the
ipc_clients_list is not initialized, and we segfault.  This fixes that
bug.

moved ipc_init above config file processing.

---

sway/focus.c

This should fix #868. Essentially the problem was if the prior focused container was an empty workspace, it got destroyed in the `update_focus()` call, but then we were trying to dereference it again later. I'm not sure how this ever worked without the "hardened" CMakeLists.txt patch mentioned in #891.
I made a lot of other changes in this function to try to make it easier to follow. It took me a while to figure out what was going on so I figured comments and descriptive variable names might help.

prevent dereference of freed workspace

---

swaybar/render.c
wayland/pango.c

Fixes #897. This change allows using numeric character references in workspace names
- for example &#230; which stands for sharp s. A fix was necessary in
get_pango_layout, since markup and parsed markup had different width.

parse pango markup in workspace names (and bugfix)

---

include/sway/commands.h
include/sway/config.h
sway/commands.c
sway/commands/force_focus_wrapping.c
sway/layout.c

This should fix #930.  Additionally, for better compatibility with i3, force_focus_wrapping command and changing focus between floating containers were implemented.

Wrap focus change

---

sway/border.c

af44154 forget one "get_text_size" made it possible to
do a format string by setting title bar.
Fix #893

Add constant scale factor in get_text_size

---

sway/layout.c

If we want to add a sibling of different type than current
container it failed. Because we add it to the wrong list
Fix #927

Fix creating of sibling floating/children

---

sway/commands.c

These were not alphabetized, so some commands weren't found. I used the sort function in my editor.

reorder cmd_handler arrays for bsearch

---

sway/handlers.c

- move wlc_view_set_mask before applying window criteria
- check parent_container because container in scratchpad doesn't have a
parent

fix for_window [] move scratchpad

---

sway/commands/move.c

Can't move an empty workspace

---

include/sway/container.h
sway/commands/layout.c
sway/commands/move.c
sway/commands/split.c
sway/container.c
sway/handlers.c
sway/layout.c

Fix #901. Minimal working example: default config, on empty workspace $mod+w, ```swaymsg exec nautilus```, Ctrl+i. Previously you'd get a segfault, after fixing that the popup would appear, but nautilus would become invisible. That's fixed in the second commit.

Fixes dealing with workspace_layout and related bugs [rfc]

---

include/sway/commands.h
include/sway/config.h
sway/commands.c
sway/commands/input.c
sway/commands/input/left_handed.c
sway/config.c
sway/input.c
sway/sway-input.5.txt

Some users may want to switch buttons on their input devices, turns out
libinput already supports it. Let's add a support for it in our config.
Signed-off-by: Michał Winiarski <knr@hardline.pl>

Add left_handed support for input devices

---

sway/commands/layout.c

This minor patch turns around an if-clause, which makes ```layout toggle``` default to horizontal instead of vertical split, which can be observed when issuing the command on a tabbed or stacked container.

Change layout toggle to default on horizontal split

---

CMake/Manpage.cmake
CMakeLists.txt
completions/zsh/CMakeLists.txt
config.in
sway/CMakeLists.txt

Exherbo installs architecture dependent data in a different place than architecture
independent data. More concretely: binaries go in /usr/$chost/{bin,lib},
data goes in /usr/share and configs in /etc, /etc is already configurable
through CMAKE_INSTALL_FULL_SYSCONFDIR but the datadir was not. This
patch fixes it so that things can be pushed in the right places.

Use CMAKE_INSTALL_FULL_DATA{,ROOT}DIR

---

sway/container.c

Sometimes views are created before we got its size
I propose this because I got a little screen and this is boring.

Put floating views in center, fallback on top left

---

sway/extensions.c

Don't switch the internal tracking of focus to the swaylock surface,
to allow for switching back to the previously active window (or the
currently active window, if some new process changed).
Closes #998
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

sway: extensions: make locking give back focus

---

protocols/CMakeLists.txt
protocols/gamma-control.xml
sway/extensions.c

Depends on https://github.com/Cloudef/wlc/pull/216 and on https://github.com/giucam/redshift

Add redshift support

---

sway/main.c

This fixes sway when run with suid binary. (suid does not work with filecaps in an intuitive manner, so breakage occurs).
Note: suid binary will not require CAP_SYS_PTRACE.

Keep CAP_SYS_PTRACE with suid binary

---

include/sway/config.h
sway/commands/hide_edge_borders.c
sway/layout.c

Hi,
I've tried to implement i3v4.13 smart edge borders. I'm new to this so please be patient with me a bit. If anything is wrong with my changes let me know, I'll try to fix it.

Implement hide_edge_borders smart (like in i3 4.13)

---

include/sway/output.h
sway/output.c

This fixes issue #733 . Now if the user focuses output right but is at
the rightmost monitor, the focus will wrap the the leftmost monitor
(or whatever direction was chosen).
This commit adds a new function, swayc_opposite_output, which selects
the opposite output given a position and a direction. Now, when calling
output_by_name, we first check if there is an adjacent output to switch
to. If that fails, we call swayc_opposite_output to handle wrapping.

Add output wrapping

---

sway/sway.5.txt

I forgot to add the option to manual page, so here is the fix.

add hide_edge_borders smart to sway.5 manual

---

sway/criteria.c

This reflects i3 behavior (see i3/i3#1770)
Scrapping focused support will probably break some existing configs

Support __focused__ as a valid criterion

---

sway/handlers.c

~~Not sure if this needs adjustments for hidpi.~~ Seems to work.
(Based on https://github.com/Cloudef/wlc/commit/09fca20730c0da361e375eebede53a9541af7b7e)

Properly place windows with xdg-positioner

---

sway/container.c

Since we are creating a new view here, `wlc_view_get_visible_geometry()` does not (always? ever?) give us the geometry we want; instead we need the "absolute" geometry of the view.

use absolute view geometry to calculate position

---

common/util.c
include/swaylock/swaylock.h
swaylock/main.c
swaylock/swaylock.1.txt

Colors are configured through the command line so that swaylock conforms
to the i3lock fork 'github.com/chrjguill/i3lock-color'. Differences from
it are that one letter options '-r' and '-s' are not implimentend because
'-s' is already used by '--scaling' in swaylock.
This commit also fixed whitespace in 'include/swaylock/swaylock.h' and
changed `parse_color` in 'common/util.h' so that it can accept colors
that do not start with a hash. This was done to keep compatability with
the i3lock fork.

Feature for #1078: Configurable swaylock colors

---

include/sway/layout.h
sway/commands/move.c
sway/layout.c
sway/sway.5.txt

This commit lets the 'move' command apply to floating containers as well
as tiled ones. The command may be appended with a number of pixels and
then the string `px` (like '10 px') in order to move the container more
or fewer than the standard ten pixels.

i3 feature support: Moving flotaing containers

---

sway/commands/workspace.c
sway/sway.5.txt

This commit allows unquoted spaces in worspace names in order to keep
compatability with i3. The names _must not_ contain the string "output"
which is documented in 'sway.5' because how sway detects the `move
<workspace> output <output>` command. Also I documented that "number"
may be used before the worspace name without affecting how the name is
evaluated.

Fix #1099: Allow spaces in worspace names

---

sway/commands/workspace.c

I don't know if this is going to break any of the functionality introduced in #1101 but it does make workspace -> output assignment work again.

fix workspace output assignment

---

sway/sway.5.txt

Fix trivial typo in sway.5.txt (right_ -> _right_)

---

include/util.h

If the WLC headers aren't installed globally (e.g. somewhere in your home directory rather than in `/usr/includes`), despite `-DWLC_INCLUDE_DIRS` being passed correctly to `cmake`, `make` fails.
Apparently, the `CMakeList.txt` in some subdirectories are missing `WLC_INCLUDE_DIRS` in their `include_directories()` directive.

Superfluous include causes failures if WLC headers aren't installed globally

---

sway/config.c
sway/sway-security.7.txt

Allow also 444 as security file mode in addition to 644.
This helps with systems like NixOS where nothing in /nix/store is writable to anyone.

Allow also 444 for security file mode

---

sway/commands/workspace_layout.c

If the configuration file contains:
```
workspace_layout auto left
```
or anything similar, the code checking the configuration will ignore the command and output an error.
The reason is easily confirmed with GDB:
```
(gdb) break cmd_workspace_layout
Breakpoint 1 at 0x16240: file /usr/src/debug/sway-master/sway/commands/workspace_layout.c, line 5.
(gdb) run
Starting program: /usr/bin/sway 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.24-4.fc25.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Detaching after fork from child process 8799.
Detaching after fork from child process 8800.
Breakpoint 1, cmd_workspace_layout (argc=2, argv=0x559a6f093d98)
at …
```

Fix off-by-one error when checking workspace_layout arguments

---

sway/commands/workspace.c

As best I can tell this todo was intended to add workspace movement to
the given output with the `workspace <ws> output <op>` command, but i3
does not behave this way.
see #1122 for some clarification

remove unnecessary todo item

---

sway/handlers.c

prevent fullscreen focus thievery

---

sway/container.c
sway/layout.c

This pull request fixes #1120 for me.
The commit message contains an explanation of why I think it works.
It also includes a small behaviour change to workspace layouts, as I found it confusing that they would default to L_HORIZ despite the default of an output being something else. Perhaps there's a reason for this that I'm not seeing?

Fix move next crash

---

include/sway/commands.h
include/sway/criteria.h
sway/commands.c
sway/commands/border.c
sway/commands/floating.c
sway/commands/focus.c
sway/commands/fullscreen.c
sway/commands/kill.c
sway/commands/layout.c
sway/commands/mark.c
sway/commands/move.c
sway/commands/resize.c
sway/commands/split.c
sway/commands/unmark.c
sway/criteria.c
sway/sway.5.txt

This commit changes how commands decide what container to act on.
Commands get the current container though `current_container`, a global
defined in sway/commands.c. If a criteria is given before a command,
then the following command will be run once for every container the
criteria matches with a reference to the matching container in
'current_container'. Commands should use this instead of
`get_focused_container()` from now on.
This commit also fixes a few (minor) mistakes made in implementing marks
such as non-escaped arrows in sway(5) and calling the "mark" command
"floating" by accident. It also cleans up `criteria.c` in a few places.
I have tested the changed commands and things seem to work.

Improve criteria handling

---

sway/criteria.c

This changes the regex matching for criterias to use PCRE instead of POSIX. i3 uses PCRE, so this would be increase compatibility with it.
PCRE is already pulled in as a dependency so I don't think this will cause any issues.

Change regex to use PCRE

---

sway/ipc-server.c

Doing this before calling ipc_client_disconnect is calling file descriptors to leak.

Removed explicitly setting file descriptors to -1

---

sway/commands/mark.c
sway/ipc-server.c

In i3 every mark is unique and one mark cannot be used in more than one
window, sway behavior has been amended to match this.
`swaymsg -t get_marks` will now return an array of all marks used in sway.
See #98

Add `-t get_marks` and use more i3-like marks

---

.travis.yml
CMake/FindLibcap.cmake
CMakeLists.txt
sway/main.c

- Moved <sys/capability.h> include inside `__linux__` guard, because all uses are similarly guarded.
- <sys/capability.h> is a part of optional devel package on at least fedora, so CMake now explicitly checks that libcap devel files are available.
- Added libcap to list of arch packages in .travis.yml, to make the dependency explicit. travis-ci installs the package by default, which is why this hasn't surfaced previously).

Add libcap check to CMake

---

include/sway/ipc-json.h
sway/ipc-json.c
sway/ipc-server.c
swaymsg/main.c
swaymsg/swaymsg.1.txt

If stdout is a tty, it will pretty print unless -r (--raw) is given.
Sample outputs:
```
~/s/s/build > ./bin/swaymsg fullscreen toggle
Error: Permission denied for fullscreen toggle via IPC
~/s/s/build > ./bin/swaymsg -t get_workspaces
Workspace 3:三
Output: DVI-I-1
Layout: splith
Workspace 1:一 (off-screen)
Output: HDMI-A-1
Layout: splith
Workspace 5:五 (focused)
Output: HDMI-A-1
Layout: splith
~/s/s/build > ./bin/swaymsg -t get_inputs
Input device Metadot - Das Keyboard Das Keyboard
Type: Keyboard
Sway ID: 9456:320:Metadot_-_Das_Keyboard_Das_Keyb
Input device Wacom Intuos S 2 Pen
Type: Tablet tool
Sway ID: 1386:827:Wacom_Intuos_S_2
Input device Wacom Intuos S 2 Pad
Type: Tablet pad
Sway ID: 1386:827:Wacom_Intuos_S_2
Input device Logitech Gaming Mouse G502
Type: Keyboard, Mouse
Sway ID: …
```

Add pretty printing to swaymsg

---

sway/main.c
sway/sway.1.txt

This is shipping no earlier than 0.13 and not unless I hear positive feedback from nvidia users about the new EGL support in wlc.

Downgrade nvidia proprietary driver warning

---

README.md
sway/ipc-json.c
sway/sway-bar.5.txt

(Was "Prep Work for swaybar hide mode", but #1169 beat me to it so I just kept the cleanup fixes)
I think b463fb8 (taken together with #1150)  shows a current weakness in the way version management/CI is handled. I'd suggest that an explicit version baseline for dependencies be defined and documented. The CI should then test at least against that baseline to make sure sway is in sync with the shipped versions of its dependencies in recent distros releases. my 2c.

Misc fixes

---

common/log.c
include/log.h

- `_sway_assert` is a variadic function which tries to delegate to another variadic function. This requires a vprintf-style variant of the delegate. https://stackoverflow.com/a/150616
- DRY: _sway_log now delegates to _sway_vlog. 
- `sway_assert` did not correctly propagate the location information for the assert callsite.

Fix multiple issues in sway_assert

---

common/util.c
include/sway/security.h
include/util.h
sway/commands.c
sway/commands/ipc.c
sway/commands/permit.c
sway/extensions.c
sway/handlers.c
sway/ipc-server.c
sway/security.c

FOR_REVIEW: IPC security - Allow policy targets to be symlinks

---

sway/commands/move.c
sway/sway.5.txt

Closes #931. While there's a few more weird interactions, none of them keep me from using the scratchpad with a terminal emulator in it.

Feature move to scratchpad

---

sway/sway.5.txt

The code and docs use `off` not `no`.

Fix typo in sway(5)

---

CMakeLists.txt
sway/ipc-json.c
sway/main.c
swaybar/main.c
swaygrab/main.c
swaylock/main.c
swaymsg/main.c

Currently, the version number (as shown by `sway --version` and used in other places) is based on
`git describe`. But when packaging sway for Debian, where it is built outside of git, these information aren't available. Moreover, the version string contains information, such as date and branch, that aren't relevant for release builds, not to mention that the boilerplate to generate that version string is duplicated across the code base, which I fixed as well by having `CMakeList.txt` generate the version string. Finally, while on it, I also fixed the JSON version information in the IPC code.
Note that I removed the code path for when `SWAY_GIT_VERSION` and `SWAY_GIT_BRANCH` aren't defined. This was dead code anyway, as `CMakeList.txt` always defined these macros, but merely with an empty …

Add -DVERSION flag for release version numbers

---

sway/commands.c
sway/commands/client.c

This doesn't work, I'm not sure why. The color structs definitely get
changed but if you specify fewer than 5, it renders with the defaults.

Support specifying fewer than 5 colors

---

sway/sway-input.5.txt

Also, fix a small typo.
https://wayland.freedesktop.org/libinput/doc/latest/group__config.html#ga56c9886b0161ecdb9b351d8dedc212e4

Add missing send-event mode to sway-input(5)

---

CMakeLists.txt
common/log.c
common/stringop.c
common/util.c
sway/border.c
sway/commands.c
sway/commands/assign.c
sway/commands/set.c
sway/config.c
sway/criteria.c
sway/input.c
sway/main.c
sway/security.c
swaygrab/json.c
swaygrab/main.c

Increase _POSIX_SOURCE value for localtime_r access.
Increase _XOPEN_SOURCE value for lstat() and various printf() functions access.
Conditionally link to libcap (only on Linux).
Possibly some trailing whitespace fixes (automatic).

FreeBSD fixes

---

wayland/pango.c

It doesn't comlile with musl if you don't include it explicitly

include stdint to be compaitable with musl

---

swaybar/bar.c

Fixes child proccess killing, when status_command is a complex command
like "i3status | wrapper.sh".
Set the process group id of the child process by calling `setpgid` after
forking and before calling `exec`.
The process group ID will be set to the process ID of the forked
process. Processes spawned by this child process will also have this
group ID.
Send signals to the process group with `killpg`. This will send the
signal to all of the process group.

swaybar: Group child processes for signalling

---

swaybar/tray/icon.c

Handle getline failure in icon theme parsing

---

completions/zsh/_swaylock

There was a missing ' in _swaylock, prevents zsh from providing completion.

Fix zsh completion for _swaylock

---

swaybg/main.c

#895 is caused by unclear documentation, which this fixes.
EDIT: actually swaybg should probably also report problems loading the image
EDIT2: actually it already does, but cairo doesn't seem to fail loading when given a jpeg instead of a png
EDIT3: Made swaybg break if background image can't be loaded

Do not fail silently when background is not PNG

---

sway/commands/bind.c

The _bindsym_ command accesses the token list after it has been freed. This patch prepares the error message before freeing the list.

fix use-after-free bug

---

include/sway/input_state.h
sway/commands/move.c
sway/container.c
sway/handlers.c
sway/input_state.c

Uses Cloudef/wlc#274, which fixes the slow cursor movements not working.
I have tested this, but it wasn't intensive. I basically checked that the slow cursor thing was fixed, and that was about it.
Not a whole lot of code needed to change, so it's probably fine.

Use WLC v2 pointer interface

---

include/swaybar/tray/sni.h
swaybar/tray/sni.c
swaybar/tray/tray.c

If an item doesn't have a well-formed name, it will not be added to the
tray.

Don't trust SNI names, fixes #1274

---

swaybar/tray/sni_watcher.c

This commit also fixes a memory leak that occurs on failure.

Fix name validation in sni_watcher.c

---

swaybar/event_loop.c
swaybar/tray/dbus.c
swaybar/tray/sni.c
swaybar/tray/tray.c

These are a few memory leaks in the tray I found while on the plane. Of the leaks that seem to come from the tray, there is one that occurs on `swaybar/tray/sni.c:81` that I could not figure out, but that's it. There are also many leaks that come from pango calls, and a few in glib, but I did not have the resources to investigate and fix these.

Fix memory leaks in swaybar tray

---

CMakeLists.txt
swaybar/CMakeLists.txt

Swaybar's CMakeLists.txt uses the enable-tray option directly to decide whether to build the tray. This leads to a compilation error if dbus is not installed.
This patch uses the ENABLE_TRAY variable instead, which is only true if the user enabled the tray *and* dbus is available.

[swaybar] fix non-dbus build

---

sway/container.c

When killing views with `close_views` a use-after-free can sometimes
occur because parent views are killed before their children. This commit
makes `container_map` run functions on child containers before their
parent, fixing the race.
Fixes #1302

Prevent race condition in the kill command

---

sway/ipc-server.c

Added client write buffer and handler for writable status on client
socket.
Also fixes #892.

Implement nonblocking IO in IPC server

---

include/swaybar/bar.h
include/swaybar/status_line.h
swaybar/bar.c
swaybar/render.c
swaybar/status_line.c

Implementing click_events feature. Followed documentation at https://i3wm.org/docs/i3bar-protocol.html
Right, Left, Middle clicks on a status block trigger an event to be send to the standard input of status_command

click_events

---

swaygrab/main.c

https://github.com/SirCmpwn/sway/issues/1350 is fixed with this.
The commit that change swaygrab to use fork instead of Popen tried to
write to the read end of the pipe in the child branch and exec in the
parent branch.
It also didn't add "convert" for `arg[0]` of the child, which caused it to skip the first argument.
This commit fixes those and closes the write fd after writing,
so convert actually exits.

fixes a hanging swaygrab

---

swaybar/bar.c

i3 bar handles scroll events as button 4 and 5. An example use case would be volume up/down.
This probably has some effect on the "scrolling between workspaces" feature - now one probably has to put the pointer over the workspace buttons for it to work.

swaybar protocol: handle button 4 and 5

---

sway/commands/output.c
sway/config.c

Plugs memory leaks during failure of the output command and in other
circumstances and fixes `bg` option.
Fixes #1381
How outputs are applied is still buggy, but I decided to just focus on these changes now.

Clean up output command

---

sway/commands/move.c
sway/workspace.c

In two cases, the workspace name was cropped until the first space:
* when moving a container to a workspace
* when finding a suitable name for a workspace (by parsing the configuration file)
The `workspace xx` command is already behaving correctly but there might be some other instances of this error.

Fix two issues with spaces in workspace names

---

sway/config.c

I think it's safe to ignore dot files there.
What happened: sway crashed because I kept a file there, opened in vim (it creates a `.xxx.swp`).

Security config: skip hidden files

---

sway/commands.c
sway/criteria.c
sway/handlers.c
sway/ipc-json.c
sway/ipc-server.c

Fixes #1386 + other inconsistencies with i3's behavior.
The goal was to be able to use [focus-last.py](https://github.com/acrisci/i3ipc-python/blob/master/examples/focus-last.py) (and [my rust version](https://github.com/lbonn/i3-focus-last)) with sway. It seems to work now, if permissions are set up correctly.
The program is not that trivial and uses window events, `get_tree` and commands with criteria: this was a good way to test the ipc implementation.
Major highlight: 3 criteria missing in sway, taken from i3

ipc: various fixes for i3 compat

---

CMake/Manpage.cmake

This should make man pages install in correct place across platforms.

Change install folder for man pages

---

sway/config.c

Poking around with the output command with `swaymsg -t command output` I noticed a couple oddities with setting scaling on the fly.
Without this change, only the first output command would cause the scaling factor to change.  This change allows subsequent output commands to adjust scaling, as well as revert the scaling factor back to 1 (the default).
Tested by:

Fixes to changing scale factor with output command

---

CMakeLists.txt

Uses CMake's `add_compile_options` directive instead of interpolating  `CMAKE_C_FLAGS` for adding compilation flags.
Also, I have a question: why adding `-g` to all build types instead of recommending `RelWithDebInfo` (essentially `Release` with `-g`) as default?

Use add_compile_options instead of interpolation

---

sway/main.c

When the proprietary nvidia driver is used, ensure the modeset option is
set instead of checking /proc/cmdline for nvidia-drm.modeset=1.
Fixes: #1429

nvidia: Validate the nvidia_drm module options

---

.travis.yml
CMakeLists.txt

- Add `-DCMAKE_BUILD_TYPE=ASAN` to possible build types
I've found address sanitized builds to be super helpful for finding leaks etc.

Add Address Sanitized build type

---

swaybar/status_line.c

Trailing comma was violating JSON validity and caused issues with deserialization in different status_command implementations (eg. [i3status-rust](https://github.com/greshake/i3status-rust))

Removed trailing comma from swaybar click event json

---

include/swaybar/tray/tray.h

This fixes compilation failure:
error: call to function 'init_tray' without a real prototype

Fix init_tray function declaration

---

common/util.c
include/sway/server.h
sway/desktop/xdg_shell_v6.c
sway/server.c

A couple of trivial fix ; this should build with wlroots/master and remove the last need for wlc includes that I didn't have in a standard path.

Fix build with recent wlroots

---

sway/desktop/output.c

Should fix travis. I think we used this before to send surface callbacks.

remove unused timepsec func

---

include/sway/server.h
include/sway/view.h
sway/desktop/wl_shell.c
sway/meson.build
sway/server.c

Pretty much the same features as xdg_shell currently. Gives us a basis for improvement.
QT can be made to use wl_shell.
Will post this diff for testing again to make that work in case you missed it:
```diff
diff --git a/sway/server.c b/sway/server.c
index bf5c37e..e24b607 100644
--- a/sway/server.c
+++ b/sway/server.c
@@ -36,10 +36,12 @@ bool server_init(struct sway_server *server) {
wl_signal_add(&server->backend->events.output_remove,
&server->output_remove);
+	/*
server->xdg_shell_v6 = wlr_xdg_shell_v6_create(server->wl_display);
wl_signal_add(&server->xdg_shell_v6->events.new_surface,
&server->xdg_shell_v6_surface);
server->xdg_shell_v6_surface.notify = handle_xdg_shell_v6_surface;
+	*/
server->wl_shell = wlr_wl_shell_create(server->wl_display); …
```

basic wl_shell

---

sway/commands.c
sway/commands/exec.c
sway/commands/exec_always.c
sway/meson.build

Remaining TODOs to add to wlroots issue:
Test plan: `swaymsg exec gnome-dictionary`

Add exec and exec_always commands

---

swaylock/main.c

After a user enters or clears a password, try to overwrite the buffer containing it. That way it's not sitting around in RAM for something else to read later. Also, mlock() the password buffer so that it is never swapped out.
This also replaces the dynamically allocated buffer with a static char[1024]. Any characters past that are discarded until the user hits enter or escape.
I had to close #1513 because I opened it against the wrong base. This PR addresses your comments over there.
Regarding PAM zeroing-out the `strdup()`'d password: I figured that out with gdb. Here's a screenshot of my debug session:
I'm too lazy to set up debug symbols, and the Linux PAM code is really hard to follow, so I can't link to the exact line where the zeroing happens.
I also used the debugger to verify that …

Swaylock: Clear password buffer after use.

---

common/meson.build

It is required for include path if wlroots is not built in standard path,
but found through pkg-config

build: add wlroots dependency to common

---

sway/input/input-manager.c
sway/input/seat.c

Restore the code that used to be in config.c:apply_input_config() pre-wlroots.
Lines were very long in the original code, do we want to use the heavy rewrite as a chance to wrap these?

Libinput config

---

sway/handlers.c

this patch allow the user to type its password when a modal window is shown
while the desktop is locked by swaylock.
It is a partial fix of the bug since the window should not be visible (see bug
https://github.com/swaywm/sway/issues/1056 for details).

partial fix #1056

---

include/sway/config.h
sway/commands/output.c
sway/config/output.c
sway/tree/container.c

Test plan:
```
output "wayland wayland " scale 2
```

Allow to configure outputs by their identifier

---

sway/handlers.c

The initial problem that sparked #1507 was when I had views inside a container inside a tabbed container and could focus those views by clicking in their title bar region when the tab wasn't focused. This patch resolves that bug, but the issue remains open because there is a lot more to fix in those scenarios.

Patch #1507: Clicking on invisible title bars switches focus

---

sway/workspace.c

An allocated pointer was incremented before being freed in
`sway/workspace.c` which led to an invalid free. This has been fixed by
keeping the pointer in place and moving the data instead.
Fixes #1548

Prevent invalid free of workspace name

---

swaybar/bar.c

i3bar sends forward/back mouse buttons to the status command, so swaybar should too.

Handle forward/back mouse buttons in swaybar

---

swaybar/render.c

Skipping the rendering step altogether for empty blocks can result in those blocks having an x-position of 0, which causes all mouse events left of the status line to be sent to the leftmost block instead of the workspace buttons. This was happening with i3blocks (vivien/i3blocks#274), which for whatever reason always puts an empty block at the beginning of its status line.

Calculate positions of empty blocks in swaybar

---

include/sway/layout.h
include/sway/view.h
sway/desktop/output.c
sway/desktop/wl_shell.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/tree/container.c
sway/tree/layout.c

Render subsurfaces and popups.
Further work:
* make wl-shell transient windows floating

Subsurfaces and popups

---

include/sway/config.h
sway/config.c
sway/config/input.c
sway/config/seat.c
sway/input/input-manager.c
sway/input/seat.c

Don't hang onto copies of config pointers in the input manager or the seat.
For #1555.

Copy input config references

---

sway/focus.c

When you try to change the workspace with the mouse, upon mouse release event it will try focus on the OUTPUT 'WLC-1' handler for some reason, we just prevent it. Additionally it seems wlc_view_focus should be called with C_VIEW only.
[debug_log.c:98] Setting focus to 0x5649148455a0:1 (OUTPUT 'WLC-1')
[main.c:50] [wlc] compositor/view.c: 574 @ wlc_view_focus(): Tried to retrieve handle of wrong type (output != view)
[log.txt](https://github.com/swaywm/sway/files/1619627/log.txt)

Fix out of focus when using mouse to change workspace

---

include/sway/input/cursor.h
include/sway/input/input-manager.h
include/sway/input/seat.h
sway/commands.c
sway/commands/reload.c
sway/config.c
sway/input/cursor.c
sway/input/input-manager.c
sway/input/seat.c
sway/meson.build

This is actually pretty straightforward, and doesn't seem to leak anything.
I've tested:
- key bindings: added/removed/changed, no problem seen
- input config: changed some libinput config option without problem.
Not sure how the other options work, I'm not using them.
Note that when I open an urxvt before reloading, sometimes reloading will resize it, but I think this is working as intended as it's called arrange_windows(). I'm not sure why it doesn't happen everytime, but I'm not going to look at window placements right now as there is nothing done there (is there?)
I've also had the choice of commenting out load_swaybars() in commands or adding a stub in config.c and decided to add a stub, happy to go the other way, but we'll probably want that function eventually.

commands: add 'reload' command

---

common/readline.c
sway/handlers.c
sway/ipc-server.c

- `read_line`: OOB write when a line in `/proc/modules` contains a
terminating character at `size` position.
- `handle_view_created`: Ensure that the `list_t` returned by `criteria_for`
is `free`'d after use
- `ipc_event_binding_keyboard`/`ipc_event_binding`: Properly handle
`json_object` reference counting and ownership.

Fix memory errors

---

common/util.c
sway/commands/split.c
sway/workspace.c

- `get_parent_pid`: free buffer returned from `read_line` after use.
- `workspace_for_pid`: ensure `free_pid_workspace` is called when
`pid_workspace`s are removed from `config->pid_workspaces`.
- `cmd_split`: return the `cmd_results` from `_do_split`, so that the
parent function may free it.

Fix more leaks

---

swaybg/main.c

Mirrors a similar check in `swaylock/main.c`

Fix segfault if swaybg is run without Wayland

---

include/log.h
include/sway/commands.h
include/sway/container.h
include/sway/input/input-manager.h
include/sway/input/seat.h
include/sway/layout.h
include/sway/output.h
include/sway/server.h
include/sway/workspace.h
meson.build
sway/commands.c
sway/commands/exit.c
sway/commands/focus.c
sway/commands/kill.c
sway/commands/layout.c
sway/commands/reload.c
sway/commands/set.c
sway/commands/workspace.c
sway/desktop/output.c
sway/desktop/xdg_shell_v6.c
sway/input/input-manager.c
sway/input/keyboard.c
sway/input/seat.c
sway/ipc-json.c
sway/ipc-server.c
sway/meson.build
sway/server.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/workspace.c

Changes:
No new features added or bugs fixed, just refactoring changes.
* Keep an up-to-date list of all the containers of the seat in focus order
* Add `sway_seat_get_focus` to get the "focus inactive" of the container (returns true focus if the seat has focus and container is the root)
* Add `sway_seat_container` to store seat-specific data about a container (here, the focus stack list link and destroy handler).
Features:
Tests:
Hard problems:
Test config:
```
bindsym Alt+h focus left
bindsym Alt+j focus down
bindsym Alt+k focus up
bindsym Alt+l focus right
bindsym Alt+z layout splith
bindsym Alt+x layout splitv
bindsym Alt+c layout toggle split
```
Feedback on the approach is welcome.

focus overhaul

---

.travis.yml

Adds the docker service in travis which is now required by arch-travis.
See: https://github.com/mikkeloscar/arch-travis/pull/40

Enable docker service in travis

---

sway/desktop/xwayland.c

The code in `apply_horiz_layout` systematically does `set_position`
then `set_size`, so for new windows there is an invalid call.
For old windows there are two calls when only one is needed,
with the current code set_position could not send any surface
configure without impact, but in the future it might be needed?
Native wayland surfaces do not need to know where they are (the
set_position handled only updates the sway internal view variable),
why does X11 window need that?

xwayland: do not send surface configure when no width/height

---

.gitignore
meson.build

Usage: make `subprojects/wlroots` a symbolic link to wlroots.
This allows to edit and build sway and wlroots at the same time. This can be useful for features like multibackend.

meson: allow wlroots to be a subproject

---

include/swaybar/status_line.h
swaybar/render.c
swaybar/status_line.c

swaybar: correctly render min_width for strings

---

common/log.c

was fiddling around with the logging to make it a bit more convenient to debug
and noticed a small mistake with `sway_log_errno`, as `errno` can get overwritten before we use it.
its been a while since i contributed, but i assume 0.15 is where development is going for now

save errno to avoid issues with it being overwritten in sway_log_errno

---

sway/commands.c
sway/container.c
sway/debug_log.c

Fixes #1468 `Scratchpad show then floating toggle crashes sway.`
Could not reproduce with original instructions,
but can reproduce with instructions provided by nickbatsaras
1. Move a window to scratchpad
2. Move another window to scratchpad
3. Scratchpad show
4. Floating toggle
5. Scratchpad show
6. Scratchpad show
The first sign of the issue starts at step 4.
Given a scratchpad with 2 windows (1,2), with window 1 being a visible container,
turning off floating via `toggle floating` will call `remove_view_from_scratchpad`.
this function was incorrect and resulted in removing window 2,
leaving window 1 in the scratchpad when it shouldnt be and losing window 2 permanently.
the segfault was later caused in update_visibility_output due to window 1 having a NULL parent and dereferencing it. …

fix remove_view_from_scratchpad

---

sway/desktop/xwayland.c

Test plan:
1. Run sway, open a window on ws 1
2. Switch to ws 2
3. Open a xwayland window, observe it being added to ws 2

Add xwayland views to focused container

---

include/sway/tree/container.h
include/sway/tree/layout.h
include/sway/tree/workspace.h
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/ipc-json.c
sway/ipc-server.c
sway/meson.build
sway/tree/container.c
sway/tree/layout.c
sway/tree/output.c
sway/tree/view.c
sway/tree/workspace.c

Fixes:
- Move from empty workspace to an adjacent output without destroying that workspace
- Destroy empty (off-screen) workspace when last view is removed from it
- Move some container functions into type-specific files

Fix workspace deletion edge cases

---

sway/input/cursor.c
sway/ipc-server.c

To test, add this at the end of `cursor_send_pointer_motion`:
```c
static struct sway_container *old = NULL;
if (old != swayc) {
wlr_log(L_DEBUG, "focus change: %p", swayc);
}
old = swayc;
```
Test plan: open a window on a workspace, switch to an empty workspace. Pointer events shouldn't be sent to the window on the hidden workspace.

Fix pointer events for hidden workspaces

---

sway/input/cursor.c

Make it clear that unmanaged views don't have a container

---

sway/desktop/layer_shell.c
sway/tree/layout.c

Test plan: open two outputs on the X11 backend, close them.

Fix two segfaults when destroying outputs

---

include/sway/config.h
include/sway/input/seat.h
sway/commands.c
sway/commands/focus_follows_mouse.c
sway/commands/mouse_warping.c
sway/config.c
sway/input/cursor.c
sway/input/seat.c
sway/meson.build

Superceeds #1680, #1683 
Test plan:
- `mouse_warping output` (default) should make the mouse follow the focused output.
- `mouse_warping none` should not warp the mouse at all.
- `focus_follows_mouse yes` (default) should move focus as the mouse moves over new views/containers
- `focus_follows_mouse no` should not move focus as the mouse moves over new views/containers
- Should not break when mouse is moved over popups, layers, etc

Implement focus_follows_mouse, mouse_warping

---

include/sway/output.h
include/sway/tree/container.h
include/sway/tree/layout.h
sway/commands.c
sway/commands/focus.c
sway/commands/move.c
sway/desktop/output.c
sway/input/keyboard.c
sway/meson.build
sway/tree/container.c
sway/tree/layout.c
sway/tree/output.c

Works:
- move [container|window] to workspace <name>
- Note, this should be able to move C_CONTAINER but this is untested
- move [workspace] to output [left|right|up|down|<name>]
Not implemented yet:
- move [left|right|up|down]
- move scratchpad
- move position

Partially implement move command

---

sway/tree/workspace.c

Due to a missing assignment, the name of the active container is saved for workspace back-and-forth instead of the name of the workspace. For an empty workspace, the active container is the workspace. However, for a non-empty workspace, it will be a descendant of the workspace.
This PR makes a single line fix to add that missing assignment so that the name of the workspace is stored in both cases.
0. Recommended Prerequisite
- Add a binding for `workspace back-and-forth` to the sway config
1. Switching from an empty workspace
- Switch to workspace 2
- Switch to workspace 1
- Switch to workspace back-and-forth
- Look at either swaybar and/or the output of `swaymsg -t get_workspaces` and verify that the active workspace is `2`
2. Switching from a non-empty workspace
- Switch to workspace 2 …

Fix back-and-forth workspace name saving for non-empty workspaces

---

common/pango.c
include/swaybar/ipc.h
include/swaybar/status_line.h
sway/tree/layout.c
swaybar/bar.c
swaybar/i3bar.c
swaybar/ipc.c
swaybar/meson.build
swaybar/render.c
swaybar/status_line.c

Test plan:
```
bar {
status_command i3status
}
```
Bonus: test click events by running the bar manually with `-d` and it'll log each block that's clicked.

I3bar json

---

include/sway/config.h
include/sway/input/input-manager.h
include/sway/input/seat.h
sway/commands.c
sway/commands/focus.c
sway/commands/seat.c
sway/commands/workspace.c
sway/config.c
sway/desktop/output.c
sway/desktop/wl_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/input-manager.c
sway/input/keyboard.c
sway/input/seat.c
sway/ipc-json.c
sway/ipc-server.c
sway/server.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/workspace.c

* take `sway_` prefix off of seat and input manager functions for consistency.
* dont copy seat config on the seat
* dont copy input device config on the input device
* general cleanups and refactorings
No changes in functionality, just code cleanup.
see `sway-input.5.txt`
example:
```
seat seat1 {
fallback true
}
seat seat0 {
attach '9494:39:CM_Storm_Coolermaster_Novatouch_TKL'
attach '1267:12306:ELAN1010:00_04F3:3012_Touchpad' 
}
input '1267:12306:ELAN1010:00_04F3:3012_Touchpad' {
}
input '9494:39:CM_Storm_Coolermaster_Novatouch_TKL' {
xkb_layout de
}
```

Seat fixes and cleanup

---

sway/tree/workspace.c

A workspace name is generated by looking at the bindings and finding the first workspace command with an unused workspace name. When a command of the form `workspace number <name>` is found, the generated name is `number <name>`.
This PR isolates the `<name>` portion. Additionally, there is a check added to make sure that a workspace with that number does not already exist.
1. Either use the minimal config below or add bindings for the following before any others in the sway config
- `workspace number 1:First`
- `workspace number 1:ThisShouldBeSkipped`
- `workspace number 2:Second`
2. Run sway with two outputs using the command `env WLR_X11_OUTPUTS=2 sway -d -c <path-to-config>`
3. Look at swaybar and/or `swaymsg -t get_workspaces` and verify that the workspace names in use are `1:First` …

Fix name generation from workspace number commands

---

include/swaybar/bar.h
swaybar/bar.c
swaybar/render.c

Fixes https://github.com/swaywm/sway/issues/1137
Ref https://github.com/swaywm/sway/issues/797

Add hidpi support to swaybar

---

include/sway/tree/view.h
sway/desktop/wl_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/tree/view.c

This removes per-shell `sway_*_surface` and replaces them with `sway_*_view` which are more in line with the impl pattern. I believe this also fixes #1738.

Implement shell views

---

include/sway/desktop.h
include/sway/output.h
include/sway/tree/container.h
include/sway/tree/view.h
sway/desktop/desktop.c
sway/desktop/output.c
sway/desktop/wl_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/meson.build
sway/tree/container.c
sway/tree/view.c

Test plan: make sure damage is accumulated when view children commit.
* Add `wlr_log(L_DEBUG, "child damaged");` in `view.c` on line 231
* Add `wlr_log(L_DEBUG, "unmanaged surface damaged");` in `xwayland.c` on line 32
Check that these appear in the log when opening a popup and a combo in `gnome-calculator`, under xdg-shell and xwayland.

Damage tracking for view children

---

sway/ipc-json.c
sway/ipc-server.c

Make the containers have the "layout" in ipc json for tests.
[layout tests](https://github.com/swaywm/sway-tests/blob/master/test/test_layout.py)
Will also be added to move tests.
Also don't send container json if no listeners are subscribed to the event.

ipc layout

---

swaybar/render.c

Problem: clicking on swaybar workspace hotspot creates new workspace if `strip_workspace_numers` is enabled. Reason is wrong name in hotspot callback.
Example config subset:
```
set $ws1 "1:&#x3B1;"
set $ws2 "2:&#x3B2;"
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bar {
strip_workspace_numbers yes
}
```

Use full ws->name in swaybar hotspot callback

---

sway/commands.c
sway/commands/ws_auto_back_and_forth.c
sway/meson.build

This is the only missing piece - other code regarding this functionality has
already been ported from pre-wlroots source.

Add workspace_auto_back_and_forth command

---

README.de.md

This PR fixes some minor typographic character issues in the German README file.
Some argumentation for these changes:
* "sway"-Paket → „sway“-Paket
https://de.wikipedia.org/wiki/Anf%C3%BChrungszeichen#Deutschland_und_%C3%96sterreich
* e-Mail → E‑Mail
https://de.wikipedia.org/wiki/Gesch%C3%BCtzter_Bindestrich

Fix some typographic characters in German README

---

swaybar/i3bar.c

This PR fixes a null termination issue and two dangling pointers.
The string that read() returns is not null terminated, so the `while (*cur)` loop could run into garbage data. In all my testing this has sometimes resulted in a "failed to parse i3bar json" message, and sometimes an infinite loop where swaybar pegs the CPU and nothing is displayed (or updated) in the status line part of the bar.
To prevent this I'm setting the null byte manually.
To test, run swaybar with a status command several times. Without my PR one of the above symptoms occurs about once in every 5 launches. With my PR it should not display the parse error message nor become unresponsive at all.
When increasing the buffer size, `cur` and `state->current_node` need to be updated accordingly as these point into the old …

Fix buffer issues in swaybar status line

---

swaybar/ipc.c

Swap return with break in IPC_EVENT_WORKSPACE case to free resp.
Change default return value to true. This causes IPC_EVENT_MODE changes to be
rendered instantly.

fix swaybar ipc handling

---

swaybar/render.c

Fixes #1790.
When rendering a non-edge block, swaybar's render_status_block() was miscalculating the height needed for the separator and was returning early, expecting itself to be called again later with a new surface height.
I've redone the logic here, as well as renamed _height to sep_height.
In addition to this, the separator symbol was not positioned correctly vertically.
For anyone checking my logic, my understanding is:
* `height` is the bar height with scaling applied
* `sep_height` and `_ideal_height` are both without scaling
* The function expects the return value to be without scaling
I've tested with output scales of 0.5, 1 and 2, and the pipe character as the separator symbol.

Fix swaybar not showing all status blocks

---

include/swaylock/swaylock.h
swaylock/main.c
swaylock/password.c

- Replace char* with static array. Any chars > 1024 will be discarded.
- mlock() password buffer so it can't be written to swap.
- Clear password buffer after auth succeeds or fails.
This is basically the same treatment I gave the 0.15 branch in https://github.com/swaywm/sway/pull/1519

swaylock: Securely zero-out password.

---

sway/desktop/xwayland.c

Update for https://github.com/swaywm/wlroots/pull/866

Do not call the map handler when an xwayland surface is created

---

protocols/meson.build

Same as for wlroots - autodetect version and use either 'code' or the
new one

Use 'private-code' for wayland-scanner code generation

---

common/ipc-client.c
sway/commands.c
sway/commands/exec_always.c
sway/ipc-server.c
sway/tree/layout.c

Similar to wlroots as well, some string truncations
* the -1s are harmless since we manually force the final \0 all the time;
* the strncpy->strcpy is because we based the strncpy on the source length and gcc complained that we never wrote the final \0 then when adding 1 that `strncpy(dst, src, strlen(str)+1)` is useless..........
and another maybe-uninitialized variable

Fix gcc warnings

---

sway/server.c

This fixes an issue with direct sessions not shutting down properly, reported by ponky on IRC.

Destroy display in server_fini

---

include/sway/ipc-server.h
include/sway/tree/container.h
include/sway/tree/view.h
include/sway/tree/workspace.h
sway/commands.c
sway/commands/fullscreen.c
sway/desktop/output.c
sway/desktop/wl_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/seat.c
sway/meson.build
sway/tree/container.c
sway/tree/layout.c
sway/tree/view.c
sway/tree/workspace.c

This implements `fullscreen enable`, `fullscreen disable`, `fullscreen toggle`, and allows views to request fullscreen.
This is my first significant PR for sway and I've had to learn a lot about how everything works, so please scrutinise this carefully.
Note that sway 0.15 allows the command `fullscreen` without any arguments which acts as toggle, but this is different to the i3 user guide so I've implemented it as described above. As a result, if you're porting config from sway 0.15 you may need to update your command to be `fullscreen toggle`.
wl_shell seems a bit lacking with its fullscreen ability, and from what I understand wl_shell is deprecated anyway, so I've not implemented fullscreen for that. If someone could confirm then that'd be appreciated.
There is one known issue, and …

Implement fullscreen

---

sway/tree/layout.c

`container_handle_fullscreen_reparent()` must be called *after* setting the container's new parent.
To test:
* Fullscreen a view, then move the view to another workspace, then switch to that workspace - the view should be fullscreen.

Keep view fullscreened when moving to another workspace

---

sway/input/cursor.c
sway/input/seat.c

Not only this updates the cursor image, but this also (and more importantly) sends pointer enter/leave events.

Update cursor when workspace focus changes

---

swaybar/bar.c
swaybar/event_loop.c

Remove status command fd from event loop on error.
This prevents poll constantly looping on POLLHUP if the status command dies, causing 100% CPU usage.

Swaybar fix

---

sway/desktop/output.c

This makes Chromium context menus appear when fullscreen.
Fixes an item on #1828.
Question: This will render all unmanaged xwayland views, even if it doesn't belong to the fullscreen view. Do I need to worry about this, and if so how do I filter them?
To test:
* Launch Chromium, fullscreen it, then right click on the page or open the context menu in the top right.

Render unmanaged xwayland views when an xwayland view is fullscreen

---

include/sway/commands.h
sway/commands.c
sway/commands/rename.c
sway/meson.build

This implements the following commands:
* `rename workspace to new_name`
* `rename workspace old_name to new_name`
* `rename workspace number n to new_name`
General tests:
* `swaymsg rename workspace to foo`
* `swaymsg rename workspace to foo bar`
* `swaymsg rename workspace foo to bar`
* `swaymsg rename workspace foo bar to bar`
* `swaymsg rename workspace number 1 to foo`
* `swaymsg rename workspace number 1: foo to bar`
Failure handling tests:
* `swaymsg rename workspace`
* `swaymsg rename workspace to`
* `swaymsg rename workspace foo to`
* `swaymsg rename workspace foo to foo` (same name)
* `swaymsg rename workspace foo to bar` (where bar already exists)

Implement rename workspace command

---

include/swaybar/bar.h
include/swaybar/config.h
include/swaybar/status_line.h
swaybar/bar.c
swaybar/config.c
swaybar/i3bar.c
swaybar/ipc.c
swaybar/status_line.c

There are more leaks from fontconfig and cairo. I guess we can't do anything about it.

Fix a bunch of swaybar memory leaks

---

include/sway/tree/container.h
include/sway/tree/layout.h
sway/commands/layout.c
sway/ipc-json.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/workspace.c

Resolves #1716.
The `container_set_layout()` function turned into a single `container->layout` assignment, so I opted to remove the function completely.

Remove sway_container.workspace_layout

---

include/sway/tree/arrange.h
include/sway/tree/container.h
include/sway/tree/layout.h
include/sway/tree/view.h
sway/commands/layout.c
sway/commands/reload.c
sway/commands/resize.c
sway/commands/split.c
sway/desktop/layer_shell.c
sway/desktop/output.c
sway/input/seat.c
sway/meson.build
sway/tree/arrange.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/view.c
sway/tree/workspace.c

The arrange_windows() function hurts my brain. Here's a refactor for your consideration.
* I've split `arrange_windows()` into a function for each container type. So you can call `arrange_root()`, `arrange_output(output)`, `arrange_workspace(workspace)` or `arrange_children_of(workspace_or_container)`. Each one iterates its children and recurses as needed.
* For convenience, if you don't know what type of container you're dealing with and just want it to work, you can pass it to `arrange_windows(whatever)` and it'll figure it out.
* Because there's now several more functions related to arranging, I've moved this out of layout.c and into a new file.
* Passing -1, -1 to the function is now unnecessary, as it gets it from the provided parent and updates the child's dimensions before …

Refactor arrange_windows()

---

include/sway/tree/arrange.h
sway/tree/arrange.c

After the refactor, this function is no longer called.

Remove arrange_windows()

---

sway/tree/view.c

If the last remaining view on a workspace is unmapped and the workspace is not visible, parent will be a C_OUTPUT. Call the arrange_output() function in this case.
To test:
* Launch a terminal
* Within that terminal, run something like `urxvt -e sleep 5`
* Move the new terminal window to a new workspace
* Ensure the workspace is not visible at the time the sleep command finishes

Fix segfault in view_unmap()

---

sway/config/output.c
sway/desktop/layer_shell.c
sway/tree/container.c

Before freeing sway_output, NULL the wlr_output reference to it. Check for that
NULL in layer_shell handle_destroy. Don't damage null container in unmap.
Additionaly, terminate swaybg if its output is being disabled.
Fixes #1877 segfaults, but reenabling output still doesn't work.

Fix layer surface segfault on output destroy

---

sway/commands/client.c
sway/desktop/output.c

The alpha component is merged with the container's opacity.
Fixes #1882
In this example, the title background uses about 25% alpha:
`client.focused          #ff0000 #00ff0040 #ffffff #2e9ef4   #0000ff`
Launch a terminal, run `swaymsg opacity 0.5` and it'll adjust accordingly.

Support alpha in border colours

---

sway/tree/view.c

This is a fix for: #1888 
Sway wouldn't compile on Archlinux due to uninitialized variables.
For the record, these build flags are passed automatically to GCC on Archlinux in makepkg:
```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
CPPFLAGS="-D_FORTIFY_SOURCE=2"
```
Note that I don't have a lot of experience in C so please let me know if this is not the way it should be fixed.

Fixed #1888 GCC cannot compile due to uninitialized variables

---

sway/input/cursor.c
sway/input/seat.c

This required changing container_at_cursor to container_at_coords so
that we could get the appropriate surface (and sx/xy) without moving the
cursor.
Future work:
- Simulate a pointer for clients which have not bound to wl_touch
- With long-press to right click
- Keep sending motion events when moving outside the surface (#1892)
- Bind gestures to sway commands

Implement basic touch support

---

sway/input/seat.c

Test plan: rotate the output on the Wayland or X11 backend.

Default to backend-wise input device mapping, if any

---

sway/desktop/output.c
sway/tree/arrange.c
sway/tree/container.c

This allows the title's texture to always be the full width of the text, and clipped at render time according to the desired width (eg. tabs...).
As an added bonus, the texture no longer needs to be updated when containers are arranged.

Use scissor to render title texture

---

include/sway/commands.h
include/sway/config.h
include/sway/tree/container.h
include/sway/tree/view.h
sway/commands.c
sway/commands/font.c
sway/commands/title_format.c
sway/config.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/meson.build
sway/tree/container.c
sway/tree/view.c

This implements the `title_format` command, with a new placeholder `%shell` which gets substituted with the view type (xwayland, xdg_shell_v6 or wl_shell).
Example config:
for_window [title=".*"] title_format %title (class=%class instance=%instance shell=%shell)
You can change the title using swaymsg:
$ swaymsg title_format %title
Some implementation notes:
* container_update_title() has been renamed to view_update_title() and moved into view.c as it only applies to views.
* Because of the above, container_notify_child_title_changed() is now public.
* The arguments of view_update_title() have changed. It used to have the title given to it via an argument; now it reads it from view_get_title().
* Containers now have both a `name` and `formatted_title` property. The `name` is used purely …

Implement title_format

---

include/sway/config.h
sway/commands/font.c
sway/tree/container.c

Implements support for the `pango:` prefix in the font command.
Also fixes a missing `free()` in the font command.
Closes #1903.
Merge after #1915 (Implement title_format).
Example config:
font pango:DejaVu Sans 10
for_window [title=".*"] title_format <b>%title</b>

Implement pango support

---

meson.build
meson_options.txt
security.d/00-defaults.in
sway/commands/exec_always.c
swaybar/meson.build
swaybg/meson.build

1.) has an unneeded / in meson.build which causes the PATH env variable to have an incorrectly appended libexec directory for sway
2.) breaks launching swaybar and swaybg at startup with a message "sh: swaybar[/bg]: command not found"

Revert PR #1881

---

swaybar/render.c

Makes swaybar respect the user's `pango_markup` configuration in the workspace buttons and binding mode indicator.

Swaybar: Respect pango_markup config

---

sway/desktop/output.c

If the output is rotated, the scissor box needs to be transformed in the opposite rotation.
To test, launch with an output with a 90 degree rotation and open a view on that output. Before the fix, the title isn't shown.

Fix titles on rotated outputs

---

sway/server.c

If the backend fails to be created, log an error and immidiately return
from server_init.

Fix null deref in server_init

---

sway/config.c

Fixes #1949 
When your config lacks a `font` directive, the font height was being set to 0 and it wasn't being recalculated. This sets the default to 17, which is the font height for `monospace 10` as defined on the line above.

Use reasonable default for font height

---

include/sway/output.h
include/sway/tree/view.h
sway/desktop/output.c
sway/desktop/wl_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/seat.c
sway/tree/container.c
sway/tree/view.c

Uses scissors for now, will improve this in the future.

Implement full damage tracking

---

sway/desktop/output.c
sway/input/seat.c

This adds a `bool parent_focused` argument to some of the `render_container` functions which gets passed down through the children and allows them to be rendered with focused colours.
To test, create a mix of horizontal and vertical layouts and run `focus parent`.

Highlight all child borders when using focus parent

---

sway/commands/default_border.c

In Sway 0.15, `default_border normal 1` would set 1px wide borders. This recreates that behavior.

Allow setting border widths for normal borders using default_border.

---

sway/commands/move.c

In Sway 0.15, moving a window to another workspace would cause a window on the source workspace to be focused. This restores that behavior, allowing you to quickly move a lot of windows to another workspace.

cmd_move_container: Focus a window on the source workspace.

---

include/sway/criteria.h
include/sway/tree/view.h
sway/commands.c
sway/commands/assign.c
sway/commands/for_window.c
sway/criteria.c
sway/desktop/wl_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/sway.5.txt
sway/tree/view.c

This builds off PR #1928 which I submitted several days ago, then decided to close in favour of overhauling the criteria system completely.
The criteria struct now uses **properties for each token type** rather than the list_t list of tokens. The reason for this is that different token types have different data types: pcre, string and number to name a few. Tokens like urgent and window_type are enum-ish too. A bonus of this is that criteria is now easier to understand when looking at the struct definition.
The criteria **parser has been rewritten** because the previous one didn't support valueless pairs (eg. `[class="foo" floating]`).
Criteria now has **types**. Types at the moment are `CT_COMMAND`, `CT_ASSIGN_WORKSPACE` and `CT_ASSIGN_OUTPUT`. i3 uses types as well. Previously the assign …

Overhaul criteria implementation

---

include/sway/tree/view.h
sway/criteria.c
sway/tree/view.c

Merge after #1943.
This adds support for the `__focused__` keyword in criteria values.
To avoid excessive use of `strcmp`, I've added a `criteria_token` enum.

Implement __focused__ criteria

---

sway/tree/view.c

Currently, attempting to fullscreen while the window is inactive will crash Sway. This fixes that.

fix crash on fullscreen toggle

---

include/sway/tree/view.h
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c

The current code prevents an unmapped xdg-popup from being re-mapped again.
This PR also removes an extraneous `if (surface is unmapped)` check on destroy: unmap is guaranteed to always be triggered before destroy.

Don't destroy view child on xdg-popup unmap

---

common/pango.c
include/pango.h
sway/tree/view.c

The characters & < > ' " needs to be escaped when using pango markup
Signed-off-by: Heghedus Razvan <heghedus.razvan@protonmail.com>

Fix crash when using pango markup font

---

common/pango.c

The condition checking if the markup is valid was inverted.
This commit also adds better error handling: if the markup cannot
be parsed, it fallbacks to plain text.

Fix pango markup

---

include/sway/criteria.h
include/sway/tree/view.h
sway/commands.c
sway/commands/assign.c
sway/commands/for_window.c
sway/criteria.c
sway/desktop/wl_shell.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/tree/view.c

This restores the criteria implementation (after SirCmpwn's revert) and fixes the issue described in #1966. The fix is in a separate commit from the reverts for easy reviewing.
The config used in that issue uses string values for `id` which triggers errors. The caller frees the error, and when the criteria is parsed a second time it attempted to free the error again, causing the crash.

Fix double free in criteria

---

include/sway/config.h
include/sway/tree/view.h
sway/commands.c
sway/commands/mark.c
sway/commands/unmark.c
sway/criteria.c
sway/meson.build
sway/tree/view.c

This implements the `mark` and `unmark` commands, including the `--add`, `--replace` and `--toggle` arguments for the `mark` command, and also implements mark matching in criteria.
To test, run a variety of these commands:
* `swaymsg mark foo` (replaces any existing marks on this view with `foo`)
* `swaymsg 'mark --add bar'` (will append `bar` to view's marks list)
* `swaymsg [con_mark="foo"] opacity 0.9`
* `swaymsg [con_mark="foo"] mark bar`
* `swaymsg 'mark --add --toggle bar'` (keep existing marks list and toggle `bar`)
Try to break it:
* `swaymsg mark`
* `swaymsg 'mark --add'`
* `swaymsg 'mark --asdf'`
Note that single quotes are required when using `--add` and friends, otherwise your shell may interpret them.
There's no easy well to get a view's marks (`show_marks` is not yet …

Implement marks

---

sway/desktop/output.c

Test plan: set output config to `scale 1.5 transform 90`, check that the texture stops right before the border.
Fixes #1983

Correctly clip title texture if necessary

---

include/sway/server.h
sway/main.c
sway/server.c

Xwayland is lazy now, there is no need to wait at all
Test plan: Try to add stuff to your .sway/config as 'exec' statements to run at startup, see nothing fails unexpectedly because we didn't wait enough.
(works for me: X11 app (urxvt), swayidle, swaylock)

sway: run commands without waiting for Xwayland

---

sway/tree/view.c

Fixes #1989
When a view changes its title, it executes its criteria and must focus the view in question temporarily. It would then incorrectly restore focus to whatever view was focused_inactive on that workspace. I'm not sure why the code does anything with the workspace - it was copied from sway 0.15.

Don't steal focus when a view changes its title

---

common/pango.c
include/pango.h

Since `pango_attr_scale_new` takes a `double`, this PR changes the pango-related function signatures from `int32_t scale` to `double scale` to allow for fractional scaling of text.
Fixes #1985

Change scale from int32_t to double for pango

---

include/sway/tree/view.h
sway/commands.c
sway/commands/mark.c
sway/commands/show_marks.c
sway/commands/unmark.c
sway/desktop/output.c
sway/meson.build
sway/sway.5.scd
sway/tree/container.c
sway/tree/view.c

The implementation is similar to titles: store a texture for each focus class.
Tests:
* Run `show_marks yes` and `show_marks no` in both config and swaymsg
* `swaymsg mark foo`
* Test with scaled outputs (I've already done this but doesn't hurt to double check)
If the title is long enough to intersect the mark then the mark is drawn on top. However, I've noticed an unrelated bug where the title isn't scissored properly and renders into the right side border if it's long enough. This makes a few pixels of it appear to the right of the mark which looks bad. I won't fix that as part of this PR because it's a separate issue.

Implement show_marks

---

include/sway/tree/container.h
sway/tree/container.c

When moving a container to an output which has a different scale than the previous, rebuild the title and marks textures at the new scale.
Fixes #1999.
To test:
* Have two outputs at different scales
* Mark a container with `swaymsg mark foo`
* Move the container between the outputs, using both `mod+shift+<direction>`, as well as `mod+shift+<workspace-number>`

Rebuild textures if needed when moving a container

---

sway/desktop/output.c

This commit changes how the left and right indents are calculated for the
title bottom pixel bar, so that it is displayed properly in case the left or
right border is hidden.

Fix pixel bar below title

---

include/sway/input/cursor.h
sway/commands/border.c
sway/commands/seat/cursor.c
sway/input/cursor.c
sway/input/seat.c

Fixes #1951 
This allows the border commands to update the cursor without having the side effect of `focus_follows_mouse` changing the focus. All other calls to `cursor_send_pointer_motion` currently allow refocusing (no change) so `focus_follows_mouse` should continue to work as expected.

Fix border commands from changing focus

---

sway/tree/arrange.c

Fixes #2023.
To test:
* Create a tabbed container with some views.
* Focus one of the views and run `splith` or`splitv`.
* Run `layout tabbed` (the tree should now be something like `T[view, view, T[view]]`)
* The title bar of the nested view should sit below the outer tab bar, rather than on top of it.
I also combined two functions which were identical.

Fix nested tabs

---

sway/tree/layout.c

Fixes #2026.
To test, run something like `move workspace to output left`.

Fix crash in move workspace to output command

---

sway/tree/layout.c

When moving focus left or right to an adjacent output, only select the first or last child in the new workspace if the workspace's layout is horizontalish. If it's a verticalish layout, use the last focused container.
To test:
* Have two outputs.
* On the left output, create two or more views in a vertical layout. Ensure the views are direct children of the workspace (eg. by creating two views then moving one of them down).
* Focus the topmost view.
* `focus right` to move focus to the right output (it doesn't matter if the right output is empty or has views).
* `focus left` to move back to the left output.
* Prior to the fix, sway would focus the bottom child in the left output. Because the layout is perpendicular to the movement direction, It should focus the last active child instead.

Fix focus bug when moving between outputs

---

common/stringop.c
include/stringop.h
include/sway/tree/container.h
sway/commands/layout.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/view.c

This is mostly a code cleanup PR. The only functional change is fixing a minor bug (5th bullet point).
* Add and use `lenient_strcat` and `lenient_strncat` functions
* Rename `concatenate_child_titles` function as that's no longer what it does
* Rename `container_notify_child_title_changed` because we only need to notify that the tree structure has changed, not titles
* Don't notify parents when a child changes its title
* Update ancestor titles when changing a container's layout
* Eg. create nested tabs and change the inner container to stacking
* No need to store tree presentation in both `container->name` and `container->formatted_title`

Clean up container title functions

---

sway/tree/layout.c

Fixes #2029.
To test:
* Created a tabbed layout with some views
* Focus a view and run `splitv` or `splith` (tree should be something like `T[view, view, V[view]]`)
* Run `move left` (tree should be `T[view, view, view]`)
Before the PR, the view would be offset from the title bar until the tabbed container is next arranged. After the PR, it shows correctly as a regular tab.

Arrange views after flattening the parent

---

sway/tree/view.c

Fixes #1879.
Have something like this in your config:
assign [class="Firefox"] web
workspace web output X11-2
Then launch sway with two outputs, focus output X11-1, and launch Firefox. The web workspace will be created on X11-2, Firefox will be created there and focused, the IPC workspace event will be sent, but Firefox wouldn't actually render because you hadn't switched to the workspace.

Switch workspace if required when mapping a view

---

sway/tree/view.c

If we have `%class` and `%instance` we should probably have `%app_id` too. Makes it easier to write criteria.

Add %app_id to title_format

---

include/swaylock/swaylock.h
swaylock/main.c
swaylock/password.c
swaylock/render.c

This is an attempt to fix #2031. I cannot reproduce this issue, so please test.
If I typed too fast, I experienced tearing. This PR fixes it by implementing a proper render loop.

swaylock: implement a proper render loop

---

sway/desktop/xdg_shell.c

Depends on https://github.com/swaywm/wlroots/pull/1007
Fixes #1988

xdg-shell: make all toplevels tiled

---

include/sway/config.h
sway/commands/bind.c
sway/input/keyboard.c
sway/sway.5.scd

Adds the --locked flag to bindsym and bindcode commands.
When a keyboard's associated seat has an exclusive client
(i.e, a screenlocker), then bindings are only executed if
they have the locked flag. When there is no such client,
this restriction is lifted.
-------
This should resolve #592. As my development system only has one screen, I haven't 
tested e.g. how this will interact with seat or keyboard additions while a screenlocker
is active, or with multiple screens. Example usage:
bindsym --locked XF86AudioMute exec amixer sset Master toggle
bindsym XF86AudioMicMute exec  amixer sset Capture toggle

Implement bindsym/bindcode --locked

---

sway/tree/container.c

This sends the `workspace::move` IPC event in `container_output_destroy` when moving a workspace from one output to another. This notifies swaybar (and anything else subscribed to the IPC events) of the change.

Send workspace::move in container_output_destroy

---

swaymsg/main.c

When executing commands via IPC, sway returns the result in a JSON array. swaymsg expected the result to be in the root of the JSON object, wouldn't find the `success` boolean, and would always return the fallback which is `true`.
This changes swaymsg to look in the array rather than the root, and return false if any of the commands failed.
Note that sway only ever returns an array of one item (the last executed command), but that's out of scope of this PR.
To test, run `swaymsg lol; echo $?`

swaymsg: Fix exit code

---

sway/tree/view.c

Don't read properties until needed, and do it with less lines of code.

Refactor parse_title_format

---

include/sway/commands.h
sway/commands.c
sway/commands/force_focus_wrapping.c
sway/meson.build
sway/sway.5.scd

Implements support for i3's legacy `force_focus_wrapping yes|no` command.
This is a follow-up to #2060. @SirCmpwn commented after the merge that he wants support for this legacy command.

Support i3's legacy force_focus_wrapping command

---

sway/desktop/output.c

This forces fullscreen views to be fully opaque.
Test:
- Open a view
- Set opacity (Ex: `swaymsg opacity 0.5`)
- Fullscreen the view (`swaymsg fullscreen`)
- Observe a fully opaque view
- Unfullscreen the view (`swaymsg fullscreen`)
- Opacity should return to 0.5 (or whatever it was set to above)

Force fullscreen views to be fully opaque

---

sway/ipc-json.c
sway/tree/layout.c

Fixes #2018 
Moving a container out of a tabbed or stacked parent container creates a new split with the container and it's former parent as siblings

Fix #2018 - Moving containers out of tabs/stacks

---

sway/tree/layout.c

Fixes #2078 
This handles moving out of a tab/stack when the container is the only child.

Fix moving out of tab/stack when only child

---

sway/tree/layout.c

Fixes the `SEGV on unknown address 0x000000000060` issue @martinetd found when testing #2081.
```
==2950==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000060 (pc 0x000000457a0d bp 0x7ffe81407ae0 sp 0x7ffe8
1407ac0 T0)
==2950==The signal is caused by a READ memory access.
==2950==Hint: address points to the zero page.
#0 0x457a0c in container_remove_child ../sway/tree/layout.c:145
#1 0x45b06d in container_move ../sway/tree/layout.c:522
#2 0x44350b in cmd_move ../sway/commands/move.c:178
#3 0x40e414 in execute_command ../sway/commands.c:369
#4 0x435f7d in keyboard_execute_command ../sway/input/keyboard.c:100
#5 0x43636e in keyboard_execute_bindsym ../sway/input/keyboard.c:168
#6 0x437590 in handle_keyboard_key ../sway/input/keyboard.c:380
#7 0x7f48a54d8948 in …
```

Fix move perpendicular segfault

---

sway/tree/layout.c

Fixes #2077 
I was sending the reparent event for the wrong container, which may have been freed by `container_flatten`. It was supposed to be for the container being split (`container_insert_child` already handles it for the container being moved out of the tab/stack). 
I decided the correct solution was not to send the reparent event after `container_split`, but in the `container_split` function itself.

Send reparent events in container_split

---

sway/commands/workspace.c

Fixes #1976 
Fixes #1957 
Switching workspaces would cause a crash when a layer surface has focus, such as swaylock. This is due to the seat not having focus so `seat_get_focus` returns `NULL`, which fails the assert in `container_parent` on the following line.
The only reason why `seat_get_focus` was called was to handle mouse warping. This is already handled by the `seat_set_focus` call in `workspace_switch` though so it can be removed entirely

Fix cmd_workspace crash when a surface has focus

---

include/sway/tree/container.h
include/sway/tree/layout.h
include/sway/tree/view.h
include/sway/tree/workspace.h
sway/commands.c
sway/commands/border.c
sway/commands/floating.c
sway/commands/layout.c
sway/commands/move.c
sway/commands/split.c
sway/commands/sticky.c
sway/config.c
sway/criteria.c
sway/debug-tree.c
sway/desktop/output.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/seat.c
sway/ipc-json.c
sway/meson.build
sway/tree/arrange.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/view.c
sway/tree/workspace.c

This implements basic floating features. You can float views, unfloat views, make them sticky and unsticky, and click to focus/unfocus them. You cannot move or resize them.
I was going to make it so you can float `C_CONTAINER`s in this PR, but there were some issues and I wanted to get this in front of everyone for review, so I blocked off that functionality. There's still bits in the code where it handles `C_CONTAINER`s being floated though.
This PR has a known issue with floating xdg_shell views when using multiple outputs. If floating the view on the left output, I'm experiencing a flickering copy of the container at the same output-local position on the right output. This does not happen for xwayland views. I can't see what I'm doing wrong, so if someone can assist me with that then …

Implement floating

---

sway/tree/view.c

Fixes #2085.
Those properties control whether the individual borders are rendered, and only take effect if the view's border is not `B_NONE`. Therefore it's safe to set them all to true. It initialises the values if the view is initially floating, and undoes any `hide_edge_borders` effects if the view was previously tiled.

Fix top border when a view is initially floating

---

include/sway/input/keyboard.h
sway/commands/bind.c
sway/input/keyboard.c

This pull request first simplifies the bindcode and bindsym generation code, 
so that the binding generated are identical in form up to the ids used to identify
the set of pressed keys; as most of the code between `cmd_bindsym` and `cmd_bindcode`
is shared, the two functions have been merged.
(Keycode numbering is briefly adjusted to match the XKB numbering scheme, like i3 seems to. (?))
The next large change is a rewrite of the shortcut handling, which should preserve the same behavior
except in edge cases. A single shortcut model is used for keycodes, raw keysyms, and translated keysyms. Release flag shortcuts are now identified on the preceding keypress, triggered if the next keyrelease breaks the shortcut condition, and kept if the next key event doesn't change shortcut state. The …

Reduce work duplication in keyboard and binding code

---

common/readline.c
include/readline.h
include/sway/commands.h
include/sway/config.h
sway/commands.c
sway/commands/bar.c
sway/commands/bar/colors.c
sway/commands/bar/id.c
sway/commands/input.c
sway/commands/mode.c
sway/commands/seat.c
sway/config.c
sway/input/keyboard.c
sway/ipc-server.c

Overview
-------------
Fixes #547 - Generic Code Blocks
Fixed #1034 - Braces on following line
Fixes #1753 - Output Block
This allows for any command to be given in either block form or expanded form. All commands should be working now.
`bar` command
----
For `bar`, the following syntax structures should be working:
1. Block with optional id subcommand (currently in master)
```
bar {
id bar-one
<bar-command>
}
bar
{
id bar-one
<bar-command>
}
```
2. Identifier block (similar to input and seat in master)
```
bar bar-one {
<bar-command>
}
```
3. Nested
```
bar {
bar-one {
<bar-command>
}
bar-two {
<bar-command>
}
bar-three <bar-command>
}
```
4. Expanded with identifier
```
bar bar-one <bar-commad>
``` 
5. Expanded with identifier on bar change
```
bar bar-one <bar-command>
bar …
```

Make command block implementation generic

---

sway/config.c

Introduced in 7c810dc344c28d1876c5ee158cb0806289d0f813

sway/config: fix use-after-free for end of block

---

sway/desktop/output.c

This fixes clients scheduling a frame by committing without damaging anything like so:
```
callback = wl_surface_frame(surface);
wl_surface_commit(surface);
```

Schedule a frame even if damage is empty

---

sway/tree/container.c

`_container_destroy` emits a `destroy` event, and any listener for this event should have access to the full container, not a half destroyed one.
`_container_destroy` also destroys the swayc, so we have to grab a reference to the sway_workspace so we can free it afterwards.
This also fixes a memory leak where the floating container wasn't freed.
Fixes #2092.

Fix potential crash when destroying workspace

---

sway/tree/view.c

The first view renders its title text incorrectly in case any font is set in the config file.
The `font` command calls `config_update_font_height(true)`, which resets `config->font_height` to 0 before iterating through child containers, but `config->font_height` is not updated anymore, because at this point there is only the root container with empty `formatted_title`.
When a new view is created after that, it relies on `config->font_height` to render its title, however it gets updated after the title is already rendered.
This commit changes the order, so that a newly created view uses the relevant font height.

Fix view title update order

---

sway/tree/output.c

When launching on DRM with an output rotated 90 or 270 (ie. portrait), the first workspace on that output would incorrectly have an `L_HORIZ` layout. This is because the workspace was being created before the output's dimensions were assigned, and the workspace's layout is chosen when it is created.
The PR assigns the output's dimensions before creating the workspace.

Fix initial workspace orientation on a rotated output

---

sway/input/seat.c

`seat_get_active_child` is used for tabbed and stacked containers to get the active child. The previous implementation used `seat_get_focus_inactive` then ascended the tree to the child of the tabbed/stacked container, but this fails when the workspace itself is stacked or tabbed and the most recently active child is floating.
The new implementation takes a more simple approach, where it directly scans the focus stack for the first immediate child which isn't the floating container.
Fixes #2098.

Fix seat_get_active_child

---

include/sway/commands.h
include/sway/config.h
sway/commands/output.c
sway/commands/output/background.c
sway/commands/output/disable.c
sway/commands/output/dpms.c
sway/commands/output/enable.c
sway/commands/output/mode.c
sway/commands/output/position.c
sway/commands/output/scale.c
sway/commands/output/transform.c
sway/meson.build

**This is forked from #2070 so that needs to be merged first**
@emersion requested that the output command be refactored to use subcommands in #2070. This PR does that
This also fixes setting a solid color background. In master, there are two issues:
1. There is a logic issue that prevents the `solid_color` branch from executing (it is checking against argument before -- the color).
2. `#` needs to be quoted or escaped when included in a shell command (ie swaybg). I decided to go with quoting the argument.

Refactor cmd_output to use config_subcommand

---

sway/tree/layout.c

Fixes #2105 
For the first and second issue in #2105, the issue was the `focus_inactive` loop. In both cases, `focus_inactive == sibling` so 
```
while (focus_inactive->parent == sibling) {
focus_inactive = focus_inactive->parent;
}
```
was going until it was trying to access the `parent` of `NULL`.
For the third issue, if the movement direction was perpendicular to the workspace layout and the layout was `L_HORIZ` or `L_VERT`, it was never escalated to the output level.
I also fixed a fourth issue that I noticed when making sure nothing broke. If you created the representation `H[view#1 V[view#2 view#3]]` and focused `view#2` and executed move up, the representation would be `V[view#1 view#2 V[view#3]]`. This is fixed by rejiggering the workspace with two containers instead of having the …

Fix movement crashes/issues

---

sway/desktop/layer_shell.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/seat.c

This PR fixes three focus related issues.
1. Restore focus when unmapping unmanaged xwayland surfaces. To test:
* Open a terminal and run i3-input.
* Cancel the prompt by pressing escape.
* Focus should be returned to the terminal.
2. Restore focus when unmapping layer shell surfaces. To test:
* Open a view.
* Lock the screen with swaylock.
* Unlock the screen.
* Focus should be returned to the view.
3. Don't set focus to NULL when clicking a surface which has no container. To test:
* Launch chromium and configure it so the bookmarks bar is visible and it contains a bookmark.
* Right click on a bookmark.
* swaybar should show that the workspace has focus.
There is one thing I'm not sure about, and that's the `wlr_xwayland_surface_is_unmanaged` check in `unmanaged_handle_unmap`. I copied …

Focus fixes

---

sway/main.c

This return effectively disables the log_kernel function. I don't think this is intended. Git blame suggests this was accidentally commited in 9eecbb5d8a988a0dded57ead1982dd0121071454.

Remove suspicious unconditional return

---

sway/input/cursor.c

Fix the problem with focus jumping to the container under the cursor
when first starting sway.

Initialise previous cursor position.

---

sway/tree/layout.c

Fixes #2113 
This fixes focusing issues after splitting a child of a tabbed or stacked container.

Fix focusing after splitting tabs/stacks

---

include/sway/ipc-json.h
include/sway/output.h
include/sway/tree/layout.h
sway/commands/output.c
sway/config/output.c
sway/desktop/layer_shell.c
sway/desktop/output.c
sway/ipc-json.c
sway/ipc-server.c
sway/tree/container.c
sway/tree/layout.c
swaymsg/main.c

Fixes #1887
When an output is:
- _connected_ - the sway_output stored in a `list_t` in `struct sway_root`
- _disabled_ - the container is destroyed
- _enabled_ - the container is (re-)created
- _disconnected_ - the sway_output is removed from the `list_t` in `struct sway_root` and freed
Additionally, I added disabled outputs to the output of `swaymsg -t get_outputs`.

Allow outputs to be re-enabled

---

sway/commands.c
sway/config.c
sway/tree/workspace.c

**This is forked from #2070 so that needs to be merged first**
Fixes #548
This makes it so variables are expanded at runtime. For commands like `bindsym` and `bindcode`, that need an argument (such as `<key combo>`) expanded at config time, there is `char *expand_var(char *var)`.
This also makes it so that `set` can be used at runtime.

Runtime variable expansion

---

sway/commands.c
sway/config.c

Fixes #2117 
This also fixes a strncpy--param-overlap error by replacing strncpy with memmove.

Remove strip quoting and fix strncpy-overlap

---

sway/commands/exec_always.c
swayidle/main.c

Also using `waitpid()` in sway for exec cmd because we can™

Swayidle: doublefork to not leave zombies around

---

sway/criteria.c

gcc complains about 0-length strncpy... it's fine anyway because calloc

sway/criteria: gcc string truncation warning fix

---

include/swaylock/seat.h
swaylock/password.c
swaylock/seat.c

The whole state->xcb.modifiers thing didn't work at all (always 0)
The xkb doc says "[xkb_state_serialize_mods] should not be used in
regular clients; please use the xkb_state_mod_*_is_active API instead"
so here it is
The final result is still rather messy so happy to get rebuked, please give me a better idea to do it though.

swaylock: implement ^U to clear buffer

---

include/sway/tree/workspace.h
sway/tree/container.c
sway/tree/layout.c
sway/tree/output.c
sway/tree/workspace.c

**This is forked from #2108 so that needs to be merged first**
In #2108, it was requested that workspaces be restored to their outputs when re-enabled as discussed in swaywm/wlroots#479. This PR implements that request.

Restore workspaces to output when re-enabled

---

sway/desktop/output.c
sway/ipc-json.c

```
FAILED: sway/sway@@sway@exe/desktop_output.c.o 
clang -Isway/sway@@sway@exe -Isway -I../sway -Iinclude -I../include -Isubprojects/wlroots/include -I../subprojects/wlroots/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/json-c -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/libdrm -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O0 -g -Wno-unused-parameter -Wno-unused-function -Wno-unused-result '-DSYSCONFDIR="/etc"' '-DSWAY_VERSION="1.0-alpha.2-266-g22c1c4be (" __DATE__ ", branch '"'"'master'"'"')"' -pthread  -MD -MQ …
```

Fix compilation errors related to disabled outputs

---

include/sway/config.h
include/sway/input/keyboard.h
sway/commands/bind.c
sway/input/keyboard.c

To quote the commit messages:
* Sort the list comprising the set of keys for the binding in ascending order. (Keyboard shortcuts depend only on the set of simultaneously pressed keys, not their order, so this change should have no external effect.) This simplifies comparisons between bindings.
* Ensure that modifier keys are identified even when the next key does  not produce a keysym. This requires that modifier change tracking  be done for each sway_shortcut_state.
* Permit regular and --release shortcuts on the same key combination. Distinct bindings are identified for press and release cases; note that the release binding needs to be identified for both key press and key release events.
* Maintain ascending sort order for the shortcut state list, and keep track of the number of …

Clean up keyboard handling code

---

client/pool-buffer.c

Pool buffers keep track of whether the compositor is still using them, so we don't step on its toes. They never got marked as such, though, so toe-stepping could be occurring.

Set pool_buffers busy when handing them out

---

sway/server.c

Allows desktop capture via the dmabuf-capture wlroots example client.

Init the dmabuf exporting protocol in wlroots

---

include/sway/server.h
sway/main.c
sway/server.c

Some operations during backend creation (e.g. becoming DRM master)
require CAP_SYS_ADMIN privileges. At this point, sway has dropped them
already, though. This patch splits the privileged part of server_init
into its own function and calls it before dropping its privileges.
This fixes the bug with minimal security implications.

Perform (partial) server initialization before dropping privileges.

---

sway/commands/output/background.c

if src is NULL due to a previous error we cannot use it in the command
result string.
Moreover if `src` points to `p.we_wordv[0]` we cannot use it after
`wordfree(&p)` in the command result string.
Bonus feature: If there was an error accessing the file, the string
rapresentation of the error is now included in the command result
string.

bugfix: avoid access after free

---

sway/input/cursor.c

Compare to i3 behavior:
Right click something to open a popup and focus follows mouse is suspended.

dont focus-follow-mouse when keyboard grab

---

include/sway/output.h
sway/desktop/layer_shell.c
sway/desktop/output.c

Both commits revolve around the same idea that layer shells need to die and cleanup properly before sway's output.
First one is a simple not cleaning up properly on handler being called, but second one is more subtle: both layer shell and sway's output listen to wlr's output destroy event, but there is no ordering guarantee here so I added a new event from sway's output to artificially order them.

layer shell: fix some use after free on destroy

---

include/sway/server.h
include/sway/xwayland.h
meson.build
sway/desktop/xwayland.c
sway/input/seat.c
sway/meson.build
sway/server.c

This PR makes the compositor connect to xwayland to get fetch atoms. These atoms are then used to automatically float xwayland windows.
Reference: https://github.com/i3/i3/blob/05a1dc0f6e1b2c963b10ff5d69789f6eb54b1b68/src/manage.c#L441
Updates #2063

Automatically float xwayland windows

---

sway/commands/input.c

Using `swaymsg "input identifier"`, was making sway crashing, no matter the validity or not of the input identifier. According to `sway-input(5)`, all input commands have the following format : `input identifier subcmd arg1 [args]`, so at least 3 arguments are expected (identifier, subcmd, and arg1).

Check if command input has at least 2 arguments

---

sway/desktop/xwayland.c

The view was configured with the container coordinates.
Although they were right on the first configure, they
changed after a XCB_CONFIGURE_REQUEST, when the
border was already drawn.
May fix #1925

 fix accidently removing borders on XCB_CONFIGURE_REQUEST 

---

sway/tree/view.c

That happened when they were in tabbed or stacked containers.
Fixes #2161

Fix floating views not receiving frame events

---

swaymsg/main.c

Command errors weren't displayed, because the success function didn't accept objects

fix swaymsg: errors are displayed again

---

include/sway/layers.h
include/sway/tree/view.h
sway/desktop/layer_shell.c
sway/desktop/output.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/tree/view.c

As discussed on IRC a few days ago with @emersion, get the appropriate wlr shell type depending on the surface type with wlr_surface_is_x then get the view through that `->data` field.
This is a prerequisite for idle inhibit to properly toggle itself on/off depending on surface visibility as the inhibitor only has a wlr_surface to deal with - I have an implementation that uses this and it appears to work but some of the rest depends on atomic transactions (e.g. when to check if view is still visible) so that'll hold off until atomic stuff is merged... But I wanted to get feedbacks on this first anyway.

sway views: add helpers to get view and layer from wlr_surface

---

sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c

That event comes from the toplevel and not the surface, so would cause
a use-after-free on destroy if the toplevel got destroyed first:
```
==5454==ERROR: AddressSanitizer: heap-use-after-free on address 0x6110001ed198 at pc 0x000000472d10 bp 0x7ffc19070a80 sp 0x7ffc19070a70
WRITE of size 8 at 0x6110001ed198 thread T0
#0 0x472d0f in wl_list_remove ../common/list.c:157
#1 0x42e159 in handle_destroy ../sway/desktop/xdg_shell_v6.c:243
#2 0x7fa9e5b28ce8 in wlr_signal_emit_safe ../util/signal.c:29
#3 0x7fa9e5afd6b1 in destroy_xdg_surface_v6 ../types/xdg_shell_v6/wlr_xdg_surface_v6.c:101
#4 0x7fa9e5d98025 in destroy_resource src/wayland-server.c:688
#5 0x7fa9e5d98091 in wl_resource_destroy src/wayland-server.c:705
#6 0x7fa9e27f103d in ffi_call_unix64 (/lib64/libffi.so.6+0x603d)
#7 …
```

xdg_shell: listen to fullscreen request on map

---

sway/commands/exec_always.c

- child would leak in the workspace_record_pid path
- removing malloc lets us get rid of That Comment nobody seems
to remember what it was about
- we would leak pipe fds on first fork failling
- we didn't return an error if second fork failed
- the final executed process still had both pipe fds
(would show up in /proc/23560/fd in launched programs)
- we would write twice to the pipe if execl failed for some reason
(e.g. if /bin/sh doesn't exist?!)
FWIW, this has a trivial conflict with the pid workspace stuff; happy to wait till the other one lands first but pointless sitting on the commit for such a small conflict.

exec_always: fix leaks

---

include/sway/desktop/idle_inhibit_v1.h
include/sway/server.h
sway/desktop/idle_inhibit_v1.c
sway/desktop/transaction.c
sway/meson.build
sway/server.c

Implements idle inhibit, and make it toggle when the surface goes "invisible" (hooks on every transition so whenever layouts change or workspace change)
It should be easy to adjust when the idle protocol works per-output, just need to make view_is_visible return a list of outputs where the thing is visible and disable idle for these specifically.
One thing I'm not totally happy about is I'm taking a pointer to the server struct everywhere in the idle inhibit code... To end up using the global server object in transition -_-
Should I just always use the global?
Also not happy storing the list of idle inhibitors directly in servers struct, I might want to encompass things in a sway_idle_inhibit_manager_v1 or something

Idle inhibit

---

sway/input/seat.c

Fixes #2192.
`seat_get_active_current_child` is intended to return a **current** child of the given container (ie. a child which has finished its mapping transaction and is able to be rendered on screen). The previous implementation was capable of returning a pending child, which caused a child of a tabbed or stacked view to be rendered prematurely while it was mapping.

Don't return pending children in seat_get_active_current_child

---

sway/main.c
sway/server.c

We would previously run all config commands without the environment,
which would appear to work as our socket name is the default one, but
wayland clients would start up in the wrong sway session.
(This explains why 'sometimes' my swayidle processes wouldn't die with
sway, as they weren't listening to the correct socket)

startup: move setenv WAYLAND_DISPLAY before config execs

---

sway/input/seat.c

When you have an unfocused container (so one view is focused_inactive), and you focus any other view in that container, the view with focused_inactive was not damaged. This is because we damaged the
previous focus and new focus, but needed to damage the parent of the new focus.
For example, create layout `H[view 1, V[view 2, view 3]]` and set focus to view 2. `focus left` to focus view 1, so view 2 becomes focused_inactive. Then use the mouse to focus view 3. Do this a couple of times and you'll see damage issues.

Fix focus related damage

---

include/sway/ipc-server.h
sway/ipc-server.c
sway/main.c

`wl_event_source_remove()` is illegal after display has been destroyed
```
==20392==ERROR: AddressSanitizer: heap-use-after-free on address 0x607000001240 at pc 0x00000048e86e bp 0x7ffe4b557e00 sp 0x7ffe4b557df0
READ of size 8 at 0x607000001240 thread T0
#0 0x48e86d in wl_list_insert ../common/list.c:149
#1 0x7fdf673d4d7d in wl_event_source_remove src/event-loop.c:487
#2 0x41b742 in ipc_terminate ../sway/ipc-server.c:94
#3 0x40b1ad in main ../sway/main.c:440
#4 0x7fdf6664c18a in __libc_start_main ../csu/libc-start.c:308
#5 0x409359 in _start (/opt/wayland/bin/sway+0x409359)
0x607000001240 is located 48 bytes inside of 72-byte region [0x607000001210,0x607000001258)
freed by thread T0 here:
#0 0x7fdf692c4880 in __interceptor_free (/lib64/libasan.so.5+0xee880)
#1 0x7fdf673d371a in …
```

ipc-server: add display destroy listener

---

sway/desktop/transaction.c

If we set an instruction as ready twice, it decreases the transaction's num_waiting a second time and applies the transaction earlier than it should. This no doubt has undesired effects, probably resulting in a use after free.
Hopefully fixes the first part of #2207.

Fix use after free in transaction code

---

sway/tree/container.c
sway/tree/view.c

I don't know why that line is there, but it effectively forces `B_NORMAL` for all tiled views, even if I run `border toggle`. It also disables borders for floating views.

Fix border weirdness

---

sway/input/cursor.c

Fixes #2111 
The function was returning before the call to `wlr_seat_pointer_notify_button` that sends the event to the layer surface.

Send pointer button events for keyboard-interactive layer surfaces

---

include/sway/config.h
include/sway/ipc-server.h
sway/commands/mode.c
sway/ipc-server.c
sway/sway.5.scd
swaybar/render.c

Fixes #663
This implements the `--pango_markup` flag for the `mode` command. For anything listening for IPC events, `mode::pango_markup` is sent along with `mode::change`.

Implement mode --pango_markup

---

sway/input/input-manager.c

This prevents it from being bypassed when the device has no seat configuration, which resulted in segfaults when trying to access the removed input.

Attach destroy handler earlier for input devices

---

include/sway/output.h
sway/desktop/output.c
swaylock/main.c

Also, when rendering, don't descend into the tree if the lockscreen is active. Just render the lockscreen's surfaces.
This makes an assumption that an `exclusive_client` will always be a lockscreen. This assumption is also made when handling `bindsym --locked` so I think it's a safe assumption.
This PR paints black behind the lockscreen, so if your lockscreen uses transparency or doesn't cover the whole layout for some reason then you'll just see black there. I know some people like to have their lock shortcut take a screenshot, blur it and apply it as the lockscreen background, and this is still possible.
Maybe my fans will spin down when my computer is locked now.

Don't send frame done to surfaces behind lockscreen

---

include/sway/commands.h
sway/commands.c
sway/config.c
sway/config/bar.c
sway/input/keyboard.c
sway/ipc-server.c
sway/main.c
sway/tree/container.c
sway/tree/view.c
sway/tree/workspace.c

This PR depends on #2203 as it touches the same function.
I'm pretty sure I'm still missing some here, I got a couple of crashes while trying to "produce activity" so I got annoyed and very likely missing some as I didn't check various patterns. This should still be a good start.
There also is tons of fontconfig stuff that seems to be alloc'd by cairo but I have no idea where that comes from, hopefully it's really just fontconfig's cache and won't grow endlessly.
wrt. what I said on IRC earlier for swaybar (bar leaking ~250 bytes every 5s) it would seem that this only happens with ASAN, so I guess that's just how much memory ASAN needs to keep track of the... 913 (!) indirect alloc/malloc calls that swaybar does every 5 seconds according to perf record. I guess I'll live with that for now …

Fix a bunch of leaks

---

sway/desktop/xwayland.c
sway/tree/view.c

Some xwayland views are first configured with a 1x1 size, and then
resized. Since the view size isn't updated, they are unclickable.
Fixes #2195

Fix xwayland floating views unclickable

---

sway/desktop/output.c
sway/tree/container.c
sway/tree/view.c

The title and marks textures would have their height set from the config's computed max font height, but the textures were not regenerated when the config's max font height changed which made a gap appear. Rather than making it regenerate the title textures every time the config font height was changed, I've changed it to just make the textures the height of the title itself and fill any gap when rendering.
Also, the `title_width` and `marks_width` variables have been renamed to make it more obvious that they are in output-buffer-local coordinates.
To test, visit [this YouTube video](https://www.youtube.com/watch?v=kfgFcMz-VnM) or [search for "grilled pork ginger" in Japanese](https://duckduckgo.com/?q=%E8%B1%9A%E3%81%AE%E7%94%9F%E5%A7%9C%E7%84%BC%E3%81%8D+&t=ffab&ia=web).
Fixes #1936.

Fix titles when container titles contain UTF-8 characters

---

swaybar/render.c

Fixes #2213
When workspace buttons are hidden, `wl_display_dispatch` was returning `-1` with `errno = 71`. Running `swaybar` with `WAYLAND_DEBUG=1` gave `wl_shm@4: error 1: invalid size (0)`. `max_height`was `0` on the first frame render due to the status line not being read yet.
~This PR prevents `max_height` from being `0`.~ This PR prevents rendering the bar if the `height` is not greater than `0`

Fix swaybar teardown when workspace buttons hidden

---

include/sway/output.h
sway/desktop/output.c
sway/desktop/render.c
sway/meson.build

This is a more conservative version of #2183. This PR refactors `output.c`, moving rendering functions into `render.c`. This PR doesn't contain any logic change (apart from fixing a bad cast in `output_view_for_each_surface`).
The goal is to make it easier to work with and review changes in `output.c` (such as refactoring iterators).

Split renderer

---

swaylock/password.c

Displaying verified after damaging state needs more than one roundtrip,
so keep looping until surfaces are not dirty anymore
I had this commit laying around for testing since we talked about it in #2112,
might as well use that since the author closed the original PR.
(I don't remember why the flush is needed after the loop, but I said it's needed so it probably was...)

swaylock: fix the displaying of "verified"

---

sway/tree/layout.c

When moving a workspace to an output with only an empty workspace, remove the empty workspace instead of leaving it until the user then switches to and away from it.

Replace empty workspace with moved workspace

---

include/sway/desktop.h
include/sway/output.h
include/sway/tree/container.h
sway/commands/move.c
sway/desktop/desktop.c
sway/tree/container.c

This implements the following for floating containers:
* `move <direction> <amount>`
* `move [absolute] position <x> <y>`
* `move [absolute] position mouse`
Containers are assigned to new workspaces as needed.
I moved the `strtol` parsing part out of `cmd_move` and into `move_in_direction` because it's specific to that function and was conflicting with the floating arguments.

Implement some floating move commands

---

sway/desktop/render.c

To reproduce, open a few views and change layouts to get a stack layout inside a tabbed layout or another stacked layout, e.g.: `T[termite S[termite termite]]`.
The code to render title bar for stacked layouts currently relies on the stacked container `swayc_y` field. However, in the example above `T[termite S[termite termite]]`, and both `termite` and `S[termite termite]` will have `swayc_y` set to the same value (the top bar height in my case). This makes the stacked container title bar be rendered over the tabbed container title bar with a gap below.
The issue does not affect tabbed containers, because they use `swayc_y` of their children. The same approach fixes the behavior for stacked ones, since both `termite` in `S[termite termite]` have `swayc_y` set to a value which takes into …

Fix title bar rendering for nested stacked containers

---

include/ipc.h
include/sway/config.h
sway/commands/output/background.c
sway/commands/reload.c
sway/config.c
sway/ipc-json.c
sway/ipc-server.c
swaymsg/main.c
swaymsg/swaymsg.1.scd

Namely get_binding_modes and get_config, though I'm not sure how well the latter has been implemented, would appreciate feedback on it.
Note: the config also doesn't expand includes, and I'm not sure whether that would be wanted, but it would definitely be a bit more work to add.

Add some missing ipc message types from i3

---

sway/desktop/render.c

using tabs with gaps causes the title bar to hang over the container on the right side
this fixes the title bar width under tabbed mode by factoring gaps into the calculation.

fix tabbed titlebar widths

---

common/list.c
include/list.h
sway/input/seat.c

To test, open two floating windows and position them (eg. using `move position mouse`) in a way that they overlap. Click each one and observe it move to be in front of the other one.

Move floating windows to front when focused

---

sway/desktop/render.c

Fixes #2237.
To test, launch mpv, fullscreen the video then unfullscreen it. When unfullscreening, it continued to render the live buffer while the other views were resizing, which meant you can get some frames of smaller video despite being fullscreen.
An easier way to test is to set `TRANSACTION_DEBUG` and increase the `TIMEOUT_MS` to 1000 or so.

Use saved buffer when fullscreen view is in a transaction

---

sway/input/seat.c

`container` will be `NULL` if launching swaylock.

Fix crash when launching swaylock

---

include/sway/commands.h
include/sway/config.h
sway/commands/input.c
sway/commands/input/scroll_button.c
sway/config/input.c
sway/input/input-manager.c
sway/meson.build
sway/sway-input.5.scd

Hello!
I missed in sway an option to set a scrolling button for my trackball Logitech M570, so I decided to implement it myself.
This patch adds support for `scroll_button` command in user's config file. Below is an example of my working config:
```
input "1133:4136:Logitech_M570" {
scroll_method on_button_down
scroll_button 273
}
```
In result I can scroll with holding the right button instead of default middle button.
The scroll button identifier is the same as in `libinput debug-events`.
I decided to set min and max value of button identifier to 0 and 1000, because I don't really know how the situation will be with other input devices. I am sure, that the minimum possible value must be set to 0, because libinput accepts it and disables the `on_button_down` scroll method. …

feature: scroll button option for input devices

---

sway/desktop/output.c

The `pixman_region32_contains_rectangle` call was using `wlr_surface->current.opaque` instead of `surface_opaque_box` (which was then unused).
The new `wlr_surface->opaque_region` is now used, fixing clients that set an infinite region and clients using a buffer without an alpha channel.

Fix output_has_opaque_lockscreen

---

swaybar/render.c
swaybg/main.c

When turning off displays via DPMS, swaybar and swaybg still tried to
render, but did not get a valid buffer, causing them to crash.
Not sure if that's a proper fix for the problem, but it does work

swaybar/bg: Fix crash on DPMS off

---

include/sway/commands.h
include/sway/config.h
sway/commands/input.c
sway/commands/input/tap_button_map.c
sway/config/input.c
sway/input/input-manager.c
sway/meson.build
sway/sway-input.5.scd

Closes #1569 
Implements `input <identifier> tap_button_map lmr|lrm`. This allows for the number of fingers used to be remapped to different buttons when using tap to click. There are only two options allowed by libinput: `lmr` (1=left, 2=middle, 3=right) and `lrm` (1=left, 2=right, 3=middle).

Implement tap_button_map for input devices

---

include/sway/debug.h
sway/desktop/render.c
sway/desktop/transaction.c
sway/main.c

We currently have several ways of setting debug flags, including command
line arguments, environment variables, and compile-time macros. This
replaces the lot with command line flags.

Add extended debugging flags

---

include/sway/desktop/transaction.h
include/sway/server.h
include/sway/tree/arrange.h
include/sway/tree/container.h
sway/commands.c
sway/commands/border.c
sway/commands/floating.c
sway/commands/fullscreen.c
sway/commands/gaps.c
sway/commands/layout.c
sway/commands/move.c
sway/commands/reload.c
sway/commands/resize.c
sway/commands/smart_gaps.c
sway/commands/split.c
sway/commands/swap.c
sway/config.c
sway/desktop/layer_shell.c
sway/desktop/output.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/server.c
sway/tree/arrange.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/view.c
sway/tree/workspace.c

This PR changes the way we handle transactions to a more simple method. The new method is to mark containers as dirty from low level code (eg. arranging, or `container_destroy`, and eventually `seat_set_focus`), then call `transaction_commit_dirty` which picks up those containers and runs them through a transaction. The old methods of using transactions (`arrange_and_commit`, or creating one manually) are now no longer possible.
The highest-level code (`execute_command` and view implementation handlers) will call `transaction_commit_dirty`, so most other code just needs to set containers as dirty. This is done by arranging, but can also be done by calling `container_set_dirty`.
This PR will make transactionising the focus stack much easier as I will be able to mark containers as dirty …

Simplify transactions by using a dirty flag on containers

---

include/sway/input/seat.h
include/sway/tree/container.h
sway/commands.c
sway/desktop/render.c
sway/desktop/transaction.c
sway/input/cursor.c
sway/input/keyboard.c
sway/input/seat.c
sway/ipc-server.c
sway/main.c

Rather than maintain copies of the entire focus stack, this PR transactionises the focus by introducing two new properties to the container state and using those when rendering.
* `bool focused` means this container has actual focus. Only one container should have this equalling true in its current state.
* `struct sway_container *focus_inactive_child` points to the immediate child that was most recently focused (eg. for tabbed and stacked containers).
While implementing this PR I discovered `transaction_commit_dirty` needs to be called even earlier than in `execute_command`, so it's now called from IPC, bindsym handling, etc. The reason for this is that a mapping view with criteria would call `execute_command` which created a second/nested transaction, which when combined with the new …

Make focus part of transactions

---

sway/config.c

When I originally wrote the code to read the config file, I set the struct variable early and used the null check to see whether it was reading the main config or an included config. Later on, I changed my mind so that it would attach it late, which negated the null check without me realising, leading to a whole bunch of problems.
Hopefully, this fixes that, as well as making the logic a bit better. I also added in a check so that if somehow, improbably, it reads in more than it thought it needed, it just aborts. I thought about resizing the buffer but was still a bit paranoid about race conditions.
Would appreciate feedback.

Fix config buffer overflow and logic

---

sway/input/seat.c

Fixes a bug where if you have a tab containing a split, then switch from a non-split tab to the split tab, focus is not changed properly.
To test, create layout `T[view, V[view, view focused]]` then `focus left` then `focus right`.

Fix tab split focus bug

---

include/sway/criteria.h
sway/commands.c
sway/commands/no_focus.c
sway/meson.build
sway/tree/view.c

i3 docs: https://i3wm.org/docs/userguide.html#no_focus
Example config: `no_focus [class="Firefox"]`
Note that if you've focused an empty workspace when the view maps, the view should receive focus regardless of any `no_focus` directive.

Implement no_focus command

---

swaylock/main.c
swaylock/swaylock.1.scd

Closes #1962 
Allows for `swaylock` to be configured from file. All long options are valid using the format `long-option[=value]`. Ex. `color=111111FF` or `ignore-empty-password`. If requested, I can add support for short options, but they are currently not supported in the config file.
The default configuration file paths are `$HOME/.swaylock/config`, `$XDG_CONFIG_HOME/swaylock/config`, and `SYSCONFDIR/swaylock/config`. The configuration file can also be manually specified using `-C, --config`.
I decided that instead of duplicating the code for configuring via the command line and a config file, to just reuse the same code and treat each line of the config file as a single argument for parsing. This makes it so that options do not need to be implemented/parsed in two locations and …

Implement swaylock configuration file parsing

---

include/sway/commands.h
include/sway/tree/container.h
include/sway/tree/view.h
include/sway/tree/workspace.h
sway/commands.c
sway/commands/urgent.c
sway/criteria.c
sway/desktop/render.c
sway/desktop/xwayland.c
sway/input/seat.c
sway/ipc-json.c
sway/meson.build
sway/sway.5.scd
sway/tree/container.c
sway/tree/layout.c
sway/tree/view.c
sway/tree/workspace.c
swaybar/ipc.c

Introduces a command to manually set urgency, as well as rendering of urgent views, sending the IPC event, removing urgency one second after focus, and matching urgent views via criteria.
To test, run something like `swaymsg [class="Firefox"] urgent enable`.
Try it with Firefox on a different workspace too, and notice the swaybar indicator working.
Note that urgency is not yet implemented when xwayland views request it, nor when a view requests focus (depending on the value of `focus_on_window_activation`). I feel like that's out of scope for this PR.
Closes #2258.

Implement urgency base functionality

---

sway/tree/view.c

When an xwayland view is mapped, the IPC urgent event ("this is/is-not urgent") was being sent on every surface commit.
I had intentionally ommitted the check because I figured an urgent surface could update its urgent timestamp by sending urgent a second time. But that's not how it works in xwayland's case, and it makes for more complicated code.

Remove superfluous IPC urgent events

---

include/sway/tree/view.h
sway/commands.c
sway/commands/default_floating_border.c
sway/desktop/render.c
sway/meson.build
sway/tree/container.c
sway/tree/view.c

i3 docs: https://i3wm.org/docs/userguide.html#_default_border_style_for_new_windows
To test, you need to use something which floats by default and doesn't have CSD:
* Have `default_floating_border pixel 10` in config
* Open Firefox and press `Ctrl+O` to open the file open dialog
The existing code in `view_set_tiled` that set the border to `config->border` was causing issues. I've changed this so the border values are untouched, and it instead uses a `bool using_csd` in the view to determine whether the border values should be respected or not. This allows the previous border config to be reinstated easily when toggling between floating and tiling, and also means the user can't run an IPC command to mess with the borders while CSD is active.

Implement default_floating_border command and adjust CSD behaviour

---

sway/config.c
sway/criteria.c
sway/desktop/idle_inhibit_v1.c
sway/desktop/layer_shell.c
sway/tree/view.c

Found using Cppcheck and AddressSanitizer. (FYI, Cppcheck also indicates
[sway/common/stringop.c:150]: (error) Common realloc mistake: 'argv' nulled but not freed upon failure
but the file is full of unchecked allocations anyway.)

Fix memory leaks and reference to uninitialized 

---

sway/input/seat.c

This allows to send wl_pointer.enter when switching between views
in a split/tabbed layout for instance. This (1) updates the cursor
image accordingly (2) makes it unnecessary to move the mouse before
scrolling. It's harmless to always call cursor_send_pointer_motion
because in case the focused surface hasn't changed this is a no-op.
The `last_focus != NULL` condition is required otherwise
cursor_send_pointer_motion will crash when sway starts up (the
sway_output doesn't yet have a workspace).

Update cursor on focus change

---

sway/input/cursor.c

Fixes #2302, as well as a crash.
To replicate the crash:
* Have multiple outputs
* In config: `for_window [<criteria>] workspace foo`
* Also in config: `workspace foo output <left-output-name>`
* Focus the right output, and ensure workspace foo doesn't exist
* Launch the app that triggers the criteria
When the view maps, it calls `workspace_switch` which calls `send_set_focus` which calls `cursor_send_pointer_motion` which calls `transaction_commit_dirty`. This call to `transaction_commit_dirty` is not meant to happen at this time because the tree isn't guaranteed to be in a consistent state, but I'm not sure how exactly this leads to the crash or render issues.
In this case the transaction is already committed by the view implementation's `handle_map` function. So the solution is to …

Fix crash and render issues involving cursor_send_pointer_motion

---

include/sway/server.h
sway/config.c
sway/main.c
sway/server.c

Fixes #2298 
Deferred commands were being run before the backend was started. This meant that there were no globals available yet. Since all deferred commands require globals (either directly or indirectly), this was causing deferred commands to fail.
This PR splits the `server_run` function in two: `server_start_backend` and `server_run`. The first starts the backend, which allows for the globals to be processed. The second does the call to `wl_display_run`. The deferred commands are being run between the two calls.
I also fixed a minor issue that was adding the raw line to the command queue instead of the expanded one. Off the top of my head, I'm not sure of anything used in a block that would be deferred, but that does not mean that one does not exist or will not exist in the future.

Fix deferred command handling

---

include/swaybar/bar.h
include/swaybar/status_line.h
swaybar/bar.c
swaybar/i3bar.c
swaybar/render.c

As well as ignoring scroll events on status elements when click_events
is enabled.
Previously, using the scroll wheel on a workspace button would switch to
that workspace instead of scrolling through them. Clicks and scrolling
on status elements would always be processed by swaybar, too. So in case
you were using scrolling as volume control on a status item, swaybar
would additionally scroll through your workspaces.
Note: I'm unsure about the enum naming. It doesn't seem to express the intent well enough, open to suggestions.

swaybar: Fix scroll handling on workspace buttons

---

include/sway/config.h
sway/commands/output.c
sway/config/output.c

Fixes #1724 
Fixes #2127 
Fixes #2295 
(Any others that I'm missing?)
This PR fixes issues related to `output *`.
Instead of applying the wildcard config directly to the output, the wildcard config is merged on top of the config for the output and that is then applied (falling back to the wildcard config). Additionally, when creating a non-wildcard config, it is merged on top of a copy of the wildcard config (if existent).
Output layout is no longer lost. This was due to an `output *` command being after the `output <name>` commands. When applying the `output *` config, the following snippet was changing it to auto positioning:
```c
if (oc && (oc->x != -1 || oc->y != -1)) {
wlr_log(WLR_DEBUG, "Set %s position to %d, %d", oc->name, oc->x, oc->y);
wlr_output_layout_add(output_layout, …
```

Fix output wildcard handling

---

include/sway/commands.h
include/sway/config.h
sway/commands.c
sway/commands/force_display_urgency_hint.c
sway/config.c
sway/desktop/xwayland.c
sway/input/seat.c
sway/meson.build

The directive sets the timeout before an urgent view becomes normal again after switching to it from another workspace.
Docs: https://i3wm.org/docs/userguide.html#_delaying_urgency_hint_reset_on_workspace_change
Also:
* When an xwayland surface removes the urgent hint while the timer is active, we now ignore the request. This happens as soon as the view receives focus, so it was effectively making the timer pointless.
* The timeout is now only applied when switching to it from another workspace.

Implement force_display_urgency_hint

---

include/sway/config.h
sway/commands/output.c
sway/config.c
sway/config/output.c

Fixes #1752 
Fixes #2293
This PR creates default output configs for connected outputs when reloading. This ensures that when the output configs are applied, if an option is missing it is reset to the default instead of left unchanged.
Additionally, when reloading output configs are now applied after the entire config is read and before the deferred commands. This ensures that all workspace command bindings are read and the output does not incorrectly get assigned an automatic workspace name. This simulates the behavior that sway would have on a fresh start.

Reset outputs on reload

---

include/sway/tree/view.h
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c

This allows to update the title even if the view doesn't commit.
This is useful e.g. when a terminal sets its toplevel title to
the currently running command and when the view isn't visible.

Handle set_{title,app_id} for xdg-shell and zxdg-shell-v6

---

sway/desktop/render.c

fix crash on new output while swaylock is running

---

sway/input/seat.c

Fixes #2339 
In `seat_set_focus_warp`, there was a missing null check and container type check that was causing the segfault.

Add missing checks to fix 2339

---

sway/input/cursor.c

`cursor_set_image` only uploads the named image if it doesn't match the previous named image. This means when setting the cursor image to a surface as given by a client (ie. not named), we have to clear the `cursor->image` property.
To test, open a window that sets a different cursor (eg. open a terminal and see the I-beam/text cursor) then switch to a new workspace. The cursor would not update, but now it changes to the regular pointer.

Fix some cases where the cursor doesn't update

---

common/util.c
include/util.h
sway/commands/focus_follows_mouse.c
sway/commands/focus_wrapping.c
sway/commands/force_focus_wrapping.c
sway/commands/fullscreen.c
sway/commands/input/drag_lock.c
sway/commands/input/dwt.c
sway/commands/input/left_handed.c
sway/commands/input/middle_emulation.c
sway/commands/input/natural_scroll.c
sway/commands/input/tap.c
sway/commands/output/dpms.c
sway/commands/show_marks.c
sway/commands/urgent.c

Related to #2336.
This PR adds a function (`parse_boolean`) similar to i3's `eval_boolstr`. The only `true` value that I added was `enabled` since that was in use for various commands. The rest are identical to i3's.
I also added support for toggling values. Currently, toggling is not supported for `input` or `output` commands (since it would require a change to the way their configs work, which is out of scope for this PR), but should work for anything else that takes a boolean value. For `input` and `output` commands, `toggle` is interpreted as a non-true value.

Switch to using a function to parse booleans

---

include/sway/config.h
include/sway/input/cursor.h
sway/commands/bind.c
sway/config.c
sway/input/cursor.c
sway/input/keyboard.c

~This set of changes is based on and requires #2296 ; I'm not entirely sure how best to to express this with Github's UI -- it seems I'll need to rebase a bit once #2296 is set, and clean up the resulting merge conflicts.~ (Done.)
I've recently tested the code using
bindsym Ctrl+button3 floating toggle
bindsym button1+button3 kill
bindsym --release Shift+button2 floating toggle
but not with much else. I'm currently minimizing changes to the cursor code so as to avoid rebase conflicts, but there's significant refactoring of the binding code, and consequent keyboard code adjustments.

Implement mouse bindings

---

sway/input/cursor.c

This makes it so if you hold mod and right click on a surface to resize it, the resize direction is chosen based on which quarter of the surface you've clicked. The previous implementation only resized towards the bottom right.

Make mod+resize work in any direction

---

sway/input/cursor.c

Fixes #2345.
`cont` was `NULL`.
To test, I ran `i3-input` then clicked the xwayland surface that appeared.

Fix crash when clicking certain surfaces

---

include/sway/config.h
sway/commands/floating_modifier.c
sway/config.c
sway/input/cursor.c

Closes #2335 
Implements the `[inverse|normal]` portion of `floating_modifier <mod> [inverse|normal]`.
In `normal` mode (default), `<mod> + left click` is move and `<mod> + right click` is resize.
In `inverse` mode, `<mod> + left click` is resize and `<mod> + right click` is move.

Implement floating_modifier <mod> [inverse|normal]

---

sway/input/seat.c

The crash only occurs if the mouse cursor is above the tabbed container when the last child is closed.
Introduced in 03d49490ccff3c5c81bea73622c8616fa61eb3dd, over a week ago and unnoticed until now :O
The above commit changes the behaviour of a focus change. When you change focus, it sends pointer motion which makes the client set a new cursor image. We already had this behaviour for workspace switching, but this commit adds it for view switching too, such as in a tabbed container or when closing a view.
The sequence of events that leads to the crash is:
* The last child of a tabbed container unmaps, which triggers a `destroy` event before we've cleaned up the child or reaped the tabbed container.
* The seat code listens to the `destroy` event and removes the seat container from the …

Fix crash when closing last child of a tabbed container

---

include/sway/output.h
sway/desktop/output.c
sway/desktop/render.c

The rendering code doesn't use the exclusive input surface at all
anymore to decide to skip rendering of shell surfaces. This fixes
a weird situation in which a client requests exclusive input but
isn't an overlay layer surface.
The renderer also renders all overlay surfaces in this situation,
not just one. This simplifies the code and fixes rendering when
there are more than one overlay surfaces (e.g. for a virtual
keyboard to type the lockscreen password).

Improve rendering with a fullscreen opaque overlay surface

---

include/sway/tree/container.h
include/sway/tree/view.h
include/sway/tree/workspace.h
sway/commands/fullscreen.c
sway/commands/move.c
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/seat.c
sway/scratchpad.c
sway/tree/arrange.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/view.c

Note that unmanaged xwayland surfaces are now rendered when anything is fullscreen, as opposed to only when an xwayland view is fullscreen. The alternative is searching the fullscreen container for an xwayland view, but I figured this isn't worth it.
Test plan:
* `focus parent` then `fullscreen` on different container layout types
* Move views around within a fullscreen container
* Attempt to move views out of a fullscreen container (they shouldn't move)
* Attempt to fullscreen a child of a fullscreen container - the fullscreen container should unfullscreen and the child becomes fullscreen
* In a fullscreen container, `focus parent`, `focus child`, `focus <direction>` into another output
* `focus <direction>` from a sibling output into the fullscreen container
* Move fullscreen containers …

Allow containers to be fullscreen

---

sway/tree/view.c

* Move workspace selection into separate function
* Instead of keeping a `prev_focus` variable, do the check in `should_focus` (ie. views can only take focus if they're mapped into the active workspace)
* Fix assign-to-output - it previously set `prev_focus` but should be `target_sibling`
* Remove call to `workspace_switch` as we'll only ever focus the view if it's in the active workspace

Refactor view_map

---

sway/desktop/transaction.c

In `set_instructions_ready`, calling `set_instruction_ready` may cause any number of transactions to get applied, which removes them from the list being iterated.  The iteration variables need to be adjusted accordingly.

Fix use after free in transactions

---

sway/desktop/transaction.c

The solution used in 073ac425d5bf6f6393eb91d9b5f84e3caa68f511 doesn't work in all cases because the freed instruction might be ahead in the list, not necessarily behind.
The new solution delays running the queue until after the loop has finished iterating, thus avoiding the problem completely.
To test, I opened filezilla (not firefox), floated it, then resized it violently using mod+resize. It would crash within several seconds.

Second attempt at fixing transaction use-after-free

---

sway/tree/container.c

Example config that produces the crash (with a single output):
workspace 1
workspace 2
I'm not sure on the specifics as to why it fails, but this fixes it by committing a transaction after each deferred command.

Fix crash when a deferred command destroys a workspace

---

sway/desktop/transaction.c
sway/input/seat.c

I tested it by changing the condition to `false`.

Handle out-of-fd situations gracefully for transaction and urgent timers

---

include/sway/input/seat.h
include/sway/tree/container.h
include/sway/tree/view.h
sway/commands/floating.c
sway/commands/focus.c
sway/commands/move.c
sway/commands/scratchpad.c
sway/commands/split.c
sway/desktop/render.c
sway/input/cursor.c
sway/input/seat.c
sway/scratchpad.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/view.c

Things worth noting:
* When a fullscreen view unmaps, the check to unset fullscreen on the workspace has been moved out of `view_unmap` and into `container_destroy`, because containers can be fullscreen too
* The calls to `container_reap_empty_recursive(workspace)` have been removed from `container_set_floating`. That function reaps upwards so it wouldn't do anything. I'm probably the one who originally added it...
* My fix (b14bd1b0b1536039e4f46fe94515c7c44e7afc61) for the tabbed child crash has a side effect where when you close a floating container, focus is not given to the tiled container again. I've removed my fix and removed the call to `send_cursor_motion` from `seat_set_focus_warp`. We should consider calling it from somewhere earlier in the call stack.
Test plan:
* `focus …

Allow containers to float

---

sway/input/keyboard.c
sway/sway-input.5.scd

This fixes a confusing issue where some laptop keyboards would have 'numlock mode' enabled, remapping parts of the alphabet to numbers.
It'd be great if we could detect keyboards with dedicated numpads and enable numlock by default, but that sounds really hard. :/

Don't enable numlock by default.

---

sway/desktop/xwayland.c

Fixes dunst.
Requires https://github.com/swaywm/wlroots/pull/1165

Don't give focus if xwayland window has a type hint

---

include/sway/tree/container.h
sway/desktop/output.c
sway/tree/container.c

On an output scale change, only the title texture of the focused container and all marks textures were being updated.
This PR updates the title textures for all containers.
Test Plan:
- Open any number of views in various layouts (including floating)
- Add some marks
- Change the scale of the output
- Verify all title and marks textures are updated to use the correct scale

Fix title textures on scale change

---

completions/zsh/_sway

zsh: fix sway completion

---

include/sway/input/keyboard.h
sway/input/keyboard.c

This PR resolves #2332. Have tested with
input 1:1:Piano {
repeat_rate 2
repeat_delay 2000
}
Setting 
input 0:0:X11_keyboard {
repeat_rate 0
repeat_delay 0
}
should disable key repeat. 
~I will update the documentation soon.~ (No documentation changes, as this PR now reuses the advised repeat_rate and repeat_delay from the Wayland protocol.)

Implement key repeat for keybindings

---

include/sway/output.h
sway/desktop/output.c
sway/desktop/render.c

The current iterators design is very confusing. This PR will:
- Remove `struct root_geometry`
- Remove `output_get_surface_box`
Updates #2291

Refactor surface iterators

---

sway/input/seat.c

Small change that stops the cursor from being displayed if there is no pointer input device. Created this to address the floating cursor in the middle of my screen, even though I am a keyboard-only user.

XCursor is not configured if no pointer device is available

---

completions/bash/swaymsg
completions/zsh/_swaymsg
include/ipc.h
include/sway/config.h
include/sway/input/seat.h
include/sway/ipc-server.h
include/sway/tree/view.h
sway/commands/bind.c
sway/commands/mark.c
sway/commands/move.c
sway/commands/reload.c
sway/input/cursor.c
sway/input/seat.c
sway/ipc-json.c
sway/ipc-server.c
sway/main.c
sway/tree/container.c
sway/tree/layout.c
sway/tree/output.c
sway/tree/view.c
swaymsg/main.c
swaymsg/swaymsg.1.scd

IPC Events (1.0)

---

include/sway/output.h
include/sway/tree/container.h
include/sway/tree/view.h
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/input/cursor.c
sway/input/seat.c
sway/tree/container.c
sway/tree/view.c

Fixes the render and `container_at` order for popups.
Fixes #2210
For rendering:
* `render_view_surfaces` has been renamed to `render_view_toplevels`
* `render_view_toplevels` now uses `output_surface_for_each_surface` (which is now public), as that function uses `wlr_surface_for_each_surface` which doesn't descend into popups
* Views now have a `for_each_popup` iterator, which is used by the renderer to render the focused view's popups
* When rendering a popup, toplevels (xdg subsurfaces) of that popup are also rendered
* Popups are now rendered on top of all containers
For sending frame done, the logic has been updated to match the rendering logic:
* `send_frame_done_container` no longer descends into popups
* `for_each_popup` is used to send frame done to the focused view's popups and …

Fix popups (v2)

---

meson.build
sway/meson.build

xcb is only required with xwayland, so remove xcb dependency if xwayland is disabled.
I'm new to meson, so I'm not sure it's done the right way. But I successfully tested the build with both -Denable-xwayland=true and -Denable-xwayland=false.

Link xcb dependency to meson options "enable_xwayland"

---

sway/commands/exec_always.c
sway/config/bar.c

To test: run i3status as swaybar status_command and/or from a terminal launched from sway, `killall -USR1 i3status`. i3status should refresh.

Reset signal mask after fork

---

sway/input/seat.c
sway/tree/view.c

Fixes #2402.
* `seat_set_focus_warp` lacked a container `NULL` check
* view mapping code needs to use `seat_get_focus_inactive`
Also, `seat_set_focus_warp` triggered the wrong IPC event if focus was a workspace, which resulted in swaybar not showing the workspace as active.
To test, I opened a terminal, ran `sleep 2 && firefox`, then locked the screen before the sleep finished.

Fix focus related crashes

---

sway/commands/move.c

To test, create two views in a workspace, then use `focus parent` to focus the workspace, then run something like `move to workspace 2`.

Allow moving containers when workspace itself is focused

---

sway/input/cursor.c

`container_at` expects a workspace, not the fullscreened container.
Fixes #2409

Fix crash on mouse motion on fullscreen container

---

include/sway/tree/container.h
sway/input/cursor.c
sway/tree/container.c

Leftover from https://github.com/swaywm/sway/pull/2410
To test, open mpv in fullscreen mode and try to use the UI with the mouse.

Fix pointer events for fullscreen views

---

sway/commands/move.c

Deny "move container" when an empty workspace is focused

---

include/sway/tree/container.h
sway/input/cursor.c
sway/tree/container.c

Calling `container_at_view` fails an assertion if the container isn't a view. Calling `tiling_container_at` works correctly, as that function checks if the container is a view and calls `container_at_view` if so.
To test:
* Fullscreen mpv and interact with the UI
* Fullscreen a split container where one of them is mpv and interact with the UI

Fix crash when moving cursor over a fullscreen split container

---

swaynag/main.c
swaynag/swaynag.c

Without this swaynag does not build on my system (implicit declaration of
functions like "free"). With these includes added it builds and works.

Add missing stdlib.h includes to swaynag

---

include/sway/commands.h
include/sway/config.h
include/sway/swaynag.h
sway/commands.c
sway/commands/include.c
sway/commands/reload.c
sway/commands/swaynag_command.c
sway/config.c
sway/main.c
sway/meson.build
sway/sway.5.scd
sway/swaynag.c

Closes #545 
This PR spawns `swaynag` when there are errors in the config. When reloading, the spawned instance is killed and if needed, a new instance is spawned.
~Additionally, this PR changes the allocation for the `error` field of `cmd_results` to get the size from `vsnprintf` instead of using a hard coded 256 bytes. This is to allow for the config error log for an included config to be passed as the error for the `include` command in the calling config.~
I also added a `swaynag_command` command so that a custom path for swaynag or additional arguments can be given.

Show swaynag on config errors

---

sway/tree/workspace.c

Fixes #2416 
~When switching workspaces, the wrong workspace could be checked for sticky floating containers. This is fixed by using `seat_get_focus_inactive` (followed-by `container_parent`) instead of `seat_get_active_child`.~ See comments below
Additionally, I fixed the iterator for the floating children so the current index is decremented when moving a sticky container to the workspace being switched to.

Check correct ws for sticky and fix floating iter

---

sway/swaynag.c
swaynag/swaynag.c

- Some platforms don't expose kill() unless _POSIX_C_SOURCE is defined.
- fork(), execl(), and setsid() need unistd.h on some platforms.
Basically, this fixes some platform-specific build errors.

Fix compiler errors.

---

include/sway/tree/container.h
include/sway/tree/view.h
include/sway/tree/workspace.h
sway/commands/layout.c
sway/commands/move.c
sway/commands/rename.c
sway/commands/workspace.c
sway/criteria.c
sway/sway.5.scd
sway/tree/layout.c
sway/tree/view.c
sway/tree/workspace.c

Ref #2336 
Fixes #1518
Criteria:
Commands:
Also prevents renaming workspace to "back_and_forth", as well as making it clear that they cannot be named to "special" workspace names.

Fix commands: criteria, layout, move, workspace

---

sway/commands/move.c
sway/tree/layout.c

`container_move_to` handled moving containers to new parents, as well as moving workspaces to new outputs.
This commit removes the workspace-moving code from this function and introduces `workspace_move_to_output`. Moving workspaces using `container_move_to` only happened from the move command, so it's been implemented as a static function in that file.
Simplifying `container_move_to` makes it easier for me to fix some issues in #2420.

Move workspace moving code out of container_move_to

---

common/ipc-client.c

Occurs very infrequently, such as calling swaymsg from i3

Fix memory leaks in get_socketpath

---

sway/tree/workspace.c

In a multi-output setup, if a sticky container is on one output and focus is on the other output, and you run (eg) `workspace 1` to focus the workspace containing the sticky container, an infinite loop would occur. It would loop infinitely because it would remove the sticky container from the workspace, add it back to the same workspace, and then decrement the iterator variable.
The fix just wraps the loop in a workspace comparison.

Fix infinite loop when focusing sticky containers via workspace command

---

sway/commands/move.c

The back_and_forth condition is intended to be handled in the else-if block, but this was never reached because it remained in the first block's conditions.
To test, run `move container to workspace back_and_forth` when no other workspaces exist.

Fix crash when running `move container to workspace back_and_forth`

---

sway/input/cursor.c
sway/tree/container.c

Fixes #2431.
It's not right for `container_at_view` to only return the swayc if a surface was clicked. It needs to also return the swayc if the decorations are clicked.
Note that `container_at_view` will now always return the swayc, so it assumes you've done a box check already. This seems like a safe assumption as I can't fault it.
To test, float a view which has title decorations then click the title. The floating view should be become focused.

Fix focus when clicking floating decorations

---

sway/tree/view.c

I've got the following SIGSEGV when terminating sway:
Program terminated with signal SIGSEGV, Segmentation fault.
```
0x00005607dc603af5 in view_unmap (view=0x5607dcb3d350) at ../sway/tree/view.c:599
599		if (surviving_ancestor->type >= C_WORKSPACE) {
```
When I was printing the surviving_ancestor, it was NULL at that time

[RFC] Fix segv when sway is terminating

---

include/sway/config.h
sway/commands/output/background.c
sway/config/output.c
sway/sway.5.scd
swaybg/main.c

Closes #2434 
Fixes #2270
This allows for a color to be optionally set when the wallpaper does not fill the entire output. If specified, the fallback color is also used when the image path is inaccessible.
I opted to use the following syntax
```
output <name> bg <path> <mode> [<fallback_color>]
```
instead of the following from #2434
```
output <name> bg <color> solid_color
output <name> bg <path> <mode>
```
This allows for both solid colors and images (with an optional fallback color) to be set without affecting the other when changed via commands further down the config or swaymsg.

Allow a fallback color to be specified for swaybg

---

sway/commands/resize.c
sway/sway.5.scd

Completes #1737.
* Implements `resize grow|shrink <direction> <amount>` for tiled containers
* Implements `resize set <width> <height>` for tiled containers
I made `resize set` allow px units, then realised afterwards that i3 doesn't support it. So I left it in. Use `px` to use pixels, and `ppt` or no unit to use percentage points.
Also fixes a sane size check which failed to check against the correct amount of pixels in some cases.

Finish resize commands

---

include/sway/tree/container.h
sway/input/seat.c
sway/tree/container.c

In all cases you can use `container_has_ancestor` with the arguments swapped, which is faster than `container_has_child`.

Remove container_has_child

---

include/sway/tree/container.h
sway/commands/hide_edge_borders.c
sway/commands/show_marks.c
sway/commands/unmark.c
sway/config.c
sway/criteria.c
sway/input/seat.c
sway/ipc-server.c
sway/tree/container.c

The function was not used.
Also renames `container_for_each_descendant_dfs` to just `container_for_each_descendant`.

Remove container_for_each_descendant_bfs

---

common/list.c
include/list.h
include/sway/commands.h
include/sway/input/seat.h
sway/commands/resize.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/input/cursor.c
sway/input/seat.c

* The `OP_RESIZE` seat operation has been renamed to `OP_RESIZE_FLOATING`, and `OP_RESIZE_TILING` has been introduced.
* Similar to the above, `seat_begin_resize` and `handle_resize_motion` have been renamed and tiling variants introduced.
* `resize.c`'s `resize_tiled` has to be used, so `container_resize_tiled` has been introduced in `resize.c` to allow external code to call it. Ideally all this would be in `container.c`, but I didn't want to make this PR unnecessarily big.
Things to test:
* Create two tiled views in horizontal/vertical layout and resize all internal edges
* Float a container with two or more views inside it and resize them
* Check for regressions in the resize/move stuff that's already implemented
BTW, it would be good if the cursor icon could be something like this: …

Implement resizing tiled containers via cursor

---

common/list.c
include/list.h
sway/tree/layout.c
sway/tree/root.c
sway/tree/workspace.c

The original purpose of this commit is to replace some `for` loops with `list_find`. But while doing this I found the `workspace_prev_next_impl` functions to be difficult to read and also contained a bug, so I refactored them and fixed the bug.
To reproduce the bug:
* Have two outputs, where the left output has workspaces 1, 2, 3 and the right output has workspaces 4, 5, 6. Make workspace 2 focused_inactive and workspace 4 focused.
* Run `workspace prev`.
* Previously it would visit the left output, then apply `workspace prev` to workspace 2, which focuses workspace 1.
* Now it will focus the rightmost workspace on the left output (workspace 3).
The refactoring I made to the workspace functions are:
* Added the `static` keyword.
* They now accept an `int dir` rather than bool, to avoid an …

Use list_find in more places and refactor/fix workspace prev_next functions

---

include/sway/desktop/transaction.h
include/sway/tree/container.h
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/tree/container.c
sway/tree/root.c

Commit 4b8e3a885be74c588291c51f798de80bd81a92db makes it so only one transaction is committed (ie. configures sent) at a time. This commit removes the now-unnecessary code which was used to support concurrent committed transactions.
* Instead of containers storing a list of instructions which they've been sent, it now stores a single instruction.
* Containers now have an `ntxnrefs` property. Previously we knew how many references there were by the length of the instruction list.
* Instructions no longer need a `ready` property. It was used to avoid marking an instruction ready twice when they were in a list, but this is now avoided because there is only one instruction and we nullify the `container->instruction` pointer when it's ready.
* When a transaction applies, we no longer need to …

Simplify transactions

---

sway/tree/workspace.c

This fixes a bug that I found that can be replicated as follows:
Go to a new workspace and open any app. Do this three times so you have 3 workspaces with one window each. Go to the middle workspace, close the window and attempt to use `workspace next` or `workspace prev` to navigate to either. You won't be able to
This seems to be because `workspace_by_name` only defines `current_workspace` and `current_output` if there's something focused on the current workspace as you can see here https://github.com/swaywm/sway/blob/master/sway/tree/workspace.c#L260 and in `workspace_prev_next_impl` it checks if the passed in workspace is null and stops if it is.
Since I'm not proficient in C, I just patched it in `workspace_prev_next_impl` by defaulting to the previous workspace if it exists.
This is …

Default to the previous workspace if the current one has no focused windows

---

include/sway/tree/container.h
sway/desktop/render.c
sway/desktop/transaction.c

This fixes a race condition flicker when unfloating a view which uses client side decorations.
When the view is floated it has `using_csd = true`, so the decorations are not drawn. When unfloating it it changes to false, but this change wasn't part of transactions so it could potentially render the decorations around the view while it's waiting for the transaction to apply.

Add using_csd variable to transaction state

---

sway/tree/container.c

To test:
* Create layout `H[view V[view]]`
* Focus the view inside the vertical split container and float it
The vertical split container was not reaped, so the tiling view would take up half the space.

Attempt to reap old tiling parent when floating a container

---

include/sway/input/seat.h
sway/commands/focus.c
sway/input/seat.c

Fixes #2467.
This commit introduces `seat_get_focus_inactive_floating` to supplement `seat_get_focus_inactive_tiling`, and uses it during `focus mode_toggle` which fixes a focus bug.
This also refactors the `seat_get_focus_inactive` functions so that they do their selection logic themselves rather than offloading it to `seat_get_focus_by_type` which was getting bloated. `seat_get_focus_by_type` is now removed.
Lastly, this commit changes `seat_get_focus` to just return the first container in the focus stack rather than looping and calling `seat_get_focus_by_type`.

Refactor seat_get_focus functions

---

sway/input/cursor.c

Fixes #2479.
It was missing a `mod_pressed` check.
This also moves the parent traversal into the `if` block.

Fix mod+resize

---

include/sway/input/seat.h
sway/input/cursor.c
sway/input/seat.c

This allows you to move the cursor off the surface while dragging its scrollbar.
To test:
* Launch something which has a scrollbar such as Firefox.
* Put something to the right of it such as a terminal.
* Click and hold Firefox's scrollbar.
* With the button still held, move the cursor off Firefox and onto the terminal.
* Observe the scrollbar still responds to mouse movements.
* If using `focus_follows_mouse`, observe the terminal does not gain focus.
* Release the mouse button. Do not move the mouse afterwards.
* Observe the cursor changes to whatever the terminal uses, such as an I-beam.
* If using `focus_follows_mouse`, observe the focus is changed to the terminal.

Implement mousedown operation

---

include/sway/output.h
include/sway/tree/container.h
include/sway/tree/root.h
include/sway/tree/workspace.h
sway/commands/hide_edge_borders.c
sway/commands/show_marks.c
sway/commands/swap.c
sway/commands/unmark.c
sway/config.c
sway/criteria.c
sway/desktop/output.c
sway/input/seat.c
sway/ipc-server.c
sway/tree/container.c
sway/tree/output.c
sway/tree/root.c
sway/tree/view.c
sway/tree/workspace.c

This introduces the following `for_each` functions:
* `root_for_each_workspace`
* `root_for_each_container`
* `output_for_each_workspace`
* `output_for_each_container`
* `workspace_for_each_container`
* `container_for_each_child`
And introduces the following `find` functions:
* `root_find_output`
* `root_find_workspace`
* `root_find_container`
* `output_find_workspace`
* `output_find_container`
* `workspace_find_container`
* `container_find_child`
And removes the following functions:
* `container_descendants`
* `container_for_each_descendant`
* `container_find`
This change is preparing the way for demoting `sway_container`. Eventually these functions will accept and return `sway_output`s, `sway_workspace`s and `sway_container`s (meaning a `C_CONTAINER` or `C_VIEW`), and which point their …

Implement iterators per container type

---

include/sway/desktop.h
include/sway/tree/view.h
sway/desktop/desktop.c
sway/desktop/output.c
sway/desktop/render.c
sway/desktop/transaction.c
sway/desktop/xdg_shell.c
sway/desktop/xdg_shell_v6.c
sway/desktop/xwayland.c
sway/tree/container.c
sway/tree/view.c

The only issue I've found with this PR is alacritty flickers while resizing. I think the content area might be a subsurface, and we don't save or render subsurfaces during transactions. From what I've read in the alacritty project their Wayland support is pretty beta.
My testing includes {floating,tiling} {gedit,alacritty,urxvt} and testing {pointer events,moving,resizing}. Urxvt is included to make sure I didn't break anything with views which use normal borders and no geometry.
Fixes #2178
Fixes #2476

Fix geometry
