swaywm/sway

sway/tree/container.c
Fixes #4892 
Fixed #4823 
When a container was being made fullscreen and it is on the focused
workspace for a seat, focus was being set to the container. However,
when the container was on a non-focused workspace, the focus stack
wasn't being touched. When assigning a fullscreen container to a
workspace or moving a fullscreen container to a different workspace,
this would make it so the fullscreen container was never added to the
focus stack for the workspace thus preventing access to the workspace.
This adds the container to the top of the focus stack, behind the
container on the focused workspace.
=> container: add inactive fullscreen to focus stack

include/sway/tree/container.h
This reverts commit 79c5f5ba1245a8c3d575770419a6501447e78919.
Fixes: https://github.com/swaywm/sway/issues/4908
=> Revert "Make all the container dimensions integers"

include/sway/tree/container.h, sway/commands/focus.c, sway/commands/move.c, sway/commands/split.c, sway/tree/container.c, sway/tree/root.c
Fixes #4788, Replaces #4789 
OK, so there are a few bugs handling scratchpad hidden split containers (SPHSCs).
Originally reported segfault:
<details>
<summary>
`scratchpad toggle` causes segfault on focused hidden container (because it is inadvertantly possible to focus SPHSCs)
</summary>
- stack trace in [comment](https://github.com/swaywm/sway/issues/4788#issuecomment-562295664)
</details>
But I've also found:
<details>
<summary>
`move to &lt;dest&gt;` causes segfault on SPHSC dest
</summary>
```
#0  0x0000564610a32042 in node_is_view (node=node@entry=0x0) at ../sway/sway/tree/node.c:41
#1  0x0000564610a10b9c in seat_get_active_tiling_child (seat=0x5646126c4220, parent=parent@entry=0x0) at ../sway/sway/input/seat.c:1251
current = <optimized out>
#2  0x0000564610a040c6 in …
```
=> Fix scratchpad hidden split container related segfaults

sway/config/output.c
Fixes #4904 
If applying an output config to an output fails, the output may be
destroyed by wlroots. To be able to handle this situation correctly,
apply_output_config_to_outputs needs to use wl_list_for_each_safe.
=> output: apply oc to outputs using wl_for_each_safe

sway/commands/move.c
Fixes #4919.
Crash was occurring because ++argv was going out of bounds.
=> commands/move: Fix crash when required args not provided

include/sway/server.h, sway/main.c
GCC 10 will enable -fno-common by default and sway currently fails to compile when using this flag.
=> fix build errors when using -fno-common

sway/sway-ipc.7.scd
This was previously undocumented in i3 until [recently](https://github.com/i3/i3/pull/3871), however it has now been confirmed stable.
=> Docs: Add marks field to get_tree response

include/sway/criteria.h, sway/commands.c, sway/criteria.c
Closes #4929
Replaces `criteria_get_views` with `criteria_get_containers` which can
return containers without views when the criteria only contains
container properties.
=> criteria: match containers without view

sway/desktop/layer_shell.c
This fixes the following crash:
#0  0x00007f7daac3af25 in raise () at /usr/lib/libc.so.6
#1  0x00007f7daac24897 in abort () at /usr/lib/libc.so.6
#2  0x00007f7daac24767 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007f7daac33526 in  () at /usr/lib/libc.so.6
#4  0x0000555bfbc35029 in seat_set_focus_layer (seat=0x555bfd76d860, layer=0x555bfdda2ff0)
at ../sway/input/seat.c:1164
__PRETTY_FUNCTION__ = "seat_set_focus_layer"
__PRETTY_FUNCTION__ = "seat_set_focus_layer"
#5  0x0000555bfbc35029 in seat_set_focus_layer (seat=seat@entry=0x555bfd76d860, layer=0x555bfdda2ff0)
at ../sway/input/seat.c:1164
__PRETTY_FUNCTION__ = "seat_set_focus_layer"
#6  0x0000555bfbc25899 in handle_output_destroy (listener=0x555bfdb90688, data=<optimized out>)
at ../sway/desktop/layer_shell.c:263
layer = …
=> Fix seat_set_focus_layer crash when disabling output

swaybar/tray/icon.c
The function group_handler may get a nullptr as `new_group`. If that's
the case, return -1, as if `new_group` was the empty string.
This fixes a build failure on s390x on Fedora rawhide:
```
[132/268] cc -Iswaybar/cf785bf@@swaybar@exe -Iswaybar -I../swaybar -Iinclude -I../include -Iprotocols -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/json-c -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/fribidi -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Werror -std=c11 -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wno-missing-braces -Wundef -Wvla '-DSYSCONFDIR="//etc"' …
```
=> Avoid calling strcmp on nullptr

include/swaybar/i3bar.h, include/swaybar/input.h, include/swaybar/status_line.h, swaybar/i3bar.c, swaybar/input.c, swaybar/render.c, swaybar/status_line.c, swaybar/tray/item.c
The first commit fixes the mistakes I made in 24e8ba048aef4751c6fa1d5982ee634f921e6cf6. The second commit is the one that actually increases the precision of the reported values. Pixel coordinates are sent, not logical coordinates. Do you think this makes sense, or should logical coordinates be sent as floating-point values?
I haven't tested multi-monitor setups.
=> fix i3bar relative coordinates when scaling is used

sway/tree/container.c
Fixes #4969
The container_at_tabbed and container_at_stacked container were checking
the bounds along the y-axis, but not the x-axis. This made it possible
to cause a segfault for specific resolution, horizontal gap, and
workspace children lengths. The issue is that child_index was -1 and was
resulting in a buffer underflow. Adding the x-axis bound checks for
early returns should prevent this from happening.
=> container_at_{tabbed,stacked}: check x-axis bounds

sway/main.c
It looks like the code to drop privileges may have been broken via commit 37f0e1f. That commit reverted the correct order from #911, which first drops the gid then the uid. If setuid is called first then the target user may not have the ability to setgid.
Fixes #4990.
=> Fix ordering of setgid and setuid

sway/commands/output.c, sway/config.c, sway/main.c
Fixes #4976
This makes it so invalid configs will return the exit code 1 when the
validation flag is given. This also reduces the log level to SWAY_ERROR,
which makes it so only the errors are shown. If someone wants more
verbose output, they can use the -V/--verbose or -d/--debug flags.
Additionally, this also makes it so swaybg will not be spawned when
validating the config.
=> config: fix validation exit code and log level

sway/commands/swap.c
Fixes #5007
The condition in test_mark was checking the negation of list_seq_find.
This works fine for the first mark, but fails for every other mark. This
fixes the condition to check for anything other than -1, which is the
value returned from list_seq_find for index not found.
=> cmd_swap: fix test_mark condition

sway/config/output.c
Fixes segfault on start:
https://gist.github.com/yorickvP/89eccb3782c6edb22aeda6ce9c6d4fcb
=> Fix crash: use wlr_output->name instead of possibly missing oc->name

include/sway/output.h, sway/config/output.c, sway/tree/output.c
Fixes #5014 
The output manager config is created when the output is created. It is
updated when the mode, transform, scale, or layout for the output
changes, as well as, when the output is destroyed.
Since the output->enabled property was not being set before calling
apply_output_config, the output event handlers were early returning and
never updating the output manager config when the output state was
committed.
This fixes the issue by setting output->enabled in apply_output_config
below the output disabling section. There are also a few other minor
changes that are required to function.
=> output: fix updating output manager config

sway/commands/output/transform.c, sway/sway-output.5.scd
This patch makes it so users that have configured their screen with a
transform don't have to update their config after the wlroots breaking
change.
References: https://github.com/swaywm/wlroots/pull/2023
=> Fix inverted transforms

sway/ipc-json.c, sway/sway-ipc.7.scd
i3 added these in i3/i3#3797
Todo:
- update docs
- convert int to string? e.g. `...WINDOW_TYPE_NORMAL`
=> i3compat: add `window_type` to IPC response

sway/tree/view.c
If a subsurface is created for a surface that is associated with a
scratchpad hidden view, do not attempt to send an enter to it. The
subsurface is not on any output and since there is no workspace
associated with the view, attempting to get the output for the NULL
workspace will result in a SIGSEGV.
There is likely other ways to reproduce, but I ran into this with the following for_window rule and attempting to do a video conference in firefox-nightly using wayland backend for firefox.
```
for_window [title="Nightly - Sharing Indicator"] move to scratchpad
```
=> tree/view: do not attempt enter on hidden child

sway/desktop/layer_shell.c
Backport of [1].
[1]: https://github.com/emersion/rootston/pull/15/files
=> Don't apply exclusive zones of unmapped layer-shell surfaces

sway/desktop/layer_shell.c
Reverts swaywm/sway#5032
https://github.com/swaywm/sway/pull/5032#issuecomment-590646108
> swaybg silently fails after this commit for me, and wofi dies with the protocol error "layer_surface has never been configured".
=> Revert "Don't apply exclusive zones of unmapped layer-shell surfaces"

include/sway/criteria.h, sway/criteria.c, sway/sway.5.scd
One of my barriers to switching to a Wayland native terminal emulator is the lack of urgency support. I have my shell configured to echo a bell character when commands are completed, which makes most X terminal emulators set the window to urgent. This is generally not possible in Wayland due to no native urgency support.
With this patch I can apply this behaviour in a Wayland native terminal using the following in my `~/.zshrc`:
precmd() {
swaymsg "[pid=$PPID] urgent enable"
}
So when a shell command completes, zsh runs that swaymsg command with the PID of the terminal emulator. Sway then sets the terminal emulator to urgent.
You can test it by putting the above in your zsh config, then run `sleep 1` in a Wayland native terminal and focus away before the sleep completes. This assumes your …
=> Introduce pid criteria token

swaybar/ipc.c
Currently when changing properties via ipc like `workspace_buttons`, which don't affect the bar's surface at all, the surface is still destroyed and recreated. This causes sway to recalculate the workspace height twice in rapid succession, which is rather unpleasant. This fix only requests destruction if the mode was changed.
=> Only destroy swaybar surface via ipc when needed

sway/sway.5.scd
Closes #5051 
This correct the description of the commmand:
workspace [--no-auto-back-and-forth] [number] <[num:]name>
Previously, the number and num pieces were being confused. This also
documents the behavior of the --no-auto-back-and-forth flag.
=> sway.5: correct description of workspace [number]

include/sway/output.h, sway/desktop/output.c
When a client hasn't damaged its surface, we only need to schedule an
output frame if the client has requested a frame callback.
=> Only schedule a frame if client has requested a frame callback

include/sway/commands.h, include/sway/config.h, sway/commands/output.c, sway/commands/output/adaptive_sync.c, sway/config/output.c, sway/ipc-json.c, sway/meson.build, sway/sway-output.5.scd, swaymsg/main.c
This enables/disables adaptive synchronization on the output.
For now, the default is disabled because it might cause flickering on
some hardware if clients don't submit frames at regular enough
intervals. In the future an "auto" option will only enable adaptive sync
if a fullscreen client opts-in via a Wayland protocol.
Testing:
- Set `output * adaptive_sync on` to enable VRR on all outputs that support it
- Set up output scheduling parameters so that clients will miss the deadline. On my hardware, `output * max_render_time 1` plus `max_render_time 1` works well.
- Check that adaptive sync is marked as enabled in `swaymsg -t get_outputs` (alternatively, "VRR enabled on connector" should appear in the debug logs)
- Run `weston-presentation-shm` on an output without adaptive sync enabled. …
=> Add an adaptive_sync output command

common/log.c
Regressed by https://github.com/swaywm/sway/pull/5075. See [error log](https://github.com/swaywm/sway/files/4301714/sway-1.2.r1.242.log).
`CLOCK_MONOTONIC` was added in POSIX.1-2001 according to CHANGE HISTORY in https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html
=> Unbreak build on FreeBSD

sway/desktop/output.c
Before this change, an overlay layer-shell surface without a buffer
attached would segfault the compositor on screen damage.
=> Null check sway_layer_surface when checking damage

sway/ipc-json.c
"nodes" is only missing from the scratchpad, and hopefully I didn't get anything wrong about "fullscreen_mode", but I added them to the base function to make their requirement explicit.
=> ipc: add missing required properties

sway/commands/input/xkb_switch_layout.c, sway/sway-input.5.scd
This change enables users to change layout relative to the current position on the layout list. This way one can for example `bindsym Mod1+space input * xkb_layout_switch next` and iterate through their entire list of keymaps with a single shortcut.
=> input: implement cycling through keyboard layout list

include/sway/commands.h, include/sway/config.h, include/sway/input/input-manager.h, include/sway/input/seat.h, sway/commands/bind.c, sway/commands/seat.c, sway/commands/seat/cursor.c, sway/commands/seat/shortcuts_inhibitor.c, sway/config/seat.c, sway/input/input-manager.c, sway/input/keyboard.c, sway/input/seat.c, sway/meson.build, sway/sway-input.5.scd, sway/sway.5.scd
Adding support for the keyboard shortcuts inhibit protocol allows remote
desktop and virtualisation software to receive all keyboard input in
order to pass it through to their clients so users can fully interact
the their remote/virtual session. The software usually provides its own
key combination to release its "grab" to all keyboard input. The
inhibitor can be deactivated by the user by removing focus from the
surface using another input device such as the pointer.
Use support for the procotol in wlroots (swaywm/wlroots#2026) to add support to sway. Extend
the input manager with handlers for inhibitor creation and destruction
and appropriate bookkeeping. Attach the inhibitors to the seats they
apply to to avoid having to search the list of all currently existing
inhibitors on every …
=> Keyboard shortcuts inhibit

sway/input/seat.c, sway/input/tablet.c
If a pad device for a tablet exists, reloading the configuration,
removing/reading the device or even suspending the system will recreate
the same Wayland input device multiple times.
Make sure we don't re-create the same Wayland device more than
necessary.
Signed-off-by: Olivier Fourdan <ofourdan@redhat.com>
Closes: https://github.com/swaywm/sway/issues/5093
Thanks @ofourdan for the patch!
=> input: Avoid creating the PAD device multiple times

sway/commands/bind.c
Outer `if` condition already checks `!button`﻿
=> sway/commands/bind.c: remove unnecessary `if` check"

sway/input/cursor.c
This check appears a couple times in the code, but it was out of place for one of them.
=> sway/input/cursor.c: move NULL check to proper location

sway/sway-input.5.scd
From the current manpage it was not clear to me which input settings will take precedence, if `identifier`, `type` and `*` are all being used, so I ventured out into the code:
* https://github.com/swaywm/sway/blob/33a984bbc5c5ec4202f24bacf6ddd584b95a9ec0/sway/config.c#L522-L529
* https://github.com/swaywm/sway/blob/3ee5aace33f1b5673ab372afba38480338ba8b90/sway/input/input-manager.c#L506-L525
* https://github.com/swaywm/sway/blob/90d8a4df32747161c7218c006bb96e8214d8f7f2/sway/input/libinput.c#L273-L295
* https://github.com/swaywm/sway/blob/30e666f1710e5fcff46e9a75660dc2331d79dca8/sway/input/input-manager.c#L619-L640
* https://github.com/swaywm/sway/blob/30e666f1710e5fcff46e9a75660dc2331d79dca8/sway/input/input-manager.c#L233-L235
* …
=> Document input selector precedence

sway/input/cursor.c
Since `libevdev_event_code_get_name` may return NULL
=> sway/input/cursor.c: fix undefined behaviour (printing NULL)

sway/input/seat.c
This commit fixes calling to `seat_send_focus()` twice when a view is closed.
This PR basically revert #2580.
I have tested that the original issue no longer exists. Closing a fullscreen view can successful focus to another view even after reverting.
=> Fix redundant call to seat_send_focus()

sway/commands/workspace.c
For the 'workspace <name> output <output>' command, output_location must
be greater than zero or the attempt to get the workspace name with
join_args will segfault or abort() (depending on the flavor of
sway_assert() in use). This checks and returns an error instead.
=> check for workspace command name arg (fix #5131)

sway/tree/container.c
In the case of multiple overlapping floating windows, this commit fixes an issue where the wrong window would be focused in response to a cursor if one of the windows came from a different output (overhanging).
This fix is similar to 8789ceea8 (fixes #2315) which switched to reverse iteration on the floating list, whereas this fix does it on the output list.
=> Fix hit test for floaters that cross outputs

swaynag/main.c, swaynag/swaynag.c
swaynag_destroy is called on all cleanup cases and needs the lists to be valid,
just init them early
=> swaynag: fix segfault on exit when arguments are not correct

sway/input/cursor.c
The issue is similar to #4819: while the application windows correctly handle touch events when tapped, the keyboard input focus stays on the window the mouse is hovered upon. The solution is also similar, call move_cursor with relative coordinates.
=> Add focus following for touch_down

sway/config.c, sway/sway.5.scd
Before the default was "smart". This means a visible app could steal focus
whenever it wanted to. This can be an issue since having focus allows for
e.g. clipboard access.
This commit changes the default to "urgent" instead.
Closes: https://github.com/swaywm/sway/issues/5139
=> Change focus_on_window_activation default to urgent

include/sway/config.h, sway/commands/bind.c, sway/input/keyboard.c, sway/sway.5.scd
This allows e.g. triggering one command while a key is held, then
triggering another to undo the change performed by it afterwards. One
use case for this is triggering push-to-talk functionality for VoIP
tools without granting them full access to all input events.
Fixes #3151
=> add --no-repeat option for bindings

sway/desktop/layer_shell.c
As briefly discussed in IRC.
Sway currently respect the the positive exclusive zone of surfaces anchored
to three or four edges. With these changes, sway will respect positive
exclusive zones of layer surfaces anchored to one or three edges.
This matches the protocol, which states that a positive exclusive zone
should be respected, "if the surface is anchored to one edge or an
edge and both perpendicular edges". If the surfaces is "anchored to
only two perpendicular edges (a corner), anchored to only two
parallel edges or anchored to all edges a positive value will be
treated the same as zero".
---
I am not entirely sure if this is the best way to do this, but I think two anchor-cases to compare to per struct and a single struct per edge is clearer than either complex bit logic or having …
=> change apply_exclusive() to match layer shell protocol

sway/sway.5.scd
Where available, we should probably reference Wayland specific tools.
=> Reference wev instead of xev

swaynag/swaynag.c
fixes loop when sway closes the socket in the middle of querying outputs,
see #5138.
(in my opinion doesn't close it, because I'd like to understand why sway closes the socket, this probably just hides the problem but is good to have anyway)
=> swaynag: exit on wl_display_roundtrip error

sway/input/cursor.c
As discussed in swaywm/sway#5145 a more logical solution is to perform cursor hide/leave before emitting a touch down event instead of after.
=>  hiding the cursor and sending a touch event are swapped 

include/sway/input/seat.h, include/sway/input/text_input.h, include/sway/server.h, sway/input/seat.c, sway/input/text_input.c, sway/meson.build, sway/server.c
This ports basic input method support from rootston to sway.
Origin from: 
- swaywm/wlroots#1203
- swaywm/wlroots#1303
- swaywm/wlroots#1308
- swaywm/wlroots#1759
=> Port input method and text input from rootston

meson.build
Tell pkgconfig about prefix and datadir as required in the .pc files, so
if the prefix isn't standard nothing is installed outside of it.
For fish, this requires https://github.com/fish-shell/fish-shell/pull/6778
Fixes swaywm/swaybg#13
=> build: make completions respect install prefixes

sway/config.c
This color, both in i3 and as described in sway(5), defaults to #888888.
However, the actual default also has an alpha of 88 instead of FF,
meaning it ends up significantly darker than intended.
=> config: fix unfocused text color

include/sway/config.h, sway/config/output.c, sway/desktop/output.c
This depends on https://github.com/swaywm/wlroots/pull/2097.
To test, use [wlr-randr](https://github.com/emersion/wlr-randr)'s `--dryrun` mode to perform an invalid output configuration change. For instance, use the Wayland backend and try to disable an output:
```
wlr-randr --dryrun --output WL-1 --off
```
This should fail (the Wayland backend doesn't support disabling outputs). Prior to this PR, this always succeeded.
=> Add support for wlr_output_test

assets/lJ9C.vtt, index.html
I put the vtt subtitle file in the assets directory, with the same name as the video. The video itself is hosted at sr.ht, so it may be more appropriate to put this vtt file there instead.
I'm also not entirely sure this will work correctly hosted from github pages, as some browsers may need the MIME type to be "text/vtt" and I'm not sure how github pages will serve it. Might work correctly out of the box. My local testing webserver applied the correct MIME type based on the extension automatically.
=> Add subtitles to video on home page

sway/config/output.c
An if branch takes care of the case where the output needs to be turned
off (DPMS'ed or disabled). The other branch needs to unconditionally
enable the output.
output->current_mode is already taken care of in apply_config.
Sorry about that, probably made a bad change by mistake after my DRM testing.
Closes: https://github.com/swaywm/sway/issues/5193
=> Fix initial modeset

sway/desktop/output.c
Instead of removing the destroy listeners in the output destroy, remove
them in the damage destroy handler. Fixes the following use after free:
```
==646625==ERROR: AddressSanitizer: heap-use-after-free on address 0x61200017cab8 at pc 0x0000004f8f29 bp 0x7ffdf465ad30 sp 0x7ffdf465ad20
WRITE of size 8 at 0x61200017cab8 thread T0
#0 0x4f8f28 in wl_list_remove ../common/list.c:181
#1 0x43dd24 in handle_destroy ../sway/desktop/output.c:790
(`wl_list_remove(&output->damage_destroy.link);` here, 214e3030e1dce master branch)
#2 0x7f0e573a1c93 in wlr_signal_emit_safe ../util/signal.c:29
#3 0x7f0e57390954 in wlr_output_destroy ../types/wlr_output.c:365
#4 0x7f0e5735e37f in backend_destroy ../backend/x11/backend.c:128
#5 0x7f0e57348147 in wlr_backend_destroy ../backend/backend.c:47
#6 …
```
=> output: remove damage listeners in damage destroy

include/sway/output.h, sway/desktop/output.c, sway/desktop/render.c, sway/input/cursor.c
As talked about in #4684, this renders popups separately from the corresponding windows, to make sure they are always displayed above other windows. I'm not sure though, whether they should be rendered before or after the top layer.
Furthermore, I don't have a good understanding of sways rendering code. This seems to work for me, but I cannot really figure out the side effects those changes may have. Splitting the output_layer_for_each_surface in three functions also gives some code duplication but I wanted to make sure to not break anything using output_layer_for_each_surface and expecting it to also include popups.
So it would be nice, if someone with an actual understanding of this code could give it a look and it's also why it is marked [WIP].
Edit: something I just realised: this …
=> Render layer shell popups over the top layer

include/sway/config.h
Instead of hardcoded power of 2 values, use bitshifts. This makes the
enums more readable, avoids mistakes, and makes it clear how much of the
int32_t bit space we have left.
While at it, fix other minor style issues.
=> Use bitshifts for bitfields

sway/input/seatop_default.c
Instead of handling presses and releases on empty workspaces as setting
focus to the workspace, handle releases by notifying the seat of a
pointer action. This way DnDs are correctly released if the button is
released over an empty workspace.
Fixes #3932
=> input/seatop_default: release on empty workspace

sway/input/cursor.c
Fixes #5185
The issue is fixed when checking for NULL already, but I think the N_WORKSPACE check also makes sense.
Edit: removed the workspace part as proposed by emersion.
=> Don't transfer focus to NULL node on touch

sway/tree/container.c, swaybar/render.c
Fixes issue #5228. Currently, WL_OUTPUT_SUBPIXEL_NONE is ignored and CAIRO_ANTIALIAS_SUBPIXEL is still set. This commit checks if subpixel is set to none and if so, calls set_antialias with CAIRO_ANTIALIAS_GRAY. This mirrors the functionality in Mako's [PR261](https://github.com/emersion/mako/pull/261).
@progandy brought up that we could alternatively "extend it to 'none' = no antialias, 'gray' = grayscale" and/or read from the fontconfig setup.
=> interpret "subpixel none" as CAIRO_ANTIALIAS_GRAY

sway/sway.5.scd
Apparently, there's a typo in Sway's man page where `input-device` of
`unbindcode` command has no dashes.
=> scdoc: unbindcode --input-device, not input-device

sway/commands/output/transform.c, sway/sway-output.5.scd
Prevent them from being used in the config file.
This is a breaking config file change.
References: https://github.com/swaywm/sway/issues/5236
=> Restrict relative output transforms to runtime changes

sway/input/cursor.c
If we started holding the tool tip down on a surface that accepts tablet
v2, we should notify that surface if it gets released over a surface
that doesn't support v2.
Since GTK supports tablet v2, this fixes the common case of starting a
drag over a GTK surface (e.g. scrollbar) and releasing it outside (e.g.
over the gaps between sway containers, or in a terminal).
It does not fix the other direction, e.g. dragging over a non-v2 surface
(with tablet events being emulated as mouse events) and releasing over
a v2 surface.
Refs #5230.
=> input/cursor: correctly send tablet v2 up event when over non-v2 surface

sway/input/cursor.c
This fixes resizing containers being very jerky under pointer emulation.
Refs #5232.
=> input/cursor: fix jerky resizing of non-tablet_v2 surfaces

include/sway/input/cursor.h, sway/input/cursor.c, sway/input/seat.c
This commit refactors `cursor_handle_activity` to also take the idle
source, so that it can be reused for tablet and touch activity.
Previously, the timeouts would be tracked, but the cursor would never be
un-hidden for anything but pointers (including emulated pointers on
non-tablet_v2 surfaces).
Fixes #5169.
=> input/cursor: fix hide cursor timeouts on tablets and touchscreens

sway/input/seatop_resize_floating.c
Otherwise the borders can be resized to smaller than the minimum window size like this:
=> Take window borders into account when resizing floating windows

sway/config/output.c, sway/input/seat.c
Some input rules, like `map_to_output`, are dependent on a specific
screen being present. This currently does not work for hotplugged
outputs, or outputs that are processed after the input device is
initially probed.
This commit fixes both cases, by reconfiguring inputs on each output
addition.
Fixes #5231.
=> config/output: reconfigure input devices on new output

sway/input/cursor.c
Tentatively fixes #4819.
This commit ensures that `seatop_motion` is called to transfer focus when a window is selected via a pen. Previously, it would race with `node_at_coords`, and only properly transfer focus if its returned `surface` was `NULL`.
I've tested this locally, and it fixes the issues I was experiencing.
Calling `seatop_motion` directly here works as well, but my impression is that the confine handling inside `cursor_motion` should be done for tablet devices too. Applications see the following sequence of events:
```
[912231.664] wl_pointer@3.motion(7987491, 281.539062, 991.007812)
[912231.673] zwp_tablet_tool_v2@4278190083.motion(281.539062, 991.007812)
[912231.676] zwp_tablet_tool_v2@4278190083.frame(7987491)
```
In a GNOME session on the same application, the …
=> input/cursor: correctly transfer focus when using tablet pen

sway/config/output.c
Previously in 3de1a39, it "worked by accident" in my testing since the
display being used in `map_to_output` was initialized first (the map
would not be applied because the display hadn't actually come online
yet), and was followed by a second display (at which point the map would
get applied for the first display).
Replacing a monitor with another one surfaced this bug.
Refs #5231
=> config/output: reconfigure input devices after full output init

sway/input/tablet.c
`handle_tablet_tool_set_cursor` was copied from input/cursor.c's
`handle_request_set_cursor`, but the focused surface check was not
adjusted appropriately.
Fixes #5257.
=> input/tablet: query tablet focused surface for cursor image check

ISSUE_TEMPLATE.md
In reading through issues I've noticed that the first developer response is often "you don't have debug symbols". Hopefully including this information in the issue template can help save a round-trip :smiley:
=> Add debug symbol stack trace note to ISSUE_TEMPLATE.md

sway/ipc-json.c, sway/sway-ipc.7.scd
This is a criteria you can use to select windows since commit 484cc189e909 ("Add shell criteria token"), but there's no way to query it for an existing window. This exposes its value in the output of `swaymsg -t get_tree`.
I don't know if this makes sense. Regarding criteria, `sway(5)` says "[y]ou may like to use `swaymsg -t get_tree` for finding the values of these properties", but shell isn't currently reported there. Some of the others aren't obviously included either, though, so maybe the man page just needs changing.
=> [RFC] Add each view's shell to JSON description

include/swaybar/input.h, swaybar/bar.c, swaybar/input.c
This patch implements some logic to try to emulate scrolling in discrete steps for devices which scroll continuously, such as modern touchpads. It keeps track of whether the axis event is discrete or not, so it shouldn't have any effect on switching workspaces with scroll wheels (assuming an axis_discrete event is always fired before an axis event for devices which scroll wheels, which seems to be the case).
This is related to https://github.com/swaywm/sway/issues/1930.
Note that this patch makes swaybar depend on wl_seat v5 instead of v3.
Here's exactly how the decision about whether to switch workspaces or not is done:
``` C
bool do_scroll =
(axis == WL_POINTER_AXIS_VERTICAL_SCROLL && seat->scroll_is_discrete_vertical) ||
(axis == WL_POINTER_AXIS_HORIZONTAL_SCROLL && …
```
=> swaybar: Fix scrolling to switch workspace with precise trackpads

ISSUE_TEMPLATE.md
It is common for user to attach a debug log from the Wayland backend
because they are running the command from inside of Sway. This just adds
a note that the debug logs should be obtained from a TTY. Anyone who is
actually using the Wayland or X11 backends and submitting an issue
related to them likely is already familiar with how to obtain a debug
log for the appropriate backend.
=> ISSUE_TEMPLATE: note debug logs should be from TTY

meson.build
Use the Meson summary() built-in instead of manually formatting a
message.
wlroots already depends on Meson 0.54.0.
=> build: improve feature summary

sway/input/seatop_default.c
Currently, clients receive wl_data_device::leave events only when the
pointer enters another surface, which leads to issues, such as #5220.
This happens because wlr_seat_pointer_notify_enter() is called when
handling motion events only for non-NULL surfaces.
Fixes #5220
=> input/seatop_default: properly notify pointer leave

include/sway/input/cursor.h, sway/input/cursor.c
d88460f addressed sending v2 tool tip up when over a non-v2 surface.
This commit addresses the other direction.
Fixes #5230.
=> input/cursor: release simulated tool tip button when over v2 surface

include/sway/server.h, sway/server.c
This allows the create_output command to work on DRM too.
Depends on ~~https://github.com/swaywm/wlroots/pull/2111~~, ~~https://github.com/swaywm/sway/pull/5215~~ and ~~https://github.com/swaywm/wlroots/pull/2063~~
cc @any1
=> Add a secondary headless backend

include/sway/input/cursor.h, include/sway/input/seat.h, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_default.c
Fixes #5232 and hopefully other tablet bugs.
Will need rebasing after https://github.com/swaywm/sway/pull/5222 is merged.
=> input/cursor: refactor cursor logic for reuse in tablet/touch

include/sway/input/seat.h, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_default.c, sway/input/seatop_down.c, sway/input/seatop_move_floating.c, sway/input/seatop_move_tiling.c, sway/input/seatop_resize_floating.c, sway/input/seatop_resize_tiling.c
This commit renames `motion` and `axis` handlers to `pointer_motion` and
`pointer_axis`, respectively, to disambiguate them from their tablet
(and future touch) handlers. `button` is left as-is, as it is generic
across input devices.
=> input: rename pointer handlers to be unambiguous

sway/input/cursor.c
The type expected by wlroots is uint32_t, which `event->button`
already is.
=> input/cursor: remove erroneous cast for tablet tool button

sway/input/cursor.c
Touch events hide the cursor so unhiding it again only causes it to
flicker (and not hide at all).
=> Don't unhide cursor on touch events

include/sway/input/seat.h, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_default.c
This is a small cleanup commit for removing `sway_tablet` parameters
from functions that already accept `sway_tablet_tool`, since the tablet
reference can be accessed through `tool->tablet`. This makes it
unmistakable that the tablet is tied to a given tool, and removes
any doubt that an unassociated tablet reference can be passed in.
=> input/tablet: simplify parameter plumbing for tablet references

sway/input/cursor.c
Fixes https://github.com/swaywm/sway/issues/5268.
The less-obvious part of this change is in the second commit, with the (unexpected) problem described in its message. By my understanding of the pointer constraint spec this should be correct, but I wouldn't bet on my understanding :)
=> Fix up pointer constraint interaction with tablet input

sway/input/seatop_resize_floating.c
Same problem, different approach.
Fixes: https://github.com/swaywm/sway/pull/5250
I've done testing of all combinations of settings and runtime border changes with resize I could come up with. So far I'm unable to see it brake. More testing is welcome. 
@David96 : please test this instead https://github.com/swaywm/sway/pull/5292, it should resolve your problems.
=> Really fix floating window border resize problems

include/sway/input/cursor.h, sway/input/cursor.c
This implements simulating cursor events if the surface under the cursor hasn't bound to touch events.
A touch down is interpreted as button down, movement moves the cursor with the button pressed and touch up releases it.
I'm not exactly sure about the check for the pointer constraints - my idea was to ignore the touch if it's outside the constraint.
**Edit:** this should now correctly determine whether a surface supports touch events. It depends on https://github.com/swaywm/wlroots/pull/2151
I also removed all pointer constraints checks and added some multi touch handling (all touches except the first one are be ignored).
=> Implement pointer simulation if client hasn't bound to touch

include/sway/commands.h, include/sway/input/seat.h, include/sway/tree/view.h, sway/commands.c, sway/commands/shortcuts_inhibitor.c, sway/input/input-manager.c, sway/input/seat.c, sway/meson.build, sway/sway.5.scd, sway/tree/view.c
Add a separate per-view shortcuts_inhibitor command that can be used
with criteria to override the per-seat defaults. This allows to e.g.
disable shortcuts inhibiting globally but enable it for specific,
known-good virtualization and remote desktop software or, alternatively,
to blacklist that one slightly broken piece of software that just
doesn't seem to get it right but insists on trying.
Add a flag to sway_view and handling logic in the input manager that
respects that flag if configured but falls back to per-seat config
otherwise. Add the actual command but with just enable and disable
subcommands since there's no value in duplicating the per-seat
activate/deactivate/toggle logic here. Split the inhibitor retrieval
helper in two so we can use the backend half in the command to …
=> commands: Add per-view shortcuts_inhibitor command

sway/input/input-manager.c, sway/input/keyboard.c, sway/input/seat.c
Fixes #5358
Keyboard group keyboards should not call sway_keyboard_configure. They
do not have an input config and they derive their state from the
keyboards within the group.
For some reason, I got sway_keyboard_configure and
seat_configure_keyboard mixed up and thought seat_reset_device called
the latter when working on #5317 
Calling sway_keyboard_configure with a keyboard group's keyboard is not
supported and can cause issues. If any clients are listening to the ipc
input event, a sigsegv will occur due to not every property - such as
identifier - being wired up for keyboard group keyboard's.
This also adds an assertion to sway_keyboard_configure to ensure that
this does not occur in the future and any instances are quickly caught.
=> input: fix reloading crash due to keyboard group configuring

sway/sway.5.scd
This makes the formatting more consistent.  It seems \_ is used for variables and \* for commands.
=> sway.5: make formatting more consistent

swaybar/ipc.c
For some reason my version of sway doesn't show workspace names:
$ swaymsg -t get_outputs
Output HDMI-A-1 '(null) (null) (null)' (inactive)
Output HDMI-A-2 '(null) (null) (null)' (inactive)
Which is weird, but it's no reason to crash swaybar. The field is
totally missing from the JSON, so it ends up doing `strcmp(NULL, name)`
which is undefined behavior.
=> swaybar: add NULL check when listing workspaces

include/sway/input/cursor.h, include/sway/input/seat.h, sway/input/cursor.c
Refs #5268.
Sway counterpart to https://github.com/swaywm/wlroots/pull/2191.
=> input/pointer: only warp cursor when the confine region has changed

sway/ipc-json.c
Since #4949, we have better support for marks on non-leaf containers.
But, unlike in i3, these marks did not appear in `get_tree`'s output.
=> ipc: show marks of containers without view in tree

common/log.c
On some terminals under default settings, black is truly rendered as
`#000`, making it unreadable when the background is also black.
Closes #5141.
=> common/log: use bright black rather than black for SWAY_DEBUG

include/sway/input/seat.h, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_default.c, sway/input/seatop_down.c
Depends on https://github.com/swaywm/wlroots/pull/2158.
Currently, when tablet input exits a window during an implicit grab, it
passes focus to another window.
For instance, this is problematic when trying to drag a scrollbar, and
exiting the window &mdash; the scrollbar motion stops. Additionally,
without `focus_follows_mouse no`, the tablet passes focus to whatever
surface it goes over regardless of if there is an active implicit grab.
If the tablet is over a surface that does not bind tablet handlers, sway
will fall back to pointer emulation, and all of this works fine. It
probably should have consistent behavior between emulated and
not-emulated input, though.
This commit adds a condition for entering `seatop_down` when a tablet's
tool tip goes down, and exiting when it goes up. Since …
=> input/tablet: add seatop_down entry for tablet input

sway/input/cursor.c
Fixes #5383, caused by an oversight in 6f0a0bd.
=> input/cursor: fix heap-buffer overflow in constraint set_region

include/sway/input/seat.h, sway/input/cursor.c
`set_region` accepts a `NULL` `*data`, so we can't use it to reference the constraint and find the cursor through its seat.
Fixes #5386.
/cc @emersion, sorry about that, don't know how this didn't fail during my testing...
I've tested this PR with:
```
$ wlroots/build/examples/pointer-constraints confine persistent disjoint-region
```
...and clicked a couple of times to observe `set_region` calls while running with ASan.
An alternative fix is in wlroots, but I recall we didn't want to add a non-`NULL` data parameter to `set_region` yet.
```diff
diff --git a/include/wlr/types/wlr_pointer_constraints_v1.h b/include/wlr/types/wlr_pointer_constraints_v1.h
index 0c49e3bf..d99b92f7 100644
--- a/include/wlr/types/wlr_pointer_constraints_v1.h
+++ b/include/wlr/types/wlr_pointer_constraints_v1.h …
```
=> input/cursor: keep reference to cursor in constraint

sway/server.c
Though unlikely, this commit makes server initialization totally
explicit in the logs.
=> Log Xwayland startup failures

sway/input/cursor.c, sway/input/seatop_default.c
The spec has this to say about sending events on confine creation:
> Whenever the confinement is activated, it is guaranteed that the
surface the pointer is confined to will already have received pointer
focus and that the pointer will be within the region passed to the
request creating this object.
...and on region update:
> If warped, a wl_pointer.motion event will be emitted, but no
wp_relative_pointer.relative_motion event.
Prior to this patch, sway did neither, and updated the hardware cursor
position without notifying the underlying surface until the next motion
event. This led to inconsistent results, especially in applications that
draw their own software cursor.
([Related SDL patch.](https://bugzilla.libsdl.org/show_bug.cgi?id=5151))
=> input/pointer: send pointer enter event on confine warp

sway/ipc-json.c
After swaywm/wlroots#2023, #4996 inverted config inputs to
`transform`. For consistency, we should also communicate inverted
transformations via IPC.
Closes #5356.
=> ipc: invert output transformation when necessary

include/sway/input/cursor.h, sway/input/cursor.c
This is a tiny cleanup commit that renames `simulated_tool_tip_down` to
`simulating_pointer_from_tool_tip`, making it match
`simulating_pointer_from_touch` (that was added later and had more
discussion on naming).
This is a better name since it makes it clear that it's the *pointer*
that's being simulated, not the tool tip.
=> input/cursor: rename `simulated_tool_tip_down` to be more accurate

sway/commands/seat/cursor.c
Fixes #5361 
This emits frame events for the seat_cmd_cursor subcommands. The
wl_pointer frame event are required to notify clients when to process
the events. It will now be emitted after cursor movement, button press,
button release, and axis events.
=> seat_cmd_cursor: emit frame events

include/sway/desktop/idle_inhibit_v1.h, include/sway/tree/view.h, sway/desktop/idle_inhibit_v1.c, sway/ipc-json.c, sway/sway-ipc.7.scd, sway/tree/view.c
Fixes #5286
Following command is an example of scripting to determine whether any view is currently inhibiting the idle state.
Exits with 0 if idle is inhibited, >0 otherwise.
```
swaymsg -t get_tree |
jq -e 'recurse(.floating_nodes[]?,.nodes[]?) | select(.inhibit_idle == true)' > /dev/null
```
=> Add views idle inhibition status in get_tree output

include/sway/tree/container.h, include/sway/tree/view.h, sway/desktop/output.c, sway/desktop/render.c, sway/desktop/transaction.c, sway/desktop/xdg_shell.c, sway/desktop/xwayland.c, sway/tree/view.c
This PR contains a few improvements to the resizing logic:
1. Save all view buffers, including subsurfaces, rather than only the main surface. Fixes subsurfaces disappearing during resize.
2. Ensure that "current" geometry is not trashed, and is used when appropriate. Fixes border/titlebar and content disagreeing on dimensions during resize.
3. Update centering logic to account for complete and current dimensions. Fixes positioning during resize, especially with CSDs.
4. Remove bogus dimensions being tracked on the container state that was no longer useful.
=> Improve resize transactions

sway/input/cursor.c, sway/input/seatop_default.c, sway/input/seatop_down.c
This commit moves tool tip event generation into seatops. In doing so,
some corner cases where we'd erroneously (but likely harmlessly)
generate both tablet and pointer events simultaneously are eliminated.
The resulting code should be easier to understand and verify the
correctness of.
=> input/cursor: refactor tablet tool tip events into seatops

sway/config/output.c, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_default.c, sway/input/seatop_move_floating.c, sway/input/seatop_move_tiling.c, sway/input/seatop_resize_floating.c, sway/input/seatop_resize_tiling.c
We are not allowed to do what we did in #5222 and pass a `NULL` surface wlr_seat_pointer_notify_enter(), and it's causing crashes when an xdg-shell popup is active (see #5294 and swaywm/wlroots#2161).
Instead, solve #5220 using the new wlroots API introduced in swaywm/wlroots#2217.
=> Use new wlroots API for clearing keyboard/pointer focus during grabs

common/util.c, include/util.h, sway/input/cursor.c
This commit makes `get_current_time_msec` correctly return milliseconds
as opposed to microseconds. It also considers the value of `tv_sec`, so
we don't lose occasionally go back in time by one second. Finally, the
function is moved into `util.c` so that it can be reused elsewhere
without having to consider these pitfalls.
=> common/util: fix get_current_time_msec returning microseconds

include/sway/tree/container.h, sway/input/seatop_default.c, sway/input/seatop_move_floating.c, sway/input/seatop_move_tiling.c, sway/tree/container.c
Closes #5293.
This PR "cheats" a bit since tool tips on container titlebars/edges actually go through pointer emulation, so we don't need to implement resizing logic in the tool tip seatop.
=> Implement moving tablet v2 surfaces by pen input

include/swaynag/swaynag.h, swaynag/config.c, swaynag/swaynag.1.scd, swaynag/swaynag.c
I don't love -z / -Z, but I figure this patch is far from being
accepted for other reasons too.
=> swaynag: allow specifying more buttons which execute and dismiss

include/sway/tree/view.h, sway/tree/view.c, sway/tree/workspace.c
=> tree/view: fix smart gaps when ancestor container is tabbed or stacked

swaybar/bar.c, swaybar/status_line.c
`$WAYLAND_SOCKET` is unset by `wl_display_connect` after it has
successfully connected to the wayland socket.
However, subprocesses spawned by swaybar (status-command) don't have
access to waybar's fds as $WAYLAND_SOCKET is O_CLOEXEC. This means any
status command which itself tries to connect to wayland will fail if
this environment variable is set.
Reorder display and status-command initialization so that this variable
is not set and add an assert so we can enforce this invariant in future.
=> swaybar: ensure correct init order for status_line

sway/tree/view.c
Hopefully fixes #5321. I tried reproducing #5309 this morning but got the other crash instead. 
Previously I could somewhat sporadically crash either FF77 or sway by middle clicking. After the patch I tried spamming middle click for a little while and wasn't able to crash either, but I don't have a 100% reliable reproduction method to test with.
Asan seems to indicate the problem was a surface_new_subsurface listener remaining after the popup was destroyed, and in my debug output just before the abort I also have a "New xdg_shell popup" message every 16~17ms it seems which is probably related to whatever triggers the crash. (1 every frame for some reason? My middle mouse button is a bit jank which might cause that, I don't know.)
Small patch, but a first attempt with Asan. PTAL.
=> view: fix surface_new_subsurface use-after-free

sway/tree/view.c
We were registering listeners in `xdg_shell.c` without removing them.
=> Remove view child surface_{map,unmap} listeners on destroy

include/sway/input/keyboard.h, sway/input/keyboard.c
Fixes #4975 
Requires swaywm/wlroots#2229
This adds support for wlr_keyboard_group's enter and leave events. The
enter event just updates the keyboard's state. The leave event updates
the keyboard's state and if the surface was notified of a press event
for the key code, then it is notified of a key release.
=> input/keyboard: wlr_keyboard_group enter and leave

contrib/grimshot
fixes this error:
`/usr/local/bin/grimshot: line 22: [: ==: unary operator expected`
Furthermore, variables should be always quoted. (https://stackoverflow.com/a/13618376)
=> grimshot: Unary operator expected

contrib/grimshot
`source` is not POSIX compliant, '`.`' is.
https://stackoverflow.com/a/11588629
Take together with #5465 
The reason this didn't bubble up before might be that `/bin/sh` resolves to `/bin/bash` for some people?
=> grimshot: fix POSIX compliance

include/sway/input/input-manager.h, sway/config/output.c, sway/input/input-manager.c, sway/input/libinput.c, sway/tree/output.c
Fixes #3449.
---
Tested with a pointer device, since I do not have a libinput recent enough to contain https://gitlab.freedesktop.org/libinput/libinput/-/commit/0d06bfc4e27bf4a56a7f34b3f20c4a61570e765c.
=> input: disable events for map_to_output devices when output not present

sway/input/seat.c
Fixes #5469, a minor regression introduced in #5368.
=> input/seat: don't notify keyboard grabs with NULL surface on shutdown

sway/input/seatop_default.c
This commit addresses a regression introduced in 8fa74ad.
Fixes #5481.
=> input/pointer: correctly handle bindings for synthetic events

sway/tree/view.c
Fixes #5484.
---
Tested states (all match i3-gaps now):
=> tree/view: fix smart borders with tabbed/stacked ancestor

sway/desktop/transaction.c, sway/desktop/xdg_shell.c, sway/desktop/xwayland.c
If a client commits a new size on its own, we create a transaction for
the resize like any other. However, this involves sending a configure
and waiting for the ack, and wlroots will not send configure events when
there has been no change. This leads to transactions timing out.
Instead, just mark the view ready immediately by size when the client
is already ready, so that we avoid waiting for an ack that will never
come.
Closes: https://github.com/swaywm/sway/issues/5490
=> transaction: Mark client resize immediately ready

include/sway/input/seat.h, sway/input/seat.c
wlr_drag installs grabs for the full duration of the drag, leading to
the drag target not being focused when the drag ends. This leads to
unexpected focus behavior, especially for the keyboard which requires
toggling focus away and back to set.
We can only fix the focus once the grabs are released, so refocus the
seat when the wlr_drag destroy event is received.
Closes: https://github.com/swaywm/sway/issues/5116
Depends on: https://github.com/swaywm/wlroots/pull/2306
=> seat: Refocus seat when wlr_drag is destroyed

sway/tree/view.c
It is not a part of the foreign-toplevel-management protocol to get the class of a toplevel, only for getting the app_id.
For xwayland clients this is an issue because that means that you cannot identify what application the toplevel refers to which is the point of the app_id property.
By falling back to class when an app_id does not exist solves this problem.
Phoc also uses app_id and class interchangeably in their implementation of foreign-toplevel-management, in fact they always do that and not only for just this protocol
https://source.puri.sm/Librem5/phoc/-/blob/c8d8a4c5440a6c1647b09dbd3bba7999f9cd433c/src/xwayland.c#L236
=> tree/view: Make foreign-toplevel app_id fallback to class

include/sway/tree/workspace.h, sway/commands/move.c, sway/tree/workspace.c
If moving e.g. `T[app app]` into a new workspace with
`workspace_layout tabbed`, then post-`arrange_workspace` the tree in
that workspace will be `T[T[app app]]`. This still happens with
horizontal or vertical workspace layout, but is less visible since those
containers have no decorations.
Fixes #5426.
=>  commands/move: unwrap workspace container on move to new workspace 

sway/input/seat.c
sway_input_method_relay_set_focus was called before
sway_input_method_relay_init.
Closes: https://github.com/swaywm/sway/issues/5503
=> seat: fix segfault in sway_input_method_relay_set_focus

sway/tree/view.c
xdg-shell doesn't allow clients to set the title to NULL, so we
shouldn't need to call wlr_foreign_toplevel_handle_v1_set_title with an
empty string to reset the old one.
Closes: https://github.com/swaywm/sway/issues/5488
=> tree/view: fix segfault in view_update_title

sway/commands/move.c, sway/tree/container.c
Fixes #5157.
---
I think there are definitely cases I've missed here, but at least Sway does generate compatible layout trees as per the linked issue.
=> commands/move: maintain workspace_layout when moving

protocols/wlr-layer-shell-unstable-v1.xml
Hidden visibility (via `WL_PRIVATE`) doesn't seem to have an effect during static linking. When there're multiple copies the linker doesn't know when to use each definition, so bundled wlroots may end up using protocols/libserver_protos.a.
Fixes https://github.com/swaywm/sway/issues/5515
=> protocols: update wlr-layer-shell-unstable-v1

sway/input/seat.c
As per the Wayland spec [1]:
> The icon surface is an optional (can be NULL) surface that provides an
> icon to be moved around with the cursor.
However, as of now Sway "start_drag" signal handler does not starts the
DND session unless a non-NULL drag icons is provided. This patch fixes
it by skipping handling of the drag icon if it is null.
Fixes #5509
[1] https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_data_device
Signed-off-by: Nick Diego Yamane <nickdiego@igalia.com>
=> seat/dnd: Support null drag icon surfaces

include/sway/config.h, sway/commands/reload.c, sway/config.c, sway/sway.5.scd
Reload Command now loads config file with most priority instead of currently loaded config file
=> Reload Command loads config file in order of priority described in man pages

include/sway/output.h, sway/config/output.c, sway/desktop/output.c, sway/input/cursor.c, sway/tree/output.c
Previously, we called output_disable prior to wlr_output_commit. This
mutates Sway's output state before the output commit actually succeeds.
This results in Sway's state getting out-of-sync with wlroots'.
An alternative fix [1] was to revert the changes made by output_disable
in case of failure. This is a little complicated. Instead, this patch
makes it so Sway's internal state is never changed before a successful
wlr_output commit.
We had two output flags: enabled and configured. However enabled was set
prior to the output becoming enabled, and was used to prevent the output
event handlers (specifically, the mode handler) from calling
apply_output_config again (infinite loop).
Rename enabled to enabling and use it exclusively for this purpose.
Rename configured to enabled, because …
=> config/output: don't change output state before commit

config.in
**Problem**:
When I rename the workspace to something like "1:web", `$mod+1` does not move to the "1:web" with the default config. This breaks the expectation of i3 users.
**Cause**:
The default Sway binding for `$mod+1` does not have the `number` keyword:
```
bindsym $mod+1 workspace 1
```
Instead, the default Sway binding for `$mod+1` is
```
bindsym Mod1+1 workspace number $ws1
```
https://github.com/i3/i3/commit/e6662df114329ba45bd1d117c731b3dc8bdd13fb is the corresponding commit from i3.
=> Make the default workspace commands compatible with i3

config.in
The current configuration of sway contains (as a comment) a call to `swayidle`. However, according to the current manpage of `swayidle`, the command is using an incorrect `resume` flag. This corrects this, so that the `swayidle` example used in the default config is fully functional out-of-the-box.
=> rephrase swayidle-timout example to improve readability

include/sway/tree/container.h, include/sway/tree/view.h, sway/desktop/xdg_shell.c, sway/input/seatop_resize_floating.c, sway/input/seatop_resize_tiling.c, sway/tree/container.c
This PR implements interactive resize hints for xdg_toplevels by setting the resize state on all clients participating in an interactive resize. Should resolve #5411. The issues made it sounds ambiguous, but by my reading of xdg-shell.xml clients _should_ receive a non-resizing configure at the end:
> xdg_toplevel resize request:
> [...]
> After the resize is completed, the client will receive another "configure" event without the resize state.
these resizes don't involve the request, but I think it makes sense.
I made a little test client that turns green when resize hint is set, gif below. PTAL.
=> input: implement xdg_toplevel interactive resize hints

sway/desktop/xdg_shell.c
OK, so I'm pretty sure this is a hack, but hear me out.
I saw some users get caught up about buggy Evince behavior and when searching the old reports found #4593. I think the discussion there is correct, however when I tried to run Evince and reproduce, I can see with `WAYLAND_DEBUG=1 evince` that just before evince hangs (until next configure) it tries `set_maximized`, which obviously shouldn't do anything for a tiled view, BUT sway doesn't send back a configure event. Evince waits until the next configure and continues fine.
Now, I'm pretty sure we're _supposed_ to send one, even if it doesn't do anything, based on the description of set_maximized from the xml:
> After requesting that the surface should be maximized, the compositor
will respond by emitting a configure event. Whether …
=> xdg_shell: schedule configure on maximize requests

swaymsg/swaymsg.1.scd
Argument expansion happens twice when sending commands through `swaymsg`, leading to confusing behavior like #5531 . This PR adds a note to the swaymsg manpage to clarify.
I'm not sure that it's sufficient... may be better to add one on sway-output as well, since that's a common place to see multi-word strings as a single argument (display identifiers).
Closes #5531 .
=> Add note on quoting to swaymsg manpage

contrib/grimshot
In case when slurp is used to select part of screen or a window, if user aborts the selection, grimshot will capture the whole screen instead of exiting. This is fixed with check for empty variable.
This is a duplicate of closed pull request. Previous one had some issues with branches.
=> Add check for empty GEOM variable

README.md
The subproject compilation is the best way to test sway and wlroots but it's hidden. I only found it from comments in issues.
=> readme: link to the development doc

sway/input/cursor.c
On warping to a cursor hint, update the pointer position we track as well, so that on the next pointer rebase we don't send an unexpected synthetic motion event to clients.
Fixes #5405.
---
Refs https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/20, awaiting clarification on that end but figured I should bring up a patch for testing/review earlier. I don't have any games/applications that require this patch, so it hasn't been tested by me (hoping to get someone affected by the issue to give it a shot).
If the plan is to tag Sway 1.5 in the near-ish future, I think we should either (temporarily) revert https://github.com/swaywm/sway/commit/6ea45395c70939a6d855736cabfe75ad9cf4a0ae or apply something along the lines of this patch. The slight cosmetic improvement …
=> input/cursor: don't send wl_pointer.motion event on pointer unlock warp

contrib/_incr_version, meson.build
cc @ddevault @emersion: I'm not sure about this, but it seems like the "v" was added by accident (if not the code would need to be changed).
Version outputs:
```console
$ # Old
$ sway --version
sway version v1.5
$ swaymsg -rt get_version
{
"human_readable": "v1.5",
"variant": "sway",
"major": 0,
"minor": 0,
"patch": 0,
"loaded_config_file_name": "\/home\/nixos\/.config\/sway\/config"
}
$ # New
$ sway --version
sway version 1.5
$ swaymsg -rt get_version
{
"human_readable": "1.5",
"variant": "sway",
"major": 1,
"minor": 5,
"patch": 0,
"loaded_config_file_name": "\/home\/nixos\/.config\/sway\/config"
}
```
=> meson.build: Fix the version format

sway/desktop/output.c
This fixes an issue with wlr-output-management causing the frame rate to
jump to 60000 Hz when setting a custom mode.
=> desktop: output: Scale custom output refresh rate

sway/sway.5.scd
Found this typo while reading the docs, command is `shortcuts_inhibitor` not `shortcuts inhibitor`.
=> sway.5: add missing underscore

swaybar/status_line.c
`determine_bar_visibility` stops and starts the status command process according to the bar’s visibility. If the bar was hidden during teardown, teardown would stall while waiting for the stopped status command process to exit.
This resumes a stopped status command during teardown and allows, for example, sway to reload or quit without leaving a swaybar instance behind each time.
Fixes #5536.
=> swaybar: allow status line cleanup to proceed when hidden

include/sway/tree/view.h, sway/desktop/xwayland.c
Usually it should be enough to simply not grant a client's
minimize request, however some applications (Steam, fullscreen
games in Wine) don't wait for the compositor and minimize anyway,
getting them stuck in an unrecoverable state.
Restoring them immediately lead to heavy flickering ( https://streamable.com/imhyj7 ) when unfocused
on my test application (Earth Defense Force 5 via Steam), so it's
preferable to grant their request without actually minimizing and
then restoring them once they are in focus again.
Should fix https://github.com/swaywm/sway/issues/4324
=> Fix X11 clients getting stuck minimized

sway/tree/view.c
Fix #5572 by showing scratchpad hidden containers when they are activated by ftm.
=> view: display scratchpad hidden containers when activated by ftm

sway/commands/move.c
If the mouse/cursor/pointer is near the edge of an output when a "move
position to pointer" command is run, then the floating container will be
constrained to fit inside the bounds of the output as much as possible.
This behavior matches what i3 does in this scenario. I also think it is
a better user experience.
Relates to #4906
The logic for the bounds check follows the implementation in i3: https://github.com/i3/i3/blob/733077822302d8b77eacb606a26fd002a42f534f/src/floating.c#L536
=> Keep windows in bounds on move to position mouse

sway/sway.5.scd
I believe these asterixis are placed wrongly
=> fix typos in sway.5.scd

sway/commands/force_display_urgency_hint.c, sway/sway.5.scd
=> document force_display_urgency_hint

swaybar/swaybar-protocol.7.scd
The following statusbar output is not considered by sway to be following
the swaybar-protocol:
{"version":1}[[{"full_text":"2.89","urgent":false}],
However this one is:
{"version":1}\n[[{"full_text":"2.89","urgent":false}],
Both outputs contain a header with the required values and an unfinished
array of objects with the required values, but the first one is showed
verbatim.
=> Document required '\n' in swaybar-protocol

include/sway/tree/view.h, sway/tree/container.c, sway/tree/view.c
This pull adds support for the foreign toplevel fullscreen event and request.
By event I mean that previously FTM would not indicate the fullscreen state as set on fullscreen views, so the first commit fixes it to indicate the fullscreen state for fullscreen views.
The second commit handles the FTM set_fullscreen request. It doesn't comply with the output hint, since it's not necessary and I don't have an easy way to test multi-output stuff on my laptop anway. PTAL.
=> Implement foreign toplevel fullscreen

sway/main.c
Gracefully exit on SIGINT, like we do for SIGTERM.
=> Handle SIGINT

include/sway/commands.h, sway/commands/exec.c, sway/commands/exec_always.c
Repro steps:
1. Add `exec` (with no arguments) to your config.
2. Reload sway.
Sway crashes with the "argc should be positive" error from `join_args`.
The `exec` command just calls `exec_always`, however a few shared validation checks should be performed before this call.
=> exec: fix validation during config reload

include/sway/output.h, sway/desktop/output.c
Instead of listening to both transform and scale events, we can listen
to the commit event and use the new wlr_output_event_commit struct to
decide what to do.
This de-duplicates some of the work we were doing twice when an output
was re-configured.
Depends on [1].
[1]: https://github.com/swaywm/wlroots/pull/2315
=> Use wlr_output_event_commit

sway/input/libinput.c
Closes #5654 
This changes it so all libinput config options are set on any device
that supports it. Previously, only a subset of libinput config options
were being considered depending on the input type. Instead of trying to
guess which properties the device may support, attempt to set any
configured property regardless of the device type. All of the functions
already have early returns in them for when the device does not actually
support the property. This brings the configuration side inline with
describe_libinput_device for the IPC side.This change was prompted
by a tablet tool showing the calibration matrix property in the IPC
message, but not being able to actually change it since that property
was only being considered for the touch input type.
=> input/libinput: remove input type property bias

swaymsg/swaymsg.1.scd
Strings with commas inside, such as the ones used for
xkb_{config,layout} commands, count as multi-word strings.
Based on #5039
=> swaymsg.1: expand tip for multi-word strings.

include/swaynag/types.h, swaynag/config.c, swaynag/render.c, swaynag/swaynag.1.scd, swaynag/swaynag.5.scd, swaynag/types.c
adds the `button_text` option, which allows setting a separate RRGGBB[AA] value for the text color of buttons. If not set, the generic text color is used.
example:
```bash
$ ls -a ~/ | ./swaynag -t warning -m "files in home" -L "show..." -l --text=FF0000 --button-text=000000
```
=> swaynag: adds option to separately specify the text color for buttons

sway/desktop/xwayland.c
First I must say that I am not sure if my approach is sound.
My primary issue was IntelliJ IDEA's code suggestion pop-up not returning focus
to the active editing window.
I have spent some time looking at the changes of @Xyene (#5398) and
@RyanDwyer (#2103). I think my proposed change maintains the status
quo for the most part whilst fixing my focus issue.
I have verified that @Xyene's fix for IntelliJ sub-menus still works.
I have done basic testing which consists of:
- Chrome
- IntelliJ IDEA 2020.2.1
- VSCode
- Alacritty
It seems to hold up. I at least didn't see any obvious errors.
Relates to #3007
=> Re-focus on parent surface if it is available

sway/input/cursor.c, sway/input/seat.c
Reset the event source after unhiding the cursor, to ensure that the
timeout starts after showing the cursor. Also remove the open coded
variant in seat_consider_warp_to_focus().
Fixes #5679
=> input/cursor: reset event source after unhide

sway/input/cursor.c
Otherwise, Sway will not re-hide a cursor after the last button has been
released.
Needed alongside afa890e to fix #5679.
/cc @Emantor -- <del>I had tested #5681 by scrolling, which worked correctly
after that patch.</del> Looking a bit deeper into this, this was regressed by 82c439c4f116b36d7d171bcc923b50ead59b4ab2 ([diff](https://github.com/swaywm/sway/commit/82c439c4f116b36d7d171bcc923b50ead59b4ab2#diff-40846134db734aabaf9eb9e98bccab5eL358-L375)),
so just reverting that bit of the patch (which is what this PR does) fixes the issue
by itself.
I think afa890e8e9f10667a56e896a114bf81fbc3ff54a still makes sense, though.
=> input/pointer: update cursor activity after updating button counts

sway/desktop/render.c
i3 shows indicators for the workspace-level pseudo-split, but Sway does
not, as of b977c02. This commit replaces the floating container check
with a call to `container_is_floating`, which has some more robust
checks in place.
Fixes #5699.
=> desktop/render: show indicators for top-level split

sway/commands/move.c
Prior to this commit, having a layout like `T[app1 V[app2]]`, focusing
`app2`, and then doing `move left` would result in `T[app2 app1]`. Now, the
resulting layout is `T[app1 app2]`, which matches i3 behavior.
`container_flatten` updates `container->parent`, meaning that the
existing check would never be true.
=> commands/move: fix single-split escaping on move

include/sway/tree/view.h, sway/desktop/xwayland.c
This fixes https://github.com/swaywm/sway/issues/4600 by destroying the view and recreating it with the correct type (same as this Wayfire patch https://github.com/WayfireWM/wayfire/pull/706 )
I have tested with the Warframe launcher and Dark Souls 3, which both work fine with this.
=> xwayland: support views that change override-redirect status

include/sway/commands.h, include/sway/config.h, include/swaybar/config.h, sway/commands/bar.c, sway/commands/bar/workspace_min_width.c, sway/config/bar.c, sway/ipc-json.c, sway/meson.build, sway/sway-bar.5.scd, sway/sway-ipc.7.scd, swaybar/config.c, swaybar/ipc.c, swaybar/render.c
https://github.com/swaywm/sway/issues/5690 requests support for workspace_min_width in swaybar. This pull requests implements that support.
I am not sure if there are any guidelines to the order/position of items added to existing structs. I tried to make them logical but there is already some discrepancy between the sway and swaybar versions of the config struct.
=> Add support for workspace_min_width bar option.

include/sway/commands.h, include/sway/config.h, include/sway/input/tablet.h, sway/commands/input.c, sway/commands/input/tool_mode.c, sway/config/input.c, sway/input/cursor.c, sway/input/tablet.c, sway/meson.build, sway/sway-input.5.scd
Closes https://github.com/swaywm/sway/issues/4139.
This commit adds a new option to set whether movement of a tablet tool should be treated as absolute or relative; the default is absolute.
Configuration is per-tool, with pen/eraser/brush/pencil/airbrush tools being independently configurable. Mouse and lens tools ignore this setting and are always treated as relative.
Included is a change to switch lens tool input to relative. I don't have such a device to test this, but [the libinput docs](https://wayland.freedesktop.org/libinput/doc/1.11.3/tablet-support.html#tablet-relative-motion) recommend having it as relative by default.
Tested with the pen tool, since that's all I have :)
=> Add a configuration option to set a tablet as a relative input

swaybar/render.c
When swaybar receives the following JSON body
[
{
"full_text": "foo",
"separator": false,
"separator_block_width": 0
},
{
"full_text": "bar"
}
]
it should not draw any separator or any space between the two
blocks. However, since swaybar calculates that `separator_block_width`
0 is too small to fit any configured separator, it will override the
`separator_block_width` with some non-zero value. This patch changes
that such that the necessary `separator_block_width` is only expanded if
the block has `separator: true`.
This should be in line to what i3 does, as its documentation of the i3bar
protocol for `separator` states that
> [...] if you disable the separator line, there will still be a gap after the block, 
unless you also use `separator_block_width`.
To reproduce, set your sway bar …
=> swaybar: don't expand separator_block_width if separator is false

sway/input/seat.c
This causes sway to use the default output mapping for input device even when there is no applicable input config.
The motivation here is to fix #5638, in which pointer coordinates in individual Wayland backed outputs are incorrectly interpreted as in the coordinate space of the abstract output plane. With this commit each pointer is mapped to it's own output which fixes the offset.
=> seat: use default output mapping if there is no input config

include/sway/tree/view.h, sway/desktop/xwayland.c
Closes #5735, refs #3007.
This makes the "Search everywhere" dialog in JetBrains IDEs movable. (Thanks @ammen99!)
=> xwayland: listen to `set_geometry` event

sway/input/seatop_move_tiling.c
At the moment moving windows with the tiling drag feature doesn't emit ipc events, but I think it probably should.
It looks like the swap command doesn't currently emit a window move event, so I've just added a window move event to the actual move action of a tiling drag, not the swap.
=> tiling_drag: emit window move ipc events

sway/desktop/transaction.c
Sway logical coordinates are doubles, but they get truncated to integers
when sent to Xwayland through `xcb_configure_window`. X11 apps will not
respond to duplicate configure requests (from their truncated point of
view) and cause transactions to time out.
Fixes #5035.
=> transaction: don't reconfigure X views unless integral coords changed

include/sway/desktop/transaction.h, sway/desktop/transaction.c, sway/desktop/xdg_shell.c, sway/desktop/xwayland.c
Xwayland views are aware of their coordinates, so validating transaction
completions should take into account the reported coordinates of the
view. Prior to this commit they didn't, and matching dimensions would
suffice to validate the transaction.
Also introduced `transaction_notify_view_ready_immediately` to support
the fix from d0f7e0f without jumping through hoops to figure out the
geometry of an `xdg_shell` view.
=> transaction: validate X transaction completions by geometry, not size

sway/desktop/transaction.c
Sway maintains a list of pending transactions, and tries to merge
consecutive transactions applying to the same views into one. Given
a pending transactions list on views `{A, B, C}` of:
A -> A' -> A'' -> B -> B' -> B''
Sway will collapse the transactions into just `A'' -> B''`. This works
fine when doing things like resizing views by their border. However,
when interactively resizing layouts like `H[V[A B] C]`, we end up with
pending transaction lists like:
A -> B -> C -> A' -> B' -> C' -> A'' -> B'' -> C''
Previously, Sway would not be able to simplify this transaction list,
and execute many more transactions than would be necessary (the final
state is determined by `{A'', B'', C''}`).
After this commit, the transaction list gets simplified to `A'' -> B'' ->
C''`,
resolving performance …
=> transaction: make transaction collapsing smarter with > 2 views

sway/input/seatop_resize_tiling.c
Fixes #5746 
It would be possible not to abandon the resize if we want by calculating which containers will become the new siblings and setting the resize hints on those. I started writing that patch but then I thought "who cares?" It doesn't seem like a sibling container closing during a tiling resize will be a common case and the user can easily just restart the resize themselves.
If you care, let me know and I'll get back to writing that patch. Otherwise, here's the easy fix.
=> tiling_resize: abandon resize if a sibling con dies

sway/commands/resize.c
A "resize shrink width 1px" will cause grow_x to be 0 while grow_width is -1,
incorrectly rejecting the command even though the resize is not a noop.  Fix
this by checking width/height instead of x/y.
=> commands/resize: don't consider 1px resizes to be invalid

sway/commands/move.c
Fixes #5707.
Yet another bug with scratchpad hidden split containers. Children of sphsc need to be shown before we move them. This change also stops calling root_scratchpad_show for non-hidden scratchpad containers, but afaict that's redundant anyway so the behavior should be the same.
=> commands/move: fix crash when moving sphsc child

sway/tree/container.c
Reset the workspace layout to the output's default only if the workspace
is actually attached to an output.
Fixes #5762
=> container: Fix NULL pointer dereference

sway/tree/view.c
Currently, in view_autoconfigure, the only condition for show_border
is !view_is_only_visible. view_is_only_visible does not cross the
boundary between the workspace's tiling and floating lists and does not
differentiate between them.
The result is, that in a workspace with zero or more tiling containers
and a single floating container, the floating container will lose its
borders as soon as it is split, provided that a only one view is visible
within the floating container.
To test the current behaviour, enable smart borders and open a single floating container
and split the container. It will lose its borders unless a sibling is created
and the layout is either horizontal or vertical. Opening a second floating
container will restore the borders.
Fixed by adjusting the condition for …
=> Smart borders fix: always show borders for floating containers

include/sway/tree/workspace.h, sway/tree/output.c, sway/tree/workspace.c
Sticky floating containers on an otherwise empty workspace can only be
evacuated if the new output has an active workspace. The noop output may
not have one and in that case we have to move the whole workspace to the
new output.
=> output: evacuate sticky containers only if new output has a workspace

sway/tree/container.c
Currently, when a floating container with a view is split and children are added to it, the new views are rendered as tiled, while the first view stays in floating style.
Here this is addressed by setting the view to tiled as soon as the container is split, by duplicating the "view part" of the logic in container_set_floating(..., false). Since the new container of the view is no longer considered floating, it makes sense to set the view to tiling at this point.
The view would have to be set back to floating if it was possible to "unsplit" the container (see "split none" when it gets implemented).
=> In container_split, set a floating container's view to tiled

sway/tree/output.c
The function evacuate_sticky() was changed in commit 32788a93 to be used
by workspace_for_each_container() to make the code more readable. But I
overlooked that it is not safe to use workspace_for_each_container() to
remove container from a workspace. This commit restores the previous
implementation for evacuate_sticky().
=> output: Revert implementation of evacuate_sticky()

include/sway/config.h, include/sway/input/cursor.h, sway/commands/seat/hide_cursor.c, sway/config/seat.c, sway/input/cursor.c, sway/input/keyboard.c, sway/sway-input.5.scd
Add an option for the `hide_cursor` command to hide the cursor when typing, i.e. whenever a key is pressed.
The format of this new option is `seat <name> hide_cursor keyboard enable|disable`. This is in addition to the existing format of this command for setting the timeout, which still works the same. Combining both to hide the cursor either when typing or after a some time of inactivity is also possible.
This is supposed to have a similar behavior to using [xbanish](https://github.com/jcs/xbanish) or `unclutter -keystroke` on X.
=> Add an option to hide the cursor when typing

include/sway/input/seat.h, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_default.c, sway/input/seatop_down.c, sway/input/seatop_move_floating.c, sway/input/seatop_move_tiling.c, sway/input/seatop_resize_floating.c, sway/input/seatop_resize_tiling.c
Straightforward cleanup, they haven't been used for a while.
=> input: remove motion deltas from seatop callbacks

sway/input/seatop_default.c
When scrolling on a tabbed/stacked container, i3 focuses its
inactive-focused child. Sway does the same, but then resets the
focus to whatever was focused previously.
Ref https://github.com/i3/i3/blob/e5992eed163179f5cd2715c2c212d3d757f04b31/src/click.c#L207-L219
=> input: fully change focus when scrolling tabs/stacks

include/sway/input/cursor.h, sway/commands/focus.c, sway/input/cursor.c, sway/input/seat.c
This commit switches focusing behavior to force a warp when executing
`focus mode_toggle`.
Fixes #5772.
=> commands/focus: force container warp when fulfilling `focus mode_toggle`

sway/input/seatop_default.c
Previously, `find_edge` on a single fullscreen view would occasionally
return an edge rather than `WLR_EDGE_NONE`*. This would trigger entry
into `seatop_resize_tiling`, which doesn't have meaning for a fullscreen
view.
The result was that the fullscreen container hitbox was considered to be
that of where it'd be if it were tiling, so most clicks would not go
through.
Fixes #5792.
\* I suspect this to be due to floating point imprecision in `find_edge`,
but I didn't dig too deeply.
=> input/seatop_default: consider fullscreen views to have no edges

include/sway/tree/container.h, sway/commands/move.c, sway/commands/sticky.c, sway/input/seat.c, sway/tree/container.c, sway/tree/view.c, sway/tree/workspace.c
To query whether a container is sticky, checking `con->is_sticky` is
insufficient. `container_is_floating_or_child` must also return true;
this led to a lot of repetition.
This commit introduces a `container_is_sticky` function, and switches
all stickiness checks to use it. (Including ones where the container is
already known to be floating, for consistency.)
=> tree/container: introduce `container_is_sticky`

sway/input/keyboard.c
Fixes #5800 
The keyboard group's effective keyboard layout was never being changed
due to a condition that incorrectly preventing it from being performed.
The IPC event that follows the change was correctly being prevented.
=> input/keyboard: fix Group# bindings for keyboard groups

common/stringop.c, include/stringop.h, sway/criteria.c
_Copy of the main commit message:_
For each following combinations of criteria & command below, the command would
crash sway without the fix.
It's particular about the __focused__ criteria, where the view matches part of
the criteria but not the focused app, leading to a failure when calling
`strcmp` with NULL.
"xterm" is a non-wayland app (X11) and "kitty" is. Both are terminals.
for_window [class="__focused__"] floating enable
exec kitty -e xterm
for_window [app_id="__focused__"] floating enable
exec xterm -e kitty
for_window [title="__focused__"] floating enable
exec xterm -title "" -e xterm
**EDIT:** Applied more fixes as suggested
=>  criteria: fix crash when comparing NULL properties

include/sway/layers.h, sway/desktop/layer_shell.c
Damage subsurfaces created by layer surfaces on map, unmap and
commit. This fixes the flicker of Gtk Popovers.
Can be tested with gtk-layer-demo from https://github.com/wmww/gtk-layer-shell
Fixes #5617
=> Add layer shell subsurfaces

.builds/archlinux.yml, include/swaybar/tray/tray.h, meson.build, meson_options.txt, swaybar/meson.build
See https://github.com/emersion/basu
=> Add support for basu

sway/main.c
Instead of letting wlroots print messages to stdout, route debugging
messages into Sway's logging functions. This allows a more consistent
output (e.g. if Sway or wlroots changes its output style, they don't get
out-of-sync).
I also added a [wlr] prefix to wlroots messages, not yet sure it's a
good thing.
=> Route wlroots logs into Sway logging infrastructure

include/swaybar/tray/tray.h
Meson's generated config.h header defines false macros as 0, not
undefined.  This means that the header line, which was checking for the
definition existing, not a non-zero value, was incorrect.  Now the
swaybar tray can be used with systemd, elogind, or basu.
=> Fix swaybar tray for non-systemd

.github/ISSUE_TEMPLATE/bug_report.md
Mention that the github wiki may contain outdated information scripts
and old workarounds and that sway the sway project does not provide
support for it.
=> ISSUE_TEMPLATE: the wiki is community maintained

README.md
This avoids cluttering the README text with URLs.
[GitHub's rendered diff](https://github.com/swaywm/sway/pull/5894/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) can help making sure the links didn't change. I simplified the language links, removing a broken anchor.
=> readme: use references for links

sway/desktop/output.c
This avoids some log spam.
Eventually when we wire up the atomic test commit this will take care of
the other log spam referenced below.
References: https://github.com/swaywm/sway/pull/5010
References: https://github.com/swaywm/wlroots/issues/2181
Closes: https://github.com/swaywm/wlroots/issues/2532
=> Test output before direct scan-out

include/sway/tree/container.h, include/sway/tree/workspace.h, sway/commands/layout.c, sway/commands/move.c, sway/commands/split.c, sway/desktop/xdg_shell.c, sway/input/seatop_move_tiling.c, sway/sway.5.scd, sway/tree/container.c, sway/tree/output.c, sway/tree/view.c, sway/tree/workspace.c
EDIT: Hijacking top comment b/c this PR is barely related to what it started as anyway
Hey you. Lurker. Please test.
---
Fix #5755 
This is intended to match i3's behavior here:
https://github.com/i3/i3/blob/3cd1c45eba6de073bc4300eebb4e1cc1a0c4479a/src/tree.c#L354
=> Rework split, layout, workspace_layout, and move commands to work like i3

sway/tree/container.c
Fixes #5905
Previously the new fullscreen container would fail to focus because of a check for "obscured by fullscreen view" in seat_set_focus, but the container here is itself the fullscreen view. Thats a bug in it's own right, and it incidentally fixes the crash.
The crash happens because when the scratchpad window is dismissed the focus logic again fails to re-set focus to the previous focus behind the newly fullscreened view (so the scratchpad hidden window retains focus, a guaranteed crash).
Aside:
In my experience, focused scratchpad windows are a common source of fatal crashes in sway. I think the \*set_focus\* functions really ought to return a bool or maybe a pointer to the node they focused so the caller can do something intelligent when it fails to find a proper focus. We …
=> container: set fullscreen mode before attempting focus

.builds/freebsd.yml
Avoid swaybar tray growing dependencies not supported by elogind and basu.
https://github.com/swaywm/sway/blob/7c9706de7186f32159f719e3f15fcdc017a13f35/.builds/alpine.yml#L31
https://github.com/swaywm/sway/blob/7c9706de7186f32159f719e3f15fcdc017a13f35/.builds/archlinux.yml#L28
=> ci: enable basu on freebsd

sway/commands/move.c
Fixes #5925
Since e95c299f the sibling swap case is handled by container_move_to_container_from_direction which may list_swap instead of inserting the child, so we need a call to update the container repr in this case. Previously container_insert_child handled that.
=> cmd_move: update container representation in sibling swaps

include/sway/output.h, include/sway/tree/view.h, sway/desktop/output.c, sway/desktop/render.c, sway/desktop/xdg_shell.c, sway/tree/view.c
Instead of calling wlr_xdg_surface_for_each_popup and then
wlr_surface_for_each_surface, use the new for_each_popup_surface helper
introduced in https://github.com/swaywm/wlroots/pull/2609 that does it in one go.
=> Switch to wlr_xdg_surface_for_each_popup_surface

swaymsg/main.c
The fractional part of the real number we want to represent never has more than 3 decimal digits, so use 3 decimal digits of precision.
e.g. 'swaymsg -t get_outputs' would show a refresh rate of 59934 mHz
as 59.933998 Hz, now correctly as 59.934 Hz.
It was previously cast as a float, probably because that's how the output_config represents it, but printf only prints doubles anyway so that seems kind of pointless.
=> swaymsg: use 3 digits for fractional part of the refresh rate

sway/config/output.c
When we apply the configured refresh rate in set_mode the mHz value is calculated as:
```c
int mHz = (int) (1000 * refresh_rate)
```
where `refresh_rate` is a float with value `(mHz / 1000.f)`. Well, not all 6-digit integers can be represented as `(int) (1000 * (mHz / 1000.f))`, because the `(int)` cast truncates towards zero.
e.g. 64340 mHz is unrepresentable:
```c
(int) (1000 * (64340 / 1000.f)) == 64339
(int) (1000 * (64341 / 1000.f)) == 64341
```
I find 739 integers ≤ 100000 have this property. The float value is less than the target integer by at most 1/2 the maximum floating-point epsilon on the interval we care about. For 32-bit floats and mHz ≤ 300000 (300Hz), that means 1/64.
So a 1/64 nudge would be enough, but I figure a 1/2 nudge won't hurt. None of the non-representable mHz …
=> config/output: correct refresh rate rounding error

sway/tree/view.c
When mapping an X11 view the focus state should be retrieved via the
existing mechanisms to determine focus. For certain views if this check
is not completed they will have initial focus when it is undesired.
Relates to swaywm/wlroots#2604
=> Adhere to X11 focus requirements

sway/tree/view.c
Closes #5637
This feels a bit too simple, but I think this should be enough.
=> Implement foreign toplevel fullscreen output hint

sway/desktop/output.c
wlr_output_configuration_head_v1_create normally fills out the head
"enabled" field to match the wlr_output state. We overwrite this to also
set the head as enabled if it is only turned off with DPMS.
However, in some cases we may not have a mode for this display, in which
case setting it as enabled will lead to a segfault later on. Therefore,
enabled conditional on the presence of a mode.
Fixes: https://github.com/swaywm/wlroots/issues/2199
=> desktop/output: Disable head if mode is NULL

sway/desktop/layer_shell.c
Since `sizeof(struct sway_layer_surface) > sizeof(struct sway_layer_subsurface)`, the allocation size mismatch fixed by this PR is currently not a problem.
=> desktop/layer_shell: Fix allocation type mismatch

sway/tree/root.c
Steps to reproduce:
1. Run a process that takes some time to open a view (e.g. a bash script runs on workspace 2 and sleeps for a few seconds before executing something else).
2. Disable the output on which the process started.
In this case Sway re-creates the workspace on the disabled output. If you go to workspace 2 after that, there appears one more workspace 2 on the enabled output.
=> Check the output state for recorded workspaces

sway/server.c
Updated original xdg-foreign commit with changes from swaywm/wlroots#2487.
Tested with [portal-test](https://github.com/matthiasclasen/portal-test) flatpak.
=> xdg-foreign: add v1 and v2 implementations

include/sway/commands.h, sway/commands.c, sway/commands/bar.c, sway/commands/bar/colors.c, sway/commands/input.c, sway/commands/mode.c, sway/commands/output.c, sway/commands/seat.c, sway/main.c, swaybar/bar.c, swaybar/input.c, swaybar/main.c, swaymsg/main.c, swaynag/config.c, swaynag/swaynag.c
There are three groups of variables which this PR makes static const.
* Lists of command handlers
* The Wayland request listeners
* The option lists passed to getopt_long
I'm fairly certain that these are all the variables which should be static const; I checked with ``objdump -t `which sway` | grep "\.data" `` to find initialized global (or function static) variables that were not linked as relocatable read-only, and did not find any others which could be fixed.
=> Add static+const qualifiers

swaynag/swaynag.c
Only wl_pointer.motion was used to update pointer position, which would
cause issues if the pointer was not moved prior to wl_pointer.button.
This also fixes touch input through wl_pointer emulation, which fires
wl_pointer.button immediately after wl_pointer.enter.
Closes: https://github.com/swaywm/sway/issues/5991
=> swaynag: Use position from wl_pointer.enter

sway/commands/bind.c, sway/input/cursor.c, sway/input/keyboard.c, sway/input/seatop_down.c, sway/input/seatop_move_floating.c, sway/input/seatop_move_tiling.c, sway/input/seatop_resize_floating.c, sway/input/seatop_resize_tiling.c, sway/input/switch.c
There is no need to check for transactions at the end of every user
input, as the vast majority of input will not issue transactions. This
implementation can also hide where changes are made without an
appropriate transaction commit, as a future unrelated input would issue
the commit instead.
Instead, commit transactions in places where changes are made or are
likely to be made.
=> input: Only commit transactions when necessary

sway/input/seatop_default.c
This is needed for focus_follows_mouse, and was accidentally omitted in
the previous transaction commit shuffle.
=> input: Commit transactions in seatop_default

sway/input/text_input.c
Before this commit, there would be cases where focus changes from one
window to another, the new window activates text_input, then the old
window sends a deactivate request, making text_input unfocused
completely.
=> text_input: Ignore text_input disable from unfocused windows

sway/input/text_input.c
Allows the input method to detect if these are not supported.
~~Depends on https://github.com/swaywm/wlroots/pull/2735~~
=> text_input: Only send surrounding_text and content_type if supported

include/sway/server.h, sway/desktop/transaction.c, sway/server.c
The transaction system contains a necessary optimization where a popped
transaction is combined with later, similar transactions. This breaks
the chronological order of states, and can lead to desynchronized
geometries.
To fix this, we replace the queue with only 2 transactions: current and
pending. If a pending transaction exists, it is updated with new state
instead of creating additional transactions.
As we never have more than a single waiting transaction, we no longer
need the queue optimization that is causing problems.
Closes: https://github.com/swaywm/sway/issues/6012
=> transactions: Amend pending transactions

sway/input/seat.c
Without this, text-input focus stays on the last focused non-layer-shell surface.
=> text_input: Add support for focusing layer-shell surfaces

contrib/inactive-windows-transparency.py
When running swaylock, no workspace is focused, so the script `inactive-windows-transparency.py` fails with the following stacktrace:
```
'NoneType' object has no attribute 'workspace'
Traceback (most recent call last):
File "/home/pat/.config/sway/bin/opacity", line 64, in <module>
ipc.main()
File "/usr/lib/python3.9/site-packages/i3ipc/connection.py", line 514, in main
raise loop_exception
File "/usr/lib/python3.9/site-packages/i3ipc/connection.py", line 497, in main
while not self._event_socket_poll():
File "/usr/lib/python3.9/site-packages/i3ipc/connection.py", line 477, in _event_socket_poll
raise e
File "/usr/lib/python3.9/site-packages/i3ipc/connection.py", line 474, in _event_socket_poll
self._pubsub.emit(event_name, event)
File …
```
=> Prevent script to crash on lockscreen

sway/input/seatop_default.c
See commit description.
I hope I didn't miss anything.
=> Add missing transaction commits to seatop_default

meson.build
Instead of manually parsing header files and having two different
code-paths depending on whether a subproject is used, use
dependency variables which can come from either the subproject or
pkg-config.
References: https://github.com/swaywm/wlroots/pull/2734
=> build: use wlroots dependency variables

sway/desktop/transaction.c
This is because popup iteration is based on `container->surface_x` and `container->surface_y`, which are only set after the new location is damaged.
To reproduce:
- Open a floating window and a popup that hangs over the bottom or right
- Move the window in the direction of the popup overhang
- The previous position of the popup is damaged, not the new one
=> Fix incorrect damage being applied on popups

sway/desktop/render.c
When a container straddles multiple outputs, the title bar is only rendered
at the scale of the "effective" output. If the title bar straddles onto
another output with a different scale factor, it was drawn at the wrong size.
In this commit, we take into consideration the scale the title was rendered
at and scale it accordingly so that it appears at the right size on the other
outputs.
This fixes #6054.
=> render: scale titlebars correctly when straddling outputs

include/sway/tree/container.h, sway/desktop/render.c, sway/tree/container.c
Needed to check if containers are currently floating from render code,
as container_is_floating checks pending state.
=> container: Add container_is_current_floating

sway/tree/view.c
When a popup had a subsurface, view_child_init would fail to set the parent link, leading to the subchild not being able to extract the xdg_popup location.
Includes a fix to check child mapping recursively in order to ensure that we don't try to damage a subsurface before its parent is mapped, as well as an unmapping fix to ensure that we don't try to damage a subsurface *after* its parent has been unmapped and unlinked (which is neither needed nor possible, as the parent is required for position to be known).
Closes: https://github.com/swaywm/sway/issues/6038
=> Ensure view children have their parent set

sway/desktop/output.c, sway/desktop/render.c
Currently, various floating-point expressions involving the coordinates of borders, title bars and content surfaces are directly assigned to integers, and so they are rounded towards zero.
This results in off-by-one distances between these elements when the signs of their coordinates differ.
The glitches are easier to see with semitransparent borders and title bars, where one can see that they can overlap with the content surface when it enters an area with a negative coordinate. 
Fixed by wrapping these expressions with a call to floor before the assignment.
=> Fix #5643, #5064: rounding issues in floating-point -> integer conversions

contrib/grimshot, contrib/grimshot.1, contrib/grimshot.1.scd
Swappy is a great screenshot annotation tool that expects input in STDIN.
Support tools like that by adding an option to pipe the output to STDOUT.
Example syntax:
grimshot pipe area | swappy -f -
=> grimshot: add a pipe mode

include/sway/desktop/transaction.h, sway/desktop/transaction.c, sway/desktop/xdg_shell.c, sway/desktop/xwayland.c
Avoid transactions if a resize is client-initiated.
Closes: https://github.com/swaywm/sway/issues/5857
=> Avoid configure events on client-initiated resize

meson.build, sway/meson.build
As of 66343839b146a54505b746784cd42a8efb844963, sway now uses a
libdrm header. Add this dependency to the build system so headers from
it can be used on systems where pkg-config is required to find them.
(Encountered on NixOS.)
=> build: Add dependency on libdrm

sway/config/output.c
Before this commit, when an output had its scale dynamically changed,
Sway would not load a cursor theme with the new scale. This results
in stale cursor images when moving the cursor into an area controlled
by the compositor, like the background or resize areas.
To reproduce:
- Using IPC, set an output scale to a value that isn't currently used
- Move the cursor into a compositor-controlled area
- The cursor will not change
=> output: Reconfigure xcursor when applying output config

include/sway/tree/container.h, sway/desktop/render.c
In e0a94bee8da3271f942c0881ee18a7e2d4138063, it was believed that if the
container is being rendered, it must have an output.
This turned out not to be the case. When rendering a container, all its
children are rendered, even if the children is positioned off screen and
thus not having any output. This is the cause of the crash in #6061.
This commit introduces a null-check, which fixes #6061.
=> render: handle containers without output when rendering titles

include/sway/input/libinput.h, meson.build, sway/input/libinput.c, sway/input/seat.c, sway/meson.build, sway/sway-input.5.scd
Detect whether an output is built-in via its type. Detect whether
a touchscreen/tablet is built-in via its ID_PATH property.
=> Automatically map built-in touchscreens/tablets to built-in panels 

include/sway/tree/container.h, sway/commands/focus.c, sway/input/seat.c, sway/tree/container.c
When issuing a focus command on a specific container, users expect to proceed it even if is hidden by a fullscreen window.
This matches the behavior of i3.
Reported by @markstos: https://github.com/lbonn/i3-focus-last/issues/5
=> focus: beyond fullscreen when focused explicitly

include/sway/config.h, sway/commands.c, sway/commands/scratchpad.c, sway/commands/unmark.c
Previously, the special case handling of scratchpad and unmark commands
was (probably accidentally) limited to criteria directly handled in the
execute_command function. This would exclude: 1. for_window criteria, as
these are handled externally for views and 2. and mouse bindings which
select target the node currently under the mouse cursor.
As a concrete example `for_window [app_id="foobar"] move scratchpad,
scratchpad show` would show (or hide due to the toggling functionality)
another window from the scratchpad, instead of showing the window with
app_id "foobar".
This commit replaces the "using_criteria" flag with "node_overridden"
with the more general notion of signifying that the node (and
container/workspace) in the current command handler context of the sway
config is not defined …
=> Fix for_window criteria and mouse button bindings

sway/desktop/render.c, sway/tree/container.c
This draft PR attempts to clip surfaces to their configured size if applicable.
Works by clamping box dimensions to the view size with fmin. Maybe we could just use the view width/height instead and flat out ignore the surface dimensions.
=> Clip surfaces to container

sway/desktop/output.c
Note that now data.{width,height} are set to the layer surface's size, not to an xdg_surface's. Not sure if it's important, but it seems to work correctly anyway.
=> output: simplify layer surface iteration

sway/desktop/xwayland.c
No need to grab the xwayland surface from the wlr_surface, the
parent is already an xwayland surface.
=> xwayland: simplify override-redirect focus restoration

include/sway/input/text_input.h, sway/input/keyboard.c, sway/input/text_input.c
This implements input-method-unstable-v2 keyboard grab.
Depends on: ~~#4740~~, ~~swaywm/wlroots#1864~~
=> Implement input method keyboard grab

swaybar/tray/item.c
`IconThemePath` is not a standard property in XDG's StatusNotifierItem specification, so missing this property should not be logged as an error.
This patch changes the log level to `SWAY_DEBUG` when `swaybar` queries the value of `IconThemePath` so that `swaybar` won't log the returned message as an error if `IconThemePath` does not exist. It's a quick fix and may not look nice though...
Now, if users want to see the return message regarding `IconThemePath`, they'll have to enable the debug flag, like `swaybar -b bar-0 --debug`.
=> resolve #6092: silence IconThemePath message

swaybar/input.c
Only wl_pointer.motion was used to update pointer position, which would
cause issues if the pointer was not moved prior to wl_pointer.button.
This also fixes touch input through wl_pointer emulation, which fires
wl_pointer.button immediately after wl_pointer.enter.
Copied from a similar fix made to swaynag.
Closes: https://github.com/swaywm/sway/issues/6109
=> swaybar: Use position from wl_pointer.enter

include/sway/desktop/idle_inhibit_v1.h, sway/desktop/idle_inhibit_v1.c, sway/tree/view.c
Should fix a dangling sway_view pointer in between view unmap and inhibitor destroy, which could cause issues if inhibition is checked in between.
As a bonus, we should now support idle inhibitors persisting across surface remap.
I still haven't managed to reproduce the original issue, so it would be nice if we could have someone experiencing problems test it.
Closes: https://github.com/swaywm/sway/issues/5325
Closes: https://github.com/swaywm/sway/issues/5680
Closes: https://github.com/swaywm/sway/issues/6091
Closes: https://github.com/swaywm/sway/issues/6103
Supersedes https://github.com/swaywm/sway/pull/6104
=> idle_inhibit: Store wlr inhibitor instead of view

swaybar/ipc.c
There's no inherent limit on the nesting Sway can generate, and the
default used by `json_tokener_new`, 32, can plausibly be hit during
regular usage.
Fixes #6115.
=> swaybar: use INT_MAX max JSON depth when parsing IPC response

swaybar/ipc.c
This commit adds missing error-handling to the creation of the tokener
instance. The stack depth parameter is used to initialize an array that
json-c prefaults ahead of time, causing INT_MAX to result in out of
memory errors.
Also drop the depth to 256 to prevent this OOM.
Though this fix is not very satisfactory -- json-c could be made to
not prefault -- it should do for now. At the very least, swaybar will
not crash.
Fixes #6126.
=> swaybar: fail gracefully on tokener creation fail

sway/tree/view.c
Necessary NULL checks had been added to xdg_shell and xwayland surfaces,
but subsurfaces had been missed.
=> view: subsurface NULL check in view_from_wlr_surface

sway/commands/output/dpms.c, sway/sway-output.5.scd
Logic that obtains current DPMS state is put inside the handler.
sway_output from which the current DPMS state will be obtained is selected by the following logic:
* For `-` and `--` the focused output is used;
* For `*` error "Cannot apply toggle to all outputs" is reported;
* For everything else all_output_by_name_or_id() is used.
Fixes #5929.
=> Add toggle logic inside DPMS handler

sway/config.c
Backport configpath building from xdg-desktop-portal-wlr.
=> config: allow whitespaces in config path

sway/desktop/output.c
=> output: damage whole output when exiting scanout

contrib/autoname-workspaces.py
Same as in [this line](https://github.com/swaywm/sway/blob/master/contrib/autoname-workspaces.py#L26), fix the TypeError when  class_name is of type `NoneType`.
=> contrib/autoname-workspaces.py: fix type error when class_name none

sway/main.c
Can be useful to make sure a bugfix is included. In the future maybe
the wlroots version string could include a commit hash when built
from source, too.
=> Log wlroots version on startup

sway/desktop/layer_shell.c
Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>
=> desktop/layer_shell.c: Fix misspelled "exclusive"

sway/desktop/layer_shell.c
Fixes #6160. Tested it with the mako patch mentioned in the issue.
=> desktop/layer_shell: fix centering for opposing anchors

sway/commands/fullscreen.c
#6152 fixes fullscreen split containers to better match i3 visually.
For commands, using the fullscreen command on a child of a fullscreen split container should fullscreen that child, rather than just unfullscreen the parent.
I've also noticed that i3 seems to refuse move commands that add a child to a fullscreened container, but I've left that alone for now.
=> cmd_fullscreen: allow fullscreen on fullscreen split containers

sway/commands/bar.c
If any error is encountered during execution of the first subcommand of
a freshly created bar configuration, parsing apparently is to be aborted
and the current bar config is freed. The pointer to that memory is left
dangling though, leading to a use-after-free on successive bar
subcommands. This quite reliably ends in a crash like so:
```
sway -c reproducer.config
00:00:00.083 [sway/config.c:865] Error on line 2 'foo bar': Unknown/invalid command 'foo' (s)
free(): double free detected in tcache 2
00:00:00.608 [swaynag/swaynag.c:451] failed to register with the wayland display
Aborted (core dumped)
```
Minimal reproducer config:
```
bar {
foo bar
position top
}
```
Other messages:
```
malloc(): unaligned fastbin chunk detected
double free or corruption (fasttop)
```
The invalid command …
=> Prevent use-after-free on first bar subcommand error

sway/tree/view.c
remove view from its own unmap event listener so when subsurfaces
link try to remove themselves they won't run into it.
This fixes the following ASAN use-after-free error on a build slightly
modified to instrument wl_list operations:
```
==71705==ERROR: AddressSanitizer: heap-use-after-free on address 0x6160000829a0 at pc 0x000000508eb7 bp 0x7ffec8fd8030 sp 0x7ffec8fd8028
WRITE of size 8 at 0x6160000829a0 thread T0
#0 0x508eb6 in wl_list_remove ../common/list.c:181
#1 0x4f4998 in view_child_destroy ../sway/tree/view.c:1131
#2 0x4f38fa in subsurface_handle_destroy ../sway/tree/view.c:946
#3 0x7fda50744892 in wlr_signal_emit_safe ../util/signal.c:29
#4 0x7fda5072f0dd in subsurface_destroy ../types/wlr_surface.c:649
#5 0x7fda507312c4 in subsurface_handle_surface_destroy …
```
=> view_destroy: fix use-after-free with subsurface_destroy

sway/tree/view.c
Fixes #6211.
Since I'm touching the focus function anyway, took the opportunity
to fix some formatting issues (mixed tabs and spaces, etc.)
=> tree/view: don't give focus to views mapped under fullscreen views

sway/desktop/output.c, sway/desktop/render.c
The first commit removes `surface->sx`/`surface->sy` from these calculations. It doesn't work, break things if non-zero, and causes confusion.
The second commit shuffles the clip box handling around a bit, in order to compensate for the offset in the clip dimensions, which could otherwise lead to insufficient or excessive clipping.
Closes: https://github.com/swaywm/sway/issues/6223
=> Fix offset toplevel geometry issue

include/sway/output.h, sway/desktop/output.c, sway/desktop/render.c
There was some unused code-paths for rendering surfaces with an
arbitrary rotation applied. This was imported from rootston.
Since we don't have plans to make use of this, remove it.
=> Remove support for arbitrary rotations

sway/desktop/xdg_shell.c, sway/tree/workspace.c
So for whatever reason qutebrowser likes to give us an output hint for fullscreen requests, which is fine. But in response sway tries to add qutebrowser to the tiling workspace it's already in and bungles things.
There's really two bugs here I think,
1. There's no reason to remove and re-add a window to the workspace it's already in if it requests the output it's already on. This would mess up the tiling order even without the ghost containers because it get's re-added at workspace level even if it was nested.
2. Doing that shouldn't make ghost containers anyway, so let's reap them in workspace_tiling add.
Fixes #6202.
=> Ignore superfluous fullscreen output hints

sway/tree/view.c
When a criteria places the view into the scratchpad, map_ws is NULL and
trying to access map_ws->fullscreen will result in SIGSEGFAULT with:
```
#0  0x0000000000455327 in should_focus (view=0x15a6a70) at ../sway/tree/view.c:604
prev_con = 0x0
len = <optimized out>
seat = 0x12233c0
prev_ws = 0x1264c80
map_ws = 0x0
criterias = <optimized out>
seat = <optimized out>
prev_con = <optimized out>
prev_ws = <optimized out>
map_ws = <optimized out>
criterias = <optimized out>
len = <optimized out>
num_children = <optimized out>
#1  view_map (view=view@entry=0x15a6a70, wlr_surface=0x15a5cb0, fullscreen=<optimized out>, fullscreen_output=<optimized out>, decoration=<optimized out>) at ../sway/tree/view.c:809
__PRETTY_FUNCTION__ = "view_map"
ws = <optimized out>
seat = <optimized out>
node = …
```
=> view: handle case where map_ws is NULL

sway/ipc-json.c, sway/sway-ipc.7.scd
This commit adds the capability to get the current scroll_factor from the config #6232
=> Added scroll_factor to ipc

config.in
This is my preferred terminal emulator now. Seeing as the default config
file is basically "Drew's preferences watered down a bit for a general
audience", I reckon it should be updated accordingly :)
=> config.in: change terminal emulator to foot

client/pool-buffer.c, common/background-image.c, common/cairo.c, common/pango.c, include/background-image.h, include/cairo_util.h, include/pango.h, include/pool-buffer.h, sway/config.c, sway/tree/container.c, swaybar/render.c, swaybar/tray/item.c, swaynag/render.c
For full context, read https://github.com/Cloudef/bemenu/issues/170 and https://gitlab.freedesktop.org/cairo/cairo/-/issues/479.
TL;DR, cairo’s pc file adds `/cairo` to CFLAGS.
So namespace cairo shouldn’t be used.
It was working simply because `/usr/include` is always used, not because of Meson + pkg-config.
A similar patch will land in swaybg too.
Thank you.
=> cairo: Replace <cairo/cairo.h> by <cairo.h>

sway/tree/view.c
These foreign toplevel actions require a transaction, but currently none are triggered. The ipc/binding fullscreen/focus commands already have their transactions triggered later.
To see the issue, send a foreign fullscreen request for your terminal and observe it won't fullscreen until you disturb something to commit a transaction.
=> view: commit transactions for foreign toplevel requests

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml, sway/tree/view.c
Cherry pick #6046 into the v1.5 branch in case it's useful for others not yet on 1.6.
=> Backport subsurface parent fixes to v1.5

sway/tree/view.c
Update for the breaking change in [1].
[1]: https://github.com/swaywm/wlroots/pull/2948
=> Iterate over subsurfaces below the parent surface

sway/commands/seat/attach.c
Deferred commands are only run once, during sway startup. This means that deferring seat attachment based on whether we are reading the config prevents devices from being reattached to the correct seat during a config reload. Instead, only defer if the config is not yet active.
Fixes #6048.
It sort of feels like there's still something more fundamental going on here, but this at least fixes the crash and gets devices where they're supposed to be. I think there might be some race with the device getting added to its intended seat before being removed from seat0 (or whatever fallback) based on how they happen to be iterated. It also seems like we tend to apply the config more times to a single device than is necessary based on the debug logs from the original issue. Finally, I'm also not …
=> Only defer seat attachment during initial startup

include/sway/config.h, sway/commands/bar/font.c, sway/config/bar.c, sway/ipc-json.c
Until now, swaybar did not have pango markup enabled by default, even if
the sway config had it on. This patch aims to mimic the i3 behavior, but
maintaining the functionality of the "pango_markup" sway config command.
Fixes swaywm/sway#6118
More details can be found in the referenced issue.
=> config: Fix swaybar pango_markup inconsistency

sway/commands/exec_always.c, sway/config/bar.c
Sway ignores `SIGPIPE` (by installing a `SIG_IGN` handler), in order to [prevent IPC from crashing Sway](https://github.com/swaywm/sway/blob/9755684fb0fd665a65be2a3cbabc5d502244c459/sway/main.c#L356).
`SIG_IGN` handlers are the *only* signal handlers inherited by sub-processes. As such, we should be a good citizen and restore the `SIGPIPE` handler to its default handler.
One way to reproduce is to bind `foot bash` in Sway's config:
```
bindsym $mod+t exec foot bash
```
Activate the key combo, and then run e.g. this program:
```c
#include <stdio.h>
#include <signal.h>
int
main(int argc, const char *const *argv)
{
for (int i = 1; i < 32; i++) {
struct sigaction sig;
if (sigaction(i, NULL, &sig) < 0)
return 1;
if (sig.sa_handler != SIG_DFL)
printf("signal #%d is NOT the default handler\n", …
```
=> Restore SIGPIPE before exec:ing

sway/commands/workspace.c
Fix #6299 
This forces `no_auto_back_and_forth` to true for `workspace next_on_output` and `workspace prev_on_output` to keep parity with i3.
In i3, running `next_on_output` never changes focus to another output.
In Sway currently, with `workspace_auto_back_and_forth` set to `yes`, running `next_on_output` on an output with only a single active workspace will typically end up focussing the other output:
1. `next_on_output` focusses the current workspace, because it's the only
one
2. `auto_back_and_forth` focusses the last focussed workspace, because the
workspace to focus is the current one. This will usually be on the other monitor if the workspace there was last focused one
Looking at the code, I actually think it may be cleaner to not make `no_auto_back_and_forth` an argument of …
=> Disable auto_back_and_forth for next_on_output

include/sway/tree/workspace.h, sway/commands/workspace.c, sway/tree/workspace.c
Followup on #6331
- Extract the auto back and forth code to a separate `workspace_auto_back_and_forth` function.
- Rename/repurpose `no_auto_back_and_forth` to `auto_back_and_forth` for easier understanding
- Only call `workspace_auto_back_and_forth` in the 2 cases it's actually needed, instead of disabling it for all other cases.
I had a closer look at the [i3 implementation](https://github.com/Airblader/i3-original/blob/next/parser-specs/commands.spec#L122-L136) now, and they only use the flag for changing to a named/numbered workspace, so I've made it similar here. Actually, `man 5 sway` already documents it this way as well.
Note that in both sway and i3 providing the flag is allowed in all cases. It's just ignored in some of them.
=> Move auto_back_and_forth logic out of workspace_switch

sway/tree/view.c
This fixes the following scenario:
- Place a floating window so its border is right at the edge of the screen
- Create a new split
- The border disappears
- Moving the window does not restore the border
=> Don't apply hide_edge_borders to any floating container

include/sway/tree/workspace.h, sway/commands/workspace.c, sway/tree/workspace.c
This reverts commit 487c83f0de9ca2a7650ad636eed6fd694ddcb82e.
The `--create` flag is undocumented, not in i3, and at least partially broken (#5913), so this removes the feature.
@ddevault should probably review this, since he added it.
Fix #5913
=> Revert workspace {prev,next}_on_output --create

.builds/alpine.yml, common/util.c, include/util.h, sway/input/cursor.c
As plans are to temporarily revert our solution to symbol collisions (https://github.com/swaywm/wlroots/pull/2980), we'll have to instead work around the problem locally.
If we make a 1.6.1 for wlroots 0.14 support, we should cherry-pick this PR as well.
=> Fix wlroots symbol collision

sway/tree/container.c
~In the special case of fullscreening a floating window,
container_discover_outputs would detect that the container box
intersected with a sway_output that the window wasn't actually over.
This would then send bogus surface entrance events to clients which
would confuse them. The cause of this appears to be con_box using
x/y/width/height instead of content_x/content_y (and so on). Just the
"plain" x/y could return negative values at times which is clearly
incorrect. Since output_get_box uses layout coordinates, it makes more
sense to properly use the layout coordinates for the container as well
when we are comparing the geometry between the two. Fixes #6080.~
~I'm unsure if using the `content`coordinates here has any deeper implications, but just running through the logic for this, I saw …
=> container: ignore borders in fullscreen windows

contrib/grimshot
Whenever the selection is cancelled by the user, exit 1, since not
screenshot has been taken.
=> grimshot: Exit 1 on cancellation

meson.build, meson_options.txt
- Both options default to on (no change in behavior).
- Users can toggle them off.
- Not sure if an option should also be added for `swaymsg`, let me know.
- Files related to swaybar/swaynag are still compiled (`sway/commands/bar/` for example). Shall I also make these conditional?
=> swaybar/swaynag: Add meson options to enable/disable

sway/commands/gaps.c, sway/sway.5.scd
This command is part of i3-gaps since Airblader/i3#264 but is currently missing in sway.
It can be used to toggle gaps at runtime either via a keybinding or via `swaymsg`, e.g.:
```
bindsym $mod+g gaps inner current toggle 30
swaymsg gaps outer all toggle 15
```
=> Add `gaps <type> <scope> toggle <px>` command

sway/desktop/render.c
We were calling wlr_gles2_texture_get_attribs, but we were never
using the result.
(cherry picked from commit 86b08e3257a4e3e204740f6252c5b1180ead8467)
* * *
This fixes the Pixman renderer.
=> Backport "desktop/render: remove unused wlr_gles2_texture_attribs" to v1.6

sway/config.c
If HOME environment variable is not set, sway fails startup with a
segmentation fault due to null pointer dereference.
Also check calloc return value and only perform the fallback code when
really needed.
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>
=> Fix crash when starting without HOME

include/sway/input/cursor.h, sway/input/cursor.c
When emulating touch, the simulating_pointer_from_touch field is
set to true. It's switched back to false when a touch_up event is
received. However we need to ensure we always send a wl_pointer.frame
event following a group of other wl_pointer events.
Since a touch_frame event is always guaranteed to come after a group
of touch events, unset simulating_pointer_from_touch in the touch_frame
handler instead of the touch_up handler. Add a new field to know whether
the touch_frame handler should stop emulation.
=> Fix wl_pointer.frame not sent on touch emulation

sway/desktop/xdg_shell.c, sway/tree/container.c, sway/xdg_decoration.c
The xdg-decoration protocol allows clients to request whether they want
to use server side decorations or client side decorations. Currently,
sway ignores this and always enforces whatever the server is currently
set to. Although tiled clients cannot be allowed to set borders, there
is no harm in listening requests from floating clients. First,
handle_map needs to check if the client has requested client side
decorations and flip the csd bool to true if it has. Secondly,
xdg_decoration_handle_request_mode needs to also check if a client
requests a different mode and update the container if applicable.
Sidenote: also fixed an unrelated style error.
I didn't check, but I think this would fix #6414 assuming this is how SDL requests a borderless window.
=> xdg-decoration: let floating clients set borders

include/sway/layers.h, sway/desktop/layer_shell.c
Feels a bit lame, but it does fix #6415. Previously only the size of the new surface (+subsurfaces) was damaged, now the whole previous extent is damaged.
=> layer_shell: damage previous area when a surface shrinks

sway/commands/bind.c
`[0]` is the switch type, not its state; we want `[1]` for that, and it's a string not an int :)
=> cmd_bind_or_unbind_switch: fix copy/paste typo error message

include/sway/input/seat.h, sway/input/seatop_default.c, sway/input/seatop_down.c
This PR changes the seatop implementation to ```seatop_down``` after a layer-surface has been clicked.
This solves an issue with layer-shell surfaces not receiving button release events. Especially when "mouse_warping container" is set.
On Waybar the issue leads to secondary interactions being necessary to "re-activate" the bar after changing workspaces with a mouse click.
However, the issue can also be triggered when moving the cursor away from the surface while being held pressed.
See https://github.com/Alexays/Waybar/issues/1047 for complaints and https://github.com/wmww/gtk-layer-shell/issues/109 for videos and a log. Maybe [this warning](https://codeberg.org/dnkl/foot/src/branch/master/input.c#L1773) from foot is also related.
The problem seems to be that on click the pointer is …
=> input: Use seatop_down on layer surface click

sway/commands/split.c, sway/sway.5.scd
While browsing the i3 issue tracker I saw issue i3/i3#3808 "split none" command with an accepted label. 
Not sure if we want it yet, but I figured this one was pretty easy to implement for sway so here it is. i3 doesn't have an implementation yet, so I can't really compare it to theirs, but I expect this is the intended behavior.
=> Implement split none command

sway/tree/container.c
The width of the texture needs to be calculated using the string that is
actually displayed in the texture.
=> Fix overly-wide mark textures

sway/tree/view.c
Fixes the issue when saved buffers were rendered in a reversed order.
=> view: fix saved buffer order

protocols/meson.build
As in wlroots: https://github.com/swaywm/wlroots/pull/2953.
To build sway on my system with outdated wayland-protocols (1.20):
- add wlroots, wayland-protocols, seatd as subprojects
- run `meson setup --force-fallback-for wayland-protocols build`
- ...
Without the force-fallback, sway finds wayland-protocols from the system, which does not satisfy wlroots (>=1.21) and the setup fails without a good error message.
I'll add a note in the wiki if this is merged.
=> build: subproject support for wayland-protocols

include/sway/tree/view.h, sway/desktop/xdg_shell.c, sway/tree/view.c
Previously, the position was calculated incorrectly for nested
subsurfaces.
---
Test client: [subsurface-client/grandchild-damage](https://codeberg.org/vyivel/subsurface-client)
=> view: fix child position calc

include/sway/server.h, sway/desktop/output.c, sway/server.c
Requires https://github.com/swaywm/wlroots/pull/2929
=> Implement wlr_drm_lease_v1

swaybar/input.c, swaybar/render.c, swaynag/render.c
Use `cairo_scale` to set the scale factor, removing redundant multiplications by `output->scale`.
Tested on my setup using fractional scaling, but also works properly for integer and no scaling (as tested with nested sway).
Fixes #6486
=> Simplify swaybar/swaynag scaling code

common/pango.c, include/pango.h, sway/tree/container.c, swaybar/render.c, swaynag/render.c
This avoids using the pango_ prefix, reserved for functions coming
from the Pango library.
=> Rename pango_printf to render_text

swaynag/swaynag.c
#6504 simplified rendering code by setting scaling at cairo, but
that also changed button position records into ones without scale
multiplication, breaking button events. This fixes it by not multiplying
scale on events handling as well.
=> swaynag: fix pointer button events on scaled outputs

README.md
When seatd is used, it isn't necessary to suid the sway binary.
=> readme: mention seatd

meson.build
Since [1], Meson allows feeding the input file as stdin and
capturing stout to the output file. We don't need the sh hack
anymore.
[1]: https://github.com/mesonbuild/meson/pull/8923
=> build: remove scdoc stdin/stdout hack

common/pango.c, sway/commands/reload.c, sway/commands/title_format.c, sway/config.c, sway/tree/view.c
Prior to 62d90a8e, titlebar's font height (and other related values)
would change any time any titlebar's content changed, so these values
were recalculated each time any titlebar's content changed (or a new
titlebar was created).
However, since the above was merge, these values no longer change so
often and we only need to recalculate them when the configured font
changes (and stop calling `config_update_font_height` each time
titlebars are rendered).
This commit removes all the unecessary calls to this function and avoids
all those unecessary calculations. Whenever the font strays from the
default value, the `font` command is called, and it calls
`config_update_font_height`, which is enough to keep the value always up
to date.
I've also added a default value to the `font_baseline` …
=> Avoid unecessary font metric calculations

include/swaybar/i3bar.h, swaybar/i3bar.c, swaybar/render.c
while the draw itself is a no-op, alignment must still be accounted
the blue bordered blocks demonstrate the transparent black (`0x0`) border support working (the background is blue)
```
bar {
status_command ./top.sh
position bottom
separator_symbol '¦'
icon_theme Adwaita
colors {
urgent_workspace #FF7F00 #1F1F1F #FFFFFF
}
}
bar {
status_command ./bottom.sh
position bottom
icon_theme Adwaita
separator_symbol '¦'
}
```
```bash
#!/usr/bin/env bash
echo '{ "version": 1, "click_events": true, "cont_signal": 18, "stop_signal": 19 }'
echo '[[]'
while sleep 1; do
echo ',[
{"full_text": "UDD", "urgent": true,  "border": "#1F7F1FFF"},
{"full_text": "UTB", "urgent": true,  "border": "#00000000"},
{"full_text": "U--", "urgent": true},
{"full_text": "N--", "urgent": false},
{"full_text": "NTB", …
```
=> swaybar: properly draw blocks with transparent black border

include/sway/server.h, sway/desktop/output.c, sway/main.c
This can help debugging direct scan-out issues, such as [1].
[1]: https://github.com/swaywm/wlroots/issues/3185
=> Add -Dnoscanout debug option

sway/desktop/layer_shell.c
https://github.com/swaywm/wlroots/pull/3201
=> layer-shell: chase wlr layer surface refactor

sway/desktop/layer_shell.c
This avoids infinite configure-ack_configure-commit loop.
---
Depends on https://github.com/swaywm/wlroots/pull/3214
Fixes https://github.com/swaywm/sway/issues/6546
=> layer-shell: check `committed` bitmask

include/sway/layers.h, sway/desktop/layer_shell.c
This commit makes sure the extents are kept up-to-date, fixes not
damaging the surface if its layer shell-specific state didn't change,
and adds a check if the layer shell-specific state didn't change but the
surface got mapped/unmapped, which could affect keyboard focus.
---
Fixes https://github.com/swaywm/sway/issues/6552
=> layer-shell: fix commit handler

include/sway/config.h, sway/commands.c
Clang 13 reports:
../sway/commands.c:470:23: error: variable 'context' set but not used
[-Werror,-Wunused-but-set-variable]
enum command_context context = 0;
^
Last use of was removed in commit 1d3681f52135.
Downstream PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258813
--
I removed lines 470-495 and related because I couldn't find code that would pass "ipc"
and "binding" so they end up in argv[i]. This might be wrong.
=> commands: Remove unused code after 1d3681f52135

include/sway/server.h, sway/commands/exec_always.c, sway/config/bar.c, sway/config/output.c, sway/main.c, sway/swaynag.c
Wayland compositors handle many file descriptors: client
connections, DMA-BUFs, sync_files, wl_data_device pipes, and so
on. Bump the limit to the max.
Closes: https://github.com/swaywm/sway/issues/6285
=> Bump RLIMIT_NOFILE

sway/main.c
Proprietary drivers require `--unsupported-gpu` to be allowed, and IPCs
require no option to be passed.
The only way to satisfy both is to run IPCs before checking for
proprietary drivers.
---
I have an nvidia card (I didn't know better 8 years ago, unfortunately), but since they've finally added support for Wayland I've installed the `nvidia` driver on my machine, but to my surprise `sway reload` stopped working as a result.
I understand having to pass `--unsupported-gpu` to run sway itself, but I think having to pass that to execute IPC commands is a bit much, so instead of the complex solution of allowing this flag but not others in the IPC path, I opted to simply move the check after it.
=> sway: allow IPCs on proprietary drivers

sway/tree/container.c
```
18:04:58 <vyivel> maybe i'm a bit too tired for this, but can someone explain the logic behind https://github.com/swaywm/sway/blob/master/sway/tree/container.c#L384?
18:05:14 <vyivel> it seems like it assumes that a popup can be toplevel's parent
18:05:30 <vyivel> or that anything but toplevel can be toplevel's parent
18:09:14 <vyivel> hm, a simple check like "is this xdg surface and popup" wouldn't be enough, if it's a popup with subsurfaces
18:09:58 <emersion> hm yeah not sure what this code is doing
18:11:22 <vyivel> the intention probably was to check parent-child relationship in terms of subsurfaces
18:12:04 <vyivel> eacalate until current surface is xdg-surface, if it's also a popup then return true
18:12:31 <emersion> hm maybe
18:12:42 <emersion> it's clearly not doing this …
```
=> container: fix surface_is_popup()

include/sway/server.h, sway/desktop/output.c, sway/desktop/render.c, sway/server.c, sway/tree/container.c
wlroots now required the compositor to create its own wlr_renderer and wlr_allocator to initialize the wlr_output
Matching wlroots PR: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3349
=> sway: create wlr_renderer and wlr_allocator

include/sway/commands.h, include/sway/config.h, sway/commands/output.c, sway/commands/output/render_bit_depth.c, sway/config/output.c, sway/meson.build, sway/sway-output.5.scd
~Companion to [wlroots MR !3333](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3333).~ ~See commit message (and the documentation for the introduced command in the man page) for what this does.~
This PR provides an `output <name> render_bit_depth [8|10]` command which can be used to make sway render window surfaces onto a 10 bit-per-channel buffer, if sway's backend and rendering system support it. The default bit depth remains 8, because that is supported essentially everywhere.
This is a rather specific interface; it does not guarantee that 10 bpc will be used, and even if a 10-bpc render buffer is used, it is not guaranteed that a monitor will be sent 10 bpc color data. Also, direct scan out for fullscreen windows might temporarily change the format of the buffers …
=> Add 'output render_bit_depth [8|10]' command

sway/commands/bar/hidden_state.c, sway/commands/bar/mode.c
sway-bar(5) says:
> For compatibility with i3, `bar mode <mode> [<bar-id>]` syntax is supported along with the sway only `bar <bar-id> mode <mode>` syntax.
while the actual behavior is that `bar_cmd_mode` ignores already selected `config->current_bar` and applies the change to all the configured bars.
Before:
```
00:00:15.799 [INFO] [sway/commands.c:257] Handling command 'bar bar-0 mode dock'
00:00:15.799 [DEBUG] [sway/commands/bar.c:66] Selecting bar: bar-0
00:00:15.799 [DEBUG] [sway/commands.c:428] Subcommand: mode dock
00:00:15.799 [DEBUG] [sway/commands/bar/mode.c:33] Setting mode: 'dock' for bar: bar-0
00:00:15.799 [DEBUG] [sway/commands/bar/mode.c:33] Setting mode: 'dock' for bar: bar-1
00:00:15.799 [DEBUG] [sway/ipc-server.c:347] Sending barconfig_update event
```
Note that the …
=> ipc: make `bar <bar_id> mode|hidden_state` behave as documented

swaybar/bar.c, swaybar/status_line.c
Make the status command a process group leader and change the kill(2)
calls to target the new process group. Signals sent by swaybar will then
be received by both the status command and its children, if any. While
here, check the result of fork(2).
Without this, children spawned by the status command may not receive the
signals sent by swaybar. As a result, these children may be orphaned on
reload.
The issue could be shown by setting the bar to
bar {
status_command i3status | tee /tmp/i3status.out
}
which would leave orphaned processes for each reload of sway
$ ps o pid,ppid,cmd | grep i3status | grep -v grep
43633   43624 sh -c i3status | tee /tmp/i3status.out
43634   43633 i3status
43635   43633 tee /tmp/i3status.out
$ swaymsg reload
$ ps o pid,ppid,cmd | grep i3status | grep -v grep …
=> swaybar: signal status command's process group

include/sway/server.h, include/sway/tree/root.h, sway/commands/output.c, sway/config/output.c, sway/desktop/layer_shell.c, sway/desktop/output.c, sway/ipc-server.c, sway/server.c, sway/tree/output.c, sway/tree/root.c, sway/tree/workspace.c
Fix for https://github.com/swaywm/wlroots/pull/3227
=> remove noop backend and noop output

meson.build
This allows to simplify our logic. Meson will pick the first found
library.
=> build: use list for sdbus dep

sway/desktop/output.c
A surface can have effective damage even without any buffer damage
committed.
---
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3389
=> output: remove surface buffer damage check

sway/desktop/output.c, sway/server.c
We use the headless backend to create a special fallback output
used when no other output is connected. However this messes up the
"real" headless output names users have come to expect (e.g.
currently the first headless output will be named "HEADLESS-2"
instead of "HEADLESS-1").
Fix this by setting the output name with [1].
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3395
=> Fixup headless output names

sway/tree/view.c
There seems to be a null pointer access that can happen. I was able to reproduce this by running the [cemu emulator](http://cemu.info/) with the new [collabora wine wayland driver](https://www.winehq.org/pipermail/wine-devel/2021-December/203035.html) and opening and closing some sub menus.
Adding a trival null check seems to do the trick to stop sway from crashing and returning to tty and everything else works normally.
Stack trace from lldb:
```Process 64013 stopped
* thread #1, name = 'sway', stop reason = signal SIGSEGV: invalid address (fault address: 0xf8)
frame #0: 0x00005555555c3fc3 sway`view_child_init(child=0x0000555555f67940, impl=0x00005555555ee030, view=0x00005555565bc590, surface=0x00005555565b6940) at view.c:1117:25
1114		wl_signal_add(&view->events.unmap, …
```
=> Fix null pointer dereference

include/swaynag/swaynag.h, meson.build, swaybar/bar.c, swaynag/swaynag.c
We can just get the output name from wl_output directly, now that
wl_output version 4 exists.
=> swaynag: remove xdg-output logic

include/sway/output.h, sway/desktop/layer_shell.c, sway/desktop/output.c, sway/tree/output.c
This is just the first 2 commits from #6639.
Previously an output had a destroy event that was emitted twice in a row (once in `output_begin_destroy` and again in the handler that is its only caller) and the output node destroy event was never signaled.
This renames the output destroy event to "disable" to better reflect it's usage and updates it to only emit once, and now the output node destroy event is emitted in `output_begin_destroy`.
There's no functional change to sway here, .
=> Clean up output destroy sequence

meson.build
I think this is relatively self explanatory :D
[Version bump in wlroots](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/7360810f2e5c71fe143b25b63517ab1a6475ce0a)
=> build: bump wlroots dependency to 0.16.0

sway/tree/container.c
cairo_image_surface_create can fail, e.g. when running out of
memory or when the size is too big. Avoid crashing in this case.
Closes: https://github.com/swaywm/sway/issues/6531
=> Add cairo_image_surface_create error handling

meson.build
Historically we've been sticking with the last release number in
the master branch. However that's a bit confusing, people can't
easily figure out whether they're using a release or a work-in-progress
snapshot. Only the commit hash appended to the version number may
help, but that's not very explicit and disappears when using a
tarball.
We could bump the version in master to the next release number.
However during the RC cycle there would be a downgrade from 1.8 to
1.8-rc1. Also it would be hard to tell the difference between a
stable release and an old snapshot.
This patch introduces a new pre-release identifier, "dev". It's
alphabetically before "rc" so it should be correctly sorted by
semver comparisons. "dev" is upgraded to "rc" (and then to stable)
when doing a release. The master …
=> build: bump version to 1.8-dev

swaybar/tray/item.c, swaybar/tray/tray.c
Fixes some fallout from #6504:
- tray item rendering, due to scale changes, and creeping bad logic
- tray_padding vs min-height computation
---
This branch/solution; notice the icons are all crisp, they are all vertically centered and evenly spaced (but not evenly sized width-wise!):
(https://github.com/nmschulte/sway/commit/fa75a39295326aa54a32666b01c6d088ba8920a9)
One of my prior/first attempts, not really knowing how the scaling is applied or the intricacies of libcairo and wayland-protocols/sway; notice the aliasing/blur due to the reversal/removal of scale:
`master` with the same/similar diagnostic as my dev; note the large icons:
(https://github.com/nmschulte/sway/commit/8425299c80dac8e80d7f06739f4d9342c406bbe6)
=> Swaybar scaling fixes

sway/tree/container.c
Followup on 4e4898e90f.
If a view quickly maps and unmaps repeatedly, there will be multiple
destroyed containers with same view in a single transaction. Each of
these containers will then try to destroy this view, resulting in use
after free.
The container should only destroy the view if the view still belongs
to the container.
Simple reproducer: couple XMapWindow + XUnmapWindow in a loop followed
by XDestroyWindow.
See #6605
=> container: Fix crash when view unmaps + maps quickly

sway/commands/move.c
Only need to check for argc >= 1 here because the unit argument is optional (handled properly by parse_movement_amount)
Closes #6737
=> commands/move: Fix crash when pos_y is omitted

common/util.c
Let's add this just in case a caller passes argc == 0.
References: https://github.com/swaywm/sway/issues/6737#issuecomment-1008082540
cc @mstoeckl @David96
=> Add safety assert in parse_movement_unit

meson.build
Future meson releases will change the default and warns when the
implicit default is used, breaking builds.
Explicitly set check=false to maintain behavior and silence warnings.
=> meson: check=false on run_command

sway/main.c
SUID privilege drop is needed for the "builtin"-backend of libseat,
which copied our old "direct" backend behavior for the sake of
compatibility and ease of transition.
libseat now has a better alternative in the form of seatd-launch. It
uses the normal seatd daemon and libseat backend and takes care of SUID
for us.
Add a soft deprecation warning to highlight our future intent of
removing this code. The deprecation cycle is needed to avoid surprises
when sway no longer drops privileges.
We should put this in the release notes as well.
=> Print deprecation notice when running SUID

sway/desktop/xdg_shell.c
`popup_unconstrain` uses view coordinates to init the output box for
popups. However wlroots expects the box to be set in a toplevel surface
coordinate system, which is not always equal to view. The difference
between those is a window geometry set via xdg-shell.
GTK4 reserves some space for client-side decoration and thus has a
window with top left corner not matching to (0, 0) of a surface. The box
calculated without taking that into account was slightly shifted
compared to the actual output and allowed to position part of the popup
off screen.
***
I'm not entirely sure that this is the right change. xdg-shell alternates between using window geometry coordinates and surface coordinates, but then  `wlr_xdg_popup_unconstrain_from_box` clearly wants a surface-local coordinates (as implied …
=> xdg-shell: use toplevel geometry to adjust the popup box

meson.build
The reverted commit introduced the use of list for sdbus deps, however
it was assuming that all packages which were in a list has a version
higher than 239. That is true for libsystemd and libelogind, since they
use the same versions, however basu is using version numbers which are
way lower than what libsystemd/libelogind are using, so basu only build
is failing.
This reverts commit 02b412a3d4e930237a1d16554af6e1e7d1855c89.
=> Revert "build: use list for sdbus dep"

sway/input/cursor.c
I accidentally overlooked this in fd53f80.
Thanks @iyzana for pointing it out.
=> input/cursor: treat swipe begin as idle activity too

sway/commands/focus.c
Currently, fullscreen containers are treated differently based on whether they were originally floating or tiled. This is strange from a user perspective, since there is no visual hint whether a container was originally floating or tiled. This change only affects multi-monitor setups.
To see the current effect, try the following:
1. Open a window in tiled mode
2. Fullscreen it
3. You can still move between monitors with `$mod-$left`/`$mod-$right`.
4. Open a window in floating mode
5. Fullscreen it
6. You can _not_ move between monitors with `$mod-$left`/`$mod-$right`
7. However, there is no visual difference between 3. and 6.
This PR makes the behaviour in 6. consistent with the behaviour in 3.
=> Treat fullscreen windows as 'tiled' for commands/focus

sway/desktop/transaction.c
Commit 37d7bc69986f ("transaction: Only wait for ack from visible
views") introduced a check which uses view_is_visible() to check if a view
is still visible on the screen. However view_is_visible() will early
return in case the node is in the destroying state. This is incorrect
for transactions, since a destroying view which is visible will trigger
configure events for other clients. This bug was visible when repeatedly
opening and closing two views side by side, since we ignore the
destroying node we get a frame where the still open view is shown with
the old configure values and the rest is the desktop background. The
next frame is than correct again.
Fix this by considering destroying views as visible, we correctly wait
for them and send the configure events to other views in time, …
=> transaction: destroying nodes aren't hidden

meson.build
wlroots often requires dependencies more recent than Sway's.
Executing the wlroots subproject first will give Meson a chance to
find these newer dependencies, possibly via subprojects.
The subproject will override the "wlroots" dependency when executed,
so we don't need to use get_variable anymore.
References: https://github.com/swaywm/sway/pull/6498#issuecomment-1001746017
=> build: execute wlroots subproject before finding deps

swaybar/tray/item.c
From the spec:
> Passive: The item doesn't convey important information to the user, it can be considered an "idle" status and is likely that **visualizations will chose to hide it**.
https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/#org.freedesktop.statusnotifieritem.status
=> tray: do not render passive items

sway/commands/swap.c
Fixes #6724. Swapping a con with itself is an error in i3.
=> cmd/swap: error on swapping a container with itself

include/sway/input/cursor.h, sway/input/cursor.c
This just follows swaywm/wlroots#3047, so `wl_pointer_gestures_v1`
clients can be notified of these events.
=> input/cursor: pass through pointer hold gestures

swaynag/swaynag.c
An address of a variable can never be NULL, so checking it doesn't make
sense; and `destroy_buffer()` can operate on already destroyed buffers
anyway.
Fixes #6780
=> swaynag: remove buffer destruction condition

include/sway/tree/view.h, sway/desktop/xwayland.c
When REAPER submenu is closed `XCB_CLIENT_MESSAGE` with type
`NET_ACTIVE_WINDOW` is sent to set focus to parent menu.
Closes: #6324
=> xwayland: listen to `request_activate` event 

sway/desktop/xdg_shell.c
wlroots MR: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3326
=> Chase wlroots xdg-shell refactor

sway/sway.5.scd
Removed xwayland limitation since wayland clients are supported via xdg-activation. See https://github.com/swaywm/sway/issues/4523#issuecomment-1026194317.
(The only real change is removing "n xwayland", but I re-wrapped the block so the diff is messy. If there's a better way, let me know.)
=> Minor update to focus_on_window_activation

include/sway/tree/view.h, sway/desktop/xdg_shell.c, sway/tree/container.c
Improved type safety.
Closes: https://github.com/swaywm/sway/issues/6813
cc @vyivel
=> xdg-shell: use wlr_xdg_{toplevel,popup}

sway/commands/output/background.c, sway/server.c
https://github.com/swaywm/sway/issues/6784
Hello this replaces sprintf with snprintf to avoid
`../sway/server.c:217:50: warning: ‘%d’ directive writing between 1 and 11 bytes into a region of size 8 [-Wformat-overflow=]
`
and
`../sway/commands/output/background.c:115:25: warning: ‘sprintf’ argument 4 overlaps destination object ‘src’ [-Wrestrict]
`
=> Fix snprintf compiler warnings (errors)

sway/tree/container.c, sway/tree/root.c, swaynag/config.c, swaynag/swaynag.c
Replace them with snprintf, which ensures buffer overflows won't
happen.
=> Remove all sprintf calls

sway/desktop/xdg_shell.c, sway/desktop/xwayland.c
Currently, a floating window that's been fullscreened can send us `xdg_toplevel::move`, and we'll enter seatop_move_floating, which lets us drag the surface around while it's fullscreen. We don't want this—fullscreen surfaces should always be aligned to the screen—so add the same check that seatop_default already does when entering this mode.
Tested with Weston's weston-fullscreen demo, which sends a move request if you click anywhere on its surface.
Note that this fix is pretty fragile. There's nothing stopping some other code path from altering `pending.x` and `pending.y` of a fullscreen container. If there's a place where we can consolidate this logic to be more bulletproof, let me know.
=> Don't enter seatop_move_floating when fullscreen

swaynag/config.c, swaynag/main.c, swaynag/swaynag.c
Ideally the number of allocations should be reduced, but until then, detecting failure is better than not.
=> swaynag: die on all allocation failures

sway/input/text_input.c
active_keyboard may be NULL, in which case an invalid pointer could be
passed to wlr_input_method_keyboard_grab_v2_send_modifiers. This
procedure call is unnecessary since wlroots commit [372a52ec](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/372a52ec) "input
method: send modifiers in set_keyboard", so the call can simply be
removed.
Fixes #6836.
=> sway/input: don't pass possibly invalid modifiers pointer

sway/input/seat.c
Fix: #6861
There is sway_switch_destroy function in `input/switch.c`, but never used.
So, I added that function to seat_device_destroy function in `input/seat.c`
I've checked with ASAN and leak has gone.
=> sway/input: destroy sway_switch properly

sway/commands/focus.c
=> commands/focus: fix segfault when no container is already focused.

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml, README.de.md, README.dk.md, README.es.md, README.fr.md, README.gr.md, README.hu.md, README.ir.md, README.ja.md, README.ko.md, README.md, README.nl.md, README.pl.md, README.pt.md, README.ro.md, README.ru.md, README.tr.md, README.uk.md, README.zh-CN.md, README.zh-TW.md, include/sway/criteria.h, meson.build, sway/criteria.c, sway/meson.build
Thank you @psychon for fixing the patch I've sent over email. This should fix #6838.
=> Replace pcre with pcre2

include/swaybar/bar.h, swaybar/bar.c
No need to keep the region around, we can immediately destroy it
after the wl_surface.set_input_region request.
=> swaybar: remove swaybar_output.input_region

sway/criteria.c
With PCRE2.
The function regex_cmp now return a positive integer for match instead of 0.
This change the checking to include positive value as true.
This should fixed #6886
=> Updating criteria checking with PCRE2

sway/main.c
This is a mostly aesthetic change; it keeps the constants `long_options` and `usage` out of stack traces, making it slightly easier to see the important parts.
```diff
#14 0x00007f51a64302e5 in wl_display_run (display=0x5563ffc0c720)
at ../wayland/src/wayland-server.c:1408
#15 0x00005563ff0bd620 in server_run (server=server@entry=0x5563ff1264c0 <server>)
at ../sway/sway/server.c:307
#16 0x00005563ff0b1d82 in main (argc=3, argv=0x7fff18269888) at ../sway/sway/main.c:431
verbose = false
debug = false
validate = false
allow_unsupported_gpu = false
-        long_options = 
-            {{name = 0x5563ff105459 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5563ff109365 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5563ff10545e "validate", has_arg = 0, flag = 0x0, val = 67}, …
```
=> sway/main: move constants off the stack

sway/commands/output/background.c, sway/server.c
Sway master has two compile errors when using GCC 12; one false positive and one due to an actual bug.  This adjusts the code slightly to fix the warnings.
=> Gcc 12 fixes

include/sway/input/seat.h, include/sway/server.h, sway/desktop/output.c, sway/desktop/render.c, sway/input/input-manager.c, sway/input/keyboard.c, sway/input/seat.c, sway/input/switch.c, sway/lock.c, sway/meson.build, sway/server.c
This prevents input from bypassing a lockscreen if the lockscreen crashes or has other problems (for example, https://github.com/swaywm/swaylock/issues/204).  Swaylock support is already present as of 1.6 (https://github.com/swaywm/swaylock/pull/219).
=> Implement ext-session-lock-v1

sway/criteria.c
memcpy is useless here, is dangerous because it doesn't guarantee
that the string is NUL-terminated and causes the following warning:
../sway/criteria.c: In function ‘criteria_parse’:
../sway/criteria.c:712:25: error: ‘strncpy’ destination unchanged after copying no bytes [-Werror=stringop-truncation]
712 |                         strncpy(value, valuestart, head - valuestart);
|                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> Replace strncpy with memcpy

sway/desktop/output.c
Fixes https://github.com/swaywm/swaylock/issues/236.
@alextsits - please confirm this fixes it for you.
=> ext-session-lock: disable direct scan-out when locked

include/sway/tree/view.h, sway/desktop/xdg_shell.c
This commit reverts 03879290dbee26127f6867ef60bc2a7f9a6c8c5f and
fc84bcb7fb0ffa29b1f9bed287762241a3473803.
=> xdg-shell: schedule a configure on maximize request

meson.build, sway/meson.build
Fixes the following FreeBSD error:
ld: error: undefined symbol: pthread_getschedparam
>>> referenced by realtime.c:25 (../sway/realtime.c:25)
>>>               sway/sway.p/realtime.c.o:(set_rr_scheduling)
Fixes: a3a82efbf6b5 ("realtime: request SCHED_RR using CAP_SYS_NICE")
=> build: link with -pthread

sway/ipc-server.c
These aren't particularly useful, and clobber the debug logs.
=> ipc: remove chatty debug log messages

include/sway/server.h, sway/main.c, sway/server.c
This ensures that those surprised by the deprecation of SUID operation
receive an error rather than accidentally having sway run as root.
This detection will be removed in a future release.
=> Refuse to start when SUID is detected

swaynag/main.c
When swaynag_parse_options encounters '--dismiss-button' (or its
shorthand '-s'), it sets the text of the first button in the
swaynag.buttons list, which is expected to exist and to be the dismiss
button, to the one passed by the user.
Commit 4780afb68b4ee2cdf0e4925f40cf885819f8a74a ("swaynag: statically
allocate button_close, and move declaration") moved the list
initialization to after swaynag_parse_options is called which made that
code fail.
For example, the command 'swaynag --dismiss-button Dismiss' crashes and
'swaynag --message Message --button Yes "" --dismiss-button Dismiss'
shows the wrong buttons.
Move it back to before swaynag_parse_options is called.
=> swaynag: move close_button up to fix SIGSEGV

sway/config/output.c
This makes the code more robust because we don't potentially leave
bad state in wlr_output.pending behind anymore. This also fixes a
bug.
Closes: https://github.com/swaywm/sway/issues/7043
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3610
=> config/output: use wlr_output_commit_state

sway/commands.c
Sometimes (i.e. https://github.com/swaywm/sway/blob/master/sway/commands/move.c#L980-L990), 256 bytes is not enough to hold an error message.
=> Allocate enough space for `cmd_results->error`

include/sway/commands.h, sway/commands/output.c, sway/commands/output/dpms.c, sway/commands/output/power.c, sway/meson.build, sway/sway-output.5.scd
The "dpms" command refers to VESA Display Power Management
Signaling, a deprecated standard. It's superseded by VESA DPM.
Instead of tying out command name to a particular standard, use the
neutral term "power".
=> Rename dpms output command to power

common/pango.c, include/pango.h, include/sway/config.h, include/swaybar/config.h, include/swaynag/types.h, sway/commands/font.c, sway/config.c, sway/tree/container.c, swaybar/config.c, swaybar/ipc.c, swaybar/render.c, swaynag/config.c, swaynag/render.c
Use pango to parse font configuration early, and reject the command as
invalid if the value is invalid for pango. Since we're already parsing
the font into a `PangoFontDescription`, keep that instance around and
avoid re-parsing the font each time we render text.
Fixes: https://github.com/swaywm/sway/issues/6805
=> Reject font values that are invalid for pango

config.in, include/sway/config.h, include/sway/output.h, sway/commands/output/power.c, sway/config/output.c, sway/desktop/output.c, sway/ipc-json.c, sway/sway-ipc.7.scd
Follow-up for https://github.com/swaywm/sway/pull/7083
=> Remove all remaining references to "DPMS"

swaymsg/main.c
Fix floating_nodes being ignored in pretty_print_tree.
=> swaymsg: fix floating_nodes being ignored

sway/ipc-json.c
Without this, the `IPC_GET_TREE` ipc call would return false information about the container's `deco_rect` and `rect` properties if `hide_edge_borders --i3` was in effect.
=> ipc: make get_deco_rect check config->hide_lone_tab

sway/sway-output.5.scd
Since "width" and "height" are separate parameters, show them as such.
=> sway-output.5: improve display of parameter

sway/xdg_activation_v1.c
wlr_xdg_surface_from_wlr_surface() can return a NULL pointer, so check for NULL before dereferencing it.
I have managed to get the NULL pointer and trigger a sway crash using dosbox 0.74.3. To reproduce, create a `dosbox.conf` with the following contents:
```
[sdl]
output=opengl
```
and run `SDL_VIDEODRIVER=wayland dosbox -conf dosbox.conf`
=> Fix crash in xdg_activation_v1.c

include/sway/ipc-json.h, include/sway/output.h, include/sway/tree/root.h, sway/desktop/output.c, sway/ipc-json.c, sway/ipc-server.c, sway/tree/output.c, sway/tree/root.c, swaymsg/main.c
Currently, `swaymsg -t get_outputs` doesn't report VR headsets.  This ultimately adds that support by adding non-desktop outputs to a list of the new type `sway_output_non_desktop` to `sway_root` since sway doesn't hold on to those outputs. I could simply create `sway_outputs` for non-desktop outputs, but I wasn't sure of the implications.  Let me know your thoughts
=> swaymsg: show non-desktop outputs

sway/sway.5.scd
I just tripped over this detail myself, not knowing that these parameters won't work anymore with X/XWayland disabled.
=> man: Add XWayland information

README.ja.md
Make some improvements and updates to the Japanese README.
=> Improve Japanese translation of README

sway/input/seatop_default.c
Fixes #6503.
Tested to behave the same as i3 wrt. inactive containers in this layout:
=> input: focus container when scrolling on titlebar

sway/input/seatop_default.c
Sway focuses the inactive child when focusing split containers. However,
there is currently no way to focus the parent container itself by mouse.
A user must use the keyboard (`focus parent`) to do so.
This commit maintains the current behavior, but makes it such that a
second click on the split container titlebar (i.e., after its children
are visible) focuses the split container itself.
=> input: tweak focus behavior to allow focusing parent containers

include/sway/input/libinput.h, sway/input/input-manager.c, sway/input/libinput.c
Sway was crashing on me everytime I connected or reconnected my Thinkpad usb keyboard. It turns out that for some reason, upon connection, the pointer to the keymap was NULL, therefore crashing Sway as it attempted to access the pointer in ipc_json_describe_input. I've added a check for that.
So far I've tested it and it doesn't crash on me anymore when connecting my keyboard. `swaymsg -t get_inputs` still shows the correct layouts for the keyboard, so I guess it sets the keymap pointer in a later event.
=> Prevent segfault on keyboard connection

include/sway/input/seat.h, include/sway/server.h, sway/input/seat.c, sway/lock.c
Keyboard focus tracking with session lock has some incorrect edge cases around output destroy/create; this changes them to more closely mirror those used by layer_shell.
=> Session lock focus fixes

sway/tree/container.c
A trivial patch I had floating around for a really long time.
=> container_floating_set_default_size: Store workspace size box on the stack

include/sway/commands.h, include/sway/config.h, meson.build, sway/commands/input.c, sway/commands/input/dwtp.c, sway/config/input.c, sway/input/libinput.c, sway/ipc-json.c, sway/meson.build, sway/sway-input.5.scd, sway/sway-ipc.7.scd
Support the new dwtp (disable while trackpointing) option introduced in libinput 1.21, allowing users to control whether the trackpoint (like those in Thinkpads, but not only) should be disabled while using the keyboard/touchpad.
See: https://gitlab.freedesktop.org/libinput/libinput/-/issues/731
=> Support libinput's 1.21 new dwtp option

sway/criteria.c, sway/tree/view.c
Any windows that have never had a title set visually behave closer to that of an empty title, but are unformattable, as the code bails out early on a NULL title.
(as an example, `hello-wayland` does this, as well as xwayland windows with an empty title.)
=> Improve NULL title handling

meson.build, sway/tree/container.c, sway/tree/output.c, sway/tree/view.c, sway/tree/workspace.c
This function fixes segfaults when emitting a signal potentially removes arbitrary listeners.
=> Use wl_signal_emit_mutable()

sway/tree/workspace.c
Through code inspection a null name shouldn't be given. Also, there is existing code that will segfault if the name is NULL, guard against this. The commit is quite old, I haven't hit this assert in running it for the past few months.
=> workspace_create: Don't allow NULL name

include/swaybar/i3bar.h, include/swaybar/input.h, swaybar/i3bar.c, swaybar/input.c, swaybar/render.c, swaybar/tray/item.c
This is consistent with i3bar's behaviour, and for example, allows binding a command to button1, while still being able to click on tray icons or other zones on the bar's status line which may have their own bindings.
E.g., in Sway, without this commit, this config. makes tray icons unclickable:
```
bar {
bindsym button1 exec swaynag -m You_clicked_the_tray._Want_some_help?
}
```
But the same configuration in i3 (with i3-nagbar) keeps tray items clickable.
=> swaybar: Prioritize hotspot events to bar bindings

meson.build
xcb-icccm is required to build Xwayland support.
=> build: fix have_xwayland when xcb-icccm is not found

include/sway/commands.h, include/sway/config.h, sway/commands.c, sway/commands/primary_selection.c, sway/config.c, sway/meson.build, sway/server.c, sway/sway.5.scd
See https://github.com/swaywm/sway/issues/4511. This PR builds on https://github.com/swaywm/sway/pull/6897 which seems to have stalled, and I have kept @t1lde's contributions in the commit history.
I have attempted to address @emersion's feedback in https://github.com/swaywm/sway/pull/6897. Firstly, the `config` option is stored as `bool`. Secondly, I make the `primary_selection` only configurable at launch (similar to `xwayland`). This allows me to destroy the primary selection global after the config is loaded.
I couldn't think of a clean way to avoid creating the global at all, since `server_init()` creates the global and the default seat, and then registers listeners. After that, the configuration is loaded in `load_main_config()`. So I hope destroying the global after loading the …
=> Disable primary clipboard option

sway/criteria.c
This extends #5822 to window_role and instance properties too, which may also be NULL for non-xwayland views. Fixes a crash like:
<details>
<summary>swaymsg '[instance=__focused__]' nop</summary>
```
#0  0x00007f125115470f in  () at /usr/lib/libc.so.6
#1  0x00005601e3af8907 in criteria_matches_view (criteria=0x5601e5a2d020, view=0x5601e5900b70) at ../sway/sway/criteria.c:290
instance = 0x5601e3b4f617 ""
seat = <optimized out>
focus = <optimized out>
focused = 0x5601e53ddf10
#2  0x00005601e3af8f42 in criteria_get_containers_iterator (container=0x5601e5991220, data=0x7ffcabe000c0) at ../sway/sway/criteria.c:411
match_data = 0x7ffcabe000c0
#3  0x00005601e3b40838 in workspace_for_each_container (ws=0x5601e5990860, f=f@entry=0x5601e3af8f20 <criteria_get_containers_iterator>, …
```
=> criteria: be lenient on window_role and instance too

include/sway/commands.h, include/sway/config.h, sway/commands/input.c, sway/commands/input/rotation_angle.c, sway/config/input.c, sway/input/libinput.c, sway/meson.build, sway/sway-input.5.scd
This patch adds the libinput option RotationAngle to sway.
Fix: #7277 
Signoff-by: Lucas Zampieri <lzampier@redhat.com>
=> Add libinput RotationAngle

sway/commands/move.c
This makes sway's behavior consistent with i3 when `mouse_warping` is set to any value besides `none`.
Fixes #7027.
=> commands/move: Warp cursor after moving workspace to another output

sway/input/keyboard.c
sway sends wl_keyboard.enter on seat focus change and when a keyboard active on a seat is configured. If all keyboards are removed and a keyboard is added back without changing the focused client, no new notify event would be sent despite having keyboard focus. This could lead to key events without notify, which is a protocol violation.
As a quick fix, when configuring a keyboard on a seat where no keyboard is currently active, activate the keyboard so that a focused surface will receive a notify event.
Regressed by: e1b268af98edeb09e570e8855ef64f0719cbafe2
Closes: https://github.com/swaywm/sway/issues/7330
=> seat: Set keyboard if seat keyboard is NULL

include/swaynag/types.h, swaynag/config.c, swaynag/main.c, swaynag/types.c
The font description was only set if provided on the CLI. It was
left NULL for the defaults and when reading from the config file.
Closes: https://github.com/swaywm/sway/issues/7186 
cc @WhyNotHugo
=> swaynag: fix NULL font description 

sway/input/cursor.c
This might be the wrong fix, but the crash is happening because the ->data field on an xwayland surface is NULL. A NULL data field is normal for unmanaged surfaces, however it seems clients can do weird things: They can create a cursor lock on a regular xwayland surface then make it unmanaged by calling override_redirect. In this case, the xwayland server should destroy the cursor lock, which is does, but does so in the wrong order making it try to dereference a NULL pointer after sway has acknowledged its new unmanaged status.
```
(gdb) bt full
0  0x000055fd91934861 in warp_to_constraint_cursor_hint (cursor=0x55fd93486c00)
at ../sway/input/cursor.c:1243
sy = 605
lx = 6.9527431433545762e-310
sx = 1272
view = 0x0
con = 0x7ffd1cdfe400
ly = -6.949595189996421e+59
constraint = 0x55fd93e7faa0 …
```
=> warp_to_constraint_cursor_hint: Handle NULL view

include/sway/input/cursor.h, sway/input/cursor.c
This change allows the tablet tool button to be used for floating mod resize. In addition, it attempts to ensure that tablet tool events are consistent such that tablet v2 events and pointer events will never be interleaved, and such that the tool buttons count will never fall out of sync and cause tool button emulation to break.
Some of this logic is similar to what is done for tablet tool tip, but not quite identical, because of the complication that we have to deal with multiple inputs that can overlap each-other.
The logic described to fix this in #7036 is not sufficient as it does not account for the inverse case (going from tablet events to pointer events.) Implementing the fix this way leads to much better behavior if you, for example, use a tool button to open a menu, then before …
=> Improve tablet tool button handling.

include/sway/input/tablet.h, sway/input/seat.c, sway/input/tablet.c
Additionally, rename the function responsible for switching focus to match its behavior better.
---
Might fix https://github.com/swaywm/sway/issues/7369, which I can't reproduce.
=> input/tablet: handle focusing NULL surface

sway/input/cursor.c, sway/input/seat.c
We were never sending any pointer event to ext-session-lock surfaces.
=> Fix pointer events for ext-session-lock surfaces

sway/tree/view.c
If `focus_on_window_activation = focus` is set, an xwayland window should be focused when it requests activation. If there are multiple floating windows on the screen the one that receives focus may be obscured, so it makes sense to raise it.
=> focus_on_window_activation: raise if floating

sway/desktop/render.c
Since [1], wlr_renderer_begin() can fail. Check its return value and bail.
This fixes an assertion error (when begin() fails and then we try to render something) after a GPU reset.
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/a541c9510a4cf544313bc9b0503d75820b42444e
=> Check return value of wlr_renderer_begin()

sway/desktop/output.c
fixes #7394
Test cases:
* zwlr_output_configuration_head_v1_set_adaptive_sync 0->0, no change
* 0->1, enabled
* 1->0, disabled
* 1->1, no change
Similar tests with an incapable display resulted in `"Adaptive sync failed, ignoring"` messages as expected.
=> 7394: apply new adaptive sync value

swaymsg/swaymsg.1.scd
*sway-ipc*(7) is mentioned under *SEE ALSO* but it helps to mention it explicity where the events can be looked up.
=> Added reference for event types to swaymsg manpage

include/sway/ipc-server.h, sway/desktop/output.c, sway/ipc-server.c, sway/sway-ipc.7.scd
For compatibility with i3 [1].
[1]: https://i3wm.org/docs/ipc.html#_output_event
=> ipc: add support for output event

sway/tree/root.c
This fixes a memory leak because the non_desktop_outputs list was not freed when the root was destroyed.
=> root: free non_desktop_outputs list on root_destroy

.builds/alpine.yml
We're missing the pkg-config file so the DRM backend gets disabled.
=> ci: install hwdata-dev on Alpine

include/sway/desktop/launcher.h, include/sway/server.h, include/sway/tree/view.h, sway/commands/exec_always.c, sway/desktop/launcher.c, sway/desktop/xwayland.c, sway/server.c, sway/tree/view.c, sway/xdg_activation_v1.c
This allows a launcher client to request an activation token useful for startup notifications. For a compatible launcher, see fuzzel [1].
For the time being, we use these in exactly the same way we would our own internal launch contexts except they cannot be pid matched. If the launched client supports startup notifications I'd consider that a positive. We also get a little more info from the launcher than we have on our own, i.e. the intended app_id. We might consider restricting matches to the given app_id.
Depends on [2].
[1] https://codeberg.org/dnkl/fuzzel/pulls/195 (merged)
[2] https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3907 (merged)
=> Add support for external launcher clients with xdg activation

sway/xdg_activation_v1.c
xdg-activation is now too strict in only allowing tokens with a seat to activate a surface. Clients may rely on this behavior for urgency hints. The seat argument is still useful in case the client does provide a seat so we can activate it on the desired seat.
=> xdg-activation: fix urgency when the client does not specify a seat

sway/ipc-json.c, sway/sway-ipc.7.scd
I'm using `border pixel` with `hide_edge_borders both` and noticed that `window_rect.y` was incorrectly offset for some windows.
`window_rect.y` is currently set to `border_thickness` for windows with `border pixel`.
This is correct if there is a top border (exaggerated here with `border pixel 10`):
...but it is not correct if top border is not drawn:
This means that windows adjacent to top screen edge return incorrect `window_rect.y` in this configuration.
Compute the actual `y` offset into the container for windows with `border pixel`.
I also updated the man page section about `window_rect`. Previously it said that `borders are included` but that was not correct.
* With `hide_edge_borders both`:
* Window with `border pixel 10`, adjacent to top screen edge
* Expected: `window_rect.y == …
=> ipc: Fix window_rect.y with hide_edge_borders

sway/desktop/layer_shell.c
This sends fractional-scale-v1 events before the first configure event. That way clients have all of the metadata they need to render the first frame.
=> layer-shell: enter output before surface is mapped

include/sway/input/cursor.h, include/sway/input/seat.h, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_default.c, sway/input/seatop_down.c
Atm we got issue with the touch position sent to the clients. While
holding contact, leaving the initial container will continue to send
motion event to the client but with the new local position from the new
container.
This seatop goal is to send the position of the touch event, relatively
to the initial container layout position.
This will solve: https://github.com/swaywm/sway/issues/6454
I'm pretty new to Wayland and even more with the Sway codebase.
=> Implement seatop_touch

sway/tree/view.c
When a window in the scratchpad container requests for xdg_activation_v1, it is ignored no matter what the value of focus_on_window_activation is.
At least allow windows in the scratchpad to set the urgent flag.
=> Allow windows in scratchpad to set the urgent flag

sway/desktop/output.c
Extracted from #7477. I couldn't find a native wayland client that was broken by this because subsurfaces are apparently very common which masks the problem.
=> Disable direct scanout for surfaces with popups

include/sway/tree/container.h, sway/commands/move.c, sway/tree/arrange.c, sway/tree/container.c, sway/tree/root.c
Should fix https://github.com/swaywm/sway/issues/5308 and https://github.com/swaywm/sway/issues/6561. The translation behavior also applies to all floating containers (not just those on the scratchpad), since that's what i3 does.
I've been dogfooding this for the past week on a setup with monitors of different aspect ratios without issue.
`floating_fix_coordinates` is adapted from [the same in i3](https://github.com/i3/i3/blob/d26ddcbfe5f0ead61cc55c1f596692d9a89e71f9/src/floating.c#L799).
=> root: Try to preserve relative positions of floating containers

sway/tree/root.c
Fixes behavior which can be replicated by these steps:
1. In a session with two outputs, open at least 2  tiling windows on each visible workspace and put a window in the scratchpad
2. While on output 1, show the scratchpad with `scratchpad show`
3. Move to output 2
4. Move the visible scratchpad window to the focused output with `scratchpad show`
5. Move back to output 1 with `focus output`
All of the containers in output 1 end up being focused instead of just the inactive one.
=> root: Set inactive focus when scratchpad is moved to new workspace

sway/desktop/output.c
Otherwise the initial bounds would be `INT_MAX` until `handle_mode` or `handle_commit` is called :)
=> Init the damage_ring bounds on output creation

sway/sway-input.5.scd
The Wayland protocol better serves this purpose, and is supported by more compositors.
=> man: deprecate seat cursor move/set/press/release

meson.build, sway/ipc-json.c
This was introduced in the last libinput release.
Fixes the following error:
../sway/ipc-json.c:928:17: error: enumeration value 'LIBINPUT_CONFIG_ACCEL_PROFILE_CUSTOM' not handled in switch [-Werror=switch]
928 |                 switch (libinput_device_config_accel_get_profile(device)) {
|                 ^~~~~~
=> ipc: add LIBINPUT_CONFIG_ACCEL_PROFILE_CUSTOM entry

swaybar/render.c
The opaque region is set incorrectly if updated on-the-fly if switching from an opaque to a non opaque background.
=> swaybar: Set opaque region properly

sway/desktop/output.c
#7524 was a partial fix. Seems like this is still an issue when unplugging and plugging the monitor back in.
I'm not sure if it's a good fix due to the `update_output_manager_config` function being called from other places though.
=> Fix damage-ring bounds not being set when unplugging -> plugging in monitor

sway/desktop/output.c
We already do this in handle_commit().
=> Remove duplicate wlr_damage_ring_set_bounds() call

include/sway/input/seat.h, include/sway/output.h, sway/desktop/output.c, sway/desktop/render.c, sway/input/seat.c, sway/input/seatop_move_tiling.c
Ref: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3631
=> Use wlr_render_pass

include/sway/input/cursor.h, include/sway/input/seat.h, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_down.c
https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/37f42e2d introduces touch cancel events to wlroots. At the moment touch sequences that are cancelled by libinput are not terminated by a cancel or end event. The only way client applications can become aware of this is by tracking touch ids. When a new touch sequence is started that reuses a previously cancelled touch id, said application can assume that the previous touch sequence was cancelled. However, this approach introduces a range of other issues. See https://github.com/xournalpp/xournalpp/pull/4852 for the original motivation.
I've performed some rudimentary tests on a Surface Go running a 6.2 mainline kernel. Do you have any wishes for an exhaustive test plan?
=> Add support for touch cancel events

swaybar/ipc.c
This fix resolves a bug where setting `binding_mode_indicator` or `workspace_indicators` to `no` in the config prevented them from being properly enabled with `swaymsg bar bar-0 binding_mode_indicator on` or `swaymsg bar bar-0 workspace_indicators on`.
The fix that I implemented simply removes the guards that restrict swaybar's event subscriptions to only the required events. Would it be preferable to reintroduce the guards and have swaybar close and resubscribe the socket on configuration updates, so that it only subscribes to required events?
=> swaybar: fix configuration bug with binding_mode_indicator and workspace_indicators

sway/desktop/render.c
Two regression fixes:
1. Apply clip properly without affecting the projection matrix
2. Clear using the proper dimensions when scaling is in use
Seems to do the trick locally.
=> Fix wlr_render_pass regressions

sway/desktop/render.c
We need to provide an unclipped dst_box.
Fixes: https://github.com/swaywm/sway/issues/7573
Regressed by: https://github.com/swaywm/sway/pull/7552
=> render: fix titlebar texture clipping

sway/desktop/layer_shell.c
Issue in question:
https://github.com/swaywm/sway/assets/35975961/236f6a6a-d03c-4560-9334-3982e9aaddcc
To reproduce:
1. Open sway with two outputs
2. Run rofi-wayland, `rofi -show drun`
3. Type something in so that there are no results and hit enter
4. If the bug doesn't appear, wait a few seconds
=> Fix layer old damage not being offset by the monitor layout coords

sway/desktop/output.c
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4159
> ../sway/desktop/output.c:618:47: error: too few arguments to function 'wlr_renderer_begin_buffer_pass'
>   618 |         struct wlr_render_pass *render_pass = wlr_renderer_begin_buffer_pass(
>       |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
encountered in [nixpkgs-wayland](https://github.com/nix-community/nixpkgs-wayland) update job
log showed that people used chase in their messages relating to fixing wlroots changes
=> chase wlroots wlr_renderer_begin_buffer_pass change

include/sway/input/seat.h, include/sway/layers.h, sway/desktop/layer_shell.c, sway/input/seat.c, sway/input/seatop_default.c, sway/server.c
Supersedes #5974 
Tested (from original PR) with gtk-layer-demo:
More test cases would be appreciated :)
=> Add support for layer-shell on_demand keyboard interactivity

include/sway/output.h, include/sway/server.h, sway/desktop/output.c, sway/server.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4046
Depends on: #7493
=> Handle gamma-control-v1 set_gamma events

sway/input/input-manager.c
=> Fix `bindsym --to-code` not respecting input configs

sway/desktop/output.c
In case a display is unplugged, the sway output may be removed from the userdata before the gamma_control can be reset. In this case we can't schedule a commit on the output, simply return within the function.
backtrace full:
```
#0  handle_gamma_control_set_gamma (listener=0x4856a8 <server+616>, data=0x7ffce1ed59c0) at ../sway/desktop/output.c:1105
server = 0x485440 <server>
event = 0x7ffce1ed59c0
output = 0x0
#1  0x00007f430d1dca0c in wl_signal_emit_mutable ()
from /nix/store/ky1g6ylzr2m4bq8fy0gzrnqmjr6948k5-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#2  0x00007f430d142370 in gamma_control_destroy (gamma_control=0x29eb9b0) at ../types/wlr_gamma_control_v1.c:37
manager = 0x27e33e0
output = 0x2a10770
event = {output = 0x2a10770, control = 0x0}
#3 …
```
=> gamma_control_v1: handle destroyed output

meson.build, sway/desktop/render.c, sway/meson.build
The old solution only worked with gles2. The new built in wlroots solution works with all renderers!
=> render: Use wlroots scale filter

sway/input/cursor.c
wlr_xcursor_manager_set_cursor_image() is deprecated.
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4170
=> Use wlr_cursor_set_xcursor()

include/sway/desktop/idle_inhibit_v1.h, include/sway/server.h, sway/commands/inhibit_idle.c, sway/desktop/idle_inhibit_v1.c, sway/desktop/transaction.c, sway/server.c
We only have a single running server, no need to keep track of multiple server instances. Also no need to support multiple idle inhibit managers.
=> idle-inhibit-v1: simplify with server global

include/sway/input/cursor.h, include/sway/input/input-manager.h, sway/input/cursor.c, sway/input/input-manager.c, sway/input/seatop_default.c
On multi-seat configurations a zwp_pointer_gestures_v1 global was created for every seat.
Instead, create the global once in the input manager, to be shared across all seats.
=> input: Move wlr_pointer_gestures_v1 to sway_input_manager

swaybar/input.c
When there's only one workspace open, swaybar will mark it as not visible if the user scrolls on it and eventually incorrectly fail the `active->visible` assert. Fix this by making sure that new and current workspace aren't the same.
=> swaybar: don't set current workspace as not visible

swaybar/input.c
This fixes a rare crash when [`wl_cursor_theme_get_cursor`](https://gitlab.freedesktop.org/wayland/wayland/-/blob/6d3334657180f3663b8d83636f4d1bc2097492d2/cursor/wayland-cursor.c#L439-449) fails and returns NULL. This crash will not happen under normal usage -- I suspect the one computer I have for which this happens has a broken set of cursor config files. Still, even in that situation I think it is better to print an error than segfault or suddenly exit.
=> swaybar: handle wayland-cursor failures

sway/commands/resize.c
i3 shrinks/grows tiled windows according to screen size for ppt unit. So, for i3 compatibility, I've changed how sway calculates resizing amount for tiled windows.
Resolves: #7593
You can find the demonstration of default behaviour on issue #7593 and here is after this change:
https://github.com/swaywm/sway/assets/17731403/3e9a200c-10e7-4fb4-94d7-c1e9ee99a99a
Note: This is my first time trying to contribute to open source. Please feel free for suggestions/advices. 😇
=> Calculate tiled resizing amount from parent/workspace

sway/desktop/output.c, sway/desktop/render.c
```
sway-unwrapped> ../sway/desktop/render.c: In function 'render_surface_iterator':
sway-unwrapped> ../sway/desktop/render.c:153:9: error: implicit declaration of function 'wlr_presentation_surface_sampled_on_output'; did you mean 'wlr_presentation_surface_textured_on_output'? [-Werror=implicit-function-declaration]
sway-unwrapped>   153 |         wlr_presentation_surface_sampled_on_output(server.presentation, surface,
sway-unwrapped>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sway-unwrapped>       |         wlr_presentation_surface_textured_on_output
```
https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/67447d6cb407ac5b6405b4dbae01a38567feb111
I don't know if it should be
`wlr_presentation_surface_textured_on_output`
or …
=> chase wlroots 'presentation-time: add separate helper for zero-copy '

swaynag/swaynag.c
Same as 92244c87dbb8 ("swaybar: handle wayland-cursor failures") but for swaynag.
Closes: https://github.com/swaywm/sway/issues/7671
=> swaynag: handle wayland-cursor failures

sway/commands/seat/idle.c, sway/input/seat.c, sway/sway-input.5.scd
Sway has two knobs to control idling:
- seat idle_inhibit: when the seat is active (ie. not idle), this extends the active state. When the seat is idle, this is ignored.
- seat idle_wake: when the seat is idle, this wakes up the seat. When the seat is active, this is ignored.
The motivation for the deprecation is two-fold:
- The concept of "seat idle state" is ill-defined. Each idle-notify-v1 client will pass a different idle timeout. With the old logic, a seat was declared idle if and only if all idle-notify-v1 timeouts have expired. However, if only a portion of the timeouts have expired, then some clients would wake up, and the rest would stay active. This is inconsistent with the definition of idle_inhibit/idle_wake: idle_inhibit was used for clients which are waking up.
- It never …
=> Deprecate seat idle_wake

sway/commands/resize.c
Splitting and then hiding a scratchpad container results in a segfault.
fixes #6693
=> fix crash when resizing tiled scratchpad windows

include/sway/input/cursor.h, include/sway/server.h, protocols/meson.build, sway/input/cursor.c, sway/server.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4106
~~TODO: animated cursors. Ideally `wlr_xcursor_manager` would be patched to support this.~~ `wlr_cursor` now supports animated cursors.
=> Add support for cursor-shape-v1

sway/tree/view.c
If a floating client resizes itself, sway updates several of its internal dimensions to match but not wlr_toplevel. This means that the next time wlroots sends a toplevel configure event, it can have wrong coordinates that resize the client back to its old size. To fix this, let's just use wlr_xdg_toplevel_set_size so the wlr_toplevel has the same dimensions as sway. Fixes #5266.
=> view: update wlr_toplevel size on client resizes

sway/desktop/xdg_shell.c, sway/tree/view.c
Reverts #7676 and applies the logic to strictly xdg_shell and not xwayland to avoid some bad bugs there. cc @rpigott
=> xdg_shell: update wlr_toplevel size on client resizes

protocols/meson.build
Without this change, the `meson build/` step of compiling sway cannot be completed successfully. This is related to #7719
=> fixing `meson build/` fail on debian

sway/commands/input/map_from_region.c
When using the `map_from_region` for pen tables, we will usually make the available area as big as possible while maintaining the proportions with the screen.
As most of the tablets uses a 16:10 ratios while the most popular screen ratios is still 16:9, the argument for most people should be `0x0 1x0.9` to have the maximum effective area.
However, the argument above won't work because the current code will treat `0x...` as a hexadecimal number, instead of setting both `x` and `y` to `0`.
This fix allows the use of the following syntax:
```
input type:tablet_tool {
map_from_region 0x0 1x0.9
}
```
=> fix: don't treat 0x prefix as hex identifier

sway/server.c
This fixes #7727, a crash which occurs when one runs Sway with a config file containing `xwayland disable`.
=> sway/server: Fix null pointer crash when Xwayland disabled

include/sway/desktop/idle_inhibit_v1.h, include/sway/server.h, sway/desktop/idle_inhibit_v1.c, sway/input/cursor.c, sway/input/keyboard.c, sway/input/seat.c, sway/input/switch.c, sway/server.c
We support the standard idle-notify protocol since Sway 1.8: https://github.com/swaywm/sway/commit/9400bd963c59fd59f597c1477b8021a82ca0a72e
~~Depends on #7641~~
=> Drop support for KDE's idle protocol

sway/sway-input.5.scd
The documentation didn't explain the meaning of the terms 0..1. This PR makes the implication explicit.
Also, adding a commonly used example as in #7724.
=> doc: clarify arguments for `map_from_region`

.gitignore, sway/config/output.c
This PR adds a proposal to solve issue #7599.
It replaces the previous behavior which required an exact match of the output refresh rate by choosing the refresh rate that is closest to the specified target refresh rate (up to a difference of 1Hz). The limit of 1Hz is arbitrarily chosen, other suggestions are also welcome.
Otherwise, if there is no match, the fallback to the highest available refresh rate (for the same resolution) is kept as before.
As discussed in the issue, I also made the logging more verbose to provide additional information about the mode that gets activated in the end.
Additionally, I added the directory `.cache/` to the `.gitignore` which is the default cache directory generated by the `clangd` language server. If you want to have this change in a separate PR or …
=> Allow approximate output refresh rate

sway/tree/view.c
wlr_surface_has_buffer() is insufficient; if a client has committed a buffer but it couldn't be applied, NULL deref happens in the next line.
=> view: check if the buffer was uploaded on save

sway/desktop/xdg_shell.c
3d5ae9813d390ea747462fc0026ee43b7c77d0f2 added logic to change the underlying wlr_toplevel size for floating containers, but it does it even when the pending state is fullscreen. This shouldn't be done there because sway's internal size will not be incorrect and there are cases when clients have no idea which output they are going to end up on (like setting fullscreen during initialization) and thus cannot know the correct size in advance.
cc @rpigott: Sorry, I didn't realize that my commit broke this edge case. Easy reproduction would be `mpv --fs video.mkv` and it should be the wrong size if the video size doesn't match your monitor's size. Should affect any other application that initially launches fullscreen as well.
=> xdg_shell: don't update wlr_toplevel if the container has no size yet

sway/desktop/output.c
References:https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4411
fix #7802
=> chase wlroots!4411 "backend: drop wlr_backend_get_presentation_clock()"

swaynag/config.c
`gcc-14` added a new `-Walloc-size` warning that makes sure that size of an individual element matches size of a pointed type:
https://gcc.gnu.org/PR71219
`sway` triggers it on `calloc()` calls where member size is used as `1` (instead of member count):
swaynag/config.c:169:65: error: allocation of insufficient size '1'
for type 'struct swaynag_button' with size '48' [-Werror=alloc-size]
169 | struct swaynag_button *button = calloc(sizeof(struct swaynag_button), 1);
=> swaynag/config.c: fix build against gcc-14 (-Walloc-size)

sway/input/seat.c, sway/input/tablet.c
This reverts commit afde6369
"seat: avoid unneeded reloading xcursor theme".
Always avoiding to reload the xcursor theme prevents reloading the
cursor even when this is desired. Instead seat_configure_xcursor
can determine whether a full reload is necessary.
To stay with the spirit of the reverted change, cursors are only fully
reloaded, if the theme has changed.
Fixes #6931
=> seat: Fix reloading cursor theme after change

sway/tree/view.c
Remove any existing executed criteria items at unmap time. If a window gets unmapped but not destroyed, we want to reapply 'for_window' criteria. Fixes #6905.
=> view: re-apply criteria when window gets unmapped

include/sway/server.h, sway/server.c
As a first step, deny access to privileged protocols to sandboxed
apps.
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3589  
Depends on #7647
=> Add support for security-context-v1

common/background-image.c, common/meson.build, include/background-image.h, include/swaybar/image.h, swaybar/image.c, swaybar/meson.build, swaybar/tray/item.c
As swaybg/swaylock are no longer part of this repository, `render_background_image` can be dropped.
Since `load_background_image` is only used by swaybar, move it out of `common/` into `swaybar/` , and give it a better name.
=> Remove unused render_background_image and move load_background_image to swaybar

sway/config.c
`gcc-14` added a new warning around dangerous use of `strncpy()` withi known overflow:
../sway/config.c: In function 'do_var_replacement':
../sway/config.c:983:33: error: '__builtin___strncpy_chk' specified bound depends on the length of the source argument [-Werror=stringop-truncation]
983 |                                 strncpy(newptr, var->value, vvlen);
|                                 ^
../sway/config.c:971:45: note: length computed here
971 |                                 int vvlen = strlen(var->value);
|                                             ^~~~~~~~~~~~~~~~~~
It's a bit fishy to rely on truncating behaviour of `strncpy()`. The change uses `memcpy()` as more explicit way to express copy of `vvlen` bytes.
=> sway/config.c: use `memcpy()` for known buffer size

sway/tree/root.c
wlroots will destroy this object itself.
=> Don't destroy output layout on exit

sway/commands/output/background.c
This changes the output of `swaymsg` to indicate the failure to set the background image:
```
[
{
"success": false,
"parse_error": false,
"error": "unable to access background file '/path/to/file'"
}
]
```
This change will also lead to not applying other output options when a command like `swaymsg -r 'output * bg /non/accessible/file scale 1'` is executed.
However, I think that is an improvement in user experience - if they should be run independently of each others success, they could be split into two `swaymsg` calls.
Closes #7859
=> Raise error on non-accessible background file

include/sway/server.h, meson.build, sway/main.c, sway/server.c
Use the DRM API instead of `/proc/modules`, and add DisplayLink.
Depends on https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4493
=> Improve proprietary driver detection

include/sway/output.h, sway/desktop/output.c
Since output layout is destroyed when the wayland display is destroyed we run into a destroy listener order problem: Either the display starts destroying the outputs first, in which case we're good: The existing handling will clean up. However, things go wrong if the display decides to destroy the output layout first. In this case, sway will hold invalid references to the output layout as part of each output so that when it finally goes to destroy them, sway will dereference destroyed output layout bits.
Ref: https://github.com/swaywm/sway/pull/6844#issuecomment-1843599513
=> output: Destroy when output layout is destroyed

sway/input/cursor.c
Update for a wlroots breaking change which resets the committed mask.
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4478
=> Check wlr_pointer_constraint_v1_state.cursor_hint.enabled

sway/server.c
Allowing sandboxed clients to request DRM leases has security implications.
=> Mark DRM lease protocol privileged

include/sway/server.h, sway/main.c, sway/server.c
7e69a7076fc8 ("Drop wl_drm") has dropped wl_drm, however a lot of software wasn't quite ready for this (Xwayland, libva, amdvlk). Keep wl_drm disabled by default to pressure the wl_drm phase-out, but add a -Dlegacy-wl-drm flag for users to restore the previous behavior in the meantime.
References: https://github.com/swaywm/sway/issues/7897
=> Add debug flag to re-enable wl_drm

sway/desktop/layer_shell.c
Got a crash after waking my display (which causes a momentary unplug event):
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000423647 in find_mapped_layer_by_client (client=0x19dd8f0, ignore_output=0x0) at ../sway/desktop/layer_shell.c:144
144                             struct wlr_layer_surface_v1 *layer_surface = surface->layer_surface;
[Current thread is 1 (Thread 0x7f1f7c5b3ac0 (LWP 2473))]
(gdb) bt
#0  0x0000000000423647 in find_mapped_layer_by_client (client=0x19dd8f0, ignore_output=0x0) at ../sway/desktop/layer_shell.c:144
#1  0x000000000042379f in handle_node_destroy (listener=0x1aceae0, data=0x0) at ../sway/desktop/layer_shell.c:178
#2  0x00007f1f7d55adcc in wl_signal_emit_mutable (signal=<optimized out>, data=0x0) at ../src/wayland-server.c:2241
#3 …
```
=> Fix SIGSEGV on output destroy

sway/desktop/layer_shell.c
Otherwise we would skip arranging the rest of the surfaces if one of them isn't initialized.
=> layer_shell: Fix typo of return instead of continue

sway/commands/output.c, sway/config/output.c
This PR checks if the execution of swaybg was successful by checking the return value of `spawn_swaybg`.
However, this is not sufficient to fix the issue that success is reported if the command does not exist (incorrect value of `swaybg_command` in config or `swaybg` is not installed).
The failure of the forked `swaybg` process is not propagated.
Unfortunately, checking for this error is not entirely trivial since `swaybg` does not return if it is successful.
Thus, I added a timeout after which `swaybg`'s execution is considered successful (if it didn't fail before).
This has the drawback that (at least on my system) I got the following error message up to four times (failure) or up to two times (success) following the execution of a `bg` command:
```
00:00:08.457 [ERROR] [wlr] …
```
=> Propagate success/failure of swaybg execution

sway/config.c
Otherwise, an error will be shown whenever reloading due to the value of primary_selection being reset to true.
=> sway/config.c: only reset primary_selection at launch

include/sway/desktop/transaction.h, include/sway/layers.h, include/sway/tree/view.h, sway/desktop/layer_shell.c, sway/desktop/transaction.c, sway/desktop/xdg_shell.c, sway/input/cursor.c
We had this `SWAY_SCENE_DESC_POPUP` type floating around that would only handle popup arrangement for xdg_shell. This was originally created to have popups follow the location of views as they move.  I had the same concern for layer_shell, but I only moved popups for a layer shell when that layer shell has been committed. This is wrong because if a layer_shell commits, we could potentially arrange other layer shells to move and those popups wouldn't move as well. This system ties it all together into a common system. 
This is also a soft requirement for input_method popups as they have a similar concern.
=> Add a common popup management struct

include/sway/tree/view.h, sway/tree/view.c
It's not used and causes a crash when a view is destroyed.
=> view: drop ext_foreign_destroy

include/sway/server.h
The header is not installed by wlroots when the DRM backend is disabled. We don't need it here, so don't include it.
Closes: https://github.com/swaywm/sway/issues/7943
=> Fix build with wlroots DRM backend disabled

include/sway/desktop/launcher.h, include/sway/tree/view.h, sway/desktop/launcher.c, sway/tree/view.c, sway/xdg_activation_v1.c
Where incomplete means that the requesting app did not provide a focused surface or a valid input event serial.
The token is still valid, so set the urgency instead.
See also #7446
***
This works exactly as I imagined. With `for_window [app_id=xxx] focus_on_window_activation focus`, the following happens:
A self-issued token without a serial (`QWindow::alert()` in Qt 6.6) can set urgency but does not switch workspace or bring the window forward.
A token from a click on mako notification allows the window to activate itself.
I'm not happy with the abuse of `launcher_ctx` (which may be not set) for an unrelated flag. Really don't see a way to avoid this, because it's too late to check if the token was fully validated in `request_activate`.
=> xdg-activation: deny activation if the token is incomplete

include/sway/input/text_input.h, include/sway/input/text_input_popup.h, sway/desktop/layer_shell.c, sway/input/text_input.c
May I continue this pr in https://github.com/swaywm/sway/pull/5890 ?
=> text_input: Implement input-method popups

sway/ipc-json.c, sway/sway-ipc.7.scd
See: https://i3wm.org/docs/ipc.html
=> Add `floating` and `scratchpad_state` properties to GET_TREE to restore IPC parity with i3

sway/input/cursor.c, sway/input/input-manager.c, sway/input/seat.c
wlroots has changed the naming, causing the following build errors when building:
error: ‘WLR_INPUT_DEVICE_TABLET_TOOL’ undeclared
=> input: Rename WLR_INPUT_DEVICE_TABLET_TOOL to WLR_INPUT_DEVICE_TABLET

sway/commands/move.c
My code archaeology isn't good enough to determine what this is here for, but it isn't correct. We should be able to move containers in a direction without focusing them. AFAICT i3 doesn't do this, so we shouldn't either.
This fixes ipc commands like move \<dir\> with criteria that apply to containers which are not the current focus.
=> commands/move: do not force focus on the moved container

sway/config.c
If we can't create the XKB keymap used for keysym translation,
gracefully error out instead of crashing. This can happen if the
XKB_DEFAULT_LAYOUT is set to an invalid value, for instance.
Closes: https://github.com/swaywm/sway/issues/7789
=> config: error out on keysym translation XKB state failure

include/sway/output.h, sway/config/output.c
This was useful when wlroots backends were updating the current mode on their own. This is no longer the case.
=> config/output: drop enabling flag

sway/server.c
Same as [1].
I originally tried to properly handle seat destruction, but that turned out to be a can of worms [2].
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4590
[2]: https://github.com/swaywm/sway/pull/8034
=> server: fix wlr_seat use-after-free on exit

sway/sway.5.scd
This  PR documents the existing modifier names supported by sway as part of the description of `bindsym` in the man page `sway(5)`.
Intended to be merged before #8085.
=> man: document supported modifier names

include/sway/config.h, sway/commands/output.c, sway/commands/output/toggle.c, sway/config.c, sway/config/output.c, sway/desktop/output.c
Use the new `wlr_backend_commit` and `wlr_swapchain_helper` to light up outputs and apply configuration changes.
Works in local testing, but as sway's output configuration system is a bit complicated it wouldn't hurt with more testing.
=> output: wlr_backend_commit and wlr_swapchain_helper

sway/sway-ipc.7.scd
Without this change, i see the following in the sway-ipc manpage:
```
9. GET_CONFIG
MESSAGE
Retrieve the contents of the config that was last loaded
REPLY
An object with a single string property containing the contents of  the
config
Example Reply:
{
"config": "set $mod Mod4nbindsym $mod+q exitn"
}
```
=> sway-ipc(7): Escape backslashes correctly in GET_CONFIG output

sway/input/keyboard.c, sway/sway.5.scd
This PR implements alternative human-readable names for the logo key (Mod4) as proposed in #8084.
Implemented in this PR are the names "Super", "Meta", and "Logo".
This is the first time the supported modifier names have been touched since #153, almost 9 years ago (besides moving the code around into different files and switching from wlc to wlroots).
=> input: add Super as alternative for Mod4

include/sway/config.h, sway/config/output.c
Output configuration can be applied to a particular output in three
ways: As a wildcard, by connector name and by identifier. This in turn
means that three different configurations must be handled at any given
time.
In the current model, this is managed by merging new configuration into
every other matching configuration. At the same time, an additional
synthetic configuration is made which matchehes both identifier and name
at the same time, further complicating logic.
Instead, manage and store each configuration independently and merge
them in order when retrieving configuration for an output. When changes
are made to a less specific configuration, clear these fields from more
specific configurations to allow the change to take effect regardless of
precedence.
Depends on: …
=> config/output: Refactor handling of tiered configs

sway/server.c
wlr_renderer_get_{dmabuf|shm}_texture_formats have been replaced by a unified wlr_renderer_get_texture_formats interface using buffer caps.
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4644
=> server: Use wlr_renderer_get_texture_formats

sway/config/output.c
When storing a config, we need to find the output that is being configured to extract its identifier. output_by_name_or_id does not return outputs that are disabled, and using this makes it impossible to merge configurations related to disabled outputs.
Switch to all_outputs_by_name_or_id.
Fixes: https://github.com/swaywm/sway/issues/8141
=> config/output: Use all outputs for config merge

include/sway/config.h, sway/config/output.c, sway/desktop/output.c
The original sway output config implementation enabled one output at a time, testing modes, render formats and VRR support as it went along. While this sort of fallback is easy to do, it has the downside of not considering the effect of neighbor outputs on the configuration viability.
With backend-wide commits, we can now better consider the effect of neighbor outputs, but to handle the fact that we commit all outputs at once we need to perform a more elaborate search of viable configurations.
Implement a recursive configuration search for when the primary configuration failed to apply.
=> config/output: Search for output config fallbacks

sway/tree/container.c
Fixes "Invalid rectangle passed" errors printed by Pixman.
=> tree/container: ensure pixman rect is valid in container_arrange_title_bar()

sway/desktop/layer_shell.c
Since layer shell surfaces are assigned an output on creation, before being mapped, it is possible to provide them with an output scale immediately. This commit does this.
I do not know the scene graph code very well, so it's possible this is the wrong place to add the `wlr_fractional_scale_v1_notify_scale()` call. (The other point I was considering was in `wlr_scene_layer_surface_v1_create()`, the first wlroots function that could know about the output which the client (or Sway, if no output specified) picked, but I don't know if it is possible to get an output scale within that function.)
This can be tested with the most recent (git) version of swaybg, which supports wp-fractional-scale-v1. With non-integral output scales, like 1.5, swaybg should only render a single buffer, and the …
=> desktop/layer_shell: provide fractional scale on creation

sway/config/output.c
If there's no config for the output, oc is null, but some screens might have a default rotation, causing the log call to dereference a null pointer.
=> sway/config/output.c: fix null deref on output config

.builds/alpine.yml, include/sway/criteria.h, include/sway/server.h, include/sway/tree/root.h, include/sway/tree/view.h, meson.build, meson_options.txt, sway/commands/swap.c, sway/commands/xwayland.c, sway/criteria.c, sway/desktop/transaction.c, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_default.c, sway/ipc-json.c, sway/meson.build, sway/server.c, sway/tree/root.c, sway/tree/view.c
Instead of having a build-time option to enable/disable xwayland support, just use the wlroots build config: enable xwayland in Sway if it was enabled when building wlroots. I don't see any use-case for disabling xwayland in Sway when enabled in wlroots: Sway doesn't pull in any additional dependency (just pulls in dependencies that wlroots already needs). We have a config command to disable xwayland at runtime anyways.
This makes it so xwayland behaves the same way as other features such as libinput backend and session support. This also reduces the build matrix (less combinations of build options).
I think we originally introduced the xwayland option when we didn't have a good way to figure out the wlroots build config from the Sway build system.
=> build: drop xwayland option

sway/tree/view.c
As of commit 9da295c11, surfaces of `xdg_toplevel`s are clipped to a region defined by the geometry. This causes drop shadows of floating windows to be cut off, as seen with gnome-calculator against a white background:
This PR will avoid clipping if a `sway_view` is in a floating container and using CSD.
=> tree/view: Do not clip to geometry if using CSD

include/sway/server.h, sway/server.c
Regular Wayland clients shouldn't care about the position or size of outputs. Hide xdg_output from unprivileged clients to make sure they're not doing shenanigans with this information.
=> server: hide xdg_output from unprivileged clients

sway/input/text_input.c
Clients get confused when modifier events are sent before the keymap.
=> input/text_input: ensure keyboard is set before sending modifiers

include/sway/criteria.h, include/sway/input/input-manager.h, sway/commands/input/events.c, sway/commands/input/xkb_switch_layout.c, sway/commands/move.c, sway/commands/seat/cursor.c, sway/commands/seat/pointer_constraint.c, sway/commands/seat/shortcuts_inhibitor.c, sway/commands/shortcuts_inhibitor.c, sway/config.c, sway/config/bar.c, sway/config/input.c, sway/config/output.c, sway/criteria.c, sway/desktop/launcher.c, sway/desktop/transaction.c, sway/input/cursor.c, sway/input/keyboard.c, sway/input/seatop_default.c, sway/input/switch.c, sway/input/tablet.c, sway/input/text_input.c, sway/ipc-json.c, sway/tree/workspace.c
The only reason it's included there is for a declaration of struct sway_server, but we can just forward-declare it.
This avoids rebuilding almost all of Sway when touching server.h. All other server.h includes are from source files, not headers.
=> Drop server.h include from input/input-manager.h

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml, include/sway/commands.h, include/sway/config.h, include/sway/output.h, sway/commands/output.c, sway/commands/output/color_profile.c, sway/config/output.c, sway/desktop/output.c, sway/meson.build, sway/sway-output.5.scd, sway/tree/output.c
This PR matches the **very WIP** wlroots MR [4280](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4280).
This requires the Vulkan renderer to be useful. (Use `WLR_RENDERER=vulkan` ; setting  `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation`  to enable validation layers may be useful for testing.)
Example usage:
```
swaymsg output '*' color_profile icc /usr/share/color/icc/colord/ProPhotoRGB.icc
```
Known issues: 
* ~some race condition in which only some frames render correctly; causes flickering~ (fixed)
* ~Only applies with bit depth 10, at the moment~ (fixed)
* ~Having to copy the `struct wlr_color_transform` a number of times is awkward~ (now using reference counting)
=> sway/commands/output: Add command to set color profile

sway/config/output.c, sway/desktop/output.c
We were only passing the color transform when calling wlr_scene_output_commit(). However when modesetting or pushing a new gamma LUT we render via wlr_scene_output_build_state(). Pass the color transform there as well.
cc @mstoeckl
=> Set color transform when calling wlr_scene_output_build_state()

sway/tree/view.c, sway/tree/workspace.c
To reproduce:
1. Open a new (terminal) window
2. Execute: `sleep 5 && notify-send crash "this is how you crash"`
3. Send the container to the scratchpad before the 5 seconds sleep is finished
4. `sway` will crash as soon as the notification is sent.
The reason for this is that `container_is_scratchpad_hidden` returns false and `workspace_detect_urgent` is run, calling `workspace_find_container` with a `NULL` workspace, causing it to crash because of a null pointer dereference: https://github.com/swaywm/sway/blob/master/sway/tree/workspace.c#L695-L696
=> fix crash when setting urgency on an hidden scratchpad container

sway/tree/view.c
One of the nice things about explicit scale notifications is that it erases any confusion that would necessitate hacks like #6479. We should really take advantage of this to be nicer to fast clients, letting them know the intended scale as early as possible.
Ideally we would also send a better guess at the correct dimensions too, but that's a longstanding bug (can't find an issue for it though?) and a bit more of a hassle.
In practice, I observe the following less-than-ideal behavior on master: with the release of foot 1.15.2, my zsh prompt is reflowed after the first frame because the terminal initially has a larger number of columns than the 1.5 scale actually permits in the final window geometry. As a result, my zsh prompt begins on the second line instead of the first of a new …
=> view: send scale notification when the output is known

sway/config/output.c
Adaptive sync is a "soft" setting which we degrade of off when not supported. Some outputs types do not support turning it off (Wayland, X11), which makes for an awkward three-way test where we first enable, disable and finally unset the setting.
wlr_output.adaptive_sync_supported tells us whether the output definitely does not support making changes (backend without support, connector without the feature), or whether it might work.
Use this to avoid wasting time on adaptive sync test that can never succeed, and to avoid the Wayland/X11-backend specific unset step.
=> config/output: Skip VRR tests when not supported

sway/input/keyboard.c
"The compositor must not send this event if the wl_keyboard did not have an active surface immediately before this event. The compositor must not send this event if state is pressed (resp. released) and the key was already logically down (resp. was not logically down) immediately before this event."
From https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/382
=> input/keyboard: don't send key release if we don't have focused surface

include/sway/server.h, sway/desktop/output.c
Add a 10 millisecond modeset debounce timer.
Depends on https://github.com/swaywm/sway/pull/8095
=> desktop/output: Debounce modesets

sway/ipc-json.c
Tabbed or stacked containers with more than one child always have a titlebar.
19df2e590602abe0b5e1b53bc11debdb37be3fbe changed `rect` to exclude the titlebar, but overlooked this case, causing my screenshot script to miscalculate the coordinates of the window contents.
=> ipc: consider all titlebar cases for window_rect

sway/desktop/xdg_shell.c
the surface isn't initialized yet when we first handle it in `handle_xdg_shell_toplevel`, move setting WM capabilities to handle_commit instead.
Fixes warnings from wlroots about a configure being scheduled for uninitialized surface
=> xdg_shell: don't send configure events to uninitialized surfaces

include/sway/tree/container.h
This function doesn't exist anymore.
=> tree/container: drop decl for container_update_textures_recursive()

sway/sway_text_node.c
When a floating container has a titlebar, render_backing_buffer() ends up being called each time the container is moved. Add some more checks for no-op changes in sway_text_node_set_max_width() and sway_text_node_set_background(). This makes the move smoother.
=> sway_text_node: avoid unnecessary redraws

include/sway/commands.h, include/sway/config.h, sway/commands/input.c, sway/commands/input/clickfinger_button_map.c, sway/config/input.c, sway/input/libinput.c, sway/ipc-json.c, sway/meson.build, sway/sway-input.5.scd, sway/sway-ipc.7.scd
Opening this as a draft since it depends on an unreleased libinput feature.
I recently closed [libinput issue #909](https://gitlab.freedesktop.org/libinput/libinput/-/issues/909) by [implementing](https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/988) a "clickfinger_button_map" option (mirrors "tap_button_map", but for clickmethod "clickfinger").
This implements support for setting such option in Sway. However, this would bump the required libinput version to 1.26, and the dependency comes through wlroots, which supports 1.14 and up. So maybe this code should be conditionally enabled depending on the libinput version during build, and I'm not sure if there is any project policy about this.
=> config/input: Implement libinput clickfinger_button_map option support.

sway/xdg_activation_v1.c
If the launched client decides to pass it's token along as an activation request, allow that. This will make the behavior match tokens provided by an external launcher client.
=> xdg-activation: launcher tokens are activation requests

meson.build
Meson has introduced a relative_to() function [1] in its fs module since version 1.3.
[1]: https://mesonbuild.com/Fs-module.html#relative_to
Same as https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4724
=> build: use fs.relative_to() instead of hand-rolled logic

sway/desktop/output.c
1e0031781fc9 refactored repaint to accumulate all changes in a single wlr_output_state and commit them at the end of the repaint loop, replacing a call to wlr_scene_output_commit. wlr_scene_output_commit contains an early bail-out when no frame has been requested and no damage has accumulated, which was not replicated as part of this refactor, causing the repaint loop to never pause.
Replicate the logic to stop the repaint loop as needed.
Fixes: 1e0031781fc9 ("desktop/output: unify page-flip codepath")
=> desktop/output: Stop repaint loop when not needed

meson.build
When attempting to use Git to populate commit/branch information in a version string, it is possible through repository discovery that it uses Git information not relevant to project. For example, if repository content is extract into an interim build location when using an embedded build framework (e.g. Buildroot), the project will not have its Git repository to refer to. When it cannot find its repository, it will look into its parent folders and may find the Git repository of another project and use its branch/commit information.
This commit provides an explicit path to the project's Git repository when consider commit/branch information. This will prevent any repository discovery from occurring.
=> build: avoid git repository discovery when determining version

sway/desktop/transaction.c
=> transaction: Reparent all container children when disabling for scratpad

sway/server.c
Depends on https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4715
=> Add support for linux-drm-syncobj-v1

sway/config/output.c, sway/desktop/output.c, sway/desktop/tearing.c, sway/server.c, sway/tree/view.c
Fixes: 9a1c411abd8261c121dcd50dfe54132718768084
=> tearing: fix UAF, remove trailing whitespace

sway/commands/input/xkb_switch_layout.c, sway/ipc-json.c
Even though there are already many issues / prs trying to address this problem, including #6484, #6873, #6990, I still get segfaults due to null keymap pointer.
Hence, I would simply suggest to add a check before we call `xkb_keymap_num_layouts`.
=> Add null-safety check for virtual keyboard keymaps

config.in
Even if users don't want these exact tools, at least it gives examples.
Maybe we should use PipeWire instead of PulseAudio? I don't know what the equivalent commands would be thought.
=> Bind a few utilities to special keys in default config

config.in
This removes the last dependency bit on dmenu. No need for "swaymsg exec" anymore: wmenu-run handles the xdg-activation shenanigans.
=> Switch default config to wmenu-run

sway/config/output.c
After 4e38f93f367d ("config/output: Skip VRR tests when not supported"), the configuration search no longer touches VRR state for outputs that are known to not support it. This also means that it will not remove VRR if already set, which could cause output configuration to fail.
Ensure that VRR state is never set for outputs that do not support it by adding the same test for support to queue_output_config.
Fixes: 4e38f93f367d ("config/output: Skip VRR tests when not supported")
Fixes: https://github.com/swaywm/sway/issues/8296
=> config/output: Do not set adaptive_sync if not supported

sway/config/output.c
When doing an output configuration search, the intent is to only look for modes if the output's configuration does not contain a specific mode. This was done by testing if config_has_auto_mode returned false.
config_has_auto_mode had its return values backwards, leading to other modes being tested if the output configuration had specified modes or modelines, leading to unwanted modes being selected.
Invert the function to config_has_manual_mode to give it a clearer name, and fix the return values in the process.
=> config/output: Skip search if config has a mode

sway/commands/move.c
When moving a container to a new workspace, the workspace's dimension are left unset. Usually this doesn't matter, but when moving a floating container to a new workspace on a different output, this leads to the position of the container being calculated with 0, so the container ends up halfway offscreen on the leftmost topmost monitor.
=> sway/commands/move.c: arrange new workspace

sway/tree/container.c
This can cause issues such as the window not being shown at the exact same coordinates when the old and new wlr_box aren't the same dimensions and the container is being moved back-and-forth between them.
For example, in the case where a floating window gets moved from one output to another but the outputs aren't the same resolution. For e.g. have two displays that aren't the same resolution then:
1. Open a floating window and set it to pos 0,0 on output 2
2. Send it to scratchpad then `scratchpad show` on output 1
3. `scratchpad show` on output 2 again
Observe that the window isn't at 0,0 on output 2 anymore.
=> sway/tree/container: don't trunc coords in `floating_fix_coordinates`

sway/sway.5.scd
It's a little tough to notice that the COMMANDS section is actually 3 sections. Here is a simple change to the man page to give the sections their own headings.
=> Use heading markdown to demarcate sections of commands

include/sway/tree/container.h, include/sway/tree/view.h, sway/commands/title_format.c, sway/tree/container.c, sway/tree/view.c
Fixes #8322
This PR moves logic behind title_format support to container. This allows to add title_format to non-view containers, like i3 does.
Usage example: Formatting tab names in tabbed and stacked layouts which contain child layouts
Before:
After:
Related i3 issue: i3/i3#2120
Related i3 PR: i3/i3#2143
=> Move title_format to container

include/sway/output.h, include/sway/server.h, include/sway/tree/root.h, sway/config/output.c, sway/desktop/output.c, sway/server.c, sway/tree/output.c, sway/tree/root.c
Whenever output configurations occurred we would end up re-arranging everything a gajillion times due to several components and listeners all responding to the change by calling `arrange_*`.
We now have a central location where changes occur from - by relying on that we can get down to a single `arrange_layers` per output and a shared `arrange_root` + output manager update... In most cases, as arrange_layers still calls arrange_output/arrange_popups on its own for now.
=> Reduce output configurations and rearranges

sway/desktop/output.c, sway/tree/output.c
Two more places where we did too much stuff on output changes - these are covered by `apply_output_configs`.
=> output: More redundant reconfigures

sway/tree/container.c
The else condition was missed here and we would never skip the % char if it didn't end up matching with any property. Since we fail to skip we would re-evaluate the % in an infinite loop never achieving any forward-progress.
Fixes: https://github.com/swaywm/sway/issues/8333
=> container: Skip % char if it doesn't match a view property

sway/desktop/transaction.c, sway/tree/arrange.c
Instead of attempting to arrange workspaces on a disabled output which may not have a valid geometry, treat workspaces on disabled output as disabled, ensuring that scene nodes are properly disabled and the missing geometry not accidentally relied on.
Fixes: https://github.com/swaywm/sway/issues/8328#issuecomment-2332747218
=> transaction: Disable workspaces of disabled outputs

sway/input/keyboard.c
Previously, we incorrectly only set active keyboard for non-virtual devices. 4c3c0602116c12c2821e1e505e7248b3c642b4ca incorrectly put unrelated code in `sway_keyboard_set_layout`.
Fixes: 4c3c0602116c12c2821e1e505e7248b3c642b4ca
=> sway/input/keyboard: always set active keyboard if there is none

sway/config/output.c
Some display output hardware [1] doesn't support any of the current formats, but works with ARGB8888. Fall back to it if available.
[1] https://github.com/torvalds/linux/blob/196145c606d0f816fd3926483cb1ff87e09c2c0b/drivers/gpu/drm/xlnx/zynqmp_disp.c#L313
=> config/output: support DRM_FORMAT_ARGB8888

include/sway/lock.h, sway/config/output.c, sway/lock.c
Arranging lock surfaces rely on the sway_output width and height being updated, but these are only updated after the commit has been completed and all commit listeners have executed. This means that the lock surfaces will not be appropriately scaled to match a change in output dimensions, and may reveal what is under the lock background.
Replace the implicit arrange through the output commit listener with an explicit arrange after the output configuration is finalized.
This might have regressed by other transition away from output commit listeners for other arrange tasks, but even then it would have erroneously relied on signalling order.
Note: There is still a one-frame glitch on scale change as we only have the new output layout geometry for arrange *after* the output commits have gone …
=> ext-session-lock: Do not use commit listener to arrange

include/sway/config.h, sway/commands/output/render_bit_depth.c, sway/config/output.c, sway/sway-output.5.scd
The [GUD](https://github.com/notro/gud/wiki) driver needs to use RGB565 for performance reasons, but exposes XRGB8888 with the driver doing a conversion in that case, making a fallback insufficient.
Extend the bit depth option to allow lowering to a maximum of 6 bits per channel.
Depends on https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4824 to have any use.
=> Support for RGB565 render format for GUD

include/sway/input/text_input_popup.h, sway/desktop/transaction.c, sway/input/text_input.c
The update method was a big hammer, it did a lot of things.
- This function would recreate the scene every time the input method client commits a new buffer
Instead, we create the scene when the input method surface maps / unmaps.
When the input method is unfocused, we simply disable the scene node.
Fixes: #8086
=> input_method: Split up update method

sway/commands/gaps.c
Checking if the config is not active or is reloading is just a convoluted way of checking if the config is being read.
=> commands/gaps: Check config->reading instead

include/sway/config.h, include/sway/lock.h, include/sway/output.h, include/sway/server.h, include/sway/tree/root.h, sway/commands/output.c, sway/config.c, sway/config/output.c, sway/desktop/output.c, sway/lock.c, sway/server.c, sway/tree/arrange.c, sway/tree/output.c, sway/tree/root.c
Backports: 
- #8349
- #8341
- #8332
- #8331
- #8326
cc @emersion
=> 1.10 backport

sway/commands/move.c
Closes #6818
This extracts the specific part of #6835 that addresses the issue. I'm doing this since the original PR was closed over 2 years ago after the author got informal approval for this part of the change but pushback on other parts (not included here).
> It removes this line
> https://github.com/swaywm/sway/blob/f707f583e17cb5e8323ceb4bfd951ad0465b7d10/sway/commands/move.c#L235
> In order to match the behaviour of i3's move functionality, which can be found [here](https://github.com/i3/i3/blob/c822eff1bfdeac30baf92b14a09d1c81a0193997/src/move.c#L72-L79), posted below:
> ```c
>     /* We compare the focus order of the children of the lowest common ancestor. If con or
>      * its ancestor is before target's ancestor then con should be placed before the target
>      * in the focus …
```
=> Removed destination-is-ancestor check from container_move_to_container to match i3 behaviour

include/sway/config.h, sway/commands/input.c, sway/commands/output.c, sway/config.c, sway/desktop/output.c
During a fresh sway start, we end up doing a bunch of input and output configuration, as each input command triggers input device configuration, and each output command triggers modeset. In addition, because output manager failed to clear the modeset timer, we could end up with another bogus modeset after output manager apply.
Batch input/output configuration during the initial config load, and skip the initial modeset altogether as we don't have any output devices at this point - those come later, and will trigger modeset on their own.
We still waste up to a few milliseconds per input command on my machine due to config store making some costly checks.
=> Reduce modesets and input configuration

swaybar/bar.c, swaybar/ipc.c, swaybar/tray/tray.c
Currently, swaybar does not gracefully die if it detects that the dbus connection was lost. Although it's not recommended to restart dbus without restarting the compositor, it can very easily happen. In the case it does, compositor's tray should not consume 100% cpu until it has to be force killed.
=> swaybar: Fix 100% cpu usage if dbus dies.

release.sh
Otherwise the GitHub release isn't attached to the Git tag.
=> release: push tags before creating GitHub release

sway/desktop/output.c
`output_configure_scene()` will overwrite any alpha that scene tries to set itself. We need to teach `output_configure_scene()` about alpha modifier.
Fixes: #8362
=> Fix alpha-modifier-v1

sway/server.c
sway_root.outputs only include enabled outputs. We also need to re-init the renderer for any disabled outputs, so use sway_root.all_outputs instead.
Resolves the following heap-use-after-free accessing the render formats when a disabled output is modeset after a GPU reset has occurred.
ASan report:
```
=================================================================
==707==ERROR: AddressSanitizer: heap-use-after-free on address 0x522000004930 at pc 0x653f2bb4266c bp 0x7fff72e64220 sp 0x7fff72e64210
READ of size 8 at 0x522000004930 thread T0
#0 0x653f2bb4266b in wlr_renderer_get_render_formats ../subprojects/wlroots/render/wlr_renderer.c:68
#1 0x653f2bb4266b in output_pick_format ../subprojects/wlroots/types/output/render.c:159
#2 0x653f2bb8c4df in manager_output_prepare …
```
=> Re-init renderer for all outputs on lost context

sway/input/text_input.c, sway/scene_descriptor.c
resolve: https://github.com/swaywm/sway/issues/8375
in pr https://github.com/swaywm/sway/pull/8196, when im_popup_surface is unmapped, author set the popup->relative to NULL, butt popup is still in popup groups, where assert the relative is not NULL, this cause the panic
=> fix: sway crashes if switch to another workspace with surface when IME popup is shown

sway/input/seat.c
switching workspace directly to urgent window creates timer which delays reset of urgent state so user is able to notice it. make sure state change is reflected visually as well (border change) by triggering container update
Fixes: #8377
Created PR to get feedback on change proposed in #8377
=> trigger container update after disabling urgent in timer

sway/input/seatop_default.c
Make it so config->floating_mod_inverse only applies when pressing mod, not when clicking on titlebars.
Centralize logic into shared variables.
=> input/seatop_default: refactor move/resize button logic

sway/config/output.c
An issue was reported where default panel orientation no longer worked, and found it to be caused by the configuration `find_output_config` used as a starting point. This in turn was something sway always would apply during config loading, but it likely never had any effect as outputs tended to not show up during that time.
Instead, remove these initial values and make it so that `queue_output_config` fills out all output states even for unset config options, and without regard for the current output state.
=> config/output: Fix default panel orientation and cleanup

sway/config/output.c
Backports: config/output: Fix default panel orientation and cleanup (#8394)
Fixes an issue where initial panel orientation is not respected.
=> backport:  config/output: Fix default panel orientation and cleanup

README.cs.md, README.sv.md
They are not present in other translated README files. Also remove them from README.cs.md and README.sv.md.
=> Remove language bars from remaining non-English README files

sway/tree/container.c
Important for centered titles
Fixes: https://github.com/swaywm/sway/issues/8422
=> container: Properly constrain title bar padding

sway/desktop/transaction.c
Fixes #8120. More changes might be required within IPC to prevent other issues.
=> desktop/transaction: clamp vertical border length to 0

swaynag/swaynag.c
To reproduce the null dereference, run `swaynag` under recent sway or some other compositor supporting cursor-shape-v1, and then change the output scale.
Example:
```
swaymsg output '*' scale 1
swaynag -d -m "Test" &
sleep 1
swaymsg output '*' scale 2
```
Instead of crashing, the error `[swaynag/swaynag.c:161] Failed to get default cursor from theme` is also possible if your cursor theme does not have images for 2x scale; clearing the XCURSOR_THEME environment variable may help.
(The example sometimes produces  `Failed to get buffer. Skipping frame.` warnings for me and produces mis-sized buffers, but that is a separate issue.)
=> swaynag: fix null dereference on scale change

README.hu.md
Fix a few mistakes so the text conforms to
Hungarian orthography. The following rules were
applied (the whole linked page is in Hungarian):
- <https://www.helyesiras.mta.hu/helyesiras/default/akh12#110>
- <https://www.helyesiras.mta.hu/helyesiras/default/akh12#112>
- <https://www.helyesiras.mta.hu/helyesiras/default/akh12#113>
- <https://www.helyesiras.mta.hu/helyesiras/default/akh12#215>
- <https://www.helyesiras.mta.hu/helyesiras/default/akh12#244>
=> Fix orthographic mistakes in Hungarian README

include/sway/config.h, sway/desktop/output.c, sway/ipc-server.c, sway/main.c
Some commands require outputs to be enabled. These commands are deferred to allow outputs to be discovered, but the delayed modeset might only run some time later.
Force a modeset to occur before running deferred commands.
Fixes: https://github.com/swaywm/sway/issues/8433
=> config: Force modeset before running deferred configs

sway/commands/include.c, sway/sway.5.scd
i3 supports including multiple files in a single line, whereas sway limits to single file per line.
=> commands/include: handle many files in single line

sway/desktop/output.c, sway/tree/output.c
The teardown of a sway_output is split in two: begin_destroy and output_destroy. The former clears some state such as NULL'ing the reference to wlr_output, while the latter frees the struct and its remaining resources.
If an output is destroyed while a repaint timer is pending, future frame callbacks will no longer occur as the listener is torn down in begin_destroy, but the repaint timer is not torn down and may still fire until output_destroy is hit. As begin_destroy cleared the reference to wlr_output, this leads to a NULL-pointer dereference.
Tear down the repaint timer in begin_destroy as there is no need for it.
Fixes: fdc4318ac66d ("desktop/output: Clear frame_pending even output is disabled")
=> desktop/output: Clear repaint timer earlier in destroy

meson.build, sway/commands/input/drag_lock.c, sway/input/libinput.c, sway/ipc-json.c, sway/sway-input.5.scd, sway/sway-ipc.7.scd
Use it as the default, as recommended by the libinput release
notes:
https://lists.freedesktop.org/archives/wayland-devel/2024-November/043860.html
(First commit is for backporting only, to fix the build failure.)
=> Add support for LIBINPUT_CONFIG_DRAG_LOCK_ENABLED_STICKY 

sway/tree/container.c
https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/0d6cc471e95c1632b234fc9152659d24fe5982f1 added an assert that all signals are clear when destroying a wlr_scene_buffer, which is currently triggering due to sway not removing the output_enter and output_leave listeners on the container before calling wlr_scene_node_destroy on output_handler. Remove the listeners before wlr_scene_node_destroy is called.
=> tree/container: remove output_{enter,leave} listeners in destroy

sway/commands/bind.c, sway/commands/mark.c
has_prefix() returns a bool, unlike strncmp() which returns an int.
When writing the has_prefix() patch, I said to myself that I really should be careful to remove the integer comparisons, but still managed to miss these.
Fixes: 0c60d1581f7b ("Use has_prefix() instead of strncmp() throughout")
Closes: https://github.com/swaywm/sway/issues/8527
=> Fix has_prefix() comparisons with 0

sway/config/output.c
=> config/output: skip format checks if all are supported

sway/config/output.c
We could be running with a backend which doesn't support DMA-BUFs, e.g. inside a parent Wayland compositor without GPU acceleration.
=> config/output: don't hardcode DMA-BUF in search_render_format()

sway/desktop/layer_shell.c
Found via https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4918
=> layer_shell: cleanup new_popup listener when destroying node

sway/server.c
This change increases the default max buffer size to 1 MiB, preventing clients from crashing when they require more than the default 4096 bytes of buffer.
When an application’s GUI thread is blocked, the Wayland protocol may require larger buffers to handle input events. If the buffer size is insufficient, it can result in client crashes.
For example, Firefox has recently started crashing occasionally with the following crash report:
MozCrashReason: () Error reading events from display: Connection reset by peer
When this happens, the following appears in the Sway logs:
00:13:36.485 [INFO] [wlr] [wayland] Data too big for buffer (4092 + 20 > 4096).
00:13:37.336 [INFO] [wlr] [wayland] error in client communication (pid 3029)
This issue has been observed in Firefox ([Bug …
=> Increase default max buffer size to 1 MiB to prevent client crashes

include/sway/criteria.h, include/sway/tree/view.h, sway/criteria.c, sway/ipc-json.c, sway/sway-ipc.7.scd, sway/sway.5.scd, sway/tree/container.c, sway/tree/view.c, swaymsg/main.c
Rebase and update of https://github.com/swaywm/sway/pull/7187.
Add sandbox properties to IPC JSON, criteria, and title format:
- `sandbox_engine`
- `sandbox_app_id`
- `sandbox_instance_id`
These properties may be set by sandbox engines (e.g. `flatpak`) via the security context protocol: https://wayland.app/protocols/security-context-v1.
Prepend sandbox properties to window title when sandbox engine is set:
```
for_window [sandbox_engine="."] title_format "[%sandbox_engine/%sandbox_app_id/%sandbox_instance_id] %title"
```
Launch an app via `flatpak`:
```
flatpak run org.gnome.clocks
```
Observe JSON layout tree via `swaymsg -r -t get_tree`:
```
"name": "Clocks",
"pid": 14309,
"app_id": "org.gnome.clocks",
...
"sandbox_engine": "org.flatpak",
"sandbox_app_id": "org.gnome.clocks", …
```
=> Expose sandbox properties via IPC JSON, criteria, title format

sway/desktop/output.c
wlr_matrix is now private API.
Fixes #8549
=> Drop wlr_matrix.h include from sway/desktop/output.c

sway/input/cursor.c
Fixes crash when a transient seat client destroys its seat since https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/8f56f7ca43257cc05c7c4eb57a0f541e05cf9a79
=> input/cursor: remove tool_proximity listener in destroy

sway/sway-bar.5.scd
Functionality for switching swaybar's current mode between hidden and docked currently exists, but is absent from the relevant manpage. The described behavior is referenced from [mode.c](https://github.com/swaywm/sway/blob/d093c2e3583e785cb308bec74c08a61e8808faf6/sway/commands/bar/mode.c#L10-L15).
Closes #7646
=> man: Document bar mode toggle command

sway/commands/output/background.c
currently, the output background command handler prematurely returns with an error if the background file cannot be accessed. It should only error if user did not provide fallback color.
closes #8556
=> output/background: fix config ignoring fallback color

sway/ipc-json.c, sway/sway-ipc.7.scd, swaymsg/main.c
Adds the [ext-foreign-toplevel-list-v1](https://wayland.app/protocols/ext-foreign-toplevel-list-v1) toplevel identifier of a node to the output of the GET_TREE ipc command.
This is useful to be able to connect information from Sway IPC with information from standard Wayland protocols, for example for visual selection of windows with tools like `slurp`.
This PR fixes issue #8291.
=> sway/ipc-json: add foreign_toplevel_identifier to IPC_GET_TREE output

sway/sway-ipc.7.scd, sway/sway.5.scd
"view" is an internal term, while the commonly understood
user-facing term is "window"
Ref: #7323
=> docs: use "window" instead of "view" throughout.

include/sway/output.h, sway/commands/opacity.c, sway/desktop/output.c
```
Calling container_update() wasn't enough: If there is no visible window
decorations (title bar, borders) container_update would basically no-op
and the scene wouldn't repaint with the update alpha. By also calling
output_configure_scene() we force a call to
wlr_scene_buffer_set_opacity() thus ensuring we update the scene.
```
Closes: #8580
=> Fix opacity command not updating contents sometimes

sway/sway_text_node.c
sway_text_node was not respecting max_width during rendering, which could lead to very large cairo surfaces and failures during rendering.
Minimal reproduction: https://gitlab.freedesktop.org/emersion/wleird/-/merge_requests/36
=> sway_text_node: Fix issues with large dimensions

sway/commands/exec_always.c, sway/config/bar.c, sway/config/output.c, sway/main.c, sway/swaynag.c
cmd_exec_process is used whenever sway is meant to execute a child process on behalf of the user, and had a lot of complexity.
In order to avoid having to wait on the user's process, a double-fork was used, which in turn required us to wait on the outer process. In order to track the child PID for launcher purposes, a pipe was used to transmit the PID back to sway.
This resulted in sway blocking for 5-6 ms per exec on my system, which is quite significant. The error handling was also quite lacking - the read loop did not handle errors at all for example.
Instead, teach sway to handle SIGCHLD and do away with the double-fork. This in turn allows us to get rid of the pipe as we can record the child's PID directly. This reduces the time we block to just 1.5 ms on my system. We'd be able to …
=> Rework fork/exec strategy

sway/criteria.c
To use something like:
`[con_id=__focused__] mark --add --toggle foo`
The container must currently have a view. However, it is possible to focus parent containers that do not have a view. For example, via:
`focus parent`
Since containers without views can be the focused (meaning the container is marked `"focused": true` in the output of: `swaymsg -t get_tree`), it seems reasonable that a view is not required to target a container via `__focused__`.
My motivation for making this change is that I have the following in my sway config:
```
bindsym $mod+i \
exec \
'swaymsg -t get_tree                                                            \
| jq -r ".. | select(.focused?) | .marks[]"                                  \
| wmenu -f "'$font'" -p "Marks:" …
```
=> Remove constraint that con->view != NULL to use __focused__ criteria

sway.desktop
According to
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html, to set the value of XDG_CURRENT_DESKTOP, a DesktopNames key is required in the session file.  And the value of XDG_CURRENT_DESKTOP is used to run xdg-desktop-portal*. 
If this value is not set, xdg-desktop-portal-wlr will not run at login.
The value of XDG_CURRENT_DESKTOP is set by the login manager, but from my research, some of them are supported and some are not.
In sddm, I confirmed that it is supported.
=> Add the DesktopNames key to the sway.desktop session file

include/sway/server.h, sway/server.c
I kept the old wlr_data_control manager too because clients aren't done migrating yet due to [Kwin for instance](https://invent.kde.org/plasma/kwin/-/merge_requests/6606) not supporting ext-data-control yet.
Wine for example uses wlr-data-control, while mpv wants ext-data-control.
=> sway/server: create ext-data-control manager

include/sway/server.h, sway/commands/exec_always.c, sway/config/bar.c, sway/config/output.c, sway/main.c
The behavior of handlers registered with signal(3p) is not well-defined  for signals delivered more than once, as laid out in the man page.
We should replace our use of signal with sigaction, but for SIGCHLD specifically we can also just skip the signals altogether by setting the handler to SIG_IGN which causes child reaping to not be required.
Fixes: https://github.com/swaywm/sway/pull/8567
We should still replace our other `signal` calls with `sigaction`, but only SIGCHLD is expected to be seen by sway more than once, and why let us get interrupted by sporadic signals if we can help it? Resetting the handler in 3 places before exec isn't too bad.
=> Use SIG_IGN for SIGCHLD instead of our own handler

sway/desktop/transaction.c
As of Sway 1.10, output positions no longer seem to be correctly applied when repositioning outputs in global fullscreen. For example, if I run a program in global fullscreen in a dual-monitor setup and then want to mirror the monitors by setting both monitor positions to 0 0 (using "swaymsg output ... pos 0 0"on both monitors, not using the sway config file!), I get a blank picture on one of the monitors. In Sway 1.9, the screens are mirrored as expected.
I had a look at the code and found the line
wlr_scene_output_set_position(output->scene_output, output->lx, output->ly);
in arrange_root in sway/desktop/transaction.c. At the moment, it looks like wlr_scene_output_set_position is only called when global fullscreen is not enabled. I modified the code so that wlr_scene_output_set_position …
=> Fix output repositioning in global fullscreen

sway/commands/scratchpad.c
=> sway/commands: Return error if container is not in scratchpad and criteria are specified

sway/desktop/output.c
When the repaint timer fires, we check if the sway_output is disabled, and if so, skip the output commit after having reset frame_pending.
The sway_output enable flag is only updated if the output is disabled and removed from the layout, not if the power is disabled for e.g. idle. This can lead to situations where a commit is attempted on a disabled output, which will lead to an attempted and failed primary swapchain allocation.
Use the wlr_output.enabled state to check if the output is active.
=> desktop/output: Skip repaint if wlr_output is disabled

sway/commands/bind.c, sway/commands/gesture.c, swaybar/ipc.c
`has_prefix()` signature is `bool has_prefix(const char *str, const char *prefix)`. The prefix is expected to be given 2nd, not first.
This breaks in places where order was swapped around when moving from `strncmp` to `has_prefix` (added in 0c60d1581f7b12ae472c786b7dfe27a1c6ec9a47)
My following config was broken:
```
bindcode --no-repeat --input-device=$logitech_g604 {
191 focus output right
192 focus output left
193 move workspace to left, focus output right, focus output left
194 exec pamixer --toggle-mute, $volume_notification -i "$([ $(pamixer --get-mute) == "true" ] && echo "audio-volume-muted-symbolic" || echo "audio-volume-high-symbolic")"
195 move workspace to right, focus output right, focus output left
196 exec pamixer --increase 5, $volume_notification -i …
```
=> stringop: fix has_prefix() arg order in config parsing

sway/desktop/transaction.c, sway/tree/arrange.c
If far too many containers are created, they can become so small that their size calculations come out negative, leading to crashes on asserts.
Instead, set a lower bound for sizes and disable the container entirely if it goes below it, giving whatever space it used to the last container.
The splits are not recalculated, so currently the effect is that if all containers have the same width fraction, they keep getting narrower until at some point they all round to zero and the last container will be given all the available space.
A better behavior would have been if the additional container did not contribute to size and fraction calculations at all, but it's an extreme edge-case, anything is better than crashing, and this is easier to implement.
=> Avoid crashing on too many containers

sway/sway.5.scd
Replace the XWayland-only class attribute in the examples:
- The first example given should work for Wayland-native windows.
- The example 'Kill all windows with the title "Emacs"' should use title, not class. Also, it's a substring (regex) match.
There are many different implementations of regular expressions with incompatible syntax. For example, GNU grep alone provides three different ones. Clarify the use of PCRE2 by sway criteria.
=> man: clarify criteria (incl. PCRE2 usage)

sway/desktop/transaction.c
Commit c2d6aff added a bounds check on `height - title_bar_height`, repurposing the local variable `height` in an attempt to DRY out the expression.
In https://github.com/swaywm/sway/issues/8625#issuecomment-2748546723, @lbatalha noted that the variable gets re-assigned inside the loop body, so its result would leak across loop iterations. This effect compounds and causes the artifact reported in issue #8625, where each child except the first in a tabbed container would acquire a visible waterline.
This PR introduced a second variable and reset it in each loop iteration to get rid of the waterline.
Open Sway and create three tabbed children in the root container.  
Check for visible waterlines in child windows (except the first child):
Notably, I couldn’t reproduce the effect in stacking …
=> Fix regression that added visible waterline

sway/desktop/idle_inhibit_v1.c, sway/lock.c, sway/tree/view.c
We were not correctly handling idle inhibitor visibility in case of session locks, nor in case of unmapped surfaces.
This tries to fix both. Not yet tested.
=> idle_inhibit: Session lock and unmapped surface fixes

include/sway/desktop/idle_inhibit_v1.h, include/sway/input/input-manager.h, include/sway/input/text_input.h, include/sway/server.h, include/sway/tree/container.h, sway/desktop/idle_inhibit_v1.c, sway/input/input-manager.c, sway/input/text_input.c, sway/server.c, sway/tree/container.c
This PR fixes sway crashing on exit due to event listeners not being removed from wlroots objects on exit.
Listeners fixed:
- server: all objects created during `server_init()`, reworked `handle_renderer_lost()` to use an idle callback 
- input/input-manager: `wlr_backend.new_input`, `wlr_virtual_keyboard`, `wlr_virtual_pointer`, `wlr_keyboard_shortcuts_inhibit`, `wlr_transient_seat_manager`
- desktop/idle-inhibit: `wlr_idle_inhibit_manager`
- input/text-input: `wlr_text_input_manager` and `wlr_input_method_manager`
- tree/container:  `wlr_scene_buffer.output_enter` and `wlr_scene_buffer.output_leave`
If I haven't missed any, this fixes removing listeners at exit for all wlroots objects with listeners that sway uses. Other wlroots objects not touched in this PR already have some form of …
=> Fix crashes on exit caused by wlroots listener checks

sway/server.c
When running with X11 backend, DRM is not used, so deinitialization on fini should be skipped.
With this, after https://github.com/swaywm/sway/pull/8578 sway has no more crashes on shutdown.
=> server: fix shutdown crash when running on x11 backend

sway/desktop/transaction.c
Related to https://github.com/swaywm/sway/pull/8606
One of the calls to `arrange_container` was left outside the if block
=> Remove duplicate call to arrange_container

sway/desktop/layer_shell.c
According to the spec, the closed event should be sent when the surface is no longer shown, because the output may have been destroyed or the user may have asked for it to be removed. In such cases, the clients should destroy the resource.
This fixes mako not being able to show notifications if the assigned output was destroyed while a notificataion was still visible
=> layer_shell: destroy layer_surface on assigned output destruction

include/sway/server.h, sway/main.c, sway/server.c
In [1] we re-introduced a debug flag to enable wl_drm. Time has passed and Xwayland + VA-API + amdvlk now all support linux-dmabuf-v1.
[1]: https://github.com/swaywm/sway/pull/7916
=> Drop wl_drm again

sway/main.c, swaybar/main.c, swaynag/main.c
The man page for signal(3) reads:
> new applications should use sigaction() rather than signal()
=> Replace signal() with sigaction()

sway/commands/resize.c
problem: an invalid usage of the command `resize set` will cause sway to crash because it doesn't check for an invalid height.
solution:
1. validate height along with width
2. collect all the resize returns into a var in order to log potential errors before returning, so the user has more context as to why the resize config did not work.
fixes #8619
=> sway/commands: Handle incorrect resize unit

sway/config.c
The function `load_include_configs` already changes the directory to the one containing the parent config. Therefore, `load_include_config` trying to assemble the "full" path leads to repetition of path segments, making the `realpath` call fail with ENOENT.
Just calling `realpath` on the path itself from the directory with the parent configuration is sufficient, so there is no point in passing `parent_dir` to `load_include_config`.
When running sway with a relative path to confiig, like `sway -c tmp/sway-configs/root`, if that config includes other file with `include other`, the file that gets included is in fact `tmp/sway-configs/tmp/sway-configs/other` relative to where sway was ran from. (Without such directory structure the include fails.)
---
(oops, I forgor to write this part in the …
=> Fix includes with relative paths

sway/config/output.c
We oftne use -1 to indicate unset values. In case of output (x, y), we would consider the fields set if they are not both -1. This means that (0, -1) and (-1, 0) are valid coordinates, but (-1, -1) is not.
We support negative output positioning, so we cannot use -1 to mean unset. Zero is also not an option as that would disallow reverting a set position back to (0, 0).
INT_MAX is an unreasonable output position, so use it to indicate unset values, and only use the value when both are set.
=> config/output: Use INT_MAX as x/y unset value

sway/config/output.c
color_transform and allow_tearing was not handled by supersede_output_config which could lead to configuration being incorrectly applied.
=> config/output: Fix missing output config supersedes

sway/commands/move.c
Before this commit, when moving a non-leaf child of a tabbed or stacking container to a new workspace, the child would be detached from the parent container and the grandchildren would be sent to the new workspace but the child itself wouldn't be destroyed causing the titlebar to still be rendered as part of the parent container. Fixes #8648.
=> move: fix broken titlebar when moving child to new workspace

sway/desktop/transaction.c
When a container that was previously an inactive child of a tabbed or stacking layout becomes floating, it's border scene tree remains disabled. This results in only the titlebar being rendered for the container. This commit ensures the border scene tree is enabled when arranging floating containers.
Fixes #8721
=> transaction: ensure border scene is enabled for floating containers

sway/tree/root.c
When a scratchpad container is shown, it may appear underneath other floating containers, making it difficult for users to access it. This can lead to a frustrating user experience, as the scratchpad container is intended to be easily accessible.
=> Raise scratchpad container in floating

sway/desktop/transaction.c
Currently we do a good job of reparenting the scenes of a container when it moves into a disabled workspace. We need to do this since normally the scenes are reparented in the 'arrange_{children,container}' functions but these don't get called for disabled workspaces. However, the 'arrange_{children,container}' functions also don't get called when there is a fullscreen container hiding them.
This commit makes sure to call 'disable_workspace' on workspaces with a fullscreen container so that when a container is moved into the workspace its scenes will be properly reparented. Also, when there is a fullscreen global container 'disable_workspace' is called for all workspaces since the scenes of a previously fullscreen global container may still be parented in the 'fullscreen_global' layer. …
=> transaction: reparent scenes of containers behind fullscreen containers

sway/desktop/layer_shell.c
wlroots resets 'initialized' when a layer surface is unmapped and sway doesn't rearrange the layer surfaces in response to a commit of a surface where 'initialized' is false. This results in space not getting reclaimed from a recently unmapped layer surface until some other action causes 'arrange_layers' to get called. This commit makes sure all layer surfaces get rearranged when a layer surface is unmapped.
=> layer-shell: reclaim space from unmapped layer surfaces

include/sway/tree/workspace.h, sway/desktop/output.c, sway/tree/output.c, sway/tree/workspace.c
When an output is destroyed, we go through the process of disabling it. This includes evacuating all content away from the output, which can lead to various modifications to the scene. With the scene_output still present, this can lead to things like output_enter events being emitted for the output currently being destroyed.
Ensure that the scene output is destroyed first and that the output is immediately considered disabled.
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3974
=> output: Minimize interaction with output after destroy

config.in
I assisted someone in getting their tap to click working.
The default example left them confused as it did not seem to work.
The issue was, that the device name in the example did not work for their laptop.
Instead of using a device name, i suggest to use the input type in the example.
This should work on most devices.
=> Improve example of input section in default config

include/sway/server.h, sway/server.c
The socket path allocated with strdup() in server_init() was not being freed in server_fini().
Remove const qualifier and add proper cleanup.
=> server: fix socket path memory leak

sway/input/text_input.c
Unfocused windows shouldn't be allowed to activate the IM.
This fixes an issue with swaymsg invocations that contain several
commands which result in multiple swift focus changes. An application
briefly gets text input focus, sends an enable request, then sway
processes it and activates the IM only after the commands are all
finished and focus is on something else which did not send an enable
request.
The second commit also prevents unfocused applications from changing content_type/surrounding_text/text_change_cause.
=> text_input: Ignore enable requests from unfocused windows

meson.build
This can be surprising (e.g. in CI, this can download source code instead of using system libraries) and users can easily turn it back on if desired.
=> build: set wrap_mode=nodownload in default options

sway/main.c
A temporary SUID detection that would cause sway to exit was introduced when SUID operation was deprecated, intended to avoid cases where a user would not heed the deprecation notice, continued to use SUID and ended up with sway accidentally running as root.
Remove the check, as the three years that have passed is sufficient time for users to discover the deprecation and adapt. We did not care if users intentionally want to run sway as root through SUID, we only wanted to avoid surprise root.
=> Remove the temporary SUID warning

include/sway/desktop/transaction.h, include/sway/output.h, include/sway/tree/container.h, include/sway/tree/node.h, include/sway/tree/view.h, include/sway/tree/workspace.h, sway/commands/move.c, sway/desktop/launcher.c, sway/desktop/output.c, sway/desktop/transaction.c, sway/desktop/xdg_shell.c, sway/desktop/xwayland.c, sway/tree/container.c, sway/tree/output.c, sway/tree/view.c, sway/tree/workspace.c
A sway_node may end up being referenced in either a queued transaction, pending transaction or as a dirty node. To manage this, the transaction system has been responsible for destroying containers, workspaces and outputs at the end of their last referenced transaction.
This significantly complicates the teardown flow of surfaces and outputs. Instead, remove the node from transactions and dirty lists so that the callsite can remove and free the node immediately.
=> sway/tree: Simplify sway_node teardown

include/sway/layers.h, include/sway/output.h, sway/desktop/layer_shell.c, sway/tree/output.c
In general wl_signal isn't well-suited for Sway: Sway doesn't need any modularity, and signals make it trickier to track down exactly what happens down the stack.
Replace Sway's output disable signal with a simple list tracking for the only user.
=> Drop sway_output.events.disable

sway/ipc-json.c, swaymsg/main.c
A new "features" object is added to the output description. We'll add more entries in the future, e.g. HDR.
=> ipc-json, swaymsg: indicate when adaptive sync is unsupported

sway/tree/view.c
Visble flicker can occur during transactions, if these are not copied to the 'saved' scene
=> tree/view: save new wlr_scene_buffer fields

sway/tree/container.c, sway/tree/node.c, sway/tree/output.c, sway/tree/workspace.c
Node destruction currently runs through the transaction system such that a particular node is only destroyed after its use in an ongoing transaction. If a node is dirtied after the node is marked as destroying but before it is destroyed, the pointer added to dirty_nodes would become a dangling pointer once the node was destroyed.
Do not dirty destroying nodes, and ensure that destroying is only set after the last dirty.
=> tree/node: Do not mark destroying nodes as dirty

sway/input/seatop_default.c
This small patch fixes an issue with how `hide_cursor` feature interacts with keyboard control and `wl_pointer.{enter,leave}` Wayland events. It seems to fix #6245.
When the cursor is hidden over a container which regains focus without mouse warping (for example with keyboard bindings for `focus` and `workspace` commands when `mouse_warping` is set to `output`), the Wayland event `wl_pointer.enter` is sent despite the cursor remaining hidden (and it is not reverted with `wl_pointer.leave`). This is noticeable and somewhat bothersome in particular when using a web browser primarily with a keyboard — when the browser regains focus and a web site is scrolled with a keyboard, some hyperlinks become unexpectedly underlined (sometimes causing popups to appear, as on Wikipedia) because of the …
=> Fix an issue with `hide_cursor` and container focus

sway/commands/layout.c
Applying layout changes to the parent of the parent, in case the parent only has a single child, stops the creation of a chain of single child containers. 
fixes #7945
=> reduces redundant containers

sway/commands/resize.c, sway/sway.5.scd
Fixes a compatibility issue with i3 where resizing works as described
hereafter:
> Direction can either be one of up, down, left or right. Or you can be
> less specific and use width or height, in which case i3 will take/give
> space from all the other containers.
Sway previously considered only the direct neighbours not all siblings.
Fixes #5936
=> commands/resize: make resize consider all siblings

sway/desktop/xdg_shell.c
Previously it was reporting `window_menu` and `maximize` instead of `fullscreen` because `wlr_xdg_toplevel_set_wm_capabilities` expects a bitmask (`WLR_XDG_TOPLEVEL_WM_CAPABILITIES_*`), and `XDG_TOPLEVEL_WM_CAPABILITIES_*` are supposed to be used as values in `wl_array`, so the values are different:
`XDG_TOPLEVEL_WM_CAPABILITIES_FULLSCREEN = 3`
`WLR_XDG_TOPLEVEL_WM_CAPABILITIES_FULLSCREEN = 4`
(cherry picked from commit c5456be7506adece2cdf922ed6d919db597944ab)
=> xdg-shell: fix reported WM capabilities (backport)

sway/input/text_input.c
These are now NULL.
Fixes: aaab7f961e0b ("input/text_input: chase wlroots update")  
Closes: https://github.com/swaywm/sway/issues/8864  
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/5107
=> input/text_input: stop using listener data

sway/tree/root.c
Fixes: https://github.com/swaywm/sway/issues/8909
=> commands/scratchpad: don't hide scratchpad if no pending workspace
