swaywm/sway

sway/commands.c, sway/commands.h, sway/config.c, sway/config.h, sway/layout.h, sway/list.h, sway/log.c, sway/log.h, sway/main.c
This should make allow for config file reloads and will suppress exec but not exec_always commands on reloads.
=> Added in reload and exec_always handling.

sway/commands.c
lets try this again.
frees cmd if necessary, and removed pointless copying when exec is one word.
=> fixed small memory leak. v2

sway/container.c
unless you want it to return something, then void return type could be changed.
=> fixed 'return NULL' in 'void container_map(...)'

sway/layout.c
=> fixed focus

sway/commands.c, sway/container.c
when focus is on workspace, and there is more then 1 child, splitting will now split properly.
it now acts as if the container is created around workspace, without actually doing so.
```
┏━┯━┓
┃ │ ┃
┗━┷━┛
with vertical split (+ new view) becomes. before it just changes workspace layout.
┏━┯━┓
┠─┴─┨
┗━━━┛
```
although the effects of this cant be seen yet as focusing still needs to be fixed. (i did test it with a buggy focus fix, but im not pushing that)
what we are currently using to set the focus `focus_view` doesnt support focus in the middle of the layout tree, so when workspace has children, focus cant be on workspace.
oh and i also moved the `if(parent->focused==child)parent->focused=NULL);` into the `free_swayc` function.
=> fixed split

sway/container.c, sway/handlers.c, sway/layout.c, sway/workspace.c, sway/workspace.h
This fixes how pointer test and workspace switching work to fix most of the multi output issues present in sway.
=> Multi output fixes

sway/workspace.c
Also renamed var parent to ws_output for clarity.
=> Fixed output focusing on workspace switch

sway/commands.c, sway/handlers.c, sway/handlers.h
`handle_pointer_motion`,  `handle_pointer_button`, `handle_view_created` now check if currently focused window is fullscreen before trying to change focus.
just one more change and it should be fine.
=> fixed fullscreen & focusing

sway/config.c
Forgot to change some lines when adding in the i3 stuff, this fixes it.
=> Minor fix to config loading

include/layout.h, include/log.h, sway/handlers.c, sway/layout.c
handles fullscreen state requests from views.
also added format attribute to logs, though it could be removed if the warnings are annoying.
other state request handling will need to be added later.
=> handle_view_state_request

sway/handlers.c
#50 
whoops. doesnt interact properly with hidden views.
=> focus changes when mouse moves over border instead of any mouse movement

include/container.h, include/layout.h, sway/container.c, sway/handlers.c, sway/layout.c, sway/workspace.c
views created were hogging the focus preventing focus from working properly.
#50
=> send_to_back/bring_to_front set when view changes visibility.

include/config.h, include/container.h, sway/commands.c, sway/config.c, sway/container.c, sway/layout.c
This is a fairly rough implementation of the gaps from the infamous i3-gaps fork.
I read on reddit that you guys already have plans for a gaps implementation, so I don't mind if you don't merge this, but gaps were the only thing that I was missing (except for an i3bar equivalent), and I figure there might be others like me.
=> Add support for gaps option

sway/handlers.c
=> reset floating view on floating_mod repress

sway/commands.c
The proper containers will now be toggled between.
=> Fixed mode_toggle

include/container.h, include/input_state.h, include/ipc.h, include/layout.h, sway/commands.c, sway/handlers.c, sway/input_state.c, sway/layout.c, sway/log.c, sway/type
I've implemented the resize command using the resize function and recursive resizing function that were described in the issue. I've done testing with fairly complex layouts, and it seems to function identically to i3, but further testing will definitely be good.
=> Added in basic resizing command.

include/handlers.h, include/layout.h, include/resize.h, sway/commands.c, sway/handlers.c, sway/layout.c, sway/resize.c
No real changes with this, just refactored all the resizing handlers into a new file resize.c.
=> Refactored resizing functions into resize.c

sway/handlers.c
handle_key does not get the keysym from wlc anymore
=> fixed keyboard handling

CMake/FindJsonC.cmake, CMakeLists.txt, sway/container.c, sway/ipc.c
version as far as possible without working on the versioning code
=> added json-c lib and implemented IPC get_version

CMakeLists.txt, sway/ipc.c, sway/main.c
Version info is now more like i3, just missing the release version.
=> Added in better versioning info

sway/container.c, sway/handlers.c, sway/input_state.c
also made it so view swapping mode (mod + lclick) wont start if theres nothing to swap
=> move workspace from dead output to other output

sway/container.c
and here are the bug fixes from that commit, this time without macros.
=> properly remove children in loops

sway/config.c, sway/handlers.c
a cleanup of `get_config_path` no more temp config nonsense.
guna do a bit more cleanup of config related things later.
=> config_path cleanup

include/commands.h, include/list.h, sway.5.txt, sway/commands.c, sway/config.c, sway/list.c, sway/stringop.c
fixed a few things with setting variables.
conflicting `set $variable` are handled properly, instead of just creating a new one, it updates the old one.
conflicts such as `set $mod, set $mode` are handled.
escaped $'s are handled properly.
variable replacement is changed. 
also added the `mode` entry for man page, might need to be rewritting since im no good at that.
a few more things need to be fixed.
=> variable changes.

sway/main.c
=> Revert "#187 cleanup zombies properly"

sway/commands.c, sway/main.c
heres a method similar to how i3 does it.
no sigchld handling at all.
=> #187, let init handle child processes

include/ipc.h, sway/main.c
Implement `--get-socketpath` switch.
=> main: Implement --get-socketpath switch.

include/config.h, sway.5.txt, sway/commands.c, sway/config.c, sway/handlers.c
A much simpler implementation of #198 .
=> Switch to adjacent output when hitting output edge.

sway/handlers.c
Minor bugfix. Seamless transitions works great now!
=> handlers: Fix swapped top/bottom for seamless transitions.

include/log.h, include/output.h, sway/commands.c, sway/focus.c, sway/handlers.c, sway/layout.c, sway/log.c, sway/output.c
patch 1) Refactoring.
patch 2) Add swayc_log which I found useful (better logging).
patch 3) Fix/refactor "move container to workspace number n".
I didn't bother splitting these into their own pull requests, but I can if you want (the commits are nicely separated already).
=> Misc stuff

include/ipc.h, sway/ipc.c, sway/workspace.c
It's a starting point; only does `workspace` events on focus change.
=> implemented IPC subscribe for workspace event

sway/layout.c
The old algorithm would only take one axis in consideration at a time (ie. x axis for left/right and y for up/down) causing it to choose the wrong output for e.g. a "grid layout" of outputs.
This patch simply reuses the algorithm in output.c which works fine.
=> layout: get_swayc_in_direction: Properly find adjacent outputs.

sway/ipc.c
ie. "/run/user/<user-id>" instead of "/tmp" (and fallback to /tmp).
=> ipc: Put socket into proper user runtime dir.

HACKING.md
Thought I'd add some general documentation. Please read to verify there's no mistakes :-p
Also, this could be placed in its own file if you don't want it straight in the readme.
=> README: Add long code overview section.

sway.5.txt, sway/commands.c, swaybg/main.c
Implemented "stretch", "fill", "center", "tile", and added a new mode "fit".
=> implement background scaling

sway/workspace.c
This function looks for bound commands that start with `workspace` (ie.
the commands that change to a static workspace) and fetches the
workspace name.
However, if it's actually a list of commands, then the parsing will pick
up the delimiter ("," or ";") and also fail to recognize keywords
("next" etc).
This patch fixes that by properly separating with delimiters.
=> workspace: Improve workspace_next_name.

sway/debug_log.c
Makes the log easier to read, and the developers more happy (this one at
least).
=> debug_log: Improve container_log so that debug lines are aligned.

include/config.h, sway/commands.c, sway/config.c
Some refactoring to prepare for correctly merging with existing output configuration.
=> refactor cmd_output

CMakeLists.txt, common/CMakeLists.txt, protocols/CMakeLists.txt, sway/CMakeLists.txt, swaybar/CMakeLists.txt, swaybg/CMakeLists.txt, swaygrab/CMakeLists.txt, swaymsg/CMakeLists.txt, wayland/CMakeLists.txt
This creates (static) libraries for protocols/, common/, and wayland/.
=> cmake: build common code only once

README.md
Add `gdk-pixbuf2` to list of dependencies in README.md
=> Add new dependency to README

README.md
Fixed path to sway in chmod (line 58)
=> Fix wrong path to sway executable

sway/config.c
Has been starring at me all day.
=> Use tabs instead of spaces

sway/commands.c
If the id is defined by another bar it will just use the default id for
the bar. Typically `bar-x`.
If the id command is used multiple times within a bar block, the last
one will 'win'.
=> Implement bar option: id <custom-id>

sway/commands.c
=> Implement bar option: hidden_state <hide|show>

sway/commands.c
=> Implement bar option: mode <dock|hide|invisible>

include/config.h, sway/commands.c, sway/config.c, sway/input_state.c
Fixes bug introduced in 22916e9 where dragging of floating windows was messed up.
=> Lookup dragging key when in dragging mode

include/config.h, sway/commands.c, sway/config.c
Now I not only read `CONTRIBUTING.md` but I actually followed it. It's much cleaner indeed.
=> Added bar_cmd_bindsym

sway/commands.c
=> Added bar_cmd_status_command

sway/config.c
=> Free bar->bindings

include/config.h, sway/commands.c, sway/config.c, sway/ipc-server.c
Make it possible to set the bar height.
=> Add bar height option (Airblader/i3)

wayland/buffers.c
This made backgrounds not work on my system
=> fix segfault when doesn't have a trailing '/'

sway/commands.c
This might conflict with #335 but I will just fix the PR you pull last, if needed.
=> Implement bar option: binding_mode_indicator <yes|no>

sway/config.c
No need to reimplement free_flat_list functionality.
=> Use free_flat_list for simple char* list.

swaygrab/main.c
With this it's possible to run `swaygrab` without a filename argument.
With no filename supplied it will use a default name based on the
current time.
The default file will get the extension `png` for screenshots and `webm`
for video capture.
=> swaygrab: add default output filename.

swaybar/main.c
Fix #346
Send SIGTERM to the `status_command` process before swaybar exits.
=> swaybar: terminate status_command process

sway/layout.c
If the output is not at the correct size then that info must be queried
from wlc. The output size is used by e.g. seamless mouse to detect
output edges.
With this patch the output size is now correct and the workspace size is
adjusted according to any panels.
Without this patch seamless mouse would fail to detect outputs
above/below each other if there was a panel in between because the
output would offically end where the panel started, not at the actual
screen edge.
=> layout: Keep output at the correct size, workspace can be smaller.

swaybar/main.c
using no position, position top, position bottom work. Left and right don't. Not sure if that is a sway/wlc issue or something
=> swaybar: use position from config

swaybar/main.c
Use of busyloop caused high cpu usage for sway because swaybar had to be
redrawn all the time. By using select instead the bar only has to be
redrawn when the status_command changes (i.e. every second) or when the
workspaces are updated.
Fix #345
=> swaybar: use select instead of busyloop

swaybar/main.c
I had to move the window_setup code around. I don't think it breaks anything...
=> swaybar: use height from config

swaybar/main.c
This should make the bar workspace button layout identical to the layout
used in i3.
Before:
after:
This obviously adds more mess to `swaybar/main.c` so it's perfectly fine if you want to wait until it has been refactored before this is added, I'll just rebase what is needed.
=> swaybar: pixel perfect layout

swaybar/main.c
Swaybar did not correctly handle the SIGTERM sent from sway when
exiting, ultimately leaving the child status_command behind.
This should correctly handle the SIGTERM signal and terminate the
status_command.
Fix #386
=> swaybar: Correct handling of SIGTERM.

sway/commands.c
Our initial implementation of `bar {  }` assumed that the commands could
only be used in the config. This is not true for two commands:
* bar mode
* bar hidden_state
This patch makes it possible to issue these commands outside a bar
block, for instance through swaymsg
$ swaymsg bar mode hide bar-0
This does not implement the `barconfig_update` IPC event which should be
trigged from these commands. I have added TODO's where this should be
added once implemented.
Reference: http://i3wm.org/docs/userguide.html#_i3bar_control
=> Handle bar commands outside config file

README.md
There have been more tracking issues created for various features, so it'd be nice to have these front and center.
If I forgot anything, let me know!
=> Add references to other feature support issues to README

swaybar/main.c
This should improve parsing of json data with linebreaks, e.g. conky output.
=> swaybar: read status line without fgets

sway/commands.c
Found this completely by accident
=> Dont try and fullscreen a workspace with no views

sway/commands.c, sway/sway.5.txt
Not sure if you will accept this, but i find it useful (I use it when
opening new terminal windows on a workspace
=> split toggle

swaybar/main.c
http://i3wm.org/docs/userguide.html#_strip_workspace_numbers
=> swaybar: Implement strip_workspace_numbers

sway/commands.c
This implements cmd_assign. Basically a copy and paste from
cmd_for_window however it has → handling and injects a `move container to
workspace`
=> cmd_assign

CMakeLists.txt, completions/zsh/CMakeLists.txt, completions/zsh/_sway, completions/zsh/_swaygrab, completions/zsh/_swaymsg
Hi, I've created at least a skeleton of zsh completion files for the sway, swaymsg, and swaygrab. Currently, it is only for --options but I will work on the other commands unless you say otherwise.
I'm sorry if it is a mess because it is my first time submitting a pull request to anything.
=> Basic Zsh auto-completion for --options

sway/main.c
Fixes https://github.com/SirCmpwn/sway/issues/458
=> Prevent ipc from crashing sway

completions/zsh/_swaygrab
I restructured it to include single dash so now it is a proper code completion for swaygrab. More to come for the others
=> restructured to include single dash options

sway/commands.c
Code should be pretty straightforward.
=> Some fixes in commands/assign

completions/zsh/_swaymsg
Just like the title says, I refactored the swaymsg to include the single dash options
=> refactored to include single dash options

completions/zsh/_sway
like the title says but I also added the files complete to config so it's easier to find a config file to test
=> refactored sway command to include single dash

sway/layout.c
This patch aims to correctly handle moving focus <left|right|up|down>
between outputs.
For instance, if moving from one output to a new output at the left of
the current one, it should focus the right-most view/container on the
new output, and the opposite if moving from right to left. This should
happen regardless of the previously stored focus of the new output.
This also handles moving to a new output above or below the current one.
=> Correctly move focus from one output to a new one.

include/config.h, sway/commands.c, sway/config.c, sway/container.c, sway/layout.c, sway/sway.5.txt
This adds support for `smart_gaps` from i3-gaps: https://github.com/Airblader/i3#smart-gaps
=> Implement 'smart_gaps' feature from i3-gaps

swaylock/CMakeLists.txt, swaylock/main.c, swaylock/swaylock.1.txt
Additionally
- Made background colors display when an image is enabled if
a --color is specified.
- Link CJson to swaylock.
- Add the --socket option to swaylock.
Sorry about having to make a new pull request.
=> Add choice of display to --image.

swaybar/bar.c
=> Stop swaybar crashing without args

sway/border.c, sway/layout.c
This fixes floating borders when moving outside of the output. Not sure what
happens with dual screen as I only have 1 monitor
=> Fix window borders

sway/commands.c
i3s way of setting border colors is really awkward, maybe we should choose a different approach with blocks, eg:
```
border {
focused {
border = #FFFFFFFF
background = #FFFFFFFF
...
}
unfocused {
...
}
}
```
=> Add border color commands

swaylock/main.c
I'm still not sure if it's the right way to do things but it should be way better than before.
=> Improve swaylock event flushing

sway/container.c, sway/debug_log.c, sway/focus.c, sway/handlers.c, sway/ipc-server.c
=> Use correct format string for x86_64 and i686

config
=> Use bindsym $mod+b splith in default config

common/stringop.c, sway/config.c
Each commit contains the reason why each change was made. 
Found using Valgrind :)
=> Cleaned up some un-free'd memory

README.md
I know I've reached bike-shed level here, and I promise my next PRs are going to be actual bug fixes :wink:
=> Remove empty params from url in README.md

sway/container.c
Reverts SirCmpwn/sway#650
Fixes #655
Will fix the problem #650 was attempting to solve some other way.
=> Revert "sway/container.c: fix segfault where view is assigned prematurely"

swaylock/main.c
also prevent screen redraws on modifier key presses
=> clear password buffer with ctrl-u in swaylock

include/output.h, sway/commands.c, sway/container.c, sway/output.c
This seems to have resolved issue #669 for me. Please give it a careful review, it's getting pretty heavy into C for my current comfort level and may have side effects I am not aware of.
=> Implement sort_workspaces() function for outputs.

sway/ipc-server.c
I've found this patch fixes the issue in #684, but I have no idea why.
=> fix swaybar problem in 08bef67

include/config.h, sway/commands.c, sway/config.c, sway/sway.5.txt
Included new option for configuration floating_minimum_size.
=> Floating size conf

sway/layout.c
takes place of https://github.com/SirCmpwn/sway/pull/687
=> redo smart_gaps/hide_edge_borders fix

sway/commands.c, sway/sway-bar.5.txt, sway/sway.5.txt, swaylock/main.c
You may want to convert to manpages and review the formatting before merging. Nested lists and tables in AsciiDoc are kinda complicated.
=> add documentation for client commands

swaylock/main.c
This should fix issue #647.
Also a couple minor, unrelated wording and comment changes.
=> make numpad enter key work in swaylock

sway/config.c
This should fix the issue #681
=> Fix segfault when using include with *

include/resize.h, sway/commands.c, sway/resize.c, sway/sway.5.txt
Just piggybacked on the existing `resize_tiled()` function here. `resize width 300px` sets width of container to 300px (if doing so is possible given constraints of layout).
=> implement resize command for absolute dimensions

include/focus.h, include/resize.h, sway/commands.c, sway/focus.c, sway/resize.c, sway/sway.5.txt
I think this ticks all the boxes on #713 except supporting up/down/left/right for `resize`. Please review - it's a pretty big PR and I'm not sure I tied up all the loose ends.
=> Set size command

include/client/window.h, include/extensions.h, sway/extensions.c, sway/handlers.c, swaybar/bar.c, swaybg/main.c, wayland/window.c
=> Make swaybar and swaybg shell surfaces, take 2

sway/ipc-json.c
- null pointer check against container names
- use actual JSON null values instead of "null" strings
- add "visible" boolean property to all containers
- remove "nodes", "floating_nodes" and "unmanaged_nodes" arrays from views as they cannot have children
=> get_tree json fixes

README.md
=> readme: add nixos package

include/ipc-json.h, include/ipc-server.h, sway/commands.c, sway/extensions.c, sway/focus.c, sway/handlers.c, sway/ipc-json.c, sway/ipc-server.c, sway/layout.c
Some points for discussion are mentioned in the comments.
=> [RFC] Implement window events

sway/handlers.c
please review but I think this should be relatively safe (cpu usage-wise)
=> third try for #678

sway/handlers.c
This requires https://github.com/Cloudef/wlc/pull/177 get merged, but once that is done will allow us to get pids for both Wayland and X views.
=> update handler to get pid from wlc for all views - now ok to merge

common/CMakeLists.txt, common/util.c, include/bar/config.h, include/config.h, include/util.h, sway/commands.c, sway/sway.5.txt, swaybar/config.c, swaybar/status_line.c, swaybg/main.c
`output * bg #rrggbb solid_color` is the syntax, but it wouldn't hurt my feelings if that changed.
=> implement solid color rendering for swaybg

sway/commands.c
This should take care of #761.
=> cache floating container size when fullscreening

swaymsg/CMakeLists.txt, swaymsg/main.c
=> swaymsg: pretty print ipc response

sway/ipc-json.c
This is for compatability with i3.
=> Use uintptr_t for ipc container id

sway/input_state.c
=> Arrange windows after swapping containers

sway/layout.c
=> Sort workspaces when moving workspace to output

sway/commands.c
Fixes #819. If workspace is focused and command 'move container to
workspace/output' is issued, workspace child containers are wrapped in a
new container and moved according to command.
=> Fix container move when workspace is focused

sway/sway.1.txt
see https://github.com/Cloudef/wlc/blob/09146b68163978aa0a49c2d271c9f891e1538d42/src/compositor/seat/seat.c#L311-L315
=> document all xkb settings handled by wlc

sway/border.c, sway/commands.c, sway/sway.5.txt
I implemented the indicator color as discussed in the IRC channel tonight.
I'm not sure what the testing guidelines are. I tested on my machine and it (seems) to work.
=> Implement indicator color

config, sway/sway-input.5.txt
Also improve sway-input(5) description to be more consistent with sway-bar(5).
=> Add input example section to config

sway/config.c
Fixes: https://github.com/SirCmpwn/sway/issues/865
=> Avoid dereferencing null configuration

sway/layout.c
=> Move views between outputs

wayland/pango.c
I think this should take care of #887
=> fix pango markup on swaybar

swaybar/ipc.c
=> Put workspace name in quotes (swaybar ipc)

sway/focus.c
=> fix pointer format string in sway_log() call

sway/ipc-json.c
consolidate the `nodes` and `floating_nodes` json arrays as mentioned in #890
=> consolidate nodes json

swaylock/main.c
See also https://github.com/i3/i3lock/pull/89
=> Explicitly set cairo font to avoid wonky fallback

include/sway/container.h, sway/container.c, sway/handlers.c
=> add click on title_bar to focus a container

sway/handlers.c
- Check null pointer for swayc_parent_by_type
- Split line to follow coding style
=> fix for click on title_bar

sway/container.c
=> also check floating cons in container_find

sway/container.c
=> Revert "also check floating cons in container_find"

include/sway/container.h, sway/commands/layout.c, sway/commands/move.c, sway/commands/split.c, sway/container.c, sway/handlers.c, sway/layout.c
=> Revert "Fixes dealing with workspace_layout and related bugs [rfc]"

sway/config.c, swaybar/config.c
For compatability with a change in i3.
=> config: set pango_markup default to false

common/ipc-client.c, common/list.c, common/log.c, common/readline.c, include/log.h, sway/border.c, sway/commands.c, sway/commands/assign.c, sway/commands/bar.c, sway/commands/bar/bindsym.c, sway/commands/bar/colors.c, sway/commands/bind.c, sway/commands/exec_always.c, sway/commands/for_window.c, sway/commands/mode.c, sway/commands/output.c, sway/commands/permit.c, sway/commands/set.c, sway/commands/workspace.c, sway/config.c, sway/container.c, sway/extensions.c, sway/handlers.c, sway/input.c, sway/ipc-json.c, sway/ipc-server.c, sway/main.c, sway/security.c, sway/workspace.c, swaybar/ipc.c
Still to do in future PRs around error handling:
=> Handle allocation failures

sway/ipc-json.c
=> Fix workspace layouts in json data

CMakeLists.txt, sway/main.c
Setting it is oftentimes problematic.
=> Unset LD_LIBRARY_PATH, unless specified

include/sway/container.h, sway/border.c, sway/container.c, sway/criteria.c, sway/ipc-json.c
At the very least, get_tree output and instance criteria work and are tested.
Whether or not to include the second commit is to your discretion.
=> Add window instance support

sway/handlers.c
Made possible by Cloudef/wlc#234.
Epiphany window size is still wrong though (might be a gtk issue).
=> Respect xdg-positioner offset, anchor edges and gravity

swaylock/swaylock.1.txt
=> Improve swaylock man

CMakeLists.txt
=> Ignore Wimplicit-fallthrough

include/sway/commands.h, sway/commands.c, sway/commands/default_border.c, sway/commands/default_floating_border.c, sway/commands/new_float.c, sway/commands/new_window.c, sway/sway.5.txt
as discussed in https://github.com/i3/i3/issues/2702
=> deprecate new_window and new_float commands

roadmap.html
As of 8d191b2 Marks should be fully implemented
=> Update roadmap with Marks as implimented

sway/config.c
Also remove a useless `sway_log` and replace it with a pipe
=> Prevent sway from duplicating on a failed fork

sway/commands/scratchpad.c
See https://github.com/i3/i3/blob/master/src/scratchpad.c#L196-L197
=> Use i3's dimensions for initial scratchpad views

sway/config.c
=> explicitly ignore unused return value

include/sway/commands.h, include/sway/config.h, include/sway/criteria.h, sway/commands.c, sway/commands/no_focus.c, sway/config.c, sway/criteria.c, sway/handlers.c, sway/sway.5.txt
=> Implement no_focus

sway/commands/bind.c, sway/handlers.c
Adds support for bindings like:
bindsym button3 floating toggle
bindsym $mod+button3 floating toggle
=> Add mouse button bindings

common/util.c, sway/main.c
=> Terminate when both suid bit and filecaps are set

swaygrab/main.c, swaygrab/swaygrab.1.txt
=> FFmpeg options for swaygrab

swaybar/tray/dbus.c
=> Prevent crash if DBus connection is NULL

README.ja.md, README.md
片言日本語はすみません。がんばりました。助言してください！
I would like to start translating documentation into various languages. I'm starting with Japanese, but I encourage anyone with skill in another language to submit similar patches. I will also take a whack at translating the man pages and will install them so they can be viewed with `man -Lja`.
=> Translate README to Japanese / READMEを日本語訳す

README.de.md, README.md
This translation takes into account the edit made to the Running section in #1317.
=> Translate README to German

sway/ipc-server.c
=> Raise max ipc message size limit to 256 MB

sway/main.c
This is a pull request meant to help with people experiencing the problems detailed in #143 by detecting if sway is being run on a Raspberry Pi and if the vc4 module is loaded. If the module isn't loaded, it's safe to assume the Pi isn't in the correct video mode, and the error message contains instructions to boot with the correct video mode.
=> Detecting Raspberry PIs and advising to use correct video mode

README.de.md
=> Update German README according to TL guideline update

README.fr.md
This translation takes into account the edit made to the **Running** section in #1317.
=> Translation README to French / Traduction du README en français

swaygrab/main.c
It's been a long time since I've done C but I'm fairly sure that this works.
Fixes #1245.
=> Convert a popen into a fork.

README.ja.md
Hello.
I read README.ja.md, but there was a grammar mistake in Japanese.
I wrote new translate for README.ja.md in Japanese.
=> Fix Japanese translate in README.ja.md #1337

sway/commands/set.c
The variable matching is now looping through all variables trying to find the longest possible match.
=> Fix issue #1287

swaymsg/swaymsg.1.txt
Added a hint where to find the commands.
Also indicate that command is itself not a command.
=> Interlink swaymsg to sway(5) and hint that command is interchargeable

sway/sway.5.txt
Changes 'orientation' to 'default_orientation' to match commands.c
=> Update man 5 page

sway/sway-bar.5.txt, sway/sway-input.5.txt, sway/sway-security.7.txt, sway/sway.1.txt, sway/sway.5.txt
Like last time, only more fixes and I completely rewrote the config file paragraph. 
Thanks for the good software :)
Also I'm unsure if you want to change "criteria" to "criterion" ([wictionary](https://en.wiktionary.org/wiki/criterion) for reference).
And there is [this paragraph](https://github.com/swaywm/sway/blob/master/sway/sway.5.txt#L386-L388) which I'm not sure of what it means.
=> Various manpage edits

sway/ipc-server.c, swaybar/status_line.c
=> Fix build on FreeBSD adjusting/removing _XOPEN_SOURCE declaration.

common/log.c
Makes reading debug logs much easier, debug lines will start with `D`,
info lines with `I` and error lines with `E`.
=> Print log level even if STDERR is not a tty

swaygrab/json.c
The default max nesting depth of json-c is 32, which can cause some valid trees to fail to be parsed. Instead of segfaulting, just abort and print the error returned by json-c.
Ideally this code would increase the nesting depth or manually recurse if the JSON was too deep, but this behavior is better than segfaulting.
=> swaygrab: Prevent segfault if IPC response can't be parsed.

swaygrab/json.c
- If IPC response contains `success: false`, abort and print error message.
- If tree has no nodes, abort with error msg instead of segfaulting.
=> swaygrab: Add some error handling.

sway/desktop/output.c
Makes it work with drm. Future work will involve getting the configured mode and setting that.
=> set mode on output

sway/main.c
So it logs the current SWAYSOCK.
=> log env after ipc init

include/sway/ipc-json.h, sway/ipc-json.c, sway/ipc-server.c
Just enough of `get_tree` to help us debug.
=> basic get_tree

include/sway/server.h, include/sway/view.h, sway/desktop/xwayland.c, sway/meson.build, sway/server.c
Basic xwayland shell with the same features as the others.
=> xwayland shell

swaylock/main.c
This commit makes swaylock poll the registry the first time in its
fork in order for sway to recognize it and grant it lock privileges
=> Fix `swaylock -f`

include/swaybar/bar.h, include/swaybar/tray/dbus.h, include/swaybar/tray/sni.h, swaybar/bar.c, swaybar/tray/dbus.c, swaybar/tray/icon.c, swaybar/tray/sni.c, swaybar/tray/sni_watcher.c, swaybar/tray/tray.c
See #1372
Menus for canonical (libappindicator) programs do not yet work, this will be added in a future PR as it is out of scope for #1431
=> Support libappindicator

sway/main.c, sway/server.c
See #1390 and swaywm/wlroots#546
=> Consolidate WLR and Sway logging

meson.build, swaymsg/main.c
Array lengths are size_t now, but otherwise everything works fine.
=> update json-c dep to 0.13

sway/commands.c, sway/commands/input.c, sway/config.c, sway/main.c
Some typos but it's mostly leak fixing, was waiting for bindings to land to push
=> config cleanup & implement free_config

sway/input/keyboard.c, sway/input/seat.c
Update for [wlroots 553](https://github.com/swaywm/wlroots/pull/553).
=> update for new wlr-keyboard modifiers

include/swaybar/event_loop.h, include/swaybar/status_line.h, swaybar/bar.c, swaybar/event_loop.c, swaybar/status_line.c
The event loop API was redesigned to avoid race conditions as well.
Fixes #1583
=> Handle swaybar status line errors

sway/ipc-json.c
Indicate the focused container in the ipc tree with the "focused" member.
=> ipc show focused container

include/sway/ipc-server.h, sway/ipc-server.c, sway/tree/container.c
Should give a `window::new` event when you open a new window.
=> Ipc new window

sway/ipc-json.c, swaymsg/main.c
Test plan: `swaymsg -t get_outputs`
=> ipc: add output modes

sway/desktop/output.c
Breaking wlroots change: https://github.com/swaywm/wlroots/pull/722
=> Update rendering code for wlroots matrix redesign

include/sway/server.h, sway/desktop/output.c, sway/server.c, sway/tree/container.c
Breaking changes in wlr_xdg_shell_v6 and wlr_renderer have been
made upstream.
=> Update wlroots API

protocols/meson.build
fixes build for xdg-positioner wlroots pr.
=> add xdg-shell protocol header

include/sway/server.h, sway/desktop/output.c, sway/desktop/xwayland.c, sway/server.c
* Don't create a GLES2 renderer
* Use backend renderer when rendering output
* Unify initial xwayland view mapping with map handler
=> Misc minor fixes

include/sway/tree/view.h, sway/desktop/xwayland.c
See https://github.com/swaywm/wlroots/pull/779
=> Use the new map/unmap events for xwayland views

include/sway/output.h, include/sway/server.h, include/sway/tree/view.h, sway/desktop/layer_shell.c, sway/desktop/output.c, sway/desktop/wl_shell.c, sway/desktop/xdg_shell_v6.c, sway/desktop/xwayland.c, sway/tree/container.c, sway/tree/output.c, sway/tree/view.c
This skips the renderer if nothing has changed, and renders
everything otherwise.
=> Add lite damage tracking

sway/desktop/output.c, sway/desktop/xwayland.c, sway/input/cursor.c
* Fix configure not sent when width/height are zero
* Fix unmanaged views rendering on every output
* Fix configure send in output-local coords in set_size
Fixes #1673
=> Fix various xwayland issues

include/sway/output.h, include/sway/tree/container.h, include/sway/tree/layout.h, include/sway/tree/view.h, sway/desktop/output.c, sway/desktop/wl_shell.c, sway/desktop/xdg_shell_v6.c, sway/desktop/xwayland.c, sway/input/cursor.c, sway/tree/layout.c, sway/tree/output.c, sway/tree/view.c
Test plan: test various shells, test xwayland unmanaged views.
=> Views redesign

include/sway/input/seat.h, sway/desktop/layer_shell.c, sway/input/cursor.c, sway/input/seat.c
Test plan: same as this guy https://github.com/swaywm/wlroots/pull/804
=> Give keyboard input to layer surfaces that ask for it

swaybg/main.c
Seems to work fine on Sway's side
=> swaybg: add HiDPI support

sway/tree/container.c
Implement window and workspace events for things that are implemented right now.
=> ipc window and workspace events

include/sway/commands.h, include/sway/tree/container.h, sway/commands.c, sway/commands/opacity.c, sway/desktop/output.c, sway/meson.build, sway/sway.5.txt, sway/tree/container.c
Test: `swaymsg transparency 0.25`.
fixes #1558
=> Implement opacity command

include/sway/tree/view.h, sway/desktop/output.c, sway/desktop/wl_shell.c, sway/desktop/xdg_shell_v6.c, sway/desktop/xwayland.c, sway/input/seat.c, sway/tree/container.c
See https://github.com/swaywm/wlroots/pull/824
=> Update for wlroots#824

sway/ipc-json.c
add "type" to ipc json containers.
=> Ipc container type

client/pool-buffer.c, include/pool-buffer.h, include/swaybar/bar.h, sway/tree/container.c, swaybar/bar.c, swaybar/ipc.c, swaybar/render.c
Test plan:
* swaybar
* output removal
* handle
=> Handle output removal on swaybar

include/sway/tree/view.h, sway/tree/view.c
=> Fix wl_output enter/leave events

include/sway/tree/view.h, sway/desktop/xdg_shell_v6.c, sway/desktop/xwayland.c, sway/tree/view.c
Test plan: check subsurfaces + popups HiDPI support
=> Send surface enter/leave events to view children

include/sway/tree/container.h, include/sway/tree/layout.h, sway/commands/layout.c, sway/commands/move.c, sway/commands/resize.c, sway/desktop/desktop.c, sway/desktop/output.c, sway/input/seat.c, sway/ipc-json.c, sway/tree/container.c, sway/tree/layout.c, sway/tree/view.c, sway/tree/workspace.c
=> Revert "Break everything^W^WUse wlr_box for sway_container"

include/sway/desktop.h, include/sway/output.h, include/sway/tree/view.h, sway/commands/opacity.c, sway/desktop/desktop.c, sway/desktop/layer_shell.c, sway/desktop/output.c, sway/desktop/wl_shell.c, sway/desktop/xdg_shell_v6.c, sway/desktop/xwayland.c, sway/tree/view.c
The last part is still missing: rendering only damaged regions
=> Fine-grained damage tracking

include/sway/input/seat.h, sway/desktop/xwayland.c, sway/input/input-manager.c, sway/input/seat.c
=> Give keyboard focus to unmanaged xwayland surfaces

sway/server.c
See https://github.com/swaywm/wlroots/pull/850
=> Update for wlroots#850

swaybar/render.c
=> Fix swaybar HiDPI rounding issue

sway/commands/move.c
Related tests: https://github.com/swaywm/sway-tests/pull/6
=> Add workspace_auto_back_and_forth for move cmd

swaybar/bar.c
Swaybar would crash on launch if it wasn't configured to run on all outputs. This PR fixes that and makes swaybar respect its output config.
What was previously happening was all outputs from the wl_registry were being added to `bar->outputs` regardless of whether the bar actually used them, and ipc_get_workspaces() would iterate these and run strcmp() on `output->name`. For the unused outputs, `output->name` was null which caused swaybar to segfault.
My PR makes it ignore the outputs given by the wl_registry if the bar doesn't use them, noting that we have to keep track of the output index to make sure the `bar->config->outputs` maps correctly. That's the handle_global() part.
The second part of the PR cleans up the logic in bar_setup(). Because `bar->outputs` now contains only used …
=> Fix swaybar output config

sway/sway.5.txt
Signed-off-by: Quentin Bourgeois <quentin@bourgeois.eu>
=> <sway/man: In sway(5) treat scale as keyword for output command>

sway/tree/container.c
Update for https://github.com/swaywm/wlroots/pull/860
=> Fix pointer input for xdg-popups

swaybar/status_line.c
=> Set _POSIX_C_SOURCE properly

sway/input/seat.c
Until now, focus changing code only considered cleaning up the last focused
workspace. This commit adds removal of empty workspace from output that just
received focus on a different workspace.
Fixes: #1797
=> remove empty workspace when focusing its output

swaybar/i3bar.c
Code from @NilsBrause
Ref #1820
=> Fix memory leak on swaybar

swaybar/bar.c
Fixes #1807 
Uses 'visible' instead of 'focused', since we may scroll on a bar which
isn't the focused output.
We can't use "next_on_output" or "prev_on_output" to implement this,
because it only modify the focused output. So scrolling on an unfocused
output will affect the incorrect one.
We just use the "workspace name" command instead.
Test (requires multiple outputs):
- Set `focus_follows_mouse no` in sway config
- Focus a window on output A
- Scroll on the swaybar on output B
Notice no crash and the workspace change is on output B.
=> Fix swaybar axis event logic

sway/tree/view.c
Update for https://github.com/swaywm/wlroots/pull/885
=> Update for wlroots#885

sway/desktop/xwayland.c, sway/input/seat.c
Also do not let tiled xwayland views do what they want.
Fixes #1841
=>  Fix segfault when switching back to workspace with osu! 

include/sway/commands.h, include/sway/config.h, sway/commands.c, sway/commands/input/map_from_region.c, sway/commands/input/map_to_output.c, sway/config/input.c, sway/input/cursor.c, sway/input/input-manager.c, sway/input/seat.c, sway/meson.build, sway/sway-input.5.txt
This allows to map from a region of tablet tool.
=> Add map_from_region command

sway/desktop/xdg_shell_v6.c, sway/desktop/xwayland.c
Fixes a segfault when running Highway Blossoms.
=> Don't call view_set_fullscreen on unmapped xwayland views

sway/input/cursor.c
=> Update for wlroots#923

sway/tree/container.c
Use minimum of the container width or text width.
Also creates a `scale` variable in this function for convenience.
Tested with scaling.
=> Fix title texture width

meson.build, meson_options.txt, security.d/00-defaults.in, sway/commands/exec_always.c, swaybar/meson.build, swaybg/meson.build
=> Install swaybar and swaybg under /usr/lib/sway

protocols/wlr-layer-shell-unstable-v1.xml
Otherwise it's not possible to pass a NULL output.
=> Update layer-shell protocol

sway/server.c
The relevant PR in wlroots: https://github.com/swaywm/wlroots/pull/959
Left the behavior in sway (non lazy start) the same.
=> Update xwayland start for new API

include/sway/server.h, include/sway/tree/view.h, protocols/meson.build, sway/desktop/xdg_shell.c, sway/meson.build, sway/server.c, sway/tree/container.c, sway/tree/view.c
Not having `default` cases in `switch` statements definitely helped.
=> Add xdg-shell stable support

swayidle/main.c
=> swayidle: terminate when server died

include/sway/tree/container.h, sway/commands/layout.c, sway/desktop/output.c, sway/tree/arrange.c, sway/tree/container.c, sway/tree/view.c
You know the drill. It's mostly a copy/paste from tabbed.
At some point (probably after floating) I will try to combine some of the rendering parts to minimise the amount of duplicate/similar code.
=> Implement stacked layout

sway/ipc-server.c
Test:
- Mark some views
- Run `swaymsg -t get_marks`
- Verify all marks are listed
=> Implement IPC_GET_MARKS

sway/server.c
=> Update for swaywm/wlroots#993

sway/server.c
=> Update for swaywm/wlroots#1000

include/sway/criteria.h, include/sway/tree/view.h, sway/criteria.c, sway/sway.5.scd, sway/tree/view.c
=> Add shell criteria token

client/pool-buffer.c, include/pool-buffer.h
- Set CLOEXEC, just in case
- `munmap` in destroy_buffer
=> Pool buffer fixes

include/sway/tree/container.h, sway/commands/swap.c, sway/input/seat.c, sway/tree/container.c, sway/tree/layout.c
=> Fix ancestor typos

sway/desktop/output.c
Also don't accumulate empty damage.
Test plan: try setting and unsetting a view fullscreen.
=> Only send frame done to visible views

sway/desktop/output.c
Setting it to "rerender" will always re-render everything
regardless of the damaged region. Setting it to "highlight" will
clear the screen and render only damaged regions.
=> Add SWAY_DAMAGE_DEBUG

sway/desktop/output.c
This code mirrors `render_output`.
=> Only send frame to visible surfaces when fullscreened

include/sway/input/seat.h, include/sway/tree/layout.h, sway/desktop/output.c, sway/input/cursor.c, sway/input/seat.c, sway/tree/layout.c
=> Render drag icons

sway/desktop/output.c
=> Update for swaywm/wlroots#1060

sway/commands/output/background.c
I'm here again with background command stuff.
I've fixed a memleak, a double free error and made some refactoring.
=> output bg command: fix memleak and refactoring

sway/input/keyboard.c
=> fix handling key modifiers if not pressed at first

include/sway/tree/view.h, sway/desktop/output.c, sway/desktop/xdg_shell.c, sway/desktop/xdg_shell_v6.c, sway/desktop/xwayland.c, sway/tree/container.c, sway/tree/view.c
As agreed on IRC.
Doesn't work or do anything yet, I'm hoping someone can throw some hints as to why not.
=> Revert "Don't unmaximize floating views"

common/unicode.c, common/util.c, sway/commands.c, sway/commands/assign.c, sway/commands/bar/font.c, sway/commands/bar/modifier.c, sway/commands/input/accel_profile.c, sway/commands/input/click_method.c, sway/commands/input/drag_lock.c, sway/commands/input/dwt.c, sway/commands/input/events.c, sway/commands/input/left_handed.c, sway/commands/input/map_from_region.c, sway/commands/input/middle_emulation.c, sway/commands/input/natural_scroll.c, sway/commands/input/pointer_accel.c, sway/commands/input/repeat_delay.c, sway/commands/input/repeat_rate.c, sway/commands/input/scroll_method.c, sway/commands/input/tap.c, sway/commands/output/background.c, sway/commands/output/mode.c, sway/commands/output/position.c, sway/config.c, sway/config/bar.c, sway/desktop/transaction.c, sway/ipc-server.c, sway/main.c, sway/tree/workspace.c, swaylock/main.c
Like swaywm/wlroots#1101, a bunch of trivial fixes; most are stuff not done properly on error (meh) but there are a couple of real leaks/small fixes.
I didn't do this as thoroughly as wlroots but it's a start
=> Static analysis fixes

sway/desktop/xdg_shell.c, sway/desktop/xdg_shell_v6.c, sway/desktop/xwayland.c
=> Fix damage on swaybar when view requests to exit fullscreen

sway/tree/view.c
=> Call view_set_tiled for mapping non-floating views

include/swaylock/swaylock.h, swaylock/main.c, swaylock/swaylock.1.scd
=> swaylock: daemonize after locking

sway/commands.c, sway/commands/floating_minmax_size.c, sway/meson.build, sway/tree/view.c
Relevant i3 docs: https://i3wm.org/docs/userguide.html#_constraining_floating_window_size
=> Implement floating_minimum_size and floating_maximum_size

sway/tree/view.c
=> Update for swaywm/wlroots#1116

sway/desktop/xdg_shell.c, sway/desktop/xdg_shell_v6.c
Test plan: open right-click menus in Gedit, make sure they don't show up outside the current output.
=> Add xdg-positioner support

sway/commands/resize.c
Implements the following for floating views:
* `resize set <width> <height>`
* `resize <grow|shrink> <width|height|up|down|left|right> <amount>`
=> Implement resize command for floating views

sway/server.c
https://github.com/emersion/grim/commit/8480e3ebdb752e8b0b65096cc312af664e50de45
=> Remove orbital screenshooter

sway/commands/bar/position.c, sway/config.c, sway/config/output.c
Hopefully I've got my thinking correct.
=> Fix some memory leaks

swayidle/main.c
No idea why wlr_output_layout was involved here.
=> swayidle: cleanup

swaylock/main.c
I messed up the handling of arguments in `swaylock` with 7b91712416953c25f2722fedb57b474504460a48. The issue is that I only gave `C:` to `getopt_long` when getting searching for the config path. This caused the `getopt_long` to output that every other flag was invalid. Since the swaylock itself was never aborting, the arguments should still be working (aside from `-i, --image` -- see below).
I decided to alter `parse_options` to only handling options when a valid pointer is given. This makes it so the option string does not have to be updated in two places. However, it does make function longer. I think in the long run, this is still the better option.
As for `-i, --image`, only the first image for an output was used. This means if you have `image` in the config and `-i, --image` as an …
=> Fix swaylock arguments

include/sway/input/seat.h, sway/desktop/xwayland.c, sway/input/seat.c
This fixes syncplay menus.
~~… and breaks dmenu.~~
=> Handle xwayland override_redirect flag change

sway/tree/view.c
Eg. `assign [class="Firefox"] output foo`
=> Implement assign to output

sway/desktop/transaction.c, sway/server.c
=> Update for swaywm/wlroots#1148

sway/tree/container.c
=> Fix pointer events for overlapping floating views

sway/tree/workspace.c
This PR resolves an open TODO in `src/tree/workspace.c`, so that in cases like
bindcode $mod+49 workspace 0
bindcode $mod+10 workspace 1
the first workspace name is correctly identified.
=> Also extract first workspace name from bindcodes

include/sway/input/input-manager.h, sway/input/input-manager.c
Ref #2373 
To test use [virtboard](https://source.puri.sm/Librem5/virtboard)
cc @dcz-purism
=> Add virtual keyboard protocol

include/util.h
`parse_boolean()` takes and returns a `bool`
=> util.h: add missing include

completions/bash/sway, completions/bash/swayidle, completions/bash/swaylock, completions/bash/swaymsg, meson.build, meson_options.txt
Similar to the existing shell completion for zsh, this adds support for completion in bash
=> bash completion

sway/desktop/output.c
=> Fix segfault with fullscreen

sway/desktop/transaction.c
This fixes two issues which were both introduced in #2396.
First issue:
The PR changes the location of the buffer save to `transaction_apply`, but puts it inside the `should_configure` block. For unmapping (destroying) views, `should_configure` returns false so it wasn't saving the buffer. If a frame was rendered between the unmap and the transaction applying then it would result in a crash.
Second issue:
If a destroying view is involved in two transactions, we must not release the buffer between the transactions because there is no live buffer to grab any more.
To test, create layout `H[view, V[view, view]]` then kill the vertical split container.
=> Fix race condition crashes when unmapping views

include/sway/output.h, include/sway/tree/container.h, include/sway/tree/view.h, sway/desktop/output.c, sway/desktop/render.c, sway/desktop/xdg_shell.c, sway/desktop/xdg_shell_v6.c, sway/input/cursor.c, sway/tree/container.c, sway/tree/view.c
The first commit reverts the revert. The second commit fixes the issue.
=> Fix popups v3

include/sway/decoration.h, include/sway/server.h, include/sway/tree/view.h, sway/decoration.c, sway/desktop/xdg_shell.c, sway/desktop/xdg_shell_v6.c, sway/meson.build, sway/server.c
=> Enable borders on floating SSD xdg-shell views

sway/desktop/xwayland.c
=> xwayland: fix unmanaged surfaces order

sway/tree/container.c
=> Fix container_has_ancestor crash

sway/tree/workspace.c
Instead of relying on bindings being configured, primarily source
new workspace names from workspace-output assignments.
Fixes #2435
=> Use assigned workspace name for output

include/sway/commands.h, include/sway/criteria.h, sway/commands.c, sway/commands/assign.c, sway/commands/exec_always.c, sway/commands/focus.c, sway/commands/move.c, sway/commands/nop.c, sway/commands/rename.c, sway/commands/set.c, sway/commands/sticky.c, sway/commands/workspace.c, sway/meson.build, sway/sway.5.scd, sway/tree/view.c, sway/tree/workspace.c
Ref #2336 
Don't think I will do `popup_during_fullscreen`, ~`force_display_urgency_hint`~ or `force_on_window_activation` in this PR since it's mainly just fixing things
=> More commands

sway/desktop/output.c
=> Fix popup position when parent uses geometry

sway/tree/container.c
=> Fix sending fullscreen event to view

sway/tree/arrange.c
When a workspace is moved to another output, or the output it's on changes its global layout position, the floating containers on that workspace should be translated by the same amount as the workspace. This keeps the floating containers in the same position relative to the workspace.
A check is done to make sure the floating container's center point isn't being moved off screen (eg. when moving the workspace to a smaller output). If it is, it is centered within the workspace.
Fixes part of #2500.
=> Translate floating containers when a workspace is moved

completions/zsh/_swaylock
This should be fixed, but there are also a bunch of completions that are missing and could be added, so I don't know whether to do so now or closer to 1.0 release in case there are more changes.
=> [WIP?] Fix zsh completions

include/sway/tree/arrange.h, include/sway/tree/container.h, include/sway/tree/workspace.h, sway/tree/arrange.c, sway/tree/container.c, sway/tree/layout.c, sway/tree/workspace.c
In preparation for using type safety.
=> Make separate gaps functions per container type

completions/fish/sway.fish, completions/fish/swaylock.fish, completions/fish/swaymsg.fish, meson.build, meson_options.txt
This is my first ever pull request and I am very excited. 
Everything compiled successfuly.
=> Add fish completion

sway/input/seat.c
Main changes:
1. Check if container is the child of a floating container to bring to the front
2. Check if container is NULL early, allowing some later checks to be removed. Though I'm wondering whether in this case, it makes sense to destroy the last workspace, so maybe that block can be removed? (or even whether popups should be closed?)
3. Removed `new_output_last_ws` because I'm not sure if it's doing anything. If it is, can someone provide an example?
Other than that, I just moved a few things around to makes things a bit cleaner, hopefully.
=> seat.c: clean-up seat_set_focus_warp function

sway/tree/container.c
=> Allow subsurfaces which overflow the container to be interacted with

sway/commands/move.c
When moving a container to an inactive workspace on a different output, this will change the focus on the destination output back to its last active workspace.
Also includes a few code cleanups.
~Edit: need to add a check that `new_output_last_ws != destination_ws`~
=> Fix moving container to inactive workspace on different output

sway/desktop/transaction.c
When there's multiple transactions in the queue, sway can take a shortcut by checking if they all operate on the same set of containers. If they do, it can skip all but the last transaction. The way we tested for transactions which used the same containers was to exclusive-or their con IDs together, but this has proved not only to be ineffective but also has the potential to make sway crash.
This patch replaces the exclusive-or with a loop and container comparison.
This has a good chance of fixing #2527, but I've not been able to reproduce it in a nested session and can't do DRM testing right now. @ianyfan Can you please test? Otherwise I'll do DRM testing later.
=> Don't use bitfield to test for similar transactions

sway/input/seat.c
=> Fix crash when running deferred commands

sway/server.c
=> Update for swaywm/wlroots#1216

common/ipc-client.c, sway/ipc-server.c
silences releated warnings from the undefined behavior sanitizer.
=> fix misaligned integer stores/loads

include/sway/criteria.h, meson_options.txt, sway/criteria.c
There were errors building with "enable-xwayland" set to "false" which were introduced by #2550.
This commit places those changes within "#ifdef HAVE_XWAYLAND" checks.
=> Fix window_type with disabled xwayland support

swaybar/render.c
=> Fix swaybar block background fill logic

sway/commands/client.c
Since the `client.{focused,focused_inactive,unfocused,urgent}` commands change colors, the textures need to be updated otherwise the textures and the rest of the title bar may utilize different colors.
=> Update textures for cmd_client_* commands

swaybar/i3bar.c
Ref https://github.com/swaywm/sway/pull/2622#issuecomment-421467458
=> bar: remove i3bar_block_free in favour of i3bar_block_unref

sway/ipc-json.c, sway/tree/node.c
=> ipc: add focus information to root node

include/sway/tree/view.h, sway/ipc-json.c, sway/tree/view.c
=> ipc: add pid information for views in layout tree

sway/desktop/render.c
=> Fix segfault in output_render

swaybar/i3bar.c
Fixes #2664 @cnt0 @Ogromny please check
This issue occurs when there is still input to be read, which did not arise when I was testing it before.
=> swaybar: fix parsing errors when json is sent in parts

include/sway/config.h, sway/config/bar.c, sway/main.c, sway/tree/output.c, swaybar/bar.c, swaybar/render.c
Don't kill and respawn swaybars on hotplug.
=> swaybar: handle hotplugging

sway/desktop/transaction.c
=> Reconfigure xwayland views when repositioned

sway/input/seat.c
It seems like advertising that we support touch when we don't, while using SSD, makes GtkMenuBar misbehave. Please don't ask me why...
Fixes #2299.
=> Fix GtkMenuBar always opening first item

sway/config/input.c
=> input config: merge left_handed option

sway/desktop/transaction.c
Fixes memory leaks.
Not sure about function names, whether to check for NULL, and commit message lol
=> Free transaction state upon destruction by removing pointer indirection

include/swaybar/bar.h, include/swaybar/i3bar.h, include/swaybar/ipc.h, include/swaybar/status_line.h, sway/commands/bar/binding_mode_indicator.c, swaybar/bar.c, swaybar/i3bar.c, swaybar/ipc.c, swaybar/main.c, swaybar/render.c, swaybar/status_line.c
The only real fix is setting the binding mode indicator, the others are mostly aesthetic changes.
=> swaybar: small fixes and clean-ups

include/swaybar/bar.h, include/swaybar/render.h, swaybar/bar.c, swaybar/render.c
=> swaybar: synchronize rendering to output frames

sway/input/seat.c
To reproduce the problem, create layout `H[view V[view view view-focused]]`, then switch to another workspace and have the previously focused view in the vsplit close (eg. using criteria, or an mpv video finishing). Return to the workspace using `$mod+<num>` and the entire vsplit would be focused. This happens because `handle_seat_node_destroy` would only set a new focus if the currently focused view or a parent was being destroyed. To fix it, it needs to set a sibling of the destroying container to `focus_inactive` regardless of the current focus, then restore current focus if needed.
This patch changes the function accordingly. Additionally:
* The function now makes an early return if the node being destroyed is a workspace.
* `set_focus` has been renamed to `needs_new_focus`. This …
=> Set focus_inactive on a sibling when a container closes in an inactive workspace

include/swaybar/status_line.h, swaybar/i3bar.c
=> swaybar: add leading comma to click event JSON

sway/input/seat.c
Progress towards resolving #2754.
=> Add sanity check for empty focus stack

include/sway/commands.h, include/sway/config.h, include/sway/input/cursor.h, sway/commands.c, sway/commands/raise_floating.c, sway/config.c, sway/input/cursor.c, sway/input/seat.c, sway/meson.build, sway/sway.5.scd, sway/tree/container.c
Adds a configuration option to raise/not raise floating containers on gaining focus (see also https://github.com/i3/i3/issues/2990).
=> raise floating

sway/commands/bar/status_command.c, sway/commands/swaybg_command.c, sway/config.c, sway/config/output.c, sway/sway.5.scd
Same as #2791 but for swaybg.
Fixes #2790
=> Allow swaybg to be disabled

include/sway/commands.h, include/sway/config.h, include/sway/tree/container.h, include/sway/tree/view.h, sway/commands.c, sway/commands/popup_during_fullscreen.c, sway/config.c, sway/desktop/output.c, sway/desktop/render.c, sway/desktop/xdg_shell.c, sway/desktop/xdg_shell_v6.c, sway/desktop/xwayland.c, sway/input/cursor.c, sway/input/seat.c, sway/meson.build, sway/sway.5.scd, sway/tree/container.c, sway/tree/view.c
i3 docs: https://i3wm.org/docs/userguide.html#_popups_during_fullscreen_mode
~~Note that this currently doesn't work for xwayland. Xwayland popups are unmanaged, and for some reason they don't have the `NET_WM_WINDOW_TYPE_POPUP` atom when mapping, so I can't identify them from other unmanaged surfaces.~~
=> Implement popup_during_fullscreen

sway/config.c
=> config: remove double free of config->swaynag_command

sway/tree/workspace.c
=> Only consider tiling views for gaps outer

sway/input/input-manager.c
add send_events support
I found that in master branch I can't disable keyboard anymore. this pr will add support of setting sent_events mode for keyboards.
=> add libinput config for keyboard

swaybar/input.c
Added missing #include for swaybar/input.c.
=> missing headers for swaybar/input.c

sway/main.c
The idea here is we don't want users to be blissfully unaware that they are running unsupported drivers. So we abort on startup, and force the user to add a specific argument to bypass the check.
Closes #2894.
=> Abort if proprietary drivers are in use

contrib/inactive-windows-transparency.py
I was thinking whether it's worth putting into sway docs or here, and [I was advised](https://github.com/swaywm/sway/issues/2787#issuecomment-431524704) to create a contrib dir instead, which I'm doing here.
=> A script to make inactive windows transparent

swaybar/bar.c, swaybar/render.c
Fixes https://github.com/swaywm/sway/issues/2892
=>  swaybar: render with minimum height, nominally text height

swaybar/bar.c
swaybar doesn't handle hotplug correctly. On hotplug, a `wl_surface` is created and nothing else happens. This patch fixes this.
To test:
1. Run sway with the Wayland backend
2. `swaymsg create_output`
3. The bar should appear on the newly created virtual output
=> swaybar: fix hotplug

README.bg.md, README.de.md, README.el.md, README.fr.md, README.it.md, README.ja.md, README.md, README.pt.md, README.ru.md, README.uk.md
sway depends on git for version information
=> advertize dependency on git

swaybar/bar.c
=> Fix swaybar crash when there's no status_command

include/sway/commands.h, sway/commands.c, sway/commands/bar/bindsym.c, sway/commands/bar/hidden_state.c, sway/commands/bar/mode.c, sway/commands/bind.c, sway/commands/exec_always.c, sway/commands/fullscreen.c, sway/commands/layout.c, sway/commands/opacity.c
First commit is a required fix, the rest are more subjective aesthetic changes, so you may disagree with them.
=> commands: clean up checkargs function +other small changes

include/swaylock/seat.h, include/swaylock/swaylock.h, swaylock/main.c, swaylock/seat.c
=> Add multiseat support to swaylock

sway/input/cursor.c
For example, create layout `H[view T[view view view]]`, focus the view in the hsplit and scroll the mouse wheel over the tab title bars. Prior to this patch, focus would be given to a descendant of the tabbed container. This patch keeps the focus on the hsplit view.
This also renames some of the variables used in this part of the code to make it be easier to follow.
Tested with regular view children, as well as split container children, and tested while focus is on the tabbed container as well as off the tabbed container.
=> When scrolling on a tab titlebar, set focus_inactive if not focused

README.pt.md
Signed-off-by: Matheus Horstmann <mch15@inf.ufpr.br>
Update README.pt to include notice
Signed-off-by: Matheus Horstmann <mch15@inf.ufpr.br>
Update README.pt to include notice
Signed-off-by: Matheus Horstmann <mch15@inf.ufpr.br>
=> [pt_BR] Update README.pt to include notice

swaymsg/main.c
=> swaymsg: fix get_outputs status code

sway/desktop/render.c, sway/tree/view.c
As discussed in issue #3002 
Fixes #3002
=> Restore previous tabbed layout behavior

sway/main.c
=> Make it clear that being able to restore root is a failure

swayidle/main.c
=> Revert "Work around swayidle never triggering on SIGUSR1"

sway/desktop/output.c
Required after https://github.com/swaywm/wlroots/pull/1261
=> Use wlr_surface_get_effective_damage

sway/config.c
This commit removes an unnecessary line from config.c.
=> Remove extra line. 

sway/commands/bar/binding_mode_indicator.c, sway/commands/bar/pango_markup.c, sway/commands/bar/workspace_buttons.c, sway/commands/bar/wrap_scroll.c, sway/commands/floating.c, sway/commands/input/xkb_capslock.c, sway/commands/input/xkb_numlock.c, sway/commands/seat/fallback.c, sway/commands/smart_gaps.c, sway/commands/sticky.c, sway/commands/ws_auto_back_and_forth.c
Whilst working on #3083, I noticed some opportunities to refactor the commands arg parsing.
=> Use parse_boolean where possible.

sway/commands.c
**Since this heavily alters the way the config commands are processed, this needs to be heavily tested before merging**
Currently, variables cannot contain commands and cannot span more than one argument. This is due to variable replacement happening after determining the handler and after splitting the config line into arguments.
This changes the process to:
1. Check for empty lines and block boundaries
2. Split the arguments as before
3. Verify that the first argument is not a variable. If needed the following occurs
a. Perform variable replacement on just the first argument
b. Join the arguments back together then split the arguments again. _(This is needed when the variable contains the command and arguments for the command)_
4. Determine the handler
5. If the handler is cmd_set, …
=> Alter config variable replacement process

include/stringop.h, meson.build, sway/commands/create_output.c, sway/desktop/output.c
Also removes a weird `setenv` declaration and a unused function.
=> Use #if instead of #ifdef for WLR_HAS_*

sway/desktop/render.c
Update for https://github.com/swaywm/wlroots/pull/1366
=> Render software cursors with wlr_output_render_software_cursors

sway/decoration.c
=> Fix double free when unmapping any view

sway/commands/resize.c
=> resize set: convert ppt to px for floating containers

common/util.c, include/sway/commands.h, include/sway/config.h, include/swaybar/bar.h, include/swaybar/config.h, sway/commands/bar.c, sway/commands/bar/strip_workspace_name.c, sway/commands/bar/strip_workspace_numbers.c, sway/config/bar.c, sway/ipc-json.c, sway/meson.build, sway/sway-bar.5.scd, swaybar/bar.c, swaybar/config.c, swaybar/ipc.c, swaybar/render.c
#3082.
~~For some reason, the `strip_workspace_name` is deemed invalid in the config file. Still trying to find out why.~~
=> Implement strip_workspace_name.

swayidle/swayidle.1.scd
See https://github.com/swaywm/sway/pull/3160#issuecomment-440804037
=> fix typo in swayidle(1)

sway/ipc-server.c
It's set even if a child of the output is focused.
=> ipc: fix focused in get_outputs reply

sway/tree/view.c
The support for pango_markup was broken in title_format because the
formated title was escaped. I think only the payload should be escaped.
This commit fixes 789a877b379cd35c350610be62b971ae00feb542
The pango_markup looks like:
```
font pango:"DejaVu Sans Mono 10"
for_window [class=".*"] title_format "<span background='#ff0000'>%title</span>"
```
=> fixes pango_markup support with title_format

sway/server.c
=> Update for swaywm/wlroots#1387

sway/tree/output.c
Fixes #3156 
Since the output config is no longer applied before creating the default workspace, the layout for default workspaces on an output may not be correct. Due to the ordering of calls in output_enable being changed in several bug fix PRs, this just fixes the layout after the call to apply_output_config.
=> Fix default_orientation auto

sway/desktop/render.c
=> Update for swaywm/wlroots#1403

sway/config/output.c
Fixes #3221
When generating default output configs to reset the outputs to their default settings on reload, the output name was being used. Additionally when determining the output config to apply, if there was an output config with the output name, that was being used without checking for an identifier config. This caused sway to completely ignore any of the users specified output configs that used identifiers.
To fix this issue, the following changes have been made:
1. Default output configs are created for the identifier now instead of name. This actually makes more sense anyway since you could hotplug multiple different outputs to the same port.
2. In get_output_config, which is only used to determine which output config to apply, output configs for both the name and identifier are …
=> Fix identifier output configs on reload

include/swaybar/i3bar.h, include/swaybar/input.h, swaybar/i3bar.c, swaybar/input.c, swaybar/render.c
Compatibility with i3 commit 161db6f17d734ac9deb0a20e81b78d4b2a92ce68.
=> Add relative coordinates in JSON for i3bar click events

swaybar/render.c
When `block->urgent` is set, use the urgent colors. This matches i3bar's
behavior. Previously, swaybar just ignored the property.
This also adds in rendering for right borders, which was missing.
=> swaybar: handle block->urgent

sway/input/seat.c, sway/ipc-json.c
=> Update for swaywm/wlroots#1377

sway/commands/rename.c
Fixes #3309.
Please be sure to check my work thoroughly for backdoors (I'm from Australia).
=> Return success when renaming a workspace to itself

_layouts/master.html
Uses the swaywm’s GitHub account image as a favicon.
=> Add a favicon

sway/ipc-server.c
=> IPC_SUBSCRIBE ensure request object is an array

sway/sway.5.scd
Adds documentation in sway(5) for the tiling_drag command
=> sway(5): document tiling_drag

sway/tree/container.c
=> Set font options when computing text width.

completions/bash/swaybar, completions/zsh/_sway, completions/zsh/_swaybar, completions/zsh/_swayidle, completions/zsh/_swaylock, completions/zsh/_swaymsg
This PR adds zsh completions for swayidle and swaybar and updates the other completions using descriptions taken from the --help option of the various commands.
I'm very new to zsh completions so your feedback is welcome.
=> zsh: update completions

sway/input/cursor.c, sway/sway.5.scd
=> Apply tiling_drag_threshold to all containers

sway/sway-output.5.scd
Some more clarifications because it seems scale questions are recurring.
=> sway-output(5): Added additional info for scaling and position wrt. scale

sway/sway.5.scd
Also removes some trailing spaces from other lines in the file.
=> Fix urgency documentation

swayidle/main.c
Fixes #3377.
The sleep lock file descriptor was immediately closed after it was acquired due to the dbus message being freed. Now the fd is duplicated before the message is freed so the inhibitor stays active.
=> swayidle: Fix sleep inhibitor not being acquired

sway/server.c
See https://github.com/swaywm/wlroots/pull/1423
=> Add data-control-v1

sway/input/keyboard.c
Since the keyboard can be destroyed by executing a binding (reloading
with a different seat attachment config), update the repeat timer before
executing the binding.
=> keyboard: update repeat timer before execution

include/swaybar/tray/item.h, swaybar/main.c, swaybar/tray/host.c, swaybar/tray/item.c, swaybar/tray/tray.c
Fixes #3365 
This ostensibly works, but I'm going to leave it as WIP for now in case I notice anything wrong or anything I can do better.
=> swaybar: handle SNI signals better

sway/commands/move.c
=> Reset container dimensions when moving into workspace from direction

swaybar/render.c
Related to #3329 
This fixes the rendering of borders and backgrounds for blocks. This
also makes the following changes:
* both borders and padding are scaled with the output
* both lines and rectangles are rendered without an antialiasing to
avoid bleeding outside the desired area
Follow-up points for the completion of #3329:
* Make the vertical padding optional
* Make the edge margin optional
=> swaybar: fix rendering of border and background

sway/config.c
When the config has continued lines, `get_line_with_cont` may read more
than one line of the actual file. When displaying line numbers for error
messages, they should be the line number in the file to make it easy to
find and fix the issue.
=> config: fix line number with continued lines

config.in
For https://github.com/swaywm/swayidle/pull/7
=> config.in: update swayidle/swaylock example

sway/config/output.c, swaybg/main.c
=> swaybg fixes

swaybar/tray/item.c
Ignore pixmaps for icons where width or height is 0 and use the exact width and height to parse the image data of nonsquare icons.
Fixes #3487
---
Notes:
* Crash reproduced and fix verified with [unibrow](https://xyne.archlinux.ca/projects/unibrow/)
* This does not address the creation of visible windows for all xembed tray icons.
=> swaybar: fix crash with some tray icon pixmaps

include/sway/ipc-json.h, include/swaybar/status_line.h, sway/commands.c, sway/ipc-json.c, sway/ipc-server.c, swaybar/i3bar.c, swaybar/ipc.c, swaybar/status_line.c, swaymsg/main.c
Regressed by 4b1eaaf731b0e29497.
```
$ pkg info -x json-c
json-c-0.13.1
$ pkg-config json-c --cflags
-I/usr/local/include/json-c
```
```c
../swaymsg/main.c:12:10: fatal error: 'json-c/json.h' file not found
#include <json-c/json.h>
^~~~~~~~~~~~~~~
1 error generated.
```
=> Unbreak build on FreeBSD

include/sway/input/seat.h, sway/input/seat.c
=> Update for swaywm/wlroots#1402

sway/commands/output/background.c, sway/desktop/transaction.c, sway/input/seat.c
=> Use sway_log_errno instead of strerror

include/sway/input/cursor.h, sway/input/cursor.c
=> Update for swaywm/wlroots#1503

sway/config/bar.c, sway/config/output.c, sway/criteria.c, swaybar/config.c, swaybar/status_line.c
Please see https://github.com/swaywm/sway/pull/3121#issuecomment-459697467.
I am sincerely sorry for this. I should've had a better understanding of what I was doing and not relied on you guys to catch my errors.
=> Revert double frees.

sway/main.c
Fixes https://github.com/swaywm/sway/pull/3581#issuecomment-460681872.
=> Initialize server so input manager is available.

sway/config.c
=> Revert "Return false if config could not be loaded."

meson.build
Fixes https://github.com/swaywm/sway/issues/3656
=> Fix --version when building from tarball

sway/commands/move.c
on move container window to another workspace,
not remove from scratchpad.
I not sure, i3 for ex, no remove
=> Don't remove from scratchpad on move to workspace

swaybar/tray/item.c, swaybar/tray/watcher.c
=> tray: when a service is lost, remove all matching items

include/sway/tree/workspace.h, sway/commands/workspace.c, sway/tree/workspace.c
This creates the next workspace if you hit the end.
=> Add workspace {prev,next}_on_output --create

.builds/alpine.yml, .builds/archlinux.yml
Fixes https://github.com/swaywm/sway/issues/2681
=> ci: add Alpine build

.builds/freebsd.yml, sway/config/output.c
Obviously this currently fails because of `SOCK_CLOEXEC`.
=> ci: add FreeBSD

sway/commands/layout.c
=> layout cmd: always operate on parent container, like i3

README.md, README.pl.md
More compact variants of some expressions (e.g. "wyknać polecenie") might exist, but this should be an ok starting point.
=> Add Polish README

sway/main.c
I went through the Address Sanitizer Report from #3658 and fixed the missing IPC frees.
=> Fix small memory leaks reported in #3658

include/sway/input/seat.h, sway/input/cursor.c, sway/input/seat.c
=> Update for swaywm/wlroots#1517

sway/commands/output/transform.c
There are some changes to this code still being discussed in #3770 but this is the main thing I wanted to change.
=> Allow 0 degree transform (normal transform).

sway/config/output.c, sway/input/cursor.c
These are some smaller fixes for issues reported by running scan-build and reading the code.
=> Small fixes found by running scan-build and reading code

sway/sway.1.scd
Closes #1575
This just documents the few environment variables set by sway in
sway.1.scd
=> sway.1.scd: document environment vars set by sway

sway/server.c
This is necessary after https://github.com/swaywm/wlroots/pull/1596
=> Set DISPLAY after initializing Xwayland

sway/tree/container.c
Fixes https://github.com/swaywm/sway/issues/3825
=> Fix container_parent_layout for scratchpad windows

sway/desktop/output.c
Fixes #3537 
This adds an iterative call in `output_damage_whole_container` to
damage the subsurfaces for all visible views that are inside of the
container. This is needed to damage subsurfaces that extend outside the
box of the container. Without this, those subsurfaces will create
artifacts when moving or resizing.
=> output_damage_whole_container: damage subsurfaces 

sway/input/keyboard.c
Allows both BackSpace and Shift+BackSpace to be bound under the US keyboard layout, per #3705, by making raw keysyms take precedence over translated keysyms.
Strictly speaking, only the call to `get_active_binding` needed to be reordered. I made the other changes for aesthetic consistency.
I haven't been running with this patch for long, but it does fix the issue for me.
@emersion 
Fixes #3705
Fixes #3079
=> Allow both BackSpace and Shift+BackSpace to be bound

sway/ipc-json.c
Fixes #3870 
This fixes the decoration rects for floating containers on a workspace
that is either tabbed or stacked. Without this, the floater would
incorrectly try to calculate where it's tab or stack decorations were
on the workspace. This would cause a SIGFPE (due to a divide-by-zero)
when the floater was on a tabbed workspace without any tiling children.
Furthermore, the floater does not care what the workspace's layout is
and should just use the location relative to the workspace. This should
have no effect on children of a floating container.
=> get_deco_rect: fix floaters on tabbed/stacked ws

sway/commands/focus.c
This kind of worked before in that focus would change, but it wasn't intentionally supported and had side effects such as not raising the container, and being unable to cycle through all floaters depending on the direction used.
This commit makes it properly supported. The new focus is chosen based on the distance to the center point of each floating container in the workspace, and the container is raised.
In a multi output setup, if both visible workspaces have floating containers, focus will NOT cross into the other output. It is assumed the user will use a workspace binding in this case.
If two floating containers occupy the exact same center point and you try to focus in a direction, the behaviour is undefined.
Fixes #3859.
To test, float a few views, move them around a bit so none …
=> Support focus <direction> for floating containers

README.fr.md
Removed the image at the start of the readme.
Removed the mention of bounties.
Updated the dependencies.
Removed a few lines that were not present in the english readme anymore.
@abdelq Could you check this out? I dont know if you still provide support on the irc. If not, i'll remove that part. Do you have any other comments?
=> Updated the french readme

sway/commands/floating.c
Fixes https://github.com/swaywm/sway/issues/3972#issuecomment-476780165
=> Fix crash for floating command on scratchpad window

README.zh-CN.md
=> fix typo in zh-CN

swaybar/render.c
Matches i3bar behavior of setting all blocks to use the short_text if the full
text width does not fit.
=> Implement handling of short_text field of i3 input protocol.

meson.build, swaybg/swaybg.1.scd
Preparing `swabg` to become a standalone tool
=> swaybg: add manpage

sway/ipc-json.c, swaymsg/main.c
=> Send disabled output available modes on IPC get_outputs

sway/sway.5.scd
Closes https://github.com/swaywm/sway/issues/4032
=> Add documentation for rename workspace

sway/desktop/output.c, sway/desktop/render.c
See https://github.com/swaywm/wlroots/pull/1660
=> Update for wlroots#1660

include/swaybar/bar.h, include/swaybar/input.h, swaybar/bar.c, swaybar/input.c
Closes #2780
This just adds multiseat support to swaybar
=> swaybar: add multiseat support

README.de.md, README.es.md, README.fr.md, README.ja.md, README.md, README.pl.md, README.uk.md, README.zh-CN.md
Just occurred to me while reading through the readme, thought I could add it. May be a bit too much.
=> add links to i3 for first mention in README's

swaymsg/main.c
Fixes #4116 
This makes it so swaymsg still returns the correct successful or failed
error code when in quiet mode
=> swaymsg: fix quiet error reporting

include/sway/config.h, sway/config/bar.c
Follow-up to https://github.com/swaywm/sway/pull/4124#issuecomment-489297910
This just makes it so swaybar is handled as a wayland client
=> Spawn swaybar as a wayland client

sway/sway.5.scd
Infos about how to get criteria was nowhere to be found on the man page.
=> Add infos to help using for_window to man 5

config.in
Makes the first letter of all the comments uppercase. THus making the config file more consistient
=> Make comment casing consistient

sway/desktop/output.c
The output manager config was not properly updated when output
configuration was changed through some other means (such as a command).
=> Update output manager config on all output events

sway/server.c
~~Waiting for 1.1 to be released before merging this.~~
Fixes https://github.com/swaywm/sway/issues/4101
=> Remove orbital gamma-control protocol

sway/ipc-json.c
These can be useful to implement per-window layouts as a script.
See https://github.com/swaywm/sway/issues/2361
=> ipc: add xkb_layout_names and xkb_active_layout_index

include/sway/commands.h, sway/commands/input.c, sway/commands/input/xkb_switch_layout.c, sway/meson.build
This allows users to programatically change the active layout.
=> Add a new xkb_switch_layout command

sway/sway-input.5.scd
=> Add missing docs for xkb_switch_layout

sway/sway-ipc.7.scd
I wanted to add this to #4241, but @RedSoxFan is too quick to merge :P
=> Add docs for new IPC keyboard properties

sway/commands/mode.c
This allows for modes to be created, bindings to be added to modes, and
bindings to be removed from modes at runtime. Additionally, this also
allows for `mode <mode>` to be deferred in the config to set an initial
mode.
Bindings can already be added and removed from the default mode at
runtime so I don't see why manipulating other modes should be any
different.
=> cmd_mode: allow runtime creation and modification

sway/commands/layout.c
Fixes #4129
This fixes the logic of split for layout toggle when the default
layout is L_TABBED or L_STACKED. When the default layout is L_TABBED
or L_STACKED, the container/workspace may not have a prev_split_layout.
This was causing L_NONE to be returned by get_layout_toggle, which was
being handled as a syntax error. This adds logic to try
config->default_orientation when prev_split_layout is L_NONE. If that
is also L_NONE, then L_VERT is used when the output is taller than
wide, otherwise, L_HORIZ is used.
=> cmd_layout: toggle split for tabbed/stack default

README.md, README.nl.md
=> Added Dutch translation of README

include/sway/criteria.h, sway/commands/for_window.c, sway/commands/no_focus.c, sway/criteria.c
=> Avoid adding duplicate criteria for no_focus and command

sway/config/output.c, swaybar/render.c
=> Minor fixes

sway/tree/workspace.c
Fixes #4432 
Since output names can change in various configurations, including
DisplayPort MST, prefer output identifiers for the output priority.
Users can still use `workspace <ws> output <names-or-ids>`, but any
output that is programmatically added to the list will be added under
the output identifier. If the output name exists in the list (from the
user workspace output configs), then that will be retained instead of
switching to the output identifier for that output.
=> workspace: prefer identifiers for output priority

sway/input/seatop_down.c
Closes #4172 
Closes #4389
This adds an axis handler to seatop_down so that it is possible to
manually scroll while having a mouse button down. This is mainly useful
for selecting text. Some applications may not automatically scroll when
the cursor is near the edge of the application or the user may just
prefer manually scrolling for more control over the scrolling speed.
=> input/seatop_down: add axis handler

sway/commands.c
Fix for #4483.
That's the quick and dirty solution instead of refactoring all commands to process lists of nodes.
It might be enough or not but it should be closer to the intended behavior than what we have now.
=> ipc: collapse multi-container command results

sway/desktop/render.c
i3's currently displays a border on all 4 sides of titlebars as a result of i3/i3#3485 being merged, while sway still uses the old behavior of only doing so for tabbed layouts. This PR essentially updates sway to match i3's current behavior.
Here are some comparison screenshots with `titlebar_padding 2 2` (this setting matches i3):
Before this change:
After this change:
Latest version of i3 for comparison:
=> Update titlebar borders to match i3's current behavior.

sway/sway-input.5.scd
This isn't described in xkeyboard-config(7).
=> man: document how to specify multiple xkb layouts and options

sway/input/seatop_default.c
Subsurfaces (in most cases popups) aren't decorated by sway
and will never have any borders, but may be drawn beyond container
boundaries producing false positive when searching for edge.
So we want to skip edge search when handling mouse event on subsurface.
=> Do not search for edges on subsurfaces, fix #4381

sway/tree/view.c
Fixes #4565 
If the view was mapped as fullscreen or the view was assigned either a
workspace or output, the pid was not being populated since it was
occurring as part of the pid mapping check in select_workspace. This
extracts the pid population and makes it so it is always executed
=> view: always populate pid

meson.build
Closes: https://github.com/swaywm/sway/issues/4618
=> build: bump wlroots version to 0.8.1

include/sway/config.h, sway/commands/focus.c, sway/commands/focus_wrapping.c, sway/sway.5.scd
Following i3 support: https://github.com/i3/i3/pull/3407
Step 1 of #4638
=> focus: support focus_wrapping workspace

sway/desktop/output.c
Closes: https://github.com/swaywm/sway/issues/4663
=> Fix presentation feedback when scanning out fullscreen view

sway/input/seatop_move_floating.c
=> seatop_move_floating: make container respect pointer constraint

sway/input/seatop_default.c
Closes #4693 
Some xwayland clients like dmenu and rofi can never regain keyboard focus once they've lost it.
Now clicking on the view can give those clients keyboard focus again. This should bring sway more in line with the X11 behavior of those applications.
Not sure if I've accidentally borked some other xwayland behaviors here, testing appreciated. PTAL.
=> seatop_default: handle focus for xwayland_unmanaged views

include/sway/config.h, sway/commands/hide_edge_borders.c, sway/commands/smart_borders.c, sway/config.c, sway/sway.5.scd, sway/tree/view.c
=> smart_borders: separate smartness from edge types

include/sway/commands.h, include/sway/config.h, sway/commands/input.c, sway/commands/input/map_to_output.c, sway/commands/input/map_to_region.c, sway/config/input.c, sway/input/seat.c, sway/meson.build, sway/sway-input.5.scd
This has been in the documentation for a while but never got implemented.
=> Implement input map_to_region command

sway/config/output.c
If the screen DPI is high enough, auto-enable scale=2 (if the user
hasn't set the scale).
Uses heuristics based on [1].
[1]: https://gitlab.gnome.org/GNOME/mutter/blob/05217066171992b0bc50882869aad6385285c878/src/backends/meta-monitor.c#L1590
Closes: https://github.com/swaywm/sway/issues/1800
=> Auto-detect output scale

sway/config/input.c
Fixes the first bullet of #4811 
When an input becomes available, the input type config for that device
type will be merged underneath the input identifier config, provided
they both exist. If an input type config gets added or modified at a
later point, then those changes get merged onto the input identifier
configs for that type. However there was a missing case of the input
identifier config being added after the device is already available and
the input type config existing. This makes it so that the first time an
input identifier config gets stored, there will be a check to see if it
matched any of the available devices. If it does, then there will be a
search for the associated input type config, which will be merged
underneath the input identifier config if found.
=> config/input: set type for new identifier configs

swaybar/swaybar-protocol.7.scd
=> Fix typo in swaybar-protocol.7.scd

include/sway/input/input-manager.h, sway/input/input-manager.c
Plumbing for [this PR](https://github.com/swaywm/wlroots/pull/1879) in wlroots
=> Add virtual pointer protocol

include/swaynag/swaynag.h, swaybar/input.c, swaynag/swaynag.c
This fixes multi-seat related issues in swaynag and swaybar.
=> Fix multi-seat related issues

sway/input/cursor.c
Related #4884 
See https://gist.github.com/FreeFull/2a00065a15b1a2ea079f29274c8c9532 for the backtrace provided by @FreeFull on IRC
This fixes a crash when attempting to listen to a signal on a NULL
cursor image surface. If the surface is NULL, the listener is just
reinitialized using wl_list_init.
=> input/cursor: handle setting a NULL image surface

protocols/wlr-layer-shell-unstable-v1.xml
Brings spelling in line with wlr-protocols/unstable/wlr-layer-shell-unstable-v1.xml
=> Amend typo

sway/desktop/render.c
Two changes were made:
- Bind the texture before glTexParameteri
- Set the scaling filter before each wlr_render_texture_with_matrix call
Logging in wlroots allows to check that the scaling filter is properly
set prior to rendering.
Fixes: 6968fb3123e6 ("add scale_filter output config option")
Closes: https://github.com/swaywm/sway/issues/4798
cc @RPigott
=> Fix unreliable scaling filter

config.in
It was not obvious to me why until I saw a comment from @RyanDwyer on Reddit, so I think it's better to add an explanation. Tried to keep the comment as short as possible.
=> Docs: explain why menu command should be passed to sway

sway/ipc-server.c
The `ipc_event_binding` function does not handle encoding of bindswitch events, and there is currently no documented format for these events in the ipc documentation.
To avoid sway crashing when any binding event listeners are registered and a bindswitch event occurs, simply ignore the event. I have implemented it this way as it resolves the crash. However it might be useful to implement support for bindswitch events?
=> Resolve bindswitch events causing crash when listener is registered

contrib/grimshot
Hi,
This adds the possibility to capture only the focused screen(s) if several are used
Regards,
=> Add 'output' mode to grimshot

sway/input/input-manager.c
Depends on https://github.com/swaywm/wlroots/pull/2019
=> input: Map virtual-pointer to the requested output

include/sway/output.h, sway/config/output.c, sway/desktop/output.c, sway/tree/output.c
Closes: https://github.com/swaywm/sway/issues/4960
=> Fix output scale auto-detection

sway/commands/input/events.c
Closes #4661 
This adds support for input type configs to input_cmd_events. This works
similar to the wildcard handling that existed where configs for the
devices are stored and the type config is reset to INT_MIN so that it
does not override.
This also condenses the toggle_send_events and
toggle_wildcard_send_events functions into a single function to reduce
code duplication.
=> input_cmd_events: add support for input types

include/sway/output.h, include/sway/server.h, protocols/meson.build, protocols/wlr-output-power-management-unstable-v1.xml, sway/desktop/output.c, sway/server.c
See https://github.com/swaywm/wlroots/pull/1875
=> Add support for wlr-output-power-management-unstable-v1

sway/ipc-server.c
Felt the need for this while investigating #5044.
=> ipc-server: improve error message

include/sway/tree/view.h, sway/desktop/output.c, sway/tree/view.c
Update for breaking changes in [1].
[1]: https://github.com/swaywm/wlroots/pull/2043
=> Use wlr_client_buffer

common/log.c
Same as [1].
[1]: https://github.com/swaywm/wlroots/pull/2052
=> common/log: log current time with milliseconds

sway/ipc-json.c
Fixes #5078, which also brings us inline with i3 behaviour.﻿
=> Fix big workspace numbers overflow

completions/fish/sway.fish
`--config` should autocomplete filepaths
=> Update fish completions

sway/sway-output.5.scd
=> Fix output mode usage

include/swaybar/tray/icon.h, include/swaybar/tray/item.h, swaybar/input.c, swaybar/ipc.c, swaybar/tray/host.c, swaybar/tray/icon.c, swaybar/tray/item.c, swaybar/tray/watcher.c
1st commit fixes a small memory leak
Rest are tray-related.
2nd commit is just a QoL improvement for debugging.
3rd commit fixes icon inheritance to bring it up to spec.
4th commit performs refactoring, including some logic that I believe should have been removed in https://github.com/swaywm/sway/pull/4532/ since the `find_icon_in_dir` call is already performed in the previous `find_icon` call. 
5th commit fixes #4942.
Cherry-pick as necessary
=> Various swaybar improvements

sway/tree/view.c
Update for https://github.com/swaywm/wlroots/pull/2044
=> Update for new wlr_buffer API

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml
scodc is now available in all distributions we have CI for.
=> ci: don't build scdoc

ISSUE_TEMPLATE.md
The issue tracker has already enough traffic with bug reports and
feature requests.
=> Redirect questions to wiki/IRC

sway/input/keyboard.c
Added in swaywm/wlroots#2172, so that sway doesn't need to maintain
an independent copy of this function.
Minor space &rarr; tab conversion also included for two lines.
=> input/keyboard: use wlr_keyboard_keymaps_match from wlroots

sway/sway-output.5.scd, sway/sway.5.scd
The current documentation for repaint scheduling is very technical and
somewhat confusing.
Closes: https://github.com/swaywm/sway/issues/4769
=> Simplify repaint scheduling documentation

sway/input/input-manager.c, sway/input/seat.c
Fixes #5029 
If the keyboard that triggers the reload binding is using the default
keymap, default repeat delay, and default repeat rate, the associated
keyboard group is never being destroyed on reload. This was causing the
keyboard group's keyboard not to get disarmed and result in a
use-after-free in handle_keyboard_repeat.
If the keyboard was not using the defaults for all three settings, then
it's associated keyboard group would get destroyed during the reset -
which did disarm the keyboard group's keyboard. In this case, the
use-after-free would not occur.
This adds a block to input_manager_reset_all_inputs that disarms the
keyboard for all keyboard groups in all seats. Since the inputs are all
being reset anyway, which will disarm all individual keyboards, it is
not necessary to be …
=> input: reset keyboard groups keyboard on reset all

sway/tree/container.c
This makes transient containers have logic more in-line with the test from `floating_container_at`. This fixes bugs where a floating container would take input way past its borders when its parent was fullscreened.
---
This was particularly noticeable in Xwayland apps. For instance, a fullscreened Chrome or Jetbrains IDE dialog would be resizable (and show the resize cursor image) everywhere outside its bounds. It's also present in Wayland-native apps, e.g. Firefox's <kbd>Ctrl</kbd>+<kbd>O</kbd> file browser can be moved by dragging around anywhere, not just on the dialog itself.
=> input/cursor: only consider in-bounds floaters for fullscreen hit test

sway/desktop/xwayland.c
This is necessary because some applications (e.g. Jetbrains IDEs) represent their multi-level menus as unmanaged surfaces, and when closing a submenu, the previous "parent" menu should get input focus.
Closes #5347.
---
It's not clear-cut to me whether this is entirely correct, but it definitely makes menus in PyCharm and CLion usable. The focusing logic on map is a bit different; it also calls `wlr_xwayland_set_seat`:
https://github.com/swaywm/sway/blob/6f7b548589feead7c3c3ae8d619f23770fd65fb0/sway/desktop/xwayland.c#L78-L81
I don't have any testcases where not including that logic breaks something, so felt it best to bring it up for discussion.
---
This PR regresses https://github.com/swaywm/sway/issues/4370. It makes the workaround from https://github.com/swaywm/sway/issues/3007 …
=> xwayland: pass focus to previous unmanaged surface on unmap

include/sway/tree/view.h, sway/desktop/render.c, sway/tree/view.c
=> Save transform during transaction

common/meson.build
This PR is based off of the discussion over at #5410 which seems to have reached a stalemate so I've made this PR for it.
=> Add wayland_client dependency to common

sway/input/seatop_default.c
If a resize is triggered on a tabbed or stacked container, change focus to the tab which already had inactive focus, rather than to the tab whose border was clicked -- otherwise, we'd change the active tab when the user probably just wanted to resize.
---
Tested with tabbed and stacked containers, with both `focus_follows_mouse yes` and `no`.
=> input: tweak resize behavior to not change tab focus on border click

completions/bash/swaymsg, completions/fish/swaymsg.fish, completions/zsh/_swaymsg, include/ipc.h, include/sway/ipc-json.h, sway/ipc-json.c, sway/ipc-server.c, sway/sway-ipc.7.scd, swaymsg/main.c, swaymsg/swaymsg.1.scd
Introduced to i3 here https://github.com/i3/i3/pull/4122.
Resolves #5447
=> i3-compat: add GET_BINDING_STATE IPC command

sway/input/seatop_default.c
This commit makes tablet input more usable when `focus_follows_mouse` is
set to `no`.
Previously, tapping down on surfaces that bound tablet input would not
switch focus, whereas tapping on surfaces that didn't (and hence went
through pointer emulation) did.
This misbehavior is masked when `focus_follows_mouse` is set to `yes`,
which is probably why this hasn't come up before.
=> input/tablet: focus appropriate node on tip down

sway/input/seatop_default.c
Prior to this commit, a tablet device could trigger mouse button down
bindings if the pen was pressed on a surface that didn't bind tablet
handlers -- but it wouldn't if the surface did bind tablet handlers.
We should expose consistent behavior to users so that they don't have to
care about emulated vs. non-emulated input, so stop triggering bindings
for any non-pointer devices.
=> input/pointer: don't trigger pointer bindings for emulated input

include/sway/tree/view.h, sway/desktop/render.c, sway/server.c, sway/tree/view.c
Depends on https://github.com/swaywm/wlroots/pull/2092
=> Add support for viewporter

include/sway/server.h, include/sway/tree/view.h, sway/server.c, sway/tree/container.c, sway/tree/view.c
A rebase of #4476 as requested by @ddevault 
There were no risky merge conflicts. Compiled and shortly tested as well.
=> Rebase of wlr-foreign-toplevel-management-v1

sway/desktop/output.c
See: https://github.com/swaywm/wlroots/pull/2309
cc @emersion
=> output: simplify loop over layer surfaces

README.ro.md
These are from the original review; I think these were accidentally marked as resolved rather than confirmed.
=> Minor wording changes in Romanian README.md translation

sway/input/seat.c, sway/server.c
=> Graceful Xwayland failures

sway/input/input-manager.c
=> Replace unprintable characters in input device id

sway/tree/output.c
References: https://github.com/swaywm/sway/issues/5483
=> Assert output is found before removing from list

common/util.c, include/util.h, sway/commands/move.c, sway/commands/resize.c, sway/sway.5.scd
You could specify the width and height of a container in percent when resizing it but not when moving it.
I also updated the docs to reflect the changes. 
First time coding in C, hopefully my formatting is ok :)
=> added ppt unit to move position command

sway/commands.c
Simple fix for #5569 if this is what we want.
=> commands: disallow runtime include

common/ipc-client.c, common/loop.c, sway/commands/bar/colors.c, sway/commands/bind.c, sway/desktop/layer_shell.c, sway/input/libinput.c, sway/input/seat.c, sway/ipc-json.c, sway/ipc-server.c, sway/main.c, swaynag/main.c
Hi!
This is a collection of small patches fixing some warnings reported by PVS-Studio.
Happy to change things if I got the "bug fix" wrong.
=> Patches to address static analysis warnings

include/swaynag/types.h, swaynag/config.c, swaynag/render.c, swaynag/swaynag.1.scd, swaynag/swaynag.5.scd, swaynag/types.c
Adds a new config option for details background for swaynag
Closes #5673
=> swaynag: add details background option

sway/server.c
Closes: #5687
See https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/486
=> server: Avoid using "wayland-0" as WAYLAND_DISPLAY

sway/desktop/xwayland.c
Fixes https://github.com/swaywm/sway/issues/5667
=> check parent surface before it is destroyed

README.pt.md
Fixed typos and added some new info from the English version.
=> Update Portuguese README

README.ja.md
=> Small wording change to README.ja.md

sway/sway-ipc.7.scd
=> document parse_error in run_command reply

sway/desktop/xdg_shell.c
Fixes #5750.
Currently, when sway sends a configure with some geometry and the client responds with a different geometry in a commit that acks that configure, sway ignores the new size. Sway applies the surface geometry it had requested to the container, not what was actually committed, in the following transaction.
This change allows any client commit to change its surface geometry, even if it is a response to a configure event.
=> xdg_shell: allow views to change geometry anytime

include/sway/input/cursor.h, sway/commands/seat/cursor.c, sway/input/cursor.c, sway/input/seat.c
=> input/cursor: unhide cursor on synthetic input

sway/server.c
See: https://github.com/swaywm/wlroots/issues/2421 https://github.com/swaywm/wlroots/pull/2460
=> Drop gtk-primary-selection support

.builds/archlinux.yml
=> ci: fix archlinux builds

sway/server.c
It's removed upstream [1].
[1]: https://github.com/swaywm/wlroots/pull/2561
=> Remove create_renderer_func argument

include/sway/input/text_input.h, sway/input/seat.c, sway/input/text_input.c
I was playing with multi-seat and ran into some use-after-free issues.
=> Fix seat use-after-free

sway/main.c, swaybar/main.c, swaymsg/main.c, swaynag/config.c
Changed variable name from "f" to for example "DetectRaspi"
Changed fprintf(stdout,...) to printf(...) for more readable code and it's basically the same.
=> More readable code

include/sway/tree/view.h, sway/desktop/render.c, sway/desktop/transaction.c, sway/desktop/xdg_shell.c, sway/desktop/xwayland.c, sway/tree/view.c
Closes: https://github.com/swaywm/sway/issues/5848
=> Transactional resize fixes

sway/desktop/transaction.c
Transactions currently wait for all configures to be acked, regardless
fo what they were sent to. This includes views that are hidden in tabbed
or stacked containers. If these views do not ack the configure in
response to a single frame callback, they can cause transaction
timeouts.
Check if a container is hidden before registering the configure serial
and saving any view buffers.
Closes: https://github.com/swaywm/sway/issues/6023
=> transaction: Only wait for ack from visible views

sway/ipc-json.c
Try to better mimic JSON node structure produced by i3 which might be
relied on by already existing tools. In particular having "type" right
after "id" is quite handy for streaming high-performance JSON parsers
such as simdjson (which are handy for maintaining responsiveness on
resource constrained systems).
refer https://github.com/i3/i3/blob/ab2a22a78b25ad12fed2c177a34c44950795cf33/src/ipc.c#L338
=> Align ordering of core node properties with i3

swaybar/render.c
Closes #5605
Text Subpixel antialiasing is :
- FreeType makes glyph bitmaps containing coverage percentage for each
subpixel, instead of pixel
- Then draw by performing the blend for each subpixel, instead of pixel (e.g.
dual-source blending in opengl)
And there's only one Alpha channel, so this extra coverage data can't
leave Cairo to reach the compositor through there.
Therefore, it can't work as intended if output text alpha != bar background
alpha. Disable it for those cases, enable it elsewhere
As for color emojis, they are RGBA bitmaps. If drawn with text alpha=1.0
and background alpha=1.0 (should be completely opaque bar), then with
'CAIRO_OPERATOR_SOURCE' texels with alpha < 1.0 result in a blend with
whatever's behind the bar, instead of the bar background
=> swaybar: use text subpixel antialias only where it would look good

sway/tree/container.c
container: Add view_container_content_at
container_at checks if the position provided matches the currently
focused container with view_container_at as a fast path.
view_container_at checks using the main container geometry, which
includes the titlebar and border area. If a tabbed container is focused,
then positions over unfocused tabs are incorrectly reported as belonging
to the focused container, breaking focus on click.
Add view_container_content_at for use in the focused container fast path
which only tests container content area, and fall back to full workspace
scans for border and titlebar areas.
Closes: https://github.com/swaywm/sway/issues/6074
=> container: Use content geometry in view_container_at

.builds/alpine.yml
The name was changed recently.
=> ci: Update alpine xwayland package name

sway/tree/container.c
"Bug report" I saw on irc:
> 15:23 <FreeFull_> By the way, I bug I noticed: With tabbed layouts, often when I unfloat a window, it'll end up in a split layout rather than going in as a tab
i3 tries a little harder to restore floated windows to their original position, so let's do that too. Ref in i3: https://github.com/i3/i3/blob/9bf9cb9926402e73aa62e4c1bcc03d671c849c2e/src/floating.c#L244
=> Match i3 floating enable/disable behavior

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml, meson.build
See https://github.com/swaywm/wlroots/pull/2839
=> Mandatory libseat

sway/tree/container.c
the original behavior set fullscreen for all descendents of a container, which causes issues when firefox is one of those children because it sends its own set_fullscreen request in response to being fullscreened.
=> container: don't set fullscreen on children

sway/commands/exec_always.c, sway/swaynag.c, swaynag/swaynag.c
=> Minor exec improvements

sway/main.c
Signed-off-by: Bartłomiej Burdukiewicz <bartlomiej.burdukiewicz@gmail.com>
=> main: removed vc4 detection code.

README.md, README.tr.md
Added Turkish translation to README.tr.md
=> Add Turkish README

sway/input/seatop_move_tiling.c
Implements functionality described in [1].  Please see the issue for a
video with a demonstration of the new behavior.
An issue is that titlebars cover up a significant portion of the top
edge drop area.  The solution is simply to change the edge drop area
hitbox to start at the contents instead of the container.
[1] https://github.com/swaywm/sway/issues/6218
=> Add tab dragging functionality

sway/commands/fullscreen.c
Fullscreen request on a workspace crashes sway since #6190. Whoops.
=> cmd_fullscreen: ignore fullscreen request on workspaces

sway/commands/exec_always.c
This commit fixes a rare edge case, in which very long commands are silently truncated. One way to test this is to compare the following two shell commands; if truncation occurs, the first will fail to set the background color.
```
swaymsg exec "swaynag -m `(head -c 4096 < /dev/zero | tr '\0' 'a')` --background 00FF00"
swaynag -m `(head -c 4096 < /dev/zero | tr '\0' 'a')` --background 00FF00
```
=> commands/exec: stop truncating >4095-byte commands

sway/desktop/render.c
update for https://github.com/swaywm/wlroots/commit/6369f7093178f0d66414eb67c312a403bfbb84a4
=> Remove usage of `wlr_texture_get_size`

include/sway/server.h, sway/meson.build, sway/server.c, sway/xdg_activation_v1.c
Depends on https://github.com/swaywm/wlroots/pull/2718.
=> Implement xdg-activation-v1

sway/sway-output.5.scd
=> fix typo in sway-output.5.scd

include/swaynag/types.h, swaynag/config.c, swaynag/swaynag.1.scd, swaynag/swaynag.5.scd, swaynag/swaynag.c, swaynag/types.c
Uses --layer/-y set to overlay|top|bottom|background
Closes https://github.com/swaywm/sway/issues/4939
=> swaynag: adds option to set wayland shell layer

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml, meson.build, sway/desktop/render.c, sway/main.c, sway/server.c, sway/tree/view.c
This PR cherry-picks commits from master to v1.6 to allow building with wlroots 0.14.0.
=> Update for wlroots 0.14.0

.builds/alpine.yml, client/pool-buffer.c, common/background-image.c, common/cairo.c, common/pango.c, common/util.c, include/background-image.h, include/cairo_util.h, include/pango.h, include/pool-buffer.h, include/util.h, sway/commands/bar.c, sway/commands/seat/attach.c, sway/config.c, sway/desktop/layer_shell.c, sway/desktop/output.c, sway/desktop/render.c, sway/input/cursor.c, sway/tree/container.c, sway/tree/view.c, sway/tree/workspace.c, swaybar/render.c, swaybar/tray/item.c, swaynag/render.c
Skimmed over the git log and chery-picked some good candidates for the upcoming bugfix release. This may not be exhaustive, feel free to open other PRs against the stable branch to nominate other fixes.
Depends on https://github.com/swaywm/sway/pull/6339
=> Collection of bugfixes for 1.6.1

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml, meson.build, protocols/meson.build
Same as https://github.com/swaywm/wlroots/pull/2989, but for Sway.
=> ci: make Meson warnings fatal

include/sway/input/cursor.h, sway/input/cursor.c
Update for the breaking change in [1].
[1]: https://github.com/swaywm/wlroots/pull/3001
=> Add support for touch frame events

README.ir.md, README.md
The same #5611 PR with changes to the updated repository.
=> Add persian README file

sway/config/output.c
Sometimes the preferred mode is not available due to hardware
constraints (e.g. GPU or cable bandwidth limitations). In these
cases it's better to fallback to lower modes than to end up with
a black screen.
Tested with this wlroots patch:
```diff
diff --git a/backend/drm/drm.c b/backend/drm/drm.c
index cd161e02b777..550b450d68bf 100644
--- a/backend/drm/drm.c
+++ b/backend/drm/drm.c
@@ -474,6 +474,10 @@ static bool drm_connector_test(struct wlr_output *output) {
}
}
+	if ((output->pending.committed & WLR_OUTPUT_STATE_MODE) && output->pending.mode->preferred) {
+		return false;
+	}
+
return true;
}
```
Helps with some DP adapters.
=> Fallback to other output modes if preferred mode fails

sway/sway.5.scd
=> Fix typo in sway.5.scd

sway/sway.5.scd
Along with f4cda51 fixes #6217.
=> Update Pango font description URL in sway.5.scd

sway/desktop/xwayland.c
This commit updates Sway for swaywm/wlroots#2915.
=> desktop/xwayland: restack surface upon activation

sway/commands/split.c
@emersion https://github.com/swaywm/sway/pull/4935#issuecomment-912839599
Oops.
=> commands: update split none command for a047b5ee4

sway/tree/view.c
https://github.com/swaywm/wlroots/pull/3169
=> surface: chase wlr subsurface list/link change

README.de.md, README.dk.md, README.es.md, README.fr.md, README.hu.md, README.ir.md, README.ja.md, README.ko.md, README.md, README.nl.md, README.pl.md, README.pt.md, README.ro.md, README.ru.md, README.tr.md, README.uk.md, README.zh-CN.md, README.zh-TW.md
gamja offers a better experience than Kiwi.
Obviously I'm 100% biased. Completely fine to not make the switch if someone feels differently.
=> readme: link to gamja for IRC

swaybar/render.c
fixes #6510
introduced via #3287 -- https://github.com/swaywm/sway/pull/3287/files#diff-a1e918ce0bc71f4f7934767541319e724a51a34a5418ecdc286065e50921eda4L239
uncovered via #3394 -- https://github.com/swaywm/sway/pull/3394/files#diff-a1e918ce0bc71f4f7934767541319e724a51a34a5418ecdc286065e50921eda4R258
=> swaybar: properly draw urgent block right border

README.gr.md, README.md
Added README.gr.md file with Greek(Ελληνικά) translation and added Ελληνικα as a available translated language on the README.md
=> README: Added Greek translation

sway/desktop/xdg_shell.c
https://github.com/swaywm/wlroots/pull/3199
=> xdg-shell: chase wlr xdg toplevel refactor

include/sway/tree/view.h, sway/desktop/xdg_shell.c
Reverts https://github.com/swaywm/wlroots/pull/3199
This is now done by wlroots automatically.
=> Revert xdg toplevel maximize configure schedule

sway/config/output.c
References: https://github.com/swaywm/wlroots/pull/3205
=> Add support for DRM panel orientation

sway/desktop/layer_shell.c, sway/desktop/xdg_shell.c
See [1].
[1]: https://github.com/swaywm/wlroots/pull/3106
=> Chase wlr_xdg_surface breaking changes

sway/sway-input.5.scd
Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>
=> sway-input.5.scd: Fix spelling errors

sway/server.c
Update for the wlroots breaking change in [1].
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3367
=> Replace wlr_headless_backend_create_with_renderer call

include/sway/commands.h, include/sway/config.h, include/sway/tree/container.h, sway/commands.c, sway/commands/client.c, sway/config.c, sway/desktop/render.c, sway/sway.5.scd, sway/tree/container.c
Implements the [i3/i3#4650](https://github.com/i3/i3/pull/4650) feature.
=> Add title bar color

include/sway/server.h, protocols/meson.build, sway/server.c, sway/tree/container.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/1376
=> Add support for linux-dmabuf surface feedback

sway/input/seatop_resize_floating.c
This fixes #5337
Here's original author's PR. https://github.com/swaywm/sway/pull/5438
Seems like OP is not active for long time. So I fixed the build error, and squashed commits into one.
Thanks.
=> Handle border width and height on minimum floating sizes

swaymsg/main.c
This makes it easier to find information to write `for_window` rules.
=> swaymsg: add GET_TREE pretty-printing

sway/ipc-json.c
Closes #6735
wlroots already has the info in the struct so let's access it and print it out.
=> [IPC] Add repeat delay/rate info to keyboard

sway/input/seat.c
We currently track the focus of a seat in two ways: we use a list called `focus_stack` to track the order in which nodes have been focused, with the first node representing what's currently focused, and we use a variable called `has_focus` to indicate whether anything has focus—i.e. whether we should actually treat that first node as focused at any given time.
In a number of places, we treat has_focus as implying that a focused node exists. If it's true, we attempt to dereference the return value of `seat_get_focus()`, our helper function for getting the first node in `focus_list`, with no further checks. But this isn't quite correct with the current implementation of `seat_get_focus()`: not only does it return NULL when `has_focus` is false, it also returns NULL when `focus_stack` …
=> input/seat: unset has_focus when focus_stack becomes empty

include/sway/layers.h, sway/desktop/layer_shell.c
Closes: https://github.com/swaywm/sway/issues/6337
=> Destroy sub-surfaces with parent layer-shell surface

include/sway/desktop.h, include/sway/input/cursor.h, include/sway/input/text_input.h, include/sway/layers.h, include/sway/surface.h, include/sway/tree/container.h, include/sway/tree/view.h, sway/desktop/layer_shell.c, sway/desktop/output.c, sway/desktop/render.c, sway/desktop/surface.c, sway/server.c, sway/tree/container.c, sway/tree/view.c
See [1] for details.
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3412
cc @vyivel
=> Upgrade for wlroots surface refactoring

sway/input/cursor.c
Fixes https://github.com/swaywm/sway/issues/6765.
=> input/cursor: count pointer gestures as idle activity

sway/commands/input/xkb_switch_layout.c, sway/input/input-manager.c, sway/input/keyboard.c
See https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3334
=> wlroots input device refactor

include/sway/tree/container.h, sway/input/seat.c, sway/input/seatop_default.c
=> Remove some erroneous apostrophes in comments

include/sway/config.h, sway/commands/bind.c, sway/input/switch.c
Ref [1].
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/4792446ee8f50104bd207d9ccd8558a7e4eb4514
=> Remove WLR_SWITCH_STATE_TOGGLE usage

include/sway/input/cursor.h, include/sway/input/seat.h, sway/commands/seat/cursor.c, sway/input/cursor.c, sway/input/keyboard.c, sway/input/seat.c, sway/input/seatop_default.c, sway/input/seatop_down.c, sway/input/switch.c, sway/input/tablet.c
Superseeds #6882 and #6877
Ref [1] and [2]
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3482
[2]: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3484
Closes https://github.com/swaywm/sway/issues/6895
=> Follow up wlroots input device refactor

sway/input/seat.c
=> sway/input: fix bad position of wlr_drag

README.md, README.sv.md
=> Swedish README

sway/commands/input/xkb_switch_layout.c
First calculate absolute layout indexes and then apply
Fixes #6011
=> xkb_switch_layout: fix relative layout switches

sway/input/seat.c
=> Avoid inspecting a NULL view in seat_set_focus

sway/sway.5.scd
=> man: Add descriptions for `stacking` and `tabbed` layouts

README.zh-CN.md
Plus, what is the "HEAD of sway and wlroots"?
=> polished the language in README.zh-CN.md & sync with English one

sway/config/output.c, sway/ipc-json.c
Closes: https://github.com/swaywm/sway/issues/7030
=> Handle NULL output make/model/serial

sway/desktop/layer_shell.c, sway/desktop/xdg_shell.c
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3514
=> chore: chase wlroots xdg-shell update

include/sway/input/keyboard.h, include/sway/input/switch.h, include/sway/input/tablet.h, sway/commands/input/xkb_switch_layout.c, sway/input/cursor.c, sway/input/keyboard.c, sway/input/seat.c, sway/input/switch.c, sway/input/tablet.c, sway/ipc-json.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3626
Closes: https://github.com/swaywm/sway/issues/7077
=> Remove access to wlr_input_device union

sway/input/seatop_default.c
Ref https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3461
=> input: chase delta_discrete semantics change

sway/server.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3428
=> Enable single-pixel-buffer-v1

sway/config/output.c, sway/ipc-json.c
Required for [1].
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3637
=> config/output: test adaptive sync

sway/ipc-json.c, swaymsg/main.c
See https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/2178573b0a5a8160564da1fd85c1f16f7d4d7bdd
=> ipc: expose mode picture aspect ratio

include/sway/commands.h, sway/commands/output.c, sway/commands/output/unplug.c, sway/meson.build
Closes: https://github.com/swaywm/sway/issues/5522
=> sway/commands/output: Add command for unplugging non-physical outputs

sway/input/seatop_default.c
=> input: focus floating container when clicked on border

include/sway/server.h, sway/desktop/idle_inhibit_v1.c, sway/input/seat.c, sway/server.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3753
=> Add support for ext-idle-notify-v1

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml
Required by the latest changes to wlroots.
=> ci: install hwdata

include/sway/output.h, sway/desktop/layer_shell.c, sway/desktop/output.c, sway/desktop/render.c, sway/tree/output.c
wlr_output_damage is to be replaced with wlr_damage_ring, so use that.
=> Use wlr_damage_ring

sway/lock.c
Closes: https://github.com/swaywm/sway/issues/7120
=> lock: fix crash on output destroy

sway/tree/container.c
=> container_get_siblings: handle NULL workspace

sway/desktop/output.c
Fixes: https://github.com/swaywm/sway/issues/7254
=> output: set damage ring bounds to pixel values

include/sway/input/seat.h, sway/input/seat.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3861
=> input/seat: locally compute drag icon offset

include/sway/output.h, sway/desktop/output.c
References: https://github.com/swaywm/wlroots/pull/2693
=> Listen to the output request_state event

include/sway/server.h, protocols/meson.build, sway/ipc-json.c, sway/server.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3599
=> ipc: add view content type

include/sway/server.h, sway/input/keyboard.c, sway/server.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3814
=> Update for wlroots!3814

client/pool-buffer.c
This continues the replacement of mkstemp by shm_open; see also https://github.com/swaywm/swaybg/pull/49 .
(This change only affects `swaynag` and `swaybar`.)
=> Use shm_open instead of mkstemp

sway/server.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3903
Closes: https://github.com/swaywm/sway/issues/7298
=> Chase breaking changes in wlroots!3903

include/sway/output.h, sway/desktop/output.c, sway/lock.c
See [1]
Closes #7304 
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3911
=> remove output mode handles

.builds/alpine.yml, .builds/freebsd.yml
See https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3621
=> ci: install Xwayland .pc file

sway/commands/font.c
This is https://github.com/swaywm/sway/pull/7351 but targeting the v1.8 branch.
Maybe we can merge this for 1.8.1, then decide on a better fix for 1.9?
=> [1.8] Allow setting the font size to 0

sway/input/seatop_default.c, sway/tree/view.c
Accomodate for the breaking changes in [1].
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/fbf5982e3838ee28b5345e98832f6956c402b225
=> Convert to wlr_xwayland_surface_try_from_wlr_surface()

sway/input/cursor.c, sway/input/seatop_default.c, sway/tree/container.c, sway/tree/view.c, sway/xdg_activation_v1.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3991
=> Convert to *_try_from_wlr_surface() 

sway/ipc-server.c
=> ipc: add ability to subscribe to output event

sway/tree/container.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3933
Closes: https://github.com/swaywm/sway/issues/7436
Closes: https://github.com/swaywm/sway/pull/7437
=> Use wlr_linux_dmabuf_feedback_v1_init_with_options()

include/sway/surface.h, sway/desktop/layer_shell.c, sway/desktop/surface.c, sway/lock.c, sway/server.c, sway/tree/container.c, sway/tree/view.c
Alternative to https://github.com/swaywm/sway/pull/6929
=> Add support for fractional-scale-v1

sway/input/libinput.c
=> Fix map_to_output * turning off device

include/sway/surface.h, sway/desktop/output.c, sway/desktop/surface.c
Closes: https://github.com/swaywm/sway/issues/7464
=> Update surface fractional scale on output change

sway/sway-input.5.scd
See https://github.com/swaywm/sway/issues/6297
=> man: add warning for hide_cursor configuration

sway/desktop/output.c
=> Chase !4067

sway/desktop/output.c
=> Direct scanout fixes

include/sway/tree/view.h, sway/desktop/layer_shell.c, sway/desktop/output.c, sway/desktop/render.c, sway/desktop/xdg_shell.c, sway/desktop/xwayland.c, sway/input/seat.c, sway/lock.c, sway/xdg_activation_v1.c
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4043
Note: not much thought went into this. Everything seems to work correctly to me, although more testing is always appreciated.
=> chore: chase wlroots map logic unification 

sway/desktop/output.c
This avoids relying on the implicit wlr_output.pending state.
~~TODO: breaks gamma-control~~
=> desktop/output: use detached output state for page-flips

sway/sway.5.scd
Also noticed bindcode is missing [--no-repeat], not sure if this is intentional or not.
=> doc: add [--inhibited] to bindsym and bindcode

sway/input/cursor.c, sway/input/seat.c, swaybar/input.c, swaynag/swaynag.c
"left_ptr" is the legacy XCursor name. "default" is the cursor spec name.
=> Use "default" XCursor instead of "left_ptr"

sway/desktop/surface.c, sway/server.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3696
=> Send wl_surface.preferred_buffer_scale

README.ge.md, README.md
I am a native Georgian speaker and I have translated sway's `README.md`.
=> Add Georgian README

sway/xdg_decoration.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4316
=> chase wlroots!4316

sway/desktop/layer_shell.c, sway/input/cursor.c, sway/tree/container.c
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4288
=> chore: chase wlroots xdg-surface role rework

sway/server.c
Regular clients are not allowed to use this interface. wlroots already sends a protocol error if a non-Xwayland client tries to use this interface, but let's remove all temptation by hiding it completely.
=> Hide xwayland_shell_v1 from regular clients

include/sway/criteria.h, sway/criteria.c, sway/sway.5.scd
Matches all views. i3 PR: https://github.com/i3/i3/pull/4460
Fixes #7110
=> i3 compat: Adding support for the `all` criteria

README.ar.md, README.md
This pull request aims to resolve issue #7703
=> Translate readme to arabic

sway/desktop/xdg_shell.c
wlroots doesn't do it automatically anymore.
---
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4409
=> xdg-shell: send maximized if tiled isn't supported

sway/desktop/output.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3679
=> Apply gamma LUT when an output re-enabled

include/sway/server.h, include/sway/tree/view.h, include/sway/xdg_decoration.h, sway/desktop/layer_shell.c, sway/desktop/xdg_shell.c, sway/server.c, sway/xdg_decoration.c
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4345
=> xdg-shell: chase events update

README.de.md
=> Update README.de.md to match the EN one

sway/desktop/xwayland.c
When override-redirect changes, we need to setup/teardown listeners, just like we do for map.
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3773
=> desktop/xwayland: correctly handle association on o-r change

include/sway/input/seat.h, sway/desktop/layer_shell.c, sway/input/keyboard.c, sway/input/seat.c, sway/input/switch.c, sway/lock.c
This was a input-inhibit concept.
=> input/seat: drop exclusive_client

sway/desktop/output.c, sway/desktop/render.c
=> Chase wlroots!4482 "presentation-time: drop wlr_presentation arg"

include/sway/server.h, sway/server.c
=> Remove wlr_presentation in sway_server struct

include/sway/input/libinput.h, sway/input/input-manager.c, sway/input/libinput.c
Closes: https://github.com/swaywm/sway/issues/7890
=> input: reconfigure send_events on output hotplug

sway/server.c
See https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4397
=> Drop wl_drm

sway/input/seatop_default.c, sway/input/seatop_down.c
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4003
=> Chase wlroots!4003

sway/sway_text_node.c
@Nefsen402's patch from https://github.com/swaywm/sway/issues/7940#issuecomment-1915435698
Closes: https://github.com/swaywm/sway/issues/7940
=> Ensure get_text_width() returns a positive value

include/sway/server.h, include/sway/tree/view.h, sway/desktop/xdg_shell.c, sway/server.c, sway/tree/view.c
Requires: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4543
=> ext-foreign-toplevel-list: Implement protocol

include/sway/input/cursor.h, include/sway/input/seat.h, sway/commands/seat/cursor.c, sway/input/cursor.c, sway/input/seat.c, sway/input/seatop_default.c, sway/input/seatop_down.c, sway/input/seatop_move_floating.c, sway/input/seatop_move_tiling.c, sway/input/seatop_resize_floating.c, sway/input/seatop_resize_tiling.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4575
=> Convert to new pointer enums

sway/input/input-manager.c, sway/ipc-json.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4582
=> Fetch input device vendor/product from libinput

sway/desktop/output.c
=> Force bilinear scaling when scaling down

include/sway/server.h, sway/server.c
Depends on https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4606 to work properly.
=> Handle GPU resets

include/sway/input/input-manager.h, include/sway/input/seat.h, sway/input/input-manager.c, sway/input/seat.c, sway/server.c
This implements transient seats for sway. See: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3870
=> Transient seat

sway/input/seatop_down.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4613
=> input: pass wlr_seat_client to wlr_seat_touch_notify_cancel()

sway/sway_text_node.c
special case negative numbers instead.
=> sway_text_node: Allow 0 text width

meson.build
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4614
=> Update for versioned wlroots files

sway/tree/view.c
Closes: https://github.com/swaywm/sway/issues/7946
=> tree/view: ensure view content size is positive

protocols/meson.build
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4645
=> protocols: use tablet-v2 xml from stable/

sway/input/keyboard.c, sway/input/seat.c
Fixes: #8143 #8173
Upstream issue: https://github.com/fcitx/fcitx5/issues/1044
=> seat: don't send redundant leave/enter on device creation

meson.build
Master branch of wlroots just bump it's version to 0.19.0-dev. [commit](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/b10516e1e8352f3140d68fa580b0ed32e13c2d58)
=> build: Bump wlroots version

.builds/freebsd.yml, sway/desktop/xwayland.c, sway/input/cursor.c, sway/input/seatop_default.c, sway/input/tablet.c, sway/tree/view.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/2434
=> Chase wlroots!2434 "Assorted borderline bikeshedding breaking API cleanups"

sway/desktop/layer_shell.c
Commit 188811f80861 ("scene_graph: Port layer_shell") accidentally removed code in `arrange_layers` to handle focus on layer shell surfaces with keyboard interactivity.
Due to this, layer shell surfaces requesting exclusive keyboard interactivity may not get automatically focused, and layer shell surfaces giving up exclusive keyboard interactivity can remain focused.
Add the [previous code](https://github.com/swaywm/sway/blob/2c69e19fd30c5ceac61d6af821c6c6875cd3f8b6/sway/desktop/layer_shell.c#L247-L279) back to fix the problem.
Note the non-rename change included in b4d7e84d3852 ("desktop: Rename layers to shell_layers") is not included as it also seems accidental.
Fixes: #7936
=> layer-shell: Restore interactive layer focus code

sway/desktop/xwayland.c
See https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4670.
=> xwayland: chase wlr_xwayland_surface_set_maximized() change

sway/desktop/xwayland.c
=> xwayland: Let scene restack

sway/commands/output/color_profile.c
Allows using relative paths to specify the ICC file, and not just the absolute one.
I mostly took the code of `background.c` and adjusted it to fit into `color_profile.c`. Let me know if there are any issues.
=> commands/output/color_profile: allows use of relative path for ICC profile

include/sway/output.h, sway/desktop/output.c, sway/server.c
See https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4192
=> Use wlr_scene_set_gamma_control_manager_v1

sway/desktop/xdg_shell.c
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4788
=> xdg-shell: chase xdg_surface geometry updates

include/sway/config.h, sway/commands/output.c, sway/config.c, sway/config/output.c, sway/desktop/output.c
Slightly different approach from https://github.com/swaywm/sway/pull/8330, as per review comment.
=> config/output: Fix interaction with output management, take 2

sway/input/keyboard.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4775
Note, key repeat for motion is not yet implemented.
Simple way to test: `wtype -k Pointer_Right`
=> input/keyboard: add support for pointer keys

sway/desktop/output.c
This will be replaced with a proper solution later.
=> desktop/output: chase wlroots private fields update

sway/server.c
Depends on: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4858
=> sway/server: bind to presentation-time-v2

sway/desktop/output.c
Fixes an issue where the size of fullscreened views is wrong when using the Wayland or X11 backends.
It makes `request_state` no longer be a hacky side-channel and instead uses the configuration system, but at the cost of no longer being able to apply completely arbitrary output states through this path. This is not currently an issue as the path is only used for parent window resizes.
=> desktop/output: Store output config on request_state 

sway/config/output.c
The modeset logic iterates over all outputs at the end, sets their new position in the layout and takes a copy of its geometry that is later referenced by layout and scene management code.
If one output is auto configured, then a later output that is manually configured can lead to the first output being moved without the stored geometry being updated.
Split this into two passes: The first pass finalizes the output config and makes updates to the layout, while the second pass updates the copy of the geometry and arranges things as a result of it.
I unfortunately don't have a reproduction of the original issue.
=> config/output: Update output position in two passes

swaybar/tray/watcher.c
Emit property change signals for the `IsStatusNotifierHostRegistered` and `RegisteredStatusNotifierItems` properties in `StatusNotifierWatcher`, so code relying on the `PropertiesChanged` signal, instead of signals such as `StatusNotifierHostRegistered`, can work properly.
A library that is affected by this is the `libappindicator-gtk3`* library and it can cause tray icons to be missing after starting swaybar due to a race condition, as follows:
* An application using libappindicator-gtk3 starts, e.g. nm-applet.
* Some time later, swaybar starts.
* swaybar creates the `StatusNotifierWatcher`.
* libappindicator-gtk3 observes the new watcher, but it sees that `IsStatusNotifierHostRegistered`=`false`, so it falls back to the Freedesktop System tray protocol.
* swaybar creates the …
=> swaybar: Emit property changes for SNI watcher

sway/desktop/output.c
=> Repaint fixes

sway/input/libinput.c
=> input/libinput: fix builtin device detection logic

sway/commands/input/drag_lock.c
Regression introduced by by bbadf9b8b10d171a6d5196da7716ea50ee7a6062
=> input/libinput: fix parsing input drag_lock command

swaybar/render.c
The background color can be set individually for the different elements of the bar. If any of the backgrounds have transparency, we have to bail out from advertising an opaque surface.
Fixes: #8490
=> swaybar: Handle opaque region properly

sway/input/text_input.c, sway/tree/view.c
resolve: https://github.com/swaywm/sway/issues/8620
=>  text_input: Fix ime panic in ext-session-lock 

sway/main.c
This avoids calling non-async-signal-safe functions from within a signal handler.
=> Use wl_event_loop_add_signal for exit signals

include/sway/server.h, sway/commands/exit.c, swaymsg/main.c, swaynag/main.c
=> sway_terminate() cleanups

sway/input/seatop_down.c
=> input/seatop_down: Update decorations for touchscreen inputs

sway/input/text_input.c
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/5032
Fix #8718
=> input/text_input: chase wlroots update

include/sway/criteria.h, include/sway/server.h, include/sway/tree/view.h, sway/criteria.c, sway/desktop/xdg_shell.c, sway/ipc-json.c, sway/server.c, sway/sway-ipc.7.scd, sway/sway.5.scd, sway/tree/view.c
Ref https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/5026
=> Add support for xdg-toplevel-tag-v1

sway/server.c
Requires [wlroots!4685](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4685).
=> Add wl_fixes interface
